### ISSUE TITLE
How to select a nested Codable column?

### ISSUE THREAD

**Issue by shawnkoh** [groue/GRDB.swift#1000]
### What did you do?

```swift
struct Sketch: Identifiable, Codable, Hashable {
    let id: UUID
    var color: CodableColor
}

struct CodableColor: Codable, Hashable {
    /// 0-255
    var r: Int
    /// 0-255
    var g: Int
    /// 0-255
    var b: Int
    /// 0-1
    var a: Double

    init(r: Int, g: Int, b: Int, a: Double) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }
}
```

I'm trying to select only the color column of Sketch.

```swift
func retrieve(sketchId: Sketch.ID, db: Database) -> CodableColor? {
  try Sketch
    .filter(id: sketchId)
    .select(Column("color"), as: CodableColor.self)
    .fetchOne(db)
}
```

I understand from the documentation that GRDB stores it as a JSON string.

So I tried to decode it by conforming CodableColor to DatabaseValueConvertible, but to no avail.

```swift
extension CodableColor: DatabaseValueConvertible {
    public static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
        guard case let .string(text) = dbValue.storage else {
            return nil
        }

        let decoder = JSONDecoder()
        decoder.dataDecodingStrategy = .base64
        decoder.dateDecodingStrategy = .millisecondsSince1970
        decoder.nonConformingFloatDecodingStrategy = .throw
        return try? decoder.decode(CodableColor.self, from: text.data(using: .utf8)!)
    }
}
```

May I ask how should we go about retrieving nested Codable columns like this?

### What did you expect to happen?

Receive the nested Codable column.

### What happened instead?

`
GRDB/DatabaseValueConvertible+Encodable.swift:66: Fatal error: keyed encoding is not supported
`

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.8.0
**Installation method:** SPM
**Xcode version:** 12.5.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.4

**Comment by shawnkoh** [comment]
Bah! I was so close.
Solved it with

```swift
extension CodableColor: DatabaseValueConvertible {
    public var databaseValue: DatabaseValue {
        let encoder = JSONEncoder()
        let data = try! encoder.encode(self)
        let string = String(data: data, encoding: .utf8)!
        return string.databaseValue
    }

    public static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
        guard
            let string = String.fromDatabaseValue(dbValue),
            let data = string.data(using: .utf8)
        else {
            return nil
        }

        let decoder = JSONDecoder()
        return try? decoder.decode(CodableColor.self, from: data)
    }
}
```

On another note, may I know if this is actually the right way to handle nested codable columns?
Or, should we not even have nested codable columns to begin with?

**Comment by groue** [comment]
Hello @shawnkoh,

First, I'm glad you found a solution. It is correct: `DatabaseValueConvertible` is the protocol for decoding and encoding values.

A small advice: I would set `encoder.outputFormatting = .sortedKeys`, so that CodableColor is encoded in a stable way. This will prevent GRDB from thinking two colors are different when they are the same, whenever your app relies on some database-level equality check.

Now, your use case has not been a focus yet, so the ergonomics are clearly lacking. I'll take a closer look.

**Comment by groue** [comment]
(Note to myself: make it clear that whenever a type conforms to `DatabaseValueConvertible`, it is fully autonomous, and `EncodableRecord.databaseJSONEncoder(for:)` is never called. We may need to state this clearly in the documentation. Finally, see if we can provide a default `DatabaseValueConvertible` conformance for `Codable` types.)

**Comment by groue** [comment]
> So I tried to decode it by conforming CodableColor to DatabaseValueConvertible, but to no avail

What does "to no avail" mean? The first sample code you provide works pretty well.

> `GRDB/DatabaseValueConvertible+Encodable.swift:66: Fatal error: keyed encoding is not supported`

This error is about **encoding**, but everything else you wrote in the issue is about **decoding**.

---

I'm pretty much confused now. I think that you found a solution for your immediate issue, so I won't investigate further.

Please open *focused* issues in the future.

Meanwhile I'll try to see how I can help dealing with `DatabaseValueConvertible` that need JSON encoding.

**Comment by groue** [comment]
Next version of GRDB will automatically provide JSON encoding for Codable DatabaseValueConvertible value types. They will be stored as a JSON array or object when necessary.

**Comment by masterchiip** [comment]
> Next version of GRDB will automatically provide JSON encoding for Codable DatabaseValueConvertible value types. They will be stored as a JSON array or object when necessary.

Thanks @groue, how I can use the automatic JSON encoding provider?
My class extends `Codable` and `DatabaseValueConvertible` but I'm still asked to provide databaseValue.

**Comment by masterchiip** [comment]
For now I'm using this extension.

```swift
extension Encodable {
    func getDatabaseJSONValue() throws -> DatabaseValue {
        let encoder = JSONEncoder()
        encoder.outputFormatting = .sortedKeys
        let data = try encoder.encode(self)
        let string = String(data: data, encoding: .utf8)!
        return string.databaseValue
    }
}
```

**Comment by groue** [comment]
Hello @masterchiip,

It looks like my sentence was not quite precise enough. The support for JSON encoding of values is still incomplete, you are correct.

You can implement JSON support for your DatabaseConvertible type as follow:

```swift
extension MyValueType: DatabaseValueConvertible {
    var databaseValue: DatabaseValue {
        let jsonEncoder = JSONEncoder()
        jsonEncoder.outputFormatting = .sortedKeys
        let data = try! jsonEncoder.encode(self)
        let string = String(data: data, encoding: .utf8)
        return string.databaseValue
    }

    static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
        guard let string = String.fromDatabaseValue(dbValue) else { return nil }
        guard let data = string.data(encoding: .utf8) else { return nil }
        let jsonDecoder = JSONDecoder()
        return try? jsonDecoder.decode(Food.self, from: data)
    }
}
```

I still believe a future GRDB version _will_ do it for you ;-)

Also, you'll have to wait for GRDB6 in order to support encoding errors in `databaseValue`. Meanwhile, make sure your value type can be encoded as JSON.

**Comment by groue** [comment]
> It looks like my sentence was not quite precise enough. The support for JSON encoding of values is still incomplete, you are correct.

No @masterchiip, you made me doubt, but I'm not aware of anything that is currently missing.

DatabaseValueConvertible conformance can be fully derived from Codable (and it then encodes and decode a JSON column).

> I still believe a future GRDB version will do it for you ;-)

It's already done.

**Comment by masterchiip** [comment]
Thanks a lot, I was confused because the type I was working with can't automatically synthesis of 'encode(to:)' for protocol 'Encodable'. Thanks also for the fast reply!

**Comment by masterchiip** [comment]
> > It looks like my sentence was not quite precise enough. The support for JSON encoding of values is still incomplete, you are correct.
> 
> No @masterchiip, you made me doubt, but I'm not aware of anything that is currently missing.
> 
> DatabaseValueConvertible conformance can be fully derived from Codable (and it then encodes and decode a JSON column).
> 
> > I still believe a future GRDB version will do it for you ;-)
> 
> It's already done.

Thanks a lot, I was confused because the type I'm working with (GraphQLSelectionSet) can't automatically synthesis of `encode(to:)` for protocol `Encodable`. I ended up with this solution at the end. Thanks also for the fast reply!

```swift
extension GraphQLSelectionSet {
    func databaseJSONValue() -> DatabaseValue {
        do {
            let data = try JSONSerialization.data(withJSONObject: resultMap, options: [])
            let string = String(data: data, encoding: .utf8)!
            return string.databaseValue
        } catch {
            debugPrint("getDatabaseJSONValue failed \(error)")
            return "".databaseValue
        }
    }

    static func fromDatabaseJSONValue<T>(_ databaseValue: DatabaseValue) -> T? where T: GraphQLSelectionSet {
        guard let data = Data.fromDatabaseValue(databaseValue) else { return nil }

        do {
            if
                let dictionary = try JSONSerialization.jsonObject(with: data, options: []) as? [String: Any?],
                dictionary.isEmpty == false
            {
                return T(unsafeResultMap: dictionary)
            } else {
                return nil
            }
        } catch {
            debugPrint("fromDatabaseValue failed \(error)")
            return nil
        }
    }
}
```
