### ISSUE TITLE
How to filter array values?

### ISSUE THREAD

**Issue by HeebeLee** [groue/GRDB.swift#1003]
I have a variable tags, which is of type [string].

Now I want to get tags including "AAA" data from the database. Can I have a convenient filtering method?

`public typealias common = Codable & Identifiable & FetchableRecord & PersistableRecord`

thx

**Comment by groue** [comment]
Hello @HeebeLee,

It looks like you store your tags in a JSON column. Processing such JSON values at the SQL level is done via the [JSON1 extension](https://www.sqlite.org/json1.html).

GRDB does not provide any convenience Swift API for JSON1 yet. It looks like you will have to write a raw SQL request:

```swift
extension Player {
    /// The request for all players tagged with `tag`
    static func tagged(_ tag: String) -> SQLRequest<Player> {
        """
        SELECT player.*
        FROM player, json_each(player.tags)
        WHERE json_each.value = \(tag)
        """
    }
}

let players = try dbQueue.read { db in
    try Player.tagged("foo").fetchAll(db)
}
```

**Comment by HeebeLee** [comment]
> ```swift
>     static func tagged(_ tag: String) -> SQLRequest<Player> {
>         """
>         SELECT player.*
>         FROM player, json_each(player.tags)
>         WHERE json_each.value = \(tag)
>         """
>     }
> ```

It works for me, thank you.
