### ISSUE TITLE
How to improve the performance of large inserts of data

### ISSUE THREAD

**Issue by karthuszY** [groue/GRDB.swift#1004]
### What did you do?

- Insert over than 1000 data it's cost a lot of time

### What did you expect to happen?

How can i get it faster or batch insert?

### Environment

**GRDB flavor(s):** GRDB, SQLCipher
**GRDB version:** 5.8.0
**Installation method:** CocoaPods
**Xcode version:** Xcode 12.4
**Swift version:** Swift 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Big Sur 11.1

**Comment by groue** [comment]
Hello @karthuszY,

Make sure you group all your inserts in a single transaction:

```swift
// SLOW
for player in players {
  try dbQueue.write { db in
    try player.insert(db)
  }
}

// FASTER
try dbQueue.write { db in
  for player in players {
    try player.insert(db)
  }
}
```

If this is still too slow, see https://github.com/groue/GRDB.swift/issues/926
