### ISSUE TITLE
opening the database gives error 21 (library routine called out of sequence)

### ISSUE THREAD

**Issue by Yasihera** [groue/GRDB.swift#1006]
### What did you do?

try to open a database file

### What did you expect to happen?

database file should open

### What happened instead?

gives an error "21 (library routine called out of sequence)"

### Environment

Xcode 12.5 Swift

### Demo Project
             let str = "/Users/yasitha.herath/Library/Developer/CoreSimulator/Devices/137F4B78-3B9D-4C93-A1C3- 
              CE8D04C3BCBE/data/Containers/Data/Application/TRAINING01.db"
            var config = Configuration()
            config.readonly = true
            config.foreignKeysEnabled = true // Default is already true
            config.label = "MyDatabase"      // Useful when your app opens multiple databases
            config.maximumReaderCount = 10   // The default is 5
      do {
                let dbpool = try DatabasePool(path: str,configuration: config)
                grDB = dbpool
            } catch let error as DatabaseError  {
                print(error.resultCode)
            }

**Comment by groue** [comment]
Hello @Yasihera,

Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), thank you.

**Comment by Yasihera** [comment]
Thank you for the quick reply. Yes, this works in sample apps I created. But I can't connect the database in my project.   Does this have any effect from a project setting or effect of other frameworks in the project that may use sqlite3? The same database file can be open in sample apps without any issues. I tried to call the database connection inside Appdelegate file , and it also fails with the same error so I am assuming my other coding may not have a conflict with this since Appdelegate file fires before all other files.

**Comment by groue** [comment]
> Yes, this works in sample apps I created. But I can't connect the database in my project. 

So something is different in your project. What about finding out what it is? You'll solve your issue, or be able to write a proper bug report here.

**Comment by groue** [comment]
Also, search Google for SQLite error 21 (SQLITE_MISUSE) and "library routine called out of sequence". You may find out what kind of SQLite misuse is triggered by your application. I'm not aware of GRDB performing such a misuse on its own. As far as I can tell, your app does.

**Comment by Yasihera** [comment]
Hi groue

I found the issue caused to not to work GRDB in my project. I am using an arm64 embedded framework known as Foxit in my project 
https://developers.foxit.com/ 
Because of this, it causes GRDB to not work. Maybe GRDB will not work with other arm64 build frameworks embedded in the project(Not tested). However, GRDB will definitely not works with Foxit. Your Help or solution is much appreciated for this matter thank you.

**Comment by groue** [comment]
@Yasihera, I will not investigate this question. I'm not responsible for the problems introduced by the Foxit product.
