### ISSUE TITLE
How to auto binding struct variable and table column name

### ISSUE THREAD

**Issue by Chen-Michael** [groue/GRDB.swift#1007]
### What did you expect to happen?

My DBA used "snake case" in create the data table (e.g., group_id),

but we are used "camel case" in design the struct (e.g., groupId),

is there a scheme that can be auto binding two way?

I know can be use "encode(to:)" to binding column,

but there will be a lot of duplicate code in each model,

could you help me solution this problem?

**Comment by groue** [comment]
Hello @Chen-Michael 

it looks like you are asking for something like https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase and its encoding counterpart.

Those are not built-in GRDB. I would be interested in a pull request.

**Comment by Chen-Michael** [comment]
> Hello @Chen-Michael
> 
> it looks like you are asking for something like https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy and its encoding counterpart.
> 
> Those are not built-in GRDB. I would be interested in a pull request.

https://github.com/groue/GRDB.swift/pull/1008

Please let me know if there are any parts that have not been taken into consideration

**Comment by groue** [comment]
This issue describes a scenario where the library could help the user more, I agree. #1008 was not accepted, because it does not address the issue at the correct level. The correct solution is letting Codable record types customize how their coding keys are turned into column names.

**Comment by Chen-Michael** [comment]
> This issue describes a scenario where the library could help the user more, I agree. #1008 was not accepted, because it does not address the issue at the correct level. The correct solution is letting Codable record types customize how their coding keys are turned into column names.

I was inexpert in Swift, can't understand the correct solution you said

Sorry for wasting your time, hope someone can help solve this problem

**Comment by groue** [comment]
No worries, @Chen-Michael. You surely did not waste the time of anyone! Your idea is very good, and I too hope it eventually ships in the library. I'm right now focusing on shipping the improvements that are already developed, so I won't personally tackle your problem right now. Maybe someone else will, or I will do it later.

The current policy is to close issues that nobody is currently working on. So I will close this issue. I'll however add the "needs revisiting" flag, as a reminder that there's a good idea that is not yet addressed here.
