### ISSUE TITLE
Compiling with Xcode 8 beta 5 - error

### ISSUE THREAD

**Issue by swiftlyfalling** [groue/GRDB.swift#101]
@groue:

I cloned the Swift3 branch and tried building the `GRDBDemoiOS` project in Xcode 8 beta 5.

The build fails with `error: Reached end of file while looking for: uint32_t.` in the `CopySwiftLibs` phase.

(I experienced this error on an existing project and tried to narrow down the cause.)

Do you also experience this error on your machine?

**Comment by swiftlyfalling** [comment]
I literally spoke a moment too soon. 😄

Xcode 8 beta 6 was released today and resolves this `CopySwiftLibs` issue.

(It does, however, bring a lot more breaking changes to Swift 3.)

In any case, consider this issue closed.

**Comment by groue** [comment]
All right! Let's head to beta 6 :smile:

**Comment by groue** [comment]
@swiftlyfalling The Swift3 branch now targets Xcode 8 beta 6, but the GRDBDemoiOS app won't compile either. The Swift compiler crashes with Segmentation Fault: 11 while processing a deprecated SQLite function (and deprecated does not mean discontinued).

**Comment by swiftlyfalling** [comment]
@groue: Using the latest in the Swift3 branch, I had to fix up some remaining Xcode 8 beta 6 Swift changes in the GRDBDemoiOS project, but I was able to get GRDBDemoiOS to compile and run.

I do get a Swift stdlib tool warning now of:
`warning: /Users/username/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/GRDB.framework/Headers/GRDB-Bridging.h: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.`
in the CopySwiftLibs phase, but the demo app seems to compile and runs just fine in the Simulator?

Weird.

**Comment by swiftlyfalling** [comment]
@groue: And excluding `GRDB-Bridging.h` from the GRDBiOS target fixes that warning. 🙃

**Comment by groue** [comment]
Also, no Xcode 8 beta since beta 1 could test GRDB on OSX - they all fail with a weird linker error about missing libdispatch (wtf ?!).

Bugs everywhere. But I'm not too afraid (yet): I haven't really contributed to http://bugs.swift.org recently (bad, bad, bad me) since I only maintain the Swift3 branch in order to keep pace with Swift novelties, and be as ready as possible when Xcode 8 eventually ships. Not because I actually *run* Swift 3 code today.

Thus today GRDB's Swift3 branch is like the master branch of Swift - not fully tested. Are you actually developing an app with Swift 3 those days, @swiftlyfalling?

**Comment by swiftlyfalling** [comment]
@groue:

I've been doing something similar, keeping a separate branch of an app updated with the Swift3 changes, as they keep filtering in through each Xcode 8 beta. More than once, I have basically re-converted a few sections from scratch when they dropped a new batch of changes. 😄

I _believe_, as of Xcode 8 beta 6, almost all of the major breaking Swift 3.0 changes have landed in the Xcode betas. So hopefully there won't be too many other required changes before Xcode 8 GM.

**Comment by swiftlyfalling** [comment]
I took a look at testing on OSX. A few observations:

1. `SQLTableBuilderTests.swift` takes ages to compile in Xcode 8 beta 6.

2. I got an initial error of:

```
Code Coverage Data Generation Failed
Unable to retrieve the profile data files from 'My Mac'.
```

If I disable "Gather coverage data" in the scheme, I can get to the error you mentioned:

```
xctest[xxx] The bundle “GRDBTests” couldn’t be loaded. Try reinstalling the bundle.
xctest[xxx] (dlopen(/Users/user/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug/GRDBTests.xctest/Contents/MacOS/GRDBTests, 265): Symbol not found: _OBJC_CLASS_$_OS_dispatch_group
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug/GRDBTests.xctest/Contents/MacOS/GRDBTests (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/user/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug/GRDBTests.xctest/Contents/MacOS/GRDBTests)
Program ended with exit code: 83
```

However, if I then edit the **macOS Deployment Target** for the **GRDBOSXTests** target to **macOS 10.11**, I can get the tests to run.

**Comment by groue** [comment]
> SQLTableBuilderTests.swift takes ages to compile in Xcode 8 beta 6.

Yes. The table creation DSL makes Swift compiler crazy. I did notice that but did not yet understand how. The know weakness of swiftc is type inference. But there's no overload or type inference in the following innocuous-looking piece of code that reveals so hard to compile:

```swift
db.create(table: "foo") { t in
    t.column("id", .Integer).primaryKey()
}
```

**Comment by swiftlyfalling** [comment]
So this is weird. I am able to significantly reduce the compilation time of `SQLTableBuilderTests.swift` by making changes to the String concatenation in the XCTAsserts.

For example:
```swift
XCTAssertEqual(self.lastSQLQuery,
                    "CREATE TABLE \"test\" (" +
                        "\"a\" INTEGER NOT NULL, " +
                        "\"b\" INTEGER NOT NULL, " +
                        "\"c\" INTEGER NOT NULL ON CONFLICT ROLLBACK, " +
                        "\"d\" INTEGER NOT NULL ON CONFLICT FAIL, " +
                        "\"e\" INTEGER NOT NULL ON CONFLICT IGNORE, " +
                        "\"f\" INTEGER NOT NULL ON CONFLICT REPLACE" +
                    ")")
```
to:
```swift
XCTAssertEqual(self.lastSQLQuery,
                    ("CREATE TABLE \"test\" (" +
                        "\"a\" INTEGER NOT NULL, " +
                        "\"b\" INTEGER NOT NULL, " +
                        "\"c\" INTEGER NOT NULL ON CONFLICT ROLLBACK, " +
                        "\"d\" INTEGER NOT NULL ON CONFLICT FAIL, " +
                        "\"e\" INTEGER NOT NULL ON CONFLICT IGNORE, " +
                        "\"f\" INTEGER NOT NULL ON CONFLICT REPLACE" +
                    ")") as String)
```
I made that change to all of them, and the file compiles much faster.

**Comment by groue** [comment]
@swiftlyfalling, thanks :-) I was totally misled !
