### ISSUE TITLE
Error while creating a request with association

### ISSUE THREAD

**Issue by mohitnandwani** [groue/GRDB.swift#1011]
I recently discovered this library and I'm really enjoying it. I got into some problems while trying to create a joined request.

### What did you do?

I created two tables:

```
try db.create(table: "item", body: { td in
    td.column("id", .text).primaryKey()
    td.column("name", .text).indexed()
    td.column("folderId", .text).indexed().references("folder", column: "id", onDelete: .cascade)
})
try db.create(table: "folder", body: { td in
    td.column("id", .text).primaryKey()
    td.column("name", .text).indexed()
})
```

Then I created the model for both the tables and updated the code in ```Item``` record to include foreign key:

```
extension Item: Codable, FetchableRecord, MutablePersistableRecord {
    static let folderForeignKey = ForeignKey(["folderId"])
    static let folder = hasOne(Folder.self, using: folderForeignKey)
    
    var folder: QueryInterfaceRequest<Folder> {
        request(for: Item.folder)
    }
}
```

After that, I wrote the following code to create request to fetch ```items``` with/without their optional ```folder```:

```
struct ItemsList: FetchableRecord, Decodable {
    var item: Item
    var folder: Folder?
}

let request = try Item.all()
                    .including(optional: Item.folder)
                    .asRequest(of: ItemList.self)
                    .fetchAll(db)
```

### What did you expect to happen?

To fetch all ```items``` with/without folders using the ```folderId``` foreign key.

### What happened instead?

I got this error:

```
SQLite error 1: no such column:
folder.folderId - while executing `SELECT "item".*, "folder".*
FROM "item" LEFT JOIN "folder" ON "folder"."folderId" = "item"."id"
```

I'm new to this and I don't really know why the keys are getting swapped here. Would really appreciate your help.

### Environment

**GRDB flavor(s): GRDB**
**GRDB version: 5.8.0**
**Installation method: SPM**
**Xcode version: 12.5**
**Swift version: 5.4**
**Platform(s) running GRDB: iOS**
**macOS version running Xcode: 11.4**

**Comment by groue** [comment]
Hello @mohitnandwani,

The error is a SQLite error, which refuses to run the SQL generated by GRDB according to the request definition.

Since your database schema defines a foreign key (`references(...)`), you can let GRDB infer the foreign key for you:

```
extension Item {
    static let folder = belongsTo(Folder.self)
}
```

This should fix your request.

Note that you have to use `Item.belongsTo` instead of `Item.hasOne`, because it is Item that has the column which points to the other table.

**Comment by mohitnandwani** [comment]
Hey @groue :) Thanks for such quick response. This did fix the issue. Although I'm unable to get any folder value from the ```ItemsList``` while the folder is present in the db. Thanks again!

**Comment by mohitnandwani** [comment]
Okay, Figured it out! 

> Association keys should match property names

This fixes it! Thanks again! :)
