### ISSUE TITLE
Browsing DB file from the simulator gives me an empty db.

### ISSUE THREAD

**Issue by glennposadas** [groue/GRDB.swift#1014]
### What did you do?

- I'm trying to browse the data in the db file of my simulator after inserting some data. I use DB Browser for SQLite, and SimSim to go to the path of the resources and stuff of a simulator.

### What did you expect to happen?

- I'm expecting to browse the inserted data in the db browser.

### What happened instead?

I see nothing, no data in the db. no tables either.

Similar issue: https://github.com/groue/GRDB.swift/issues/879

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 572
**Installation method:** SPM
**Xcode version:** 12.5.1
**Swift version:** 5.4.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:** 11.0.1

Thanks!

**Comment by groue** [comment]
Hello @glennposadas,

I'm not aware of any problem in this library, and the way you reported your issue does not provide anyone with the beginning of an idea of what is happening.

If you need support from here, I suggest you provide much more positive evidence of a GRDB issue. And maybe you'll find a DB Browser issue instead, who knows?

**Comment by glennposadas** [comment]
Hi @groue. Thank you. Maybe this really isn't a GRDB issue, but what I just wanted to do is basically browse my data using any SQLite UI browser. How about rephrasing my concern.

How can we see the data in our db file in this sample app of the GRDB? https://github.com/groue/GRDB.swift/blob/master/Documentation/DemoApps/GRDBDemoiOS/GRDBDemoiOS/Persistence.swift

Like the other guy in the other ticket, I can easily find the `db.sqlite` file in my simulator folders but it's basically empty.

**Comment by glennposadas** [comment]
<img width="782" alt="Screen Shot 2021-07-24 at 2 58 30 AM" src="https://user-images.githubusercontent.com/12502679/126828867-7f38d4fb-a173-4487-ae6e-d900ab505f5d.png">
<img width="864" alt="Screen Shot 2021-07-24 at 2 59 38 AM" src="https://user-images.githubusercontent.com/12502679/126828976-a6cf436e-a10b-4ca3-83d6-f1e1e795b688.png">


In the `Persistence.swift` file of the demo app of GRDB, I added a print statement there for printing the db.sqlite file location. Once I got it, I tried browsing the db file but it's empty.

**Comment by StuClift** [comment]
You'll probably find all your data is in the WAL and hasn't been checked into the main file yet. It may be enough to just open the file with sqlite `sqlite3 db.sqlite` to trigger this but you may have to execute a vacuum or a checkpoint operation.

**Comment by glennposadas** [comment]
Thank you so much, @StuClift. Because of your comment, I went to the EDIT PRAGMAS, and only then I realized what I've been doing wrong: I duplicate the db file and paste the copy/duplicate of that file to my desktop - that’s how and when the data get lost.

Now, what I did is I opened up the sqlite file directly from the simulator folder, and voila. Everything’s in there. Solved!
