### ISSUE TITLE
Documentation needed on 'impure' functions?

### ISSUE THREAD

**Issue by guidedways** [groue/GRDB.swift#1016]
It's not clear what `pure` does to a custom function. It would be nice to have an example with `pure: false` so we can see what that means. When is the result of a function not purely the function of its arguments?

**Comment by groue** [comment]
Hello @guidedways 

See https://www.sqlite.org/c3ref/create_function.html for a longer discussion ("pure" functions are called "deterministic" in the SQLite documentation).

A function is not pure or deterministic when it does not always return the same value for the same input. 

For example, a function which returns the current date is not pure. A function which returns a random number is not pure. Etc.
