### ISSUE TITLE
Build error in Xcode 13 beta 4

### ISSUE THREAD

**Issue by guidedways** [groue/GRDB.swift#1020]
Using the latest version of GRDB. Won't build with the following error:

`Enum cases with associated values cannot be marked potentially unavailable with '@available'`

above:

`case profile(statement: Statement, duration: TimeInterval)`, line 1594 in `Database.swift`

**Comment by groue** [comment]
Please see #984

**Comment by guidedways** [comment]
@groue thank you. Got the development branch compiling, however any test target (of the app) refuse to compile due to strange errors related to Combine. This could be a configuration issue, however I've set my target OS to iOS 13, plus as I said, the app itself compiles just fine.

Could be a compiler bug as the error describes:

`Failed to build module 'Combine' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug`

above this:

```
#if canImport(Combine)
/// A namespace for database Combine publishers.
@available(OSX 10.15, iOS 13, tvOS 13, watchOS 6, *)
public enum DatabasePublishers { }
#endif
```

**Comment by guidedways** [comment]
FYI

<img width="893" alt="Screenshot 2021-07-30 at 22 55 20@2x" src="https://user-images.githubusercontent.com/202437/127699191-0abb6a20-7e78-4893-8269-0c1047bcb8e6.png">

**Comment by guidedways** [comment]
Okay - a little weird. One of my frameworks that use GRDB was set to deploy for iOS 11.0. This particular framework does not use iOS 13 related features / combine, only the main app does. Bumping the framework's deployment target to iOS 13 fixed this for me.

This still isn't expected. I've logged this as a bug with Apple as I believe this is an Xcode issue.

**Comment by gcox** [comment]
In case anyone else encounters the Combine related build errors shown in @guidedways' screenshot: https://github.com/Alamofire/Alamofire/issues/3481#issuecomment-891470443
