### ISSUE TITLE
Exotic build combining FTS5, SQLCipher, and GRDBCustom (and possibly other modules heretofore undetermined)

### ISSUE THREAD

**Issue by ManheimGreen** [groue/GRDB.swift#1021]
Is it possible to combine all of these? Is it reasonably achievable?

Alternatively, would you recommend that I compile a version of SQLite separately and then embed it in the project in a "dumb" fashion?

Alternatively alternatively, would it be possible to use the SQLite Encryption Extension? And would you recommend doing so?

Thanks.

P.S. Where can I find a thorough introduction to the Xcode build process? The search engines are nigh-useless these days…

### Environment

**GRDB flavor(s):** GRDB _plus_ FTS5 _plus_ SQLCipher (local)
**GRDB version:** any latest
**Installation method:** manual
**Xcode version:** Xcode 13
**Swift version:** any latest
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 12.0

**Comment by groue** [comment]
Hello @ManheimGreen,

The supported ways to build GRDB are all documented in the main  README. If you have one specific question, feel free to open another issue. This one is just too general.

**Comment by ManheimGreen** [comment]
Pardon the delay. I've been disgustingly busy.

I searched and searched and eventually found a reasonably thorough piece on the Xcode build process: https://www.cocoanetics.com/2020/10/adding-swift-package-manager-support

This is probably a good jumping-off point if someone wants to do as I wanted to do. It would still be nice to combine FTS5, SQLCipher, and GRDBCustom, but they are not critical to my project for now. Even FTS5 alone wouldn't work... reproducible, fatal errors on subsequent mutations to the indexed table... probably something related to synchronization triggers. Will revisit later.

Thanks.
