### ISSUE TITLE
Is There some way to set union primary key

### ISSUE THREAD

**Issue by SymBooler** [groue/GRDB.swift#1022]

**Comment by groue** [comment]
What is "union primary key"?

**Comment by SymBooler** [comment]
raw create sql like this:
CREATE TABLE something (
  column1, 
  column2, 
  column3, 
  PRIMARY KEY (column1, column2)
);

**Comment by groue** [comment]
Sure, this is documented in the [Create Tables](https://github.com/groue/GRDB.swift/blob/master/README.md#create-tables) chapter:

> ```swift
> // PRIMARY KEY (a, b),
> t.primaryKey(["a", "b"])
> ```

So this gives:

```swift
try db.create(table: "something") { t in
    t.column("column1")
    t.column("column2")
    t.column("column3")
    t.primaryKey(["column1", "column2"])
}
```

Remember you can always fallback to raw SQL when you don't have time reading the documentation:

```swift
try db.execute(sql: """
    CREATE TABLE something (...)
    """)
```
