### ISSUE TITLE
Multi-column primary key where parts can be nil leads to (for me) an unexpected error when saving a record

### ISSUE THREAD

**Issue by tamc** [groue/GRDB.swift#1023]
### What did you do?

I have a record that will have either a local ID, or a remote ID, or maybe both, but never none. The SQL for the record is something like:

```sql
CREATE TABLE maybeRemoteMaybeLocalID (
    localID INT UNIQUE,
    remoteID INT UNIQUE,
    thing TEXT NOT NULL,
    PRIMARY KEY (localID, remoteID),
    CONSTRAINT check_primary CHECK (localID IS NOT NULL OR remoteID IS NOT NULL)
)
```

With this sort of record:
```swift
struct MaybeRemoteMaybeLocalID : Codable, MutablePersistableRecord, FetchableRecord {
    let localID: UInt64?
    let remoteID: UInt64?
    var thing: String
}
```

Inserting the record is fine, but when I do an update along these lines, an error is thrown:

```swift
var record = try MaybeRemoteMaybeLocalID(localID: 1, remoteID: nil, thing: "Local One")
try record.insert(db) // Ok
record.thing = "Local One Updated"
try record.update(db) // Unexpected error
```

### What did you expect to happen?

I expected the record to update.

### What happened instead?

An error was thown: ```Key not found in table maybeRemoteMaybeLocalID: [localID:1 remoteID:NULL]```

The cause seems to be that the code generates SQL like:

```sql
UPDATE ... WHERE "localID"=1 AND "remoteID"=NULL
```

Where I was expecting it to generate SQL like:

```sql
UPDATE ... WHERE "localID"=1 AND "remoteID" IS NULL
```

### Environment

**GRDB flavor(s):** Vanila GRDB
**GRDB version:** Development
**Installation method:** SPM
**Xcode version:** 13 Beta 4
**Swift version:** 5.5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) iOS, Mac OS
**macOS version running Xcode:** Big Sur

### Demo Project

Failing test ```testUpdate()``` in https://github.com/tamc/GRDB.swift/blob/bd53c830f2a6b90ebd4b20a3e39c31080b60f30f/Tests/GRDBTests/RecordPrimaryKeyMultipleSomeNilTests.swift

### Workarounds

In case others hit this, it can be worked around by being a bit more manual

e.g., 

```swift
try MaybeRemoteMaybeLocalID.filter(Column("localID") == 1).updateAll(db, [Column("thing").set(to: "Local One Updated")
```

### Comment / Question

I'm not an expert in SQL, so maybe a primary key where one or more columns can be null is against the spec, even though it seems to work? Or maybe it isn't against the spec, but that the consequences of swopping ```key = NULL``` to ```key IS NULL``` would be unexpected to experts because NULL never matches NULL in SQL?
 
Grateful for any guidance you have on that before I attempt to dig into GRDB to fix.

**Comment by groue** [comment]
Hello @tamc,

Using NULL in primary keys is indeed begging for trouble. Quoting the [SQLite documentation](https://www.sqlite.org/lang_createtable.html#the_primary_key):

> According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. 

Since SQLite itself _allows_ NULL in primary keys, GRDB should accept this non-standard practice as well. At least when it does not create problems.

In your specific case, updating would not create any problem, so there is no reason not supporting it. You just happen to be the first GRDB user who wants NULL in primary keys, and I'm sorry this specific case was not explicitly tested. A future GRDB version will fix this error.

Now, I know some other parts of GRDB, especially around _associations_, will not play nicely with NULLs in primary keys. We may discuss those cases later if you happen to meet another undesired behavior.

> Grateful for any guidance you have on that before I attempt to dig into GRDB to fix.

I'm currently in vacations and far away from any computer. I'm sure you won't have much difficulty locating this particular piece of code in GRDB. Otherwise, please way until next week until I come back.

**Comment by tamc** [comment]
Thank you @groue. I think I spotted where to make the changes and have created a pull request #1024. Grateful for feedback.

Given:

> Using NULL in primary keys is indeed begging for trouble.

Then I'm considering a re-think on my table and doing something like: 

```sql
CREATE TABLE maybeRemoteMaybeLocalID (
    id INT PRIMARY KEY AUTOINCREMENT
    localID INT UNIQUE,
    remoteID INT UNIQUE,
    thing TEXT NOT NULL,
    CONSTRAINT check_primary CHECK (localID IS NOT NULL OR remoteID IS NOT NULL)
)
```

Even though I won't actually be using the primary key much (at all?) in my code, it will make it clear that what I'm really doing, 
which is is taking two sources of truth and merging them.

The two sources are:
1. Local things, from a different table in the app, that will always have a local id but where we might not know the remote id.
2. Remote things, from an API, that will always have a remote id and might have a local id if they have been uploaded by this copy of the app

The merge process is to create a merged list of the remote and local things, without any duplicates, with whichever is the most updated version appearing in the table.

Which has made me realise that, because the merged records may not actually be identical with either the local or the remote things (because of the merge process) the merged records should be thought of as a third thing with their own id, distinct from the local and remote ids, even though in practice that id will not appear much in the code.

I probably haven't explained that clearly enough. But if you think you can grasp what I'm on about and it worries you in some way, then I'd be grateful for your thoughts.

**Comment by groue** [comment]
> Then I'm considering a re-think on my table and doing something like:

I think this is better design indeed 👍

> [...] because the merged records may not actually be identical with either the local or the remote things (because of the merge process) the merged records should be thought of as a third thing with their own id, distinct from the local and remote ids, even though in practice that id will not appear much in the code.

Merging local and remote objects is a frequent need :-) If the `id`column is unused eventually, you'll be able to remove it completely, because SQLite does not need one (tables without explicit primary key use an implicit one: the hidden rowid column).

**Comment by groue** [comment]
Closing in favor of #1024
