### ISSUE TITLE
Release build crashes around `reducer` in `ValueObserver`

### ISSUE THREAD

**Issue by mattgallagher** [groue/GRDB.swift#1026]
The Drawboard Projects app has been seeing significant crashes around its GRDB code since moving from Xcode 12.4 to Xcode 12.5 (these crashes continue in Xcode 13). We've reproduced this problem with GRDB 5.6 and 5.8 (pulled via Swift Package Manager).

The most common crash looks like this:

<img width="745" alt="Screen Shot 2021-08-06 at 9 38 58 am" src="https://user-images.githubusercontent.com/28080/128434729-e5258e73-0b94-4a43-81c9-a3cba8806cd4.png">

However, there are a handful of additional crash locations in related parts of `ValueObserver` and a couple downstream crashes. The most common crashes (as shown above) occur at a points when `reducer` – or a closure that captures `reducer` – is accessed or released. A couple less common crashes appear to occur when data that has passed through the `reducer` is subsequently accessed. These crashes affect only Release builds. They can occur on iOS (Arm64) or macOS (x86_64).

The bug is *not* easy to reproduce. Our reproduction involves a `ValueObserver` `fetch`/`filter`/`removeDuplicates` pipeline and then writing new rows 50ms apart and then it takes a few hundred transactions (sometimes a few thousand) before an issue occurs. The timing is tricky. Produce transactions too fast and libdispatch is flooded (preventing the crash). Produce too slowly and there's not enough contention (avoiding the crash). The problem occurs with both `DatabasePool` and `DatabaseQueue`. Despite the difficulty of reproduction, we are seeing hundreds of crashes per week due to this issue across our user base.

Based on a slow process of elimination, we believe that the "fewer retain/release calls" mentioned in the [Swift 5.4 release notes](https://swift.org/blog/swift-5-4-released/) has exposed thread unsafety around the `reducer` property on `ValueObserver`.

I have prepared a PR which shows the mitigation we are applying to our own code https://github.com/groue/GRDB.swift/pull/1025. This does fix our crash but since we are not intimately familiar with the internal threading model of GRDB, there's probably a better way to apply this.

There's also a possibility that we've misread the cause and this mitigation only fixes the problem by coincidence, however, we've tried to test a range of alternate theories and this is the only approach that has worked. It is conceivable that this is simply a Swift 5.4+ compiler bug and all we've done is mitigate that – although we consider that unlikely since it wouldn't be affected by timing in the same way.

**Comment by groue** [comment]
Hello @mattgallagher,

Thank you for your report :-) I'm glad you could find a workaround. I'll come back in a few days.

**Comment by groue** [comment]
@mattgallagher, thank you very much for putting so much effort analyzing and fixing this problem. I close this issue in favor of #1025.

**Comment by groue** [comment]
The fix has shipped in [v5.9.0](https://github.com/groue/GRDB.swift/tree/v5.9.0).
