### ISSUE TITLE
Wrong-thread access crash when GRDB in different target

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1031]
### What did you do?

Our app uses GRDB in the primary app target. We created a separate target (`MyAppPersistence`) and moved all of the abstraction of GRDB and the dependency itself to it. We basically did nothing but changing the target membership of those files. 

Once I do that, and use the framework instead of using the files in the primary target, I crash with the following error:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/605076/129354060-10acef7f-0bec-4448-ba99-387203771c02.png">

The message doesn't show what is the "correct" thread and what isn't so I'm not entirely sure how to debug this. Also, the code itself hasn't changed at all except for moving to a separate target.

### What did you expect to happen?

Same behavior as contained within the primary target

### What happened instead?

Crash with incorrect thread

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.8.80
**Installation method:** Cocoapods
**Xcode version:** 12.5
**Swift version:** 5.x
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Big Sur

### Demo Project

I tried to repro this on a blank project but wasn't able to, yet. This strengthens my belief that I am indeed doing something wrong in my "real" project but I can't put my finger on it, since we didn't make any functional changes to the code aside for moving it to a separate library. 

If you could share some thoughts on how to debug this, or what could cause that crash so I can investigate on our side, that would be amazing.

**Comment by freak4pc** [comment]
Some more interesting information here, I put a print around the `preconditionValidQueue` assertion and `current` is coming back as `nil`. I'm not entirely familiar with the codebase to know what `current` is - perhaps you have a thought? @groue 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/605076/129364399-409d340e-db6d-4d24-89c6-fe229add376c.png">

**Comment by groue** [comment]
Sure, it's defined two lines below: https://github.com/groue/GRDB.swift/blob/v5.8.0/GRDB/Core/SchedulingWatchdog.swift#L55

**Comment by freak4pc** [comment]
Yup, I can find the definition :) I just don't entirely understand what it does or how it works. I tried to follow the breadcrumbs there but it's a bit too convoluted for me with my knowledge of GRDB internals. I'll keep digging, but if something comes to mind I'll appreciate it. 

Thanks again.

**Comment by groue** [comment]
Each dispatch queue used for database access has an attached SchedulingWatchdog (in a dispatch queue specific). This watchdog knows which databases can run on this dispatch queue.

`current` returns the SchedulingWatchdog attached to the current dispatch queue. If nil, this dispatch queue was not created for database access, and it is a programmer error to access the database from this queue (boom). If not nil, then we check if the database is in the list of allowed ones. If not, this is a programmer error (boom).

The list of allowed databases can grow:

```swift
try dbQueue1.write { db1 in
    // On dispatch queue 1, db1 allowed
    try dbQueue2.write { db2 in
        // On dispatch queue 2, db1 and db2 allowed
        ...
    }
}
try dbQueue2.write { db2 in
    // On dispatch queue 2, db2 allowed
    ...
}
```

**Comment by freak4pc** [comment]
Thanks, that's helpful. 
Given there is only a single dbQueue (Held by a singleton), could this even happen theoretically speaking?

**Comment by groue** [comment]
No, @freak4pc, I really don't know what's happening. Since the database connection could be created, this watchdog has worked (the initial database setup is performed under its supervision). I really don't know how the watchdog can eventually vanish (turn nil).

Could it be that you have _two_ versions of GRDB linked, and two keys are used in a conflicting way?

**Comment by freak4pc** [comment]
I'm wondering if it could be related to some framework linking shenanigans (I'll look, interesting if it is).

What's a normal way of "printing" the underlying key ? Seems like it only has an initializer and a very non-description `description` that prints the same string for every key.

**Comment by groue** [comment]
`DispatchSpecificKey` is a class: you'll get its identity through [`ObjectIdentifier`](https://developer.apple.com/documentation/swift/objectidentifier).

**Comment by freak4pc** [comment]
The issue was indeed related to bad linking. Sorry for wasting your time, but it was fun learning a bit about how this mechanism works :) 

<a href="https://www.computerhope.com/jargon/p/pebkac.htm"><img src="https://user-images.githubusercontent.com/605076/129382166-fb0e5c8a-3f99-4102-98b1-6de400fb03c0.png" /></a>

**Comment by groue** [comment]
Great, @freak4pc! One less question in our clueless life 😉
