### ISSUE TITLE
DatabaseUUIDEncodingStrategy does not work as advertised 

### ISSUE THREAD

**Issue by jbuchman** [groue/GRDB.swift#1032]
### What did you do?

Create a table definition with UUIDs written as Strings so they can be read by common SQLite tools

`static let databaseUUIDEncodingStrategy = DatabaseUUIDEncodingStrategy.string`

### What did you expect to happen?

I expected that filter would be able to load the rows by UUID

### What happened instead?

No records found when filtering by UUID

### Environment

**GRDB flavor(s):** Standard GRDB
**GRDB version:** 5.3.0
**Installation method:** SPM
**Xcode version:** 12.5.1
**Swift version:** Swift 5
**Platform(s) running GRDB:** iOS / macOS
**macOS version running Xcode:** 11.5.1

### Demo Project

```
import GRDB

var configuration = Configuration()
configuration.prepareDatabase { db in
    db.trace { print("SQL> \($0)") }
}
let dbQueue = DatabaseQueue(configuration: configuration)

var migrator = DatabaseMigrator()

migrator.registerMigration("createLibrary") { db in
    try db.create(table: "author") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
        t.column("uuid", .text).notNull()
    }
}

try migrator.migrate(dbQueue)

struct Author: Codable, FetchableRecord, MutablePersistableRecord {
    static let databaseUUIDEncodingStrategy = DatabaseUUIDEncodingStrategy.string

    var id: Int64?
    var uuid: UUID
    var name: String
}

let uuid = UUID()
try dbQueue.write { db in
    var author = Author(id: nil, uuid: uuid, name: "Hermann Melville")
    try author.insert(db)
}

try dbQueue.read { db in
    if let author = try Author.filter(Column("uuid") == uuid).fetchOne(db) {
        print(author)
    } else {
        print("Unable to find author by UUID!")
    }
}
```

<pre>
SQL> SELECT * FROM sqlite_master LIMIT 1
SQL> SELECT type, name, tbl_name, sql, 0 AS isTemporary FROM sqlite_master UNION SELECT type, name, tbl_name, sql, 1 FROM sqlite_temp_master
SQL> CREATE TABLE IF NOT EXISTS grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)
SQL> PRAGMA foreign_keys
SQL> PRAGMA foreign_keys = OFF
SQL> BEGIN IMMEDIATE TRANSACTION
SQL> CREATE TABLE "author" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "uuid" TEXT NOT NULL)
SQL> INSERT INTO grdb_migrations (identifier) VALUES ('createLibrary')
SQL> PRAGMA foreign_key_check
SQL> COMMIT TRANSACTION
SQL> PRAGMA foreign_keys = ON
SQL> BEGIN DEFERRED TRANSACTION
SQL> SELECT * FROM pragma_table_xinfo('author') WHERE hidden IN (0,2,3)
SQL> -- PRAGMA table_xinfo='author'
<b>SQL> INSERT INTO "author" ("id", "uuid", "name") VALUES (NULL,'1235FABC-1E07-4321-B924-525EC1D825F3','Hermann Melville')</b>
SQL> COMMIT TRANSACTION
SQL> PRAGMA query_only = 1
SQL> SELECT type, name, tbl_name, sql, 0 AS isTemporary FROM sqlite_master UNION SELECT type, name, tbl_name, sql, 1 FROM sqlite_temp_master
SQL> PRAGMA index_list("author")
<b>SQL> SELECT * FROM "author" WHERE "uuid" = x'1235fabc1e074321b924525ec1d825f3' LIMIT 1</b>
Unable to find author by UUID!
SQL> PRAGMA query_only = 0
</pre>

**Comment by jbuchman** [comment]
Nevermind, user error discovered

**Comment by groue** [comment]
Hell @jbuchman. This behavior is indeed documented in [Date and UUID Coding Strategies](https://github.com/groue/GRDB.swift#date-and-uuid-coding-strategies). But your expectation was reasonable :-)

**Comment by groue** [comment]
> ```swift
> try dbQueue.read { db in
>     if let author = try Author.filter(Column("uuid") == uuid).fetchOne(db) {
>         print(author)
>     } else {
>         print("Unable to find author by UUID!")
>     }
> }
> ```

GRDB v5.13.0 has shipped an improvement. The following requests will now encode uuids according to the record strategy (data blob or string, lowercase or uppercase):

```swift
try Author.fetchOne(db, key: uuid)
try Author.deleteOne(db, key: uuid)
try Author.filter(key: uuid).fetchOne(db)
try Author.fetchAll(db, keys: [uuid, ...])
try Author.deleteAll(db, keys: [uuid, ...])
try Author.filter(keys: [uuid, ...]).fetchAll(db)

// For record types that conform to Identifiable
try Author.fetchOne(db, id: uuid)
try Author.deleteOne(db, id: uuid)
try Author.filter(id: uuid).fetchOne(db)
try Author.fetchAll(db, ids: [uuid, ...])
try Author.deleteAll(db, ids: [uuid, ...])
try Author.filter(ids: [uuid, ...]).fetchAll(db)
```

Those are all requests for single-column primary keys, written with a `key:`, `keys:`, `id:`, or `ids:` argument.

All other requests, such as those written as `filter(Column("uuid") == uuid)`, will continue to ignore the record encoding. See the [updated documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-uuid-coding-strategies).
