### ISSUE TITLE
Filtering empty association

### ISSUE THREAD

**Issue by kiarashvosough1999** [groue/GRDB.swift#1039]
### What did you do?

I was trying to filter the association which does not contain any row

### What did you expect to happen?

I expect that the array which the association set its value, be empty.
I even try tp use having and using isEmpty in associations but It an error occurred 'Not implemented: join an association with a GROUP BY clause'

### Environment

**GRDB flavor(s):GRDB
**GRDB version: lastest version
**Installation method:CocoaPods
**Xcode version: 12
**Swift version: 5
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 11.4

### Demo Project

```
FoodGroupParentSQLEntity
                    .all()
                    .including(all: FoodGroupParentSQLEntity
                                .childFoods
                                .forKey("childFoodItems")
                                .including(all: FoodGroupChildSQLEntity
                                            .foods
                                            .filter(Column("name").like("%\(text)%"))
                                            .forKey("foodsItems")
                                            .including(all:
                                                        FoodSQLEntity.foodCalorie
                                                        .order(FoodCalorieSQLEntity.Columns.id)
                                                        .forKey("calorieItems")
                                            )
                                            
                                )
                    )
                    .fetchAll(db)
```
I wanted that the "childFoodItems"t to be empty when the "foodsItems" becomes empty if the  .filter(Column("name").like("%\(text)%")) condition does not satisfy.

**Comment by groue** [comment]
Hello @kiarashvosough1999,

`parent.including(all: children)` has no effect on the number of parents. In your case, all "childFoodsItems" will be there, and some will have an empty "foodsItems" array.

In order to filter out parents that do not have any children, you need `parent.having(!children.isEmpty)`. See [Association Aggregates](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#association-aggregates) for more information.

This should give (untested):

```swift
let calorieItems = FoodSQLEntity
    .foodCalorie
    .order(FoodCalorieSQLEntity.Columns.id)
    .forKey("calorieItems")

let foodsItems = FoodGroupChildSQLEntity
    .foods
    .filter(Column("name").like("%\(text)%"))
    .forKey("foodsItems")

let childFoodItems = FoodGroupParentSQLEntity
    .childFoods
    .forKey("childFoodItems")

let foodGroupParents = try FoodGroupParentSQLEntity
    .including(all: childFoodItems
                .including(all: foodsItems.including(all: calorieItems))
                .having(foodsItems.isEmpty == false) // <----
    )
    .fetchAll(db)
```

**Comment by groue** [comment]
> I even try tp use having and using isEmpty in associations but It an error occurred 'Not implemented: join an association with a GROUP BY clause'

Oops, sorry @kiarashvosough1999. Does my sample code above suffer with the same problem?

**Comment by groue** [comment]
> Does my sample code above suffer with the same problem?

If you see an error, then this should be a workaround (give another key to the aggregated association):

```swift
let foodGroupParents = try FoodGroupParentSQLEntity
    .including(all: childFoodItems
                .including(all: foodsItems.including(all: calorieItems))
                .having(foodsItems.forKey("foodsItems2").isEmpty == false) // <----
    )
    .fetchAll(db)
```

Please tell which of the above suggestions fails or succeeds. We may infer ideas for GRDB enhancements from your feedback.

**Comment by kiarashvosough1999** [comment]
Hello groue,

The first answer is working and it is what I wanted to achieve.

Thank you for your quick support.

**Comment by kiarashvosough1999** [comment]
hello again

I was trying to filter the parentGroups which has no foods inside its childGroups as the same way, but It did not filter (I try several ways by calling having and joining association inside having),

```
try FoodGroupParentSQLEntity
                    .including(all: childFoodItems
                                .including(all: foodsItems.including(all: calorieItems))
                                .having(foodsItems.isEmpty == false)
                    ) /// code work until here
                    .having(childFoodItems.forKey("foodsItems").isEmpty == false) // this line it seems not affect anything
                    .fetchAll(db)
```

this code seems to be logical and working but It does not.

**Comment by groue** [comment]
@kiarashvosough1999, I recommend that you activate database tracing:

```swift
db.trace { print($0) }
let values = try myRequest.fetchAll(db)
```

Provide both the request and the output.

**Comment by kiarashvosough1999** [comment]
Thank you for your help, I solved it by using hasManyThrough and set some predicate on it.
