### ISSUE TITLE
Unexpected error on UPDATE with nested SELECT

### ISSUE THREAD

**Issue by Orijhins** [groue/GRDB.swift#1042]
### What did you do?

When trying to update with a nested SELECT, I had an error. Is this supported by GRDB, am I doing it wrong or is there any better way to maybe create the query ?

### What did you expect to happen?

I expected the query to return successfully, as this was the case in DB Browser for SQLite :

<img width="505" alt="Screenshot 2021-08-24 at 14 15 55" src="https://user-images.githubusercontent.com/47521598/130614666-ba9bc588-632f-441a-91c0-94391d99a0e0.png">

### What happened instead?

I had an error with "near "FROM"" =>

near "FROM": syntax error in "UPDATE AccountConfig
SET value = v.id
FROM (
    SELECT vr.id
    FROM VatRate vr
    LEFT JOIN AccountConfig ac
    ON ac.value = vr.value
    WHERE ac.pool = 3
) v
WHERE pool = 3"

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.5.0 - Next Major
**Installation method:** SPM
**Xcode version:** 12.5.1
**Swift version:** 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11

### Demo Project

```swift
// typeVatRate = 3
// the other variables have the same values as their names

try database.execute(sql: """
    UPDATE \(AccountConfig.databaseTableName)
    SET \(AccountConfig.Columns.value.name) = v.\(VatRate.Columns.id.name)
    FROM (
        SELECT vr.\(VatRate.Columns.id.name)
        FROM \(VatRate.databaseTableName) vr
        LEFT JOIN \(AccountConfig.databaseTableName) ac
        ON ac.\(AccountConfig.Columns.value.name) = vr.\(VatRate.Columns.value.name)
        WHERE ac.\(AccountConfig.Columns.pool.name) = \(AccountConfigFunctionId.typeVatRate.rawValue)
    ) v
    WHERE \(AccountConfig.Columns.pool.name) = \(AccountConfigFunctionId.typeVatRate.rawValue)
    """
)
```

**Comment by groue** [comment]
Hello @Orijhins,

GRDB issues are about GRDB. You have to look for SQL & SQLite support somewhere else. See for example:

- StackOverflow
- The [SQLite UPDATE documentation](https://www.sqlite.org/lang_update.html)
- The [SQLite release notes](https://www.sqlite.org/changes.html): `UPDATE FROM` shipped in 3.33.0
