### ISSUE TITLE
ValueObservation on "prepared statement" seems slower than manual query

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1047]
### What did you do?

I created the following statement:

```swift
try Workspace
    .filter(Workspace.Column.subscriptionStatus == SubscriptionStatus.unsubscribed.rawValue)
    .having(Workspace.entities.filter(Entity.Column.isSubscribed).isEmpty == false)
    .order([Workspace.Column.name])
    .fetchAll(db)
```

Then, I used `ValueObservation` to observe changes on this entire statement. I have many locally stored pieces of information that pertains to this query but I only get an initial result about 7-8 seconds in (not entirely sure why). 

Replacing this statement with a manual query seems to work immediately:

```swift
try Workspace
      .fetchAll(db,
                sql: """
                SELECT * FROM workspaces
                WHERE subscriptionStatus = 'unsubscribed'
                AND (SELECT COUNT(*) FROM entities
                     WHERE workspaceId = workspaces.id
                     AND isSubscribed = true) >= 1
                ORDER BY name
                """)
```

It seems, though, looking at the prepared statement, that the "prettier" code generated a LEFT JOIN instead. Could this be a cause for different performance in observation? (Generated using `makePreparedStatement` and prettified):

```sql
SELECT "workspaces".* FROM "workspaces"
LEFT JOIN "entities" ON ("entities"."workspaceId" = "workspaces"."id")
AND "entities"."isSubscribed" WHERE "workspaces"."subscriptionStatus" = 'unsubscribed'
GROUP BY "workspaces"."id"
HAVING COUNT(DISTINCT "entities"."rowid") > 0
ORDER BY "workspaces"."name"
```

If so, is there any way to use the "pretty syntax" to generate something like the manual query, or should I just stick to it? 

### What did you expect to happen?

Immediately get the locally cached values in the observation and get consequent updates. 

### What happened instead?

Huge delay in getting initial observation results. 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.8.0
**Installation method:** CocoaPods
**Xcode version:** 12.5.1
**Swift version:** 5.x
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.4

### Demo Project

The code above is all I can share unfortunately as this is a commercial project.

**Comment by freak4pc** [comment]
Interestingly seems like this is more apparent when attached to a debugger, I'll keep investigating before you waste your time. Might be a no-bug, but still very interesting the difference in pulling that initial load.

**Comment by groue** [comment]
Hello @freak4pc,

You use v5.8.0, which suffers from a nasty performance regression (#983). It was fixed in v5.9.0, so it may be a good opportunity to upgrade to the latest v5.10.0!

**Comment by freak4pc** [comment]
Oh, that's very interesting, thanks !

**Comment by freak4pc** [comment]
I'm not seeing a noticeable change for my specific use case but I'll investigate further before opening a new issue (or reopening this one), to reduce the noise for you. Thanks!

**Comment by groue** [comment]
Wow. OK. @freak4pc, if you need help, please provide a minimal reproducible case, will you?
