### ISSUE TITLE
Xcode 13 beta 5: Crash in libsystem_platform.dylib`_os_semaphore_dispose.cold.1:

### ISSUE THREAD

**Issue by myyra** [groue/GRDB.swift#1048]
Sorry for this being so vague, this seems like an OS issue, and it took me a while to even remotely attribute this to GRDB. I'm still not 100% sure, but it very heavily correlates with accessing the DB and GRDB is the only place where there's semaphores in this project. I'm adding it here to track it just in case.

### What did you do?

Use an observation publisher.

### What did you expect to happen?

The publisher continues to publish events from the db.

### What happened instead?

Crash in `libsystem_platform.dylib_os_semaphore_dispose.cold.1` with no (real) stack trace information. This happens faster if the publisher is scheduled using `.immediate`.

### Environment

**GRDB flavor(s):** None
**GRDB version:** 5.10.0
**Installation method:** SPM
**Xcode version:** 13.0 beta 5 (13A5212g)
**Swift version:** 5.5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.5 (20G71)

### Demo Project

I don't have a definitive way to reproduce this right now, and can't share the full project. Will update once I learn to reproduce this!

**Comment by groue** [comment]
Hello @myyra, thanks for the report. I'll keep this issue opened a few days, so that you have time to solve it or grab more information 👍

**Comment by myyra** [comment]
Now I got the same error without even having opened a database. Seems it's more a Combine issue.

**Comment by groue** [comment]
Thank you @myyra. I reopen the issue so that other users can find it.

**Comment by JoeRadman** [comment]
Not sure if this will work for you -  in Xcode, select Product > Scheme > Edit Scheme, then deselect Run > Options > Queue Debugging > "Enable backtrace recording"

**Comment by groue** [comment]
@myyra, do you know if this issue has been solved with Xcode 13?

**Comment by myyra** [comment]
@groue Looks like it.
