### ISSUE TITLE
Can not Install manually

### ISSUE THREAD

**Issue by ritesh124** [groue/GRDB.swift#105]
i followed the instructions & added everything but still "use of unresolved identifier "Database Queue""
could any one please help me, (first time on sqlite)
Thanks

**Comment by swiftlyfalling** [comment]
@ritesh124: Could you please post your code that is triggering the issue? That'll help more quickly narrow down the cause.

**Comment by iglaweb** [comment]
Close GRDB project at first

**Comment by groue** [comment]
@ritesh124 Don't forget to add the `import GRDB` line at the top of any file in which you use GRDB.

**Comment by ritesh124** [comment]
Hi Sir,
while using it manually in swift,
i have seen many times i don't need to import 
it automatically works
sir the only issue i am facing is in installing these files in my project.
can you please explain that in details.
Thanks Sir

**Comment by groue** [comment]
@ritesh124. Be serious.

You said that your error is "use of unresolved identifier "Database Queue"".

I replied: "add the `import GRDB` line at the top of any file in which you use GRDB."

Then you replied: "I don't need to import".

If you don't follow instructions, I can't do anything for you. Follow the instructions.
