### ISSUE TITLE
belongsToThrough, or a more advanced case of hasManyThrough

### ISSUE THREAD

**Issue by ManheimGreen** [groue/GRDB.swift#1051]
Hello again. I’m still using GRDB, I still like it a lot, and I’m still way out of my depth. I’ve spent most of yesterday and today on this problem, and after reading and re-reading the documentation and trying a million different things, I still have no solution and no idea how to get to a solution. But, it’s pretty simple conceptually and hopefully you can help.

Suppose I have an `Author` that has-a `Book` that has-many `References`. (Each `Reference` belongs-to a `Book` that belongs-to an `Author`.) Each `Reference` refers to its owning `Book` (which it belongs-to) and references an `Author`, another or the same. Then I want to very simply have an association, `Author.references`, that permits any `Author` to access the set of `Author`s that reference it. Here’s a nice illustration:

```
Author <-- Book <-- Reference
  ^                 /
  |                /    
  |               /
Author <---------- 

(owning on top; referencing on bottom; association on left)
```

In GRDB’s associations-interface lingo, it should (I think) be something like:

```
extension Author {
    static let references = Author.hasMany(Author.self,
                                           through: Author.hasMany(Reference.self,
                                                                   through: Reference.belongsTo(Book.self,
                                                                                                through: Book.belongsTo(Author.self),
                                                                                                using: Book.author),
                                                                   using: Reference.book),
                                           using: Author.reference)
}
```

That doesn’t work for obvious reasons, so how can this be done with associations? Or can it even be done?

Thanks. :)

**Comment by groue** [comment]
Hello @ManheimGreen,

> That doesn’t work for obvious reasons

It's not obvious to me. Do you get a compiler error? A runtime error? What does it say?

> belongsToThrough, or a more advanced case of hasManyThrough

You describe a use case for HasManyThrough.

The -through associations chain other associations. HasOneThroogh can chain "to-one" associations (belongsTo, hasOne, and hasOneThrough). HasManyThrough can chain all of them.

A -through association is always created from two other associations. When both are "direct" (belongsTo, hasMany, hasOne), then you've created a bridge from A to C through B. When either one is indirect, then the bridge gets longer: from A to D through B and C. It looks like this is your situation.

I recommend cutting the problem into small pieces: the association you show in the sample code is huge and difficult to read.

Define the direct associations you need first. Check they work as expected. Run requests on actual data. Make sure there is no runtime error. Convince yourself of the relevance of the results. Trace SQL calls: do they look like the ones you would expect? Help yourself walking on a firm ground. This can be a good opportunity to write tests.

Then build and check the first -through association. 

Then build and check the last hasManyThrough.

And you'll be done :-)

Associations are not easy. But you're on the way!

**Comment by ManheimGreen** [comment]
Pardon, I thought it would be obvious. There is no BelongsToThrough: `belongsTo(_:through:using)`. And since I need to traverse from `Author.hasMany(Reference.self)` in the belongs-to direction, that is, _from_ `Reference` _through_ `Body` _to_ `Author` (which at the end must be has-many) I need something like a BelongsToThrough ... right? I've tried everything I can think of and nothing works.

> A -through association is always created from two other associations. When both are "direct" (belongsTo, hasMany, hasOne), then you've created a bridge from A to C through B. When either one is indirect, then the bridge gets longer: from A to D through B and C. It looks like this is your situation.

What do you mean by direct and indirect? What's the difference? I don't understand. (And there isn't much on this to be found in the repository.)

> Define the direct associations you need first. Check they work as expected. Run requests on actual data. Make sure there is no runtime error. Convince yourself of the relevance of the results. Trace SQL calls: do they look like the ones you would expect? Help yourself walking on a firm ground. This can be a good opportunity to write tests.

Thanks for this excellent advice. I've written a number of "normal" associations and they've worked very well and I'm reasonably certain I know how they work at a conceptual level. The problem is this specific association for the aforesaid reasons. 

Unfortunately, I don't really know what the SQL calls should look like, as my knowledge of SQL is significantly less advanced than what I've managed to do with the magical aid of GRDB, and frankly I don't have any idea what the tests should look like in this case. But I'm all-ears to any and all specific suggestions.

**Comment by groue** [comment]
> I need something like a BelongsToThrough ... right?

No. That role is also filled by HasOneThrough.

As I said above: the -through associations chain other associations. HasOneThroogh can chain "to-one" associations (belongsTo, hasOne, and hasOneThrough). HasManyThrough can chain all of them.

> What do you mean by direct and indirect?

Direct associations are belongsTo, hasMany, hasOne.

Indirect are hasOneThrough and hasManyThrough.

> What's the difference?

A direct association can link two tables when one has a foreign key to the other.

Indirect associations are built not from tables and foreign keys, but from other associations.

**Comment by groue** [comment]
I understand what you mean. The GRDB associations are 99% inspired from the Ruby on Rails framework, where HasOneThrough is also the one and single association that chains all to-one associations (belongsTo, hasOne, etc). Maybe this explains why I could not explain it better: this was not my idea on the first place 😅

Maybe just remember that the two -through associations (hasOneThrough and hasManyThrough) cover all association composition needs.
