### ISSUE TITLE
Easy way to write a CTE association with two conditions

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#1058]
### What did you do?
```
public protocol DatabaseModel: FetchableRecord {
    associatedtype FetchRequest
    static func query(_ request: FetchRequest) -> QueryInterfaceRequest<Self>
}

public protocol PersistableDatabaseModel: DatabaseModel & PersistableRecord & Identifiable {
    var id: Int64? { get }
}

public final class Contact: Codable, PersistableDatabaseModel {
    var userId: Data
}

public final class Message: Codable, PersistableDatabaseModel {
    var sender: Data
    var receiver: Data
    var timestamp: Int
    var unread: Bool
}

public struct Chat: Decodable, Equatable, DatabaseModel {
    public enum FetchRequest {
        case all
    }

    public var contact: Contact
    public var unreadCount: Int
    public var lastMessage: Message?

    public static func query(_ request: FetchRequest) -> QueryInterfaceRequest<Chat> {
        switch request {
        case .all:
            let lastMessageRequest = Message
                .annotated(with: max(Message.Column.timestamp))
                .group([Message.Column.receiver, Message.Column.sender])

            let cte = CommonTableExpression<Message>(
                named: "lastMessage",
                request: lastMessageRequest
            )

            let lastMessage = Contact.association(
                to: cte,
                on: { contact, lastMessage in
                    lastMessage[Column("sender")] == contact[Column("userId")] ||
                    lastMessage[Column("receiver")] == contact[Column("userId")]
                })
                .order(Message.Column.timestamp.desc)

            return Contact
                .with(cte)
                .including(optional: lastMessage)
                .asRequest(of: Self.self)
        }
    }
}
```

### What did you expect to happen?

1 .  I expected to get the only one latest message between that sender and that receiver because I don't have a table for Chat itself so I don't have a chat id for example.

2 . I know I cannot expect that to happen from the code above but since I'm on it... I'd like to know if there's an easy way to go over all the messages from that same association and get that unread count

### What happened instead?

I got the last messages from both the send **- and -** the receiver

Appreciated!

**Comment by brunomunizaf** [comment]
I managed to do it in the following way but I feel like I can avoid this whole code by using some GRDB sql trait here and there:

```
        let chatStream = dbManager
            .publisher(fetch: Contact.self, .friends)
            .flatMap { [unowned self] contacts -> AnyPublisher<[Chat], Error>in
                let userIds = contacts.map { $0.userId }

                let messagesPublisher: AnyPublisher<[Message], Error> = dbManager
                    .publisher(fetch: .latestOnesFromContactIds(userIds))
                    .map { $0.sorted(by: { $0.timestamp > $1.timestamp }) }
                    .eraseToAnyPublisher()

                return messagesPublisher.map { messages -> [Chat] in
                    contactList.map { contact -> Chat in
                        Chat(contact: contact, latestMessage: messages.first {
                            $0.sender == contact.userId || $0.receiver == contact.userId
                        })
                    }
                }
                .eraseToAnyPublisher()
            }
            .catch { _ in Just([]) }
            .map { $0.filter { $0.latestMessage != nil }}
            .map { $0.sorted(by: { $0.latestMessage!.timestamp > $1.latestMessage!.timestamp })}
            .eraseToAnyPublisher()
```

**Comment by groue** [comment]
Hello @brunomunizaf, I'm away from any computer until next week, so I'm glad you could find a solution. I'll look at your issue later :)

**Comment by groue** [comment]
@brunomunizaf, it looks like your question is about more about SQL than GRDB, since the query you build does not provide the expected results. Maybe we should have a conversation in SQL, solve your problem at this level, and only then turn it into Swift.

**Comment by groue** [comment]
Hello @brunomunizaf, is this issue still relevant?

**Comment by groue** [comment]
Closing due to lack of input. Feel free to reopen when you feel like it!

**Comment by brunomunizaf** [comment]
In the end I managed to do it like this:

```
public protocol DatabaseModel: FetchableRecord {
    associatedtype FetchRequest
    static func query(_ request: FetchRequest) -> QueryInterfaceRequest<Self>
}

public struct SingleChatInfo: Decodable, Equatable {
    public enum FetchRequest {
        case all
    }

    public var contact: Contact
    public var lastMessage: Message?

    public init(
        contact: Contact,
        lastMessage: Message? = nil
    ) {
        self.contact = contact
        self.lastMessage = lastMessage
    }
}

extension SingleChatInfo: DatabaseModel {
    public static func query(_ request: FetchRequest) -> QueryInterfaceRequest<SingleChatInfo> {
        switch request {
        case .all:
            let request = Message
                .annotated(with: max(Message.Column.timestamp))
                .group([Message.Column.sender || Message.Column.receiver])

            let cte = CommonTableExpression<Message>(
                named: "lastMessage",
                request: request
            )

            let lastMessage = Contact.association(to: cte) { contact, lastMessage in
                lastMessage[Message.Column.sender] == contact[Contact.Column.userId] ||
                lastMessage[Message.Column.receiver] == contact[Contact.Column.userId]
            }.order(Message.Column.timestamp.desc)

            return Contact.with(cte)
                .including(required: lastMessage)
                .asRequest(of: Self.self)
        }
    }
}
```
No need to re-open, just leaving this here if someone faces the same issue. 
Thanks a lot! @groue

**Comment by brunomunizaf** [comment]
Hello @groue !

I finally had some time to get back to this. I'm sorry about the lack of response here.

> @brunomunizaf, it looks like your question is about more about SQL than GRDB, since the query you build does not provide the expected results. Maybe we should have a conversation in SQL, solve your problem at this level, and only then turn it into Swift.

Indeed, this is more of a SQL support than a GRDB question.

I have a DirectChat request model that holds a `contact` (of type Contact), a `lastMessage` (of type DirectMessage) and a `unreads` property (of type Int). What I'm trying to achieve is a request that pulls rows from the DirectMessage table, groups them by the `sender` or `receiver` column by each `contact.uniqueId` I have on my other table from contacts.

This first part works like a charm, now I'm trying to add to this request the amount of unread messages to each chat. I don't have a `chats` table, which is what makes this so much more complicated 😢 .  Each directMessage row has a isRead column which is a boolean. Based on this column I want to get the amount of unread messages for each of those chats. Any idea how can I reach that?

```
public static func request(with query: DirectChat.Query) -> QueryInterfaceRequest<DirectChat> {
    let lastMessageRequest = DirectMessage
        .annotated(with: max(DirectMessage.Columns.timestamp))
        .group([DirectMessage.Columns.sender, DirectMessage.Columns.receiver])

    let lastMessageCTE = CommonTableExpression<DirectMessage>(
        named: "lastMessage",
        request: lastMessageRequest
    )

    let lastMessage = Contact.association(to: lastMessageCTE) { contact, lastMessage in
        let conditionA = lastMessage[DirectMessage.Columns.sender] == contact[Contact.Columns.uniqueId]
        let conditionB = lastMessage[DirectMessage.Columns.receiver] == contact[Contact.Columns.uniqueId]
        return conditionA || conditionB
    }.order(DirectMessage.Columns.timestamp.desc)

    let unreadMessagesRequest = DirectMessage
        .annotated(with: count(!DirectMessage.Columns.isRead))
        .group([DirectMessage.Columns.sender, DirectMessage.Columns.receiver])

    let unreadMessagesCTE = CommonTableExpression<DirectMessage>(
        named: "unreads",
        request: unreadMessagesRequest
    )

    let unreads = Contact.association(to: unreadMessagesCTE) { contact, message in
        let conditionA = message[DirectMessage.Columns.sender] == contact[Contact.Columns.uniqueId]
        let conditionB = message[DirectMessage.Columns.receiver] == contact[Contact.Columns.uniqueId]
        return conditionA || conditionB
    }

    return Contact
        .with(lastMessageCTE)
        .with(unreadMessagesCTE)
        .including(required: lastMessage)
        .including(required: unreads)
        .asRequest(of: Self.self)
}
```

Thank you very much, as usual saving me. 😅 🙏🏻

**Comment by groue** [comment]
Hi again @brunomunizaf (and thanks for sponsoring the project 😊!)

> Indeed, this is more of a SQL support than a GRDB question.

OK, so this is somewhat outside of the scope of the free support. And I'm not much less fluent in SQL as you think 😅. My job is more making sure users who know what they want to do in SQL can do it with GRDB, rather than teaching SQL.

When I face a difficult problem like yours, I know that I do not have to run a single request that packs everything I need into it. Sometimes, running several requests, and merging their results together, is a pretty good solution.

For example, since you are already able to fetch everything, but the number of unread messages, what about fetch partial values first, and then fetch those extra counts in a second request? It is then possible to inject those numbers into the previously fetched partial values.

```swift
// SELECT sender, COUNT(*) AS cnt FROM directMessage WHERE NOT isRead GROUP BY sender
let rows = try DirectMessage
    .select(DirectMessage.Columns.sender, SQL("COUNT(*)").forKey("cnt"))
    .filter(!DirectMessage.Columns.isRead)
    .group(DirectMessage.Columns.sender)
    .asRequest(of: Row.self).fetchAll(db)

// A dictionary [String: Int] of unread counts for each sender
let unreadCountForSender = Dictionary(uniqueKeysWithValues: rows.map { row in (row["sender"] as String, row["cnt"] as Int) })
```

**Comment by brunomunizaf** [comment]
> Hi again @brunomunizaf (and thanks for sponsoring the project 😊!)

You're very welcome, its well deserved and I hope I can pick a higher tier in the near future. 😜

> OK, so this is somewhat outside of the scope of the free support. And I'm not as fluent in SQL as you think 😅. My job is more making sure users who know what they want to do in SQL can do it with GRDB, rather than teaching SQL.

Got it, so here's the SQL statement I'm trying to achieve on my request:

```
WITH 
  "lastMessage" AS (
    SELECT *, MAX("timestamp") 
    FROM "direct_messages" 
    GROUP BY "sender", "receiver"
), 
  "unreadCount" AS (
    SELECT *, COUNT(NOT "isRead") 
    FROM "direct_messages" 
    GROUP BY "sender", "receiver"
)
SELECT "contacts".*, "lastMessage".*, "unreadCount".* FROM "contacts"   
JOIN "lastMessage" 
ON (
    "lastMessage"."sender" = "contacts"."uniqueId" 
OR  
   "lastMessage"."receiver" = "contacts"."uniqueId"
)
  LEFT JOIN "unreadCount" 
ON (
    "unreadCount"."sender" = "contacts"."uniqueId" 
OR 
    "unreadCount"."receiver" = "contacts"."uniqueId"
)
  ORDER BY "lastMessage"."timestamp" DESC
```

This brings me all columns of each `lastMessage` and each one appending a column `COUNT(NOT"isRead")` from that contact which is exactly what I need, but how can I write this w/ GRDB?

Here's my request struct:

```
struct DirectChat {
    var contact: Contact
    var unreadCount: Int64
    var lastMessage: DirectMessage

    init(contact: Contact, unreadCount: Int64, lastMessage: DirectMessage) {
        self.contact = contact
        self.unreadCount = unreadCount
        self.lastMessage = lastMessage
    }
}
```

In this current state I crash at:

<img width="1487" alt="Screen Shot 2022-02-03 at 22 07 58" src="https://user-images.githubusercontent.com/12559440/152455619-08838c6d-9e03-4e50-8651-dff5e0170d8c.png">

Might be because my association is to `Contact` here?

```
 let lastMessageRequest = DirectMessageRecord
            .annotated(with: max(DirectMessageRecord.Columns.timestamp))
            .group([DirectMessageRecord.Columns.sender, DirectMessageRecord.Columns.receiver])

        let lastMessageCTE = CommonTableExpression<DirectMessageRecord>(
            named: "lastMessage",
            request: lastMessageRequest
        )

        let lastMessage = ContactRecord.association(to: lastMessageCTE) { contact, lastMessage in
            let conditionA = lastMessage[DirectMessageRecord.Columns.sender] == contact[ContactRecord.Columns.uniqueId]
            let conditionB = lastMessage[DirectMessageRecord.Columns.receiver] == contact[ContactRecord.Columns.uniqueId]
            return conditionA || conditionB
        }.order(DirectMessageRecord.Columns.timestamp.desc)

        let unreadCountRequest = DirectMessageRecord
            .annotated(with: count(!DirectMessageRecord.Columns.isRead))
            .group([DirectMessageRecord.Columns.sender, DirectMessageRecord.Columns.receiver])

        let unreadCountCTE = CommonTableExpression<Int64>(
            named: "unreadCount",
            request: unreadCountRequest
        )

        let unreadCount = ContactRecord.association(to: unreadCountCTE) { contact, lastMessage in
            let conditionA = lastMessage[DirectMessageRecord.Columns.sender] == contact[ContactRecord.Columns.uniqueId]
            let conditionB = lastMessage[DirectMessageRecord.Columns.receiver] == contact[ContactRecord.Columns.uniqueId]
            return conditionA || conditionB
        }

  return ContactRecord
            .with(lastMessageCTE)
            .with(unreadCountCTE)
            .including(required: lastMessage)
            .including(optional: unreadCount)
            .asRequest(of: Self.self)
```

Let me know if this is too far from what you can help me, I don't want to abuse from soliciting your help 👍

**Comment by groue** [comment]
Hello again @brunomunizaf,

The SQL request definitely looks like something that the query interface can generate, and I suppose you wrote well your Swift request.

So I'll focus on the "column not found" error.

My hypothesis is that the *structure* of the decoded record does not match the *structure* of the request. In a nutshell, one can not declare decoded properties at "random" positions in the decoded type. The position of properties must match their positions in the request.

For example, see [Choosing a Joining Method Given the Shape of the Decoded Type](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#choosing-a-joining-method-given-the-shape-of-the-decoded-type). You'll see different "shapes", or structures or requests, and the matching structure of decoded records.

See also [Debugging Request Decoding](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#debugging-request-decoding): you'll see how to decode raw database rows instead of records, and print the structure of the fetched rows. The structure of decoded records must match the structure of those rows.

If you have difficulties, please provide the structure of one fetched row (as explained in the debugging chapter):

> ```swift
> let request = Book
>     .including(required: Book.author
>         .including(optional: Author.country))
>     .including(optional: Book.coverImage)
>     .including(all: Book.prizes)
> 
> let rows = try Row.fetchAll(db, request)
> print(rows[0].debugDescription)
> // Prints:
> // ▿ [id:1, authorId:2, title:"Moby-Dick"]
> //   unadapted: [id:1, authorId:2, title:"Moby-Dick", id:2, name:"Herman Melville", > countryCode:"US", code:"US", name:"United States of America", id:NULL, imageId:NULL, path:NULL]
> //   - author: [id:2, name:"Herman Melville", countryCode:"US"]
> //     - country: [code:"US", name:"United States of America"]
> //   - coverImage: [id:NULL, imageId:NULL, path:NULL]
> //   + prizes: 3 rows
> ```

This will help designing the structure decoded record.
