### ISSUE TITLE
Xcode 13 : Instance method requires that 'DispatchQueue' conform to 'Scheduler'

### ISSUE THREAD

**Issue by xNarCiik** [groue/GRDB.swift#1059]
Hello there,

I have a problem for compile in release mode with the latest Xcode 13 version. 

Here a screen of the build errors
![Capture d’écran 2021-09-16 à 12 40 43](https://user-images.githubusercontent.com/24975457/133598559-b8341159-dadc-4ecf-a060-3f10642add26.png)

My current IOS min version is 10.0 & swift version 5.0. I use the latest commit of the master.

I can build correctly if I change the min version to 11.0 in the project and pod file. Anybody have an idea of why I have this errors ? 

Thanks in advance

**Comment by Anthony-Todd-CGI** [comment]
Hi,

I've had the same issue.
I have fixed it in one project that used GRDB cocoa pod by updating the project min iOS version to 12. this bypassed the need to compile for armv7.
I still have this issue for a project that uses SPM because the package builds for iOS 10 which requires armv7 even though the project is for ios13+.

I hope this is of some help.

**Comment by jtouzy** [comment]
Same here, can't build in Release mode (ok in Debug mode), using GRDB as SPM dependency.
Project with min version iOS 14.
It looks like combine-schedulers library had the same problem, they fixed it in 0.5.2 :
https://github.com/pointfreeco/combine-schedulers/releases/tag/0.5.2

**Comment by foxware00** [comment]
@xNarCiik this is actually a known issue in XCode 13, they've not fixed it in the [release notes](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-13-release-notes)

> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)

> Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for example, increase the deployment target of the library to iOS 11 or higher).

Given GRDB targets iOS 10, it's not on GRDB to bump the deployment target. There are a few workarounds on this bug here which was facing similar issues in earlier betas depending on your usecases. #1033

**Comment by conmulligan** [comment]
I was able to work around this by forking the repo and bumping the iOS deployment target to iOS 11: 

https://github.com/conmulligan/GRDB.swift/commit/293188ac426aa5c0be2621948746d9c8577ac705

**Comment by brunomunizaf** [comment]
@conmulligan i'm using your fork and I still have the same issue, my project is >13

**Comment by jtouzy** [comment]
@brunomunizaf I've forked it [here](https://github.com/Pictarine/GRDB.swift), tagged 5.11.1 and works fine for me, for a temporary fix
(min target iOS 13.0 - Combine release). My projet is >14

**Comment by brunomunizaf** [comment]
@jtouzy my bad it was actually combine-schedulers from point-free that was failing, this workaround does fix for GRDB. thanks

**Comment by gabors** [comment]
@groue Thanks for the great framework.
Was curious if there will be a workaround for Xcode 13 that doesn't involve upping the min OS version to 13?
Our suite of apps currently support 11+ and we would prefer to not require newer OS at this time.
Thanks!

**Comment by groue** [comment]
Hello @gabors, I'm quite annoyed by this behavior of Xcode 13. I will act shortly but meanwhile I'm still looking for the best option. I'm quite sorry about the inconvenience, believe me.

**Comment by gabors** [comment]
> Hello @gabors, I'm quite annoyed by this behavior of Xcode 13. I will act shortly but meanwhile I'm still looking for the best option. I'm quite sorry about the inconvenience, believe me.

Hi @groue Really appreciate all your hard work!

**Comment by groue** [comment]
The issue should be fixed in GRDB v5.12.0, which has dropped support for 32-bits devices by bumping the minimum iOS version to 11.0.

**Comment by gabors** [comment]
> The issue should be fixed in GRDB v5.12.0, which has dropped support for 32-bits devices by bumping the minimum iOS version to 11.0.

Thanks so much.

**Comment by ksemianov** [comment]
@groue do you plan to bump iOS version for RxGRDB as well?

**Comment by groue** [comment]
Thanks for reminding me of it 👍

**Comment by groue** [comment]
@ksemianov, I'm not sure an RxGRDB update is necessary. Please open an issue if it is.

**Comment by ksemianov** [comment]
@groue I've opened an issue https://github.com/RxSwiftCommunity/RxGRDB/issues/68
