### ISSUE TITLE
Use in objc

### ISSUE THREAD

**Issue by farfromrefug** [groue/GRDB.swift#1067]
Is it possible to use your lib in an objc project? I see a sourcemap in the Support dir but it is not part of the cocoa spec so the pod wont worm in an objc project.
Thanks

**Comment by groue** [comment]
Hello @farfromrefug, GRDB.swift is a Swift project without any ObjC bindings.

I used to maintain [GRDBObjC](https://github.com/groue/GRDBObjc), a layer on top of GRDB that exposes [FMDB](https://github.com/ccgus/fmdb)-compatible APIs, but I'm not sure this abandoned project really is what you are looking for.

Have a look at [FCModel](https://github.com/marcoarment/FCModel).

**Comment by farfromrefug** [comment]
@groue thanks did not now about GRDBObjC. Seems some people are using it. Will look at it thanks!
