### ISSUE TITLE
Compiling projects with Xcode 13.0 throws errors

### ISSUE THREAD

**Issue by huelli** [groue/GRDB.swift#1069]
### What did you do?

Archiving project for distribution

### What happened instead?

Errors: DispatchQueue must conform to Scheduler

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:**5.12.0
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**13.0
**Swift version:** 5.5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.6

### Demo Project

<img width="448" alt="Bildschirmfoto 2021-09-27 um 09 45 14" src="https://user-images.githubusercontent.com/66839649/134866472-a324c91c-5bc8-4356-931d-3023e49d9d55.png">

**Comment by groue** [comment]
Hello @huelli, please tell your GRDB installation method, please (CocoaPods, SPM, manual, other?).

**Comment by huelli** [comment]
SPM installation method

**Comment by groue** [comment]
Thank you. I will investigate, but meanwhile, you can try what I plan to do:

1. Look for the **first** macOS version that has dropped support for 32-bits devices (this information should exist somewhere online).
2. Fork GRDB, and in its package.swift file, bump the macOS target to this system version.
3. See if this fixes your issue.

**Comment by huelli** [comment]
I can archive and distribute my projects. But solving these errors might give a better performance

**Comment by groue** [comment]
I don't understand. How can you archive and distribute if you get compiler errors? I'm not sure I understand what we are talking about, now. I no longer know what kind of help you need.

**Comment by huelli** [comment]
You're right. I don't get any errors. Don't no what I've changed. Sorry but thanks for our time

**Comment by groue** [comment]
All right, @huelli. Please open another issue when needed.
