### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by hyperr** [groue/GRDB.swift#107]
Hi!
First of all i really like your library! It's amazing!!
But today i did some profiling/testing on memory for an iOS i'm currently working on. With "Leaks" from "Instruments" (Dev tools) i got this:

![image](https://cloud.githubusercontent.com/assets/4410142/18068474/ba3c5e7c-6e41-11e6-9830-3dc18c234fa1.png)

Is this may an memory leak in the StatementCompilationObserver?
What is the StatementCompilationObserver for? If it is just for the FetchController, may we can add a flag to switch it off for those (like me) that aren't using FetchController at all?

May i am completely wrong, and my own code is leaking or something, please tell me if you see something i dont :)

Thanks!

**Comment by swiftlyfalling** [comment]
@hyperr: Can you post a reduced sample that exhibits the same problem?

**Comment by hyperr** [comment]
I will try to get/extract an working sample tomorrow (today) before i go to work.
Meanwhile:I have a class TransactionRepo. Init it with a DatabaseQueue (private let database: DatabaseQueue)
Then i call:func addPosition(position, toTransaction) {    self.database.inTransaction { db in        ...        try position.update(db) // shows up in leaking stack trace
        .Commit}

Get Outlook for iOS




On Tue, Aug 30, 2016 at 12:09 AM +0200, "swiftlyfalling" <notifications@github.com> wrote:












@hyperr: Can you post a reduced sample that exhibits the same problem?

**Comment by hyperr** [comment]
Answering via mail looks bad, sorry for that!

**Comment by groue** [comment]
Hello @hyperr. Thanks for reporting this. OK I'll close the issue until the problem comes back, eventually.

**Comment by Mina-R-Meshriky** [comment]
His @groue ,
relating to leaks and maybe this problem, I am also doing some profiling to my app and there is a leak that keeps popping, here are the detailed info. 
1- I have a TableView that is fed from 2 FetchedRecordsController lets call them Controller_A and Controller_B
2-while the cells are being initialized I put a timer with any cell that will use controller_B like so:

    timer = Timer.scheduledTimer(timeInterval: TimeInterval(timeToConsiderCellRead), target: self, selector: #selector(updateCellViews(timer:)), userInfo: indexPath, repeats: false)

3- and the selector function is like that : 

    func updateCellViews(timer: Timer) {
		let index = timer.userInfo as! IndexPath
		if (Table.indexPathsForVisibleRows?.contains(index))! {
			let id = Controller_B.record(at: IndexPath(row: (index.row/Offset), section: 0)).id
			do {
				try dbQueue.inDatabase {
					db in
                                        // TableEntry is a class of Type Record
					if let cell = try TableEntry.fetchOne(db, key: id) {
						cell.views = (cell.views)! + 1
						try cell.update(db)
					}
				}
			} catch let error {
				print(error)
			}
		} else {
			timer.invalidate()
		}
	}
finally I get a leak using the profiler on the following two lines persistently:
     
    if let cell = try TableEntry.fetchOne(db, key: id) 

![screen shot 2017-07-24 at 3 59 07 pm](https://user-images.githubusercontent.com/26849271/28526859-1469f748-7089-11e7-94f1-ac924005af64.png)

    try cell.update(db)
![screen shot 2017-07-24 at 3 55 02 pm](https://user-images.githubusercontent.com/26849271/28526801-ea1d55c0-7088-11e7-8255-23646af7f8a6.png)

![screen shot 2017-07-24 at 3 55 18 pm](https://user-images.githubusercontent.com/26849271/28526749-be8ca096-7088-11e7-9f03-26291cbad92f.png)

**Comment by groue** [comment]
Hello @Mina-R-Meshriky,

If your leak has disappeared, that's good. It's been a long time I did not run the GRDBDemoiOS app that ships with GRDB in Instruments. It also uses a FetchedRecordsController. I did notice a few leaks - nothing awful, but I have to investigate the subject.

**Comment by swiftlyfalling** [comment]
In my experience, through at least Xcode 8.3.3, the built-in leak detector can falsely detect leaks in Swift code, and these typically show up as small malloc leaks. This is not to say that there might not also be occasional bugs in the Swift core libraries that result in leaks in odd circumstances (or bugs in your own code) - just that there seem to still be some bugs in the leak detector around properly attributing all allocations to their owners when using Swift.
