### ISSUE TITLE
How to backup data correctly?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1070]
Our application defines a DatabaseQueue object globally, which opens database A and is used to read and write the database.
Now we need to add a requirement that database A can be backed up to other places at any time, and all actions are completed by the background, that is, without affecting the user's operations.(the data after the backup method is executed is not taken into account)

[https://github.com/groue/GRDB.swift#backup](https://github.com/groue/GRDB.swift#backup)

I see that the document has a backup method, which will block the current thread, so I don't know how to complete our requirement.

thank you.

**Comment by groue** [comment]
Hello @SF-Simon,

Did you try to call the backup method from a background thread?

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> Did you try to call the backup method from a background thread?

I haven't written the code yet because I'm not sure how I should write it.
I wonder if I should use the global DatabaseQueue object to perform the backup method. For example:
```
let dbQueue: DatabaseQueue // 

let newDatabaseQueue: DatabaseQueue = ... 
try dbQueue.backup(to: newDatabaseQueue)
```

I don't know the actual function of this method. I'm worried that I will monopolize the database operation during backup, so that the user's write and read will fail.

So I want to understand this part and start writing code.

**Comment by groue** [comment]
> I'm worried that I will monopolize the database operation during backup, so that the user's write and read will fail.

They would not _fail_, they would _wait_.

If you need to perform database operations as the backup is performed, in parallel, use a DatabasePool instead of a DatabaseQueue.

**Comment by SF-Simon** [comment]
> > I'm worried that I will monopolize the database operation during backup, so that the user's write and read will fail.
> 
> They would not _fail_, they would _wait_. GRDB takes care of _serializing_ accesses to the database when you use a DatabaseQueue, in order to prevent errors.
> 
> If you need to perform database operations as the backup is performed, _in parallel_, use a DatabasePool instead of a DatabaseQueue.

I think we should replace the original global DatabaseQueue object with DatabasePool object.
I'll take a look at the coding test later. Thank you for your help.

**Comment by SF-Simon** [comment]
> > I'm worried that I will monopolize the database operation during backup, so that the user's write and read will fail.
> 
> They would not _fail_, they would _wait_. GRDB takes care of _serializing_ accesses to the database when you use a DatabaseQueue, in order to prevent errors.
> 
> If you need to perform database operations as the backup is performed, _in parallel_, use a DatabasePool instead of a DatabaseQueue.

I think we should replace the original global DatabaseQueue object with DatabasePool object.
I'll take a look at the coding test later. Thank you for your help.

**Comment by groue** [comment]
All right, we can close this issue then. Open a new one if you have a new question. Happy GRDB!
