### ISSUE TITLE
[Question] Could you tell me why `TableDefinition.rename` has version constraint?

### ISSUE THREAD

**Issue by cozzin** [groue/GRDB.swift#1072]
### What did you do?

First of all, thank you for maintaining this great library.
I did use `rename` method for renaming columns, but I have a question why this method has version constraint.

https://github.com/groue/GRDB.swift/blob/2c7334ccbb774283b0f9ffd5c57e72c58807a7e3/GRDB/QueryInterface/Schema/TableDefinition.swift#L659-L662

Is there anyone how can tell me why this method has version constraint? 

### What did you expect to happen?

I want to use `rename` method without version constraint.

**Comment by groue** [comment]
Hello @cozzin,

The ability to rename a column has recently shipped in SQLite. It was not present in the version of SQLite that ships with older operating system versions.

**Comment by cozzin** [comment]
@groue Wow, thank you for your quick reply!!
Based on your answer, I found a [similar issue](https://github.com/tekartik/sqflite/issues/592#issuecomment-782120354). Now I understand why it needs version check.
