### ISSUE TITLE
Good practices for Value Observation with SwiftUI and GRDB philosophy

### ISSUE THREAD

**Issue by abournier** [groue/GRDB.swift#1081]
Hello,

I'm trying to learn GRDB writing a small app inspired by the CombineDemo example, with some custom changes and more screens.

### What did you do?

My first screen shows a list of items as the demo app, and yes, with value observation on the list request, **it works like a charm when adding a new item**. It seems very powerfull. 

### A few changes

Contrary to the demo app, I added a DetailView screen whan tapping an item, showing only this item in details (with more fields). Then I can edit/modify this item from this DetailView screen. **When modifying an item, the list is updated too**. Great !

The app structure is like this:
_ListView => DetailView => EditView => FormView_

### Good Practices to refresh changes in many places 

However, I have a general question about GRDB philosophy.

As I wrote, the list is updated but not the DetailView with the item change. It's logical, because the item is not observed in the database at the time.

What's the best way to observe this change in DetailView and what is recommanded ?

1. Use SwiftUI common property wrappers such @Binding to reflect changes in DetailView (as many apps) from EditView. (I tried it, it works, howevever I need to manage "manually" the cancel due to the Binding)
2. Use (and abuse ?) of value observation to observe only this item with a new @query wrapper (it could observe a simple request such `SELECT * FROM table WHERE id=1`.) - This observation could be cancelled each time the DetailView is closed to not have performance issues.

GRDB says "database is the single source of truth". If we follow this, I think that all the content (depending the screens dispayed of course) could be observed in database, not in memory, true ?

So can we use value observation in most of "screens" of the app, and is-it recommended? (value observation performance is an other problem depending the type of app and quantity of data)

And as this app will surely sync in background with a server, is-it also the good way to observe data changes and a point in favor of database changes observation ?

### Environment

**GRDB version:** 5.12,
**Xcode version:** 13.1
**Platform(s) running GRDB:**  iOS 15

**Comment by groue** [comment]
> > Use GRDB as a tool, and consider its behaviors as bricks in your own reasoning towards your goals.
> 
> The tool seems very good. Congratulations. However, when you build an app, the question is also: how much my app will be dependent on this tool ? How much possibilities of the tool will I use ? (for example, I'm not sure to use associations basics instead of raw SQL, but this is another thing) :-)

Sometimes I also wonder how much I should rely on GRDB SQL generation.

Then I remember that all models exposed to the app are plain structs or classes, and that all the SQL generation stuff can _only_ be used _inside_ a database access method.

If you hide all GRDB-related stuff behind a `#if`, and remove the dependency on GRDB, then your everything in your app fully compiles, with the same models - granted you replace the implementation of your database-access service.

```swift
// That's what the app sees
struct Player {
    var id: String
    var name: String
    var score: Int
}

// This does not harm anybody
extension Player: Codable { }

#if MY_APP_USES_GRDB
// Everything here is only used inside dbQueue.read or .write
import GRDB

extension Player: FetchableRecord, PersistableRecord {
    enum Columns { ... }
    static let team = belongsTo(Team.self)
}

extension DerivableRequest where RowDecoder == Player { ... }
#endif
```

That's one of the benefit of not having a base class for record types, and not relying on property wrappers in the definition of those types.

What your app _is_ dependent on, when you use GRDB, is the _interface_ between your app and the database, which mainly is `write`, `read`, and database observation. `write` and `read` _can_ be replaced, with the same transactional behavior (minus concurrent read & writes), with, say, FMDB, Core Data, or Realm. Database observation is trickier to replace: after you have used ValueObservation, I'm afraid you're forever spoiled by the awesome convenience of this tool.

But SQL generation is just SQL generation: it has no impact on the core behaviors of your application.

> > Instead, you can rely on the particular ability of GRDB to be used as a single-source-of-truth, and send an immutable element to the DetailView (or an element id). The DetailView now just has to write in the db, and the list will update automatically. This sounds cool to me, because both views are now independent, and very simple - not more complex than necessary.
> 
> I'm not sure to understand. It's not the DetailView that write in the database. It's the EditView. List => Detail => Edit So currently, when EditView saves to database, the List is well refreshed due to database observation. Only the DetailView is not refreshed. So my question was more: do I need to to create a new observation only for the DetailView item ? I think one reply to this question could be the server sync: yes, the server sync needs to refresh both ListView and DetailView with value observation. (and as I wrote before, not the EditView with the form)

Oh, sorry, now I get it. That's an interesting question. I'll dare a quick answer: if DetailView observes the database, then it is standalone. This can be an advantage.

**Comment by groue** [comment]
I'm happy you feel confident organizing your files. And since you know SQL, you can always choose how to perform some tasks.

From my personal experience, in the kind of projects I work on, the GRDB associations are very useful, because not everybody can write SQL. Associations also have a _slight_ advantage over SQL, which is that they allow apps to define a library of reusable and composable request snippets. See https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#refining-association-requests

> As the database observation seems powerfull, the app will surely be "dependent" on this tool. But if this saves lots of time and problematics, it's OK for me. ;)

I know I miss them whenever I have to use another persistence layer :-)
