### ISSUE TITLE
Sharing ValueObservations without Combine or RxSwift

### ISSUE THREAD

**Issue by tcwalther** [groue/GRDB.swift#1083]
**The gist:** The documentation recommends to share observations when possible. It also includes an example for RxSwift. However, in a regular UIKit application that doesn't use RxSwift or Combine, how do you recommend sharing an observation?

---

The particular use case is:
- I have a controller that controls audio playback. It holds the current playlist and the currently playing song. It observes both the playlist and the song, because changes in the playlist impact skip forward/back behaviour, and changes in the song impact information shown in the iOS Media Center.
- I have a second view controller in my app showing information about the currently playing song - a "now playing" view. This view controller isn't always visible/in the hierarchy, because users can close the view and browse through other parts of the app while the audio continues to play. The now-playing view also needs to stay up-to-date with changes in the currently playing playlist (to enable/disable skip-forward/back buttons), as well as changes to the song (such as changes to its title).

I have created two observations in the playback controller. The playback controller is a singleton that I can access throughout my application. Is it possible, in the now-playing view controller, to say something like:

```
self.songObservation = PlaybackController.shared.songObservation.replay()
```

The alternative solution is to just send notifications instead. But if there was a way to simply copy and share an observation, that would be fantastic.

And since I have the opportunity to write this here: thanks so much for your work on GRDB! ❤️

**Comment by groue** [comment]
`SharedValueObservation` has shipped in v5.13.0 - [documentation](https://github.com/groue/GRDB.swift/blob/v5.13.0/README.md#valueobservation-sharing)
