### ISSUE TITLE
Load file database to memory database

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#109]
I have a project where speed is critical - every keystroke the database is being read.
I believe the database is optimized and indexed efficiently.

How can I quickly load the entire database into memory and access it as an in-memory database?

**Comment by groue** [comment]
Hello @mtissington. Did you try the [backup](https://github.com/groue/GRDB.swift#backup) method?

```swift
// Open an empty in-memory database...
let dbQueue = DatabaseQueue()
// ...and copy the entire database at dbPath in it
try DatabaseQueue(path: dbPath).backup(to: dbQueue)
```

It uses the dedicated [SQLite Online Backup API](https://www.sqlite.org/backup.html): we can hope it is fast enough.

**Comment by mtissington** [comment]
Hello,

 

I have tried it now – unfortunately I don’t see much speed improvement.

Need to look further at optimization ..

**Comment by groue** [comment]
Use Instruments.app, Michael, and come back with a specific bottleneck!

**Comment by mtissington** [comment]
... My optimization comment was directed at me!
