### ISSUE TITLE
ValueObservation while excluding specific columns

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1101]
### What did you do?

Let's say I have a model called `MyModel`. It has three props: `a`, `b` and `c`.
I'm using ValueObservation over it, for example:

```swift
let observation = ValueObservation.tracking { MyModel.fetchAll() }
return observation.start(
    in: dbQueue,
    onError: ...,
    onChange: ...
)
```

But, I'd like that specifically changes to column `b` won't cause a new set of values to be sent from the observation (basically ignoring changes to that column).

Is that possible? cc/ @nirlachman-monday

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.12
**Installation method:** CocoaPods
**Xcode version:** 12.5
**Swift version:** 5.4
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Big Sur / Monterey

**Comment by groue** [comment]
Hello @freak4pc,

It is not currently possible to exclude some columns from the observation.

It used to be... But the `ValueObservation.tracking { whatever }` syntax was so simple & sexy I dropped everything else! 😅 

If column `c` should be excluded from _tracking_, and if you can exclude it as well from _fetching_, you can try one those two techniques:

1. Fetch a "smaller model":

```swift
struct MySmallModel: FetchableRecord, TableRecord, Decodable {
    static let databaseTableName = MyModel.databaseTableName
    static let databaseSelection: [SQLSelectable] = [Column("a"), Column("b")]
    var a: ...
    var b: ...
}

let observation = ValueObservation.tracking(MySmallModel.fetchAll)
return observation.start(
    in: dbQueue,
    onError: ...,
    onChange: ...
)
```

2. Fetch raw rows, and turn them into `MyModel` with some dummy `c` value:

```swift
let request = MyModel
    .select(Column("a"), Column("b"))
    .asRequest(of: Row.self)
let observation = ValueObservation
    .tracking(request.fetchAll)
    .map { row in MyModel(a: row["a"], b: row["b"], c: someDummyValue) }
return observation.start(
    in: dbQueue,
    onError: ...,
    onChange: ...
)
```

You can use [`print()`](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservationprint) in order to precisely verify which tables & columns are tracked by the observation.

I think those techniques have advantage over excluding `c` from tracking, because you _control_ the value of `c` (missing, or initialised to some specific value).

Do you think one of them could work for you?

**Comment by freak4pc** [comment]
Thanks for the super-quick answer! 
We considered these options (mainly the 2nd one), but the problem is we actually want that column value. We just don't want changes to it to incur a new "emitted" change from the database. 

We could theoretically do that in the "Combine/Rx" level (distinctUntilChanged/scan/et-al) but having something like this in GRDB would feel much more natural IMO.

**Comment by groue** [comment]
You can consider this issue as a bring-back-this-feature request, and an opportunity for contributing.

I am not sure I can provide a much better solution right now.

You can explore [DatabaseRegionObservation](https://github.com/groue/GRDB.swift/blob/master/README.md#databaseregionobservation), or even the [TransactionObserver protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#transactionobserver-protocol), but you'll need some elbow grease.

**Comment by groue** [comment]
OK, this is a relatively easy feature to bring back.

You will write:

```swift
let trackedRequest = MyModel.select(Column("a"), Column("b"))
let observation = ValueObservation.tracking(region: trackedRequest, fetch: { db in
    MyModel.fetchAll(db)
})
return observation.start(
    in: dbQueue,
    onError: ...,
    onChange: ...
)
```

`ValueObservation.tracking(region:fetch:)` will accept a variadic list of DatabaseRegionConvertible values ([DatabaseRegion](https://github.com/groue/GRDB.swift/blob/master/README.md#databaseregion) and [requests](https://github.com/groue/GRDB.swift/blob/master/README.md#requests)):

```swift
// Triggered by all transactions
ValueObservation.tracking(
    region: .fullDatabase,
    fetch: { db in ... })

// Triggered by all changes to player with rowid 1
ValueObservation.tracking(
    region: Player.filter(id: 1),
    fetch: { db in ... })

// Triggered by all changes to the score column of the player table
ValueObservation.tracking(
    region: SQLRequest("SELECT MAX(score) FROM player"),
    fetch: { db in ... })

// Triggered by all changes to player or team tables
ValueObservation.tracking(
    region: Player.all(), Team.all(),
    fetch: { db in ... })
```

Such an observation only tracks the explicit list of regions (it does not automatically infer the tracked region from the fetched values).

This can ship shortly. Do you think it would address your need?

**Comment by freak4pc** [comment]
That seems perfect, actually. thank you so much for checking this so quickly 🙌 
If it doesn't incur any special performance penalty that would be incredible! 💯

**Comment by groue** [comment]
I don't expect any performance penalty: the tracked region will be compiled by SQLite once, when the observation starts.

**Comment by freak4pc** [comment]
I’d be super happy to have this available. It fits our rather unique use case quite well :)

**Comment by groue** [comment]
It it were _really_ unique I wouldn't add it ;-)

**Comment by freak4pc** [comment]
Oh yeah, that's fair :) 
I meant that we have a unique use case where tracking all of the columns would incur a lot of wasteful computations "downstream", so this would be a super fitting solution for it.

**Comment by groue** [comment]
No, don't worry. All observations need to know _what_ to track, so this feature fits quite well with the library. See https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservationhandleevents

**Comment by groue** [comment]
PR #1102 implements the [above api](https://github.com/groue/GRDB.swift/issues/1101#issuecomment-983907284), I just need to update documentation and it will be ready to ship.

**Comment by groue** [comment]
You're welcome, thanks for the good idea :-)

**Comment by freak4pc** [comment]
A question popped into my head around this.

Is there any practical different between `ValueObservation.tracking { Player.fetchAll($0) }` and `ValueObservation.tracking(region: .fullDatabase, fetch: { Player.fetchAll($0) })` ?

**Comment by StuClift** [comment]
If I understand what @groue posted in the earlier comment: the first will fetch `Players` when there is a change to the `Players` table, the second will fetch `Players` when there is a change to **any** table.

**Comment by groue** [comment]
> If I understand what @groue posted in the earlier comment: the first will fetch `Players` when there is a change to the `Players` table, the second will fetch `Players` when there is a change to **any** table.

Exactly

**Comment by freak4pc** [comment]
So the parallel would be `region: Player.all()`, correct?

**Comment by groue** [comment]
Yes!

**Comment by groue** [comment]
When you write `region: request`, you define a [DatabaseRegion](https://github.com/groue/GRDB.swift/blob/master/README.md#databaseregion). The request is never executed. It is compiled by SQLite, which tells GRDB what are the involved tables, columns, and rows.

**Comment by groue** [comment]
It just happens requests are a very handy way to define regions.
