### ISSUE TITLE
Can't use the `TransactionObserver` protocol

### ISSUE THREAD

**Issue by enricenrich** [groue/GRDB.swift#1111]
### What did you do?

Implement a class that conforms to the `TransactionObserver` protocol.

### What did you expect to happen?

Allow me to observe all the events from the database.

### What happened instead?

Xcode keeps showing this error:

```
Type 'MyObserver' does not conform to protocol 'TransactionObserver'
```

If I click the "Fix" button of the error, it adds the `databaseDidCommit` and `databaseDidRollback` functions even tho' they are already there. This ends up with the errors:

```
Invalid redeclaration of `databaseDidCommit`
Invalid redeclaration of `databaseDidRollback`
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.16.0
**Installation method:** SPM
**Xcode version:** 13.1
**Swift version:** 5.5.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.0.1

### Demo Project

```swift
class MyObserver: TransactionObserver {
    func observes(eventsOfKind eventKind: DatabaseEventKind) -> Bool {
        true
    }

    func databaseDidChange(with event: DatabaseEvent) {
        debugPrint("Did Change: \(event)")
    }

    func databaseWillCommit() throws {
        debugPrint("Will Commit")
    }

    func databaseDidCommit(_ db: Database) {
        debugPrint("Did Commit: \(db)")
    }

    func databaseDidRollback(_ db: Database) {
        debugPrint("Did Rollback: \(db)")
    }
}
```

<img width="1020" alt="Code Screenshot" src="https://user-images.githubusercontent.com/357265/145708756-3cd97ca4-c71b-4107-849a-05627bc5d5f6.png">

**Comment by groue** [comment]
Hello @enricenrich,

Your code looks quite valid, and indeed I can't reproduce your errors.

Maybe you have a `Database` type in your project which shadows the one from `GRDB`. If this is the case, rename your type, or use an explicit `GRDB.Database`:

```swift
func databaseDidCommit(_ db: GRDB.Database) {
    debugPrint("Did Commit: \(db)")
}

func databaseDidRollback(_ db: GRDB.Database) {
    debugPrint("Did Rollback: \(db)")
}
```

If you don't have any `Database` type in your project, then you're in for taming Xcode:

- Clean the build folder (Xcode > Product > Clean Build Folder) and rebuild
- Quit Xcode, relaunch, and rebuild
- Quit Xcode, delete `~/Library/Developer/Xcode/DerivedData`, relaunch, and rebuild
- Quit Xcode, delete all the `xcuserdata` directories in your project which may contain corrupted Xcode caches, relaunch, and rebuild

If you still see the errors after those steps, then please produce a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by enricenrich** [comment]
>Maybe you have a `Database` type in your project which shadows the one from `GRDB`. If this is the case, rename your type, or use an explicit `GRDB.Database`:

You were right! I also have a `Database` type in my project. Applied your suggestion of using `GRDB.Database` and now the error is gone as expected. Thanks for the quick and detailed reply.
