### ISSUE TITLE
Can FetchOne to an existing Object?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1114]
We hope to re read the value from the database to an existing object, because we need to ensure that the memory address of the whole object is unchanged.

Is there a convenient way to accomplish this requirement? Because we have a lot of watches.

thank you

**Comment by groue** [comment]
Hello @SF-Simon,

No, this feature is not built-in. You should be able to do it from your app, though:

```swift
extension Player {
    func reload(_ db: Database) throws {
        guard let row = try Row.fetchOne(db, Player.filter(id: id)) else {
            throw /* some error telling that the player could not be reloaded */
        }
        update(from: row)
    }
    
    func update(from row: Row) {
        name = row["name"]
        score = row["score"]
    }
}

let player: Player = ...
try dbQueue.read { db in
    try player.reload(db)
}
```

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> No, this feature is not built-in. You should be able to do it from your app, though:
> 
> ```swift
> extension Player {
>     func reload(_ db: Database) throws {
>         guard let row = try Row.fetchOne(db, Player.filter(id: id)) else {
>             throw /* some error telling that the player could not be reloaded */
>         }
>         update(from: row)
>     }
>     
>     func update(from row: Row) {
>         name = row["name"]
>         score = row["score"]
>     }
> }
> 
> let player: Player = ...
> try dbQueue.read { db in
>     try player.reload(db)
> }
> ```

Thank you. That's a good idea.
