### ISSUE TITLE
Can Not Import in Swift Playgrounds 4 on iPad

### ISSUE THREAD

**Issue by MoSchaub** [groue/GRDB.swift#1115]
In Swift Playgrounds 4 you can now create apps and this includes using Swift Packages via SPM. So I tried importing this Package by tapping on the icon with the doc and the plus and next swift package. Next I pasted https://github.com/groue/GRDB.swift into the textField in the modal sheet and I hit enter and it shows the error: "package has no version tags".
I hope my description is accurate enough to reproduce. I tried other packages and they seem to work fine. I also tried the url: https://github.com/groue/GRDB.swift.git instead. This results in the exact same error message

**Comment by groue** [comment]
Hello @MoSchaub,

GRDB had version tags before the Swift package manager was invented 😉 

I'm sorry you can't use GRDB from the promising Swift Playgrounds 4, but there's nothing I can do. Please report the problem to Apple, at https://feedbackassistant.apple.com, with the same accurate description of your problem. Maybe mention that this lib has version tags, and works fine with SPM on Xcode.

**Comment by groue** [comment]
Oh, also... Maybe Swift Playgrounds is picky about the package URL: try `https://github.com/groue/GRDB.swift.git`.

**Comment by sena-mike** [comment]
It seems the issue is that Swift Playgrounds 4 is not able to handle releases with a `v` prefix, e.g. `v5.17.0`. I was able to work around this by forking and pushing a tag with `5.17.0`.

**Comment by groue** [comment]
Didn't you meet this error message, @sena-mike?

> The target type, "systemModule", is not supported

https://twitter.com/damienpetrilli/status/1472144736983134211?s=21

**Comment by sena-mike** [comment]
Just noticing that now. Same issue here.
