### ISSUE TITLE
Crash when decoding certain items from the DB

### ISSUE THREAD

**Issue by cristianilea-lateral** [groue/GRDB.swift#1118]
### What did you do?

My table contains a column that is of type TEXT and there I store a struct that conforms to Codable and therefore it gets converted to a JSON string when it is stored in the DB.
Inside the struct there is a String property that actually stores a base64 string (converted from an image).
So you can imagine that the json gets pretty big - but I don't think the size is the issue here.

### What did you expect to happen?

I expected the DB to be able to decode anything I throw at it.

### What happened instead?

I get an error:

`GRDB/FetchableRecord+Decodable.swift:7: Fatal error: 'try!' expression unexpectedly raised an error: column not found: "longitude" - row: [id:1 uuid:Data(16 bytes) priority:2 ....`

Unfortunately I can't show more information due to the nature of my project.

The table doesn't have any "longitude" column, it just happen that inside the JSON there are some longitude fields. I suspect this issue has to do with how the JSON is escaped/unescaped and the fact that the base64 might break that process.

### Environment

**GRDB flavor(s):** nothing special - (i don't quite understand this question)
**GRDB version:** 5.13.0
**Installation method:** cocoapods
**Xcode version:** Version 13.2.1 (13C100)
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.1 beta

**Comment by groue** [comment]
Hello @cristianilea-lateral 

The error message is pretty explicit. Overcome your irrealistic expectation that "the DB is able to decode anything I throw at it." and you will fix your issue.

**Comment by groue** [comment]
... and if you do think something is wrong with GRDB, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), thanks!
