### ISSUE TITLE
How can i get notification only on db really changed?

### ISSUE THREAD

**Issue by karthuszY** [groue/GRDB.swift#1119]
### What did you do?

I observe the count of db,it dosen't have any change,but i get twice notification
```
        let assetsObservation = ValueObservation.tracking(NFTModel.fetchCount(_:))

        assetsCancellable = assetsObservation.start(
            in: db,
            scheduling: .async(onQueue: .main), // <- immediate scheduler
            onError: { error in
                
            },
            onChange: {[weak self]  _ in
                guard let self = self else { return }
//                self.refresh()
                print("didRefresh")
            })
```

### What did you expect to happen?

I want get notification only when the count of db really changed

### What happened instead?

It called onChange twice,but the db dosen't have any change.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @karthuszY,

The [ValueObservation documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation-usage) says:

> ValueObservation may notify consecutive identical values. You can filter out the undesired duplicates with the [removeDuplicates](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservationremoveduplicates) method.

This gives:

```swift
let assetsObservation = ValueObservation
    .tracking(NFTModel.fetchCount(_:))
    .removeDuplicates()
```

**Comment by karthuszY** [comment]
Thanks very much. I didn't notice that.

**Comment by groue** [comment]
See also https://github.com/groue/GRDB.swift/issues/937
