### ISSUE TITLE
Is there a way to use select query on joining methods?

### ISSUE THREAD

**Issue by fbertuzzi** [groue/GRDB.swift#1122]
### What did you do?

I'm trying to create this SQL Query:
```SQL
SELECT
	"chatContainer".*,
	"profile".*,
	"chatGroup".*,
	"message".*
FROM
	"chatContainer"
	LEFT JOIN "profile" ON "profile"."profileId" = "chatContainer"."profileId"
	LEFT JOIN "chatGroup" ON "chatGroup"."groupId" = "chatContainer"."groupId"
	LEFT JOIN "message" ON "message"."messageId" = (
		SELECT
			"messageId"
		FROM
			"message"
		WHERE
			"receiverId" = "chatContainer"."profileId"
			OR "receiverId" = "chatContainer"."groupId"
			OR "ownerId" = "chatContainer"."profileId"
		ORDER BY
			"timestamp" DESC
		LIMIT 1)
```

But I can't find a way on running a Select inside of a `joining` or `include` function.

The query I can generate is following:

```SQL
SELECT
	"chatContainer".*,
	"profile".*,
	"chatGroup".*
FROM
	"chatContainer"
	LEFT JOIN "profile" ON "profile"."profileId" = "chatContainer"."profileId"
	LEFT JOIN "chatGroup" ON "chatGroup"."groupId" = "chatContainer"."groupId"
```

It's basically missing the last part, where I join the message in.

```swift
...
ChatContainer
    .including(optional: ChatContainer.profile)
    .including(optional: ChatContainer.chatGroup)
...

//profile and chatGroup have a belongsTo Association:
public static let profile = belongsTo(Profile.self)
    
public var profile: QueryInterfaceRequest<Profile> {
    request(for: ChatContainer.profile)
}
    
public static let chatGroup = belongsTo(ChatGroup.self)
    
public var chatGroup: QueryInterfaceRequest<ChatGroup> {
    request(for: ChatContainer.chatGroup)
}
```

This is how my database is structured: 
![diagram](https://user-images.githubusercontent.com/11597095/147763948-abe8a9d8-8645-4703-b94d-ca58a9454b3f.png)

Is there a way to achieve the query I'm looking for?

### Environment

**GRDB flavor(s):** GRDB with custom added SQLCipher using SPM
**GRDB version:** 5.17.0
**Installation method:** SPM
**Xcode version:** 13.2.1
**Swift version:** 5.5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** macOS 12.1

**Comment by fbertuzzi** [comment]
I actually found the solution in the documentation:

https://github.com/groue/GRDB.swift/blob/master/Documentation/CommonTableExpressions.md

It even mentions a ChatApp as Example.

**Comment by fbertuzzi** [comment]
> I actually found the solution in the documentation:
> 
> https://github.com/groue/GRDB.swift/blob/master/Documentation/CommonTableExpressions.md
> 
> It even mentions a ChatApp as Example.

However this will only work if you have a field pointing at the chatContainer. If you just have the fields ownerId and receiverId like I do in my example, what I want to achieve, above this will probably most likely not work. So I'm still curious if there is a way to generate the query I provided above.

**Comment by groue** [comment]
Hello @fbertuzzi,

I'm afraid your request can not be generated, because of the LEFT JOIN with fully custom ON clause.

So your best choice is likely to use your raw SQL request just as it is. GRDB helps you consuming rows that contain columns from several tables: [Joined Queries Support](https://github.com/groue/GRDB.swift/blob/master/README.md#joined-queries-support).

**Comment by fbertuzzi** [comment]
Okay, thank you for the reply!

For now I'm working with the CommonTableExpressions. It's not the same but it works for now!
