### ISSUE TITLE
Crash: libswift_Concurrency which was built for iOS 13.0

### ISSUE THREAD

**Issue by iosWhale** [groue/GRDB.swift#1123]
I'm using GRDB version 5.17.0, and when I run the project on iOS 12 it crashes,

dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/containers/Bundle/Application/842F47CC-A858-41F7-B938-7A8FAEE3FE4D/******/Frameworks/libswift_Concurrency.dylib (which was built for iOS 13.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/containers/Bundle/Application/842F47CC-A858-41F7-B938-7A8FAEE3FE4D/******/Frameworks/libswift_Concurrency.dylib
 
 I guess that's because GRDB is using 'await' now, should i downgrade the version or what ?

**Comment by groue** [comment]
Hello @iosWhale,

This is a known Xcode issue: https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917

You'll read there this message by a member of the Swift core team:

> At this time, there is no known workaround for the issue with iOS 12.

So yes, as long as you target iOS versions older than 13, you'd better stick with GRDB v5.16.0 (until Apple fixes their tool).

**Comment by groue** [comment]
See also https://forums.swift.org/t/app-distributed-via-testflight-crashes-on-launch/53936

**Comment by iosWhale** [comment]
@groue Thanks a lot,
I ended up with downgrading GRDB version to 5.16.0 to solve this issue.

**Comment by groue** [comment]
For anyone who wants to use the latest GRDB version on iOS/tvOS < 13:

- Fork the project
- Delete all code that mentions `Sendable`, `_Concurrency`, or `async`.

**Comment by serges147** [comment]
BTW, the same story for macOS 10.12 & 10.13 (probably 10.14 as well). On 10.15+ it works. And `5.16.0` helps.

**Comment by groue** [comment]
I unpin this issue since it is [fixed in Xcode 13.3](https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917/29).
