### ISSUE TITLE
can't install pod on 2.3 branch

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#113]
I have this in my pod file

  pod 'GRDB.swift', :git => 'git@github.com:groue/GRDB.swift', :branch => 'Swift2.3'

I get the following error after a pod update command

[!] Error installing GRDB.swift
[!] /usr/bin/git clone git@github.com:groue/GRDB.swift /var/folders/xh/vdw0gz7x5g97lfh05dkc6hkc0000gn/T/d20160910-12507-z0gxij --template= --single-branch --depth 1 --branch Swift2.3

Cloning into '/var/folders/xh/vdw0gz7x5g97lfh05dkc6hkc0000gn/T/d20160910-12507-z0gxij'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bradleydwyer** [comment]
Try the HTTPS URL instead. The one you have is for access via SSH (the publickey denied part of the error).

https://github.com/groue/GRDB.swift.git

**Comment by mtissington** [comment]
Thanks - that fixed it

**Comment by groue** [comment]
Oops, the documentation was using the ssh URL. Thanks @mtissington and @bradleydwyer
