### ISSUE TITLE
Remove compiler condition for ENABLE_PREUPDATE_HOOK?

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#1135]
If I'm not missing something (which is very possible) it seems like GRDB now only support OSs that comes with a system version of SQLite built with `ENABLE_PREUPDATE_HOOK`. So would it be possible to remove the special flag required to enable that feature in GRDB? Or is there something else holding that back?

I'm asking because I'd love this feature but am all in on SPM which still doesn't seem to be able to flip that flag to on. :/

**Comment by groue** [comment]
Hello @simme! It would be cool to enable those apis with `@available` indeed!

Requirements currently are:

> iOS 11.0+ / macOS 10.10+ / tvOS 9.0+ / watchOS 2.0+

Do you happen to know which iOS/macOS/tvOS/watchOS versions start shipping with `ENABLE_PREUPDATE_HOOK`? Any reference?

---

For information, you have other ways to enable `ENABLE_PREUPDATE_HOOK` (I didn't test those techniques, but they should work more or less out of the box):

- With Cocoapods:

    ```ruby
    pod 'GRDB.swift'

    post_install do |installer|
      installer.pods_project.targets.select { |target| target.name == "GRDB.swift" }.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = "$(inherited) -D ENABLE_PREUPDATE_HOOK"
        end
      end
    end
    ```

- With SPM: Fork GRDB, and append `swiftSettings: [.define("ENABLE_PREUPDATE_HOOK")]` to the definition of the "GRDB" target in Package.swift. That's how [other people](https://github.com/groue/GRDB.swift/network) enable FTS5 support via SPM.

**Comment by simme** [comment]
> Do you happen to know which iOS/macOS/tvOS/watchOS versions start shipping with ENABLE_PREUPDATE_HOOK? Any reference?

Admittedly I was only reading the [wiki page](https://github.com/groue/GRDB.swift/wiki/SQLite-versions) which upon closer inspection really only lists iOS. Sorry, I got ahead of myself.

I didn't consider the forking option. I'll run with that for now, thanks!
