### ISSUE TITLE
Combine two QueryInterfaceRequests into one

### ISSUE THREAD

**Issue by uyalejo** [groue/GRDB.swift#1136]
### What did you do?

I have multiple `QueryInterfaceRequest` that have different filters. Now I want to support combining these filters among each other, so that they result on the records that meet all the criteria.

For example, let's say I have the following two requests:
```swift
let frenchRequest = Wine
        .filter(countryColumn == "France")
    
let redRequest = Wine
        .filter(colorColumn == "red")
```

And the following records on the Wines table:
| Id  | Country |  Color |
| ------------- | ------------- | ------------- |
| 1  | Spain | Red |
| 2  | France | White |
| 3  | France | Red |

Running the `frenchRequest` would return rows `[2, 3]`, while running the `redRequest` would return the rows `[1. 3]`. 

I would like to know how would you build a new request joining the two others that returns only row `3`.

**Note:** I know I can just implement the following code, but I am thinking of a generic solution that would me to combine requests programatically.
```swift
let combinedRequest = Wine
        .filter(countryColumn == "France")
        .filter(colorColumn == "Red")

``` 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.18.0
**Installation method:** SPM
**Xcode version:** 13.2.1
**Swift version:** 5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @uyalejo,

You can not combine two requests, but you can build one request with a combined filter:

```swift
let filter1 = countryColumn == "France"
let filter2 = colorColumn == "Red"
let combinedFilter = filter1 && filter2

let combinedRequest = Wine.filter(combinedFilter)
```

**Comment by groue** [comment]
No news is good news. Happy GRDB!
