### ISSUE TITLE
Bizarre query results joined results across two tables

### ISSUE THREAD

**Issue by oddanderson** [groue/GRDB.swift#1147]
### What did you do?

Listening to DB changes produces bizarre results on insertion.

I am listening to results like this:
```
let request = Event
    .annotated(withRequired: Event.contact.select(
        Column("id").forKey("contactId"),
        Column("name").forKey("contactName")))
     .asRequest(of: EventInfo.self)
     let observation = ValueObservation.tracking { db -> [Row] in
         let eventRows = try Row.fetchAll(db, request)
         return eventRows
    }
    .map { rows in rows.map(EventInfo.init(row:))}
    cancellable = observation.start(
        in: SharedUser.user.dbPool,
        scheduling: .immediate,
        onError: { error in print("events could not be fetched") },
        onChange: { [weak self] (newEvents: [EventInfo]) in
            print ("onChange fired")
            if (newEvents.count == 0) {
                print ("empty results")
            } else {
                print ("happy!!!")
            }
            self?.refreshEvents(newEventInfo: newEvents)
         })
```

So I am listening to both Event and Contact and combining the result into EventInfo. When my app loads up, I immediately fire off network requests to fetch Events and Contacts from the server, in separate API calls. Here is the insertion code that gets triggered for each return result for the network requests:
```
func updateAllEventsFromJson(newEvents: [[String: Any]]) {
    let newEvents = newEvents.map { Event(using: $0)}
    do {
        try dbPool.writeInTransaction { db in
            try Event.deleteAll(db)
            for event in newEvents {
                try event.insert(db)
            }
             return .commit
         }
         print("update events finished")
         events = newEvents
    } catch {
          print (error)
    }
}
func updateAllContactsFromJson(newContacts: [[String: Any]]) {
        let newContacts = newContacts.map {Contact.init(fromJson: $0)}
        do {
            try dbPool.writeInTransaction { db in
                let allContactIds = try Contact.fetchAll(db).map {$0.id!}
                let allAddressIds = try Address.fetchAll(db).map {$0.id!}

                var contactIds: [Int64] = []
                var addressIds: [Int64] = []
                for contact in newContacts {
                    contactIds.append(contact.id!)
                    try contact.insert(db)
                    if let addresses = contact.addresses {
                        for address in addresses {
                            addressIds.append(address.id!)
                            try address.insert(db)
                        }
                    }
                }
                let addressIdsToDelete = Array(Set(allAddressIds).subtracting(Set(addressIds)))
                try Address.filter(ids: addressIdsToDelete).deleteAll(db)
                let contactIdsToDelete = Array(Set(allContactIds).subtracting(Set(contactIds)))
                try Contact.filter(ids: contactIdsToDelete).deleteAll(db)
                
                return .commit
            }
            print ("update contacts finished")
            contacts = newContacts
        } catch {
            print (error)
        }
    }
```
I have verified that my network requests are functioning properly, as well as the intermediate DB results. I am receiving the following output on startup:

1. Launch app
2. prints 
```
onChange fired   
happy!!!
```
3. network request getEvents called
4. prints
```
update events finished 
onChange fired
happy!!!
```
5. network request getContacts called
6. prints
```
update contacts finished
onChange fired
empty results
```

### What did you expect to happen?

The empty results statement at the very end is the biggest problem. I have verified that getContacts is not returning an empty result, nor is my conditional deletion code deleting anything. Additionally, if I kill the app immediately following this sequence and reopen it, the correct events/contacts are populating immediately, so I have another layer of proof that the DB looks the way I expect it to.

The second issue is that I only expect the onChange block to fire once in this sequence, when the get requests return identical information to what's already in the DB.

### What happened instead?

Most importantly: OnChange is firing with empty results when it should not
Of concern, but lesser so: removeDuplicates() does not seem to be correctly filtering out duplicate results. In each of my examples, no data has changed from the server but the `onChange` block is firing 3 times instead of once (the immediately)

### Environment

**GRDB flavor(s):SQLCipher (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:5.18
**Installation method: CocoaPods
**Xcode version:13.2.1
**Swift version:5.2
**Platform(s) running GRDB:iOS
**macOS version running Xcode:12.0.1

### Demo

I can put together a demo app if necessary, but it will take time so please let me know.

**Comment by groue** [comment]
> I can put together a demo app if necessary, but it will take time so please let me know

This sentence can't give anyone the will to spend time for you.

You have debugging operators on ValueObservation. They will help you spot where your issue lies:
https://github.com/groue/GRDB.swift/blob/master/README.md#why-is-valueobservation-not-publishing-value-changes

If you eventually find an actual GRDB issue, please _take the time_ to report it properly, thanks.

**Comment by oddanderson** [comment]
It looks like the issue has to do with SQL behavior, not the library.

Specifically:
onConflict: .replace issues a DELETE followed by an INSERT (rather than an UPDATE)
and since I had set onDelete: setNil() it was failing
