### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#115]
[Travis](http://travis-ci.org) would be of great help, considering GRDB aims at supporting:
- three operating systems: macOS / iOS / watchOS
- three variants of SQLite : stock / SQLCipher / custom sqlite build (with [pre-update hook](https://github.com/groue/GRDB.swift#support-for-sqlite-pre-update-hooks))
- three methods of integration: manual / Cocoapods / Carthage
- two Swift language versions: Swift 2.3 and Swift 3

Any help would be greatly appreciated in this rigorous task

**Comment by skreutzberger** [comment]
Have a look at "Just" - they are doing it very well including Cocoapods and Carthage. 

The important files are:
https://github.com/JustHTTP/Just/blob/master/.travis.yml
https://github.com/JustHTTP/Just/blob/master/Makefile

**Comment by groue** [comment]
That's a very good hint, thanks @skreutzberger!

**Comment by groue** [comment]
Superseded by #213
