### ISSUE TITLE
Possibly wrong documentation for foreignKeysEnabled

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1150]
I noticed the docs for `foreignKeysEnabled` say as follows:
![image](https://user-images.githubusercontent.com/605076/150139410-aff91327-6c0b-455b-8417-9f40f24f1622.png)

I assumed this means that it only enables validity checks - confirming an object with a foreign key refers to something that exists, etc. 

I was very surprised though to see that setting it to `false` also prevent things like `onDelete: .cascade` from working - even if there is nothing wrong with the foreign keys.

More specifically:
1. Have two records with a `belongsTo` relation with a CASCADE on deletion and a foreign key. 
2. Turn on `foreignKeysEnabled` and make sure there are no warnings/issues.
3. Delete a "Parent" record, I correctly see the cascaded delete of the linked records.
4. Turn off `foreignKeysEnabled`
5. Delete a "Parent" record, all linked records are still there

I'm not sure if this is a bug, or simply a documentation issue but I suspect the latter. If it is, I'm happy to submit a PR with updated docs. 

Thank you 🙏

**Comment by groue** [comment]
Hello @freak4pc,

You're right, the wording is poor. The flag controls the whole [SQLite Foreign Key Support](https://www.sqlite.org/foreignkeys.html), which covers integrity checks but also cascades, etc.

It should be "If true (the default), support for foreign keys is enabled. See https://www.sqlite.org/foreignkeys.html for more information."

**Comment by freak4pc** [comment]
Fixed in #1151 :) 
Thanks for the quick reply!
