### ISSUE TITLE
Make queue public

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDB.swift#1157]
I have several places in my code base which should be executed only once at a time. I currently have an own queue and a DatabasePool. The DatabasePool is backed by a private DispatchQueue. Lot's of time, I need to do something with the database so I use pool.write and I know the code is executed serial. Sometimes I don't need the database so I use my own queue.

I now check if the code is on one of either queues:

```
func runningSerialCode() -> Bool {
    guard
        let queueName = String(
            cString: __dispatch_queue_get_label(nil),
            encoding: .utf8
        ) else {
        return false
    }

    return queueName == "GRDB.DatabasePool.writer" || queueName ==
        myDispatchQueue
}
```

However a race condition can still occur when code is executed in the GRDB queue and code is executed in my own queue and both call the same mutating function. Opening a write block everytime on the DatabasePool to just use the queue is a bit expensive I guess.

Is it possible to just expose that queue? That way I can remove my own queue. Or make a sync method on DatabasePool which can be used which doesn't open a transaction.

**Comment by groue** [comment]
Hello @Jasperav,

I'm not sure I understand you question. `DatabasePool` uses several dispatch queues. That's how it serializes accesses to each individual SQLite connections, and yet support concurrent reads and writes.

Maybe you should better explain what you're after, so that we avoid talking past to each other in a nasty loop of [XY problem](https://xyproblem.info).

**Comment by Jasperav** [comment]
Some more background on why I want this, I have a method which changes a variable. That method can be called while being in the `write` block of a `DatabasePool`. I also call that method when I am not in that `write` block, so I created my own `DispatchQueue` to eliminate race conditions. 

To make sure the method isn't called concurrently, I am stuck with lot's of `queue.sync` and `DispatchQueue` label checking. When I am in the `write` block, I should call `sync` on my own queue to not get race conditions. That looks a bit overkill for me, I thought `write` blocks can not run concurrently.

If I could reuse the queue from `SerializedDatabase` I wouldn't have that hassle anymore.

**Comment by groue** [comment]
> That method can be called while being in the write block of a DatabasePool. I also call that method when I am not in that write block.

Did you challenge this practice before asking for a GRDB change?

**Comment by groue** [comment]
> Did you challenge this practice before asking for a GRDB change?

Maybe I wasn't clear as well.

Considering a database write _can fail_, I'd be wary of modifying some shared state from within a write:

```swift
// Dubious. If the write eventually fails, `written` was set to true anyway.
var written = false
try dbPool.write { db in
    // ...
    written = true
    // ...
}
```

You have another solution, which is to return the new state from the `write` method:

```swift
// Definitely an improvement over the previous version.
var written = false
written = try dbPool.write { db in
    // ...
    return true
}
```

**Comment by Jasperav** [comment]
> > That method can be called while being in the write block of a DatabasePool. I also call that method when I am not in that write block.
> 
> Did you challenge this practice before asking for a GRDB change?

Not yet, maybe I am overthinking. I saw in the Configuration that I can specify a DispatchQueue. I will pass in my own DispatchQueue and switch to DatabaseQueue, that should do the trick

**Comment by groue** [comment]
> Not yet, maybe I am overthinking. I saw in the Configuration that I can specify a DispatchQueue. I will pass in my own DispatchQueue and switch to DatabaseQueue, that should do the trick

Yes you can. Beware that all database pool reads will _also_ use this queue, ruining the pool concurrency 😅 (and you may weep in despair).

_This_ is something that I'm keen to revisit (allow the user to provide different target dispatch queues for writer and readers).

**Comment by groue** [comment]
> _This_ is something that I'm keen to revisit (allow the user to provide different target dispatch queues for writer and readers).

See #1161

**Comment by Jasperav** [comment]
@groue my app deadlocked previously when I did set the targetDispatchQueue to my queue and I did a write/read while I already was in my DispatchQueue sync block, is that issue fixed?

**Comment by groue** [comment]
This is not an issue: this is how dispatch queues work. GRDB can not know that you invoke database methods from the target queue, and this has `DispatchQueue.sync(_:)` deadlock.

I know that this can sound frustrating, that you don't want to refactor the concurrency of your app, or even to take the time to explain how it works, but I'm afraid there's nothing GRDB can do to help. I intend to keep the techniques that support [GRDB Concurrency](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md) private, so the dispatch queues will not become public.
