### ISSUE TITLE
ValueObservation not publishing

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDB.swift#1166]
I want to use ValueObservation, but it's not yet working. This tests below fails, I was thinking it should succeed. setupPool() will return a `DatabaseQueue`. It holds 1 table: User. That table has a column firstName and userUuid (PK). I want to get notified if a User is inserted with a certain firstName.

The test fails because count remains zero. Do you know why this is not working?

```
func testValueObservation() throws {
    let dbQueue = setupPool()
    let toSearchFor = "first"
    let x = ValueObservation
            .tracking { db -> [DbUser] in
                let query = """
                            select * from User where firstName = ?
                            """
                var arguments = StatementArguments()
                arguments += [toSearchFor]
                let statement = try db.cachedStatement(sql: query)
                statement.setUncheckedArguments(arguments)
                let converted: [DbUser] = try Row.fetchAll(statement).map { row -> DbUser in
                    DbUser(row: row, startingIndex: 0)
                }

                return converted
            }
            .publisher(in: dbQueue)
            .eraseToAnyPublisher()

    var count = 0

    let cancellable = x
            .sink(receiveCompletion: { _ in
                XCTFail("Should not complete")
            }, receiveValue: { _ in
                count += 1
            })

    try dbQueue.write { con in
        var user = DbUser.random()

        user.firstName = toSearchFor

        try user.genInsert(db: con)

        user.userUuid = UUID()
        user.firstName = "somethingdifferent"

        try user.genInsert(db: con)

        user.userUuid = UUID()
        user.firstName = toSearchFor
    }

    XCTAssertEqual(2, count)
}
```

**Comment by groue** [comment]
Hello @Jasperav,

Please check the [Why is ValueObservation not publishing value changes?](https://github.com/groue/GRDB.swift#why-is-valueobservation-not-publishing-value-changes) FAQ.

**Comment by groue** [comment]
Also, read [ValueObservation Scheduling](https://github.com/groue/GRDB.swift#valueobservation-scheduling). You'll see that your test, as written, needs to wait for the results.

**Comment by groue** [comment]
Finally, read [ValueObservation Usage](https://github.com/groue/GRDB.swift#valueobservation-usage), and do not miss these sentences that your test should take in consideration:

> ValueObservation may coalesce subsequent changes into a single notification.
> ValueObservation may notify consecutive identical values.

**Comment by Jasperav** [comment]
@groue Thanks for the excellent docs! I was expecting that it would notify the closure right away. I put in an expectation fulfill in the closure block and at the end of the test I wait for the expectation.

It works! Awesome! I should have tried that before opening this issue, sorry!

**Comment by groue** [comment]
No worries :-) Glad you could fix your test!
