### ISSUE TITLE
Ambiguous use of 'fetchAll'

### ISSUE THREAD

**Issue by osteslag** [groue/GRDB.swift#1169]
This is most likely a bug in my code, but I’ve been banging my head against the wall for the last two days, so I hope you can give me a clue or two as to what the problem is. In order to isolate the problem, I made the playground below. However, it does not reproduce the bug which, unsurprisingly, must be in my larger codebase. `Game` in my code only conforms to the protocols shown below.

```swift
import GRDB

let databaseQueue = DatabaseQueue()

struct Game: Hashable, Codable, Identifiable {
	typealias ID = Int64
	var id: Int64
	var title: String
}

extension Game: FetchableRecord, MutablePersistableRecord {
	
	enum Columns {
		static let id = Column(CodingKeys.id)
		static let title = Column(CodingKeys.title)
	}
	
	public mutating func didInsert(with rowID: ID, for column: String?) {
		self.id = rowID
	}
	
	public static let databaseSelection: Array<SQLSelectable> = [Columns.id]
	
	public init(row: Row) {
		self.id = row[Columns.id]
		self.title = row[Columns.title]
	}
}

func observeAllGames() -> ValueObservation<ValueReducers.Fetch<Array<Game>>> {
	
	let observation = ValueObservation.tracking { db -> Array<Game> in
		let request = Game.order(Game.Columns.id.desc)
		return try request.fetchAll(db) // Error: Ambiguous use of 'fetchAll'
	}
	
	observation.start(
		in: databaseQueue,
		onError: { _ in print("Error") },
		onChange: { _ in print("Change") }
	)
	
	return observation
}
```

For the _Ambiguous use of ‘fetchAll’_ error, the compiler points to these two implementations in these two candidates: [`DatabaseConvertible`](https://github.com/groue/GRDB.swift/blob/d40474d2b78fe530d0cf1216c46fd1fc5e30e539/GRDB/Core/DatabaseValueConvertible.swift#L535) and [`FetchableRecord`](https://github.com/groue/GRDB.swift/blob/d40474d2b78fe530d0cf1216c46fd1fc5e30e539/GRDB/Record/FetchableRecord.swift#L477).

I’ve tried various typecasting to remove the ambiguity, but I can’t figure out how. Can you explain why it’s ambiguous and how to fix it?

Thanks in advance,  
Joachim

Configuration:

- Plain GRDB 5.21.0
- Used via SPM
- Xcode 13.3b2 (but also 13.2)
- Swift 5.6 (but also 5.5)
- macOS 12.2

**Comment by groue** [comment]
Hello @osteslag,

> In order to isolate the problem, I made the playground below. However, it does not reproduce the bug which, unsurprisingly, must be in my larger codebase.

Nasty! 😅

I don't know what is happening, I have not seen such an error yet.

Missing imports have the compiler output strange errors sometimes, so make sure that all involved types are imported, with all their apis, in the file that performs this ambiguous `fetchAll`. `import GRDB`, `import Models` (if `Game` is defined in a distinct module), etc.

Check if your app defines a `fetchAll` method somewhere, even on an unrelated type. Maybe its definition messes with the compiler state?

I suppose your code had been compiling until the error started to appear. Maybe try to reduce the diff and distill the offending change to its purest form?

Move the offending `fetchAll` call in its own file?

Clean the project, delete the DerivedData folder, delete all `xcuserdata` folders nested in your `xxx.xcodeproj` and `xxx.xcworkspace`, and have a coffee, or a tea, or an orange-banana smoothie while your Mac is rebooting?

**Comment by osteslag** [comment]
Thanks for a both swift, kind, constructive and informative reply as always, @groue.

Except for the smoothie (good tip, thank you!), I have done or tried all of the above. This is part of moving all cache and iCloud sync code out of the app and into its own module (I’m not even sure it can be done; remember reading about problems with GRDB not being part of the app module?). It was in that first, big operation I started seeing the error (and more than 100s others caused by the move), and it’s therefore not easily reverted or isolated.

Previously, I used it in the simpler form, here explicitly typecast, but it generates the same error::

```swift
let request: QueryInterfaceRequest<Game> = Game.order(Game.Columns.modified.desc)
let observation = ValueObservation.tracking(request.fetchAll) // Error: Ambiguous use of 'fetchAll'
```

I will keep at it and post any findings which might help others in the future.

**Comment by groue** [comment]
I could (almost) reproduce by "forgetting" to add `FetchableRecord` conformance to `Game`:

```swift
import GRDB

struct Game: TableRecord {
    enum Columns {
        static let modified = Column("modified")
    }
}
func f() {
    let request: QueryInterfaceRequest<Game> = Game.order(Game.Columns.modified.desc)
    let observation = ValueObservation.tracking(request.fetchAll)
}
```

**Comment by osteslag** [comment]
I can reproduce it in the Playground now! 💥🥊

If we add conformance on `Game` to `DatabaseValueConvertible`, which is what I have in my package, and which also implements `fetchAll(_:)`, we get the _Ambiguous use of ‘fetchAll’_ (because `FetchableRecord` also implements it). “Curiously”, this is what the compiler said all along. 🤭

Do you know how I can have the `FetchableRecord` implementation explicitly executed? I’ve tried various typecasting and what not, but to no avail:

![](https://theawesomedaily.com/wp-content/uploads/2014/10/l3v4P3s.jpg)

**Comment by osteslag** [comment]
This is immensely helpful, and it makes a lot of sense! I was coming at it the wrong way, thinking that being a `DatabaseValueConvertible` could also represent a whole record via coding somehow.

I hope this thread will be helpful to others as well.

Thank you! 👋

**Comment by groue** [comment]
I do too hope it well help other users! Have a fine day/night, @osteslag :)
