### ISSUE TITLE
Swift 3: restore FetchedRecordsController

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#117]
Issue #116 (Swift 3 Installation Error (Carthage & Manual)) has been "fixed" by removing FetchedRecordsController from the Swift3 branch.

We need it back.

**Comment by groue** [comment]
Swift bug: [SR-2623](https://bugs.swift.org/browse/SR-2623)

**Comment by groue** [comment]
@skreutzberger, @ mtissington, @pierlo: FetchedRecordsController is back.

**Comment by swiftlyfalling** [comment]
@groue: Fantastic narrowing down of the cause. What a crazy Swift compiler bug.

**Comment by groue** [comment]
Yep. This release is time-consuming 😅.

**Comment by mtissington** [comment]
Many thanks!
