### ISSUE TITLE
SQL logic error when adding a new column with a check constraint to an existing table (iOS 15.4 beta)

### ISSUE THREAD

**Issue by phil1995** [groue/GRDB.swift#1171]
### What did you do?

I have performed a migration with an existing table. To this existing table I added another column with a CHECK constraint.

```swift
var migrator = DatabaseMigrator()
migrator.registerMigration("v1") { db in
    try db.create(table: "books", body: { table in
        table.column("price", .double)
    })
}
migrator.registerMigration("v2") { db in
    try db.alter(table: "books", body: { table in
        table.add(column: "title", .text).check { length($0) > 0 }
    })
}
try migrator.migrate(DatabaseQueue())
```

### What did you expect to happen?

A successful migration, i.e. the table `books` now has the columns `price` and `title`, where the `title` column has a CHECK constraint.

### What happened instead?
The table is not migrated successfully, instead the following error messages are logged:

```sh
[logging] flag(s) 0x00008000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
[logging] no such column: books in "SELECT CASE WHEN quick_check GLOB 'CHECK*' THEN raise(ABORT,'CHECK constraint failed') ELSE raise(ABORT,'NOT NULL constraint failed') END  FROM pragma_quick_check("books","main") WHERE quick_check GLOB 'CHECK*' OR quick_check GLOB 'NULL*'"
[logging] SQL logic error in "ALTER TABLE "books" ADD COLUMN "title" TEXT CHECK (LENGTH("title") > 0)"
SQLite error 1: SQL logic error - while executing `ALTER TABLE "books" ADD COLUMN "title" TEXT CHECK (LENGTH("title") > 0)`
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.21.0
**Installation method:** SPM
**Xcode version:** 13.3 beta 2 (13E5095k)
**Swift version:** 5.6
**Platform(s) running GRDB:** 15.4 beta 2 (19E5219e)
**macOS version running Xcode:** 12.2

**Comment by groue** [comment]
Hello @phil1995,

With my copy of GRDB 5.21.0, your sample code:

- runs fine on Xcode 13.2.1 (system SQLite)
- throws an error on Xcode 13.2.1 (custom SQLite build, version 3.37.2)
- runs fine on Xcode 13.3 beta 2, iOS 15.0 simulator (SQLite version 3.36.0)
- throws an error on Xcode 13.3 beta 2, iOS 15.4 simulator (SQLite version 3.37.0)

Well done, it looks like you found a regression with SQLite!

The following statements have started failing somewhere between 3.36.0 and 3.37.0:

```sql
CREATE TABLE books (price DOUBLE);
ALTER TABLE books ADD COLUMN title TEXT CHECK (LENGTH(title) > 0);
```

The issue [was already reported](https://sqlite.org/forum/forumpost/3c1a00b66fca81fe6192af787eed8abd0c1b2a33dc1eb4ad1f21260340ac5ed3), but it looks like it was improperly fixed. The discussion mentions that [SQLITE_DQS](https://www.sqlite.org/compile.html#dqs) is related to this issue.

This hints at the workaround:

```swift
var config = Configuration()
config.acceptsDoubleQuotedStringLiterals = true // workaround
let dbQueue = DatabaseQueue(configuration: c)
try migrator.migrate(dbQueue) // works
```

I updated the SQLite forum with your bug report. Let's hope this gets fixed eventually!

**Comment by phil1995** [comment]
Thank you for the quick and detailed reply! As I understand it, there should be no further implications to accepting double-quoted string literals - assuming that raw SQL statements are all written in good style, i.e. using the correct single-quoted string literal form?

**Comment by groue** [comment]
Yes, @phil1995, you are correct. And you don't have to worry much: SQLite has been, for many years, accepting the non-standard literals, without affecting many users.

GRDB will never generate "bad style" SQL on its own.

The only risk is for raw SQL you compose yourself. A typical problem is:

```sql
-- Bad style, but will work as expected
UPDATE player set name = "Arthur" WHERE id = 1;

-- Bad style, and will NOT work as expected if email happens to be a column
UPDATE player set name = "email" WHERE id = 1;
```

But you should never compose such SQL anyway, and use statement arguments instead:

```swift
let id: Int64 = 1
let name: String = ... // "Arthur" or "email", whatever
try db.execute(sql: """
    UPDATE player set name = ? WHERE id = ?
    """, arguments: [name, id])
```
