### ISSUE TITLE
Question: FTS4 and synchronize table

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#1174]
Salut Groue, 

Quick question for you. 
I've stumbled onto something weird with a specific FTS table eating a huge amount of memory upon inserting a record. 

This is my schema definition:
``` swift
		try db.create(virtualTable: "fts_email", ifNotExists: true, using: FTS4()) { t in
			t.tokenizer = .simple
			t.synchronize(withTable: Email.databaseTableName)
			t.column(Email.Columns.sender.name)
			t.column(Email.Columns.subject.name)
			t.column(Email.Columns.recipients.name)
			t.column(Email.Columns.cc_recipients.name)
		}
```

Now I nailed down the faulty behavior when inserting an `Email` with weird characters in the `Email.snippet` column.
Given the above definition and the `.synchronize` statement:

1. Are all columns of the synchronized table inserted in the virtual table? 
2. Am I wrong to assume that only the defined columns will be processed and indexed?

P.S.: Using GRDB 4.14, macOS 11.4

Thanks

**Comment by groue** [comment]
Hello @martindufort,

> Are all columns of the synchronized table inserted in the virtual table?
> Am I wrong to assume that only the defined columns will be processed and indexed?

You are correct: synchronized columns are the columns of the virtual table. If the main regular table has more columns, those are not indexed.

The synchronization is performed with [triggers](https://github.com/groue/GRDB.swift/blob/5ee47c3c2765bdfde0f44c2ea9a263f6aa252d63/GRDB/FTS/FTS4.swift#L116-L129), following the [practice recommended by the SQLite documentation](https://www.sqlite.org/fts3.html#_external_content_fts4_tables_).

You'll get the exact definition of those triggers by querying your `sqlite_master` table:

```swift
// Somewhere in the printed rows, you'll find the triggers:
for row in try Row.fetchAll(db, sql: "SELECT * FROM sqlite_master") {
    print(row)
}
```

> a specific FTS table eating a huge amount of memory upon inserting a record

This is concerning! Did you check memory usage by profiling your app?

**Comment by martindufort** [comment]
Interesting!

So I wondering why a column, in this case `email.snippet`, would have an impact since it is not listed in the virtual table list of columns. 

Removing the persistence of this column from the source table, fixed the issue. 
Still investigating the origin of the weird characters.

> Did you check memory usage by profiling your app?
Yep, normally we are hovering around 100-200 MB. 
This issue push it to 4-5 GB. 😳

**Comment by groue** [comment]
All right. Profiling memory with the Instruments application can provide much more detailed information about the origin of the memory consumption (a line that goes up does not tell _why_ the memory goes up).

If you think something is wrong with GRDB, please provide a detailed report. If you think something is wrong with SQLite, report the issue on the [SQLite forums](https://sqlite.org/forum/forummain), and paste here the link to your message there. And if you are clueless after your investigations, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by martindufort** [comment]
OK will do. Thanks.

**Comment by groue** [comment]
Thank your Martin :-) I'll keep the issue opened for a few days.

**Comment by groue** [comment]
Hello @martindufort, please just reopen this issue if you think GRDB can help solving the problem in your app.

**Comment by martindufort** [comment]
Hey @groue, 

Some more feedback on this as we got hit today again with this large memory allocation spike.

So has mentioned before, in some cases, whenever we are performing a fetch request we see those memory spikes....up to 5 GB. 

After that execution is completed, memory usage would settle down to around 86MB for the app. 

I'm attaching two Instruments screenshots that reflects that behavior.

Wanted to make sure we are not triggering any of this in our code. 

![CleanShot 2022-05-06 at 10 49 53](https://user-images.githubusercontent.com/28934641/167157704-35e4e58a-a8b0-4fc8-8ed7-4bc43d4a710f.png)
![CleanShot 2022-05-06 at 10 45 19](https://user-images.githubusercontent.com/28934641/167157826-171ba9bc-ff01-4433-99c3-4a516e4b763d.png)

**Comment by groue** [comment]
Hi @martindufort. Your screenshot shows that SQLite allocates a lot of memory. Because GRDB asks it to. Because your app asks it to. I can't tell who's wrong. I can't investigate with a screenshot (could you?). Please report your findings!

**Comment by martindufort** [comment]
Yeah posting only screenshots  was **not my brightest** moment. 
So I did a lot more investigating and I'm totally puzzled about the issue. 
Here's some more findings...

1) When the spike hits, SQLite is giving me a `Database Error SQLite error 7: out of memory` error

So I attached the sqlite command line directly to the database and did an integrity check.  
``` bash
sqlite> .version
SQLite 3.32.3 2020-06-18 14:16:19 02c344aceaea0d177dd42e62c8541e3cab4a26c757ba33b3a31a43ccc7d4aapl
clang-12.0.5
sqlite> PRAGMA integrity_check;
ok
```

The culprint statement is this one: 
``` sql
SELECT *, "f_conversation_id" AS "grdb_f_conversation_id" FROM "email" WHERE "f_conversation_id" IN ('17f99ec844295a02', '1802434cfc9243d6', '18048263a668a5bd', '18094f7bdc26de5a') ORDER BY "date" DESC
```
which is generated automatically by GRDB for the relationship between related tables. 
Total sizing of the email table is 
``` sql
sqlite> select count(*) from email;
484
```

So I deconstructed the query to see why it was not working. 

**Baffling results**
I tested out the `IN` clause by executing the query individually with each ID.
 
They all worked except for the last one....
``` sql 
SELECT *, "f_conversation_id" AS "grdb_f_conversation_id" FROM "email" WHERE "f_conversation_id" IN ('1802434cfc9243d6') ORDER BY "date" DESC;
1802434cfc9243d6|<CAGyJDtXKCuYuq06Tup0d9mhU-5WPGMFVPkA79Q2V6NjcM0nftw@mail.gmail.com>|1802434cfc9243d6|2022-04-13 18:34:43.000|Attachments, attachment, attachments|{"name":"Martin Dufort","entry":{"mail":"martin@bigwavelabs.co","typeOfEntry":0}}|["CATEGORY_PERSONAL","INBOX"]|Ocean for MacOS (0.9.11-807)|[{"name":"","entry":{"mail":"jake@ocean.app","typeOfEntry":0}}]|null|0|0|0|||"Here's for you. Cheers - Martin"|1802434cfc9243d6|2|1802434cfc9243d6
Run Time: real 0.000 user 0.000128 sys 0.000043

SELECT *, "f_conversation_id" AS "grdb_f_conversation_id" FROM "email" WHERE "f_conversation_id" IN ('18094f7bdc26de5a') ORDER BY "date" DESC;
Run Time: real 4.507 user 1.204103 sys 3.260736
Error: out of memory
```

P.S. This is really not related to GRDB but I'm posting here to close this and potentially see if you would have any insights. Also cross posted to the SQLite forum. 

Thanks - Martin

**Comment by martindufort** [comment]
https://sqlite.org/forum/forumpost/7c13814dc8

**Comment by groue** [comment]
Thank you for investigating and sharing Martin! 👍

**Comment by martindufort** [comment]
OK this error was producing in our application code under a weird edge case. 
See resolution here: https://sqlite.org/forum/forumpost/66f0142a1f

Thanks for the support. 👏🏼

**Comment by groue** [comment]
🤯 That was a nasty bug indeed!! I'm glad you eventually solved it!
