### ISSUE TITLE
Async/await causing apps not process for AppStore when building with Xcode 13.3

### ISSUE THREAD

**Issue by gabors** [groue/GRDB.swift#1185]
This is a new issue that apple introduced in Xcode 13.3.

Basically if your apps support iOS 13 or 14 and you have bitcode enabled and your have libswift_Concurrency.dylib compiled app's Frameworks folder, you will get an ITMS-90562: Invalid Bundle when you try to upload to AppStoreConnect.

See here: https://developer.apple.com/forums/thread/701949

Apple lists is as a known issue in the Xcode 13.3 release notes and their workaround is to disable bitcode :(

Other framework developers. like Alamofire are considering to separate out the concurrency code into its own subspec (for CocoaPods) or module (for SPM).

Please let me know what is the last version of GRDB that has no async/await and thus no libswift_Concurrency.dylib.

Thanks!

**Comment by groue** [comment]
Downgrade to 5.16.0.

**Comment by gabors** [comment]
Thanks @groue 
I don't know how other feel about this, but I would love to keep getting new features and fixes to the core GRDB without needing to use Apple's poorly designed async/await implementation.

**Comment by groue** [comment]
I am quite disappointed by this, indeed. This bad story with concurrency started with #1123. And now this bitcode bug. Meanwhile users are stuck to version 5.16 of the library. Apple is shipping very low quality updates, and we are all losing our time.

I consider stopping this fun little game indeed.

**Comment by groue** [comment]
> Other framework developers. like Alamofire are considering to separate out the concurrency code into its own subspec (for CocoaPods) or module (for SPM).

@gabors Please provide links that support your claim.

**Comment by gabors** [comment]
@groue 

https://github.com/Alamofire/Alamofire/issues/3529#issuecomment-1071906505

**Comment by groue** [comment]
I'm not sure I have to do anything right now, so I'm closing the issue. The policy here is to close issues when nobody is working on it.

Yet I pin the issue, in order to help users find the answer: **downgrade to 5.16.0, and [report a bug to Apple](https://feedbackassistant.apple.com)**.

**Comment by gabors** [comment]
> I'm not sure I have to do anything right now, so I'm closing the issue. The policy here is to close an issue when nobody is working on it.
> 
> Yet I pin the issue, in order to help users find the answer:
> 
> * **[Disable bitcode](https://developer.apple.com/forums/thread/701949), or downgrade GRDB to 5.16.0, or [fork GRDB and remove support for Swift Concurrency](https://github.com/groue/GRDB.swift/issues/1123#issuecomment-1010667690)**
> * **[Report a bug to Apple](https://feedbackassistant.apple.com)**.

Thanks. Curious if you will try to split out the async/await into a separate package?
Discovered that not including the libswift_Concurrency.dylib saves quite a few MBs from the resulting app size :)

**Comment by groue** [comment]
No @gabors. As I just said above, I do not plan to do anything.

Maybe some users will strip support for concurrency in their own forks, and I'm fine with this idea.

Maybe some user will check the [CONTRIBUTING](https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md) document, open a discussion, eventually a pull request, and that would be great.

Maybe Apple will fix their tools, and the problem will vanish.

**Comment by gabors** [comment]
The way you've replied it may seem as you will remove async await support.

**Comment by groue** [comment]
Oh, I see. The ambiguity is removed now :-)

**Comment by groue** [comment]
[Xcode 13.3.1 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3_1-release-notes):

> Resolved Issues
> - Fixed: Exporting an app that uses Swift’s concurrency features from an archive with bitcode might fail when the app targets iOS 13.0–14.7, watchOS 6.0–7.6, or tvOS 13.0–14.7. (89271047)
> - When you target iOS 13.4 and later and enable bitcode, the bitcode segment is now stripped correctly. This fixes a crash that prevented some apps from running in older operating systems (iOS 14 and earlier). (90024354) (FB9951126)

**Comment by groue** [comment]
v5.23.0 has just shipped. Swift concurrency features now require Swift 5.6, and Xcode 13.3.1.
