### ISSUE TITLE
The data is deleted, but the db file size is not reduced.

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#1191]
### What did you do?

* Insert data like this way:
```swift
try queue.write { db in
   try model.insert(db)
}
```
* Delete data like this way:
```swift
try queue.write { db in
   try model.deleteAll(db) }
}
```

I find when insert data, the file size will grow up. but when i delete data. the size is not reduced.

### What did you expect to happen?

I want to reduce the size of db file when i delete the data.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @glve1027,

A database file won't reduce its size unless you request it to do so. See [VACUUM](https://www.sqlite.org/lang_vacuum.html) for more information. And run in your application:

```swift
try dbQueue.vacuum()
```

**Comment by glve1027** [comment]
Thanks~~ Boss

**Comment by groue** [comment]
Happy GRDB!

**Comment by glve1027** [comment]
@groue  Hi. Boss~, I just read this file. [VACUUM](https://www.sqlite.org/lang_vacuum.html), I realized that executing `try dbQueue.vacuum()` is very expensive, do we have other better solutions? or `auto-vacuum`


[more Info](https://www.sqlite.org/faq.html)

> (12) I deleted a lot of data but the database file did not get any smaller. Is this a bug?

> No. When you delete information from an SQLite database, the unused disk space is added to an internal "free-list" and is reused the next time you insert data. The disk space is not lost. But neither is it returned to the operating system.

> If you delete a lot of data and want to shrink the database file, run the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command. VACUUM will reconstruct the database from scratch. This will leave the database with an empty free-list and a file that is minimal in size. Note, however, that the VACUUM can take some time to run and it can use up to twice as much temporary disk space as the original file while it is running.

> An alternative to using the VACUUM command is auto-vacuum mode, enabled using the [auto_vacuum pragma](https://www.sqlite.org/pragma.html#pragma_auto_vacuum).

**Comment by groue** [comment]
I don't know? Did you find something about this feature?

**Comment by groue** [comment]
> An alternative to using the VACUUM command is auto-vacuum mode, enabled using the [auto_vacuum pragma](https://www.sqlite.org/pragma.html#pragma_auto_vacuum).

I missed this quoted paragraph.

Well, everything is well documented by SQLite itself. To run pragmas, use the `execute(sql:)` method:

```swift
try db.execute(sql: "PRAGMA auto_vacuum=...")
```

**Comment by glve1027** [comment]
> 

Yup. But we should excute `try db.execute(sql: "PRAGMA auto_vacuum=...")` at the set up table, right?

**Comment by glve1027** [comment]
We just find someone's db file size is larger than 1G. In that condition. we can not excute [VACUUM](https://www.sqlite.org/lang_vacuum.html). In bad condition. iPhone needs at least 2G memory.

I just use this way to fix:

1. Create a new table with `PRAGMA auto_vacuum=...`. Insert to new table, and will not insert to old table anymore.
2. Also insert datas which from old table. and delete old table anymore.

* In most condition. Although db file size it larger than 1G. the real data counts are less than 100 counts.

**Comment by groue** [comment]
> Yup. But we should excute `try db.execute(sql: "PRAGMA auto_vacuum=...")` at the set up table, right?

Please read the SQLite documentation for this pragma *carefully*. And perform experiments in order to validate your understanding.

**Comment by glve1027** [comment]
👌

**Comment by glve1027** [comment]
Final Summary:

Based on this info:   https://www.sqlite.org/pragma.html#pragma_auto_vacuum.
> The database connection can be changed between full and incremental autovacuum mode at any time. However, changing from "none" to "full" or "incremental" can only occur when the database is new (no tables have yet been created) or by running the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command. To change auto-vacuum modes, first use the auto_vacuum pragma to set the new desired mode, then invoke the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command to reorganize the entire database file. To change from "full" or "incremental" back to "none" always requires running [VACUUM](https://www.sqlite.org/lang_vacuum.html) even on an empty database.

I decide to use this solution: 

1. Create a new table with `PRAGMA auto_vacuum=....` Insert to new table, and will not insert to old table anymore.
2.  Also copy datas from old table to new table. and delete old table anymore.
