### ISSUE TITLE
SharedValueObservationTests fail when run in -O (optimized) mode

### ISSUE THREAD

**Issue by kazrakcom** [groue/GRDB.swift#1192]
### What did you do?

Set GRDBiOS scheme to use Release mode for its Test build.
Turned on Enable Testability for GRDBiOS and GRDBiOS Tests builds in Release mode.
Ran tests with Cmd-U.

### What did you expect to happen?

Tests pass.

### What happened instead?

Test Case '-[GRDBiOSTests.SharedValueObservationTests test_async_observationLifetime]' started.
GRDB.swift/Tests/GRDBTests/SharedValueObservationTests.swift:309: error: -[GRDBiOSTests.SharedValueObservationTests test_async_observationLifetime] : XCTAssertEqual failed: ("["cancel"]") is not equal to ("[]")
GRDB.swift/Tests/GRDBTests/SharedValueObservationTests.swift:313: error: -[GRDBiOSTests.SharedValueObservationTests test_async_observationLifetime] : XCTAssertEqual failed: ("[]") is not equal to ("["cancel"]")
Test Case '-[GRDBiOSTests.SharedValueObservationTests test_async_observationLifetime]' failed (0.981 seconds).
Test Case '-[GRDBiOSTests.SharedValueObservationTests test_async_publisher]' started.

Test Case '-[GRDBiOSTests.SharedValueObservationTests test_immediate_observationLifetime]' started.
Development/GRDB.swift/Tests/GRDBTests/SharedValueObservationTests.swift:46: error: -[GRDBiOSTests.SharedValueObservationTests test_immediate_observationLifetime] : XCTAssertEqual failed: ("["cancel"]") is not equal to ("[]")
GRDB.swift/Tests/GRDBTests/SharedValueObservationTests.swift:50: error: -[GRDBiOSTests.SharedValueObservationTests test_immediate_observationLifetime] : XCTAssertEqual failed: ("[]") is not equal to ("["cancel"]")
Test Case '-[GRDBiOSTests.SharedValueObservationTests test_immediate_observationLifetime]' failed (0.020 seconds).

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)  GRDB stock xcodeproj
**GRDB version:**  v5.22.0 (also reproduces in v5.21.0)
**Installation method:** (CocoaPods, SPM, manual?)  Manual
**Xcode version:**  13.2.1
**Swift version:**  5.5.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)  iOS
**macOS version running Xcode:**  12.3 Intel

### Demo Project

git diff of this config from what's in github:

```
diff --git a/GRDB.xcodeproj/project.pbxproj b/GRDB.xcodeproj/project.pbxproj
index 683b990e3..c9f92ce41 100755
--- a/GRDB.xcodeproj/project.pbxproj
+++ b/GRDB.xcodeproj/project.pbxproj
@@ -4363,6 +4363,7 @@
                                DYLIB_COMPATIBILITY_VERSION = 1;
                                DYLIB_CURRENT_VERSION = 1;
                                DYLIB_INSTALL_NAME_BASE = "@rpath";
+                               ENABLE_TESTABILITY = YES;
                                GCC_NO_COMMON_BLOCKS = YES;
                                INSTALL_PATH = "$(LOCAL_LIBRARY_DIR)/Frameworks";
                                LD_RUNPATH_SEARCH_PATHS = (
@@ -4413,6 +4414,7 @@
                                COPY_PHASE_STRIP = NO;
                                DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
                                DEVELOPMENT_TEAM = "";
+                               ENABLE_TESTABILITY = YES;
                                GCC_NO_COMMON_BLOCKS = YES;
                                INFOPLIST_FILE = Tests/Info.plist;
                                LD_RUNPATH_SEARCH_PATHS = (
diff --git a/GRDB.xcodeproj/xcshareddata/xcschemes/GRDBiOS.xcscheme b/GRDB.xcodeproj/xcshareddata/xcschemes/GRDBiOS.xcscheme
index 23e695577..51e0b1e56 100644
--- a/GRDB.xcodeproj/xcshareddata/xcschemes/GRDBiOS.xcscheme
+++ b/GRDB.xcodeproj/xcshareddata/xcschemes/GRDBiOS.xcscheme
@@ -23,7 +23,7 @@
       </BuildActionEntries>
    </BuildAction>
    <TestAction
-      buildConfiguration = "Debug"
+      buildConfiguration = "Release"
       selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
       selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
       shouldUseLaunchSchemeArgsEnv = "YES"
```

**Comment by groue** [comment]
Thank you for the report, @kazrakcom 👍 Did you look at the reason why these tests would fail in Release configuration?

**Comment by groue** [comment]
This was a bug in the tests, not a bug in SharedValueObservation.

Those tests observe the side effects of the deallocation of a SharedValueObservation. But they were not robust enough, because Swift [does not deallocate objects at the same time, depending on the Debug or Release configuration](https://forums.swift.org/t/a-roadmap-for-improving-swift-performance-predictability-arc-improvements-and-ownership-control/54206).

The fix was to make sure the deallocation happens at the same time in both configurations. It has been pushed to the development branch. It will ship in the next GRDB version (current is 5.22.1).

Again, thanks for the report, @kazrakcom 🙂
