### ISSUE TITLE
Hello, Adding an error to an existing table

### ISSUE THREAD

**Issue by JackMayx** [groue/GRDB.swift#1193]
### What did you do?

![截屏2022-03-24 18 22 02](https://user-images.githubusercontent.com/13148763/159895858-4e6a8f3a-7255-4246-9ce0-8b44db801468.png)

duplicate column name: name in "ALTER TABLE "appsetTable" ADD COLUMN "name" TEXT DEFAULT 'name'; ALTER TABLE "appsetTable" ADD COLUMN "age" INTEGER DEFAULT 22; ALTER TABLE "appsetTable" ADD COLUMN "isName" BOOLEAN DEFAULT 0"
Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1: duplicate column name: name - while executing `ALTER TABLE "appsetTable" ADD COLUMN "name" TEXT DEFAULT 'name'; ALTER TABLE "appsetTable" ADD COLUMN "age" INTEGER DEFAULT 22; ALTER TABLE "appsetTable" ADD COLUMN "isName" BOOLEAN DEFAULT 0`:

### Environment

**GRDB flavor(s):GRDB (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:5.21.0
**Installation method:CocoaPods (CocoaPods, SPM, manual?)
**Xcode version:13.3
**Swift version:5.6
**Platform(s) running GRDB: iOS (iOS, macOS, watchOS?)
**macOS version running Xcode: 12.3 (21E230)

**Comment by groue** [comment]
Hello @JackMayx,

The error message is pretty clear:

`duplicate column name: name`

You can't add a column named "name" to a table that already has a column named "name".

I strongly suggest you have a look at [Migrations](http://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md). They will help your application evolve its database schema over time.

**Comment by JackMayx** [comment]
O！I understand the problem, thank you.
