### ISSUE TITLE
Delete the db file but a strange file appeared

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#1199]
### What did you do?
1. Delete unused db file
```swift
try FileManager.default.removeItem(atPath: dbPath)
```

2. `xxx.db` disappear, but a strange file which called `xxx.db-journal` appear

### What did you expect to happen?
Completely delete a database without appear a strange file.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @glve1027,

See [this comment](https://github.com/groue/GRDB.swift/issues/164#issuecomment-312468700) for more information about SQLite temporary files, and a suggested technique for deleting a database from disk.

**Comment by glve1027** [comment]
Thx~
