### ISSUE TITLE
Proposal: QueryInterface Extensibility 

### ISSUE THREAD

**Issue by hdlj** [groue/GRDB.swift#120]
Hello Groue!

The query interface is very convenient! However I didn't succeed to extend it. 

I needed to implement more complex queries like recursive queries, multiple joins, triggers, sqlite `CASE` expression, .. . 

I needed something more close to sqlite grammar  like the object: _SQLSelectQuery but it is internal. More precisely, I was looking for the possibility to write swift custom sqlite translators which can be combined with the ones provided by GRDB. 

With the current implementation, I didn't find a way to combine queries except for some specific case as:

```
    /// For example `id IN (SELECT ...)`
    case inSubQuery(_SQLSelectQuery, _SQLExpression)
    
    /// For example `EXISTS (SELECT ...)`
    case exists(_SQLSelectQuery)
    
```

I wanted to access the sql string generated without the need of a database object to generate it and then execute it inside the database with for example : ``` db.excute(sqlTranslationOfMyCustomRequest) ```. 

It could be interesting to have a public Sqlite wrapper which can be extended. 

```

public protocol SQLConvertible: FetchRequest {
    var sql: (query: String, arguments: StatementArguments) { get }
}

extension SQLConvertible {
       public func prepare(_ db: Database) throws -> (SelectStatement, RowAdapter?) {
            let (query, arguments) = self.sql
            let statement = try db.makeSelectStatement(query)
            try statement.setArgumentsWithValidation(arguments)
            return (statement, nil)
    }
}

extension _SQLExpression: SQLConvertible { ... }
extension _SQLSelectQuery: SQLConvertile { ... }

public struct SQLJoin {
    .....
}

``` 

By this way, API users could implement their own sqlite translator for different sqlite features which are not implemented inside GRDB.

It could offer the possibility to avoid pure Sqlite String which can be error prone and be very closed to the Sqlite grammar at the same time :)

Thanks!

**Comment by groue** [comment]
Hello @hdlj

I'm interested talking about extensibility of the query interface.

Before we dive into any implementation details, I think we should set a clear target first.

I suspect that you did implement your own query builder. An all-purpose builder that can generate any kind of select and update statement. You did not try to build your extensions right into your fork of GRDB.

You are suggesting that your custom query builder should ship with GRDB, and fuel the query interface. The extensibility of the query interface would be a consequence of the extensibility of this query builder.

As a reminder, here is a general tour of the query interface:

- QueryInterfaceRequest
    
    This type can select, count, and delete:
    
    ```swift
    let request = Person.filter(Column("name") == "Arthur")
    
    // SELECT * FROM persons WHERE name = 'Arthur'
    request.fetchAll(db)
    
    // SELECT COUNT(*) FROM persons WHERE name = 'Arthur'
    request.fetchCount(db)
    
    // DELETE FROM persons WHERE name = 'Arthur'
    request.deleteAll(db)
    ```
    
- Persistence methods
    
    ```swift
    // INSERT INTO persons (...) VALUES (...)
    try person.insert(db)
    ```
    
- Schema DSL
    
    ```swift
    // CREATE TABLE persons (...)
    try db.create(table: "persons") { t in ... }
    ```

Please confirm or invalidate my interpretation and guesses.

Also, please show me an example of code that is not possible to write today, and that you wish was possible, assuming that your proposal is integrated. Don't be general, and pick a specific example. I prefer talking about services before talking about the way they're implemented.

**Comment by groue** [comment]
I suggest that you provide your example as a scenario in four steps:

1. I want to write *piece of code*, but it is not supported right away
2. Fortunately, GRDB provides *this protocol/type/method*
3. I thus just have to write *piece of code*, so that I can eventually...
4. ... write *target piece of code*

**Comment by groue** [comment]
I also hope that the last step of the scenario can be:

- ...I'm eventually so proud of this robust and useful extension that I can submit a PR.

**Comment by groue** [comment]
@hdlj I've been working on extensibility lately. I've followed an evolutionary process, preserving and enhancing the strong typing on top of which the SQL grammar is implemented today. There is still no multi-purpose `SQLConvertible` protocol which may be convenient but looks aimed at generating invalid SQL.

It is not possible yet to extend the SQL grammar implemented by the QueryInterfaceSelectQueryDefinition (formerly _SQLSelectQuery). I may have to introduce the dreaded `SQLConvertible` protocol eventually 😉

But all closed enums have been replaced with public protocols, and the work is complete on [SQL expressions](https://www.sqlite.org/lang_expr.html). This means that you can right away add support for any missing SQLite function, operator, or even expression kind (such as `CAST`, or `CASE ... WHEN ... ELSE ... END`).

 You'll see at https://github.com/groue/GRDB.swift/blob/Extensibility/Documentation/ExtendingGRDB.md an in-progress documentation on extending GRDB.

**Comment by groue** [comment]
@hdlj, a good amount of work has been done, merged into the master branch, and is almost ready to ship.

Not everything is open, and that some parts have remain closed (with pull requests welcome). Thanks to you, the query interface inner types are much more robust and stable now: GRDB user can now enhance their database accesses without having to wait for their feature request to be implemented. The [GRDB Extension Guide](https://github.com/groue/GRDB.swift/blob/master/Documentation/ExtendingGRDB.md) is for you.

I'm closing this issue now. Feel free to open more specific issues.

**Comment by hdlj** [comment]
Hi @groue!

I am truly sorry not to answer you earlier. The past two weeks was very busy. 

Thanks a lot for all your detailed messages and the new extensibility of GRDB!! 

I will work on it to adapt the wrapper I wrote, If I have any question I will open a more specific issue :)  

Thanks again!

**Comment by groue** [comment]
You're welcome Hubert. FYI, I'm working on FTS3/4/5 and I'm close from an initial release.

**Comment by groue** [comment]
FTS support is tracked at https://github.com/groue/GRDB.swift/issues/92

**Comment by groue** [comment]
@hdlj A new extension opportunity has shipped: [custom requests](https://github.com/groue/GRDB.swift#custom-requests).
