### ISSUE TITLE
How to properly restore the database?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1204]
I backed up the database from A to B file.

`try AWriter.backup(to: BWriter)`

Now, we need to let the user restore B's data to A. (complete, and A's version may be higher than B's)

A database may be in use.

In this case, is it necessary to completely delete the A database, create a new file, and then execute the backup method?

**Comment by groue** [comment]
Hello @SF-Simon,

The [Using the SQLite Online Backup API](https://www.sqlite.org/backup.html) SQLite documentation does not talk about the restore step. That's unfortunate 😅 

Clearly, you sure must not mess directly with the file system while SQLite connections are open. See [How To Corrupt An SQLite Database File](https://www.sqlite.org/howtocorrupt.html).

So... Maybe close all connections to A, then backup B to A's path, then perform whatever changes are needed to deal with your "versions", and then allow accesses to A again? You will run your own experiments.

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> The [Using the SQLite Online Backup API](https://www.sqlite.org/backup.html) SQLite documentation does not talk about the restore step. That's unfortunate 😅
> 
> Clearly, you must not mess directly with the file system while SQLite connections are open. See [How To Corrupt An SQLite Database File](https://www.sqlite.org/howtocorrupt.html).
> 
> So... Maybe close all connections to A, then backup B to A's path, then perform whatever changes are needed to deal with your "versions", and then allow accesses to the restored A again? You will run your own experiments.

thanks, @groue 

Do I need to delete the path A file? (original database file)

Or will this backup process make my A file exactly the same as my B file?

**Comment by groue** [comment]
I don't think you have to delete the database. Definitive information is in the linked SQLite doc, and the observed behavior of the programs you write.
