### ISSUE TITLE
Compiler error: @usableFromInline only available for internal functions (Row.swift:169)

### ISSUE THREAD

**Issue by gmoraleda** [groue/GRDB.swift#1206]
### What did you do?

I'm in the process of moving the checkout folder of SPM to a custom one so that I'm able to cache and restore it in my CI.
While compiling the packages from the extracted folder, the compiler throws the following error:

> /SourcePackages/checkouts/GRDB.swift/GRDB/Core/Row.swift:169:5: '@usableFromInline' attribute can only be applied to internal declarations, but '_checkIndex(_:file:line:)' is public

### What did you expect to happen?

GRDB should compile correctly. 

### What happened instead?

The compiler throws the above-mentioned error.
The error can be corrected by either commenting out the `@usableFromInline` or by making the `_checkIndex` function internal.

### Environment

**GRDB flavor(s):**  GRDB
**GRDB version:** 5.23.0 (although I tried also older versions, e.g. 5.15.0)
**Installation method:** SPM
**Xcode version:** 13.2.1
**Swift version:** 5.5.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.3.1

**Comment by groue** [comment]
Hello @gmoraleda,

GRDB is tested in [many SPM setups](https://github.com/groue/GRDB.swift/blob/v5.23.0/Makefile#L391). Including with Xcode 13.2.1 (on Apple Silicon).

So your CI does something that is not tested.

Maybe your CI setup needs some fixing 😈

Maybe GRDB could be enhanced in order to support your CI setup 👼

In order to decide, a detailed report is necessary.

**Comment by gmoraleda** [comment]
The setup includes fastlane, with [this specific setting](https://docs.fastlane.tools/actions/scan/#:~:text=cloned_source_packages_path) to point to a specific path where the packages are cloned.

That's the breaking setting (both locally on an M1 and on CircleCI x64-86).

**Comment by groue** [comment]
Hm. Nothing much interesting here. Let's maybe re-read your report:

> '@usableFromInline' attribute can only be applied to internal declarations, but 'checkIndex(:file:line:)' is public

I don't get this. There is no such `checkIndex(:file:line:)` method in GRDB 5.23.0.

> The error can be corrected by either commenting out the @usableFromInline or by making the _checkIndex function internal.

In GRDB 5.23.0 there is a `_checkIndex` function that is [`internal`, not public](https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/Row.swift#L171).

> Maybe your CI setup needs some fixing 😈

This is my current understanding.

**Comment by gmoraleda** [comment]
> In GRDB 5.23.0 there is a _checkIndex function that is [internal, not public](https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/Row.swift#L171).

This is really interesting. If I look at the source files, I see that the CHANGELOG contains a reference to 5.23 (so I'd assume that's the version I'm in). The extension you are pointing to, though, is marked as `public`:
![image](https://user-images.githubusercontent.com/25835012/164728381-01c67ac3-179d-4590-901f-d00ce5302995.png)

🤔

**Comment by groue** [comment]
Yep. Try to make sure your GRDB copy is the latest (5.23.0).

**Comment by gmoraleda** [comment]
Ok. I've set up a new project.
Running this commands:
```
xcodebuild -resolvePackageDependencies -scheme "GRDBTest"  -clonedSourcePackagesDirPath SourcePackages
```
and then

```
xcodebuild \
  -project GRDBTest.xcodeproj \
  -scheme 'GRDBTest' \
  -destination 'platform=iOS Simulator,name=iPhone 8' \
  -clonedSourcePackagesDirPath SourcePackages \
  build
```
Have a successful output.


I'm going to close the issue then, as clearly there is something going on with the package resolution on my main project.
Perhaps the Package.resolved got corrupted 🤔 

In any case. Thanks a lot for your help.

**Comment by groue** [comment]
You're welcome! We all love a second pair of eyes :-) Feel free to report your findings, in case another user would meet your issue!

**Comment by gmoraleda** [comment]
For anyone facing something remotely similar: In my case was [swiftformat](https://github.com/nicklockwood/SwiftFormat) adding that `public` modifier in the extension.
As I moved SPM packages out of the DerivedData folder into the project root folder, they were also being formatted by swiftformat 🤦 
(just to make it clear: not blaming swiftformat, but my stupidity for not taking that into account).
