### ISSUE TITLE
Hook that enables database querying/modification before explicit transaction commit

### ISSUE THREAD

**Issue by swiftlyfalling** [groue/GRDB.swift#121]
Hi @groue:

I have a use-case where it would be particularly useful to be able to check/modify the database immediately prior to a transaction COMMIT - i.e. akin to a hypothetical "(explicit) transaction trigger".

SQLite itself only supports statement triggers, and the existing `TransactionObserver. databaseWillCommit()` can't support this because it's triggered by `sqlite3_commit_hook` (which is not reentrant  and doesn't support reading/modifying the database connection).

My thought, however, is that `Database` *could* support this, inside its `inTransaction` method.

A proposal:

```swift
extension Database {
    public func add(explicitTransactionHook: ExplicitTransactionHook) { ... }
    public func remove(explicitTransactionHook: ExplicitTransactionHook) { ... }

    public protocol ExplicitTransactionHook: class {
        /// Optionally query or modify the database at the very end of the explicit transaction (before the COMMIT).
        ///
        /// This method is called on the database queue. It can change the database.
        func databaseExplicitTransactionPreCommitHook(_ db: Database)
    }
}
```

And inside the `inTransaction` method, immediately after the block() returns, and prior to `try commit()`, all explicitTransactionHooks would have their `databaseExplicitTransactionPreCommitHook(_ db: Database)` called.

This would make it incredibly simple to monitor / aggregate change information in a TransactionObserver, and then issue database reads/writes depending on those changes in the databaseExplicitTransactionPreCommitHook. (Simply by implementing both `TransactionObserver` and `ExplicitTransactionHook`.)

(In one particular case, I'm looking to increment a version identifier that is logically associated with a certain table / set of records whenever they are modified - and as part of the transaction. It should not increment for every change in a transaction, but instead increment once if any of the affected rows/tables are changed in a transaction.)

EDIT: Originally had this as part of TransactionObserver, but since this implementation would only apply to explicit transactions, I modified it.

This is something that I only need for explicit transactions. (Implementing this for implicit transactions - single statements - seems unnecessary, because triggers can be used.)

It would be great to be able to add this once via adding an ExplicitTransactionHook to the database, instead of trying to manually wrap each explicit transaction block.

**Comment by swiftlyfalling** [comment]
Alternative structure:

```swift
extension Database {
    func add(explicitTransactionHook: ExplicitTransactionHook) { ... }

    protocol ExplicitTransactionHook: class {
        func databaseExplicitTransactionPreCommitHook(_ db: Database)
    }
}
```

Then a single class could implement `TransactionObserver` *and* `ExplicitTransactionHook`.

**Comment by groue** [comment]
Hello @swiftlyfalling 

I understand your request, and I see how the `ExplicitTransactionHook` helps.

Such hook only applies to explicit transactions (wrapped in BEGIN... COMMIT). Implicit transactions (the ones that implicitely wrap any statement executed outside of a transaction) fall off the radar. That means that if you forget to wrap your updates in a transaction, the hook doesn't apply.

Don't you think it is fragile design? Yes, you took care putting "Explicit" in the protocol name. But it does not make the concept less error-prone.

This makes your request look ad-hoc: the feature, along with its pitfalls, suits you, and only you. I'm reluctant to accept the feature request in its current form.

My own take on the subject would be to explicitely perform the hook, right before the commit.

**Comment by swiftlyfalling** [comment]
@groue:

Agreed that this is fragile. It's a shame that SQLite's `sqlite3_commit_hook` isn't sufficient to provide this capability.

What I have now is, in fact, a wrapper that effectively does what you suggested (it wraps a DatabasePool, and exposes its own `writeInTransaction` method - using that to compose the additional block at the end of the provided transaction block). I just wanted to raise this issue in case you (or anyone else) had a suggestion for a way similar functionality might be expanded or fit into GRDB.

(Of note, the wrapper is slightly more complex because subclassing DatabasePool isn't an option - but that also may not be something that makes sense to change in GRDB.)

In general, it would be great if there were some way to create a "transaction trigger" that applied to *any* type of transaction (implicit or explicit) and also ran as *part* of that transaction, but that would seem to require SQLite-level changes.

In any case, appreciate your feedback on my musings on the issue. I have a solution that works, there's no immediately better solution, so let's consider this issue already-solved and still-solved. ☺️

**Comment by groue** [comment]
> @groue:
> 
> Agreed that this is fragile. It's a shame that SQLite's `sqlite3_commit_hook` isn't sufficient to provide this capability.
> 
> What I have now is, in fact, a wrapper that effectively does what you suggested (it wraps a DatabasePool, and exposes its own `writeInTransaction` method - using that to compose the additional block at the end of the provided transaction block). I just wanted to raise this issue in case you (or anyone else) had a suggestion for a way similar functionality might be expanded or fit into GRDB.

You're always welcome!

> (Of note, the wrapper is slightly more complex because subclassing DatabasePool isn't an option - but that also may not be something that makes sense to change in GRDB.)

I sometimes consider this option: opening DatabasePool, DatabaseQueue and Database for subclassing. I'm waiting for the compelling feature request.

I have considered talking about subclassing in my previous comment, but eventually restrained myself: subclassing is hardly the best option in our case, again because of fragility. You'd have to override inTransaction, but also inSavepoint, and possibly deal with the savepoint stack. This means that not only Database should be audited for "subclassability", but we'd also need a few extra "protected" methods dedicated to this feature request. I eventually did not feel comfortable suggesting this option.

> In general, it would be great if there were some way to create a "transaction trigger" that applied to *any* type of transaction (implicit or explicit) and also ran as *part* of that transaction, but that would seem to require SQLite-level changes.

Totally. That's the gist of it!

> In any case, appreciate your feedback on my musings on the issue. I have a solution that works, there's no immediately better solution, so let's consider this issue solved and still-solved. ☺

Those discussions are very useful! Writing things down help us clarifying our ideas, and slowly converge on what GRDB is :-)
