### ISSUE TITLE
RecordEncoder<T>.superEncoder(forKey:) does not update the codingPath

### ISSUE THREAD

**Issue by Kloenk** [groue/GRDB.swift#1210]
### What did you do?
Tried to encode a property wrapper to JSON, where the property wrapper needs an instance to the Encoder, as it does not conform to `Encodable`.

### What did you expect to happen?
Calling `container.superEncoder(forKey: key)` should return an encoder with `codingPath` set to  `[key]`.

### What happened instead?
The `codingPath` of the result still states `[]`.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.23.0
**Installation method:** SPM
**Xcode version:** 13.3.1
**Swift version:** 5.6
**Platform(s) running GRDB:** iOS, macOS
**macOS version running Xcode:** 12.3.1

**Comment by groue** [comment]
Hello @Kloenk,

Can you be much more specific, please?

**Comment by Kloenk** [comment]
I can try.

The Encoder given by the JSONEncoder in the swift standard library gives me a container. When I call superEncoder(for:) on this container I get a new encoder, which has appended the key I gave to the superEncoder function to the codingPath. This can be used to encode a sub key with a function that only accepts a raw encoder. 

Calling this superEncoder function on the GRDB Encoder interface does not update the codigPath, therefor I cannot encode this function call to a sub key/row, but instead GRDB tries to encode it as separate columns, which fails.

**Comment by groue** [comment]
Thank you :-)

I'm not super familiar with superEncoders. I did not meet the need for them yet, and you're the first reporting this issue.

So now is a good time to fix this :-)

Are you yourself familiar enough with super encoders? Do you think you could submit a pull request that provides the expected fix?

**Comment by Kloenk** [comment]
I have a rather busy week this week. Hopefully next week I can look at it again. Maybe you can tell me where/how a struct is encoded to json, then maybe I can figure it out.

**Comment by groue** [comment]
Thanks for sharing your experience! The files are EncodableRecord+Encodable.swift, and FetchableRecord+Decodable.swift in https://github.com/groue/GRDB.swift/tree/master/GRDB/Record

**Comment by Kloenk** [comment]
Part one of 2 implemented. Now have to figure out how to do the Decoder. Seems a bit more complicated :)

**Comment by groue** [comment]
Thank you @Kloenk! I'm having a week of vacations starting tomorrow, so please be patient until I come back!

**Comment by Kloenk** [comment]
No worries, have fun in your vacation. Mine is starting a week after :)

**Comment by groue** [comment]
#1216 was unfinished, and closed.

Issues do not stay open here, unless somebody is working on it. I do not plan to work on it _right now_, so I'm flagging with "needs revisiting". Maybe when @Kloenk will provide some sample code that currently fails, we'll know better what this is all about (the "needs user input" label is still there).
