### ISSUE TITLE
Recommended way of inserting/updating related records

### ISSUE THREAD

**Issue by mpoimer** [groue/GRDB.swift#1215]
### What did you do?

I'm trying to setup a relationship between two tables.
The data I get from the API already contains a relationship and I want to break this up and save it correctly to the db and then correctly read it.

Here's the rough draft of what I'm trying to accomplish (I hope this makes sense).

/*
CREATE TABLE IF NOT EXISTS `articles` (
`id` TEXT NOT NULL,
`name` TEXT NOT NULL,
PRIMARY KEY(`id`)
)
 */

/*
 CREATE TABLE IF NOT EXISTS `article_barcodes` (
 `article_id` BLOB NOT NULL,
 `barcode` TEXT NOT NULL,
 PRIMARY KEY(`article_id`, `barcode`),
 FOREIGN KEY(`article_id`)
 REFERENCES `articles`(`id`)
 ON UPDATE NO ACTION ON DELETE CASCADE
 )
 */

This is how I get the data from the API.

```
struct APIArticle: Codable, TableRecord {
    static var databaseTableName: String {
        "articles"
    }
    
    let id: String
    let name: String
    let barcodes: [String]?
}
```

```
extension APIArticle: PersistableRecord {
    
    func encode(to container: inout PersistenceContainer) {
        container["id"] = id
        container["name"] = name
    }
    
    func save(_ db: Database) throws {
        try performSave(db)
        
        if let barcodes = barcodes {
            let mapped = barcodes.map { DBBarcode(articleId: id, barcode: $0) }
            for map in mapped {
                try map.save(db)
            }
        }
    }
    
}
```

I got the idea for this from [this](https://github.com/groue/GRDB.swift/issues/358#issuecomment-391852388) Issue from a few years ago. Since this post is already a few years old and I'm really new to GRDB, I wanted to ask if this is "recommended" or if there is any better solution to this?

```
struct DBBarcode: Codable, TableRecord, PersistableRecord, FetchableRecord {
    static var databaseTableName: String {
        "article_barcodes"
    }
    
    let articleId: String
    let barcode: String
}
```

```
struct AppArticle: TableRecord, FetchableRecord {
    static var databaseTableName: String {
        "articles"
    }
    
    let id: String
    let name: String
    let barcodes: [String]?
    
    init(row: Row) {
        self.id = row["id"]
        self.name = row["name"]
        self.barcodes = nil // how to get Barcodes here?
    }
    
}
```

And here I don't know how to correctly read it back.

I already read [this](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#convention-for-the-hasmany-association), but it does not show how to write associations.

Any help would be appreciated.
Thanks in advance!

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 5.24.0
**Installation method: SPM
**Swift version: 5.6
**Platform(s) running GRDB: iOS
**macOS version 12.3.1 running Xcode: 13.3.1

**Comment by groue** [comment]
Hello @mpoimer,

Your schema looks good at first glance.

Please check again the Associations guide, and particularly the last paragraphs about [`including(all:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall).

They tell you how to fetch a single column (`barcode`) of associated records, and feed your `barcodes: [String]` property. Quoting the documentation example:

```swift
// Fetch all authors along with the titles of their books
struct AuthorInfo: Decodable, FetchableRecord {
    var author: Author
    var bookTitles: [String]
}
let authorInfos = try Author
    .including(all: Author.books
        .select(Column("title"))
        .forKey("bookTitles"))
    .asRequest(of: AuthorInfo.self)
    .fetchAll(db)
```

You will adapt the sample code to your custom models.

If you do not want to use `Decodable`, and want to use the raw `init(row: Row)`, then it will be somewhat harder. You'll need to check [Decoding a Joined Request with FetchableRecord](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#decoding-a-joined-request-with-fetchablerecord), probably [Debugging Request Decoding](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#debugging-request-decoding), and use the [Row.prefetchedRows](http://groue.github.io/GRDB.swift/docs/5.24/Classes/Row.html#/s:4GRDB3RowC14prefetchedRowsAC010PrefetchedD4ViewVvp) property.

**Comment by mpoimer** [comment]
Thanks for the quick reply @groue!
And many thanks for help getting started.

I think I now understand how to fetch a table with Associations - thanks for clarification!
But how would i persist your example?

Would it be like the approach in my question, so I override for example the save function and in there try to save the article and barcodes into their own corresponding table?
Like this?

```swift
struct APIArticle: Codable, TableRecord, PersistableRecord {
    static var databaseTableName: String {
        "articles"
    }
    
    var id: String
    var name: String
    var barcodes: [String]
    
    func encode(to container: inout PersistenceContainer) {
        container["id"] = id
        container["name"] = name
    }
    
    func save(_ db: Database) throws {
        try performSave(db)
        
        let mapped = barcodes.map { ArticleBarcode(articleID: id, barcode: $0) }
        for var barcode in mapped {
            try barcode.save(db)
        }
    }
    
}
```

My goal is to persist the APIModel correctly, and when fetching it, converting it back to an APIModel.

**Comment by groue** [comment]
Well, your `APIArticle` is not a proper persistable record, because a persistable record deals with a **single** table.

You can not have both article and barcode data in a single type AND have this type conform to `TableRecord` and `PersistableRecord`. That's just not what those protocols are made for.

- `TableRecord + PersistableRecord ` = one table
- data from multiple tables = not a `TableRecord + PersistableRecord`.

You can still design a composite type, but don't make it conform to protocols it should not conform to:

```swift
// ONE TABLE: PERSISTABLE
struct Article: Codable, FetchableRecord, PersistableRecord {
    var id: String
    var name: String
}

// ONE TABLE: PERSISTABLE
struct ArticleBarcode: Codable, FetchableRecord, PersistableRecord {
    var articleID: String
    var barcode: String
}

// NOT ONE TABLE: NOT A PERSISTABLE RECORD
struct APIArticle {
    var id: String
    var name: String
    var barcodes: [String]
}

extension APIArticle {
    func save(_ db: Database) throws {
        try Article(id: id, name: name).save(db)
        for bardcode in barcodes {
            try ArticleBarcode(articleID: id, barcode: barcode).save(db)
        }
    }
}
```

You will adapt this sample code for your own needs.

And don't fight the framework. Instead, put it on your side!

**Comment by groue** [comment]
OK you were shown how to save and fetch. Let's close this issue now. Have a nice journey with GRDB records!

**Comment by mpoimer** [comment]
Again, thank you very much!
