### ISSUE TITLE
Is it possible to cache rows?

### ISSUE THREAD

**Issue by djordje-jovic** [groue/GRDB.swift#1218]
### What did you do?

I work on some commercial project (iOS app) and I decided to use GRDB library to manage SQLite database, but at the moment we have legacy code on back-end (BE) side and big changes are not allowed at the moment.
The project hardly depends on BE side which provides SQL statements which should be executed on iOS side.
Some of the (same) SQLs are executing multiple times when user scrolls table-view (i.e. 65 execution per one row in table view) which creates lag on UI side (UITableViewDataSourcePrefetching is implemented and improves as much as it can).

Does GRDB library has some mechanism for caching obtained rows from database?
If so, could you provide me some demo code or instructions how to use it?

I saw some [statements cache](https://github.com/groue/GRDB.swift#prepared-statements-cache) in pretty long documentation file, but I'm afraid that purpose is different of what I need?

### What did you expect to happen?

I would like for library to cache obtained rows (for particular sql) which will be obtained next time from cache instead from database.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24.0
**Installation method:** CocoaPods
**Xcode version:** 13.3.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.2.1

**Comment by groue** [comment]
Hello @djordje-jovic,

GRDB has no built-in row or value caching mechanism.

The statement cache is not about caching values. It is about caching the compiled SQL statements themselves.

First and foremost: did you try using a plain `NSCache`?

Now, SQLite itself has some level of cache, but I did not really look at the documentation about it. This may be worth explorating, starting from the SQLite documentation.

I also think it is possible to build something which is close to a cache with GRDB's `SharedValueObservation`. Check the doc, and see #1093 for more information.

That's the most I can tell today. Please report the results of your investigation!
