### ISSUE TITLE
Migrate FMDB to GRDB

### ISSUE THREAD

**Issue by bluedaquiri** [groue/GRDB.swift#1220]
Hello, groue. GRDB is a very great library. Thank you very much. @groue 
I'm so sorry. My English  is so poor. 
Looking forward to your reply.

I'm looking to migrate database from FMDB to GRDB, but I don't know much about sqlite, so I would like to ask you a few questions.

Background:
1.The FMDB database is stored in the App Group and uses standard rollback mode
2.FMDB uses the encryption function of SQLCipher4

Expected:
Use GRDB's WAL mode and avoid the 0xdead10cc problem as much as possible

Questions:
1. Mode switching problem, can the same db file be directly switched from standard rollback mode to WAL mode?
2. The key modification problem, in order to avoid the 0xdead10cc problem in WAL mode, the same db file, is there a way for me to directly modify the previous key A to `cipher_plaintext_header_size = 32` and `PRAGMA key = key B` and continue to use it ?

I want to do a database migration, and I want the changes to be as small as possible, as this is critical to the stability of our application.

Can I now migrate from FMDB to GRDB using the same db file?
Or do I have to regenerate a new db file and read out the old data and write to the new db file to complete the migration from FMDB to GRDB?

Environment

GRDB flavor(s): SQLCipher
GRDB version: 5.24.0
Installation method: CocoaPods
Xcode version: 13.3
Swift version: 5.3+
Platform(s) running GRDB: iOS

**Comment by groue** [comment]
Hello @bluedaquiri,

> I'm looking to migrate database from FMDB to GRDB, but I don't know much about sqlite, so I would like to ask you a few questions.

This should not be too hard. I've been a heavy FMDB user myself, and GRDB can do pretty much everything FMDB can.

> 1. Mode switching problem, can the same db file be directly switched from standard rollback mode to WAL mode?

Yes. Just open your database file with a `DatabasePool`. This will switch to WAL mode.

> 2. The key modification problem, in order to avoid the 0xdead10cc problem in WAL mode, the same db file, is there a way for me to directly modify the previous key A to `cipher_plaintext_header_size = 32` and `PRAGMA key = key B` and continue to use it ?

I do not know. You will have to perform experiments, and maybe ask questions to SQLCipher.

All I can say is in the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide. Use this guide as a starting point.

> Can I now migrate from FMDB to GRDB using the same db file?

GRDB won't prevent you from using the same database file.

> avoid the 0xdead10cc problem as much as possible

_This is the hardest problem._

GRDB can help, but it will be _very difficult to do_, almost _impossible to test_, and you will have to _learn a lot on your own_.

My personal advice is to stop sharing the database, and find another way to communicate between your app and its extensions. Maybe take the  migration from FMDB to GRDB as an opportunity to refactor this part of your app?

**Comment by groue** [comment]
I guess your questions were answered. I'm closing this issue.

**Comment by bluedaquiri** [comment]
Thanks for your reply.
I will try to complete the migration next month.
