### ISSUE TITLE
`.annotated(...).select(...)` doesn't work and makes me sad

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#1223]
### What did you do?

I "annotated" a query interface request with a named expression (a window expression to be exact) and then selected that column. Then I attempted to `.fetchAll()` the results.

### What did you expect to happen?

I expected the results to include a column with the value of the annotation.

### What happened instead?

GRDB "forgot" the annotation and tried to select a column from the table. That didn't work. I became sad and frustrated. 😢

### Elaboration

Suppose we have a table named "version" with the following schema:

```sql
CREATE TABLE "version" (
  "id" integer PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "rating" integer NOT NULL
);
```

The following code throws an error:

```swift
try Table("version").all()
  .annotated(with: SQL(sql: "row_number() over (partition by rating order by name) as position"))
  .select(literal: "id, position")
  .fetchAll(db)
```

SQLite reports that it received the following query:

```sql
SELECT id, position FROM "version"
```

Dang. Naturally this is a problem because:

1. There is no `position` column in `version`.
2. Even if there were, I want the named expression, not a table column.

What to do?

### Environment

**GRDB flavor(s):** Custom SQLite 3.something (I forget and this detail is irrelevant)
**GRDB version:** v5.21.0
**Installation method:** manual
**Xcode version:** 13.4
**Swift version:** 5.6.1
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 12.3.1

**Comment by groue** [comment]
Hello @mallman,

`select` sets the current selection (ignoring everything else).

`annotate` extends the current selection.

That's what those methods do.

Maybe reverse the method calls, or put your annotation right into the selection?

**Comment by mallman** [comment]
> .select sets the current selection (ignoring everything else).

Hmmm... I don't see how this contradicts my expectations. In my case, I selected `id` and `position`, and I want it to ignore everything else.

**Comment by mallman** [comment]
I think I found the solution to my problem. The following seems  to do what I'm looking for:

```swift
try Table("version").all()
//      .annotated(with: SQL(sql: "row_number() over (partition by rating order by name) as position"))
      .select(literal: "id, row_number() over (partition by rating order by name) as position")
      .fetchAll(db)
```

In retrospect, this makes sense to me. I was using `.annotated()` in other contexts and assumed that was the way to go. Adding a named expression to my `.select()` is the natural solution. Do you agree?

**Comment by groue** [comment]
> In my case, I selected `id` and `position`, and I want it to ignore everything else.

Yes! And that's why the previous call to `annotated` was just ignored.

`select`, like `order` is _absolute_: it _resets_ the selection.

As for what's best for your app, I don't quite know out of context 😅. As long as the lib does what you are expect, it looks good to me 😉

**Comment by mallman** [comment]
Thank you, @groue. This solves my problem. I am no longer sad or frustrated. 😄
