### ISSUE TITLE
How to get the current DB version

### ISSUE THREAD

**Issue by karthuszY** [groue/GRDB.swift#1224]
### What did you do?

I have migrated the DB to v45 on beta. 
When the user completes tests and wants to install the official version the DB version is v41.
The app will crash because the newly installed app's db version is lower than the current db version.

### What did you expect to happen?

How can I check this and give some tips to users?

### What happened instead?

Because of DB and code has changed to the latest, it will crash or app some feature not working.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @karthuszY, I assume that what you call "DB version" is the [`user_version`](https://www.sqlite.org/pragma.html#pragma_user_version) as defined by SQLite.

If this is correct:

```swift
// Grab the user version
let version = try Int.fetchOne(db, sql: "PRAGMA user_version")!

// Set the user version
try db.execute("PRAGMA user_version=42")
```

You'll wrap those lines in a `read` or `write` database access, depending on what you want to do.
