### ISSUE TITLE
`Date` values loses 1 millisecond after a roundtrip to the DB 

### ISSUE THREAD

**Issue by guillermomuntaner** [groue/GRDB.swift#1227]
### What did you do?

My record contains a `Date`, which is backed by a text column and is persisted directly from a `Date` and fetched into a `Date`.
I then do a roundtrip to the DB. The fetched instance `Date` is off by 1 millisecond. 

### What did you expect to happen?

I expect them to be the same, down to the millisecond precision. I've read the documentation, specially around [Date and DateComponents](https://github.com/groue/GRDB.swift#date-and-datecomponents) and I am aware this is the precision.

### What happened instead?

They are off by a millisecond. More specifically, both the persisted `Date` and the actually stored "YYYY-MM-DD HH:MM:SS.SSS" text representation are correct. However, the fetched instance `Date` is 1 millisecond lower.

This doesn't happen always, but in the sample below I provide a specific timestamp that allows to reproduce this issue. My guess is the serialisation and deserialisation logic is not symmetrical or there is some form of rounding error on the `Date` reconstruction.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24.1
**Installation method:** CocoaPods
**Xcode version:** 13.3
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:**  12.1

### Demo Project

Haven't put a demo project together, but those are the pieces involved & a unit test where I can consistently reproduce the issue:

```
// DB setup
try db.create(table: "table") { t in
  // ...
  t.column("date", .text)
  // ...
}
                
// The record with the fetch/persist logic                
public class Table: Identifiable, Equatable, FetchableRecord, PersistableRecord {
    let date: Date               
    required public convenience init(row: Row) {
        // ...
        let date: Date = row["date"]
        // ...
    }
    public func encode(to container: inout PersistenceContainer) {
        // ...
        container["date"] = date 
        // ...
    }
}

func testMillisecondsPrecissionRoundtrip() throws {

    // Given a date with millisecond resolution
    let precissionTrimmedDate = Date(timeIntervalSince1970: 1653782328.535)
        
    // The databaseValue.description looks good
    XCTAssertEqual(precissionTrimmedDate.databaseValue.description, "\"2022-05-28 23:58:48.535\"")

    let dbQueue = DatabaseQueue()
    _ = try AppDatabase(dbQueue)
    let inserted = Table.testData(withDate: precissionTrimmedDate)

     try dbQueue.write { db in
         try inserted.insert(db)
     }

    // The text value saved in the DB looks good too
    let modificationDate = try dbQueue.read { db in
        try String.fetchOne(db, sql: "SELECT date FROM table WHERE id = \(id)")
    }
    XCTAssertEqual(modificationDate, "2022-05-28 23:58:48.535")

    let fetched: Table? = try dbQueue.read { db in
        return try Table.fetchOne(db, key: inserted.id)
   }

    // However, the fetched Table instance Date gets 1 millisecond lower
    XCTAssertEqual(fetched!.date!.timeIntervalSince1970, 1653782328.535)
    // XCTAssertEqual failed: ("1653782328.534") is not equal to ("1653782328.535")
    XCTAssertEqual(fetched!.date!.databaseValue.description, "\"2022-05-28 23:58:48.535\"")
    // XCTAssertEqual failed: (""2022-05-28 23:58:48.534"") is not equal to (""2022-05-28 23:58:48.535"")
    
    // I haven't tried further roundtrips but I presume that if I save this then the milliseconds will go down to 534 also in the text representation.
}
```

Thanks for your efforts; it is a super solid library thus far, and I am having lot of fun integrating it into our project!

**Comment by guillermomuntaner** [comment]
So it seems the issue was on my side, I added some precision trimming logic that was introducing floating point issues.

**Comment by groue** [comment]
All right, @guillermomuntaner 👍 For whoever wonders about Date roundtrips and reads this issue, make sure you also check #492.
