### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by thwillingham** [groue/GRDB.swift#123]
When compiling an archive of my project with GRDB, I get this error from the GRDB, and am thus not able to compile the archive.  However, I can run it on an ios device locally or via the simulator.

System Information:
-xcode 8
-swift 3
-imported using pods

**Comment by groue** [comment]
Hello @thwillingham.

This bug should be fixed in v0.82.1. Is it the version you are using?

**Comment by thwillingham** [comment]
@groue How do I install v0.82.1?  I don't see that release under releases.

**Comment by groue** [comment]
`pod 'GRDB.swift'` in your Podfile should be enough, and then `pod update`

**Comment by groue** [comment]
...and installation instructions are available in the README: https://github.com/groue/GRDB.swift#installation

**Comment by thwillingham** [comment]
That worked.  Thanks!
