### ISSUE TITLE
This is not a bug, only a question 😅

### ISSUE THREAD

**Issue by ciltocruz** [groue/GRDB.swift#1231]
Sorry for this.

I just wanted to ask a question. I am in love with your changelog. Do you do it manually or automatically with some tool?

Thank you!

**Comment by groue** [comment]
Hello @ciltocruz, thanks for your interest!

I write the changelog with my little hands, in a text editor. That's not so much work, and I never felt the need to automate anything. Besides, I can adapt the wording to the relative importance of each release.

I hope this answers your question!

**Comment by ciltocruz** [comment]
Perfect! Thanks!
