### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by miche-atucha** [groue/GRDB.swift#124]
How to deal with SQLite error 5: Database is locked?

**Comment by urvishagile** [comment]
Same error i was facing.

**Comment by groue** [comment]
Read the GRDB [Concurrency Guide](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency) thoroughly. Understand that you get this error if and only if you don't follow the documented rules. Draw conclusions, and fix your application.

If something is not clear, ask a question, of course.
