### ISSUE TITLE
"Fatal error encountered while reading from module 'GRDB'" when building with SIL performance linker

### ISSUE THREAD

**Issue by myyra** [groue/GRDB.swift#1242]
The Xcode error suggested creating a bug report to Swift directly, but I thought I'd add it also here for visibility.

### What did you do?

Build an app with release configuration, the main thing there being the SIL performance linker.

### What did you expect to happen?

The app compiles successfully.

### What happened instead?

While compiling Swift files, Xcode gives an error: `/project/path/<unknown>:1:1: fatal error encountered while reading from module 'GRDB'`.

The same thing happens with the dynamic version also.

Build setting `OTHER_SWIFT_FLAGS: "-Xllvm -sil-disable-pass=performance-linker"` is needed to make the app compile.

(whole module compilation needs to be disabled as well, as it gets stuck because of the above setting, but it seems otherwise unrelated).

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24.1
**Installation method:** SPM
**Xcode version:**  13.4.1 (13F100)
**Swift version:** 5.6.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.4 (21F79)

### Demo Project

Under the works, because this only happens in our main project and making a minimal reproducable example from that is not trivial.

**Comment by groue** [comment]
Hello @myyra,

Is there something wrong with GRDB that should be changed?

**Comment by myyra** [comment]
I'm okay with closing it until I have a project to reproduce the bug. I added this partly for any ideas you might have, and partly for anyone else experiencing the same issue to find that temporary workaround.

> I mean, do you think you found a problem with GRDB, or with Xcode ;-) ?

One of the most elegant Swift projects ever, wrapping one of the most robust databases available, or an editor known for its inconsistencies in doing anything more than compiling a few sources files? Who knows which one could be at fault.

**Comment by groue** [comment]
You're right, @myyra. Sometimes it is difficult to point exactly at the origin of the problem, and I'm sorry I sounded dismissive.

Please do not hesitate to reopen when you have a reproducing project, even if we all end up staring at it without really understanding what's wrong.
