### ISSUE TITLE
swift.  怎么使用模糊查询啦

### ISSUE THREAD

**Issue by Joejin-0222** [groue/GRDB.swift#1243]
### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
> How to use fuzzy query?

Hello @Joejin-0222. What do you mean?
