### ISSUE TITLE
More control over sorting order in Associations

### ISSUE THREAD

**Issue by sameer4** [groue/GRDB.swift#1247]
### What did you do?

i'm need to sort data of table **ProductUse**. here's code
```
try ProductUse
.including(optional: ProductUse.product.order(Products.CodingKeys.group.asc))
.filter(ProductUse.CodingKeys.todoid == 20 && !ProductUse.CodingKeys.isdeleted)
.limit(30, offset: 0)
.order(ProductUse.CodingKeys.linetext)
.fetchAll(db)
```

### What did you expect to happen?

Apply **group** sorting from **Products**(associated record) first and then **linetext**  from **ProductUse**(base record). It should be like

```
SELECT "ProductUse".*, "Products".* FROM "ProductUse" LEFT JOIN "Products" ON ("Products"."productnumber" = "ProductUse"."productnumber") AND ("Products"."isdeleted" = 0) WHERE ("ProductUse"."todoid" = 20) ORDER BY "Products"."group" ASC, "ProductUse"."linetext" LIMIT 30 OFFSET 0
```
### What happened instead?

**linetext**  from **ProductUse**(base record) was applied first and then **group** sorting from **Products**(associated record). 
here's query

```
SELECT "ProductUse".*, "Products".* FROM "ProductUse" LEFT JOIN "Products" ON ("Products"."productnumber" = "ProductUse"."productnumber") AND ("Products"."isdeleted" = 0) WHERE ("ProductUse"."todoid" = 20) ORDER BY "ProductUse"."linetext", "Products"."group" ASC LIMIT 30 OFFSET 0
```
i see from documentation 

[When you sort both the base record on the associated record, the request is sorted on the base record first, and on the associated record next:](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#sorting-associations)

is there some way to have this in reverse or more control on which one should be done first?

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.3.0
**Installation method:** CocoaPods
**Xcode version:** 13.4.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.4

**Comment by groue** [comment]
Hello @sameer4,

You are very close. Just a few lines below the line you linked to, you will read:

> There are more sorting options:
>
> - Sorting on expressions that involve several tables.
> - Changing the order of the sorting terms (such as sorting on author name first, and then publish date).
>
> Those extra sorting options require [Table Aliases](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#table-aliases), introduced below.

**Comment by groue** [comment]
Happy GRDB!

**Comment by sameer4** [comment]
Thank you for the GRDB and your time. :-)
