### ISSUE TITLE
SQLite error 26: file is not a database, while trying to enable encryption

### ISSUE THREAD

**Issue by pwittchen** [groue/GRDB.swift#1249]
### What did you do?

I used GRDB in my project and tried to enable encryption. Project works fine without encryption

### What did you expect to happen?

I expected project to behave in the same way as before, but with encrypted database

### What happened instead?

I got an error `SQLite error 26: file is not a database` when I try to execute database operations

### Environment

**GRDB flavor(s):** GRDB, SQLCipher
**GRDB version:** 5.25.0
**Installation method:** CocoaPods
**Xcode version:** Version 13.3.1 (13E500a)
**Swift version:** 5.6
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.3.1

### Demo Project

I cannot link it here.

My db initialization looks as follows:

```swift
class db {

    ...

    public init(logger: LoggerFacade, sqlEncryptionPassphrase: String) {
        self.logger = logger
        do {
            let databaseUrl: URL = try createDatabaseUrl()
            let databaseConfiguration: Configuration = try createConfiguration(withPassphrase: sqlEncryptionPassphrase)
            self.dbQueue = try DatabaseQueue(path: databaseUrl.path, configuration: databaseConfiguration)
            try createSchema()
        } catch let error {
            self.dbQueue = nil
            logger.error(error.localizedDescription)
        }
    }
    
    fileprivate func createDatabaseUrl() throws -> URL {
        return try FileManager
            .default
            .url(
                for: .applicationSupportDirectory,
                in: .userDomainMask,
                appropriateFor: nil, create: true
            )
            .appendingPathComponent(sqlDbFileName)
    }
    
    fileprivate func createConfiguration(withPassphrase passphrase: String) throws -> Configuration {
        var configuration: Configuration = Configuration()
        configuration.prepareDatabase { db in
            try db.usePassphrase(passphrase)
        }
        return configuration
    }
}
```

Podfile:

```
platform :ios, '11.4'

use_frameworks!

target 'iOS-SDK' do
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'SWCompression', '~> 4.7'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SQLCipher', '~> 4.0'
  pod 'GRDB.swift/SQLCipher'
end

target 'iOS-SDKTests' do
  pod 'Nimble'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end

```

I tried to use SQLCipher 3.4 too with the same result.

I added `-framework SQLCipher` to "Other Linker Flags" in project configuration.
I cleaned the project, removed Derived data, rebuild project, rebuild and re-run tests.
In my project I also changed DB Pool to DB Queue because I thought it was an issue, but nothing changed.
I'm testing it via using tests on iPhone 11 simulator.
I don't know what am I doing wrong.

**It works fine when I'm not encrypting it**. 
I'm getting this error **only when I try to use encrypted database**.

I will appreciate any help.

Regards,
Piotr

**Comment by pwittchen** [comment]
Thanks for the quick response @groue. I updated my code according to your suggestion, but I'm still getting the same error. Here's how I updated it.

```swift

class GrdbFacade {
    private let sqlDbFileName: String = "dfpdb.sqlite"
    private let sqlDbFileNameSecured: String = "dfpdb_secured.sqlite"
    private let sqlTableNameTouch: String = "TouchGrdbEntity"
    private let sqlTableNameSensor: String = "SensorGrdbEntity"
    
    private let logger: LoggerFacade
    private var dbQueue: DatabaseQueue?
    private var dbQueueSecured: DatabaseQueue?
    
    public init(logger: LoggerFacade, sqlEncryptionPassphrase: String) {
        self.logger = logger
        do {
            let databaseUrl: URL = try createDatabaseUrl()
            self.dbQueue = try DatabaseQueue(path: databaseUrl.path)
            try createSchema()
            try secureDatabase(sqlEncryptionPassphrase: sqlEncryptionPassphrase)
        } catch let error {
            self.dbQueue = nil
            logger.error(error.localizedDescription)
        }
    }
    
    fileprivate func secureDatabase(sqlEncryptionPassphrase: String) throws {
        do {
            let databaseUrl: URL = try createDatabaseUrl()
            let databaseConfiguration: Configuration = try createConfiguration(withPassphrase: sqlEncryptionPassphrase)
            self.dbQueueSecured = try DatabaseQueue(path: databaseUrl.path, configuration: databaseConfiguration)
        } catch let error {
            self.dbQueueSecured = nil
            logger.error(error.localizedDescription)
        }

        try dbQueue?.inDatabase { db in
            try db.execute(
                sql: """
                    ATTACH DATABASE ? AS encrypted KEY ?;
                    SELECT sqlcipher_export('encrypted');
                    DETACH DATABASE encrypted;
                    """,
                arguments: [dbQueueSecured?.path, sqlEncryptionPassphrase])
        }
    }
    
    fileprivate func createDatabaseUrl() throws -> URL {
        return try FileManager
            .default
            .url(
                for: .applicationSupportDirectory,
                in: .userDomainMask,
                appropriateFor: nil, create: true
            )
            .appendingPathComponent(sqlDbFileName)
    }
    
    fileprivate func createConfiguration(withPassphrase passphrase: String) throws -> Configuration {
        var configuration: Configuration = Configuration()
        configuration.prepareDatabase { db in
            try db.usePassphrase(passphrase)
        }
        return configuration
    }
    
    public func createSchema() throws {
        try dbQueue?.write { db in
            // my schema goes here...
        }
    }
    
    deinit {
        do {
            try dbQueue?.close()
            try dbQueueSecured?.close()
        } catch let error {
            logger.error(error.localizedDescription)
        }
    }
```

Can you provide an example, how this encryption should be done correctly? 
I implemented everything according to the documentation and it does not work :-(.

**Comment by groue** [comment]
@pwittchen Your sample code can't be correct: you need _two_ distinct databases at two distinct locations, and I do not see that. And you need to perform the export _only once, or you'll always over-write your encrypted database. And you did not tell if your app is indeed trying to open a clear-text database, in order to validate that this is actually your problem.

I suggest you read the doc again, make sure you understand what it says, and make sure you understand what you are doing. If you have questions, make them as specific as possible, with the goal of _understanding what your app is doing_.

**Comment by pwittchen** [comment]
Thanks for the reply.

In my test I tried to replace all `dbQueueSecured` calls with `dbQueue` just to test if I can access clear-text database and now I got error like this:

```
SQLite error 1: table "MyTable" already exists - while executing `SELECT sqlcipher_export('encrypted')`
```

I tried to drop all my tabled both on `dbQueue` and `dbQueueSecured` objects before executing any operations, so I don't know why I'm receiving this error. It didn't happen before applying encryption-related code. When I remove code responsible for migration I get:

```
Swift/ContiguousArrayBuffer.swift:575: Fatal error: Index out of range
```

I don't know how to solve this correctly and I would appreciate a complete working example or code snippet of the project with the simple encrypted database. It's confusing for me and I could not find any example of how to do it correctly from the beginning to the end with your library or any other solution on iOS with Swift. It works fine without encryption, but I could not make it work with the encryption.

**Comment by groue** [comment]
Oh, so you're stuck. Be patient: this is the weekend now :)

**Comment by pwittchen** [comment]
Ok, thanks. I will try to be patient :). It's just bothers me that I can't solve it, but it seems to be simple :D.

I debugged it and I have conclusions:
- Clear-text database is created successfully
- Encrypted database is not being created that's why migration cannot be performed

Here's the code snippet:

```swift
        do {
            let secureDatabaseUrl: URL = try createDatabaseUrl(sqlDbFileNameSecured)
            var secureDatabaseConfiguration: Configuration = Configuration()
            secureDatabaseConfiguration.prepareDatabase { db in
                try db.usePassphrase(sqlEncryptionPassphrase)
            }
            self.dbQueueSecured = try DatabaseQueue(path: secureDatabaseUrl.path, configuration: secureDatabaseConfiguration)
            logger.debug("Encrypted SQLite database is located in: \(secureDatabaseUrl.path)")
        } catch let error {
            self.dbQueueSecured = nil
            logger.error(error.localizedDescription)
        }
```

It fails on the line: 

```swift
self.dbQueueSecured = try DatabaseQueue(path: secureDatabaseUrl.path, configuration: secureDatabaseConfiguration)
```

with an error: 

```
SQLite error 26: file is not a database - while executing `SELECT * FROM sqlite_master LIMIT 1
```

In my test `databaseUrl` looks like this:

```
"file:///Users/pw/Library/Developer/CoreSimulator/Devices/4BAF08A0-FC77-4D05-96A5-E83D8F3F0D1E/data/Library/Application%20Support/dfpdb.sqlite"
```

and `secureDatabaseUrl` looks like this:

```
"file:///Users/pw/Library/Developer/CoreSimulator/Devices/4BAF08A0-FC77-4D05-96A5-E83D8F3F0D1E/data/Library/Application%20Support/dfpdb_secured.sqlite"
```

Files are in the same directory, but they have different names, which looks correct.

First `DatabaseQueue` (clear-text database) is created.
Second `DatabaseQueue` (encrypted) is not created and I don't know why.
When I remove `Configuration` from the second `DatabaseQueue`, it fails anyway.

**It's exactly the same code, but used with another variable and with different url**.
First Queue creation does not fail, but second one fails.
I don't understand why it fails :(.

Maybe I cannot have two Database Queues active at the same time?

**Comment by pwittchen** [comment]
When I changed database file name from `dfpdb_secured.sqlite` to `dfpdbsecured.sqlite` it started to create new Queue object, so the underscore `_` in the file name was the problem for some reason. Now I have another problems with this, but I will have to analyze them. I will come back with questions or solutions later. :-)

**Comment by pwittchen** [comment]
I probably figured this out. Issue was not with the file name, but with the file itself. When I removed database files manually, my unit tests started passing. In my tests I had an instance of my custom class `GrdbFacade` and new instance of this class with new queues was created every time in each unit test, what caused errors. Once I created a single instance of this class for whole test case class, tests started passing. Unfortunately, Once database is created in one test case class, I cannot access it correctly in another test case class. First test case with database is executed correctly and next test cases fails. I think, in unit tests I just need to remove and re-create database files every time and it will work. In the real application, I will have just a single instance of the `GrdbFacade` class, so it should work correctly.

**Comment by groue** [comment]
Well done, @pwittchen, it looks like you found your solution 👍 

Indeed files that remain from previous test sessions can break your tests, especially if previous test sessions were not cleaned up properly, or did something that your tests do not expect (such as finding a clear-text database at the location of a supposedly-encrypted database).

Of course, this setup is very particular for your app: there were absolutely no chance that the GRDB documentation would describe what your tests must do. Only your understanding of what you are doing, informed with the library documentation, can help you fix this kind of issue.

It looks like the issue can be closed 🙂

**Comment by pwittchen** [comment]
Thanks for the support. My project is not fully working with encrypted database yet, but now I now what I need to do and should be able to proceed with that. :)

**Comment by groue** [comment]
All right. Don't hesitate asking a new question if needed :-)

**Comment by adam-alex-albert** [comment]
Currently, the App uses an encrypted database, but this error (SQLite error 26: file is not a database - while executing `SELECT * FROM sqlite_master LIMIT 1`) occurs on some devices, causing the database to fail to open. Recently, this error has affected more and more devices. Can you help analyze the reason?

**Comment by adam-alex-albert** [comment]
<img width="904" alt="Image" src="https://github.com/user-attachments/assets/0369c34a-c460-4e0e-b8f9-c1955903ad4f" />

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/72768323-27b9-4533-b228-8b518984315b" />

**Comment by adam-alex-albert** [comment]
@groue  Can you help analyze it? Many users' database initialization is not successful now, and the app cannot be used, which can also lead to data loss. Thank you very much

**Comment by groue** [comment]
@adam-alex-albert You are conflating free support and free work.
