### ISSUE TITLE
ValueObservation listen for nested values

### ISSUE THREAD

**Issue by fbertuzzi** [groue/GRDB.swift#1250]
Hey,

I'm having difficulties with ValueObservation.

I'm building a messaging app where I have a table for chat containers and one for messages. I'm using value observation to fetch all chat containers including the last message using CTEs. That works perfectly. However when the message is updated (the status of the message which is just a Integer to show if it's delivered, read and so on) the observation is not triggered. When the message changes completely (new message is latest message) it updates. Is that something the value observation isn't meant for? Observing values in objects? Should I use a value observation for all chat containers to update the status?

This is my code for the publisher:

```swift
public func publisher(in appDatabase: AppDatabase) -> AnyPublisher<[ChatContainerJoined], Error> {
        
        
        let lastMessageRequest = Message
            .annotated(with: max(Message.Columns.timestamp))
            .group(Message.Columns.chatContainerId)
        
        let lastMessageCTE = CommonTableExpression<Message>(named: "lastMessage", request: lastMessageRequest)
        
        let lastMessage = ChatContainer.association(
            to: lastMessageCTE,
            on: { chatContainer, lastMessage in
                chatContainer[ChatContainer.Columns.id] == lastMessage[Message.Columns.chatContainerId]
            })
            .order(Message.Columns.timestamp.desc)
        
        return DarwinNotificationCenter.shared.publisher(for: .extensionsDidSave)
            .map { _ in
                return ValueObservation
                    .tracking(ChatContainer
                        .with(lastMessageCTE)
                        .including(optional: ChatContainer.profile)
                        .including(optional: ChatContainer.chatGroup)
                        .including(optional: lastMessage)
                        .order(ChatContainer.Columns.pinnedTimestamp.desc)
                        .asRequest(of: ChatContainerJoined.self)
                        .fetchAll(_:))
                    .publisher(in: appDatabase.databaseReader, scheduling: .immediate)
                    .print()
            }
            .receive(on: RunLoop.main)
            .switchToLatest()
            .compactMap {
                return $0.filter({$0.lastMessage != nil || $0.chatGroup != nil})
            }
            .eraseToAnyPublisher()
    }
```

```swift
public struct ChatContainerJoined: Decodable, FetchableRecord, Equatable, Encodable {
    public var container: ChatContainer
    public var profile: Profile?
    public var chatGroup: ChatGroup?
    public var lastMessage: Message?
}
```

**Comment by groue** [comment]
Hello @fbertuzzi,

There is a FAQ about this: [Why is ValueObservation not publishing value changes?](https://github.com/groue/GRDB.swift#why-is-valueobservation-not-publishing-value-changes).

In your case, I'd directly use `print()`, between `.tracking` and `.publisher`. Would you please report what is the tracked region?

**Comment by fbertuzzi** [comment]
Hey @groue,

`tracked region:   chatContainer(groupId,id,mutedUntil,notificationTimestamp,pinnedTimestamp,profileId),chatGroup(createdTimestamp,description,groupId,groupPictureLink,name,owner),message(chatContainerId,expirationTimestamp,link,messageId,messageType,ownerId,parentMessage,receiverId,statusCode,text,timestamp),profile(biography,birthdate,firstname,isVerified,lastFetched,lastname,middlename,profileId,profilePictureLink,username,website)`

this is what I get back using the `print()` function. For me it looks like the region is correct it shows my statusCode which I want to listen for.

I also See that there is an update made. However I can't see if the statusCode did change as I only see the following for the lastMessage: `lastMessage: Optional(Cobra.Message)` Is there a way to unwrap that and see what values are inside of the class? Other than the statusCode is not updated in this case so it must have been triggered by that.

**Comment by groue** [comment]
> this is what I get back using the print() function. For me it looks like the region is correct it shows my statusCode which I want to listen for.

Yes. This is good. Whatever issue your app is facing, it does not lie there.

> I also See that there is an update made.

I interpret that you can see that a status change triggers the observation ("database did change", "fetch" and "value" events). This is good as well 👍 

> However I can't see if the statusCode did change as I only see the following for the lastMessage: `lastMessage: Optional(Cobra.Message)`

Do you mean that the logged events don't display precise enough information? You can improve the logging.

For example, provide a `CustomStringConvertible` conformance for the logged types. You'll be able to remove this temporary conformance after the debugging session.

You can alternatively replace `print` with [`handleEvents`](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservationhandleevents), with custom logging in the `didReceiveValue` callback.

**Comment by fbertuzzi** [comment]
I tried extending my class and I see that the statusCode is indeed updated as it should. Now I have to figure out why the UI isn't reflecting that change. It does show when the last message change completely from the previous but not when just the statusCode changes.

**Comment by fbertuzzi** [comment]
I found something weird:

If I use this for listening to check the change of the value I get the correct result.

```swift
.onChange(of: chatContainer.lastMessage?.statusCode, perform: {change in
                            print("New statusCode: \(change)")
                        })
```
                       

When I use this:

```swift
.onChange(of: chatContainer.lastMessage, perform: {change in
                            print(change?.description ?? "No last message")
                        })
```

I get the old statusCode displayed

**Comment by fbertuzzi** [comment]
Yes it does! I thought it was that my value observation didn't listen for the values in it sub objects but it seems like it does, otherwise I shouldn't get the value in the logging console.

**Comment by fbertuzzi** [comment]
I actually managed to solve this by using `.queryObservation(.onRender)`.
Before I was using the default value.

**Comment by fbertuzzi** [comment]
However this leads to my subview (NavigationLink) using another `@Query` flickering. Maybe you have some suggestion @groue? I guess that is because the parent view of the NavigationLink updates causing to update the subview as well?

**Comment by groue** [comment]
I suggest watching https://developer.apple.com/videos/play/wwdc2021/10022/ with great care, as well as fiddling with small SwiftUI apps on the side in order to check your understanding. During your explorations, consider that:

- If you can, avoid toying with `.queryObservation` unless you know exactly what you are doing. It is an optimization tool, not a building block.
- `@Query` behaves exactly like `@StateObject` (in the context of lifetimes).
- To simplify your explorations, consider that you can use `@Query` without a database. You can return any publisher from the `publisher(in:)` method of Queryable types. Any type can be used as a "database", as in the sample code below.

    ```swift
    import Combine
    import Foundation
    import GRDBQuery
    import SwiftUI

    // A dummy database
    struct DummyDatabase { }
    private struct DummyDatabaseKey: EnvironmentKey {
        static var defaultValue = DummyDatabase()
    }
    extension EnvironmentValues {
        var dummyDatabase: DummyDatabase {
            get { self[DummyDatabaseKey.self] }
            set { self[DummyDatabaseKey.self] = newValue }
        }
    }

    // A queryable request
    struct TimerRequest: Queryable {
        static var defaultValue = Date()
        
        func publisher(in _: DummyDatabase) -> AnyPublisher<Date, Never> {
            // Return any publisher you want here
            Timer.publish(every: 1, on: .main, in: .common)
                .autoconnect()
                .eraseToAnyPublisher()
        }
    }

    // A view that uses the TimerRequest
    struct TimerView: View {
        @Query(TimerRequest(), in: \.dummyDatabase) var currentDate: Date
        
        var body: some View {
            Text(currentDate.formatted(date: .long, time: .complete))
        }
    }

    struct TimerView_Previews: PreviewProvider {
        static var previews: some View {
            TimerView()
        }
    }
    ```
