### ISSUE TITLE
API to disconnect current db connection.

### ISSUE THREAD

**Issue by xhan** [groue/GRDB.swift#1252]
### What did you do?

I have a database shared by two apps. the other app can't access the db since GRDB connection is alive.
Is there an api to disconnect the current connection?

### What did you expect to happen?

disconnect the current connection on the fly.

**Comment by groue** [comment]
Hello @xhan 

> I have a database shared by two apps. the other app can't access the db since GRDB connection is alive.

What do you mean by this? Please aim at maximum clarity.

**Comment by groue** [comment]
Please excuse my initial answer: it contains a purposeless question. 

Since you share an database between several processes, please check the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide.

**Comment by groue** [comment]
I'm closing the issue. If you have other questions after reading the sharing guide, please open a new issue.
