### ISSUE TITLE
As long as read-only mode is turned on, an error will appear.

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1258]
My macOS app is written under the macOS system. I have a requirement that only the database needs to be opened, and the modification of this database is prohibited.

But I got an error after I implemented it through configuration. I found that it will not report an error when readonly is false.

```
        do {
            var configuration: Configuration = Configuration()
            configuration.label = UUID // uuid
            configuration.readonly = false // here

            let dbWriter = try DatabasePool(path: path, configuration: configuration)
            ...
        } catch let error {
            print(error.localizedDescription) // catch error
        }
```

2022-08-07 01:45:50.074166+0800 xxx[82260:1312218] [logging-persist] os_unix.c:45530: (0) open(/var/.../90CD57BE-4391-4B49-8F49-C9D13D8BDFB7-wal) - Undefined error: 0
2022-08-07 01:45:50.074182+0800 xxx[82260:1312218] [logging-persist] unable to open database file in "SELECT * FROM sqlite_master LIMIT 1"

I open two databases at the same time, but they are not the same file or path.

macOS: 12.5 (21G72)
GRDB.Swift: 5.26.0

**Comment by groue** [comment]
Hello @SF-Simon,

It looks like the file at the given path is not a database. Maybe open it with the `sqlite3` tool in the terminal:

```
% sqlite3 /path/to/database
```

**Comment by SF-Simon** [comment]
But, I can confirm that it's a database file, it's just that its filename
doesn't have a suffix.

Gwendal Roué ***@***.***>于2022年8月7日 周日02:09写道：

**Comment by groue** [comment]
I'm quite not sure. Please run the `sqlite3` command line in the terminal, run a SQL query in the SQLite prompt, as requested above, and paste here the result here, will you?

**Comment by groue** [comment]
Of course, make **sure** you use the same database path in your app, and in the `sqlite3` tool ;)

**Comment by SF-Simon** [comment]
> Make **sure** you use the same database path in your app, and in the `sqlite3` tool, or the experiment will fail. Thanks.

thank you for your help, @groue 

This is what I get when I run it under terminal, please help me identify the problem, thanks.

```
$ sqlite3 path...
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> SELECT * FROM sqlite_master LIMIT 1;
table|grdb_migrations|grdb_migrations|2|CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)
sqlite>
```

**Comment by groue** [comment]
So you want to open a WAL database in read-only mode (`configuration.readonly = true`), is that correct (wal mode enabled for sure + read-only)? Can you please tell if there are files, in the directory that contains the database, with names that end with `-wal` and `-shm`?

**Comment by groue** [comment]
Also please read https://www.sqlite.org/wal.html#read_only_databases

**Comment by SF-Simon** [comment]
No, what we want most is to be in read-only mode without generating other
files, including -wal and -shm.

These two files, or other files, do not exist in the directory, there is
only one database file.

Our expectation is to read only this database, not to write and generate
other files (as described in the GRDB’s documents).  But it fails and we
can't open and use it properly.

**Comment by groue** [comment]
What you want is not allowed by SQLite. Please do click the above link and read.

**Comment by SF-Simon** [comment]
Sorry, I don't know much about this part, so there may be some common sense questions.

I read the link above and I noticed that SQLite3 after version 3.22.0 can open the database as read-only, but with some additional conditions.

> Older versions of SQLite could not read a WAL-mode database that was read-only. In other words, write access was required in order to read a WAL-mode database. This constraint was relaxed beginning with SQLite [version 3.22.0](https://www.sqlite.org/releaselog/3_22_0.html) (2018-01-22).
> 
> On newer versions of SQLite, a WAL-mode database on read-only media, or a WAL-mode database that lacks write permission, can still be read as long as one or more of the following conditions are met:
> 
> The -shm and -wal files already exists and are readable
> There is write permission on the directory containing the database so that the -shm and -wal files can be created.
> The database connection is opened using the [immutable query parameter](https://www.sqlite.org/uri.html#uriimmutable).
> 
> Even though it is possible to open a read-only WAL-mode database, it is good practice to converted to [PRAGMA journal_mode=DELETE](https://www.sqlite.org/pragma.html#pragma_journal_mode) prior to burning an SQLite database image onto read-only media.

Can I use the third way to implement my idea through the configuration of GRDB.swift?
Because we don't want to generate any new files, and we can't ensure other permissions on the user directory.(In the case of only one SQLite3 database file)

**Comment by groue** [comment]
Yes. What about you change the journal mode of your database, so that it is no longer in the WAL mode? The SQLite documentation tells you how to do that, and GRDB can execute any SQL statement:

```swift
let dbQueue = try DatabaseQueue(path: ...)
try dbQueue.inDatabase { db in
    try db.execute(sql: "PRAGMA ...")
}
```

> Sorry, I don't know much about this part

Your need is not quite common, so now is the time to know more, learn about SQLite, and read the related documentation 🙂

**Comment by SF-Simon** [comment]
> Yes. What about you change the journal mode of your database, so that it is no longer in the WAL mode? The SQLite documentation tells you how to do that, and GRDB can execute any SQL statement:
> 
> ```swift
> let dbQueue = try DatabaseQueue(path: ...)
> try dbQueue.inDatabase { db in
>     try db.execute(sql: "PRAGMA ...")
> }
> ```
> 
> > Sorry, I don't know much about this part
> 
> Your need is not quite common, so now is the time to know more, learn about SQLite journaling modes, and read the related documentation (I can't repeat it here) 🙂

Thank you, you have helped me so much, and very quickly, I am very grateful.

I am looking for some solutions to see how to solve this kind of problem.

In addition there is a problem, I found that even if I put the database file in a directory with read and write permissions, as long as I set configuration.readonly=true, it will not generate the -wal and -shm files, and then it will fail.
This is inconsistent with what SQLite3 says, and I don't know if it is expected. Because in theory it should produce new -wal and -shm files, not nothing.

**Comment by SF-Simon** [comment]
My problem is temporarily solved.

I don't know if other people have the same needs and problems, but I hope everyone can have a suitable idea, so I write my solution. (Thanks Groue for your help.)

If you are worried about generating -wal and -shm, you can check these URLs.
links:
https://github.com/groue/GRDB.swift/issues/1197
https://github.com/groue/GRDB.swift/blob/8658b7bc1009237457324fc050cd06e0d961b72a/Documentation/SharingADatabase.md
https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal

My last resort was to change this file to default instead of WAL mode.
`PRAGMA journal_mode=DELETE;`

links:
https://www.sqlite.org/wal.html

The way of using inDatabase may not work, because it is an error during initialization, so I manually use the SQLite3 tool to execute it. Of course, if you execute it when exporting, it is also possible to make it normal mode.

tx.
