### ISSUE TITLE
Swift 3 compilation error

### ISSUE THREAD

**Issue by gabber3000** [groue/GRDB.swift#126]
Hello,
I have tried to create a new project in xcode last ios10 version siwtft 3.
I followed the guidelines for installing writing in my files pod
when I try to fill in with xcode I receive many compilation errors.
Where am I doing wrong?

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'GRDB.swift'
```

![schermata 2016-09-23 alle 18 00 24](https://cloud.githubusercontent.com/assets/5178424/18792670/b2591298-81b7-11e6-87fc-8f1cf0f22cf2.png)

**Comment by groue** [comment]
Hello,

You have a version mismatch. What versions of Xcode, Swift, and GRDB are you using?

**Comment by gabber3000** [comment]
1. My version of xcode and: Version 8.0 (8A218a)
2. swift version: Swift Apple version 3.0 (swiftlang 800.0.46.2-clang-800.0.38)
3. For the GRDB version I simply logged into my PodFile (cocoapod) the following statement
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'GRDB.swift'
```
Where am I doing wrong?

**Comment by groue** [comment]
> Where am I doing wrong?

Nothing. I think you have an outdated version of GRDB. Update it with `pod update GRDB.swift`. After that, check in the Podfile.lock that GRDB is at version 0.84.0. And everything should be fine then.

**Comment by gabber3000** [comment]
Following your advice I have succeeded.
Thank you

**Comment by groue** [comment]
Great! Happy GRDB!
