### ISSUE TITLE
Application crashing while run with Release mode in Scheme

### ISSUE THREAD

**Issue by Sella-invedus** [groue/GRDB.swift#1262]
Application getting crashed while running with release mode. I have attached screen shots for reference. Please help me to resolve this issue as soon as possible

running smoothly

geting crashed

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

![Screenshot 2022-08-10 at 9 06 38 PM](https://user-images.githubusercontent.com/96127361/183995713-17dd5bca-9506-4a9e-b150-4272e1e3c961.png)
![Screenshot 2022-08-10 at 9 07 06 PM](https://user-images.githubusercontent.com/96127361/183995726-94adeef0-c497-4ea3-ac36-b482b06009ec.png)
![Screenshot 2022-08-10 at 9 33 26 PM](https://user-images.githubusercontent.com/96127361/183995730-46cd80ad-2b6b-46e9-a9e7-06f31e08bbd0.png)
![Screenshot 2022-08-10 at 9 33 57 PM](https://user-images.githubusercontent.com/96127361/183995735-092bf4e4-a1c3-4dde-9539-497a70fc7f65.png)
?)

**Comment by groue** [comment]
Hello @Sella-invedus 

Without any information about how you're getting this crash, it is difficult to answer.

**Comment by groue** [comment]
Closing due to lack of usable input. @Sella-invedus, please provide a complete crash report when you have time.
