### ISSUE TITLE
How to modify primary key with migrator? 

### ISSUE THREAD

**Issue by lgj1993** [groue/GRDB.swift#1265]
Hello, how can I add a primary key in the created table, such as table a field

ID, userid, name my current primary key is [ID] how can I use Migrator to modify the primary key to [ID, userid]

**Comment by groue** [comment]
Hello @lgj1993,

SQLite does not support such schema modification out of the box, so you'll have to do it manually. You'll write a migration that creates a new table with the correct schema, dumps the content of the old table in the new table, and replace the old table with the new table.

Check the [Advanced Database Schema Changes](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#advanced-database-schema-changes) chapter of the Migrations guide for more information.
