### ISSUE TITLE
Set the converter for the specified column

### ISSUE THREAD

**Issue by kylechandev** [groue/GRDB.swift#1266]
Hello @groue , 

First, Thank you for creating this amazing library!!! It is the best SQLite library for Swift that I have tried a lot!

Now I have a question and may need your help...

Right now, I'm running into a problem regarding full custom column value conversion. I realize that the current solution is to uniformly convert to JSON to store in the database, but I want to convert an Array into a specific String to store, like [1,2,3] via split(by ",") Convert it to "1,2,3" for storage because my previous Android program did this, so if I want data that is compatible with the Android version, I must convert it to such a string...

I'm stuck now, what should I do...😖

(The GRDB.swift version I am using is v5.26.0)

**Comment by groue** [comment]
Hello @kylechandev,

Custom encoding and decoding of database values is done with the [DatabaseValueConvertible](https://github.com/groue/GRDB.swift/blob/master/README.md#custom-value-types) protocol.

You can define a custom DatabaseValueConvertible type that encodes and decodes comma-separated lists of ints, and make it a property wrapper for extra convenience. For example:

```swift
@propertyWrapper
struct CommaSeparated {
    var wrappedValue: [Int]
}

// Support for Codable
extension CommaSeparated: Codable {
    // You may have to provide a custom Codable conformance, if you use
    // CommaSeparated in types that are encoded or decoded from JSON. For this
    // sample code, the default implementation is enough.
}

// Specific database encoding and decoding
extension CommaSeparated: DatabaseValueConvertible {
    /// Returns a value that can be stored in the database.
    var databaseValue: DatabaseValue {
        // [1, 2, 3] -> "1,2,3"
        let string = wrappedValue.map { "\($0)" }.joined(separator: ",")
        return string.databaseValue
    }
    
    /// Returns a value initialized from dbValue, if possible.
    static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
        guard let string = String.fromDatabaseValue(dbValue) else {
            // Not a string
            return nil
        }
        
        // Parse and convert to ints. In your implementation, make sure your
        // return nil if parsing fails, so that GRDB can throw a decoding error
        // (for example, we can't decode an array of ints from "one,two,three").
        let wrappedValue: [Int] = ...
        return CommaSeparated(wrappedValue: wrappedValue)
    }
}
```

You can now use `CommaSeparated` just like other [values](https://github.com/groue/GRDB.swift/blob/master/README.md#values).

You can also define `@CommaSeparated` properties in records:

```swift
// Define a record type
struct MyRecord: Codable, FetchableRecord, PersistableRecord {
    var id: String
    @CommaSeparated var ints: [Int]
}

// Insert a record
try MyRecord(id: "foo", ints: [1, 2, 3])

// Fetch records
for record in try MyRecord.fetchAll(db) {
    for int in record.ints { ... }
}
```

Completing the `Codable` implementation (if needed), performing actual parsing, and extending this sample code for other types than `Int` is left as an exercise for the reader (those topics are no longer about GRDB).

**Comment by kylechandev** [comment]
> Hello @kylechandev,
> 
> Custom encoding and decoding of database values is done with the [DatabaseValueConvertible](https://github.com/groue/GRDB.swift/blob/master/README.md?rgh-link-date=2022-08-23T15%3A26%3A09Z#custom-value-types) protocol.
> 
> You can define a custom DatabaseValueConvertible type that encodes and decodes comma-separated lists of ints, and make it a property wrapper for extra convenience. For example:
> 
> ```swift
> @propertyWrapper
> struct CommaSeparated {
>     var wrappedValue: [Int]
> }
> 
> // Support for Codable
> extension CommaSeparated: Codable {
>     // You may have to provide a custom Codable conformance, if you use
>     // CommaSeparated in types that are encoded or decoded from JSON. For this
>     // sample code, the default implementation is enough.
> }
> 
> // Specific database encoding and decoding
> extension CommaSeparated: DatabaseValueConvertible {
>     /// Returns a value that can be stored in the database.
>     var databaseValue: DatabaseValue {
>         // [1, 2, 3] -> "1,2,3"
>         let string = wrappedValue.map { "\($0)" }.joined(separator: ",")
>         return string.databaseValue
>     }
>     
>     /// Returns a value initialized from dbValue, if possible.
>     static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
>         guard let string = String.fromDatabaseValue(dbValue) else {
>             // Not a string
>             return nil
>         }
>         
>         // Parse and convert to ints. In your implementation, make sure your
>         // return nil if parsing fails, so that GRDB can throw a decoding error
>         // (for example, we can't decode an array of ints from "one,two,three").
>         let wrappedValue: [Int] = ...
>         return CommaSeparated(wrappedValue: wrappedValue)
>     }
> }
> ```
> 
> You can now use `CommaSeparated` just like other [values](https://github.com/groue/GRDB.swift/blob/master/README.md?rgh-link-date=2022-08-23T15%3A26%3A09Z#values).
> 
> You can also define `@CommaSeparated` properties in records:
> 
> ```swift
> // Define a record type
> struct MyRecord: Codable, FetchableRecord, PersistableRecord {
>     var id: String
>     @CommaSeparated var ints: [Int]
> }
> 
> try dbQueue.write { db in
>     // Insert a record
>     try MyRecord(id: "foo", ints: [1, 2, 3]).insert(db)
> 
>     // Fetch records
>     for record in try MyRecord.fetchAll(db) {
>         for int in record.ints { ... }
>     }
> }
> ```
> 
> Completing the `Codable` implementation (if needed), performing actual parsing, and extending this sample code for other types than `Int` is left as an exercise for the reader (those topics are no longer about GRDB).

**Thanks for this idea, it's very helpful!! You saved me!! 🤗**
