### ISSUE TITLE
Failing `CHECK` constraint doesn't throw an error in v6.0.0-beta.2

### ISSUE THREAD

**Issue by myyra** [groue/GRDB.swift#1267]
### What did you do?

Insert a row into a table with a `CHECK` constraint that should fail with the given row.

### What did you expect to happen?

`.insert` throws an error about a failed `CHECK`, as it has in GRDB v5.x.x.

### What happened instead?

Insert succeeds without errors.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v6.0.0-beta.2
**Installation method:** SPM
**Xcode version:** 14.0 beta 5 (14A5294e)
**Swift version:** 5.7
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.5

### Demo Project

Attached is a unit test that shows the issue.

One of the tests fails when generating the project with GRDB 6 (`xcodegen -s project-grdb6.yml`).

GRDB 5 (`xcodegen -s project-grdb5.yml`) passes the tests.

Please let me know if you want a ready-generated project instead of XcodeGen.

[CheckTest.zip](https://github.com/groue/GRDB.swift/files/9417385/CheckTest.zip)

**Comment by myyra** [comment]
GitHub won't let me update the original issue attachment, but here is an updated version with a slightly smaller DB definition, just to rule more stuff out.

[CheckTest.zip](https://github.com/groue/GRDB.swift/files/9417496/CheckTest.zip)

**Comment by groue** [comment]
Hello @myyra,

GRDB6 generates an invalid `CHECK` constraint, due to a wrong interpretation of the `.check { $0 != ... }` closures.

GRDB 5 would correctly interpret `!=` as an "SQL operator". But GRDB 6 beta 2 sees a "Swift operator", and compares `Column` values -> `.check { true }` 😱

This is a big regression, and the fix will come very shortly.

Thank you very much for the report! ❤️

**Comment by groue** [comment]
The fix was shipped in the `development` branch.

I still have to update the obsolete [Single-Row Tables](https://github.com/groue/GRDB.swift/blob/master/Documentation/SingleRowTables.md) guide before the next beta.

**Comment by myyra** [comment]
All tests are passing now. Thanks for the quick fix!

Single-row tables would've been my next question, but I was sure you were onto that already, and it was quite an easy change anyway (for my use, at least). But looking forward to having the latest reference for that as well.

BTW, I love how detailed the commit message for the fix was—just a joy to read such Git usage!

**Comment by groue** [comment]
The fix has shipped in GRDB 6 beta 3!

> Single-row tables would've been my next question, but I was sure you were onto that already, and it was quite an easy change anyway (for my use, at least)

If you were following the technique described in the "Single-Row Tables" guide, you should replace the `update` override with `willUpdate`, as described in the [updated guide](https://github.com/groue/GRDB.swift/blob/master/Documentation/SingleRowTables.md). If you do not, calls to `update` methods will fail when run on an empty database.

**Comment by myyra** [comment]
Yup, I had done it exactly as in the updated guide. And now I can start testing the actually new stuff!

**Comment by groue** [comment]
It's good to know that users can upgrade without the guides. I really wish there were no breaking changes that require such scrutiny, but I could never implement support for UPSERT and RETURNING without replacing overrides with callbacks.
