### ISSUE TITLE
Keep throwing SQLite error 21: wrong number of statement arguments xxx

### ISSUE THREAD

**Issue by purepure** [groue/GRDB.swift#1272]
### What did you do?

I create a simple database with field of text, datetime but for every insert statement, the lib Keep throwing SQLite error 21: wrong number of statement arguments xxx for xxx could be vary. I search for these code but I couldn't found any issue with my query and params. Ex

INSERT INTO book (title, overview, created_date, updated_date) VALUES (:tit, :des, :created, :updated)
let params: StatementArguments = [
                "tit": book.title,
                "des": book.overview,
                "created": now,
                "updated": now
            ]
then I got this error: Execute sql with params error: SQLite error 21: wrong number of statement arguments: 369. Plz note that, I tried some query and params(value), the code could be difference but the point is, I dont think there is problem with my query + params. Plz take a look and give me some hints.

Thank

### Environment

**GRDB flavor(s):GRDB
**GRDB version: 5.26.0
**Installation method:CocoaPods
**Xcode version:13.4.1
**Swift version:5.x
**Platform(s) running GRDB:iOS
**macOS version running Xcode: 12.5.1

**Comment by groue** [comment]
Hello @purepure,

Would you please provide a reproducing sample code? It's because I suspect a misuse of a library on your side.

For example, this works as expected:

```swift
// No error
try dbQueue.write { db in
    try db.create(table: "book") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("title", .text).notNull()
        t.column("overview", .integer).notNull()
        t.column("created_date", .datetime).notNull()
        t.column("updated_date", .datetime).notNull()
    }
    
    let now = Date()
    let params: StatementArguments = [
        "tit": "Moby-Dick",
        "des": "A great novel",
        "created": now,
        "updated": now
    ]
    try db.execute(
        sql: "INSERT INTO book (title, overview, created_date, updated_date) VALUES (:tit, :des, :created, :updated)",
        arguments: params)
}
```

**Comment by purepure** [comment]
Thank @groue for your quick response!
After I use your sample code and review my code, I recognize that the error does NOT come from your lib, it is actually my typo. 
I am sorry to waste your time and thank for your support.
Plz close this ticket as no error!

Thank!

**Comment by groue** [comment]
Everything's fine, then :) Happy GRDB!
