### ISSUE TITLE
Have a faster way to save it??

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#1277]
### What did you do?
I want to save the data when the app will be closed.
I just used this way to save it
```swift

   DispatchQueue.global().async {
      // Request the task assertion and save the ID.
      self.backgroundTaskID = UIApplication.shared.
                 beginBackgroundTask (withName: "xxxTasks") {
         // End the task if time expires.
         UIApplication.shared.endBackgroundTask(self.backgroundTaskID!)
         self.backgroundTaskID = UIBackgroundTaskInvalid
      }

      // Prepare events

       // Save data in NSUserDefaults --> work
            
      // Save data in GRDB --> Can't work
        try dbWriter.write({ db in
            for var event in events {
                try event.insert(db)
            }
        })
            
      // End the task assertion.
      UIApplication.shared.endBackgroundTask(self.backgroundTaskID!)
      self.backgroundTaskID = UIBackgroundTaskInvalid
   }
```
but can't save it. 
On the contrary, I find the data can be saved with `NSUserDefaults`

### What did you expect to happen?
Can insert data correctly.
Have a faster way to save it.

### What happened instead?
Can't insert data correctly.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:`4.14.0`
**Installation method:** (CocoaPods, SPM, manual?) `cocoapods`
**Xcode version:`13.2.1`
**Swift version:`5.1`
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) `iOS`
**macOS version running Xcode:`12.5`

**Comment by groue** [comment]
Hello @glve1027,

> Can't insert data correctly.

What do you mean? Please answer as precisely as possible, and don't assume anyone can understand what's in your mind, because telepathy does not exist.

**Comment by glve1027** [comment]
Oh. sorry. my fault. There is a problem with switching threads twice.
If I want to support older version of the iOS system, how do I use something like `await` function

**Comment by groue** [comment]
> There is a problem.

I'm sorry @glve1027, but it is still impossible to guess what you mean. I have to close this issue as "invalid".
