### ISSUE TITLE
SQLITE_BUSY when sharing database with notification extension

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDB.swift#1283]
### What did you do?

I am sharing a database with my main app and the notification extension (NE) with the help of a `DispatchQueue`. This is how I create and share my database:
```
// this is an url which shared the database through an app group
let url = try pathToDb()
var configuration = Configuration()

configuration.busyMode = .timeout(5)

let database = try DatabaseQueue(
    path: url.path,
    configuration: configuration
)
```

My main app and NE calls this piece of function exactly once to open a database. My server communicates with my app in real time through a websocket and push notifications. To ensure the best UX, the server sends a push notification also through the websocket (useful if the user disallowed push notifications). 

This means the data can arrive at the exact same time in the websocket and through a push notification. Both methods will write at least one row in the database. 

When I do stress testing, e.g. I sent 20 messages from my server to my app at the same moment, both the NE and main app will be processing the data from the server. In my NE I get the locking error **instantly** (`SQLite error 5: database is locked`) without waiting for the timeout (5 seconds). I did now solve this with catching the locking error and retry in 0.1 second, but that is a bit ugly.

I tried reproducing this error in my main app by spinning up 2 `DatabaseQueue`s, writing thousands of rows at the same time in different `DispatchQueue`s, **but that worked**. I feel something is not working correct in the NE.

Maybe useful: In the NE, I write to the database with the `inTransaction` method. In my main app, I exclusively use `write` and `read`.

### What did you expect to happen?

No locking error.

### What happened instead?

Locking error

### Environment

**GRDB flavor(s):** GRDB + GRDB-ORM
**GRDB version:** 5.7
**Installation method:** SPM
**Xcode version:** 13
**Swift version:** 5.5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Monterey

### Demo Project

I don't have a demo project, maybe you have some suggestions. It is a bit of a hassle to make a demo projects where notifications can be received.

**Comment by groue** [comment]
Hello @Jasperav,

Sharing SQLite databases in a shared container is very hard, and should be avoided if you can find any other way to communicate between your app and your extension.

If you really need to keep your SQLite database in a shared contained, check the dedicated [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide.

**Comment by Jasperav** [comment]
I will keep doing the loop, I got no issues by doing that. I followed the guide of sharing a database, the problem still exists.

**Comment by groue** [comment]
OK. If you're still looking for help, make sure you provide a substantial amount of details, and everything you have learned while trying to understand the problem!
