### ISSUE TITLE
Adding a GRDB as pod in swift static library and importing that static library in another project is giving issue

### ISSUE THREAD

**Issue by ankitgarggojek** [groue/GRDB.swift#1284]
Swift Version - 5.7
GRDB version - 6.0.0

I have created a static library and added GRDB as pod for that. The static library is compiling.
After adding that static library inside another host application the host app throws an error during compile in the GRDB library.

<img width="1197" alt="Screenshot 2022-10-04 at 12 43 11 AM" src="https://user-images.githubusercontent.com/111558759/193659488-d2f826e3-6dce-42ab-8cfa-fde6c825d35f.png">

PodSpec file of which static library in which GRDB is added

Pod::Spec.new do |spec|

spec.ios.deployment_target = '11.0'

spec.name = "NewSDK"

spec.version = "0.0.7"

spec.summary = "It provides the core functionality of NewSDK"

spec.description = "NewSDK"

spec.source_files = "NewSDK/NewSDK/**/*.swift"

spec.dependency 'GRDB.swift', '~> 6.0.0'

spec.pod_target_xcconfig = { 'SWIFT_VERSION' => '5.7' }

end

**Comment by groue** [comment]
Hello @ankitgarggojek,

It looks like your question is about CocoaPods, not GRDB. Please ask your question in the CocoaPods repository, or StackOverflow, thank you. If you eventually find a problem with GRDB, please reopen this issue with a detailed report.
