### ISSUE TITLE
Can we be allowed to set threadingMode?

### ISSUE THREAD

**Issue by 1Cor125** [groue/GRDB.swift#1290]
### What did you do?

I tried to set the `threadingMode` on the `Configuration` object.

### What did you expect to happen?

I expected to be able to set it to what I wanted.

### What happened instead?

It is not publicly accessible.

### Environment

Latest GRDB.

**Comment by groue** [comment]
Hello @1Cor125,

What do you want to achieve?

**Comment by 1Cor125** [comment]
@groue Thank you for responding. I appreciate the link and I read the docs as you suggested. A little background… I’ve used SQLite for many years from different languages and runtimes so I’m used to setting a few things up a certain way (journal mode, threading mode, etc.) It seems that GRDB means to abstract details away from the dev, which is fine. The principles you outline match what I have learned: serialized writes, parallel reads, reads concurrent with writes, etc. 😊

I’m curious what threading mode DatabasePool connections use? Are you setting that somewhere at start up? If so, to what? Thank you.

**Comment by groue** [comment]
So we're on the same track :-)

All SQLite connections run in the "Multi-thread" mode, [documented](https://www.sqlite.org/threadsafe.html) like this:

> In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.

This mode fits the threading guarantees provided by [`DispatchQueue`](https://developer.apple.com/documentation/dispatch/dispatchqueue), a system object that serialises the execution of tasks - but is not tied to a single thread.

Each time you meet a `Database` objects at runtime, you're in the serial `DispatchQueue` attached to that SQLite connection:

```swift
// On any thread
try dbQueue.write { (db: Database) in
    // In the DispatchQueue of the single connection
    // created by the DatabaseQueue.
}

// On any thread
try dbPool.write { (db: Database) in
    // In the DispatchQueue of the single writer connection
    // created by the DatabasePool.
}

// On any thread
try dbPool.read { (db: Database) in
    // In the DispatchQueue of one reader connection
    // created by the DatabasePool.
}

let observation = ValueObservation.tracking { (db: Database) in
    // In the DispatchQueue of the connection
    // provided by the queue or pool that runs
    // the observation.
}
```

The connections managed by a database pool are no different. There is one writer SQLite connection, and a pool of read-only SQLite connections. Each of those connections runs in the "Multi-thread" threading mode, safely serialized by its own dispatch queue. A database pool uses a [`DispatchSemaphore`](https://developer.apple.com/documentation/dispatch/dispatchsemaphore) to schedule the access to the limited pool of reader connections.

The actual thread where database operations run depends on how you access the database. Synchronous (blocking) accesses call `DispatchQueue.sync` which generally uses the current thread. Asynchronous accesses call `DispatchQueue.async` which schedules the work on some system-managed thread. Please refer to [Dispatch](https://developer.apple.com/documentation/dispatch) for more information.

In this context, the only threading mode that is supported by GRDB connections is `SQLITE_OPEN_NOMUTEX`. Maybe future developments, or feature requests, will open the door for something else - I don't know!

**Comment by 1Cor125** [comment]
@groue I’m happy with this approach. Thanks for taking the time to explain. Great work with this library!

**Comment by groue** [comment]
Thank you @1Cor125! Happy GRDB :-)
