### ISSUE TITLE
How to "ignore" some properties of model so that database records can be less bloated?

### ISSUE THREAD

**Issue by wiencheck** [groue/GRDB.swift#1295]
Let's say I have a playlist model that comes from API and is represented as such struct in my app:

```
public struct SPTPlaylist: SPTItem {
    
    // MARK: Base properties
    
    public let type: SPTObjectType
    public let uri: String
    public let id: String
    public let url: URL
    public let externalURLs: [String: URL]
    
    // MARK: Playlist properties
    
    /**
     true if the owner allows other users to modify the playlist.
     */
    public let isCollaborative: Bool?
    
    /**
     The playlist description. Only returned for modified, verified playlists, otherwise null .
     */
    public let descriptionText: String?
    
    /**
     The name of the playlist.
     */
    public let name: String
    
    /**
     The user who owns the playlist
     */
    public let owner: SPTPublicUser
    
    /**
     Images for the playlist. The array may be empty or contain up to three images. The images are returned by size in descending order. See Working with Playlists.
     Note: If returned, the source URL for the image ( url ) is temporary and will expire in less than a day.
     */
    public let images: [SPTImage]?
    
    /**
     The playlist’s public/private status: true the playlist is public, false the playlist is private, null the playlist status is not relevant. For more about public/private status, see [Working with Playlists](https://developer.spotify.com/documentation/general/guides/working-with-playlists/).
     */
    public let isPublic: Bool?
    
    /**
     The version identifier for the current playlist. Can be supplied in other requests to target a specific playlist version.
     */
    public let snapshotId: String
    
    /**
     Information about the followers of the playlist.
     */
    public let followers: SPTFollowers?
    
    private let tracks: Tracks?
    
    /**
     Number of tracks in the playlist.
     */
    public var total: Int {
        tracks?.total ?? 0
    }
        
    // MARK: Codable stuff
    private enum CodingKeys: String, CodingKey {
        case type, uri, id
        case url = "href"
        case externalURLs = "external_urls"
        
        case images, name, owner, tracks, followers
        case isCollaborative = "collaborative"
        case descriptionText = "description"
        case snapshotId = "snapshot_id"
        case isPublic = "public"
    }
    
}

```

This model contains a bunch of stuff I don't need to keep in my database, such as `followers`, `isCollaborative` or `tracks`. 
When I created SQLite table for this model I defined columns as such:
```
static func defineBaseColumns(onTable table: TableDefinition) {
        table.column("id", .text)
            .notNull()
            .primaryKey()
            .unique(onConflict: .replace)
        table.column("uri", .text)
            .notNull()
        table.column("type", .text)
            .notNull()
        table.column("name", .text)
            .notNull()
        table.column("href", .text)
        table.column("external_urls", .blob)
        table.column("added_date", .date)
        table.column("owner", .blob)
        table.column("images", .blob)
        table.column("description_text", .text)
        table.column("snapshot_id", .text)
    }
```

Upon performing first migration I get errors from SQlite:
```SQLite error 1: table playlist has no column named tracks - while executing `INSERT INTO "playlist" ("type", "uri", "id", "href", "external_urls", "images", "name", "owner", "tracks", "followers", "collaborative", "description", "snapshot_id", "public") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)```

Those properties are marked as optional so I'd expect that JSONDecoder's method `decodeIfPresent` was used.

Is it possible to tell GRDB to ignore those properties? I recall that [Realm offered an easy way to it ](https://stackoverflow.com/questions/40472374/realm-avoid-to-store-some-property)

**Comment by groue** [comment]
Hello @wiencheck,

Sure, this feature is ready-made in the `Decodable` and `Encodable` protocols. Please refer to the "Choose Properties to Encode and Decode Using Coding Keys" section of the [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) Apple documentation.

Basically: don't define `CodingKeys` cases for properties that you don't want to decode or encode in database columns.

**Comment by wiencheck** [comment]
I’m aware of that unfortunately in near future I’ll have to start adopting other models provided by 3rd party framework so I won’t be able to modify CodingKeys

I found [this thread](https://github.com/groue/GRDB.swift/issues/290) which points towards implementing proper encode / init methods but it’s a shame there is no easier way to do that because we lose all the convenience Codable provides as we have to write all initialization code ourselves

**Comment by groue** [comment]
It looks like you are trying to force database support on types which were not designed for that in the first place.

Your models form a tree. For example, one playlist embeds an owner, images, tracks, etc. Those models fit very well a hierarchical JSON structure. But a database is not a hierarchical structure, not at all. It's a set of flat tables. In a database, a playlist has no tracks. Instead, a track points to a playlist.

This is the source of your current troubles.

I suggest you do not try to force database support on models which are not designed for that. Instead, design a parallel set of models which better reflect the database organization. You'll convert one set of models to the other when needed by your application. See [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md).

You might find this very inconvenient.

Well, a data modelling for playlists, tracks, etc. can be achieved with a set of JSON-designed types, or with a set of database-designed types. Both are equally valid. The JSON models are great for networking, the database models are great for local storage. They are both good at their jobs.

The fact that you met the JSON models first does not make them more important in any way. I can easily imagine a reversed story: a developer who starts from implementing the database, and later discovers that the objects have to be sent on the network with a very different JSON structure. Some translation has to be done. It would not be fair to blame JSON for being inconvenient.

**Comment by wiencheck** [comment]
That definitely makes sense, I'll take that approach and just create another model for database. Thanks @groue !

**Comment by groue** [comment]
Thank you, too: your question had me thinking more about the way relationships are modeled in Fluent, the Swift ORM embedded in the Vapor web framework. A typical Fluent models [embeds its relationships](https://docs.vapor.codes/fluent/relations/), just as its JSON representation (the `Playlist` type has a `tracks` property).

Fluent makes it possible to use the same models for the database, and also for the exported JSON representation :-) Indeed, Fluent is focused on web servers, which frequently produce hierarchical JSON representations that *exactly* match their database organization.

This comes with a runtime risk. In Fluent, the `Playlist` type has a `@Children var tracks` property, and the `Track` type has a `@Parent var playlist` property. Unless they have been eager-loaded from the database, those properties fail at runtime: `playlist.tracks` and `track.playlist` "fail" (euphemism for crash, I guess - see "Lazy Eager Loading" in [Fluent Relations documentation](https://docs.vapor.codes/fluent/relations/)).

GRDB has chosen a different path:
- The runtime risk described above is non-existent.
- There is no built-in support for hierarchical representations, because network clients *consume* hierarchies instead of producing them. In my experience, the application logic for dealing with hierarchical values that come from the network is most frequently very custom. Even if GRDB would provide *some kind* of ready-made support for hierarchical inputs, this wouldn't prevent most apps to bypass it and implement their own logic.
