### ISSUE TITLE
Does DatabaseReader have a variable that can store a value?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1298]
Hello
When we want to initialize, add a variable to the DatabaseReader object, which is used to determine the type and source of the database.

Don't know if there is a place for this one to store variables? We looked at the Configuration, but there doesn't seem to be a related method exposed either.

**Comment by groue** [comment]
Hello @SF-Simon,

I'm not sure I understand your question 😅 Would you mind giving a few more details?

**Comment by SF-Simon** [comment]
sorry, my English is not well.

Just hope that the DatabaseReader object has a variable that can store any data object.

 like this:

```
let configuration: Configuration = Configuration()
configuration.object = aaaaa()  // <---- here is any object 
let db = ...

func create(_ db: Database) throws{
        if let dbTag = db.tag, dbTag == 100{ // plan 1
            print(dbTag)
        }
        if let configObject = db.configuration.object as? AnyObject{  // plan 1
            print(configObject)
        }
}
```


> Hello @SF-Simon,
> 
> I'm not sure I understand your question 😅 Would you mind giving a few more details?

**Comment by groue** [comment]
You have a string that you can use for any purpose: `Configuration.label`. Maybe use it as a key in a dictionary?
