### ISSUE TITLE
persistentDictionary in Record class: "Property does not override any property from its superclass" error

### ISSUE THREAD

**Issue by RocketCity** [groue/GRDB.swift#13]
Created a new project and installed GRDB using CocoaPods.  Working through the demo app and in the Person class, getting the error "Property does not override any property from its superclass" for "override var persistentDictionary".

**Comment by groue** [comment]
Hello,

`persistentDictionary` is the new name of a property that used to be named `storedDatabaseDictionary`.

So it looks you are in between the latest version 0.34 and the current state of the master branch, or that I broke the demo apps by mistake.

So, if this is the only error you get, changing the property name should be enough to restore the demo.

**Comment by RocketCity** [comment]
Thanks for the quick response!  Yep, it's storedDatabaseDictionary.

To set up my project, I installed pod 0.34, then added the GRDB folder per the install instructions for the demo app.   The plist in that folder says version 0.34 and Record.swift does have persistentDictionary.

Changing to storedDatabaseDictionary lets me compile, but when I try to delete a record I get "invalid primary key".  

I am very much liking the look of the code using GRDB, very clean and readable!

**Comment by groue** [comment]
Thanks for the compliment, and I'm sorry you have slight difficulties. I'd be very happy to help right now but I'm not in front of my computer... I'd advise you to jump straight to the master branch, skipping the v0.34, until I ship v0.35. The master branch run all tests all right. Tell me again if you are stuck.

**Comment by RocketCity** [comment]
Ok -- sorry, I am a long-time web/SQL developer but utter n00b at iOS/SQLite so this may be a dumb question -- but I am already using the GRDB folder from the latest master branch.  Are you saying don't use the pod?

**Comment by groue** [comment]
The pod at version 0.34 is about to undergo several breaking changes (look at the CHANGELOG.md), so, yes I'd rather use the master branch. The README.md of master branch documents the latest changes: you can trust it.

**Comment by groue** [comment]
@RocketCity Version 0.35.0 is out, and all demo apps and tests run smoothly: update your Podfile! I close this issue. Please open a new one, should you have another question or trouble using GRDB.
