### ISSUE TITLE
Is there a way to clear all data?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1300]
Hello, here I am again. :)

We have a need to clear the database data, that is to say, completely delete the data of all tables, but keep the existing table structure.

Currently we delete by looping our own class names, but we need to modify this process every time we change the class names.

Is there a convenience method to do this process please? Or is there a better idea?

thanks.

**Comment by groue** [comment]
Hello @SF-Simon,

Sure, you can directly ask SQLite to give you the names of the existing tables, and delete their content one by one.

If your schema uses foreign key constraints, the order in which tables are emptied matters. For example, you can not delete an author if some books are referring to it. Since you are deleting all data, foreign keys should not come in the way. Temporarily disabling foreign key checks will make it possible to delete the content of all tables, in any order.

Finally, internal SQLite or GRDB tables must not be deleted.

This can give:

```swift
try dbQueue { db in
    try db.execute(sql: "PRAGMA foreign_keys = OFF")
    do {
        try db.inTransaction {
            let tableNames = try String.fetchAll(db, sql: """
                select name from sqlite_master where type = 'table'
                """)
            for tableName in tableNames {
                if Database.isSQLiteInternalTable(tableName) { continue }
                if Database.isGRDBInternalTable(tableName) { continue }
                try Table(tableName).deleteAll(db)
            }
            return .commit
        }
    } catch {
        try db.execute(sql: "PRAGMA foreign_keys = ON")
        throw error
    }
}
```

If the schema defines SQL triggers, you may have to adjust the above sample code.

**Comment by SF-Simon** [comment]
thank you Groue.

Does it mean I don't need to re-execute the migration method? Just need to rewrite your own new data?

> Hello @SF-Simon,
> 
> Sure, you can directly ask SQLite to give you the names of the existing tables, and delete their content one by one.
> 
> If your schema uses foreign key constraints, the order in which tables are emptied matters. For example, you can not delete an author if some books are referring to it. Since you are deleting all data, foreign keys should not come in the way. Temporarily disabling foreign key checks will make it possible to delete the content of all tables, in any order.
> 
> Finally, internal SQLite or GRDB tables must not be deleted.
> 
> This can give:
> 
> ```swift
> try dbQueue { db in
>     try db.execute(sql: "PRAGMA foreign_keys = OFF")
>     do {
>         try db.inTransaction {
>             let tableNames = try String.fetchAll(db, sql: """
>                 select name from sqlite_master where type = 'table'
>                 """)
>             for tableName in tableNames {
>                 if Database.isSQLiteInternalTable(tableName) { continue }
>                 if Database.isGRDBInternalTable(tableName) { continue }
>                 try Table(tableName).deleteAll(db)
>             }
>             return .commit
>         }
>     } catch {
>         try db.execute(sql: "PRAGMA foreign_keys = ON")
>         throw error
>     }
> }
> ```
> 
> If the schema defines SQL triggers, you may have to adjust the above sample code.

**Comment by groue** [comment]
> Does it mean I don't need to re-execute the migration method? Just need to rewrite your own new data?

Tables were not dropped. You asked "delete the data of all tables, but keep the existing table structure".

**Comment by SF-Simon** [comment]
OK, thank you very much, thank you.

> > Does it mean I don't need to re-execute the migration method? Just need to rewrite your own new data?
> 
> Tables were not dropped. You asked for "delete the data of all tables, but keep the existing table structure".

**Comment by groue** [comment]
Happy GRDB :-)
