### ISSUE TITLE
Question: Any reason why "record protocols" does not inherit archival protocls by default?

### ISSUE THREAD

**Issue by mecoFarid** [groue/GRDB.swift#1305]
This is just a generic question.

In the documentation there are parts that says you can inherit archival protocol to just save a complex field as JSON in db which is great, at least, if you are not querying them.

**Question:** Would there be a any overhead if [Record Protocols](https://github.com/groue/GRDB.swift#record-protocols-overview) implemented archival protocols by default?

**Comment by groue** [comment]
Hello @mecoFarid,

The standard `Codable` protocol is one way to conform to the record protocols `FetchableRecord` and `PersistableRecord`, but it is not the only way. You can provide the implementation of those protocol requirements "by hand", if you want. This can greatly improve performances. See https://github.com/groue/GRDB.swift/wiki/Performance and compare "Codable Records" vs. "Optimized Records".
