### ISSUE TITLE
Feature Request: Generate static column for each property of entity class

### ISSUE THREAD

**Issue by mecoFarid** [groue/GRDB.swift#1306]
### Environment

**GRDB version:** `6.5.0`

### Feature Request

I have checked the documentation about safe columns [here](https://github.com/groue/GRDB.swift#requests) and that is just perfect, at least, from safety point of view. But there could be some problems when you renaming/deleting column and forgot to do it in `enum` class or where you instantiate it with `Column("id")`.

It would be great having a generated extension for entity with static column fields. This way we can use safe column names wherever we want even in raw SQL queries without unexpected runtime exception.

**Example entity:**
```
struct Person: Record{
    var id: String
}
```

**Generated entity extension:**
```
extension Person{
    static var id = Column("id")
}
```

**Comment by groue** [comment]
Hello @mecoFarid,

Maybe you know a Swift technique that can perform such generation? I'd be glad to enhance this area of the library, if such technique exists.

**Comment by mecoFarid** [comment]
@groue There is a codegen library probably you have heard of (https://github.com/krzysztofzablocki/Sourcery). I can experiment with it and check how feasible it is do implement it.

**Comment by groue** [comment]
Sure, Sourcery can help generating code. Please experiment with it. Maybe there is a way to make it useful for all GRDB users. Only time and experience will tell.

**Comment by groue** [comment]
I'm closing the issue, since GRDB will not require Sourcery.
