### ISSUE TITLE
Combine readPublisher not emitting results.

### ISSUE THREAD

**Issue by masterchiip** [groue/GRDB.swift#1307]
### What did you do?

I've been using GRDB for the last years and I've been really happy with it so far. Lately I'm getting my first issue which I could not resolve. I'm using the Combine `readPublisher` from a `DatabaseQueue` and sometimes, in my chain of operators, when I use `receive(on: DispatchQueue.global())`, I'm not receiving the first result from the db, neither success or fail. The operation seems stuck somewhere in `asyncRead`. Maybe I'm missing something important here but everything should be thread safe.

**DatabaseManager function:**
```swift
func fetchAll<D>(_ statement: SQLStatement?) -> AnyPublisher<[D], Error> where D: DatabaseRecord {
        guard let databaseWriter else {
            return Fail(error: CoreError.missingDatabaseConnection(databasePath)).eraseToAnyPublisher()
        }

        return databaseWriter.readPublisher { database in
            guard let statement else { return try D.fetchAll(database) }
            return try D.fetchAll(database, sql: statement.sql)
        }
        .eraseToAnyPublisher()
    }
```

**Chain of operators:**
The chain is fetching the an array of TicketListViewItem, sets the thumbnail for each model and then changes the state of the store.
So I want that the second step is done on the different thread than the main and then the sink to happen on the main.

**ticketListItems** is just building the statement based on the query and calling **fetchAll**
```swift
environment.ticketService.ticketListItems(query: query)
            .receive(on: DispatchQueue.global())
            .flatMapLatest { [weak self] items -> AnyPublisher<[TicketListViewItem], Error> in
                var items = items
                for index in items.indices {
                    self?.environment.imageService.setThumbnail(for: &items[index])
                }

                return Result.Publisher(.success(items)).setFailureType(to: Error.self).eraseToAnyPublisher()
            }
            .receive(on: DispatchQueue.main)
            .sink { [weak self] result in
                switch result {
                case .success(let value):
                    self?.state.items = value
                case .failure(let error):
                    log(category: .error, ["Error": error.localizedDescription])
                }
            }
            .store(in: &state.loadTicketsCancellables)
```

Side note:
When I've removed the ` .receive(on: DispatchQueue.global())`, the result is coming all the times.

### What did you expect to happen?

To receive the result every time.

### What happened instead?

I'm receiving the result approximately 90% of the time.

### Environment

**GRDB flavor(s):GRDB** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:6.5.0**
**Installation method:SPM** (CocoaPods, SPM, manual?)
**Xcode version:14.1**
**Swift version:5.7**
**Platform(s) running GRDB:iOS** (iOS, macOS, watchOS?)
**macOS version running Xcode:13.0.1**

**Comment by groue** [comment]
Hello @masterchiip,

That's odd, isn't it? At first glance, I don't quite see where things go wrong.

Maybe we could get some debugging information from the `print` Publisher operator? I would put some prints on some key publishers in order to trace when they're subscribed, when they publish values, and when they're cancelled. This could really help sorting things out and grab a clear view of what's happening.

**Comment by regattaguru** [comment]
Could be related to compiler warnings I am getting on lines 110 and 137 of Query.swift

'Publishing changes from within view updates is not allowed, this will cause undefined behavior.'

Possibly needs to be wrapped MainActor

**Comment by masterchiip** [comment]
Hi @groue, first thanks for the quick answer!
Yeah, it's super odd. When I was investigating the initial problem I wasn't expecting to be actually there.
Maybe you're on the right path, maybe the subscription has been cancelled and I'm waiting like a fool.
In my tests I didn't consider it but sound reasonable to double check.

I'll do today some other tests and If I don't find nothing I'll close the issue 🙏

Regarding the `receiveOn` parameter of the `readPublisher`, do you think that having the same scheduler for the majority of the chain's operators (including then the database manager functions) will speed up the chain? I know that switching schedulers has a cost but I don't know actually how expensive it is.

**Comment by groue** [comment]
> I'll do today some other tests and If I don't find nothing I'll close the issue 🙏

Sounds good :-)

> [...] do you think that having the same scheduler for the majority of the chain's operators (including then the database manager functions) will speed up the chain?

I don't know if there is much difference. I assume that database operations are much slower than dispatch queue hops since they're doing I/O.

**Comment by masterchiip** [comment]
Happy new year 🎇 @groue and thanks for the precious support!
After more digging I've found that cancelling the subscription manually was causing the issue.
Even if I was doing it before re-subscribing, seems like it's not completely safe. 
So I moved away from that, using now a simple `flatMapLatest`.

Closing the issue 🎉

**Comment by groue** [comment]
Good news @masterchiip :-) Happy GRDB and happy 2023!
