### ISSUE TITLE
Inserting data using Table and Row

### ISSUE THREAD

**Issue by filipealva** [groue/GRDB.swift#1309]
### What did you do?

I'm setting up a generic wrapper to access GRDB. I'm planning to use `Table` and `Row` to do that. 

### What did you expect to happen?

I expect that there's a way to insert records using `Table` by providing the table's name. Something like: `Table("player").insert(playerDictionary, db)`

Is there a way to do that? I'm trying to find something on the Docs, but I can't find it yet.

Thank you

**Comment by groue** [comment]
Hello @filipealva,

`Table` does not provide any insertion method indeed. The library focuses on apps that have one [persistable record](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol) type per table.

**Comment by filipealva** [comment]
That makes a lot of sense. Sorry if it was a silly question, still trying to get rid from other db platforms biases 🤓
