### ISSUE TITLE
How to use SQL statements with unchecked arguments when your table has a column of the blob type?

### ISSUE THREAD

**Issue by filipealva** [groue/GRDB.swift#1319]
I need to improve the performance of batch inserts on my project. 

I saw that we can get better performance results when using SQL statements to do batch inserts on #926.
On this issue, it's advised to use an SQL statement that takes unchecked arguments as parameters. 

However, I have several tables with columns of the `blob` type. 

How should I pass the value of a `blob` column if I'm using unchecked arguments? Should I encode it and pass the data on the function that replaces the unchecked arguments with the actual values?

**Comment by groue** [comment]
Thanks for opening a dedicated issue @filipealva :-)

To feed a `blob` column, pass a `Data` (from Foundation) in the statement arguments.

**Comment by filipealva** [comment]
Thank you for the support 🙏

**Comment by groue** [comment]
You're welcome, happy GRDB!
