### ISSUE TITLE
quotedDatabaseIdentifier doesn't escape double quotes

### ISSUE THREAD

**Issue by EvanHahn-Signal** [groue/GRDB.swift#1325]
### What did you do?

Tried to create a table with a double quote in its name.

Specifically, this fails:

```swift
try db.create(table: "\"") { table in
    table.column("color", .text)
}
```

The above example is a table name that's just one double quote (`"`). It also fails, in different ways, if the table has double quotes. For example, `"foo"` also breaks.

### What did you expect to happen?

The table would be created, because SQLite accepts it.

The following is valid in SQLite:

```sql
CREATE TABLE '"' (color TEXT);
```

It's also valid if I write raw SQL with GRDB:

```swift
try db.execute(sql: "CREATE TABLE '\"' (color TEXT)")
```

However, using GRDB's syntax fails to escape the quote correctly.

### What happened instead?

I got a SQLite syntax error because it tried to run the following query:

```sql
CREATE TABLE """ ("color" TEXT);
```

### Environment

**GRDB flavor(s):** SQLite
**GRDB version:** 6.6.1 (also happens with 5.26.0)
**Installation method:** SPM
**Xcode version:** 14.1
**Swift version:** 5.7.1
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 13.2

### Sample code

```swift
import Foundation
import GRDB

let dbQueue = try DatabaseQueue()

try dbQueue.write { db in
    // This doesn't work:
    try db.create(table: "\"") { table in
        table.column("color", .text)
    }

    // This works instead:
    // try db.execute(sql: "CREATE TABLE '\"' (color TEXT)")

    try db.execute(sql: "INSERT INTO '\"' (color) VALUES ('Red')")
    try db.execute(sql: "INSERT INTO '\"' (color) VALUES ('Blue')")

    let names = try String.fetchAll(db, sql: "SELECT color FROM '\"'")
    print(names)
}
```

### Additional info

This may be out of scope for GRDB. Feel free to close if that's the case.

**Comment by groue** [comment]
Hello @EvanHahn-Signal,

Indeed the escaping algorithm is pretty basic: it just wraps identifiers in double quotes. The goal is to help users use SQL keywords as table names: `CREATE TABLE "table"`, `"index"`, `"check"`, `"case"`, `"constraint"`, `"group"`, etc.

Identifiers such as `"` are quite not expected in a regular database schema. Or do they?

**Comment by groue** [comment]
The SQLite documentation [has something to say](https://www.sqlite.org/lang_keywords.html) about `CREATE TABLE '"' (color TEXT)` (emphasis mine):

> For resilience when confronted with historical SQL statements, SQLite will sometimes bend the quoting rules above:
>
> - If a keyword in single quotes (ex: 'key' or 'glob') is used in a context where an identifier is allowed but where a string literal is not allowed, then the token is understood to be an identifier instead of a string literal.
>
> - If a keyword in double quotes (ex: "key" or "glob") is used in a context where it cannot be resolved to an identifier but where a string literal is allowed, then the token is understood to be a string literal instead of an identifier.
>
> **Programmers are cautioned not to use the two exceptions described in the previous bullets.** We emphasize that they exist only so that old and ill-formed SQL statements will run correctly. Future versions of SQLite might raise errors instead of accepting the malformed statements covered by the exceptions above.

Since the SQLite authors discourage such a use, I don't think GRDB has to support it. You can use a raw SQL query if you really need to.

**Comment by groue** [comment]
I'm closing the issue. Please bring a strong case on the table if you want it reopened, thank you!
