### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by hansengj** [groue/GRDB.swift#1327]
### What did you do?

Manually installed GRDB.swift v6.6.1

### What did you expect to happen?

For SwfitUI app to compile without any issues.

### What happened instead?

Compilation failed with issue: "Command PhaseScriptExecution failed with a nonzero exit code"

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v6.6.1
**Installation method:** manual
**Xcode version:** 14.2
**Swift version:** 5.7.2
**Platform(s) running GRDB:** iOS, macOS
**macOS version running Xcode:** 13.2
NOTE: Everything running on a macMini M1

### Demo Project

Cannot provide; project under development. Issue is with GRDB, not SwiftUI code, i.e., build failed before code compiled.

**Comment by hansengj** [comment]
Issue was the build of GRDB was trying to run the Swiftlint script in the Built Phase because it did not specify any outputs.  Resolved by removing the shell script to be executed: ${PROJECT_DIR}/Scripts/swiftlint.sh

The manual install instructions should have specified swiftlint needs to be installed and how, or how to remove the execution of swfitlint.sh. Or the Swiftlint phase should be removed in the distributed code.

**Comment by groue** [comment]
Thank you for the investigation, @hansengj

**Comment by hansengj** [comment]
You are welcome. Hope you take one or more of my suggestions, so others don’t encounter the same issue.  —Gil

**Comment by groue** [comment]
Hello again @hansengj,

The SwiftLint build phase does not require Swiftlint to be installed. I could build a project that embeds the GRDB with the "manual installation" technique, on a machine where SwiftLint is not installed.

Would it be possible for you to help reproduce your error?

**Comment by groue** [comment]
I run on an M1, too.

SwiftLint is installed on your machine: the "Linting Swift files in current working directory" message can only be printed by SwiftLint.

So it looks like you're running some old version of the tool.

OK, I'll fix the build phase. GRDB is not supposed to depend on SwiftLint, not even on a specific version. I'll just ignore SwiftLint errors.

Thank you for your response 👍

**Comment by hansengj** [comment]
If I installed SwiftLint, then I don’t remember when or how. I migrated everything from my old iMac to my new M1 using TimeMachine. I will investigate where it is installed.

I agree with your build phase fix, i.e., ignore SwiftLint errors.

Glad to have helped.

**Comment by groue** [comment]
You did :-) Happy GRDB!

**Comment by groue** [comment]
The fix will ship in next version. You may still see yellow warnings or red errors in the Xcode build log (as a way to bring your attention to the eventual problem), but your app will build successfully.

**Comment by hansengj** [comment]
Thanks for the heads up.  —Gil

**Comment by groue** [comment]
The fix has shipped in v6.7.0
