### ISSUE TITLE
ValueObservation does not monitor the erase() function of dbWriter

### ISSUE THREAD

**Issue by benck** [groue/GRDB.swift#1329]
### What did you do?

I have a shared object of AppDatabase like the demo project. And I add the SharedValueObservation in the class of AppDatabase to make different view controllers listen to the same observation.
The ValueObservation works properly with normal insertion and deletion to database. However, if I execute the erase() function of dbWriter, the onChange was not called.

### What did you expect to happen?

For example, the user would like to erase all local content in his device and get a new start, and my app would erase the whole all tables and create them again. The onChange in view controller is called during the dbWriter.erase() method and update the view with empty data.

### What happened instead?

 Since the view controller was never called of this change, the view controller remained with the old data before erasing.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.6.1
**Installation method:** SPM
**Xcode version:** 14.2
**Swift version:** 5.7
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 13.2

### Demo Project

AppDatabase:

```
final class AppDatabase {
    private var flightObservation: SharedValueObservation<[Flight]>?

    /// Creates an `AppDatabase`, and make sure the database schema is ready.
    init(_ dbWriter: any DatabaseWriter) throws {
        self.dbWriter = dbWriter
        try migrator.migrate(dbWriter)
    }
    private let dbWriter: any DatabaseWriter

    private var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()
        print("ready to migrate...")
        
        migrator.registerMigration("createDatabase") { db in
            // Create a table
            // See https://github.com/groue/GRDB.swift#create-tables
            
            print("createDatabase")

            try db.create(table: "flight") { t in
                t.autoIncrementedPrimaryKey("localId")
                t.column("date", .date).notNull()
                ......
            }
        }
    }

    // this function is called when user would like to erase the local data of his device. However, ValueObservation is not monitoring the erase()
    func dropAndCreateTables() {
        do {
            try dbWriter.erase()
            try migrator.migrate(dbWriter)
        } catch {
            print(error)
        }
    }

    func sharedFlightsObservation() -> SharedValueObservation<[Flight]>? {
        
        if flightObservation == nil {
            flightObservation = ValueObservation.tracking(Flight.fetchAll).shared(in: dbWriter)
        }
        return flightObservation
    }
}
```

MyViewController:

```

class MyViewController {
    private var flightsCancellable: DatabaseCancellable?

    override func viewDidLoad() {
        super.viewDidLoad()
         ..... 
        observeFlights()
    }

    private func observeFlights() {
        flightsCancellable = AppDatabase.shared.sharedFlightsObservation()?.start(onError: { error in
            print("flightsCancellable error \(error)")
        }, onChange: { flights in
            // called if normal insertion to the table, but not called if tables erased and re-created
            print("flightsCancellable reloadFromDatabase()")
            self.reloadFromDatabase()
        })
    }

}
``` 

Thank you.

**Comment by groue** [comment]
Hello @benck,

Erasing the database drops all tables, and this is a schema change distinct from deleting the contents of all tables. Schema changes are not detected by database observers (`ValueObservation`, `DatabaseRegionObservation`, `TransactionObserver`).

You may recreate your observations after the database content has been erased and the schema recreated.

You may also delete the contents of all your tables instead - this will trigger the observations. You'll find some sample code at https://github.com/groue/GRDB.swift/issues/1300#issuecomment-1342256507

**Comment by benck** [comment]
Hi @groue , thanks for you instant reply.

I just updated my code. First, set the shared observation variable to nil after re-create the database. Then move the start of the observation into viewWillAppear in my view controller. If the shared observation is nil, observe again.
It works in iPhone version of my app because of I'm using basic TabBarController.
However, in iPad version, I use sidebar (SplitViewController) instead of tabs. MyViewController stays on the screen while dropAndCreateTables() is called by other view controller. Because viewWillAppear() is not called in this case, observation could not be re-created.

About your second recommendation... it seems to be a better idea for my scenario. However, I would like to reset the AUTOINCREMENT value after all tables deleted. How could I do that without erasing the entire database?

```
final class AppDatabase {
   var flightObservation: SharedValueObservation<[Flight]>?

    init(_ dbWriter: any DatabaseWriter) throws {
        self.dbWriter = dbWriter
        try migrator.migrate(dbWriter)
    }
    private let dbWriter: any DatabaseWriter

    private var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()
        migrator.registerMigration("createDatabase") { db in
            try db.create(table: "flight") { t in
                t.autoIncrementedPrimaryKey("localId")
                t.column("date", .date).notNull()
                ......
            }
        }
    }

    func dropAndCreateTables() {
        do {
            flightObservation = nil
            try dbWriter.erase()
            try migrator.migrate(dbWriter)
        } catch {
            print(error)
        }
    }

    func sharedFlightsObservation() -> SharedValueObservation<[Flight]>? {
        if flightObservation == nil {
            flightObservation = ValueObservation.tracking(Flight.fetchAll).shared(in: dbWriter)
        }
        return flightObservation
    }
}
```

MyViewController:

```
class MyViewController {
    private var flightsCancellable: DatabaseCancellable?

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        if AppDatabase.shared.flightObservation == nil {
            print("viewWillAppear flightObservation = nil, observe again")
            observeFlights()
        }
    }

    private func observeFlights() {
        flightsCancellable = AppDatabase.shared.sharedFlightsObservation()?.start(onError: { error in
            print("flightsCancellable error \(error)")
        }, onChange: { flights in
            print("flightsCancellable reloadFromDatabase()")
            self.reloadFromDatabase()
        })
    }

}
```

**Comment by groue** [comment]
> However, I would like to reset the AUTOINCREMENT value after all tables deleted. How could I do that without erasing the entire database?

I don't know, but it looks like SQLite has dedicated documentation: https://www.sqlite.org/autoinc.html#the_autoincrement_keyword

**Comment by groue** [comment]
I'm closing the issue, because I think your initial question has its answer. Don't hesitate asking more questions if needed!
