### ISSUE TITLE
LIKE operator

### ISSUE THREAD

**Issue by dm7sistemas** [groue/GRDB.swift#133]
How I use this example I try but I don't know 
I need select using like 

        dbverbs = dbQueue.inDatabase { db in
            //db_verbs.filter(Column("basename") == "be%").fetchAll(db)

            //db_verbs.filter(["be"].contains(Column("basename"))).fetchAll(db)
            db_verbs.order(Column("basename").asc, Column("past").asc).fetchAll(db)
        }

**Comment by groue** [comment]
Hello @dm7sistemas,

You want to use the LIKE operator of SQLite. And it is missing from GRDB so far: that's why you can't find it in the [documentation](https://github.com/groue/GRDB.swift#expressions).

I guess it should be added, yes.

Until then, use a little SQL snippet:

```swift
db_verbs
    .filter(sql: "basename LIKE ?", arguments: ["be%"])
    .order(Column("basename"), Column("past"))
    .fetchAll(db)
```

**Comment by dm7sistemas** [comment]
Ok, Thanks for help me. I started using yesterday !!

**Comment by groue** [comment]
You're welcome! Happy GRDB!

**Comment by groue** [comment]
In next GRDB version, you'll write `db_verbs.filter(Column("basename").like("be%"))`
