### ISSUE TITLE
Unexpected order-of-execution with 'readPublisher(receiveOn:value:)'

### ISSUE THREAD

**Issue by mpretty-cyro** [groue/GRDB.swift#1334]
I've been debugging an odd behaviour which has been intermittently occurring in the codebase I'm working on for a little while, I managed to finally create a replicatable version of it (using the below code) and commenting out the `.receiveValues(on: scheduler)` or replacing it with `receive(on: scheduler)` within the `readPublisher(receiveOn:value:)` seems to result in the expected behaviour.

Please let me know if I'm doing something odd/wrong in the example code included below, in the original code we `flatMap` from the `readPublisher` into an API call which I tried to replicate via the `asyncAfter`.

**Note:** The issue **does not** seem to happen with a serial `DispatchQueue` but for our use case we want it to run in a concurrent queue.

### What did you do?

Called `Test.runTest()` with the below code:

```
public struct Test {
    private static var cancellable: Cancellable? = nil
    
    static func runTest() {
        let concurrentQueue = DispatchQueue(
            label: "TestQueue",
            qos: .default,
            attributes: [.concurrent],
            autoreleaseFrequency: .inherit,
            target: nil
        )
        Test.cancellable = Storage.shared
            .readPublisher(receiveOn: concurrentQueue) { db in false }
            .print("Test")
            .flatMap { _ in
                Deferred {
                    Future<Bool, Error> { fulfill in
                        concurrentQueue.asyncAfter(deadline: .now() + .seconds(3)) {
                            fulfill(Result.success(true))
                        }
                    }
                }
            }
            .sink(
                receiveCompletion: { _ in print("Test Result: receiveCompletion") },
                receiveValue: { val in print("Test Result: receiveValue \(val)") }
            )
    }
}
```

### What did you expect to happen?

The `receiveValue` closure should be called with a `true` value, then the `receiveCompletion` closure should be called (ie. the below output)

```
Test: receive subscription: (GRDB.(unknown context at $1032255ec).ReceiveValuesOnSubscription<Combine.Deferred<Combine.Future<Swift.Bool, Swift.Error>>, __C.OS_dispatch_queue, Combine.Publishers.Print<Combine.AnyPublisher<Swift.Bool, Swift.Error>>.(unknown context at $19b3fd458).Inner<Combine.Publishers.FlatMap<Combine.Deferred<Combine.Future<Swift.Bool, Swift.Error>>, Combine.Publishers.Print<Combine.AnyPublisher<Swift.Bool, Swift.Error>>>.(unknown context at $19b40a4c0).Outer<Combine.Subscribers.Sink<Swift.Bool, Swift.Error>>>>)
Test: request unlimited
Test: receive value: (false)
Test: receive finished
Test Result: receiveValue true
Test Result: receiveCompletion
```

### What happened instead?

`receiveCompletion` is called but `receiveValue` is never called (it does seem to output the `false` value as we can see from the `Test: receive value: (false)` log but doesn't seem to get to the `receiveValue` closure)

```
Test: receive subscription: (GRDB.(unknown context at $105bed5ec).ReceiveValuesOnSubscription<Combine.Deferred<Combine.Future<Swift.Bool, Swift.Error>>, __C.OS_dispatch_queue, Combine.Publishers.Print<Combine.AnyPublisher<Swift.Bool, Swift.Error>>.(unknown context at $19b3fd458).Inner<Combine.Publishers.FlatMap<Combine.Deferred<Combine.Future<Swift.Bool, Swift.Error>>, Combine.Publishers.Print<Combine.AnyPublisher<Swift.Bool, Swift.Error>>>.(unknown context at $19b40a4c0).Outer<Combine.Subscribers.Sink<Swift.Bool, Swift.Error>>>>)
Test: request unlimited
Test: receive finished
Test Result: receiveCompletion
Test: receive value: (false)
```

### Environment

**GRDB flavor(s):** GRDB, SQLCipher
**GRDB version:** 6.1.0
**Installation method:** CocoaPods
**Xcode version:** 14.1
**Swift version:** 5.7
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 13.0.1

**Comment by groue** [comment]
Hello @mpretty-cyro,

Concurrent queues can't guarantee the expected ordering, since Combine events are dispatched independently. Value is dispatched before completion, but the concurrent queue can handle them in any order (it's concurrent, after all).

For example, consider this sample code (you can run it in a playground):

```swift
import Combine
import Dispatch

let publisher = [1].publisher

let queue = DispatchQueue(label: "", attributes: .concurrent)
for i in 0..<1000 {
  let semaphore = DispatchSemaphore(value: 0)
  publisher
    .receive(on: queue)
    .print("Test \(i)")
    .sink { _ in
      semaphore.signal()
    } receiveValue: { _ in }
  semaphore.wait()
}
```

In the output, you'll see some "unexpected" runs. An example from my own output:

```
😱
Test 37: receive subscription: (ReceiveOn)
Test 37: request unlimited
Test 37: receive finished
Test 37: receive value: (1)
```

I suggest you reconsider your need for a concurrent queue. Alternatively, you may use a serial queue that targets your concurrent queue.

**Comment by mpretty-cyro** [comment]
Thanks for getting back so quickly - very good to know that the events are dispatched independently, it does make sense that they would be 😅

I guess I'll need to rework some logic in our codebase then, and sorry to bother you with something unrelated to GRDB!

**Comment by groue** [comment]
You're welcome!

> very good to know that the events are dispatched independently

Yeah, this is baked in [Subscriber](https://developer.apple.com/documentation/combine/subscriber). One can not "group" events.

Happy serial GRDB :-)
