### ISSUE TITLE
busyMode = .timeout isn't working as expected

### ISSUE THREAD

**Issue by richardhenry** [groue/GRDB.swift#1339]
Hi groue, thanks for creating GRDB!

We're using GRDB to share a SQLite database between the main process in our iOS app and a UNNotificationServiceExtension which handles decryption of push notification content. In case it's relevant, we're also using SQLCipher to encrypt the database file.

We've configured a DatabasePool to use `busyMode = .timeout(10)`, which I would have expected to block the GRDB write queue for up to 10 seconds if the other process has acquired the write lock, but what we're seeing in practice is that write queries immediately throw a SQLITE_BUSY error ("DatabaseError SQLite error 5: database is locked") without any delay if the other process is currently writing.

I tried setting a breakpoint in GRDB code to verify that `sqlite3_busy_timeout` is definitely being called.

What is the expected behavior here? Thanks in advance for your reply.

--

Both the iOS app and the UNNotificationServiceExtension use a DatabasePool, which is configured like this:

```
let coordinator = NSFileCoordinator(filePresenter: nil)
var coordinatorError: NSError?

coordinator.coordinate(writingItemAt: url, options: .forMerging, error: &coordinatorError) { url in
    var config = Configuration()

    config.prepareDatabase { db in
        // SQLCipher
        try db.execute(sql: "PRAGMA key=\"x'\(key)'\"")
        try db.execute(sql: "PRAGMA cipher_salt=\"x'\(salt)'\"")
        try db.execute(sql: "PRAGMA cipher_plaintext_header_size = 32")
    }

    config.busyMode = .timeout(10)

    do {
        self.pool = try DatabasePool(path: url.path, configuration: config)
    } catch {
        // error handling
    }
}
```

The really relevant part to this ticket is just the `config.busyMode =` but I wanted to include some additional context in case it's relevant for some non-obvious reason.

**Comment by richardhenry** [comment]
I just read issue #1283 which sounds a lot like this issue, and also read this helpful answer on StackOverflow: https://stackoverflow.com/questions/30438595/sqlite3-ignores-sqlite3-busy-timeout/30440711#30440711

It sounds like we should build an abstraction around our database writes that handles these errors. Feel free to close this issue unless you want to add anything, and thanks!

**Comment by groue** [comment]
Hello @richardhenry, thank you for the report.

Indeed, that's not what we'd expect from the [`sqlite3_busy_timeout`](https://www.sqlite.org/c3ref/busy_timeout.html) documentation.

At first sight you do not do anything wrong, but we're exploring a very vast territory, and maybe one detail makes the difference. The most difficult part in this issue is to reproduce the problem. Would it be possible for you to setup a sample project?

**Comment by richardhenry** [comment]
Sure thing, I'll put something together. Thanks!

**Comment by groue** [comment]
GRDB has two tests regarding the busy timeout that were commented out (flaky, plus odd behavior in Xcode 10.0 and tvOS 10.0).

I just restored them - if their flakiness persists, it will be an opportunity to better understand the busy timeout 😅

**Comment by groue** [comment]
I'm closing the issue due to lack of activity. Feel free to chime in when you have more information, @richardhenry! We'll reopen the issue accordingly.
