### ISSUE TITLE
non modular header fix?

### ISSUE THREAD

**Issue by shams-ahmed** [groue/GRDB.swift#134]
### Xcode error:
```
(lldb) po "#Shared Swift state for xctest has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.
error: in auto-import:
failed to get module 'XXX' from AST context:
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/GRDB.h"
        ^

error: /Users/shamsahmed/GIT/XXX/SDK/Pods/GRDB.swift/GRDB/GRDB.h:9:9: error: include of non-modular header inside framework module 'GRDB'
#import <GRDB/GRDB-Bridging.h>
        ^

error: could not build Objective-C module 'GRDB'

(lldb) 
```

### Discussion from cocoapods thread:
https://github.com/CocoaPods/CocoaPods/issues/4420

### Possible fix:
change:
`#import <GRDB/GRDB-Bridging.h>`
to:
`#import "GRDB-Bridging.h"`

What do you think?

**Comment by groue** [comment]
Hello @shams-ahmed 

I can't reproduce your issue. Please provide the versions of all your tools: Xcode, CocoaPods, Swift, and GRDB.

**Comment by shams-ahmed** [comment]
- Xcode version 8.0 (8A218a)
- CocoaPods 1.1.0.rc.2
- Swift 3
- GRDB v0.81.2

**Comment by groue** [comment]
There is a mismatch between Swift 3 and GRDB v0.81.2 (which targets Swift 2.3).

Bump GRDB to 0.85.0.

**Comment by groue** [comment]
No news, good news: happy GRDB!

**Comment by fstephany** [comment]
I get the same error when building for the Simulator but not when building for a real device.

Stack:

- CocoaPods 1.1.1
- XCode 8.0
- Swift 3.
- Deployment Target: 9.3
- Base SDK: Latest (iOS 10.0)

Error:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/GRDB.h"
        ^
/Users/fstephany/Code/clients/XXX/YYY/ios/Build/Products/Debug-iphonesimulator/GRDB.swift/GRDB.framework/Headers/GRDB.h:9:9: error: 'GRDB/GRDB-Bridging.h' file not found
#import <GRDB/GRDB-Bridging.h>
        ^
<unknown>:0: error: could not build Objective-C module 'GRDB'
```

Pods:
```
$ pod --version
1.1.1
$ pod install
Analyzing dependencies
Downloading dependencies
Using Crashlytics (3.8.3)
Using Fabric (1.6.10)
Using GRDB.swift (0.89.2)
Using MBProgressHUD (1.0.0)
Using RxCocoa (3.0.0)
Using RxSwift (3.0.0)
Using SwiftyJSON (3.1.1)
Using XCGLogger (4.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 8 total pods installed
```

**Comment by groue** [comment]
I also have this error from time to time. It is transient and looks like a Xcode bug to me: rebuild until it disappears. You may have to clean your build folder.

**Comment by fstephany** [comment]
Yep, I'm always perform a clean when I get an error like that on XCode. 
But since this morning, it doesn't want to build for the emulator no matter what I do. Probably another XCode quirk as you say ;) 

(Oh and thank you for GRDB.swift by the way, it's great!)

**Comment by groue** [comment]
I hope the last release has not broken CocoaPod support. Tell me if you're really stuck. And thanks for the compliment!

**Comment by fstephany** [comment]
Nope, don't worry, it builds fine on a device!
