### ISSUE TITLE
Error fetching data form a table

### ISSUE THREAD

**Issue by Momeks** [groue/GRDB.swift#1340]
Hello,
 I have a problem with reading the database file in the document directory. I created my Model like this:

```
struct DataBase: Identifiable, Hashable {
	var id: Int
	var word: String
	var meaning: String
	var pron: String
	var bookmark: Bool
	var dateTimeView: Date
	
	static let databaseTableName = "DICM"
	
	enum CodingKeys: String, CodingKey {
		case id
		case word = "NAME"
		case meaning = "MEAN"
		case pron = "PRON"
		case bookmark
		case dateTimeView
	}
}

extension DataBase: Codable, FetchableRecord, MutablePersistableRecord {
	// Define database columns from CodingKeys
	enum Columns {
		static let id = Column(CodingKeys.id)
		static let word = Column(CodingKeys.word)
		static let meaning = Column(CodingKeys.meaning)
		static let pron = Column(CodingKeys.pron)
		static let bookmark = Column(CodingKeys.bookmark)
		static let dateTimeView = Column(CodingKeys.dateTimeView)
	}
	
	// Initialize a record from a database row
	init(row: Row) {
		id = row[Columns.id]
		word = row[Columns.word]
		meaning = row[Columns.meaning]
		pron = row[Columns.pron]
		bookmark = row[Columns.bookmark]
		dateTimeView = row[Columns.dateTimeView]
	}
	
	// Encodes the record to the database
	func encode(to container: inout PersistenceContainer) {
		container[Columns.id] = id
		container[Columns.word] = word
		container[Columns.meaning] = meaning
		container[Columns.pron] = pron
		container[Columns.bookmark] = bookmark
		container[Columns.dateTimeView] = dateTimeView
	}
}

extension DerivableRequest where RowDecoder == DataBase {
	func orderedByWord() -> Self {
		order(DataBase.Columns.word.collating(.localizedCaseInsensitiveCompare))
	}
}


```

And then tried to read files using a DatabaseManager class:

```
class DataBaseManager: ObservableObject {
	
	private let dbQueue: DatabaseQueue
	
	init(fileName: String) {
		let documentDirectoryURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
		let databaseURL = documentDirectoryURL.appendingPathComponent("\(fileName).sql")
		do {
			dbQueue = try DatabaseQueue(path: databaseURL.path)
		} catch {
			fatalError("Error initializing database queue: \(error.localizedDescription)")
		}
	}
	
	func fetchData() -> [DataBase] {
		var data = [DataBase]()
		// Perform a query to fetch all data from the DICM table, ordered by word
		do {
			try dbQueue.read { db in
				let rows = try Row.fetchAll(db, sql:("SELECT * FROM \(DataBase.databaseTableName) ORDER BY \(DataBase.Columns.word)"))
				data = rows.map { row in
					DataBase(row: row)
				}
			}
		} catch {
			print("Error fetching data: \(error)")
		}
		return data
	}
} 
```

But I am getting this error, and returns null
**Error fetching data: SQLite error 1: no such table: DICM - while executing `SELECT * FROM DICM`**

I would be grateful if you review my code and help me to solve this problem. Thank you

**Comment by groue** [comment]
Hello @Momeks,

Let's fix your problems. You have two.

1. Your `DataBase` record type says that it uses the `DCIM` table, but the database does not contain such table. This is quite clear when you read the SQLite error: `no such table: DICM`.

    You have to make sure the record type and the database schema agree: they must use the same table name.

    - Does your app create the database file? Then you need to create the DCIM table before using it. See [Migrations](https://swiftpackageindex.com/groue/grdb.swift/v6.8.0/documentation/grdb/migrations) and the [demo apps](https://github.com/groue/GRDB.swift/tree/master/Documentation/DemoApps).
    - Does your app use an existing database? Check the name of the database tables in the database file, and update `DataBase.databaseTableName` record accordingly. If you don't know the table names in your database file, open it with a free SQLite reader, or directly in the terminal:
    
        ```
        $ sqlite3 /path/to/your/database.sqlite
        sqlite> SELECT * FROM sqlite_master WHERE type = 'table';
        | type  | name | tbl_name | rootpage |           sql           |
        |-------|------|----------|----------|-------------------------|
        | table | toto | toto     | 2        | CREATE TABLE toto(a, b) |
        ```

        In my example (this is not your database), the database file contains one table, named `toto`.

2. Your sample code does not generate valid SQL.

    This is quite clear in the email you sent me. It contains an error that tells that your app was not executing valid SQL:

    ```
    Error fetching data: SQLite error 1: unrecognized token: ":"
    - while executing `SELECT * FROM DICM ORDER BY Column(name: "NAME")`
    ```

    Your best option is maybe to just replace:

    ```diff
    // Remove:
    -let rows = try Row.fetchAll(db, sql:("SELECT * FROM \(DataBase.databaseTableName) ORDER BY \(DataBase.Columns.word)"))
    -data = rows.map { row in
    -    DataBase(row: row)
    -}
    // Replace with:
    +data = try DataBase.order(DataBase.Columns.word).fetchAll(db)
    ```

    If you really want to use SQL, that's fine. But take care of the eventual errors. Do read them, do understand them, and react accordingly. SQLite is a nice database that tells what's wrong. Put it on your side!

    You may eventually write:

    ```swift
    data = try DataBase.fetchAll(db, sql: """
        SELECT * FROM \(DataBase.databaseTableName)
        ORDER BY \(DataBase.Columns.word.name)
        """)
    ```

**Comment by Momeks** [comment]
Thank you so much, I am still getting that error:
```
Error fetching data: SQLite error 1: no such table: DICM - while executing `SELECT * FROM DICM
ORDER BY NAME`
[]
```
 here is what my database table looks like:
![Screen Shot 2023-02-26 at 8 27 52 PM](https://user-images.githubusercontent.com/113414/221425017-be180889-ebbe-4f47-804b-1f1774387980.jpg)

First I am calling the dbmanager on my SwiftUI:
`@StateObject private var databaseManager = DataBaseManager(fileName: "QS-EN")`

and then to read all fetches:
```
let dabArray = databaseManager.fetchData()
print(dabArray.description)

```
I would really appreciate if you may correct my code base on the table image

**Comment by groue** [comment]
Your sample code is opening a database in the documents directory. That's what it does, that's what you'll see if you read and understand it. The documents directory is empty when your application installs on a device. It does not contain your database file.

So your app is open an empty database. And it does not contain the DCIM table.

This explains the `no such table: DICM` error.

Since you want to open an existing database file, that is present somewhere on your hard drive, you need to add this file as a resource in your Xcode project.

The [Xcode documentation](https://developer.apple.com/documentation/xcode) does not describe how to add files as a resource 😖 

OK, don't miss a single step:

- Make sure the database file is somewhere next your Xcode project, not at some random place in your hard drive.
- Open your Xcode project.
- In the left sidebar of the project window, select the Files tab (with a 📁 icon).
- Drag the file from the Finder in this pane in order to embed it inside your project.
- Once dragged, select the file in the left sidebar, and open the right sidebar of the project window.
- In the right sidebar, select the File tab (with a file icon).
- Look the "Target Membership" section: check your application target if it is not yet.

Don't miss any of those steps. If you have difficulties, please ask on StackOverflow.

Once your database file is a resource of your project, update your code so that it opens this database resource. For example:

```swift
var config = Configuration()
config.readonly = true
let dbPath = Bundle.main.path(forResource: "QS-EN", ofType: "sqlite")!
let dbQueue = try DatabaseQueue(path: dbPath, configuration: config)
```

Of course, modify this sample code if your database resource is not exactly named `QS-EN.sqlite`.

**Comment by Momeks** [comment]
Thank you so much, I changed the init() code to this:

```
init() {
		  var config = Configuration()
		  config.readonly = true
		  let dbPath = Bundle.main.path(forResource: "eng-per", ofType: "sqlite")!
		  do {
			  self.dbQueue = try DatabaseQueue(path: dbPath, configuration: config)
		  } catch let error {
			  print(error.localizedDescription)
		  }
	  }

```

and it working fine. Thank you so much

**Comment by groue** [comment]
Glad your issue is solved :) Happy GRDB!
