### ISSUE TITLE
Subquery without using raw sql

### ISSUE THREAD

**Issue by ethankay** [groue/GRDB.swift#1341]
Is it possible in GRDB to write a query that contains a subquery of the form `SELECT ... FROM (SELECT ... FROM ...)`, but for the most part avoiding raw SQL? 

Example:

Suppose one is storing asset values in a DB, and wants to get back the summed values of all their assets bucketed by day/ week/ month/ quarter/ year, etc.

For example given this data:

```
// Symbol, date,  value
// AAPL,   day 1, 20
// GOOG,   day 1, 22
// MSFT,   day 1, 21
// MSFT,   day 2, 23
// GOOG,   day 2, 27
// AAPL,   day 3, 19
// MSFT,   day 3, 19
```

This is what we'd like to get bucketed in two day increments:

```
// days 1-2: 66.5 (corresponding to APPL: (20) / 1 + GOOG: (22 + 27) / 2 + MSFT: (21 + 23) / 2)
// days 2-4: 38.0 (corresponding to AAPL: (19) / 1 + MSFT: (19) / 1)
```

Here's a rough GRDB data model for this:

```swift
struct AssetValue: PersistableRecord, Codable {
  var id: String
  var symbol: String
  var date: Date
  var value: Double
  
  enum Columns {
    static let id = Column(CodingKeys.id)
    static let symbol = Column(CodingKeys.symbol)
    static let date = Column(CodingKeys.symbol)
    static let value = Column(CodingKeys.symbol)
  }
}

struct AllAssetsValue: FetchableRecord, Decodable {
  var date: Date
  var value: Double
}
```

And here's how we might get this using raw sql (leaving the datestr customizable to pick the bucket range):

```swift
try appDb.dbReader.read { db in
  try AllAssetsValue.fetchAll(db, sql: """
    SELECT
      gav.date,
      SUM(gav.value) AS value,
    FROM (
      SELECT
        strftime(:datestr, av.date) as dateInterval,
        SUM(av.value) / CAST(COUNT(1) AS DECIMAL) AS value,
        av.date AS date
      FROM assetValue av
      GROUP BY dateInterval, av.assetId
      ORDER BY av.date DESC
    ) AS gav
    GROUP BY gav.dateInterval
    ORDER BY gav.date ASC
    """, arguments: ["datestr": "%d"])
}
```

Is it possible to rewrite the above without using raw SQL? I can easily write the inner request, and the non-subquery parts of the outer request, but have no idea how to connect the two. I've seen that subqueries *are* supported in WHERE clauses in GRDB, but there's no mention that I could find in the documentation of using a subquery in the FROM clause.

```swift
try appDb.dbReader.read { db in
  let alias = TableAlias()
  let innerRequest = AssetValue
    .select(
      SQL(stringLiteral: "strftime('%d', date)").forKey("dateInterval"),
      (sum(AssetValue.Columns.value) / count(AssetValue.Columns.id)).forKey("value"),
      AssetValue.Columns.date
    )
    .group(Column("dateInterval"), AssetValue.Columns.assetId)
    .order(AssetValue.Columns.date.desc)
    .aliased(alias)
  let outerRequest =
    <magic alias to innerRequest that makes it a subquery>
      .select(sum(alias[Column("value")]), alias[Column("date")])
      .group(alias[Column("dateInterval")])
      .order(alias[Column("date")])
      .asRequest(of: AllAssetsValue.self)
  return outerRequest.fetchAll(db)
}
```

**Comment by groue** [comment]
Hello @ethankay,

`SELECT ... FROM (SELECT ... FROM ...)` is not currently supported by the query builder.

You may use a [Common Table Expression](https://github.com/groue/GRDB.swift/blob/master/Documentation/CommonTableExpressions.md) for the same effect, and generate: `WITH temp AS (SELECT ... FROM) SELECT ... FROM temp`.

Maybe make a step back and reconsider the raw SQL option. Complex SQL queries are frequently easier to read and maintain than a complex query interface request. There is such thing as too much GRBD query builder! 😉

**Comment by ethankay** [comment]
Thanks @groue. The CommonTableExpression is handy to know about as an option as well. I'll stick with the raw SQL as suggested. Hopefully this issue is at least helpful for others' reference!

**Comment by groue** [comment]
Yes, thanks for asking it, because this is a use case that I did not foresee, and it is not explored anywhere in the documentation ;-)
