### ISSUE TITLE
How to fix undefined behavior error in SwiftUI

### ISSUE THREAD

**Issue by Momeks** [groue/GRDB.swift#1342]
Hello, 

I am adding a search function that filtered the database according to the searched term. But I am getting weird behavior, Xcode gives me a lot of warnings with this message:

`Publishing changes from within view updates is not allowed, this will cause undefined behavior.`

That comes from this class:
```
class SearchViewModel: ObservableObject {
	
	@Published var searchResults: [Database] = []
	@Published var selectedWord: Database?
	private let dataBaseManager = DatabaseManager()
	
	init() {}
	
	func searchWord(by word: String) -> [Database] {
		do {
			try dataBaseManager.dbQueue.read { db in
				searchResults = try Database.filter(Database.Columns.word.like("%\(word)%"))
					.order(Database.Columns.word)
					.limit(30)
					.fetchAll(db)
			}
		} catch {
			print("Error fetching data: \(error)")
		}
		return searchResults
	}
}
```

the error generates from this line:
`searchResults = try Database.filter(Database.Columns.word.like("%\(word)%"))`

On my SwiftUI file, I am implementing the search function like this:
```
	@State private var searchText = ""
	@StateObject var viewModel = SearchViewModel()
	private var filteredDatabase: [Database] {
		if searchText.isEmpty {
			return []
		} else {
			return viewModel.searchWord(by: searchText)
		}
	}

TextField("Search", text: $searchText)
.font(.system(size: 32, weight: .bold, design: .serif))
.submitLabel(.search)
.
.
.
.

   List {
        ForEach(filteredDatabase, id: \.word) {
           SearchRow(database: $0)
			    		}
				}
```

any help would be appreciated

**Comment by groue** [comment]
Hello @Momeks,

You will get the same warning if you stop using GRDB and replace:

```swift
func searchWord(by word: String) -> [Database] {
    searchResults = []
    return searchResults
}
```

This means that your question is not about GRDB. It is about SwiftUI.

I recommend you look learn about [the way SwiftUI lets your app feed the user interface with data](https://developer.apple.com/documentation/swiftui/model-data).

If you still look for external support about SwiftUI after reading the documentation, ask your question on:
- [StackOverflow](http://stackoverflow.com)
- [Apple Developer Forums](https://developer.apple.com/forums/)
