### ISSUE TITLE
`Database` method `func releaseMemory()` not marked `public`

### ISSUE THREAD

**Issue by postmechanical** [groue/GRDB.swift#1345]
### What did you do?

[Documentation on memory management](https://github.com/groue/GRDB.swift#memory-management) indicates that `releaseMemory()` can be called on a `Database` instance, but the method is not marked `public`.

### What did you expect to happen?

Expected to be able to call `releaseMemory()` on any `Database` instance.

### What happened instead?

Cannot call call `releaseMemory()` on any `Database` instance because method has `internal` protection level.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @postmechanical,

The `Database.releaseMemory` method is public since version 5.26.0: upgrade your copy of GRDB!

**Comment by postmechanical** [comment]
@groue Oops 🤦‍♂️ , will do. Thanks.
