### ISSUE TITLE
I need to read about one million rows of data when app launched, need help.

### ISSUE THREAD

**Issue by ajunjunandtmac** [groue/GRDB.swift#1353]
I need to read about one million rows of data when app launched
When i use the code below, the read action takes very long time.
```
    func fetchTripPoints(userId: String, tripId: String) -> Observable<[TripPoint]> {
        return localDB.dbReader.rx.read { db in
            try TripPoint.fetchAll(db, sql: "SELECT * FROM \(self.tableName) WHERE userId='\(userId)' AND tripUid='\(tripId)'")
        }.asObservable()
    }
```
Is there any way to increase the speed for reading?
thanks very much for you help!

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** GRDB.swift (5.26.0)
**Installation method:** CocoaPods
**Xcode version:**14.1
**Swift version:** swift 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.6

**Comment by groue** [comment]
Hello @ajunjunandtmac,

Yes: provide an explicit implementation of `init(row:)`, and make sure you access columns my numerical index, because accessing columns by name is much slower.

For an example, see the "plain struct optimized for fetching performance" at https://github.com/groue/GRDB.swift/blob/master/README.md#examples-of-record-definitions

**Comment by ajunjunandtmac** [comment]
> Hello @ajunjunandtmac,
> 
> Yes: provide an explicit implementation of `init(row:)`, and make sure you access columns my numerical index, because accessing columns by name is much slower.
> 
> For an example, see the "plain struct optimized for fetching performance" at https://github.com/groue/GRDB.swift/blob/master/README.md#examples-of-record-definitions

Thanks very much for replying me in such a short time. Let me check your solution, thanks again.

**Comment by groue** [comment]
Also, profile your app with Instruments, in order to see how much time is spent in SQLite, how much in GRDB, and how much in your app.

**Comment by ajunjunandtmac** [comment]
```
    func fetchTripPoints(userId: String, tripId: String) -> Observable<[KSTripPoint]> {
        let observable: Observable<[KSTripPoint]> = localDB.dbReader.rx.read { db in
            try KSTripPoint.fetchAll(db)
        }.asObservable()
        
        return observable.map { tripPoints -> [KSTripPoint] in
            return tripPoints.filter{$0.userId == userId && $0.tripUid == tripId }
        }
    }
```
I read the note but i have 32 columns in my table, i don't want to write much more code.

**Comment by ajunjunandtmac** [comment]
```
 func fetchTripPoints(userId: String, tripId: String) -> Observable<[TripPoint]> {
        let observable: Observable<[KSTripPoint]> = localDB.dbReader.rx.read { db in
            try TripPoint.fetchAll(db)
        }.asObservable()
        
        return observable.map { tripPoints -> [TripPoint] in
            return tripPoints.filter{$0.userId == userId && $0.tripUid == tripId }
        }
    }
```
I read the note but i have 32 columns in my table, i don't want to write much more code. 
So i wonder if i use fetchAll function and filter the records then, will this help to make the query more quickly?
In fact, there is basically no need to add filter conditions for each query, just because there is some dirty data that is accidentally left in the database

**Comment by groue** [comment]
> I read the note but i have 32 columns in my table, i don't want to write much more code.

If you don't write code, then you're using convenience apis. Those convenience apis access columns by name, and those accesses by name take a performance toll which is quite visible when you fetch many rows.

If you're focusing on performance, the convenience apis are no longer a good fit. That's how it is. It's up to you to decide what you really want. You asked a question, I gave the answer.

Revisiting my initial advice, maybe the "plain struct optimized for fetching performance" sample code won't quite match your needs, because it introduces a risk of column-ordering mismatch between the record type and the raw SQL which is `SELECT * ...`.

Maybe you should just go this way - you can't get faster with GRDB:

```swift
return localDB.dbReader.rx.read { db -> [TripPoint] in
    let sql = "SELECT * FROM \(self.tableName) WHERE userId=? AND tripUid=?"

    // A lazy and memory-efficient cursor of rows,
    // with fast access to low-level SQLite 
    let rowCursor = try Row.fetchCursor(db, sql: sql, arguments: [userId, tripId])

    // A lazy and memory-efficient cursor of TripPoint,
    // with fast access to low-level SQLite 
    let tripPointCursor = rowCursor.map { row in
        // Just a call to the regular TripPoint initializer
        TripPoint(
            foo: row[0], // Don't use strings!!!
            bar: row[1],
            baz: row[2],
            ...)
    
    // Convert the cursor into an array
    return try Array(tripPointCursor)
}.asObservable()
```

Note how the code above avoids SQL injection by using statement arguments (you should never never never embed raw values in you SQL strings).

> So i wonder if i use fetchAll function and filter the records then, will this help to make the query more quickly?

Test and compare.

**Comment by ajunjunandtmac** [comment]
Ok, thanks, i will try the two ways you suggested and reply the result soon. thanks again.

**Comment by groue** [comment]
When you say "one million of rows", do you mean that you fetch one million of `TripPoint` values in memory, or that you fetch only a few `TripPoint` from a big big big table?

I initially assumed that you were fetching a lot of `TripPoint` values. The sample code above addresses this need.

But if you only want a few `TripPoint` from a big table, then the reason why your database access is slow is not the decoding of many rows. It is that SQLite has difficulties finding the rows you want. For this, you need to add an index to your table.

**Comment by ajunjunandtmac** [comment]
> When you say "one million of rows", do you mean that you fetch one million of `TripPoint` values in memory, or that you fetch only a few `TripPoint` from a big big big table?
> 
> I initially assumed that you were fetching a lot of `TripPoint` values. The sample code above addresses this need.
> 
> But if you only want a few `TripPoint` from a big table, then the reason why your database access is slow is not the decoding of many rows. It is that SQLite has difficulties finding the rows you want. For this, you probably need to add an index to your table. The convenience api `fetchAll` will then just work fine, since you do not have to decode a lot of trip points.

fetch one million of TripPoint values in memory when app launched, but this is just an extreme case, the probability is very low.

**Comment by ajunjunandtmac** [comment]
> plain struct optimized for fetching performance

OK, got it.

**Comment by groue** [comment]
> > plain struct optimized for fetching performance
> 
> OK, got it.

Don't miss [this comment](https://github.com/groue/GRDB.swift/issues/1353#issuecomment-1480711307).

**Comment by ajunjunandtmac** [comment]
Sorry to trouble you again

**Comment by ajunjunandtmac** [comment]
Sorry to trouble you again
Please check the attached code when you have time, i don't know which way is correct.
Thanks a lot!!!! 
[demo.zip](https://github.com/groue/GRDB.swift/files/11049519/demo.zip)

**Comment by groue** [comment]
> i don't know which way is correct.

Me neither. The correct way is the one that makes your app run:

1. correctly (aim at correctness _first_)
2. at an acceptable performance (optimize only when needed/significant)
3. while remaining understandable by you and your coworkers (don't forget the readability and maintainability)

Only you can check that.

Oh, one last piece of advice. I wrote:

> Maybe you should just go this way - you can't get faster with GRDB:
>
> ...
>
> ```swift
> return try Array(tripPointCursor)
> ```

Maybe you can go even faster if you know in advance the number of rows:

```swift
let countSQL = "SELECT COUNT(*) FROM \(self.tableName) WHERE userId=? AND tripUid=?"
let count = try Int.fetchOne(db, sql: countSQL, arguments: [userId, tripId])!
return try Array(tripPointCursor, minimumCapacity: count)
//                                ~~~~~~~~~~~~~~~~~~~~~~
```

Again, only profiling with Instruments on a real big database can tell. In the variant above, we instruct Swift to allocate an array that is big enough, and the performance gains can compensate the extra query that fetches the number of trip points.

**Comment by ajunjunandtmac** [comment]
> Revisiting my initial advice, maybe the "plain struct optimized for fetching performance" sample code won't quite match your needs, because it introduces a risk of column-ordering mismatch between the record type and the raw SQL which is `SELECT * ...`.

I mean if i use way 1 code resource according to "plain struct optimized for fetching performance", you said it introduces a risk, is it a runtime risk or just a risk generate by the coder when write the code at compiler time. I hate crash so i care about this risk.

**Comment by ajunjunandtmac** [comment]
> > I mean if i use way 1 code resource according to "plain struct optimized for fetching performance", you said it introduces a risk, is it a runtime risk or just a risk generate by the coder when write the code at compiler time. I hate crash so i care about this risk.
> 
> In the "plain struct optimized for fetching performance" sample code of the README,
> 
> * the record decides the ordering of columns (with its `databaseSelection` static property)
> * the record decodes the columns at the expected numerical position (in `init(row:)`).
> 
> You surely understand that it is important that both orders are identical.
> 
> The order decided by `databaseSelection` only applies to SQL requests that are _generated_ by the record type, but not for requests written by hand:
> 
> ```swift
> // 1. Order of columns is controlled by databaseSelection
> try TripPoint.fetchAll(db)
> 
> // 2. Order of columns is controlled by SQLite (the database schema)
> try TripPoint.fetchAll(db, sql: "SELECT * ...")
> ```
> 
> In the first case, the generated SQL, and `init(row:)` agree on the ordering of columns: `TripPoint` is responsible of both, and **can do the right thing** without interference from other parts of your application. There is no risk if `TripPoint.init(row:)` takes care of choosing the correct numerical indexes that match the static `databaseSelection` property.
> 
> In the second case, I'm not sure the SQL and `init(row:)` agree on the ordering of columns. `TripPoint` is NOT responsible of both, so things might turn wrong.
> 
> That's the risk I mention.
> 
> In my [sample code](https://github.com/groue/GRDB.swift/issues/1353#issuecomment-1480711307) above, the ordering of fetched columns and the matching numerical indexes are located in a single function, which **can do the right thing** without interference from other parts of your application. There is no risk if you take care of choosing the correct numerical indexes. You will only have to update this code if the database schema changes.

really thanks for your kindly reply.

**Comment by ajunjunandtmac** [comment]
Really amazing
When My KSTripPoint Class implement "the plain struct optimized for fetching performance"
The query time is only 3 second
If not, the query time is 27 seconds
I just use fetchAll function without any sql text to query
```
    func fetchTripPoints(userId: String, tripId: String) -> Observable<[KSTripPoint]> {
        let observable: Observable<[KSTripPoint]> = localDB.dbReader.rx.read { db in
            try KSTripPoint.fetchAll(db)
        }.asObservable()

        return observable.map { tripPoints -> [KSTripPoint] in
            return tripPoints.filter{$0.userId == userId && $0.tripUid == tripId }
        }
    }
```

**Comment by groue** [comment]
I'm glad you're happy :-)

I don't know how many trip points you discard with `tripPoints.filter { ... }`. It it is a lot, maybe try letting SQLite do the filtering. It may well perform better, especially if the database table has an index:

```swift
func fetchTripPoints(userId: String, tripId: String) -> Observable<[KSTripPoint]> {
    return localDB.dbReader.rx.read { db in
        try KSTripPoint
            .filter(Column("userId") == userId && Column("tripUid") == tripId)
            .fetchAll(db)
    }.asObservable()
}
```
