### ISSUE TITLE
Is there has anyway to set more than one table name to a model?

### ISSUE THREAD

**Issue by coder-free** [groue/GRDB.swift#1354]
```
struct Player: TableRecord {
    static var databaseTableName = "player"
}
```

This is a static property. This means that a model corresponds to only one table.

In my case, same structured data need save more than one set.

I know something similar can be achieved through foreign keys. But I still think it is more convenient to use tables with different names directly.

**Comment by groue** [comment]
Hello @coder-free,

> This is a static property. This means that a model corresponds to only one table.

Yes. Relational databases that adhere to standard schema design contain a limited set of tables. Those tables can be represented by a limited set of Swift record types.

> In my case, same structured data need save more than one set. I know something similar can be achieved through foreign keys. But I still think it is more convenient to use tables with different names directly.

I understand that several tables share a set of common columns, with some variations. You wish you could reuse some code between the record types that represent those tables.

Well, that's not something which has any built-in helper in GRDB 😬. I wish it were possible to ship something akin to [`@Embedded`](https://developer.android.com/reference/android/arch/persistence/room/Embedded) (in Kotlin, from Jetpack Room), but unfortunately the standard `Codable` and `Decodable` protocols don't make it possible 🤷‍♂️.

I suggest you make some experiments, and choose the less worse of possible alternatives. Don't let the Swift or GRDB limitations or inconveniences worsen your database schema.

**Comment by groue** [comment]
cc @itaiferber, because I don't think I had the opportunity yet to tell you how much it would be handy if [@Embedded](https://developer.android.com/reference/kotlin/androidx/room/Embedded) could be implemented on top of `Codable`.

**Comment by groue** [comment]
Could the new support for Swift macros help?

```swift
struct Coordinates {
  var latitude: Double
  var longitude: Double
}

struct Address {
    var street: String
    
    // User writes:
    @Embedded var coordinates: Coordinates
    
    // Macro generates:
    private var latitude: Double
    private var longitude: Double
    var coordinates: Coordinates {
        get {
            Coordinates(latitude: latitude, longitude: longitude)
        }
        set {
            latitude = newValue.latitude
            longitude = newValue. longitude
        }
    }
}
```

This is close to what we need. But:

1. I'm not sure if macros can iterate the contents of an external type.
2. This looks very brittle, because the macro has to assume that a memberwise initializer exists, with an order of arguments that matches the order of discovered properties.
3. This looks very brittle, because this does not support types that use a private coding representation.

    ```swift
    // This type can not be embedded with @Embedded
    struct Amount {
        // The encoded property is private
        private var cents: Int

        // Public property is not encoded.
        var value: Decimal { ... }
    }
    ```

It really looks only custom Codable implementations can help (see sample code below). But even a custom Codable implementation can not deal with **multiple** embedded properties of the same type! We'd need key prefixes, this kind of feature.

<details><summary>Custom Codable implementation</summary>

```swift
import Foundation

struct Amount: Codable {
    private var cents: Int
    var currency: String
    
    var value: Decimal {
        get { Decimal(cents) / 100 }
        set { Self.cents(for: newValue) }
    }
    
    init(value: Decimal, currency: String) {
        self.cents = Self.cents(for: value)
        self.currency = currency
    }
    
    static func cents(for value: Decimal) -> Int {
        Int(Double(truncating: (value * 100) as NSNumber))
    }
}

// {"cents":100,"currency":"EUR"}
let amount = Amount(value: 1, currency: "EUR")
try print(String(data: JSONEncoder().encode(amount), encoding: .utf8)!)


struct Product {
    /* @Embedded */ var price: Amount
    var name: String
}

extension Product: Codable {
    private enum CodingKeys: String, CodingKey {
        // No key for embedded price
        case name
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decode(String.self, forKey: .name)
        self.price = try Amount(from: decoder)
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try price.encode(to: encoder)
    }
}

// {"name":"Apple","cents":100,"currency":"EUR"}
let product = Product(price: Amount(value: 1, currency: "EUR"), name: "Apple")
try print(String(data: JSONEncoder().encode(product), encoding: .utf8)!)
```

</details>

**Comment by groue** [comment]
@DougGregor, if you have five or ten minutes, may I ask you to tell what you think about this topic, and the eventual opportunity to work on an `@Embedded` macro - if you think macros could help?

**Comment by coder-free** [comment]
Thank you very much. I was surprised that you replied with so much content. 
To be honest, I have not tried your solutions because they look complicated. Unfortunately, I am quite lazy. If there is a simple way to do something, I will definitely not try a more complex one unless the simple method has hidden risks. Back to our question, I was wondering if it is possible to allow "table names" to be passed in during `dbQueue.write`. The specific implementation may be something like this:
```swift
try dbQueue.write { db in
    try Player(id: 1, name: "Arthur", score: 100).insert(db, tableName)
    try Player(id: 2, name: "Barbara", score: 1000).insert(db, tableName2)
}
```
Or like this:
```swift
try dbQueue.write { db in
    Player.do(tableName) {
        try Player(id: 1, name: "Arthur", score: 100).insert(db)
        try Player(id: 2, name: "Barbara", score: 1000).insert(db)
    }
}
```
`tableName` parameter will override the `Player.databaseTableName ` static property.
This may be a lot of work.😂

To be honest, this implementation might give the feeling of something strange with GRDB in some respects. It may have a sense of imitation product. However, from my perspective as a user, at least it is much more convenient. Whether or not to do it this way, you can consider it. As for the issue with my requirement that I mentioned earlier, in fact, after I opened this issue, I had already completed it using foreign keys. Because I feel that there is no easy way to achieve my needs, unless the table name is directly passed in during operation.

Thanks again for your reply.

**Comment by groue** [comment]
> Thank you very much. I was surprised that you replied with so much content. To be honest, I have not tried your solutions because they look complicated.

Oh, yeah, I'm sorry. It's just that you're not the first user who asks such a question. Being able to fulfill your needs and similar ones involves a little complicated thinking - so that everything remains simple at your level. You have been a witness of this thinking, but you can ignore it of course.

> Back to our question, I was wondering if it is possible to allow "table names" to be passed in during `dbQueue.write`.

I initially wrote:

> I understand that several tables share a set of common columns, with some variations. You wish you could reuse some code between the record types that represent those tables.

But you didn't tell if this was a correct interpretation. Now I understand that your tables are all completely identical, without any variation.

Did you try defining a common super-class, and have one subclass per table that overrides the table name?

**Comment by coder-free** [comment]
> Well, did you try defining a common super-class, and have one subclass per table that overrides the table name?

It's a good idea. It seems that my imagination is not rich enough. 一叶障目😂
