### ISSUE TITLE
Selecting from multiple CTEs using query syntax

### ISSUE THREAD

**Issue by ethankay** [groue/GRDB.swift#1355]
Suppose I have multiple somewhat complex CommonTableExpressions (CTEs). Can the GRDB query builder express a SELECT that pulls from columns across the multiple CTEs? 

For example, if I wanted to translate the following raw SQL:

```sql
WITH 
  "cte1" AS (SELECT <something complex>),
  "cte2" AS (SELECT <something else complex>)
SELECT <some_column_from_cte1>, <some_column_from_cte2>
FROM "cte1", "cte2"
WHERE "cte1"."id" = "cte2"."id"
```
I would normally think to do something like:

```swift
var select1 = try MyTableStruct.select(<something complex, in query syntax>)
var select2 = try MyTableStruct.select(<something else complex, in query syntax>)
let cte1 = CommonTableExpression(named: "cte1", request: select1)
let cte2 = CommonTableExpression(named: "cte2", request: select2)
let query = GRDB.Table<MyResultStruct>("cte1, cte2")
  .with(cte1)
  .with(cte2)
  .select(
    Column(<some_column_from_cte1>),
    Column(<some_column_from_cte2>)
  )
```

However `GRDB.Table<MyResultStruct>("cte1, cte2")` does not work as it (probably correctly) interprets the string as a single table name (e.g. `FROM "cte1, cte2"` instead of `FROM "cte1", "cte2"`). Is there a different way to write this using query syntax to get around this? Obviously I can fall back to raw sql, and I realize that can sometimes be preferable, but in this case I'm hoping to avoid it as everything else for this query is much easier to reason about in the query syntax.

The above is obviously generic, but to ground this a bit with an extremely simple example, we might assume I have the following table:

| ID | Date  | Value |
| -- | ----- | ----- |
| 1  | 11/20 | 5     |
| 2  | 11/20 | 4     |
| 3  | 11/20 | 7     |
| 1  | 11/21 | 2     |
| 2  | 11/21 | 1     |
| 3  | 11/21 | 7     |
| 1  | 11/22 | 8     |
| 2  | 11/22 | 2     |
| 3  | 11/22 | 3     |
| 1  | 11/23 | 4     |
| 2  | 11/23 | 3     |
| 3  | 11/23 | 4     |

And assume that one cte gets the value from the "Value" column associated with the min date for a given ID, and the other cte gets the value from the "Value" column associated with the max date for a given ID. The final select then pulls together into one final result the start date and value, and end date and value for each ID.

**Comment by groue** [comment]
Hello @ethankay,

> However `GRDB.Table<MyResultStruct>("cte1, cte2")` does not work as it (probably correctly) interprets the string as a single table name (e.g. `FROM "cte1, cte2"` instead of `FROM "cte1", "cte2"`).

Yes. the Swift query interface does not currently allow to provide multiple tables in the `FROM` clause. It's really just not expressible at the present time 😬

> Is there a different way to write this using query syntax to get around this?

Yes. Instead of writing `FROM cte1, cte2 WHERE cte1.id = cte2.id`, we can write `FROM cte1 JOIN cte2 ON cte1.id = cte2.id`.

```swift
try DatabaseQueue().write { db in
    // Log SQL
    db.trace { print($0) }
    
    // CTE definitions
    let cte1 = CommonTableExpression(named: "cte1", sql: """
        SELECT 1 AS id, '11/20' AS date
        UNION ALL
        SELECT 2,       '11/21'
        UNION ALL
        SELECT 3,       '11/23'
        """)
    let cte2 = CommonTableExpression(named: "cte2", sql: """
        SELECT 2 AS id, 100 AS value
        UNION ALL
        SELECT 3,       1000
        UNION ALL
        SELECT 4,       10
        """)
    
    // WITH "cte1" AS (SELECT ...),
    //      "cte2" AS (SELECT ...)
    // SELECT "cte1"."id", "cte1"."date", "cte2"."value"
    // FROM "cte1"
    // JOIN "cte2" ON "cte1"."id" = "cte2"."id"
    let cte2Alias = TableAlias()
    let request = Table(cte1.tableName) // Define the FROM clause
        .with(cte1)                     // Define the CTEs
        .with(cte2)
        .select(                        // Define the SELECT clause 
            Column("id"),               // Columns come from cte1 by default.
            Column("date"),             
            cte2Alias["value"])         // Use an alias to address cte2 columns.
        .joining(required: cte1.        // Add a JOIN clause
            .association(to: cte2, on: { $0["id"] == $1["id"] }) // cte2 ON ...
            .aliased(cte2Alias)).       // The alias used in the selection above
    
    // [id:2 date:"11/21" value:100]
    // [id:3 date:"11/23" value:1000]
    for row in try request.fetchAll(db) {
        print(row)
    }
}
```

> Obviously I can fall back to raw sql, and I realize that can sometimes be preferable, but in this case I'm hoping to avoid it as everything else for this query is much easier to reason about in the query syntax.

I'm sure you will pick the solution you prefer :-)

**Comment by ethankay** [comment]
Makes sense! Thanks @groue! 

A small follow up regarding associations where the included regard uses a max or sum (follow up as it's also about maxs and mins and the only method, albeit not pretty, that I've found to sort of solve this is a CTE).

Assuming we're talking about Authors and Books here if I wanted to write a query that returned the highest rated book for each author I'd write something like the following (not sure what the correct AllColumns syntax is, but the `max` is the more relevant part).

```swift
Author
  .including(
    required: Author.books.select(
      Book.AllColumns(), 
      max(Book.Columns.rating).forKey("maxRating")
    )
  )
  .order(sql: "maxRating DESC")
```

The problem is that *if there are no authors and no books in the database*, this returns a single empty row with all values set to NULL (because of the `max`), which of course fails when using a Codable record. How do I filter that out? I can do CTE and then filter on `maxRating IS NOT NULL` but that sort of defeats the purpose of these nice association interfaces I think?

**Comment by groue** [comment]
> The problem is that _if there are no authors and no books in the database_, this returns a single empty row with all values set to NULL (because of the `max`), which of course fails when using a Codable record. How do I filter that out? I can [...] filter on `maxRating IS NOT NULL` but that sort of defeats the purpose of these nice association interfaces I think?

Let's forget about CTEs a little bit, and just focus on a request of authors fetched along with the max rating of their books:

```swift
try DatabaseQueue().write { db in
  // Log SQL statements
  db.trace { print($0) }
  
  try db.create(table: "author") { t in
    t.primaryKey("id", .integer)
    t.column("name", .text)
  }
  try db.create(table: "book") { t in
    t.primaryKey("id", .integer)
    t.column("authorId", .integer).references("author")
    t.column("rating", .integer)
  }
  
  struct Author: TableRecord {
    static let books = hasMany(Book.self)
  }
  struct Book: TableRecord { }
  
  do {
    // SELECT "author".*, MAX("book"."rating")
    // FROM "author"
    // JOIN "book" ON "book"."authorId" = "author"."id"
    let request = Author.including(required: Author.books.select(max(Column("rating"))))
    
    // [id:NULL name:NULL]
    for row in try Row.fetchAll(db, request) {
      print(row)
    }
  }
  
  do {
    // Add a group clause:
    // SELECT "author".*, MAX("book"."rating")
    // FROM "author"
    // JOIN "book" ON "book"."authorId" = "author"."id"
    // GROUP BY "author"."id"
    let request = Author.including(required: Author.books.select(max(Column("rating")))).groupByPrimaryKey()
    
    // No row
    for row in try Row.fetchAll(db, request) {
      print(row)
    }
  }
}
```

The first example returns a NULL row :-/

The second one does not, just by adding a GROUP BY clause.

I'd torned. Is it a GRDB issue, or an SQLite gotcha? What do you think?

**Comment by groue** [comment]
> I'd torned. Is it a GRDB issue, or an SQLite gotcha? What do you think?

Grmbl. I'm keen to choose the SQLite gotcha, since I'm not quite sure which logic GRDB could implement as a workaround. Something like "add a default GROUP BY clause as soon as the request involves an aggregate function somewhere"?

It happens that we already have [some logic for detecting the presence of aggregate functions](https://github.com/groue/GRDB.swift/blob/a1b76f9e06fb5aa20851317639440b7411fff49d/GRDB/QueryInterface/SQL/SQLExpression.swift#L1651), but it's not a strict test.

For example, `SQL("max(book.rating)").sqlExpression` wouldn't be detected as an aggregate. Raw SQL expressions like this look rare (they *are* rare :wink:), but they are the only escape hatch for users who need to add support for SQL constructs that have no Swift equivalent. GRDB would not be able to add a default group clause in such cases, and would exhibit an inconsistent behavior.

All in all, we're probably at a good-enough resting point. And this issue documents one more fascinating SQLite gotcha :-)

**Comment by groue** [comment]
> SQLite gotcha

Or rather, our slow understanding ;-) After all, `SELECT max(rating) FROM book` fetches one row containing a NULL value when the table is empty.

I'm closing the issue. Thanks for your questions!
