### ISSUE TITLE
Development data may be lost after `PRAGMA optimize`

### ISSUE THREAD

**Issue by baoshan** [groue/GRDB.swift#1360]
### What did you do?

> it is recommended that applications run "PRAGMA optimize" (with no arguments) just before closing each database connection. [<sup>1</sup>](https://sqlite.org/pragma.html#pragma_optimize)

I execute `PRAGMA optimize` on `willTerminateNotification`. It is the best place I can think of.

### What happened instead?

On the next launch, there is an extra SchemaObject named `sqlite_stat1` which erases the database due to `eraseDatabaseOnSchemaChange = true`, leading to (development) data loss.

I’m not sure if I should wrap the `PRAGMA optimize` using `#if DEBUG (else)` because I think compiler directives should be used minimally.

Is this by intention?

Thanks!

**Comment by baoshan** [comment]
Thanks, Gwendal! I’m closing the issue for now and continue enjoying my explorations on GRDB.

**Comment by groue** [comment]
#1361 was just shipped in v6.11.0
