### ISSUE TITLE
Issue with Swift 3

### ISSUE THREAD

**Issue by dbaroncelli** [groue/GRDB.swift#137]
I added GRDB as a pod in Xcode8

I was asked to make the conversion to Swift 3, then I get lots of errors

<img width="272" alt="schermata 2016-10-07 alle 02 44 01" src="https://cloud.githubusercontent.com/assets/5320104/19175630/bf1612ca-8c38-11e6-9e97-8797918fb7b1.png">

**Comment by swiftlyfalling** [comment]
Are you using the Swift3 version of GRDB? Currently this is **0.85.0**.

If you are using 0.80.x or 0.81.x, you have the Swift 2.2/2.3 version (respectively) and you need to switch to version 0.85.0 or higher.

**Comment by dbaroncelli** [comment]
yes, I was using 0.85.0 with Swift 3 and then I gave up, I could not solve the errors

I then decided to convert just to Swift 2.3 and I kept using SQlite.Swift, the old sqlite library I was using before

I will wait some more months to switch to Swift 3 and to GRDB

**Comment by groue** [comment]
Whenever you decide to switch, GRDB is ready. I'm sure you'll find it refreshing. If you experience trouble again, please tell which [installation method](http://github.com/groue/GRDB.swift#installation) you are using.

**Comment by Fellows666** [comment]
Hi i am trying to use GRDB and am getting the same errors dbaroncelli got, after updating to swift 3.
I have installed with cocopods and it has podded version (0.90.1).

**Comment by groue** [comment]
@Fellows666: make sure Xcode is installed in the Applications folder, with the name "Xcode", hold the Option (alt) key and clean your build folder (Product Menu > Clean Build Folder…), quit Xcode, trash your "Derived Data" folder, reboot your Mac, repeat in random order until your build succeeds.
