### ISSUE TITLE
6.12.0 not available

### ISSUE THREAD

**Issue by TheNephilim88** [groue/GRDB.swift#1370]
Hey,

wanted to update from 6.10.2 to 6.12.0 but latest thing it finds is 6.10.2.

What am I using:
- CocoaPods
- GRDB.swift with SQLCipher

```
pod 'GRDB.swift/SQLCipher'
pod 'SQLCipher', '~> 4.0'
```

Am I doing anything wrong?

**Comment by groue** [comment]
Hello @TheNephilim88, it looks like the latest versions have not been published on CocoaPods, you're right. I'll look into this shortly. Thanks for the report!

**Comment by groue** [comment]
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  GRDB.swift (6.12.0) successfully published
 📅  May 5th, 10:12
 🌎  https://cocoapods.org/pods/GRDB.swift
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Comment by groue** [comment]
Yep, it's online now :) Happy GRDB!
