### ISSUE TITLE
How to import one database into another correctly? (Merge)

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1372]
```
class Common: Identifiable, FetchableRecord & PersistableRecord {
    var id: String
    var name: String
    var score: Int
}
```
hello everyone.  Our tables all have an Identifiable attribute. (Similar to the "Common" above)

We have a new requirement to import database A into database B. That is to use B's data to cover A's data, but retain the data that B does not have. (Data with the same ID will be overwritten by B)

Because our database has many tables, the code process is slow and inefficient. (We try to read the entity object, then determine if the A database has information with the same ID, and then decide whether to use Insert or Save, which is very inefficient)

Is there a good way to achieve this requirement? 

thank you so much.

**Comment by groue** [comment]
Hello @SF-Simon,

I'm far from any computer right now, but you should be able to let SQLite to the whole import:

Start by attaching one database to the other with the SQL command [`ATTACH`](https://www.sqlite.org/lang_attach.html). This will make it possible to deal with both databases from a single connection.

Then run as many `INSERT INTO ... SELECT ...` statements as there tables to import.

When the imports are done, `DETACH` the database.

All those steps are done with raw SQL statements:

```swift
let pathToOtherDatabase = ...
try dbQueue.write { db in
  try db.execute(literal: """
    -- Attach
    ATTACH \(pathToOtherDatabase) AS other;

    -- Import
    INSERT INTO main.player SELECT * FROM other.player WHERE NOT EXISTS (SELECT main.id FROM main.player WHERE main.player.id= other.player.id);

    -- Detach
    DETACH other;
    """)
}
```

I did not run this code so please double-check carefully. Learn bits of SQL, if needed, on the way!

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> I'm far from any computer right now, but you should be able to let SQLite do the whole import:
> 
> Start by attaching one database to the other with the SQL command [`ATTACH`](https://www.sqlite.org/lang_attach.html). This will make it possible to deal with both databases from a single connection.
> 
> Then run as many `INSERT INTO ... SELECT ...` statements as there tables to import.
> 
> When the imports are done, `DETACH` the database.
> 
> All those steps are done with raw SQL statements:
> 
> ```swift
> let pathToOtherDatabase = ...
> try dbQueue.write { db in
>   try db.execute(literal: """
>     -- Attach
>     ATTACH \(pathToOtherDatabase) AS other;
> 
>     -- Import
>     INSERT INTO main.player SELECT * FROM other.player WHERE NOT EXISTS (SELECT main.id FROM main.player WHERE main.player.id= other.player.id);
> 
>     -- Detach
>     DETACH other;
>     """)
> }
> ```
> 
> I did not run this code so please double-check carefully. Learn bits of SQL, if needed, on the way!

Hello, @groue 

Sorry, did I disturb your vacation? My mistake. 
I have asked many questions because I am not familiar with SQL and SQLIte3. Fortunately, we have you, otherwise I estimate I would have wasted a lot of time. Thank you very, very much.

I didn't know about the use of _Attach_, but after your code demonstration, I finally completed the overlay import using the _Insert OR Replace INTO_ statement. The current observation results are good.

I hope it can also help others.

Reference: [https://stackoverflow.com/a/45024193/7848308](https://stackoverflow.com/a/45024193/7848308)

thanks so much, thanks.

**Comment by groue** [comment]
Great! Happy GRDB :)
