### ISSUE TITLE
How to do bitwise operation for column value update when using TableRecord.updateAll()

### ISSUE THREAD

**Issue by maxxfire** [groue/GRDB.swift#1374]
### What did you do?

Need to update the column value by bitwise operation when using TableRecord.updateAll() API.  Like this:

`
                    try Test
                        .filter(...)
                        .updateAll(db,
                                   Column("mask") &= 0x02
                        )
`

### What did you expect to happen?

Update successfully without error.

### What happened instead?

Compile error: Cannot convert value of type '()' to expected argument type '[ColumnAssignment]'

### Environment

**GRDB flavor(s):GRDB (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version: 6.5.0
**Installation method:CocoaPods (CocoaPods, SPM, manual?)
**Xcode version: 14.0 (14A309)
**Swift version: 5.0
**Platform(s) running GRDB: iOS (iOS, macOS, watchOS?)
**macOS version running Xcode: 12.6
 
Thanks.

**Comment by groue** [comment]
Hello @maxxfire,

GRDB has no support for bitwise operators yet.

Until they ship in a future version, you can add support for them by copying this snippet in your application:

```swift
extension SQLSpecificExpressible {
    static func & (lhs: Self, rhs: some SQLExpressible) -> SQLExpression {
        SQL("\(lhs) & \(rhs)").sqlExpression
    }
}

extension ColumnExpression {
    static func &= (column: Self, value: some SQLExpressible) -> ColumnAssignment {
        column.set(to: column & value)
    }
}
```

Usage:

```swift
try Test.filter(...).updateAll(db, Column("mask") &= 0x02)
```

**Comment by maxxfire** [comment]
It works, pretty cool, thanks.  @groue

**Comment by groue** [comment]
Good! I'm closing the issue then.

**Comment by groue** [comment]
@maxxfire, GRDB v6.14.0 has shipped with built-in support for the bitwise operators (`&`, `|`, `~`, `<<`, `>>`, and `&=`, `|=`, `<<=`, `>>=`). You'll be able to remove the above extensions from your app after you upgrade.
