### ISSUE TITLE
GRDB v0.86 & xcode 8.1 beta - 

### ISSUE THREAD

**Issue by dotpooch** [groue/GRDB.swift#138]
Hi groue, 

Thanks for distributing GRDB.

I've been trying to install the latest version with xcode 8.  I'm using xcode 8.1beta until I get everything working.

I created a brand new project using xcode and made no changes to the project except attempting to install the GRDB cocoapod.

I get several errors:
1. In xcode, I get 8 compile errors which mention errors in your code.  This doesn't make much sense to me, so I imagine I have a setting wrong somewhere.  Right now, "use legacy swift language version" is set to no.

In further review, it appears that Simulator - iOS 10.1 is not loading correctly.  Probably coming off the error "Could not build Objective-C module SQLiteiPhone Simulator Configuration".

Any thoughts or suggestions?

Thanks you!
 
![screen shot 2016-10-08 at 4 46 20 pm](https://cloud.githubusercontent.com/assets/4219526/19216148/5dd1063a-8d7f-11e6-8f33-f1017704f107.jpg)
![screen shot 2016-10-08 at 5 41 22 pm](https://cloud.githubusercontent.com/assets/4219526/19216149/5dd1a41e-8d7f-11e6-9452-ee53cdc1686d.jpg)

**Comment by groue** [comment]
Hello @dotpooch 

GRDB has currently no branch for Xcode beta.

I suggest you have your project compile with Xcode 8 first. Once done, open your project with Xcode 8.1 beta. If GRDB needs changes, they will be much easier to spot using this differential technique.

Also, I don't know which installation method you have chosen (CocoaPods, Carthage, or manual) - but consider that third-parties software may not be ready for Xcode 8.1 beta.

**Comment by dotpooch** [comment]
Thanks, that was such a simple solution!  Works great.

**Comment by groue** [comment]
Great, happy GRDB!

**Comment by vuevrn** [comment]
Hi @dotpooch , I am having a same 8 compile errors problem in xcode 8.0 after manually installing GRDB in the project, I am not into downloading a beta version for now, can you help me getting rid of these errors.

Thank you.

**Comment by vuevrn** [comment]
solved it by myself. Thanks anyway.

**Comment by asrivastav973** [comment]
Hi @vuevrn how did you solve this issue. I am facing the same issue right now.

**Comment by asrivastav973** [comment]
Solved it. It was because the Xcode app's location was not 'Applications/Xcode', it was 'Downloads/Xcode'.
