### ISSUE TITLE
Decode Request into sections grouped by a given property

### ISSUE THREAD

**Issue by dehlen** [groue/GRDB.swift#1380]
### What did you do?

I tried to request sectioned data from my database via GRDBs query interface but am not quite sure how to achieve it.
Lets assume the following schema:
```
GroceryList {
 id: Int64?
}

GroceryListItem {
  id: Int64?
  groceryListId: Int64
  aisleId: Int64
}

Aisle {
  id: Int64?
  name: String
}
```

I want to generate the following intermediate representation (a list of GroceryListItems by a given Aisle from a given GroceryList):

```
GroceryListItemSection {
  aisle: Aisle
  items: [GroceryListItem]
}
```

I think I need something like this but am not quite sure how to make it work:

`groceryList.items.group(Column("aisleId")).including(all: GroceryListItem.aisle).asRequest(of: GroceryListItemSection)`

### What did you expect to happen?

To retrieve the above defined structure out of my database via the available query interface.

### What happened instead?

I need help understanding the needed request to transform my data.

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:** (master)
**Installation method:** (SPM)
**Xcode version:** 14.3
**Swift version:** 5.7
**Platform(s) running GRDB:** (iOS)
**macOS version running Xcode:** 13.3.1

**Comment by groue** [comment]
Hello @dehlen,

It looks like your `GroceryListItemSection` looks a lot like the kind of structs fetched by [`including(all:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall) indeed.

You might end up with something akin to:

```swift
extension Aisle {
    // An aisle "has many" items because `GroceryListItem`
    // has an `aisleId` property.
    // See https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#hasmany
    //
    // We define a "has many" association with a custom key because
    // it looks like you want to refer to those items
    // with the name "items" instead of the default one,
    // which is derived from the table name (probably "groceryListItems").
    static let items = hasMany(GroceryListItem.self).forKey("items")
}

struct GroceryListItemSection: Decodable, FetchableRecord {
    var aisle: Aisle
    var items: [GroceryListItem]
}

let sections = try Aisle
    .including(all: Aisle.items)
    .asRequest(of: GroceryListItemSection.self)
    .fetchAll(db)
```

**Comment by dehlen** [comment]
Thanks I was missing the items hasMany association. It all works now. Thanks for the quick and competent help.

**Comment by groue** [comment]
You're welcome! Happy GRDB!
