### ISSUE TITLE
"statementDidExecute" not called after  calling "fetchOne" 

### ISSUE THREAD

**Issue by alexlee002** [groue/GRDB.swift#1385]
### What did you do?
 invoke "fetchOne", for example:

```swift
let sql = String.fetchOne(sql: "SELECT sql FROM sqlite_master")
```

### What did you expect to happen?
"statementDidExecute" should be call

### What happened instead?
"statementDidExecute" is not always called

**Comment by groue** [comment]
This does not look like a real issue created by a real person. If you are real, make it so you appear like a real person, thanks.

**Comment by alexlee002** [comment]
???
OK, let me describe more clearly.

if the result set of query:  `SELECT sql FROM sqlite_master` is empty,  then I call `String.fetchOne(sql: "SELECT sql FROM sqlite_master")`,   the method  `statementDidExecute ` would be invoked.

if the result set it not empty,  only `String.fetchCursur(sql: "SELECT sql FROM sqlite_master")` would invoked `statementDidExecute `, `String.fetchOne` won't invoke `statementDidExecute `, because the result of step() is `SQLITE_ROW` but not `SQLITE_DONE`

**Comment by groue** [comment]
Thanks for giving some details. Yet `statementDidExecute` is a private method, and it's still quite unclear why you have opened this issue.

**Comment by alexlee002** [comment]
I use the core of  GRDB in my project,  and I want to implement some feature to get the executing detail of every sql.

**Comment by groue** [comment]
> I want to implement some feature to get the executing detail of every sql.

Then use the public api for that: the [`trace`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/database/trace(options:_:)) function.

**Comment by alexlee002** [comment]
yes, I use `trace` API too, 

but I also need to get the event when the SQL  will run, did finish / did fail.   which can not get from trace API

**Comment by groue** [comment]
Indeed, those features are not built-in the library.

You have two options here:

1. Use and modify your own private copy of GRDB. Go ahead, modify it for your own convenience, as long as you honor the attached [license](https://github.com/groue/GRDB.swift/blob/master/LICENSE). If you take this route, there is no free support.

2. Contribute to GRDB, for the benefit of all. This can be done by contributing code. But this can also be done by expressing your needs in their entirety, with clarity, and generally in a way that makes it possible to help you as well as other users.

So far, it looks like you have chosen the first option, and that you are quite far from the second. I wish I could close this issue twice.

**Comment by alexlee002** [comment]
Thanks @groue !

Yes,  for some reason,  My current choice is to developing my own private library,   I try to keep the `Core` to compatible with GRDB's Core(maybe about 75%),  but the ORM is different.

I want to add some profiling feature into the Core( which is strong demand of my project,  I'm not sure if other people need it because it will slow down the SQL's execution, If someone need it, I'm very happy to contribute it to GRDB)

And BTW, if I open the source of my DB framework one day in the future(Maybe),  How should I do to avoid infringement of GRDB LICENSE?

**Comment by groue** [comment]
> And BTW, if I open the source of my DB framework one day in the future(Maybe), How should I do to avoid infringement of GRDB LICENSE?

That's easy, the [license](https://github.com/groue/GRDB.swift/blob/master/LICENSE) says how to do it (line 5):

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
