### ISSUE TITLE
Writing a lot of data while observing performance issue 

### ISSUE THREAD

**Issue by vadimvitvickiy** [groue/GRDB.swift#1388]
Hello!
I'm experiencing performance issue, could someone provide me some guidance how to accomplish what I expect?
Basically, I have many db reads and writes while I receive the data from the server.
These requests are executed fine on its own, it takes reasonable time to finish 1k+ writes and reads.

But, when I have listener on the data that being written, it takes a lot more time, minutes instead of seconds without observing, the request of this data is also mid-heavy, it has few nested associations and CTE.
As I can see, by the time profiler, the most time is spent in decoding of `Codable` models.
I wonder if it is a known issue and could be resolved somehow without dirty hacks that pops up in my head?
Thank you.

### What did you do?

Writing and reading some big chunks of data into database while simultaneously observing this data. 

### What did you expect to happen?

The writings will take seconds to finish.

### What happened instead?

Instead, it takes few minitues.

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 6.13.0
**Installation method: SPM
**Xcode version: 14.3.1
**Swift version: 5.8.1
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 13.4

**Comment by vadimvitvickiy** [comment]
> Interesting question! Feel free to monitor your application with Instruments, and compare what you see with what you read in the linked documentations. Maybe you'll find an actual problem, or suggest a good idea. That would be a good contribution!

Using `trackingConstantRegion` seem to fix the issue. 
But I wonder if you could elaborate a bit more, what are the drawbacks of using it?

```
If you happen to use the ValueObservation.trackingConstantRegion(_:) method and see a mismatch between the tracked region and your expectation, then change the definition of your observation by using tracking(_:). You should witness that the logs which start with tracked region now evolve in order to include the expected changes, and that you get the expected notifications.
```

Since I cannot go back to `tracking`, I don't know yet what kind of drawbacks I might encounter later.

Or it might be a hint where I should investigate deeper?

**Comment by groue** [comment]
> Using `trackingConstantRegion` seem to fix the issue.

First, thanks for having taken the time to have a detailed look 🙏

Phew, that matches what I was expecting. `trackingConstantRegion` is a specialized version of `tracking` that is supposed to be "optimized": it is able to use the parallelism enabled by `DatabasePool`.

> But I wonder if you could elaborate a bit more, what are the drawbacks of using it?

In a nutshell, optimized observations can fetch fresh values in parallel with writes, whereas the non-optimized ones can't: writes are serialized with observation fetches (they block each other: there is no parallelism at all).

A detailed explanation is available in the documentation of this method: [`trackingConstantRegion(_:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation/trackingconstantregion(_:)).

*The drawback is that some observations will not work correctly with the optimized version.* The observations that do not work correctly are those that do not fetch their values from a constant database region. The documentation of the method explains what this means, and gives some examples.

To sum up:

- `trackingConstantRegion` creates an optimized observation that enables parallelism.
- Not all observations can use this method, and this is why a clear understanding of what a "constant region" is is important before this method is used.
- The linked documentation provides an explanation.

If you think that the documentation is not clear, please tell: we'll try to improve it.

**Comment by groue** [comment]
I'm closing the issue, @vadimvitvickiy, because I'm not sure there remains any pending question. Feel free to reopen if needed!
