### ISSUE TITLE
Facing swift compiler error in GRDB.swift

### ISSUE THREAD

**Issue by Govindakarthikeyan** [groue/GRDB.swift#139]
Hello,

I integrated the GRDB in my app through cocoa pods. I am facing the swift compiler errors when building the app. Please find the
![screen shot 2016-10-14 at 8 03 22 pm](https://cloud.githubusercontent.com/assets/14067737/19390799/4a7b62a2-9247-11e6-857d-0adec332c025.png)
 screenshot of the errors.

I don't know what i am doing wrong on this. Please do the needful

**Note:** 
1. I installed the latest cocoa pods version 'cocoapods-1.1.0.rc.3'
2. Using Xcode 8 - Swift 3 - macOS Sierra

**Comment by groue** [comment]
Hello @Govindakarthikeyan,

I can't reproduce your issue.

Make sure you use the latest GRDB version, clean up your project (alt-shift-command-K), don't hesitate rebuilding your whole Pods folder, and I'm sure integration will eventually complete successfully.
