### ISSUE TITLE
what kind of case "invalid primary key" in delete record?

### ISSUE THREAD

**Issue by munkhbolde** [groue/GRDB.swift#14]
When I delete record xcode display that error like invalid primary key 
```swift
try! dbQueue.inTransaction { db in 
    try record.delete(db)
    return .Commit
}
```

**Comment by groue** [comment]
Make sure that the `storedDatabaseDictionary` of your Record has a non-nil value for the column of your table that holds its primary key.

**Comment by groue** [comment]
@munkhbolde Any news?

**Comment by munkhbolde** [comment]
Thank you I fixed my error.

**Comment by groue** [comment]
All right, happy GRDB!
