### ISSUE TITLE
Sub class of Record, can not update property value to nil.

### ISSUE THREAD

**Issue by ibadcool** [groue/GRDB.swift#140]
Sub class of Record, can not update property value to nil.
Sorry for my English.

**Comment by groue** [comment]
Hello @ibadcool

Is there any compiler error? Runtime error?

**Comment by ibadcool** [comment]
Hello @groue ,  
There is no error message. I found the reason, when set an property value to nil, the  [String : DatabaseValueConvertible?]   will remove the nil key & value from the dictionary.  

Then I add " ?? NSNull() " , it worked. just like the code: 

override var persistentDictionary: [String : DatabaseValueConvertible?] { 
        var returnDic = [String : DatabaseValueConvertible?]() 
        returnDic["axNote"] = axNote **?? NSNull()**
       return returnDic 
}

**Comment by groue** [comment]
**This is not normal**. GRDB automatically updates the database column to NULL if the dictionary contains nil. You shouldn't have to use NSNull, and `dic["axNote"] = axNote` should work fine even if axNote is nil.

There is another bug somewhere else.

I recommend tracing SQL queries in order to find out the real bug:

```swift
var configuration = Configuration()
configuration.trace = { print($0) }
let dbQueue = DatabaseQueue(databasePath, configuration: configuration)
```

**Comment by ibadcool** [comment]
@groue 
I have done what you said, and I get the SQL string like this:
UPDATE "axOrder" SET "Tax3Inclusive"=0,"PackagerAlreadyPrinted"=0,"RecLastModifiedDBDateTime"=1476586844.0,"Tax2TaxableSales"=0.0,"BarTabName"='Wer',"Tax2InclusiveAmountUsed"=0.0,"SurchargeAmountUsed"=0.0,"Tax2SurchargeTaxable"=0,"DiscountAmountUsed"=0.0,"RecToECStatus"=0,"RowTS"='0x0000000000047158',"Tax1SurchargeTaxable"=0,"BarTabPreAuth"=0,"Kitchen2AlreadyPrinted"=0,"Tax3SurchargeTaxable"=0,"SubTotal"=0.0,"Kitchen6AlreadyPrinted"=0,"RecToHAStatus"=0,"Tax1InclusiveAmountUsed"=0.0,"GuestCount"=5,"BusinessDate"=20161014.0,"DiscountTaxable"=0,"PercentGratuityAmountUsed"=0.0,"OrderNumber"=1000994000000000003,"RecCentralManaged"=0,"Tax1DeliveryChargeTaxable"=0,"Tax2Inclusive"=0,"Tax3DeliveryChargeTaxable"=0,"Tax3AmountUsed"=0.0,"Kitchen3AlreadyPrinted"=0,"GuestCheckPrintedAfterSettled"=0,"BarAlreadyPrinted"=0,"OrderStatus"=1,"Tax2AutoGratuityTaxable"=0,"OrderType"=2,"axEmployeeID"=1000000000000000001,"Tax2TaxPrevTax"=0,"Tax3AutoGratuityTaxable"=0,"Kitchen5AlreadyPrinted"=0,"GuestCheckAlreadyPrinted"=0,"RecCreatedDBDateTime"=1476436128.0,"Tax3TaxPrevTax"=0,"axStationID"=1000000000000000002,"OrderTotal"=0.0,"Tax1Inclusive"=0,"Kitchen4AlreadyPrinted"=0,"RecToBCStatus"=0,"Tax2DeliveryChargeTaxable"=0,"Kitchen1AlreadyPrinted"=0,"DineInTableReady"=0,"GlobalID"='ef32d05d-b05d-48f7-8201-28d73b436062',"Tax1AmountUsed"=0.0,"GratuityApplicableTotal"=0.0,"Tax3TaxableSales"=0.0,"IsPercentGratuityAuto"=0,"Tax1TaxableSales"=0.0,"Tax3InclusiveAmountUsed"=0.0,"OrderDateTime"=1476436064.0,"Tax1AutoGratuityTaxable"=0,"Tax2AmountUsed"=0.0,"RecDeleted"=0 WHERE "axOrderID"=1000994000000000003

the column count of the table is more than the SQL, there is no "null", my GRDB version is 0.60.1
I set the column axDiscountID = nil, but it's not in SQL.  so after order.save(),   the column axDiscountID is also have value in database.
What should I do..  I need your help, guy, Thanks very much.

**Comment by groue** [comment]
First of all, upgrade. The latest version that uses the Swift 2.2 language is GRDB [0.80.2](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#0802-swift-22).

See if the axNote column gets updated, then.

**Comment by ibadcool** [comment]
@groue 
Thanks for ur reply.
I update to 0.80.2, and then I got the runtime error: "fatal error: column HoldUntilDateTime can't be updated because it is missing from persistentDictionary: file /Users/sunny/Documents/TestGRDB/Pods/GRDB.swift/GRDB/Record/Persistable.swift, line 572".
In my code of the Recode sub class, this override method:
```
 override var persistentDictionary: [String: DatabaseValueConvertible?] {
            return ["id": id, "name": name]
 }
```
I change it to:
```
 override var persistentDictionary: [String: DatabaseValueConvertible?] {
            var dic = [String : DatabaseValueConvertible?]() 
            dic["id"] = id
            dic["name"] = dic
            return dic
 }
```

Because my table has lots of columns, about 100 columns, if I write the code just like  return ["id": id, "name": name]...     the Xcode compiler takes a long time then  crashed, I don't know why, maybe it's swift's bug. 
Then the problem is,   I test the code on playground:  
var dic = [String: String?]()
dic = ["id": "1" , "name": nil]
dic   //here is ["id": {Some "1"}, "name": nil]

dic["name"] = nil
dic    here is ["id": {Some "1"}]

so , "name" is missing.

**Comment by groue** [comment]
Great, you have found why the column is missing from the update statement!

Now you have to make sure the persistentDictionary contains all the columns. Your NSNull solution wasn't that bad, after all :smile:

Thanks for the time you spent exploring this issue, @ibadcool. I'm sure our conversation will help other users.

**Comment by ibadcool** [comment]
hi, @groue , I found another way to fix this, just use  dic.updateValue(axNote, forKey: "axNote") to replace dic["axNote"] = axNote
Thank u very much for ur help. And thank u very much for the GRDB framework, it's awesome!

**Comment by groue** [comment]
Good point!

**Comment by groue** [comment]
Your `updateValue(_:forKey:)` tip has entered the [FAQ](https://github.com/groue/GRDB.swift#compilation-takes-a-long-time). Thanks @ibadcool!
