### ISSUE TITLE
[Question] Is it possible to decode an array into a FetchableRecord automatically while using raw SQL?

### ISSUE THREAD

**Issue by mantuness** [groue/GRDB.swift#1404]
### What did you do?

I'm currently trying to run a `MyFetchableRecord.fetchAll` request, written using SQL (that contains a few JOINs), which I was expecting to "decode automatically" into my `MyFetchableRecord`. The thing here is that my `MyFetchableRecord` has a property that is an array `[AnotherRecord]`. 
Besides the result of the request having the expected columns and entries I'm not able to have this result "decoded" into my `MyFetchableRecord` properly. 
Nevertheless I am able to have this result "decoded" successfully if I use QueryInterface and Associations 😉. 

So my question is what do I need to do to make this happen? Some kind of RowAdapter? Is this even possible?

Thanks in advance ✌️

### What did you expect to happen?

To "decode automatically"

### What happened instead?

Error while "decoding"

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:**
**Installation method:** SPM
**Xcode version:** 14.3.1
**Swift version:** 5.8
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 13.4

**Comment by groue** [comment]
Hello @mantuness,

Yes, [Codable Records](https://github.com/groue/GRDB.swift/blob/master/README.md#codable-records) can automatically decode JSON columns into Array properties.

For example:

```swift
struct Dog: Decodable {
    var name: String
}

struct Player: FetchableRecord, Decodable {
    var id: Int64
    var dogs: [Dog]
}

try DatabaseQueue().write { db in
    let sql = """
        SELECT 1 AS id, '[{"name": "Bella"}, {"name": "Buddy"}]' AS dogs
        """
    
    let players = try Player.fetchAll(db, sql: sql)
    
    // [Player(id: 1, dogs: [Dog(name: "Bella"), Dog(name: "Buddy")])]
    print(players)
}
```

If you don't want, or can't have your record type conform to `Decodable`, then provide your own JSON decoding:

```swift
// Decoding a JSON array without Decodable
struct Player: FetchableRecord {
    var id: Int64
    var dogs: [Dog]
    
    init(row: Row) throws {
        self.id = row["id"]
        self.dogs = try JSONDecoder().decode([Dog].self, from: row["dogs"])
    }
}
```

Finally, maybe you have seen this compiler error:

```swift
// Did you see this?
struct Player: FetchableRecord {
    var id: Int64
    var dogs: [Dog]
    
    init(row: Row) throws {
        self.id = row["id"]
        // ❌ Subscript 'subscript(_:)' requires that 'Dog' conform to 'FetchableRecord'
        self.dogs = row["dogs"]
    }
}
```

Reading this message, maybe you have added the `FetchableRecord` conformance to your nested type.

I can understand the confusion. In reality, this subscript is intended for decoding [records from associated tables](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#decoding-a-joined-request-with-fetchablerecord). It is not intended for JSON columns.

Properly speaking, the types that are stored as JSON are not "records", because "records" are meant to decode full database rows (with columns and values). In our sample code, `Dog` is never decoded from any database row. It is just decoded from JSON. And this is why it only conforms to `Decodable`.

**Comment by groue** [comment]
> Nevertheless I am able to have this result "decoded" successfully if I use QueryInterface and Associations 😉.

I may have read your question too fast. You're not after decoding arrays from JSON columns, are you?

Yet a database row fetched from an SQL query that contains JOINs is still a database row: a flat collection of column/value pairs. There's no array there.

Maybe you want to perform the same SQL queries as associations? Then take care that requests built from `including(all:)` perform do not use JOINs. They use *several SQL queries*:

```swift
// SELECT * FROM player
// SELECT * FROM dog WHERE playerId in (...) -- the ids of fetched players
let players = try Player.including(all: Player.dogs).fetchAll(db)
```

Here is a sample code that performs what associations do, with raw SQL:

```swift
// Setup:
// A dog "belongs to" a player.
// A player "has many" dogs.
struct Dog: FetchableRecord, PersistableRecord, Codable {
    var id: Int64
    var playerId: Int64
    var name: String
}

struct Player: FetchableRecord, PersistableRecord, Codable {
    var id: Int64
}

let dbQueue = try DatabaseQueue()

try dbQueue.write { db in
    try db.create(table: "player") { t in
        t.autoIncrementedPrimaryKey("id")
    }
    try db.create(table: "dog") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("playerId", .integer).notNull().references("player")
        t.column("name", .text).notNull()
    }
    
    do {
        try Player(id: 1).insert(db)
        try Dog(id: 1, playerId: 1, name: "Bella").insert(db)
        try Dog(id: 2, playerId: 1, name: "Buddy").insert(db)

        try Player(id: 2).insert(db)
        try Dog(id: 3, playerId: 2, name: "Coco").insert(db)

        try Player(id: 3).insert(db)
    }
}

// Now let's fetch all players with their dogs
struct PlayerInfo {
    var player: Player
    var dogs: [Dog]
}

try dbQueue.read { db in
    let playerRequest: SQLRequest<Player> = "SELECT * FROM player"
    let players = try playerRequest.fetchAll(db)
    
    let playerIds = players.map(\.id)
    let dogRequest: SQLRequest<Dog> = "SELECT * FROM dog WHERE playerId IN \(playerIds)"
    let dogs = try dogRequest.fetchAll(db)
    let dogByPlayerId = Dictionary(grouping: dogs, by: \.playerId)
    
    let playerInfos = players.map { player in
        PlayerInfo(
            player: player,
            dogs: dogByPlayerId[player.id, default: []])
    }
    
    // [
    //   PlayerInfo(player: Player(id: 1), dogs: [
    //     Dog(id: 1, playerId: 1, name: "Bella"),
    //     Dog(id: 2, playerId: 1, name: "Buddy")]),
    //   PlayerInfo(player: Player(id: 2), dogs: [
    //     Dog(id: 3, playerId: 2, name: "Coco")]),
    //   PlayerInfo(player: Player(id: 3), dogs: [])
    // ]
    print(playerInfos)
}
```

**Comment by mantuness** [comment]
But the array property is not a JSON column. It is indeed a representation of an Association. Imagine, you have your table Book and you table Author. An Author has many books. I have a FetchableRecord like:

```
struct AuthorInfo: Codable, FetchableRecord {
  let author: Author
  let books: [Book]
}
```

(Author and Book conform with PersistableRecord & Codable)

I'm able to achieve this by doing:

```
Author
.including(all: Author.books)
.asRequested(by: AuthorInfo.self)
.fetchAll(db)
```

Is it possible to achieve the same but with raw SQL?

Something like:

```
let sql = """
SELECT author.*, book.*
FROM author
JOIN author_book_crossref
    ON author ...
JOIN book
    ON ...
"""
AuthorInfo
.fetchAll(db, sql: sql)
```
?

Thanks in advance 😉

**Comment by groue** [comment]
One last word. 

I hope we made it clear that `including(all:)` is not performed with JOINs. But you may want to use JOINs for something else. In this case, don't miss [this documentation](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/splittingrowadapters(columncounts:)).

**Comment by mantuness** [comment]
I think you answered my question in the previous comment 😅

Many thanks mate. And congrats for this nice work ✌️

**Comment by groue** [comment]
I'm glad one of the answers was spot on 😅 Happy GRDB!
