### ISSUE TITLE
Does GRDB can be configured to load dynamic lib (.dylib) on runtime

### ISSUE THREAD

**Issue by SNNafi** [groue/GRDB.swift#1406]
Firstly, Thanks for this awesome package.

I know SQLite by default build does not support loading extensions for security reasons. But we can enable it. My question is, can we load a custom tokenizer as a dynamic library (.dylib) on runtime and use it through GRDB custom SQLite build?

Again, macOS doesn't support loading unsigned .dylib. But AFAIK, it can be loaded with explicit permission from the user.

**Comment by groue** [comment]
Hello @SNNafi,

That's an interesting question, but I do not know the answer. I'm not familiar with dynamic libraries!

**Comment by SNNafi** [comment]
For example, I have created a tokenizer in c, then compiled it as a universal `.dylib`. As the `sqlite3` comes with macOS, has disabled the loading extension by default, I have to install custom `sqlite3` using brew.  Then I can load the tokenizer like this using the sqlite3 command line,

`sqlite> select load_extension('path');`

Then I can view tables created with this tokenizer or create a new FTS table with it. Like,
`sqlite> CREATE VIRTUAL TABLE table_name USING fts5(id, text, tokenize='custom_tokenizer');`

I want to do the same thing using GRDB. My primary goal is to create a DB browser app for macOS with support for dynamic library loading.

**Comment by groue** [comment]
GRDB supports [custom SQLite builds](https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md). This might be your starting point.

**Comment by groue** [comment]
I'm closing this issue, @SNNafi. If you need to ask further question, please reopen. And if you want to share your successful experience, please explain your technique for the benefit of all GRDB users :-) 🍀
