### ISSUE TITLE
Error loading association when using asRequest()

### ISSUE THREAD

**Issue by baum-sparton** [groue/GRDB.swift#1408]
### What did you do?

I'm trying to load an associated table during a query and am receiving a key not found error.  Code with simplified models:

    struct Personnel: Identifiable, Codable, FetchableRecord, MutablePersistableRecord { 
        var id: Int64? = nil
    
        static let personnelStats = hasOne(PersonnelStats.self)
        var personnelStats: QueryInterfaceRequest<PersonnelStats> {
            request(for: Personnel.personnelStats)
        }

        static let databaseTableName = "personnel"
    
        enum CodingKeys: String, CodingKey {
            case id
        }
    
        private enum Columns {
            static let id = Column(CodingKeys.id)
        }
    
        mutating func didInsert(_ inserted: InsertionSuccess) {
            id = inserted.rowID
        }
    }

    struct PersonnelStats: Identifiable, Codable, FetchableRecord, MutablePersistableRecord {
        var id: Int64? = nil
    
        static let personnel = belongsTo(Personnel.self)
        var personnel: QueryInterfaceRequest<Personnel> {
            request(for: PersonnelStats.personnel)
        }

        static let databaseTableName = "personnel_stats"
    
        enum CodingKeys: String, CodingKey {
            case id
        }
    
        private enum Columns {
            static let id = Column(CodingKeys.id)
        }
    
        mutating func didInsert(_ inserted: InsertionSuccess) {
            id = inserted.rowID
        }
    }

Query looks like this:

    struct PersonnelRequestResult: FetchableRecord, Decodable {
        var personnel: Personnel
        var personnelStats: PersonnelStats
    
        enum CodingKeys: String, CodingKey {
            case personnel
            case personnelStats = "personnel_stats"
        }
    }

    let allPersonnel: [PersonnelRequestResult] = try Personnel
            .including(required: Personnel.personnelStats)
            .asRequest(of: PersonnelRequestResult.self)
            .fetchAll(db)

### What did you expect to happen?

Expected the returned record to include properties with both the personnel and personnel_stats tables.

### What happened instead?

I get this error:
Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "personnel_stats", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No such key: personnel or personnel_stats", underlyingError: nil))

A couple notes:
-The models have been simplified, as I didn't want to post a large quantity of unnecessary code.  I can potentially share more complete code if needed.
-Throughout our code we are not using GRDB naming conventions.  We are matching our code to an existing DB schema that does not follow them.
-I believe my issue is with naming.  The error reflects whatever I put in for the CodingKey in PersonnelRequestResult.  For example if I change "personnel_stats" to "foo".  The error changes to "keyNotFound(CodingKeys(stringValue: "foo", intValue: nil)".  So I think my problem is identifying what name I should specify there.
-If I add specific fields from the personnel_status table and include them in the query with ".annotated(withRequired: Personnel.personnelStats.select(Column(PersonnelStats.CodingKeys.sample)))" the fields load fine.
-Excluded from the code above is another One to many relationship that does load fine.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.16.0
**Installation method:** Xcode Package Manager
**Xcode version:** 14.3.1
**Swift version:**
**Platform(s) running GRDB:** iOS iPhone emulator.
**macOS version running Xcode:** 13.4.1

**Comment by groue** [comment]
Hello @baum-sparton,

You have correctly identified the origin of the issue.

As described in the documentation for the [`including(required:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingrequired) method, it is important to have the _coding key_ of the decoded property match the _association key_ of the included association. Please follow the link for more information.

**Comment by baum-sparton** [comment]
Thanks for the quick reply.  I got it to work by editing the Personnel struct to have the relationship defined as:

    static let personnelStats = hasOne(PersonnelStats.self).forKey("personnel_stats")

It is unclear to me why this was necessary as I believe the coding key was already correct.

The record type being loaded (PersonnelRequestResult) has a member personnelStats with a coding key of "personnel_stats".  That value matches the table name specified in the PersonnelStats struct (static let databaseTableName = "personnel_stats").

Furthermore, the .annotated method had no issue pulling out of the table.  Would you mind clarifying why the forKey is necessary in this case?  What key value was it using before adding the forKey?  Thanks

**Comment by groue** [comment]
Yes, something is troubling indeed. I'll have another look.

**Comment by groue** [comment]
It's time for vacations 😎 I did not forget about this issue, please hold on a little bit more.

**Comment by baum-sparton** [comment]
> It's time for vacations 😎 I did not forget about this issue, please hold on a little bit more.

I've worked around the situation, so no hurry or expectations on my end.  Thanks

**Comment by groue** [comment]
Hello @baum-sparton, sorry for the delay.

The problem lies in the plural name of the `PersonnelStats` type and properties. This is proper English indeed, but this clashes with the inflections performed by GRDB to-one associations.

The key of associations are based on the table name by default, this is true. However the default keys are inflected depending on whether they're used in a singular or plural context.

To-one associations are singularized by default. The intent is to help applications whose schema contains plural table names (many still do):

```swift
// A record type in a database schema that uses plural table names
extension Player: TableRecord {
    static let databaseTableName = "players"

    // Association key is based on the table name "teams",
    // and automatically singularised to "team".
    static let team = belongsTo(Team.self)
}
```

So far so good, but what works for `Player` and `Team` does not work well with `PersonnelStats` 😬 It would not work for `CountryDemographics` either, and similar fixed plural names. We do not want them to be singularized.

To do so, provide an explicit key when you define your `hasOne` association. This instructs GRDB to not inflect the key in singular contexts:

```swift
extension Personnel {
    // Explicit key so that the "stats" suffix
    // is not automatically singularized by GRDB.
    static let personnelStats = hasOne(PersonnelStats.self, key: "personnel_stats")}
}

struct PersonnelRequestResult: FetchableRecord, Decodable {
    var personnel: Personnel
    var personnelStats: PersonnelStats

    enum CodingKeys: String, CodingKey {
        case personnel
        case personnelStats = "personnel_stats"
    }
}

// No error
let allPersonnel: [PersonnelRequestResult] = try Personnel
    .including(required: Personnel.personnelStats)
    .asRequest(of: PersonnelRequestResult.self)
    .fetchAll(db)
```

Actually, now that we use a custom key, why not make it look like a Swift identifier?

```swift
extension Personnel {
    // Explicit key so that the "stats" suffix
    // is not automatically singularized by GRDB.
    static let personnelStats = hasOne(PersonnelStats.self, key: "personnelStats")}
}

struct PersonnelRequestResult: FetchableRecord, Decodable {
    // No need for customized coding keys
    var personnel: Personnel
    var personnelStats: PersonnelStats
}

// No error
let allPersonnel: [PersonnelRequestResult] = try Personnel
    .including(required: Personnel.personnelStats)
    .asRequest(of: PersonnelRequestResult.self)
    .fetchAll(db)
```

This should solve the issue.

---

#### A note on debugging decoding issues

I spotted the problem by printing the debug description of the row decoded by PersonnelRequestResult, with a temporary `init(row: Row)` initializer:

```swift
struct PersonnelRequestResult: FetchableRecord, Decodable {
    var personnel: Personnel
    var personnelStats: PersonnelStats

    enum CodingKeys: String, CodingKey {
        case personnel
        case personnelStats = "personnel_stats"
    }
    
    init(row: Row) throws {
        print(row.debugDescription)
        fatalError("Just debugging")
    }
}
```

With the default key of the `Personnel.personnelStats` association, this would print:

```swift
// ▿ [id:1 ...]
//   unadapted: [id:1 ... id:1 personnelId:1 ...]
//   - personnel_stat: [id:1 personnelId:1 ...]
let allPersonnel: [PersonnelRequestResult] = try Personnel
    .including(required: Personnel.personnelStats)
    .asRequest(of: PersonnelRequestResult.self)
    .fetchAll(db)
```

See how the columns of `personnelStats` are found in the `personnel_stat` scope (instead of  `personnel_stats`). That's how I understood the root issue.

For more information on debugging with debug description of rows, see [Debugging Request Decoding](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#debugging-request-decoding)
