### ISSUE TITLE
Building GRDBCustom within a framework package

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#1409]
### What did you do?
Followed the instructions to the letter ;-) to build a custom version of GRDB associated with tag V6.16.0
However we want this custom version to reside inside a framework package that we will embed within our apps. 

### What did you expect to happen?
The Framework build process would happily build it without error (but the build process is never happy). 

### What happened instead?
Got two errors when trying to complile the `GRDB.h` bridging header...

#### Bridging file for Framework build

Here's the proper bridging file for Framework usage

#### grdb.h
``` swift
//@import Foundation;   // We cannot use @import within a Framework; Use #import instead

// Framework Umbrella Header
// Frameworks this Framework needs.
#import <Foundation/Foundation.h>

//! Project version number for GRDB.
FOUNDATION_EXPORT double GRDB_VersionNumber;

//! Project version string for GRDB.
FOUNDATION_EXPORT const unsigned char GRDB_VersionString[];

#import <GRDB/GRDBCustomSQLite-USER.h>
#import <GRDB/sqlite3.h>
#import <GRDB/GRDB-Bridging.h>  // Under a framework this needs to be specified in Angle Brackets

```

### Environment

**GRDB flavor(s):** GRDB Custom
**GRDB version:** 6.16.0
**Installation method:** Manual
**Xcode version:** 14.3.1
**Swift version:** 5.8.1
**Platform(s) running GRDB:** none yet because of unhappiness above....
**macOS version running Xcode:** 13.4.1

**Comment by groue** [comment]
Hello @martindufort,

This issue does not contain enough information. The setup is not clear. The problem is not clear. Your own attempts at fixing it is are not clear. Your request is not clear. The reason why you have opened this issue is not clear 😅

**Comment by martindufort** [comment]
Looks like there is a lot of mud in the water….
Close this and I will submit something clearer when the water gets
filtered.

**Comment by groue** [comment]
All right, @martindufort, that's fine :-) And maybe you'll want to complete the upgrade from GRDB 4 before building an XCFramework?
