### ISSUE TITLE
Is there any config i can't avoid initial value callback on ValueObservation

### ISSUE THREAD

**Issue by karthuszY** [groue/GRDB.swift#1413]
### What did you do?
Im tracking tables when it changes and I don't need the initial value callback.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** GRDB.swift/SQLCipher (6.10.0):
    - SQLCipher (>= 3.4.2)
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:** Version 14.3 (14E222b)
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

### Demo Project
```
let accountObserveation = ValueObservation.tracking
accountObserveation.start(in: db, scheduling: .async(onQueue: .main))
```

**Comment by groue** [comment]
Hello @karthuszY,

No, there is no such config.

**Comment by karthuszY** [comment]
Thanks for your reply.
