### ISSUE TITLE
Crash in `Inflections.inflectString`

### ISSUE THREAD

**Issue by dawilliams-gpsw** [groue/GRDB.swift#1417]
### What did you do?

A standard `read` operation on the database with a `including(all:)` join.

### What did you expect to happen?

No crash.

### What happened instead?

Crash in the database reader pool, on the `Inflections.inflectString` call in GRDB.

### Environment

**GRDB flavor(s):** GRDB, standard
**GRDB version:** 6.16
**Installation method:** SPM
**Xcode version:** Xcode 14.3.1
**Swift version:** 5.8.1
**Platform(s) running GRDB:** iOS

I cannot include a demo project, but hoping you could tell me if I'm doing something wrong, or something I could look for. The crash reports are coming back like:
<img width="986" alt="Screenshot 2023-08-18 at 10 26 31 AM" src="https://github.com/groue/GRDB.swift/assets/31672012/fd530e98-edaf-4b70-bf8c-ad1e9ecef87a">

Other internal GRDB threads look like this:
<img width="812" alt="reader 5" src="https://github.com/groue/GRDB.swift/assets/31672012/994b4a4e-8271-455c-85ca-62b5c697488f">
<img width="807" alt="reader 3" src="https://github.com/groue/GRDB.swift/assets/31672012/02e8133b-50ec-40dd-b89c-2b751a58f9d9">
<img width="683" alt="reader 2" src="https://github.com/groue/GRDB.swift/assets/31672012/80d81484-1c87-46d5-b4c1-f1b3f60aa3d6">
<img width="815" alt="reader 1" src="https://github.com/groue/GRDB.swift/assets/31672012/4751ca57-ba03-4ae0-bf60-825f71106501">
<img width="811" alt="pool barrier" src="https://github.com/groue/GRDB.swift/assets/31672012/f55891a7-c28b-4c13-ae26-6e6ee0f907d3">

I find it interesting that multiple threads are showing the `Inflections` type (perhaps a hint?).

The call that we're making to GRDB is:
```
        try await reader.read { db in
            try Foo
                .filter(Foo.Columns.someColumn == someValue || Foo.Columns.otherColumn == value)
                .including(all: Foo.bars)
                .asRequest(of: FooWithBars.self)
                .fetchOne(db)
        }
```

where `bars` is a `hasMany` relationship and `FooWithBars` looks like:
```
struct FooWithBars: Codable, Equatable {
    var foo: Foo
    var bars: [Bar]?
}
```

I only see one use of `replaceMatches` in the `Inflections` type, which is line 202, so I'm not sure why firebase categorizes it as line 186 (maybe something inlined? 🤷🏻‍♂️ )

Do you have any ideas as to what I could look for? Cheers!

**Comment by groue** [comment]
Hello @dawilliams-gpsw, I'm far from any computer right now, so it's difficult to make guesses. Maybe look for a detailed error message? This always help.

**Comment by dawilliams-gpsw** [comment]
@groue It's no worries, hopefully you're on vacation somewhere fun! :) 

I wanted to bring it up in case we can improve somehow, or see if I could help track it down internally with your guidance. It may be an apple bug, and so far I only have one crash report with this trace. Unfortunately, no additional details beyond this one firebase report, but if something comes up I'll be sure to let you know!

**Comment by groue** [comment]
@dawilliams-gpsw, do you happen to customize the default English inflections, or do you use the built-in ones?

It would be cool if you would attempt at providing a self-contained reproducing sample code.

Meanwhile, I'll run aggressive multi-threaded testing of inflections and see if anything goes wrong.

**Comment by dawilliams-gpsw** [comment]
@groue Nothing custom on our end— we're even leaning on default Codable conformance to get the free `FetchableRecord` bit. FWIW, we _are_ using the 'experimental' Swift Concurrency features to `try await` our database calls.

Maybe we should not spend so much time here, though. We still only have 1 crash since we released the new version that uses GRDB for these calls.

**Comment by groue** [comment]
I'm closing this issue. Maybe there's something wrong, but I could never reproduce. Let's wait for another report, if any.
