### ISSUE TITLE
using GRDB in a git controlled swift app

### ISSUE THREAD

**Issue by mark-bragg** [groue/GRDB.swift#142]
I am using GRDB with a group in a mobile dev class. I embedded GRDB into our project and it ran fine on mine. Now, when my teammates download the project, they have to reinstall GRDB into the project, but errors are occurring, and it won't build on their systems. Here are the errors:
![unextended-module modulemap](https://cloud.githubusercontent.com/assets/15349627/20027854/b37e6a64-a2dd-11e6-8d93-336600b60ae2.png)

I see how they are connected, but why is this an issue on the other computers when mine works perfectly fine? 
![database swift](https://cloud.githubusercontent.com/assets/15349627/20027852/8a15aa20-a2dd-11e6-881b-6054495d500b.png)

**Comment by groue** [comment]
Hello @mark-bragg 

Make sure that their Xcode application is named Xcode, and installed in the /Applications folder.

**Comment by mark-bragg** [comment]
wow. so simple. thank you for the extremely quick response as well!

**Comment by groue** [comment]
You're welcome! Happy GRDB and mobile dev class!
