### ISSUE TITLE
Pull the data of a table repeatedly, and get a blank data every two times

### ISSUE THREAD

**Issue by kaaaaai** [groue/GRDB.swift#1422]
### What did you do?

I have a sidebar view and every time it comes up is when I pull the data, i use DatabaseQueue, like this:
```Swift
static func fetchAllPlayer() -> [Player] {
        do {
            guard let players: [Player] = try DBManager.shared.dbQueue?.read({ db in
                try Player.fetchAll(db)
            }) else {
                return []
            }
            
            return players
        } catch {
            Log.e("\(error)")
            return []
        }
    }
```
to read the data to load the sidebar list, but I find that every two times it just returns an empty data, but the data in the data table doesn't actually change

### What did you expect to happen?

Getting it right every time.

### What happened instead?

No normal data returned

**Comment by groue** [comment]
Hello @kaaaaai

You did not provide enough information.

**Comment by kaaaaai** [comment]
> Hello @kaaaaai
> 
> You did not provide enough information.

Thanks for the reply, added the method implementation, is this ok?

**Comment by groue** [comment]
> Thanks for the reply, added the method implementation, is this ok?

This is code that looks perfectly fine, but does not give any hint at why your app does not behave as expected.

The code it executes is battle-tested, and runs in many GRDB-powered applications everyday without any problem.

If you don't get the players you expect out of this code, then it means that the database does not contain the players you expect. I suggest you focus on what you write in the db.
