### ISSUE TITLE
Generic parameters in function definition

### ISSUE THREAD

**Issue by erkkifromdeepforest** [groue/GRDB.swift#1426]
### What did you do?

I built the project "GRDB.xcworkspace" from your install package 

### What did you expect to happen?

No issues should exist in build 

### What happened instead?

Several errors like this:  Generic parameter 'RowDecoder' shadows generic parameter from outer scope
        with the same name; this is an error in Swift 6 

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:  **  6.11.0
**Installation method:** github's installation package
**Xcode version:**  15.0 beta 8 (15A5229m)
**Swift version:**  
**Platform(s) running GRDB:**  macOS
**macOS version running Xcode:**    macOS Sonoma beta 7 (23A5337a)

### Demo Project

 try your own GRDB.xcworkspace

**Comment by groue** [comment]
Hello @erkkifromdeepforest,

I just installed Xcode 15 beta 8, and it compiles the latest GRDB version without any warning.

Maybe try upgrading?
