### ISSUE TITLE
Debugger can't show variable values

### ISSUE THREAD

**Issue by bibhas2** [groue/GRDB.swift#143]
This may not be a defect with GRDB per se. I am just trying to get some help.

We are using GRDB. We also have some legacy SQLite code written in Objective-C. We import the header file of the Objective-C code in a bridging header which in turn imports ``sqlite3.h``. In this configuration the debugger can no longer show any variable's value. Instead we get this error:

```
warning: Swift error in module MyiOSApp.
Debug info from this module will be unavailable in the debugger.

error: in auto-import:
failed to get module 'MyiOSApp' from AST context:
```

If we solely use GRDB or our legacy code then the debugger works just fine. 

Has anyone else seen this before? Is there a work around? Thanks.

**Comment by groue** [comment]
Hello @bibhas2 

I've never seen such a problem, and I don't quite know how to fix it. Maybe another user will come and comment.

But let me try:

I would not include sqlite3.h in the bridging header. Obj-c files can import it, but this does not require any support from the bridging header.

Swift files can still have access to sqlite3.h and raw SQLite APIs if they need it, but this does not involve including sqlite3.h in the bridging header: use [this technique](https://github.com/groue/GRDB.swift#raw-sqlite-pointers) instead.

I hope this will fix your debugger issues.

**Comment by bibhas2** [comment]
Our legacy Objective-C header looks something like this.

```objectivec
#import <Foundation/Foundation.h>
#import <sqlite3.h>

@interface SchemaManager : NSObject
  + (sqlite3 *) open;
  + (void) close: (sqlite3 *) con;
} 
```

If I do not import ``sqlite3.h`` I will get compile errors because of those ``sqlite3 *`` pointers. Not sure how I can get around that.

**Comment by groue** [comment]
Just avoid including sqlite3.h in your bridging header

**Comment by bibhas2** [comment]
I am not directly including ``sqlite3.h`` from the bridging header. I am including ``sqlite3.h`` from my own Objective-C header as shown above. I then import my Objective-C header from the bridging header.

**Comment by groue** [comment]
What about **not** including sqlite3.h from your bridging header??? Just **do it**.

**Comment by bibhas2** [comment]
I get compile error for ``sqlite3 *`` pointer types if I do not include ``sqlite3.h``. May be I am missing something. So, here are some sudo code that attempts to not include ``sqlite3.h`` from bridging header.

### SchemaManager.h

```objectivec
#import <Foundation/Foundation.h>

@interface SchemaManager : NSObject
  + (sqlite3 *) open
@end
```

### SchemaManager.m

```objectivec
#import <sqlite3.h>
#import "SchemaManager.h"

@implementation SchemaManager
+ (sqlite3 *) open {
  //Code omitted...
}
@end
```

### Bridging-Header.h

```objectivec
#ifndef Bridging_Header_h
#define Bridging_Header_h

#import "SchemaManager.h"

#endif
```

This leads to compile error:

```
error: expected a type
+ (sqlite3 *) open;
   ^

failed to import bridging header '/Users/bibhas/Documents/xxx/Bridging-Header.h'
```

**Comment by groue** [comment]
@bibhas2 Don't include it in the ***bridging header***. But include it in objc files that need it, of course.

**Comment by bibhas2** [comment]
I am doing exactly what you are saying. I posted my code above. And it doesn't compile. 

I appreciate your help and don't wish to take up too much of your time on this.

**Comment by groue** [comment]
Yes, you are right. OK. So if I understand well, declarations like `+ (sqlite3 *) open` have to end up in the bridging header (dragging sqlite3.h with them), because you want Swift to use both objc database methods, and GRDB database methods. Maybe you'll end up having your Swift code use only GRDB, but right now Swift uses both. And this leads to that debugger issue. Did I describe correctly the situation?

**Comment by bibhas2** [comment]
Yes, you have described the issue correctly. Converting our legacy Objective-C code to GRDB is definitely a solution. We will do it if you have no other work around. 

This is a bad bug in Xcode and I hope Apple will fix it some day.

**Comment by groue** [comment]
I'm sorry I could not help more. Google only tells stories of unresolved lldb issues...
