### ISSUE TITLE
Getting runtime warnings (the purple ones) in `ValueConcurrentObserver`

### ISSUE THREAD

**Issue by tgrapperon** [groue/GRDB.swift#1431]
### What did you do?

In an app built with `-enable-actor-data-race-checks` enabled, We're getting runtime warnings in `ValueConcurrentObserver`. We're not sure if this is a false positive, or if something is not right.

We usually perform observation using an `AsyncStream`:
```swift
AsyncStream { continuation in
  let observation = ValueObservation.tracking { db in … }

  let cancellable = observation.start(
    in: db,
    onError: {
      continuation.finish()
    },
    onChange: { values in
      continuation.yield(…)
    }
  )

  continuation.onTermination = { _ in
    cancellable.cancel()
  }
}
```
(We disregard the fact that the `AnyDatabaseCancellable` is not `Sendable` (which is a requirement to onboard `onTermination`), which is not optimal).

Is there anything we can do to improve the situation on our side, or is this an issue with GRDB?
Thanks!

<img width="1130" alt="Screenshot 2023-09-13 at 12 18 14" src="https://github.com/groue/GRDB.swift/assets/35562418/c1e6600a-8838-49a4-b385-80aca7338fbe">

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.18.0
**Installation method:** SPM
**Xcode version:** 15RC
**Swift version:** 5.9
**Platform(s) running GRDB:** iOS 17
**macOS version running Xcode:** macOS 13.5.2

**Comment by groue** [comment]
Hello @tgrapperon,

Oh, thanks for the report.

Do you think you could use the built-in `ValueObservation` support for async sequence instead of your custom stream?
 https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation/values(in:scheduling:bufferingpolicy:)

```swift
let observation = ValueObservation.tracking { db in
    try Player.fetchAll(db)
}

for try await players in observation.values(in: dbQueue) {
    print("Fresh players: \(players)")
}
```

This `observation.values` sequence is the fostered way for transforming an observation into an async sequence. This would help focusing our troubleshooting, and solving the issue, whatever it is, for all GRDB users.

Also, a reproducible example would be very appreciated!

**Comment by tgrapperon** [comment]
I wasn't aware of that API! It should probably work, as we're essentially funneling all observations into async sequences. I'll give it a spin an let you know! I'll try to extract a reproducible example if I can too.

**Comment by tgrapperon** [comment]
Initial report, using `.values(in:…` seems to fix the issue.
As a precision, we were using `AsyncValueObservationScheduler(queue: .global(qos: .userInitiated))` as scheduler. 
We'll continue migrating observation to this API.
I'm not forgetting about the repro, and I'll try to extract one as soon as I find the time.
Thanks for your help!

**Comment by groue** [comment]
Thanks @tgrapperon. I'm happy that you no longer have any runtime warning.

Yet, the `scheduler` argument in the experimental GRDB api is a code smell. The whole point of Swift Concurrency is to perform **implicit** jumps between concurrency domains:

Before Swift Concurrency:

```swift
// OLD
func computeValue(completion: @escaping (Int) -> Void) { ... }

func computeAndUseValue() {
    computeValue(completion: { value in
        // Explicit jump to the main thread required
        DispatchQueue.main.async {
            use(value)
        }
    })
}

// Precondition: must be called on the main thread
func use(_ value: Int) {
    precondition(Thread.isMainThread, "Not on the main thread!")
    ...
}
```

After Swift Concurrency:

```swift
// NEW
func computeValue() async -> Int { ... }

func computeAndUseValue() async {
    let value = await computeValue()
    // Implicit jump to the main thread
    await use(value)
}

@MainActor
func use(_ value: Int) { ... }
```

So I'll be happy if you come up with a repro. This would help me better understand what's going on, and maybe get rid of that `scheduler` parameter.

**Comment by tgrapperon** [comment]
Thanks for getting back, and sorry for not responding sooner. I can't really find the time to extract a repro right now, but my initial intention to use the scheduler (in the previous implementation that was not producing an async sequence right away) was to avoid performing callbacks on the main thread, as these sequences are ultimately observed in some TCA effect. I haven't found the time to experiment with removing it, but if it behaves the same for us, we probably didn't have a reason to use it to begin with. I'll keep you posted. Sorry again for the late reply!

**Comment by groue** [comment]
I'm closing this issue. If the purple warning comes back, we'll reopen!
