### ISSUE TITLE
Conflict definition with iOS built-in sqlite while integrating GRDBCustom

### ISSUE THREAD

**Issue by alexlee002** [groue/GRDB.swift#1433]
### What did you do?

* I add GRDBCustom with custom sqlite to my project.
* another modules using fmdb(dependence system built-in sqlite) are already added to the project

and I got an compile error:
![image](https://github.com/groue/GRDB.swift/assets/576164/ac0c51c5-2138-41fa-a01c-f505cb15eebf)

* The Demo project:
![image](https://github.com/groue/GRDB.swift/assets/576164/e7036bb0-ca99-4c43-851a-1a39b07da508)

* the Podfile:

```ruby
install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true,
  :disable_input_output_paths => true


platform :ios, '11.0'
workspace 'GRDBTest'
use_frameworks! :linkage => :static

target 'GRDBTest' do
  project 'GRDBTest.xcodeproj'

	pod 'FMDB', '2.7.5'
end
```

* The testing code:

```swift
import UIKit
import GRDB
import FMDB
//import SQLite3 // for testinng

@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        window = UIWindow()
        window?.backgroundColor = UIColor.cyan
        window?.rootViewController = UIViewController()
        window?.makeKeyAndVisible()
        
        do {
            let grdbqueue = try DatabaseQueue()
            try grdbqueue.read { db in
                let ver = try String.fetchOne(db, sql: "SELECT sqlite_version()")
                print("sqlite version: \(ver!)")
            }
            
            let queue = FMDatabaseQueue(path: nil)
            queue?.inDatabase({ db in
                if let rs = try? db.executeQuery("SELECT sqlite_version()", values: nil) {
                    rs.next()
                    print("FMDB sqlite version: \(rs.string(forColumnIndex: 0))")
                } else {
                    print("FMDB error")
                }
            })
        } catch {
            print(error)
        }
        
        return true
    }

```

### What did you expect to happen?

fix the error

 Environment

**GRDB flavor(s):** (GRDB, Custom SQLite build)
**GRDB version:** 6
**Installation method:** (manual)
**Xcode version:** 14.3
**Platform(s) running GRDB:** (iOS,)
**macOS version running Xcode:** 13.5

**Comment by groue** [comment]
Hello @alexlee002,

It is difficult to link several versions of SQLite in a single binary, as you can see.

You can search for other similar linker issues, and look for inspiration.

You might also resurrect [GRDBObjc](https://github.com/groue/GRDBObjc) and use it as a replacement for FMDB. This would make it possible to avoid the complex linker setup by using a single version of SQLite.

**Comment by alexlee002** [comment]
Thanks @groue 

I use GRDBObjc too, but My project is a big project contains hundreds of modules, some of them is 3rd SDK, and they may includes the built-in sqlite. And I need to migrate to GRDB for some modules one by one in serval versions before migrate all my own modules.

**Comment by groue** [comment]
All right. You have to gather information about how to control the linker.

**Comment by alexlee002** [comment]
I got the solution now!

We need to follow this rule:

**Any module that import GRDB does NOT import SQLite3**

import FMDB is OK, because FMDB's headers are good designed and not import sqlite

**Comment by groue** [comment]
Glad you fixed your issue! Happy GRDB :)
