### ISSUE TITLE
Support needed: Defining foreign key in a migration

### ISSUE THREAD

**Issue by gmoraleda** [groue/GRDB.swift#1437]
I'm trying to define an association of `hasOne` / `belongsTo` in a freshly created table.
That new table represents some local state related to an object in another table that has a relation 1:1 to a backend response. 

I want to create a relationship based on the `id` column, present in both tables as the primary key.

Old table (the one that represents the backend object). I've added the `hasOne` statement.
```diff
extension DRCompanyAttendance: DatabaseRecord, TableRecord {
    static let databaseTableName = DatabaseTable.dailyReportsCompanyAttendance.rawValue
+ static let dailyReportsCompanyAttendanceDuplicate = hasOne(DRCompanyAttendanceDuplicate.self, using: DRCompanyAttendanceDuplicate.companyAttendanceForeignKey)

    static func createTable(in database: Database) throws {
        try database.create(table: databaseTableName) { table in
            table.primaryKey(CodingKeys.id.stringValue, .text, onConflict: .replace)
            table.column(CodingKeys.createdAt.stringValue, .datetime).notNull()
            table.column(CodingKeys.updatedAt.stringValue, .datetime).notNull()
            table.column(CodingKeys.deletedAt.stringValue, .datetime)
            table.column(CodingKeys.projectId.stringValue, .text).notNull()
            table.column(CodingKeys.date.stringValue, .text).notNull()
            table.column(CodingKeys.headcount.stringValue, .integer)
            table.column(CodingKeys.description.stringValue, .text)
        }
    }
}
```

New table (the one that holds some local state and needs to point back to the old table). This object is not referenced in any way as a column in the previous table. Therefore I've opted to use the same value as primary key:
```swift
extension DRCompanyAttendanceDuplicate: DatabaseRecord, TableRecord {
    static let companyAttendanceForeignKey = ForeignKey(["id"])

    static let databaseTableName = DatabaseTable.dailyReportsCompanyAttendanceDuplicate.rawValue
    static let dailyReportsCompanyAttendance = belongsTo(DRCompanyAttendance.self, using: companyAttendanceForeignKey)

    static func createTable(in database: Database) throws {
        try database.create(table: databaseTableName) { table in
            table.primaryKey(CodingKeys.id.stringValue, .text, onConflict: .replace) // This should be the same id as the entry in the old table (DRCompanyAttendance)
            table.column(CodingKeys.isHeadcountDuplicated.stringValue, .boolean).notNull()
            table.column(CodingKeys.isDescriptionDuplicated.stringValue, .boolean).notNull()
        }
    }
}
```

My goal is to be able to cascade deletions, but I'm missing something in the setup.

Thanks a lot in advance!

**Comment by groue** [comment]
Hello @gmoraleda,

To create a table whose primary key is also a foreign key, use the [`references`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/columndefinition/references(_:column:ondelete:onupdate:deferred:)) method on the column definition returned by the `primaryKey` table definition method:

```swift
try db.create(table: "attendanceDuplicate") { t in
    t.primaryKey("id", .text)
        .references("attendance", onDelete: .cascade)
}
```

**Comment by gmoraleda** [comment]
Thanks for the reply @groue 
I tried that approach previously without success. Even setting the deferred flag to true.
I found the bug, though: I was saving the duplicate before the main object itself, and since both statements were in different transactions, deferred had no effect.

All good now.
Thanks again!

**Comment by groue** [comment]
Glad you found your real issue, @gmoraleda :-)
