### ISSUE TITLE
String Interpolation doc example doesn't compile

### ISSUE THREAD

**Issue by mikechambers** [groue/GRDB.swift#1445]
### What did you do?

Looking at String Interpolation docs at:

https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md#sql-literal

The section titled:

"Extract the plain SQL string from a literal:"

It shows the following code:

```
let query: SQL = "UPDATE player SET name = \(name) WHERE id = \(id)"
let (sql, arguments) = try dbQueue.read(query.build)
```

This gives a compile time error that "Expression is async but not marked with await"

If you change the code to:

```
let query: SQL = "UPDATE player SET name = \(name) WHERE id = \(id)"
let (sql, arguments) = try await dbQueue.read(query.build)
```

You this get this warning:

>Converting non-sendable function value to '@Sendable (Database) throws -> (String, StatementArguments)' may introduce data races

Note, if you run within an enclosure like so:

```
		let results: [Row] = try await dbQueue!.read {
			transaction -> [Row] in
			let (sql, arguments) = try self.dbQueue!.read(query.build)
			return try Row.fetchAll(
				transaction,
				sql: sql,
				arguments: arguments
			)
		}
```

The errors go away.

### What did you expect to happen?

Expected code example to run without issue

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
Pods

**Xcode version:**

15.0

**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)

macOs 14.0
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @mikechambers, and thanks for pointing an area of the doc that needs an improvement.

I'll explain what is happening below. I hope this will help finding the basis for the updated documentation.

---

`SQL.build` is the `SQL` method that returns an sql plain string, and arguments. It accepts a Database connection as an argument. The documentation example does not make it explicit, so let's fix it:

```swift
let query: SQL = "UPDATE player SET name = \(name) WHERE id = \(id)"
let (sql, arguments) = try dbQueue.read { db in
    query.build(db)
}
```

---

Now enter a subtlety: the `read` method is synchronous in synchronous contexts, and asynchronous in asynchronous context. Compare:

```swift
// A synchronous function
func useTheDatabase() throws {
    try dbQueue.read { ... }
}

// An asynchronous function
func useTheDatabase() async throws {
    try await dbQueue.read { ... }
}
```

The documentation of String interpolation was written before the introduction of async/await in GRDB, so it is not mentioned. But this explains the "Expression is async but not marked with await" compiler message.

---

Your second code snippet calls `read` from another `read`, which is incorrect. Instead, call `build` directly, since you already have a Database connection from within the `read`:

```swift
let query: SQL = "SELECT ..."
let results: [Row] = try await dbQueue.read { db in
    let (sql, arguments) = try query.build(db)
    return try Row.fetchAll(
        db,
        sql: sql,
        arguments: arguments
    )
}
```

---

Finally, you can write even shorter code with [SQLRequest](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/sqlrequest), another type that supports SQL interpolation:

```swift
let query: SQL = "SELECT ..."
let results: [Row] = try await dbQueue.read { db in
    return SQLRequest<Row>(literal: query).fetchAll(db)
}
```

Or:

```swift
let request: SQLRequest<Row> = "SELECT ..."
let results: [Row] = try await dbQueue.read { db in
    return request.fetchAll(db)
}
```

**Comment by groue** [comment]
I have updated the documentation at https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md#sql-literal.

Now it reads:

> To extract the plain SQL string from a literal, you need a `Database` connection such as the one provided by the `read` and `write` methods:
> 
> ```swift
> try dbQueue.read { db in
>     let query: SQL = "UPDATE player SET name = \(name) WHERE id = \(id)"
>     let (sql, arguments) = try query.build(db)
>     print(sql)       // prints "UPDATE player SET name = ? WHERE id = ?"
>     print(arguments) // prints ["O'Brien", 42]
> }
> ```

The compiler will guide the user towards the async variant when needed.

**Comment by groue** [comment]
> You this get this warning:
> 
> Converting non-sendable function value to 'https://github.com/sendable (Database) throws -> (String, StatementArguments)' may introduce data races

Please report if you keep on seeing this warning, @mikechambers.

**Comment by mikechambers** [comment]
> > You this get this warning:
> > Converting non-sendable function value to 'https://github.com/sendable (Database) throws -> (String, StatementArguments)' may introduce data races
> 
> Please report if you keep on seeing this warning, @mikechambers.

Thanks. The issue was I was using:

```
try dbQueue.read { db in
    try query.build(db)
}
```

inside an existing enclosure / transaction. Switching to:

```
let (sql, arguments) = try query.build(db)
```

fixed it.

Really appreciate the quick response, and absolute love the library. The more I get my head around it, the more I realize how well it is thought out.

**Comment by mikechambers** [comment]
>Finally, you can write even shorter code with [SQLRequest](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/sqlrequest), another type that supports SQL interpolation:

AHHH!!! That is what I was looking for. (I had seen some older code from years ago that no longer worked). Thank you again!

**Comment by groue** [comment]
Thank you, I'm glad you like it :-) Don't hesitate asking further questions if needed. Happy GRDB!

**Comment by mikechambers** [comment]
```
let request: SQLRequest<Row> = "SELECT ..."
let results: [Row] = try await dbQueue.read { db in
    return request.fetchAll(db)
}
```

I think the return should have a try in front of it:

```
let request: SQLRequest<Row> = "SELECT ..."
let results: [Row] = try await dbQueue.read { db in
    return try request.fetchAll(db)
}
```

At least xcode complained without it

**Comment by groue** [comment]
Oops, thanks. I have fixed the sample code.
