### ISSUE TITLE
VisionOS support

### ISSUE THREAD

**Issue by medabida** [groue/GRDB.swift#1446]
Hi, are there any plans for supporting VisionOS
Thanks

**Comment by groue** [comment]
Hi @medabida,

Do you have any problem building GRDB for VisionOS?

**Comment by medabida** [comment]
<img width="772" alt="Screenshot 2023-10-25 at 10 35 15" src="https://github.com/groue/GRDB.swift/assets/11818411/11408714-2d07-4a60-b61b-fabe63652c71">

**Comment by groue** [comment]
Hello @medabida,

When you add GRDB to your VisionOS app, make sure to pick only the GRDB library, not GRDB-dynamic, as in the screenshot below:

<img width="1048" alt="Capture d’écran 2023-10-29 à 16 27 17" src="https://github.com/groue/GRDB.swift/assets/54219/9effbcaa-f20f-453d-9a91-de337c41fff4">

I could successfully build a VisionOS app and open a database with these settings.
