### ISSUE TITLE
taking long time or stuck to compile GRDB swift files I created

### ISSUE THREAD

**Issue by avaan** [groue/GRDB.swift#145]
I just followed the IOS example and created my DB model files in swift(person.swift).
when I compile its looks never ending and hangs.

If I remove those DB related files(person.swift) my project compile without any stuck.

can anyone tell me whats the issue.

Note: after commenting override functions of "Record" the project compiled.

Xcode 8.0
Swift 3

**Comment by groue** [comment]
@avaan I guess you have a person model with many columns, and the Swift compiler finds it very hard to compile the persistentDatabaseDictionary property:

```swift
override var persistentDictionary: [String: DatabaseValueConvertible?] {
    // Swift compiler finds it hard to process a dictionary literal with many keys and values:
    return [
        "a": a,
        "b": b,
        ...
}
```

To fix this, build your dictionary step by step:

```swift
override var persistentDictionary: [String: DatabaseValueConvertible?] {
    var dict: [String: DatabaseValueConvertible?] = [:]
    dict.updateValue(a, forKey: "a")
    dict.updateValue(b, forKey: "b")
    ...
    return dict
}
```

Compilation time will greatly improve.

Note: It's important that you use the `updateValue` method:

```swift
// GOOD
dict.updateValue(a, forKey: "a")
// BAD: when the value is nil, this erases the key.
dict["a"] = a
```

**Comment by avaan** [comment]
@groue thanks for your sugestion. It worked like a charm....

**Comment by groue** [comment]
You're welcome, @avaan. I added a [FAQ](https://github.com/groue/GRDB.swift#compilation-takes-a-long-time), since you're not the first stumbling on this issue.
