### ISSUE TITLE
drop(column:) func only available in CustomGRDB implementation or macOS 12+

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#1451]
### What did you do?
Just removed our GRDB Custom implementation from our app  (now that we know JSON functions are available) and the `drop(column:)` function now reports an error (macOS 12+) only.

### What did you expect to happen?
Was expecting the `drop` function to be available in macOS 11.5+

### What happened instead?
Error: `drop(column:)' is only available in macOS 12.0 or newer`

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.26.0
**Installation method:** SPM
**Xcode version:** 14.3.1
**Swift version:** 5.x
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 13.6

**Comment by groue** [comment]
Helle @martindufort!

`ALTER TABLE DROP COLUMN` is a feature shipped in [SQLite 3.35.0](https://www.sqlite.org/releaselog/3_35_0.html).

MacOS 11.6 ships with SQLite 3.32.3.

So macOS 11.5 does not have this feature.

Maybe the availability of `drop(column:)` can be extended like we recently did together for JSON functions, but not to macOS 11.5 😅 This would just create runtime errors!

**Comment by martindufort** [comment]
Hey @groue, 
Thanks for this. 
I forgot that using a `CustomGRDB` version would also bind it with `Sqlite 3.42.0` which supports the `ALTER TABLE DROP COLUMN`. 

We will have to revert to using the previous mechanism of creating a new table and copying the old one back in...
