### ISSUE TITLE
can upsertAndFetch support list record？  now only support one record

### ISSUE THREAD

**Issue by songzhiming** [groue/GRDB.swift#1455]
### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @songzhiming.

`upsertAndFetch` is an instance method. It thus deals with a single record:

```swift
let player = Player(id: 1, name: "Arthur", score: 1000)
let upsertedPlayer: Player = try player.upsertAndFetch(db)
```

If you want to upsert multiple records, perform a loop:

```swift
let players: [Player] = [...]
let upsertedPlayers = try players.map { player in
    try player.upsertAndFetch(db)
}
```

**Comment by songzhiming** [comment]
@groue hello，upsert multiple records, perform a loop  it take more times。   like below sql  faster
let sql = """
    INSERT INTO Player(name, type, source)
    VALUES 
    ("nihao", 1, "a"),
    ("nihao", 2, "b"),
    ("nihao", 3, "a")
    ON CONFLICT 
    DO UPDATE SET
    name = EXCLUDED.name
    RETURNING playerId
    """

**Comment by songzhiming** [comment]
@groue  how i get return playerid array
```
let sql = """
INSERT INTO Player(name, type, source)
VALUES
("nihao", 1, "a"),
("nihao", 2, "b"),
("nihao", 3, "a")
ON CONFLICT
DO UPDATE SET
name = EXCLUDED.name
RETURNING playerId
"""
```

**Comment by groue** [comment]
> @groue hello，upsert multiple records, perform a loop  it take more times。   like below sql  faster

Inserting multiples rows like this is not currently implemented in GRDB.

Do you have a REAL performance problem?

**Comment by groue** [comment]
> @groue  how i get return playerid array
> 
> ```
> 
> let sql = """
> 
> INSERT INTO Player(name, type, source)
> 
> VALUES
> 
> ("nihao", 1, "a"),
> 
> ("nihao", 2, "b"),
> 
> ("nihao", 3, "a")
> 
> ON CONFLICT
> 
> DO UPDATE SET
> 
> name = EXCLUDED.name
> 
> RETURNING playerId
> 
> """
> 
> ```

Fetch player ids:

```swift
let playerIds = try String.fetchAll(db, sql: """
    INSERT ...
    """)
```

**Comment by songzhiming** [comment]
> > @groue  how i get return playerid array
> > ```
> > 
> > let sql = """
> > 
> > INSERT INTO Player(name, type, source)
> > 
> > VALUES
> > 
> > ("nihao", 1, "a"),
> > 
> > ("nihao", 2, "b"),
> > 
> > ("nihao", 3, "a")
> > 
> > ON CONFLICT
> > 
> > DO UPDATE SET
> > 
> > name = EXCLUDED.name
> > 
> > RETURNING playerId
> > 
> > """
> > ```
> 
> Fetch player ids:
> 
> ```swift
> let playerIds = try String.fetchAll(db, sql: """
>     INSERT ...
>     """)
> ```
it cause error  
 `SQL> SELECT * FROM sqlite_master LIMIT 1
SQL> BEGIN DEFERRED TRANSACTION
SQL> CREATE TABLE "player" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "score" INTEGER NOT NULL, "source" INTEGER NOT NULL, UNIQUE ("score", "source"))
SQL> ROLLBACK TRANSACTION
Playground execution terminated: An error was thrown and was not caught:
▿ SQLite error 1: no such column: nihao - while executing `INSERT INTO Player(name, score, source)
VALUES
("nihao", 1, "a"),
("nihao", 2, "b"),
("nihao", 3, "a")
ON CONFLICT
DO UPDATE SET
name = EXCLUDED.name
RETURNING playerId`
  ▿ extendedResultCode : 1 (SQL logic error)
    - rawValue : 1
  ▿ message : Optional<String>
    - some : "no such column: nihao"
  ▿ sql : Optional<String>
    - some : "INSERT INTO Player(name, score, source)\nVALUES\n(\"nihao\", 1, \"a\"),\n(\"nihao\", 2, \"b\"),\n(\"nihao\", 3, \"a\")\nON CONFLICT\nDO UPDATE SET\nname = EXCLUDED.name\nRETURNING playerId"
  - arguments : nil
  - publicStatementArguments : false
`
`import GRDB

var configuration = Configuration()
configuration.prepareDatabase { db in
    db.trace { print("SQL> \($0)") }
}
let dbQueue = try DatabaseQueue(configuration: configuration)

struct Player: Codable, FetchableRecord, MutablePersistableRecord {
    var id: Int64?
    var name: String
    var score: Int
    var source: Int
    
    mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}

try dbQueue.write { db in
    try db.create(table: "player") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
        t.column("score", .integer).notNull()
        t.column("source", .integer).notNull()
        t.uniqueKey(["score","source"])
    }
    
    do {
        let sql = """
        INSERT INTO Player(name, score, source)
        VALUES
        ("nihao", 1, "a"),
        ("nihao", 2, "b"),
        ("nihao", 3, "a")
        ON CONFLICT
        DO UPDATE SET
        name = EXCLUDED.name
        RETURNING playerId
        """
        let playerIds = try Int.fetchAll(db, sql: sql)
        print(playerIds)
    }

}`

**Comment by songzhiming** [comment]
> > @groue  how i get return playerid array
> > ```
> > 
> > let sql = """
> > 
> > INSERT INTO Player(name, type, source)
> > 
> > VALUES
> > 
> > ("nihao", 1, "a"),
> > 
> > ("nihao", 2, "b"),
> > 
> > ("nihao", 3, "a")
> > 
> > ON CONFLICT
> > 
> > DO UPDATE SET
> > 
> > name = EXCLUDED.name
> > 
> > RETURNING playerId
> > 
> > """
> > ```
> 
> Fetch player ids:
> 
> ```swift
> let playerIds = try String.fetchAll(db, sql: """
>     INSERT ...
>     """)
> ```

cause error 
`SQL> SELECT * FROM sqlite_master LIMIT 1
SQL> BEGIN DEFERRED TRANSACTION
SQL> CREATE TABLE "player" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "score" INTEGER NOT NULL, "source" INTEGER NOT NULL, UNIQUE ("score", "source"))
SQL> ROLLBACK TRANSACTION
Playground execution terminated: An error was thrown and was not caught:
▿ SQLite error 1: no such column: nihao - while executing `INSERT INTO Player(name, score, source)
VALUES
("nihao", 1, "a"),
("nihao", 2, "b"),
("nihao", 3, "a")
ON CONFLICT
DO UPDATE SET
name = EXCLUDED.name
RETURNING playerId`
  ▿ extendedResultCode : 1 (SQL logic error)
    - rawValue : 1
  ▿ message : Optional<String>
    - some : "no such column: nihao"
  ▿ sql : Optional<String>
    - some : "INSERT INTO Player(name, score, source)\nVALUES\n(\"nihao\", 1, \"a\"),\n(\"nihao\", 2, \"b\"),\n(\"nihao\", 3, \"a\")\nON CONFLICT\nDO UPDATE SET\nname = EXCLUDED.name\nRETURNING playerId"
  - arguments : nil
  - publicStatementArguments : false
`

**Comment by songzhiming** [comment]
> > @groue  how i get return playerid array
> > ```
> > 
> > let sql = """
> > 
> > INSERT INTO Player(name, type, source)
> > 
> > VALUES
> > 
> > ("nihao", 1, "a"),
> > 
> > ("nihao", 2, "b"),
> > 
> > ("nihao", 3, "a")
> > 
> > ON CONFLICT
> > 
> > DO UPDATE SET
> > 
> > name = EXCLUDED.name
> > 
> > RETURNING playerId
> > 
> > """
> > ```
> 
> Fetch player ids:
> 
> ```swift
> let playerIds = try String.fetchAll(db, sql: """
>     INSERT ...
>     """)
> ```

it cause error 
`Playground execution terminated: An error was thrown and was not caught:
▿ SQLite error 1: no such column: nihao - while executing `INSERT INTO Player(name, score, source)`
code 
`// To run this playground, select and build the GRDB scheme.

import GRDB

var configuration = Configuration()
configuration.prepareDatabase { db in
    db.trace { print("SQL> \($0)") }
}
let dbQueue = try DatabaseQueue(configuration: configuration)

struct Player: Codable, FetchableRecord, MutablePersistableRecord {
    var id: Int64?
    var name: String
    var score: Int
    var source: Int
    
    mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}

try dbQueue.write { db in
    try db.create(table: "player") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
        t.column("score", .integer).notNull()
        t.column("source", .integer).notNull()
        t.uniqueKey(["score","source"])
    }
    
    do {
        let sql = """
        INSERT INTO Player(name, score, source)
        VALUES
        ("nihao", 1, "a"),
        ("nihao", 2, "b"),
        ("nihao", 3, "a")
        ON CONFLICT
        DO UPDATE SET
        name = EXCLUDED.name
        RETURNING id
        """
        let playerIds = try Int.fetchAll(db, sql: sql)
        print(playerIds)
    }

}
`

**Comment by songzhiming** [comment]
> > @groue  how i get return playerid array
> > ```
> > 
> > let sql = """
> > 
> > INSERT INTO Player(name, type, source)
> > 
> > VALUES
> > 
> > ("nihao", 1, "a"),
> > 
> > ("nihao", 2, "b"),
> > 
> > ("nihao", 3, "a")
> > 
> > ON CONFLICT
> > 
> > DO UPDATE SET
> > 
> > name = EXCLUDED.name
> > 
> > RETURNING playerId
> > 
> > """
> > ```
> 
> Fetch player ids:
> 
> ```swift
> let playerIds = try String.fetchAll(db, sql: """
>     INSERT ...
>     """)
> ```

it not ok  cause error 
![image](https://github.com/groue/GRDB.swift/assets/7426040/a5ce540f-5098-4555-b395-630219736763)

**Comment by songzhiming** [comment]
db table 
![image](https://github.com/groue/GRDB.swift/assets/7426040/6d5bf6dd-6c9e-4584-b9cc-9e1df6784aad)
sql

**Comment by groue** [comment]
Yes, because this is invalid SQL. String literals must be wrapped in single quotes (`'nihao'`) instead of double quotes.

**Comment by songzhiming** [comment]
> Yes, because this is invalid SQL. String literals must be wrapped in single quotes (`'nihao'`) instead of double quotes.

I got,thanks
