### ISSUE TITLE
Custom sqllite version 

### ISSUE THREAD

**Issue by EnjoyWT** [groue/GRDB.swift#1458]
### What did you do?
I would like to take this opportunity to sincerely thank you for your open-source contributions to the community. there is a tokenizer project (https://github.com/wangfenjin/simple) has been immensely helpful for my work, especially in conducting Chinese text queries using FTS5. Despite the absence of detailed integration documentation, your project has provided me with a valuable starting point.

While attempting to integrate your tokenizer, I encountered some challenges, particularly regarding compatibility issues with GRDB and the version of SQLite , but due to my limited understanding of C++, I faced difficulties in modifying GRDB to accommodate this version.

### What did you expect to happen?
 hope that the plugin at https://github.com/wangfenjin/simple can be used with GRDB. However, the 'simple' plugin uses sqlite3_auto_extension. I would like to know how to use the sqlite3_auto_extension function in GRDB.

### What happened instead?
The SQLite library included in iOS no longer supports the sqlite3_auto_extension function. Now, to replace the SQLite version with https://github.com/clemensg/sqlite3pod, which allows for custom registration, is necessary.

### Environment

**GRDB flavor(s):** custom SQLite build
**GRDB version: laster
**Installation method:** CocoaPods
**Xcode version:** 14.3.1
**Swift version:** 5.0
**Platform(s) running GRDB:** (OS
**macOS version running Xcode:** 13.3 (22E252)

### Demo Project

**Comment by EnjoyWT** [comment]
"Is there a way to use it like this? I want to use SQLite.swift. I find GRDB.swift more elegant.“
> pod 'SQLite.swift', :subspecs => ['standalone'] # Do not use the system-provided SQLite.

**Comment by groue** [comment]
Hello @EnjoyWT,

Here is my understanding of your issue:

1. You want to use https://github.com/wangfenjin/simple with GRDB
2. This tokenizer documents that it requires `sqlite3_auto_extension`.
3. `sqlite3_auto_extension` is not available with the default SQLite version shipped on iOS.

Do I understand well? I assume that you did check both (2) and (3) assertions. If you are not sure of them with total certainty, you may be on the wrong track.

In order to solve this problem, you want to use GRBD with a custom SQLite build. This custom build would come with `sqlite3_auto_extension`, and allow you to use wangfenjin/simple. Did I get this right?

Did you check the [Custom SQLite Builds](https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md) GRDB documentation?

**Comment by EnjoyWT** [comment]
Thank you very much for your prompt response. I've attempted multiple times, and you assume that (2) and (3) are correct. Although I've consulted the documentation before reaching out, I'm still grappling with the integration of a standalone SQLite version. I'm relatively new to SQLite, but I'll make another attempt to integrate it. I truly appreciate your assistance.

Regarding "CustomSQLiteBuilds," is it intended for building a specific version of "GRDB"? If so, can I use it like this?

`
import sqlite3 // installed via pod
import GRDB

let dbQueue = try DatabaseQueue(...)
`
Is this correct? I'll give it a try. 
Thank you once again for your help.

**Comment by groue** [comment]
The linked technique for building GRDB with a custom SQLite build does not use CocoaPods. If you want to use GRDB with a custom SQLite build and CocoaPods, you're out of the documented and supported techniques.

I do not say this is impossible. I just say this is out of the documented frame.

If you don't know how to use GRDB with a custom SQLite build and CocoaPods, I suggest you follow the documented technique instead.

**Comment by groue** [comment]
I'm closing this issue, since there's not much to add.

**Comment by Fr3027** [comment]
> Thank you very much for your prompt response. I've attempted multiple times, and you assume that (2) and (3) are correct. Although I've consulted the documentation before reaching out, I'm still grappling with the integration of a standalone SQLite version. I'm relatively new to SQLite, but I'll make another attempt to integrate it. I truly appreciate your assistance.
> 
> Regarding "CustomSQLiteBuilds," is it intended for building a specific version of "GRDB"? If so, can I use it like this?
> 
> ` import sqlite3 // installed via pod import GRDB
> 
> let dbQueue = try DatabaseQueue(...) ` Is this correct? I'll give it a try. Thank you once again for your help.

大佬您好，我也碰到了同样的问题，自带的sqlite不支持sqlite3_auto_extension，您解决了吗？
