### ISSUE TITLE
Are submodules missing from documentation?

### ISSUE THREAD

**Issue by kimash** [groue/GRDB.swift#146]
I have inherited a project that uses this library. The creator of this project followed your original instructions and installed it within the project via download. I changed this so that now it is a submodule within the project. However, I just discovered today that the project itself contains submodules (SqlCipher/src and SqlLiteCustom/src). When you download it, the submodules are missing (i.e. there's nothing in the src folders above), and they are missing unless you clone them recursively. It seems to work without them, but I'm wondering whether this will cause issues in the future. Is this what you intended? If not, please update your documentation to advise users to `git clone --recursive`.

**Comment by groue** [comment]
Hello @kimash,

> I have inherited a project that uses this library.

Lucky you!

GRDB documentation is kept up-to-date (one of the reasons why you are lucky), reflect my intent, and are accurate, as far as I know, regarding installation instructions.
