### ISSUE TITLE
raw SQL  can support   insert array？

### ISSUE THREAD

**Issue by songzhiming** [groue/GRDB.swift#1461]
### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Please open another issue and don't forget to fill the template this time:

- What did you do?
- What did you expect to happen?
- What happened instead?
