### ISSUE TITLE
Catch a `recordNotFound` error when using `MutablePersistableRecord.save(db)` to update or insert.

### ISSUE THREAD

**Issue by Asura19** [groue/GRDB.swift#1465]
### What did you do?

![CleanShot 2023-12-05 at 23 27 12@2x](https://github.com/groue/GRDB.swift/assets/13399701/b317bb80-e877-4a8d-8bf4-29f81271ddd9)

![CleanShot 2023-12-05 at 23 49 39@2x](https://github.com/groue/GRDB.swift/assets/13399701/3c384c2c-d4e8-4d89-b8d8-96850a777ca3)

When I saving a record (a chat message), actually insert a new message to database, I got a recordNotFound error, but it did insert successfully (I have checked the database file), it looks like the `updateOrInsertAndFetchWithCallbacks` does not catch `recordNotFound` successfully

### What did you expect to happen?

No `recordNotFound` error was throw out when save a new record. 
It happened sometime, NOT every  saving action

### What happened instead?

`recordNotFound` occurred when saving.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @Asura19,

That's odd indeed. Would you please provide a reproducing sample code that would help identifying the problem?

**Comment by groue** [comment]
Having a second look at your screenshot, you can see that the highlighted line (line 384) in your screenshot is an error that is thrown, and caught, inside the GRDB runtime. It is not the sign of any problem.

If you happen to run your app in Xcode with a breakpoint on errors, you might well detect such errors. But you can ignore them, because they are not thrown to your application code.

**Comment by groue** [comment]
@Asura19 Could it be that there is a conflict between the names `message` and `Message`?

**Comment by groue** [comment]
No news is good news, I suppose you were able to resolve your issue, whatever it is. If you think your resolution could solve similar problems for other GRDB users, please share your experience!
