### ISSUE TITLE
Issue with having in fetch query

### ISSUE THREAD

**Issue by ahartman** [groue/GRDB.swift#1469]
### What did you do?

I am fetching patients and their visits in a given timeframe; I want to filter out patients that have no visits in that timeframe.
I tried two different clauses to limit the records fetched but with no effect.
Filtering in Swift after the fetch does work OK.
What am I doing wrong?

```
struct PatientInfo: Codable, Hashable, FetchableRecord {
    var id: Int?
    var patientName: String
    var patientLatitude: CLLocationDegrees?
    var patientLongitude: CLLocationDegrees?
    var visits: [Visit]
}

struct Patient: Codable, Hashable, FetchableRecord, MutablePersistableRecord, TableRecord, EncodableRecord {
    var id: Int?
    var createdDate: Date?
    var modifiedDate: Date?
    var patientName: String
    var patientLatitude: CLLocationDegrees?
    var patientLongitude: CLLocationDegrees?
    static let visits = hasMany(Visit.self)
}

struct Visit: Codable, Hashable, FetchableRecord, MutablePersistableRecord, TableRecord, EncodableRecord {
    var id: String
    var createdDate: Date?
    var modifiedDate: Date?
    var visitAge: Int
    var visitCalendar: String
    var visitCreated: Date
    var visitDate: Date
    var visitFirst: Bool
    var visitWeekDate: Date
    var patientID: Int
    static let patient = belongsTo(Patient.self)
}

do {
            var patientInfo = [PatientInfo]()
            try dbQueue.read { db in
                patientInfo = try Patient
                    .including(all: Patient.visits
                        .filter(Column("visitDate") >= dates.start)
                        .filter(Column("visitDate") <= dates.end)
                        .filter(Column("modifiedDate") < writeDate)
                    )
                    .having(Patient.visits.isEmpty == false)
                    .having(Patient.visits.count > 0)
                    .asRequest(of: PatientInfo.self)
                    .fetchAll(db)
            }
            patientInfo = patientInfo.filter {$0.visits.count > 0}
        } catch {
            fatalError("Unresolved error \(error)")
        }
```

### What did you expect to happen?

I expected fetching only patients that have visits in the given timeframe.

### What happened instead?

All patients are fetched, including those with no visits. both different having clauses have no effect.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version: master
**Installation method: package
**Xcode version:14.2
**Swift version: 5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode: 12.7.1

**Comment by groue** [comment]
Hello @ahartman,

Rewrite your code as below:

```swift
let patientInfo: [PatientInfo] = try dbQueue.read { db in
    let filteredVisits = Patient.visits
        .filter(Column("visitDate") >= dates.start)
        .filter(Column("visitDate") <= dates.end)
        .filter(Column("modifiedDate") < writeDate)
    return try Patient
        .including(all: filteredVisits)
        .having(filteredVisits.isEmpty == false)
        .asRequest(of: PatientInfo.self)
        .fetchAll(db)
}
```

The difference with your initial code is that the `having` clause focuses on the filtered visits, not **all** patient's visits (`Patient.visits`).

**Comment by ahartman** [comment]
Dear Gwendal,

Thank you for the quick answer.
This is a novel approach that I did not see in the documentation.

Je te souhaite un joyeux Noël et une bonne année 2024.


Kind regards, André Hartman

**Comment by groue** [comment]
Merci André :-) Joyeux Noël à toi aussi!

**Comment by ahartman** [comment]
Dear Gwendal,

Your solution works fine; however, I do not understand the syntax at all and I can find nothing comparable in your documentation.
Maybe this is an advanced topic but I think it would be useful for many if you explained with an example in your blog or documentation.
Thank you for the solution.




Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by groue** [comment]
You have a similar example in the [Filtering a Request with Aggregates](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#filtering-a-request-with-aggregates) section:

> Authors who wrote at least one book of kind "novel":
>
> ```swift
> let novels = Author.books.filter(Column("kind") == "novel")
> let request = Author.having(novels.isEmpty == false)
> ```
