### ISSUE TITLE
`databaseDateEncodingStrategy` not wok when update a existing record

### ISSUE THREAD

**Issue by Asura19** [groue/GRDB.swift#1470]
```
final class Player: Identifiable {
    var id: Int64?
    var name: String
    var score: Int = 0
    var date: Date
}
extension Player: Codable, FetchableRecord, MutablePersistableRecord {
    // Define database columns from CodingKeys
    enum Columns {
        static let id = Column(CodingKeys.id)
        static let name = Column(CodingKeys.name)
        static let score = Column(CodingKeys.score)
        static let date = Column(CodingKeys.date)
    }
    
    /// Updates a player id after it has been inserted in the database.
    func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
    public static let databaseDateEncodingStrategy = DatabaseDateEncodingStrategy.iso8601
}
```
I have inserted a record, and its date column is a iso8601 format date string,  but when update record, the date column become the default format string

```
func update(player: Player) throws {
        try dbWriter.write { db in
            try Player
                .filter(Column("id") == player.id)
                .updateAll(
                    db,
                    Column("date").set(to: Date())
                )
        }
    }
```

I have to format by myself like:
```
Column("date").set(to: Date().iso8601String)
```

### What did you expect to happen?

Automatically transform Date using my config `databaseDateEncodingStrategy`

### What happened instead?

A default format date string is saved via `SQLExpressible`

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version: 6.21.0
**Installation method:CocoaPods
**Xcode version:15.1
**Swift version:5.9
**Platform(s) running GRDB: iOS
**macOS version running Xcode:14.2

**Comment by groue** [comment]
Hello @Asura19,

> I have to format by myself like:

Yes. I know it's not ideal, but that's the way to do it. See, in particular, https://github.com/groue/GRDB.swift/issues/1412#issuecomment-1663315096
