### ISSUE TITLE
Throwing subscript Row value

### ISSUE THREAD

**Issue by Craz1k0ek** [groue/GRDB.swift#1471]
### What did you do?
I tried to decode an object from a row using the `FetchableRecord` type, and figured out that the subscript of that type has a force try in the implementation.

### What did you expect to happen?
I would expect the subscript to be throwing, as this is possible since [Swift 5.5](https://github.com/apple/swift-evolution/blob/main/proposals/0310-effectful-readonly-properties.md). An example implementation of that would look like can be this:
```swift
// Updated around line 437 from the Row.swift file
@inlinable
subscript<Value: DatabaseValueConvertible & StatementColumnConvertible>(_ columnName: String) -> Value {
    get throws {
        try decode(Value.self, forKey: columnName)
    }
}
```

This way, when trying to decode and something fails, this will not cause the app to crash. The developer is now responsible, but more importantly, able to handle this error, i.e.:

```swift
init(row: Row) throws {
    self.id = try row["id"]
    self.name = try row["name"]
}
```

### What happened instead?
Misusage or invalid column names or indices, caused the app to crash instead.

### Environment
**GRDB flavor(s):** GRDB
**GRDB version:** 6.23.0
**Installation method:** SPM
**Xcode version:** 15.1
**Swift version:** 5.9.2
**Platform(s) running GRDB:** iOS (simulator)
**macOS version running Xcode:** 14.1.2

### Demo Project
```swift
import Foundation
import GRDB

struct User: Codable, Identifiable {
    var id: Int
    var name: String

    init(id: Int, name: String) {
        self.id = id
        self.name = name
    }
}

extension User: FetchableRecord {
    public init(row: Row) throws {
        id = row["id"]
        name = row["namee"] // <-- namee ≠ name, I know, programmer error, but still...
    }
}

extension User: PersistableRecord {}

struct ThrowingTest {
    let database: GRDB.DatabaseWriter

    func run() throws {
        // Apply user migration
        var migrator = DatabaseMigrator()
        migrator.registerMigration("create_user") { database in
            try database.create(table: "user") { table in
                table.primaryKey("id", .integer)
                table.column("name", .text)
            }
        }
        try migrator.migrate(database)

        try database.write { database in
            try User.deleteAll(database)

            let insert = User(id: 123, name: "Thomas")
            try insert.save(database)

            let select = try User.fetchOne(database, id: 123) // <-- This will crash, due to the init(row:) error
            print(select)
        }
    }
}
```

**Comment by groue** [comment]
Hello @Craz1k0ek,

Things would have been different if the library had been born after Swift 5.5. But the `Row` subscript was introduced far before, and I'm reluctant to change apis unless necessary.

And I'm not sure it is necessary. That throwing subscript is not missed. There is no user demand for `try row["name"]`.

You actually describe the situation pretty well:

```swift
name = row["namee"] // <-- namee ≠ name, I know, programmer error, but still...
```

I agree, it is a programmer error. And a crash is a valid answer.

More seriously, the library has always assumed that it deals with trusted local database. Dealing with untrusted databases requires more work. See [Advice for failable record initialisation](https://forums.swift.org/t/advice-for-failable-record-initialisation/37385) for a longer discussion.

In the end: the topic is not closed, and I'm keen to ear good arguments for a throwing subscript. It just happens that turning programmer errors into runtime errors is not one of them :-)

**Comment by Craz1k0ek** [comment]
@groue thanks for your reply. I agree with your comment and I am aware of the fact that this could be a breaking change. We could opt in for additional syntax on the subscript i.e.:

```swift
@available(swift, introduced: 5.5)
@inlinable
public subscript<Value: DatabaseValueConvertible & StatementColumnConvertible>(column columnName: String) -> Value {
    get throws {
        try decode(Value.self, forKey: columnName)
    }
}

// Usage example

let name: String = try row[column: "name"]
```
This way, the existing API should be unaffected and the requested functionality still does become available.

Additionally, after further looking around, I also found the `decode` functions on the `Row` such as this one:
```swift
// Example from line 1025
func decode<Value: DatabaseValueConvertible>(
        _ type: Value.Type = Value.self,
        forKey columnName: String)
    throws -> Value
```

Would it be an idea to open up this API by marking these functions (and alike functions) `public`. This should, as far as I can tell, not break the API. This has two nice to haves:

1. The requested behaviour in the original question is answered, albeit through a different syntax, but it's there. I.e. one can use `row.decode(String.self, forKey: "name")`.
2. The syntax is very similar as to how the `Codable` protocol is implemented by Apple. This way, the usage of the `Row` object is easy to understand for any programmer, as most of us have been using `Codable` in some way or form for JSON. I guess that's also why the `FetchableRecordDecoder` has been made available publicly, as this suits the syntax very well.

**Comment by groue** [comment]
> I would like to be able to manage the database remotely as well, by allowing migrations, table definitions and such to be downloadable. This would require the subscript of the tables to be done dynamically, but you can image there's room for error when doing things like that.

This is a valid use case 👍

> Additionally, after further looking around, I also found the `decode` functions on the `Row` such as this one:
>
> ```swift
> func decode<Value: DatabaseValueConvertible>(
>     _ type: Value.Type = Value.self,
>     forKey columnName: String)
> throws -> Value

Thanks for your suggestion. Yes, those methods are the ones you are looking for :-) They look similar to `Codable` api indeed, because I needed some inspiration ;-)

If public, your initial sample code would be turned into:

```swift
extension User: FetchableRecord {
    public init(row: Row) throws {
        id = try row.decode("id")
        name = try row.decode("name")
    }
}
```

It's not just a matter of making them public, though. The `RowDecodingError` type should probably be made public as well, so that your app that manages a remote database would be able to catch this error and react accordingly.

It's currently a dump of everything needed to produce error messages, and wasn't vetted for public consumption. Since you are interested, it would be helpful if you could tell what you expect from this type!

**Comment by groue** [comment]
> I would like to be able to manage the database remotely as well, by allowing migrations, table definitions and such to be downloadable.

Now that I think more about it, you will probably meet other issues on the way. In particular, record types are linked to a specific table, and the Swift language does not make it possible to dynamically define types. We can say that GRDB is tailored for well-defined schemas, and has not much provision for dynamic ones.

In conclusion: maybe the need for throwing accessors will become pressing, but I'm not sure we're quite there yet. I'm closing this issue. We'll have other opportunities to discuss about the topic.

**Comment by Craz1k0ek** [comment]
> the Swift language does not make it possible to dynamically define types
This is exactly the issue I ran into. It might be worth revisiting once I end up trying to create an ORM backed by SQLite/GRDB. Thanks for your time and effort nevertheless!

**Comment by groue** [comment]
Another user who would have appreciated throwing accessors: https://x.com/dexterleng/status/1799387272221212759
