### ISSUE TITLE
Linker error when building for watchOS with Address Sanitizer enabled

### ISSUE THREAD

**Issue by PawanYr** [groue/GRDB.swift#1472]
### What did you do?

Created a new iOS project, added Apple Watch as a target platform, added GRDB as a dependency, enabled Address Sanitizer, and attempted to build.

### What did you expect to happen?

For the project to build successfully.

### What happened instead?

Build failed with error "Scattered reloc r_address too large for architecture i386"
![image](https://github.com/groue/GRDB.swift/assets/73249962/4b72ac43-d9f4-47be-af45-a2a624b1a4fb)

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.23.0
**Installation method:** Add package dependency -> entered GitHub URL -> added as dependency
**Xcode version:** 15.0
**Swift version:** 5.9
**Platform(s) running GRDB:** watchOS
**macOS version running Xcode:** 14.1.1 (M1)

### Demo Project

[Test.zip](https://github.com/groue/GRDB.swift/files/13710482/Test.zip)

**Comment by groue** [comment]
Hello @PawanYr,

I'm surprised about the presence of the i386 architecture in your error message. I'm not sure GRDB has to deal with the 32-bit Intel architecture. This means I'm not sure anything has to be done at the level of the library. Did you investigate how to fix this error from your app?

**Comment by PawanYr** [comment]
Hello @groue,

I agree it is quite odd the error references i386, since this was not set as a build architecture for either the iOS or watchOS targets. Even odder is that it only complains if the Address Sanitizer is enabled, and otherwise appears to work perfectly. Anyway, the Test.zip project I have attached is a new project with no changes other than the GRDB dependency being added to the watchOS target; I created it after first encountering this issue in my app with the intention of making sure the issue didn't originate from elsewhere. I would encourage you to try it on a similar environment (M1, Sonoma) and see if you encounter the same issue; if you don't, then it is likely an issue with my environment. Frankly, I am unsure what was causing this, and XCode doesn't seem to provide much useful output. All I can say for sure is that even on a new project like the one I attached, adding GRDB as a watchOS dependency (not iOS; there it works fine) and enabling the Address Sanitizer causes the screenshotted error. 

Please let me know if there is anything you would like me to test/check.

**Comment by PawanYr** [comment]
Regarding EXCLUDED_ARCHS, I have already given that a try and unfortunately it made no difference. For anyone else encountering this issue, the only thing that has worked for me thus far is to maintain a separate branch where all usage of GRDB in the watchOS target is removed, along with the dependency in the target.

If you believe this isn't a problem with GRDB, please do close this issue at your discretion; I will file with Apple and update here if there is any change in case others end up here via Google.

**Comment by groue** [comment]
Thank you for sharing your workaround, even if it is quite less than ideal 👍

There is no evidence that there is an issue in the library that needs to be fixed, so I'm indeed closing the issue.

**Comment by PawanYr** [comment]
Update: Apple has replied with the following:

> It is correct that Xcode builds for i386 in this case because GRDB declares a watchOS 4 deployment target which implies i386 support in the simulator. We would recommend updating the minimum deployment target to watchOS 7 or later to resolve this problem.

So for anyone wondering, the old watchOS target for GRDB in the Package.swift is why this is occurring. Assuming @groue wishes to maintain this target in Package.swift, I guess the solution then would just be to not use SPM.

**Comment by groue** [comment]
Thank you very much for this information, @PawanYr 👍 Given GRDB 7 is in the pipes, I will be able to introduce a breaking change such as raising the minimum watchOS target.
