### ISSUE TITLE
Conflicting Database.logError ?

### ISSUE THREAD

**Issue by gmoraleda** [groue/GRDB.swift#1473]
### What did you do?

I've updated my device to iOS 17.2. Ever since I've started to see errors that are not coming from my DB schema.

### What did you expect to happen?

Only errors from my DB are reported.
This is my code to log Database errors:
```swift
Database.logError = { [weak self] resultCode, message in
            self?.logger.logError(context: .database, ["DatabaseService": message, "Code": resultCode])
        }
```

### What happened instead?
This error landed in my logs:
```
["DatabaseService": "abort at 27 in [INSERT into cfurl_cache_response (version, hash_value, storage_policy, \t\t\t\t\t\t\t\t\t request_key, partition) VALUES (?, ?, ?, ?, ?);]: UNIQUE constraint failed: cfurl_cache_response.request_key", "Code": 2067 (constraint failed)]
```

I've investigated a bit and that table (`cfurl_cache_response`) seems to be a table used by Safari to cache URL requests.
https://gist.github.com/steipete/2356581

That table is not in my DB schema.

From the top of my heads seems like the Database.logError is capturing errors coming from outside the GRDB domain. If that's the case, namespacing the call should fix the issue, right?

```swift
GRDB.Database.logError = { [weak self] resultCode, message in
            self?.logger.logError(context: .database, ["DatabaseService": message, "Code": resultCode])
        }
```

Have you experienced this before?

Thanks in advance!

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.22
**Installation method:** SPM
**Xcode version:** 14.2
**Swift version:**
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 13.5.2 (22G91)

**Comment by gmoraleda** [comment]
That makes a lot of sense.
Thanks a lot for your comprehensive reply @groue!

**Comment by groue** [comment]
You're welcome! Happy GRDB :-)
