### ISSUE TITLE
@CodedBy and ValueCoder Issues

### ISSUE THREAD

**Issue by jlcanale** [groue/GRDB.swift#1484]
I'm trying to use the `@CodedBy` macro with the provided `ValueCoder` but whatever I try, Xcode gives me the error "Cannot find 'ValueCoder' in scope".  

I am able to successfully use `@Codable` and `@CodedAt`, so I know the package is properly referenced in Xcode. 

Are there any examples of how to use @CodedAt with the provided coders, or any direction as to what I might be missing here?

Here's the code for the struct I'm trying to decode.

```
public struct Item {

    @CodedAt("itemid")
    public let id: Int

    @CodedAt("walmart_id")
    public let walmartId: String

    @CodedBy(ValueCoder<Int>)
    public let name: Int

    @CodedAt("images", "original")
    public let imageUrl: String
}

```

**Comment by groue** [comment]
Hello @jlcanale,

Shouldn't this issue be opened in the repository that defines `ValueCoder`, `@CodedBy`, etc? 😉

**Comment by jlcanale** [comment]
Oh shoot, I hav no idea how I even got this far.  I'm so sorry about this.

**Comment by groue** [comment]
Have a nice day :-)
