### ISSUE TITLE
Add date time column with default as current date

### ISSUE THREAD

**Issue by bonro001** [groue/GRDB.swift#1491]
Hello all,

What I hope is a simple question.  I want to do a migration that adds a column to a table of type date.  Wanting this to have always have a default value of the current date.

Is there a way to do this in GRDB migrations?

Thank you in advance!

**Comment by groue** [comment]
Hello @bonro001, 

Maybe have a look at #1475, which is related if not identical.

**Comment by groue** [comment]
No news is good news, I'm closing the issue.
