### ISSUE TITLE
Fatal Error with Spatialite: could not decode String from database value NULL

### ISSUE THREAD

**Issue by Tybion** [groue/GRDB.swift#1499]
Hello, Gwendal.

Running this ..
```
        do {
            try dbQueue!.inDatabase { db in
                let rows = try Row.fetchCursor(db, sql: sql, arguments: [])
                var count = 0
                while let row = try rows.next() {
                    count += 1
                    print("count=\(count)")
                    let fid = row["\(fidcolumn!)"] as Int
                    let wkt = row["wkt"] as String
```

.. I get this (with the very first row from the table) ..

```
SqlLayer: count=1
GRDB/Row.swift:361: Fatal error: 'try!' expression unexpectedly raised an error: could not decode String
from database value NULL - column: "wkt", column index: 1, 
row: [ogc_fid:1 wkt:NULL title:"Toy Rd Bindoon Lot 7-Area 1 - Gvl"],
sql: `SELECT ogc_fid, AsText(geometryproperty) AS wkt , title AS title FROM wa_construction_materials
 WHERE geometryproperty IS NOT NULL LIMIT 5000`, arguments: []
```          
Ths code is essentially the same as the example working code that I gave you before.  The main difference is that I am trying to process 5,000 rows instead of querying a table that contains only one row.  'AsText(geometryproperty)' returns normal text.

When the app starts I get the following, but don't know what is producing this ..
```
Maps(875,0x202cb3f00) malloc: Unable to set up reclaim buffer (46) - disabling large cache
```

This is probably a difficult one, but if you have any ideas? ..

**Comment by Tybion** [comment]
I just figured that I need to run **spatialite_init_ex** again.
This is working again, and I also found a null title on the 65th row, so now allow for that ..

```
do {
    try dbQueue!.inDatabase { db in

        spatialite_initialize()
        var spconnect: OpaquePointer?
        spatialite_init_ex(db.sqliteConnection, &spconnect, 0)  // NOT verbose
        
        let rows = try Row.fetchCursor(db, sql: sql, arguments: [])
        var count = 0
        while let row = try rows.next() {
            count += 1
            MyUtils.Log(TAG, "count=\(count)")
            let fid = row["\(fidcolumn!)"] as Int
            let wkt = row["wkt"] as String
            let title = row["title"] as? String ?? "no title"
            let geom =  try Geometry(wkt: wkt)
```

**Comment by groue** [comment]
Hello again, @Tybion,

A fatal error is the sign that the Swift code, or the database, has to be changed for the program to be correctly formed.

Here, the message "could not decode String from database value NULL" means that you ask the row for a `String` in the column `wkt`, but the row contains NULL. There is no such thing as a Swift `String` that represents the NULL value. NULL is not the same value as the empty string.

From there, there are several possible solutions, depending on the root problem.

1. If the root problem is that the `wkt` column contains NULL when it should not, then alter your database schema and add a `NOT NULL` constraint to `wkt`. Your program will then fail earlier, when it tries to insert a NULL there, and this is where you will apply the necessary fix.
2. If the root problem is that the program should filter out NULL `wkt` values, then alter the query sql with `WHERE wkt IS NOT NULL`.
3. If the root problem is that the program should be ready for NULL `wkt` values, then alter the `wkt` variable type with: `let wkt = row["wkt"] as String?`. A NULL value will then be decoded as a nil `String?` [optional](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics#Optionals). Alternatively, if you want to process NULL just as if it was the empty string: `let wkt: String = row["wkt"] ?? ""`.

> When the app starts I get the following, but don't know what is producing this ..
>
> ```
> Maps(875,0x202cb3f00) malloc: Unable to set up reclaim buffer (46) - disabling large cache
> ```

I don't know what this means.

**Comment by Tybion** [comment]
Hello, Gwendal.  It seems that you missed reading my **second message** - this has the answer to the problem in my **first message**.  The question is about spatialite and the solution is to run **spatialite_init_ex** again.  I think it is good if you leave 'spatialite' in the issue name so other spatialite+GRDB users find it when searching.
