### ISSUE TITLE
Build errors due to hardcoded paths

### ISSUE THREAD

**Issue by socantre** [groue/GRDB.swift#150]
I get an error during builds due to the hardcoded paths in Support/module.modulemap when Xcode is not installed at /Applications

**Comment by groue** [comment]
Hello @socantre.

Module maps require hard-coded paths. Follow [installation instructions](http://github.com/groue/GRDB.swift#installation), and have Xcode installed in /Applications with its regular name Xcode.

**Comment by socantre** [comment]
This project is being used by another project via Carthage. I'm 'installing' GRDB via `carthage update --platform osx`.

I don't think that eliminating the ability of Xcode to be installed anywhere is appropriate for third party libraries, especially when that requirement is then imposed transitively on projects that depend on GRDB. Relocation is useful functionality and I'm using it for a reason.

Also it's not true that module maps require absolute paths. The problem is that you're not supposed to be defining modules maps for headers you're not in control of at least to the degree that the module map can be co-located with the headers.

Anyway, if nothing else you should at least be able to generate the module map file during the build with the correct path, detected via something like `xcrun --show-sdk-path`.

Call this an enhancement request.

**Comment by groue** [comment]
I'd love to remove the hard-coded absolute paths from this repository.

**Comment by groue** [comment]
In case you'd be doubting, I'm not particularly happy with this hard-coded path.

> Also it's not true that module maps require absolute paths. The problem is that you're not supposed to be defining modules maps for headers you're not in control of at least to the degree that the module map can be co-located with the headers.

I'd love to learn something. Call this a contribution request.
