### ISSUE TITLE
6.25.0 does not support provisioning profiles

### ISSUE THREAD

**Issue by gjmoyer** [groue/GRDB.swift#1506]
### What did you do?

Upgraded reference to GRDB from 6.24.2 to 6.25.0 

### What did you expect to happen?

Compile via XCode with provisioning profile

### What happened instead?

/SourcePackages/checkouts/GRDB.swift/Package.swift: error: GRDB_GRDB does not support provisioning profiles. GRDB_GRDB does not support provisioning profiles, but provisioning profile ....

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 6.25.0
**Installation method: SPM
**Xcode version: 15.3
**Swift version: 15.10
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 13.6.4 (Azure DevOps build agent 3.236.1)

### Demo Project

N/A

**Comment by groue** [comment]
Hello @gjmoyer,

I don't know what you mean by "Compile via XCode with provisioning profile". It's also a pity you didn't copy the entire error message. Who knows what useful information is hidden in your "...." ellipsis?

Maybe try performing the usual Xcode cleanup actions (Product > Clean Build Folder…, delete `~/Library/Developer/Xcode/DerivedData`, etc.)?

And if the problem persists, do you think you could spot, in the [diff between 6.24.2 to 6.25.0](https://github.com/groue/GRDB.swift/compare/v6.24.2...v6.25.0) where the eventual regression was introduced?

**Comment by gjmoyer** [comment]
Sorry, I thought maybe it was an obvious thing. I looked at the diff and I don't see any reason for the error either. This is the full error. I replaced my company name with xxxx, otherwise untouched. This is ran on devops build agent, not locally on my machine. I will try upgrading again to see if I can understand more.

Build description path: /Users/runner/Library/Developer/Xcode/DerivedData/xxxx-egvskiajsfkihbfuartwrltlrrto/Build/Intermediates.noindex/XCBuildData/5b281fb4412ff8387ebe9a3028ec45ff.xcbuilddata

/Users/runner/Library/Developer/Xcode/DerivedData/xxxx-egvskiajsfkihbfuartwrltlrrto/SourcePackages/checkouts/GRDB.swift/Package.swift: error: GRDB_GRDB does not support provisioning profiles. GRDB_GRDB does not support provisioning profiles, but provisioning profile xxxx - 01-04-2025 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'GRDB_GRDB' from project 'GRDB')
** BUILD FAILED **

**Comment by groue** [comment]
> I thought maybe it was an obvious thing.

When it's not obvious to you, why should it be obvious for other people? That makes no sense.

It looks like a Google search for "does not support provisioning profiles" gives interesting results. This is not a GRBD issue.
