### ISSUE TITLE
Cocoapods hasn't published since 6.24.1

### ISSUE THREAD

**Issue by KeithBauerANZ** [groue/GRDB.swift#1522]
Only versions up to 6.24.1 are available in Cocoapods (6.24.2, 6.25.0, 6.26.0 are missing as of time of writing).

(We still need Cocoapods because it seems like SQLCipher isn't supported by Package.swift?)

**Comment by groue** [comment]
Duplicate of #1518

**Comment by groue** [comment]
Since you need SQLCipher, @KeithBauerANZ, please have a look at https://github.com/groue/GRDB.swift/discussions/1495
