### ISSUE TITLE
Privacy Manifest: Entry missing for accessing file timestamps via creationDate API

### ISSUE THREAD

**Issue by twiedow** [groue/GRDB.swift#1525]
As far as I can see the file PrivacyInfo.xcprivacy should contain an entry for accessing file timestamps via creationDate API. Currently the file does not declare any APIs. Is this correct?

[NSPrivacyAccessedAPICategoryFileTimestamp](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393)

**Comment by groue** [comment]
Hi @twiedow,

I'm surprised. Where do you see an access to file timestamps in GRDB source code?

**Comment by twiedow** [comment]
Sorry, my fault. I used a script which scanned for symbols which might be used and which might be needed to be declared. It had a false-positive on creationDate which used in GRDB but in SQL statements.

**Comment by groue** [comment]
Thank you for your time, @twiedow, this is appreciated :-)
