### ISSUE TITLE
Avoid conflict with other SPM packages by renaming the CSQLite SPM target

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#1528]
As reported by @jegnux, the SPM target "CSQLite" conflicts with other SPM packages such as [SQLiteNIO](https://github.com/vapor/sqlite-nio/blob/1.8.7/Package.swift#L28). This prevents users from sharing server and client code in a single SPM package, and generally makes life more complicated than desired.

Maybe this will be solvable at the SPM level at some point ([I'm not holding my breath](https://forums.swift.org/t/multiple-target-issue-with-spm/16696)), but currently it is just not possible. I don't see how this can be solved unless packages publish namespaced targets: `CSQLite` -> `GRDBCSQLite` or `GRDB_CSQLite`.

Since this is a breaking change for existing apps, this renaming will happen in GRDB 7.

**Comment by haIIux** [comment]
Is there a work around or am I using the improper branch? I'm using the `master` branch for my project and I'm getting what _I believe_ is the same error?

> Unable to resolve build file: BuildFile<PACKAGE-TARGET:GRDB-5DC4DB053-dynamic::BUILDPHASE_1::0> (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:CSQLite')
