### ISSUE TITLE
Segmentation fault in Release build, Xcode Version 8.0 (8A218a)

### ISSUE THREAD

**Issue by melsomino** [groue/GRDB.swift#153]
Release build of GRDBiOS caused swift compiler to crash with "Segmentation fault".
Problem in FetchedRecordsController.swift:
1) public func setRequest(_ request: FetchRequest) throws
2) public func trackChanges<T>(
        fetchAlongside: @escaping (Database) throws -> T,
        recordsWillChange: ((FetchedRecordsController<Record>, _ fetchedAlongside: T) -> ())? = nil,
        tableViewEvent: ((FetchedRecordsController<Record>, Record, TableViewEvent) -> ())? = nil,
        recordsDidChange: ((FetchedRecordsController<Record>, _ fetchedAlongside: T) -> ())? = nil)

When I comment part of code in this methods, which use "databaseWriter.write { db in ... }", compilation succeeded.

**Comment by melsomino** [comment]
Fixed in Xcode 8.1

**Comment by groue** [comment]
I should update the documentation and require Xcode 8.1+
