### ISSUE TITLE
Weird db read issue

### ISSUE THREAD

**Issue by ahartman** [groue/GRDB.swift#1539]
Execute read query filtering on a column == nil

Retrieve only records with filtered nil value

Some records are included as with nil value although they contain a real value in that column

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** Master
**Installation method:** Package
**Xcode version:** latest
**Swift version:** 5
**Platform(s) running GRDB:** macCatalyst
**macOS version running Xcode:** latest

### Demo Project

I attach a screen image.

<img width="1473" alt="Scherm­afbeelding 2024-05-01 om 12 04 17" src="https://github.com/groue/GRDB.swift/assets/688316/e22e54b3-0778-4f1c-aaed-fc7ebd992d38">

You can see the query in 'getNoGeoPatients', part of the results below there and the db records on the left.
Please observe:
Record 14 ' Allessandro Tina' is not retrieved as it contains a value for patientLatitude
Record 17 'Allard Veronique' is retrieved with nil for patientLatitude and nil for patientLongitude, although the database contains values for patientLatitude and patientLongitude. 

Total mystery for me, I hope you have an idea.
Regards, André Hartman

**Comment by groue** [comment]
Hello @ahartman, welcome back.

Probably the application on the right of the screenshot does not fetch values from the database displayed on the left. Or maybe the database was modified since the DB Browser has performed its last fetch.

**Comment by ahartman** [comment]
Dear Gwendal,

I deleted my issue again but you already read it.
It is indeed that the db has changed compared to the screen image.
I wil find out on my own as it must be in my code.
Nice job for a national holiday today.

Regards, André Hartman

**Comment by ahartman** [comment]
I found the issue and you may be interested.
I create a tabel as below:
```
try db.write { db in
                try db.create(table: "patient", ifNotExists: true) { t in
                    t.autoIncrementedPrimaryKey("id")
                    t.column("patientName", .text)
                        .indexed()
                        .unique()
                        .notNull()
                    t.column("patientLatitude", .real)
                        .indexed()
                    t.column("patientLongitude", .real)
                }
            }
```

**Comment by groue** [comment]
> I forgot to update the corresponding column names in the function updateDBFromPatients, so in the function there are still latitude and longitude as column names.

To prevent this kind of programmer error, I tend to define column constants. Often I derive columns constants from CodingKeys, which are compiler-generated for Codable records. They make sure no such mistep can happen:

```swift
struct Patient: Codable {
  var patientLatitude: CLLocationDegrees
  var patientLongitude: CLLocationDegrees
}

extension Patient: TableRecord {
  // Derive Column constants from CodingKeys.
  // Those automatically detect renamed properties.
  enum Columns {
    static let patientLatitude = Column(CodingKeys.patientLatitude)
    static let patientLongitude = Column(CodingKeys.patientLongitude)
  }

  // Possible alternative for non-Codable records.
  // Those do not automatically detect renamed properties, though.
  enum Columns: String, ColumnExpression {
    case patientLatitude, patientLongitude
  }
}
```

The upsert would then read:

```swift
func updateDBFromPatients(patients: [PatientInfo], dates: PeriodStartEnd) {
  ...
  tempPatient = try tempPatient.upsertAndFetch(
    db, onConflict: ["patientName"],
    doUpdate: { _ in
      [Patient.Columns.patientLatitude.noOverwrite,
       Patient.Columns.patientLongitude.noOverwrite]
    }
  )
  ...
}
```

When I'm bothered by the long column names, I sometimes define a private typealias in the file that needs them:

```swift
private typealias PColumns = Patient.Columns

func updateDBFromPatients(patients: [PatientInfo], dates: PeriodStartEnd) {
  ...
  tempPatient = try tempPatient.upsertAndFetch(
    db, onConflict: ["patientName"],
    doUpdate: { _ in
      [PColumns.patientLatitude.noOverwrite,
       PColumns.patientLongitude.noOverwrite]
    }
  )
  ...
}
```

**Comment by groue** [comment]
> The weird thing is there are no errors or warnings about using column names (latitude and longitude) that do not exist in the table.

😬 This is because columns which are not overwritten are not present in the generated UPSERT SQL query. That's probably a sub-optimal GRDB api.

**Comment by groue** [comment]
> That's probably something GRDB could detect...

Yes, that is possible. We could enhance GRBD so that it throws some kind of "no such column" error. I'm adding this to the TODO list.

**Comment by ahartman** [comment]
Dear Gwendal,

I think it is more something that SQLite should detect in a submitted query with columns that do not exist.

Regards, André Hartman
