### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by ajkiosd** [groue/GRDB.swift#154]
please add tvOS support. thanks

**Comment by groue** [comment]
Do you feel like doing it yourself and submit a PR?

**Comment by groue** [comment]
No news, closing.

**Comment by iDad** [comment]
I was trying (I only found this thread yesterday). I'm getting hung up on the Module Map. I get an error in the generated unextended-module.modulemap file on this:

module GRDBtvOS.__Swift {
    exclude header "GRDBtvOS-Swift.h"
}

I know its getting generated as I haven't added that anywhere. I even temporarily renamed my Xcode from Xcode8.2 to Xcode so I didn't have to modify the module.modulemap at all.

I must say while I'm pretty good at Swift, module maps are something I normally avoid like the plague.

**Comment by iDad** [comment]
I've made it past the module map issues and now I'm working through compile issues.

Andrew

**Comment by iDad** [comment]
Update: Its compiling. Now to see if it lives and bring up the tests.

**Comment by akbsteam** [comment]
Did you get anywhere with this?
