### ISSUE TITLE
Error for query count grouped

### ISSUE THREAD

**Issue by ahartman** [groue/GRDB.swift#1540]
### What did you do?

Tried selecting counts, grouped by a column

### What did you expect to happen?

Counts by column

### What happened instead?

Error: Agenda_Assistent/DBModel.swift:169: Fatal error: column not found: "id" - row: [visitDate:"2017-01-03 18:00:00.000" COUNT("visitAge"):1], sql: `SELECT "visitDate", COUNT("visitAge") FROM "visit" GROUP BY "visitDate"`, arguments: []

### Environment

**GRDB flavor(s): GRDB
**GRDB version: master
**Installation method:  SPM
**Xcode version: latest
**Swift version: 5
**Platform(s) running GRDB: macCatalyst
**macOS version running Xcode: latest

### Demo Project

As always, the question is: what am I doing wrong?

I have the following struct, table and query:
```
struct Visit: Codable, Hashable, FetchableRecord, MutablePersistableRecord {
    var id: String
    var modifiedDate: Date?
    var visitAge: Int
    var visitCalendar: String
    var visitCanceled: Bool
    var visitCreated: Date
    var visitDate: Date
    var visitFirst: Bool
    var visitNoShow: Bool
    var visitRecurrent: Bool
    var visitPatientName: String
    var patientId: Int
}
```

```
try db.write { db in
                try db.create(table: "visit", ifNotExists: true) { t in
                    t.column("id", .text)
                        .primaryKey()
                        .indexed()
                    t.column("modifiedDate", .text)
                        .indexed()
                    t.column("visitAge", .integer)
                    t.column("visitCalendar", .text)
                        .indexed()
                    t.column("visitCreated", .text)
                    t.column("visitCanceled", .boolean)
                    t.column("visitDate", .text)
                        .indexed()
                    t.column("visitFirst", .boolean)
                    t.column("visitNoShow", .boolean)
                    t.column("visitRecurrent", .boolean)
                    t.column("visitPatientName", .text)
                    t.belongsTo("patient", onDelete: .cascade)
                }
            }
```

```
func getVisitAges() -> [Visit] {
        var visitInfo = [Visit]()
        do {
            visitInfo = try db.read { db in
                try Visit
                    .select(
                        Column("visitDate"),
                        count(Column("visitAge"))
                    )
                    .group(Column("visitDate"))
                    .asRequest(of: Visit.self)
                    .fetchAll(db)
            }
        } catch {
            fatalError("\(error)")
        }
        return visitInfo
    }
```

and the results is the error above.

Regards, André Hartman

**Comment by ahartman** [comment]
Dear Gwendal,

I arrived as another 'modified' example that works:

```
    struct VisitAgeCounts: Decodable, FetchableRecord {
        var visitAge: Int
        var countVisitVisitAge: Int
    }

    func getVisitAges(dates: PeriodStartEnd) {
        var visitAges = [VisitAgeCounts]()
        do {
            try db.read { db in
                let request = Visit
                    .select(
                        Column("visitAge"),
                        count(Column("visitAge"))
                    )
                    .group(Column("visitAge"))
                let visitAge = try Row.fetchAll(db, request)
                for v in visitAge {
                    visitAges.append(VisitAgeCounts(visitAge: v[0], countVisitVisitAge: v[1]))
                }
                print(visitAge)
            }
        } catch {
            fatalError("\(error)")
        }
        print(visitAges)
    }
```

However, I cannot map the fetch=All to the struct above as I cannot guess the name for the count(visitAge) variable.

Regards, André Hartman

**Comment by groue** [comment]
Hello @ahartman 

> and the results is the error above.

Indeed. The request selects two columns when the record you want to decode from its fetched results  counts a dozen properties.

I'm far away from any computer right now. May I suggest you [log SQL statements](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/configuration#Tracing-SQL-Statements) so that you can check if the requests match the decoded records?

**Comment by groue** [comment]
You can give a name to any selected expression with the `AS` SQL operator. The Swift version is called `forKey`, because, well, one usually names a column so that it fits a decoding key. See [SQL operators](https://github.com/groue/GRDB.swift/blob/master/README.md#sql-operators).
