### ISSUE TITLE
Thread running at User-initiated quality-of-service class waiting on a thread without a QoS class specified (base priority 0). Investigate ways to avoid priority inversions

### ISSUE THREAD

**Issue by atacan** [groue/GRDB.swift#1542]
### What did you do?

Calling `DatabaseReader`'s `read(…)` inside an async function.

### What did you expect to happen?

No warning.

### What happened instead?

I get purple warning. It points to `itemsSemaphore` in the `Pool` class

![ScrShot 2024-05-09 at 12 23 04@2x](https://github.com/groue/GRDB.swift/assets/765873/974b3691-88ae-433e-8a11-faaa9bf026cc)

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.27.0
**Installation method:** SPM
**Xcode version:** 15.2
**Swift version:** 5.9
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 14.4.1

### Demo Project

I couldn't reproduce this issue. It seems to happen sporadically, at least to my knowledge.

**Comment by groue** [comment]
Hello @atacan. Please search for existing issues with the keyword "priority".
