### ISSUE TITLE
How to store database connection

### ISSUE THREAD

**Issue by rakuyoMo** [groue/GRDB.swift#1546]
### What did you do?

My code is as follows: I manually started a transaction, first wrote data to the database in the transaction, and then saved the image to the sandbox. If the save was successful, the transaction was committed. If the save failed, it was rolled back.

> Rolling back the database is simpler and performs better than deleting already saved images. So I write the data first instead of saving the image first

```swift
let database = try DatabaseQueue(path: ...)

database.asyncWriteWithoutTransaction { [weak self] db in
    do {
        try db.beginTransaction()

        try data.save(db)

        self?.saveImage(images, key: key) { [weak self] in
            switch $0 {
            case .success(let cachedKeys):
                do {
                    try db.commit()
                    completion(.success(data))

                } catch {
                    try? db.rollback()
                    self?.removeSavedImages(with: cachedKeys)
                    completion(.failure(.writeToDBFailure(error, sticker)))
                }

            case .failure(let error):
                try? db.rollback()
                completion(.failure(.saveImageFailure(error)))
            }
        }

    } catch {
        try? db.rollback()
        completion(.failure(.writeToDBFailure(error)))
    }
}
```

### What did you expect to happen?

I can submit the database operation after the image is saved.

### What happened instead?

The `db` object cannot be used in the trailing closure of the `saveImage` method.

```
Thread 2: Fatal error: A transaction has been left opened at the end of a database access
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.27.0
**Installation method:** SPM
**Xcode version:** Version 15.3 (15E204a)
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 14.4.1 (23E224)

**Comment by rakuyoMo** [comment]
I noticed [allowsUnsafeTransactions](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/configuration/allowsunsafetransactions), is it the only solution for this?

**Comment by groue** [comment]
Hello @rakuyoMo,

> Does this mean that no matter what method, I can't take `db` to other places?

That's exactly it. The [documentation of `asyncWriteWithoutTransaction(_:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasewriter/asyncwritewithouttransaction(_:)) states:

> The `Database` argument to the `updates` closure argument is valid only during the execution of the closure. Do not store or return the database connection for later use.

This constraint currently lives in the documentation. As soon as the Swift language makes it possible to declare that [some values can't be escaped](https://forums.swift.org/t/pitch-non-escapable-types-and-lifetime-dependency/69865), GRDB will make sure the sample code does not even compile.

If you want to perform further database operations, perform another database access.

> In later attempts, I set `allowsUnsafeTransactions` to true.

It is not easy to perform two writes in two distinct persistence systems, and recover from an error in one of them. It's even more difficult when one of the system is asynchronous (`saveImage`).

I can't really provide advice on your best way to solve this. Just remember that GRDB transactions like to be synchronous. You _can_ try to make them asynchronous with `allowsUnsafeTransactions`, but things will just turn more difficult. In particular, concurrent database access to the same `DatabaseQueue` might interfere in _really bad ways_. You might avoid this by using a specific `DatabaseQueue` instance. But now you'll face the risk of busy errors (due to the risk of parallel writes), and lose database observation (due to multiple connection instances). Pick up your battle wisely.

**Comment by rakuyoMo** [comment]
> Just remember that GRDB transactions like to be synchronous. 

When I use the `writeWithoutTransaction` method, even though the trailing closure of `saveImage` and `try db.beginTransaction()` are executed in the main thread, `SchedulingWatchdog` will still be released because of a thread switch in the middle.

In fact, when I comment out the code that prevents me from performing the operation, the database can be written to normally, does this mean that this is just a risky operation and it is not absolutely dangerous?

> does this mean that this is just a risky operation and it is not absolutely dangerous?

Well, I think it's an unrealistic idea, and just being risky is enough for it to be banned. At least this is not how the issue should be described or led in this direction.

---------

@groue Or is there a way to achieve the following:

1. After allowing back to the thread that created the database connection, add a new `SchedulingWatchdog` object.

Use the `writeWithoutTransaction` synchronization method to create a connection on the main thread, because the thread will not be released, the program just switches between different threads, and will eventually return to the main thread, so you can try to re-add the `SchedulingWatchdog` object?

2. Regarding the `asyncWriteWithoutTransaction` method, similarly, if the thread that creates the database connection is not released after switching threads, can the `SchedulingWatchdog` object be restored when we return to this thread?

**Comment by rakuyoMo** [comment]
Can you provide some clues as to when `SchedulingWatchdog` will be released? Or I could figure out a way to keep it there.

**Comment by groue** [comment]
> Just remember that GRDB transactions like to be synchronous.

I should have said it differently. When you perform a database access, whether it is synchronous or asynchronous, database operations are always executed in a closure that accepts a `Database` argument. This closure is **synchronous**. You must not perform async work there - at least no async work that escapes the `Database` from the closure.

This is how it works. This is explicitly documented, as I mentioned above. This will not change.

I'm not sure it is useful to focus of `SchedulingWatchdog`, which is an internal tool. Its goal is to help detect misuses of a `Database`, such as escaping it. If it prevents you from using the `db` value from the `saveImage` completion block, well that's exactly its job.

As I said above:

> It is not easy to perform two writes in two distinct persistence systems, and recover from an error in one of them. It's even more difficult when one of the system is asynchronous (`saveImage`).

You can try to keep on bending GRDB into supporting unsafe operations, but, again, as I said above:

> Pick up your battle wisely.

For example, did you consider refactoring `saveImage` into a synchronous method? Or did you consider performing an asynchronous call to `saveImage` and then one single database access in its completion block? As long as you try to perform an async operation in the middle of a database transaction, you'll face difficulties that GRBD has no intention to help dealing with. You have to refactor your code.
