### ISSUE TITLE
Is Configuration.trace really working ?

### ISSUE THREAD

**Issue by jmcazaux** [groue/GRDB.swift#155]
Hi there,
I am trying to debug my application and SQL traces would be extremely useful.

I have trie to set up traces when creating the queue in a basic way like this
```
    static func openOrCreateDatabase(atPath path: String) throws -> DatabaseQueue {

        var config = Configuration()
        config.trace = { print($0) }     // Prints all SQL statements


        let queue = try DatabaseQueue(path: path, configuration: config)

        var migrator = DatabaseMigrator()

        try FADbOpenHelper.initializeStructute(withMigrator: &migrator)
        try migrator.migrate(queue)

        return queue
        
    }
```
but the only thing it does print is
`PRAGMA foreign_keys = ON`

Am I doing anything wrong ?

**Comment by groue** [comment]
Last I checked, trace was working.

The `migrator.migrate(queue)` instruction should at least log the following lines:

```sql
CREATE TABLE IF NOT EXISTS grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)
SELECT identifier FROM grdb_migrations
```

Try to put a breakpoint in the trace closure?

**Comment by jmcazaux** [comment]
Sorry I was not clear enough, I am past table creation.

This is very strange, I have just seen an update statement in the logs, but all the others are missing.
And it seem it is not even consistent.

Could it be an issue with console, threading ?

**Comment by groue** [comment]
Yep, I'm not sure of the behaviour of print, actually. Try with NSLog? See http://stackoverflow.com/questions/25951195/swift-print-vs-println-vs-nslog

**Comment by jmcazaux** [comment]
I have tried with both CocoaLumberjack (integrated to my inhouse framework) and NSLog, no luck.

Updates print. It seems none of teh others.
Very strange as I am missing no other logs regardless of the thread the are called in.

**Comment by groue** [comment]
Pick a point of your program that accesses the database: put a breakpoint right before the db access, and a breakpoint inside the trace closure.

**Comment by groue** [comment]
No news, closing
