### ISSUE TITLE
The method DatabaseMigrator.migrate is time-consuming; is it necessary to execute it every time？

### ISSUE THREAD

**Issue by songzhiming** [groue/GRDB.swift#1556]
### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by songzhiming** [comment]
![img_v3_02bi_f7dad887-0b43-4cc4-bccc-15b32f08ccdg](https://github.com/groue/GRDB.swift/assets/7426040/8a560f5c-22c9-4e82-a35c-9d6b7f6fbf83)

**Comment by groue** [comment]
Hello @songzhiming,

You didn't care explain what you mean with "time-consuming". Your screenshot does not reveal anything that looks slightly related to the issue title. You did not care answering the questions in the issue template. Your [previously opened issues](https://github.com/groue/GRDB.swift/issues?q=author%3Asongzhiming) are just as lazy.

Please improve your reports.

Now, read the [Migrations Guide](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/migrations). If you have unanswered questions, **write them**.

**Comment by songzhiming** [comment]
@groue  I'm sorry, this is my fault.
