### ISSUE TITLE
How can I be sure my database is encrypted

### ISSUE THREAD

**Issue by yuyedaidao** [groue/GRDB.swift#1564]
Before proceeding with data migration, I want to confirm if my data is already encrypted. If it is encrypted, I will abandon the migration.

**Comment by groue** [comment]
Hello @yuyedaidao,

Please next time do not ignore the template when you create an issue. You saw [this](https://raw.githubusercontent.com/groue/GRDB.swift/master/.github/ISSUE_TEMPLATE.md), and ignored it. Don't do that.

Now, check the documentation [Exporting a Database to an Encrypted Database](https://github.com/groue/GRDB.swift/blob/master/README.md#exporting-a-database-to-an-encrypted-database). Chances are that you figure out how to accomplish your task on your own.
