### ISSUE TITLE
Do we have better way to resolve this issue?

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#1571]
### I just remove the original database file, and re-generate a new file to replace it.
```swift
    fileprivate func handleError(error: Error) throws {
        if let error = error as? DatabaseError, error.resultCode == .SQLITE_CORRUPT {
            //try self.dbWriter.close() -> here
            var config = Configuration()
            config.prepareDatabase { database in
                try database.execute(sql: "PRAGMA auto_vacuum = FULL")
            }
            let currentQueue = try? DatabaseQueue(path: dbPathV2, configuration: config)
            self.dbWriter = currentQueue
            try self.migrator.migrate(self.dbWriter)
        } else {
            throw error
        }
    }
```
### But there is warning message:
> BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: xxx
### After I add this line, there is no warning message: 
```swift
try self.dbWriter.close() 
```

### What did you expect to happen?
`But i noticed the comment from this function. It shouldn't be called, so Do we have a better way to resolve this issue? or Ignore warning message?`

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)  6.8.0
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?) cocoapods
**Xcode version:** iOS
**Swift version:** 5.0
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @glve1027,

The better way to resolve the `SQLITE_CORRUPT` error (you already mentioned it in #877, #1474, #1568) is to **take care** of the replies that were already given to you in your previous issues:

- https://github.com/groue/GRDB.swift/issues/877#issuecomment-735226105
- https://github.com/groue/GRDB.swift/issues/877#issuecomment-735228132

You're no longer welcome to open an issue about `SQLITE_CORRUPT`.

**Comment by glve1027** [comment]
I don't ask anything about the SQLITE_CORRUPT. I just want to confirm with you about replacing the original database file, and there is a warning from SQLite.

**Comment by glve1027** [comment]
And about the close method from GRDB.

**Comment by groue** [comment]
The documentation of [`close()`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasereader/close()) says:

> you should not call it unless the correct execution of your program depends on precise database closing.

It looks like it's the case of your app: go ahead.
