### ISSUE TITLE
Issue with SQLCipher in v6.28.0

### ISSUE THREAD

**Issue by TheNephilim88** [groue/GRDB.swift#1576]
Hey,

I just upgraded from v6.26.0 to 6.28.0 and I now get error "Value of type 'Database' has no member 'usePassphrase'".

Reverting to v6.26.0 solves the issue. Do I need to change anything? Didnt see anything relevant in changelog.

I integrate GRDB & SQLCipher via cocoa (branch GRDB6 only gived v6.26.0):
```
pod 'GRDB.swift/SQLCipher', git: 'https://github.com/groue/GRDB.swift.git', branch: 'GRDB6'
pod 'SQLCipher', '~> 4.0'
```

To get latest 6.28.0 I used following in my podfile instead:
```
pod 'GRDB.swift', git: 'https://github.com/groue/GRDB.swift.git', tag: 'v6.28.0'
pod 'SQLCipher', '~> 4.0'
```

Any idea what am I doing wrong?

**Comment by groue** [comment]
Hello @TheNephilim88 

I forgot to push v6.28.0 to the GRDB6 branch, and that's why you did not get it. I have updated the branch now.

Take care to use `GRDB.swift/SQLCipher` instead of `GRDB.swift` - that's how GRDB gets its extra encryption apis.
