### ISSUE TITLE
find(db, key:"xxx") show error: The operation couldn’t be completed. (GRDB.RecordError error 0.)

### ISSUE THREAD

**Issue by ldbfrank** [groue/GRDB.swift#1582]
### What did you do?

I created a table: ironAction(actionId TEXT, PRMARY KEY, ...)
and try method: Type.find(db, key)

### What did you expect to happen?

It would return a correct record instance of IronAction, if I try an actionId that it exists in the table.
It would show error like the title above, if I try any actionIds they are not in the table.
I expects the return is only nil without error.
I am not sure why?

Following is the code:
let actionId = "4375585899937798"

func findIronAction(actionId: String) -> IronAction? {
      do {
                  return try dbPool?.read { db in
                      try IronAction.find(db, key: actionId)
                  }
        } catch {
            return nil
        }
}

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:** 6.29.0
**Installation method:** (manual)
**Xcode version:** 15.4
**Swift version:** 5.10
**Platform(s) running GRDB:** (macOS)
**macOS version running Xcode:** 14.5

**Comment by ldbfrank** [comment]
Oh, there is code: 
print(error) in the catch clause.

**Comment by groue** [comment]
Hello @ldbfrank 

The [`find(_:key:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.29.0/documentation/grdb/fetchablerecord/find(_:key:)-4kry5) is documented to throw `RecordError.recordNotFound` if the record does not exist in the database, for the given key.

Use `fetchOne(_:key:)` if you'd prefer to get a nil result for missing records.

**Comment by ldbfrank** [comment]
I see. Thanks!
GRDB.swift is really fast and simple, it is what I want! 
Thanks for your work! GREAT!
