### ISSUE TITLE
Compilation failure with Xcode 16 beta 5 due to missing `strcmp`

### ISSUE THREAD

**Issue by noremac** [groue/GRDB.swift#1588]
### What did you do?

I attempted to compile a project that uses GRDB 6.29.0 with Xcode 16 beta 5.

### What did you expect to happen?

Compile successfully

### What happened instead?

StatementAuthorizer.swift is failing to compile due to the error:

> Cannot find 'strcmp' in scope

<img width="858" alt="Screenshot 2024-08-06 at 7 21 28 PM" src="https://github.com/user-attachments/assets/2e3b5f9b-5c03-4475-9517-2011b9dbdfae">

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.0
**Installation method:** SPM
**Xcode version:** Xcode 16 beta 5
**Swift version:** I am using Swift 6 in my app but GRDB seems to be using 5.7.
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** macOS 14.5

**Comment by noremac** [comment]
Adding this in StatementParser.swift gets past the error. Looks like something was moved around?

```
#if canImport(Darwin)
import Darwin
#endif
```

**Comment by noremac** [comment]
PR here if you'd like it! https://github.com/groue/GRDB.swift/pull/1589

**Comment by TastyHeadphones** [comment]
Same issue

**Comment by fnazarios** [comment]
Same issue

**Comment by groue** [comment]
Resolved in 6.29.1.

**Comment by nikburnt** [comment]
Issue returned in v7.0.0-beta.6

**Comment by groue** [comment]
> Issue returned in v7.0.0-beta.6

v7.0.0-beta.6 compiles fine in Xcode 16.1.

If you see some problem, please describe how to reproduce it.

**Comment by groue** [comment]
> Issue returned in v7.0.0-beta.6

> Issue returned in v7.0.0-beta.6

v7.0.0-beta.6 compiles fine in Xcode 16.1.

If you see some problem, @nikburnt, please describe how to reproduce it.
