### ISSUE TITLE
Cannot find 'strcmp' in scope error showing up in Xcode 16.0 beta 5 and above

### ISSUE THREAD

**Issue by ajcampbell** [groue/GRDB.swift#1592]
### What did you do?

I tried to build and run an app using Xcode 16.0 Beta 5 and Xcode 16.1 Beta

### What did you expect to happen?

I expected the app to run

### What happened instead?

Got a `Cannot find 'strcmp' in scope` error:

<img width="1925" alt="Screenshot 2024-08-14 at 13 06 00" src="https://github.com/user-attachments/assets/666f8a98-dbc0-4f93-8f8a-0a8c3fbedfc0">

### Environment

**GRDB flavor(s):** SQLite
**GRDB version:** Latest (Master Branch)
**Installation method:** SPM
**Xcode version:** Xcode 16.1 Beta 
**Swift version:** 6.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Sonoma 14.5

**Comment by groue** [comment]
Hello @ajcampbell 

The problem with Xcode 16 beta 5 was resolved in #1589, shipped in v6.29.1.

If this version reveals an issue with Xcode 16.1 beta, please tell.

---

It is not recommended to depend on the master branch. Use tagged versions instead. Only tagged versions have been properly tested.
