### ISSUE TITLE
XCode warns "No 'async' operations occur within 'await' expression"

### ISSUE THREAD

**Issue by gfreezy** [groue/GRDB.swift#1594]
### What did you do?

![image](https://github.com/user-attachments/assets/304f258c-8e91-4dcf-ae2c-259675268bca)

### What did you expect to happen?

it should be no warning.

### What happened instead?

XCode warns about:

```
No 'async' operations occur within 'await' expression
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.1
**Installation method:** SPM
**Xcode version:** 16.0 beta 5
**Swift version:** swift 6
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 14.5

**Comment by groue** [comment]
Hello @gfreezy,

The async version of GRDB [`read(_:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.29.1/documentation/grdb/databasereader/read(_:)-4w6gy) requires an `@escaping` closure. Your own `read(value:)` should require an `@escaping` closure as well:

```swift
static func read<T>(value: @escaping (Database) throws -> T) async throws -> T {
//                         ~~~~~~~~~
```

Please update your code, and report if this resolves the issue.

**Comment by gfreezy** [comment]
`@escaping` is not enough. After adding `@Sendalbe @escape`, it works. Seems the document is outdated.


![image](https://github.com/user-attachments/assets/31d6bd2f-0c84-4433-853b-2ee595942eac)
