### ISSUE TITLE
Swift 6 concurrency warnings

### ISSUE THREAD

**Issue by ahartman** [groue/GRDB.swift#1597]
### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** master
**Installation method: SPM
**Xcode version: 15.4
**Swift version: 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** Sonia 14.6.1

When preparing for Swift 6, the static let variables in GDRB structs for 'belongsTo' and 'hasMany' produce a warning:
"Static property 'visits' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6"

See image below:

<img width="618" alt="Scherm­afbeelding 2024-08-23 om 08 49 21" src="https://github.com/user-attachments/assets/04dda6b7-02a4-4aac-9c76-06d1246fb2da">

**Comment by groue** [comment]
Hello @ahartman. Please see https://github.com/groue/GRDB.swift/discussions/1509

**Comment by ahartman** [comment]
Dear Gwendal,
Perfect answer, thank you.
André Hartman
