### ISSUE TITLE
GRDB version "v6.29.2" incorrectly tagged as "v6.92.2"

### ISSUE THREAD

**Issue by lotz** [groue/GRDB.swift#1601]
### What did you do?

Noticed that version `v6.29.2` is incorrectly tagged as `v6.92.2`. This may cause issues or confusion for those using SPM to reference the tag.

### What did you expect to happen?

I expected version `v6.29.2` to be tagged with a tag matching that version.

### What happened instead?

Version `v6.29.2` was incorrectly tagged as `v6.92.2`.

<img width="309" alt="image" src="https://github.com/user-attachments/assets/e604331f-a0be-46c1-8077-fe1237aa103f">

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.2
**Installation method:** (CocoaPods, SPM, manual?) SPM
**Xcode version:** n/a
**Swift version:** n/a
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) n/a
**macOS version running Xcode:** n/a

**Comment by groue** [comment]
Oh, thank you @lotz! 🙏 

I deleted the wrong tag and pushed v6.29.2. I hope this won't disturb too many people 😬

**Comment by lotz** [comment]
Thanks!! Probably won't disturb too many folks as it was caught pretty early.

**Comment by groue** [comment]
Thanks to you! 👍
