### ISSUE TITLE
EXC_BAD_ACCESS Bug

### ISSUE THREAD

**Issue by hzx157** [groue/GRDB.swift#1611]
### What did you do?

When the Swift Compiler - Code Generation Optimization Level for Speed (-O) is enabled, an error EXC_BAD_ACCESS occurs in the function required init(row: Row), for example, sendTime = row[Columns.sendTime]. However, when I set it to No Optimization (-Onone), the assignment operation works correctly.

**Comment by groue** [comment]
Hello @hzx157,

Please fill in the complete issue form, including your programming environment, your installation method, etc, etc: https://github.com/groue/GRDB.swift/issues/new

Why? Because if you don't help reproducing your issue, you can't expect much help.

**Comment by groue** [comment]
Oh, and if you think this is a compiler bug, you should report the problem at http://feedbackassistant.apple.com or https://github.com/swiftlang/swift
