### ISSUE TITLE
Sponsorship - casual mode?

### ISSUE THREAD

**Issue by smhk** [groue/GRDB.swift#1616]
We generally send the odd 50 or 100 bucks to projects we support, however, preferred is just clicking paypal which is easiest.

(I don't really like the sponsor system built-in to githib as there are forms to fill in and data to supply.)

In a word, is there a paypal # for donations?  TY

Thrilled to be using grdb on a project again, haven't had a db project for a couple yrs!

![Screenshot 2024-09-06 at 7 08 53 AM copy](https://github.com/user-attachments/assets/bbe345ec-84ff-46cc-b65c-99fbf85b760a)

/\ this guy is too much work for dilettantes  :)

PS "SwiftData" - wtf?  So bad.

**Comment by groue** [comment]
Thanks for expressing your desire to support GRDB, @smhk. I did not take the time to setup any other input method than GitHub indeed. And believe me it also was a lot of forms to fill 😅.

Don't worry, GRDB is free, and sponsoring does not enable any particular privilege. In particular, support is free as long as it is reasonable and done in public. For private support, or specific developments, it's better to establish a regular business relationship.

**Comment by smhk** [comment]
! d'accord, I will follow that then.  Thanks and best!
