### ISSUE TITLE
Adding searchbar functionality

### ISSUE THREAD

**Issue by primico** [groue/GRDB.swift#162]
Hi, thanks for the great demo!

In PersonsViewController.swift I would like to add a searchbar.
Normally, I would do something like this:

        self.searchController = UISearchController(searchResultsController: self.resultsController)
        self.tableView.tableHeaderView = self.searchController.searchBar
        self.searchController.searchResultsUpdater = self

and filter the results here:

    func updateSearchResultsForSearchController(searchController: UISearchController) {
        // filter here
    }

My question is.. with the FetchedRecordsController, would I do this differently? Or would I use the same approach?

**Comment by groue** [comment]
Hello @primico/Mike

There is a GRDB demo application that performs full-text search: https://github.com/groue/WWDCCompanion

In this app, you'll find an implementation of UISearchResultsUpdating's `updateSearchResults(for:)` which updates the request of a FetchedRecordsController so that the new search results are displayed. Check out [SearchResultsTableViewController.swift](https://github.com/groue/WWDCCompanion/blob/master/WWDCCompanion/Controllers/SearchResultsTableViewController.swift).

Its implementation uses raw SQL because it uses the [Snippet SQLite function](https://www.sqlite.org/fts3.html#the_snippet_function). But you don't have to use raw SQL if you don't need the snippet function:

```swift
func updateSearchResults(for searchController: UISearchController) {
    // Turn the user query into a search pattern, and update
    // fetchedRecordsController's request.
    let queryString = searchController.searchBar.text ?? ""
    let pattern = FTS3Pattern(matchingAnyTokenIn: queryString)
    let request = Book.matching(pattern).order(Column("title"))
    try! booksController.setRequest(request)
}
```

The demo app uses a custom build of SQLite, so that it can demo how to use the FTS5 search engine. If you don't need FTS5, or don't need full text search, the regular GRDB will be just OK.

**Comment by groue** [comment]
@primico I've just updated the WWDCCompanion repo so that the README tells how to download dependencies and run the app

**Comment by primico** [comment]
Strange.. when I do this, I get data:
let request = Customer.order(Column("FirstName"))

But when I do this:
let pattern = FTS3Pattern(matchingAnyTokenIn: "test")
let request = Customer.matching(pattern).order(Column("FirstName"))
   
I get this error on performFetch():
Thread1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by groue** [comment]
I'm sure you can provide more information about the error you get.

**Comment by primico** [comment]
Here is some debug info (not sure if it is useful). I get this error just by adding "matching" to my request. When I take it out, I get data.

libswiftCore.dylib`Swift._assertionFailed (Swift.StaticString, Swift.String, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> Swift.Never:
    0x11180b430 <+0>:   pushq  %rbp
    0x11180b431 <+1>:   movq   %rsp, %rbp
    0x11180b434 <+4>:   pushq  %r15
    0x11180b436 <+6>:   pushq  %r14
    0x11180b438 <+8>:   pushq  %r13
    0x11180b43a <+10>:  pushq  %r12
    0x11180b43c <+12>:  pushq  %rbx
    0x11180b43d <+13>:  subq   $0x18, %rsp
    0x11180b441 <+17>:  movq   %r9, %rbx
    0x11180b444 <+20>:  movq   %r8, %r15
    0x11180b447 <+23>:  movq   %rcx, %r12
    0x11180b44a <+26>:  movl   %edx, -0x2c(%rbp)
    0x11180b44d <+29>:  movq   %rsi, -0x38(%rbp)
    0x11180b451 <+33>:  movq   %rdi, %r14
    0x11180b454 <+36>:  leaq   0x245825(%rip), %rdi      ; protocol descriptor for Swift.CustomLeafReflectable + 536
    0x11180b45b <+43>:  movl   $0x4c, %esi
    0x11180b460 <+48>:  movl   $0x7, %edx
    0x11180b465 <+53>:  callq  0x11193ff50               ; rt_swift_allocObject
    0x11180b46a <+58>:  movq   %rax, %r13
    0x11180b46d <+61>:  movq   %r12, 0x10(%r13)
    0x11180b471 <+65>:  movq   %r15, 0x18(%r13)
    0x11180b475 <+69>:  movq   %rbx, 0x20(%r13)
    0x11180b479 <+73>:  movq   0x10(%rbp), %rax
    0x11180b47d <+77>:  movq   %rax, 0x28(%r13)
    0x11180b481 <+81>:  movq   0x18(%rbp), %rax
    0x11180b485 <+85>:  movq   %rax, 0x30(%r13)
    0x11180b489 <+89>:  movb   0x20(%rbp), %al
    0x11180b48c <+92>:  movb   %al, 0x38(%r13)
    0x11180b490 <+96>:  movq   0x28(%rbp), %rax
    0x11180b494 <+100>: movq   %rax, 0x40(%r13)
    0x11180b498 <+104>: movl   0x30(%rbp), %eax
    0x11180b49b <+107>: movl   %eax, 0x48(%r13)
    0x11180b49f <+111>: movq   %rbx, %rdi
    0x11180b4a2 <+114>: callq  0x111a0c3c0               ; swift_unknownRetain
    0x11180b4a7 <+119>: leaq   0x15ccf2(%rip), %r8       ; partial apply forwarder for Swift.(_assertionFailed (Swift.StaticString, Swift.String, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> Swift.Never).(closure #1)
    0x11180b4ae <+126>: movq   %r14, %rsi
    0x11180b4b1 <+129>: movq   -0x38(%rbp), %rdx
    0x11180b4b5 <+133>: movl   -0x2c(%rbp), %ecx
    0x11180b4b8 <+136>: movq   %r13, %r9
    0x11180b4bb <+139>: callq  0x11180b650               ; function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer <A> ((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A
->  0x11180b4c0 <+144>: ud2    
    0x11180b4c2 <+146>: nopw   %cs:(%rax,%rax)





libswiftCore.dylib`Swift._assertionFailed (Swift.StaticString, Swift.String, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> Swift.Never:
    0x11180b430 <+0>:   pushq  %rbp
    0x11180b431 <+1>:   movq   %rsp, %rbp
    0x11180b434 <+4>:   pushq  %r15
    0x11180b436 <+6>:   pushq  %r14
    0x11180b438 <+8>:   pushq  %r13
    0x11180b43a <+10>:  pushq  %r12
    0x11180b43c <+12>:  pushq  %rbx
    0x11180b43d <+13>:  subq   $0x18, %rsp
    0x11180b441 <+17>:  movq   %r9, %rbx
    0x11180b444 <+20>:  movq   %r8, %r15
    0x11180b447 <+23>:  movq   %rcx, %r12
    0x11180b44a <+26>:  movl   %edx, -0x2c(%rbp)
    0x11180b44d <+29>:  movq   %rsi, -0x38(%rbp)
    0x11180b451 <+33>:  movq   %rdi, %r14
    0x11180b454 <+36>:  leaq   0x245825(%rip), %rdi      ; protocol descriptor for Swift.CustomLeafReflectable + 536
    0x11180b45b <+43>:  movl   $0x4c, %esi
    0x11180b460 <+48>:  movl   $0x7, %edx
    0x11180b465 <+53>:  callq  0x11193ff50               ; rt_swift_allocObject
    0x11180b46a <+58>:  movq   %rax, %r13
    0x11180b46d <+61>:  movq   %r12, 0x10(%r13)
    0x11180b471 <+65>:  movq   %r15, 0x18(%r13)
    0x11180b475 <+69>:  movq   %rbx, 0x20(%r13)
    0x11180b479 <+73>:  movq   0x10(%rbp), %rax
    0x11180b47d <+77>:  movq   %rax, 0x28(%r13)
    0x11180b481 <+81>:  movq   0x18(%rbp), %rax
    0x11180b485 <+85>:  movq   %rax, 0x30(%r13)
    0x11180b489 <+89>:  movb   0x20(%rbp), %al
    0x11180b48c <+92>:  movb   %al, 0x38(%r13)
    0x11180b490 <+96>:  movq   0x28(%rbp), %rax
    0x11180b494 <+100>: movq   %rax, 0x40(%r13)
    0x11180b498 <+104>: movl   0x30(%rbp), %eax
    0x11180b49b <+107>: movl   %eax, 0x48(%r13)
    0x11180b49f <+111>: movq   %rbx, %rdi
    0x11180b4a2 <+114>: callq  0x111a0c3c0               ; swift_unknownRetain
    0x11180b4a7 <+119>: leaq   0x15ccf2(%rip), %r8       ; partial apply forwarder for Swift.(_assertionFailed (Swift.StaticString, Swift.String, Swift.StaticString, Swift.UInt, flags : Swift.UInt32) -> Swift.Never).(closure #1)
    0x11180b4ae <+126>: movq   %r14, %rsi
    0x11180b4b1 <+129>: movq   -0x38(%rbp), %rdx
    0x11180b4b5 <+133>: movl   -0x2c(%rbp), %ecx
    0x11180b4b8 <+136>: movq   %r13, %r9
    0x11180b4bb <+139>: callq  0x11180b650               ; function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer <A> ((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A
->  0x11180b4c0 <+144>: ud2    
    0x11180b4c2 <+146>: nopw   %cs:(%rax,%rax)

**Comment by groue** [comment]
Yes, that's not quite clear. Which version of GRDB are you using? Do you know which line crashes?

**Comment by primico** [comment]
Not sure what version, where do I see that?

In my pod file:
pod 'GRDB.swift'
and I installed it within the last week.

Crashes on line:
try! customerController.performFetch()

My entire code in viewDidLoad().......  it works when I remove "matching"

        let pattern = FTS3Pattern(matchingAnyTokenIn: "test")
        let request = Customer.matching(pattern).order(Column("FirstName"))
        customerController = try! FetchedRecordsController(dbQueue, request: request)
        customerController.trackChanges { [unowned self] _ in
            self.tableView.reloadData()
        }
        try! customerController.performFetch()

**Comment by groue** [comment]
Well, search more, because I don't have enough information to help. Come back with your version of GRDB (podfile.lock), update to latest version if you don't use v0.100.0 (because I don't support old versions), and please make some visible effort to find out which framework crashes, in which function so that I make some visible effort to help you fix this issue.

**Comment by primico** [comment]
Here's the version of GRDB:
GRDB.swift (0.100.0)
Will probably switch to Sqlite.swift, but hopefully my post here will help someone else.
Good luck

**Comment by groue** [comment]
That's OK. Good luck with SQLite.swift, but you may miss FetchedRecordsController and FTS3Pattern(matchingAnyTokenIn:) when you need them. Sorry if I did sound rude, but I just don't have enough information: I can't guess what makes your application crash.

**Comment by groue** [comment]
Especially considering you are using Cocoapods: when your app crashes, Xcode shows you the line that crashes. I don't know what prevents you from providing this crucial information, and *anything* which could help *reproducing* the bug so that it can be *understood*, and then *fixed*.

**Comment by primico** [comment]
I am using the absolutely latest libraries of everything. The crash happens at performFetch(), Thread 1... and I copied/pasted everything in my console window above. I'll take another quick look to see if I can see anything else that would be useful, but I didn't see it.

**Comment by groue** [comment]
All right. Reopen the issue with useful information (especially the inner GRDB line which crashes) when you have some: I'll be there!

**Comment by primico** [comment]
OK, I stepped through the GRDB code and my error happens at the fatalerror below. I call performFetch() in viewDidLoad. Is that not correct?

    public var numberOfRecords: Int {
        guard let items = controller.fetchedItems else {
            // Programmer error
            fatalError("the performFetch() method must be called before accessing section contents")
        }
        return items.count
    }

**Comment by groue** [comment]
> Is that not correct?

Well, it looks like it is not: the error message is pretty clear. You're on the way to fix your issue.

**Comment by primico** [comment]
Good luck with your library. It looks promising.

**Comment by groue** [comment]
It is ! And it it will help you a lot once you call performFetch() before accessing section contents ;-)

**Comment by groue** [comment]
If you do, then you may have found a bug. If so, please tell so clearly!

**Comment by swiftlyfalling** [comment]
@primico: What's probably needed to debug this is your ViewController. Something is accessing `numberOfRecords` before the fetch is performed. Look up the call stack from the failing method and you should see what's getting called. Things can happen before `viewDidLoad`, and one of those thing is ultimately calling `numberOfRecords`.

**Comment by groue** [comment]
@swiftlyfalling Thanks - I'm now sure @primico has been trying to use full-text matching on a regular (non full-text) table, because of my initial advice. This advice was the kiss of the spider: he doesn't know that matching is only for [full-text tables](https://github.com/groue/GRDB.swift/#full-text-search). This explains why his sandbox app was crashing as soon as he was using `matching`. And later he has been fiddling around, until he got the performFetch error. This was unrelated to his previous issue - but he was too frustrated already - and so were I. Our conversation did not find its common level.
