### ISSUE TITLE
Obscure situation: dynamically building a StatementArguments.

### ISSUE THREAD

**Issue by smhk** [groue/GRDB.swift#1627]
As briefly as possible ...

I have something like

     arguments: [nil, pl.a, pl.b, pl.c, vals[0], vals[1], vals[2]]

vals is a `[String]`.  the `pl.` fields are various. The seven seen are type correct for the table at hand.

I wanted to do essentially:

     arguments: [nil, pl.a, pl.b, pl.c] + vals
     // Cannot convert value of type 'Array<Any?>' to expected argument type 'StatementArguments'

Or perhaps `StatementArguments([nil, pl.a, pl.b, pl.c].append(vals))` or such ("Cannot convert value of type '[Any?]' to expected argument type '[String]'")

(`vals` will vary appropriately in length for each dynamic table involved in this exotic situation)

Sorry, I just can't figure the initializer for the situation !!!!   🤪

**Comment by groue** [comment]
Hello @smhk,

You are probably looking for a `StatementArguments` initializer:

```swift
arguments: [nil, pl.a, pl.b, pl.c] + StatementArguments(vals)
```

Depending on the real type of `vals`, you may have to massage your input. The list of initializers is there: https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/statementarguments#initializers

**Comment by smhk** [comment]
got it!

`let dArgs: StatementArguments = [nil, pl.seq, pl.field, pl.well6id] + StatementArguments(vals) // works`

`let dArgs: StatementArguments = StatementArguments([nil, pl.seq, pl.field, pl.well6id] + vals)  // not`

so lovely. case closed TY TY
