### ISSUE TITLE
Promised based interface

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#163]
Hello,

Have you considered adding a promise based interface? I realize that it might not be desirable to add additional dependencies to GRDB itself (a framework for promises) but maybe as an additional "add-on"?

It could be very nice when chaining operations. But mostly it would be a nice way of handling errors (IMO).

I realize it would be a pretty big job to wrap all methods to return promises and not something I expect to happen. Just curious if it's something you've even considered?

**Comment by groue** [comment]
Hello @simme 

So far the synchronous approach has shown straightforward and efficient.

Users who need asynchronous behaviors can write asynchronous wrappers around the synchronous primitives if they want. That's what Swift extensions are for, and my recommendation.

> I realize it would be a pretty big job to wrap all methods to return promises and not something I expect to happen. Just curious if it's something you've even considered?

Yes it is a big job, and yes it has already been [considered (and rejected)](https://github.com/groue/GRDB.swift/issues/76). I think that it's easier said than done, for benefits I don't buy. Asynchronous methods can't easily express the `rethrows` qualifier of synchronous methods, for example. We'd also need to introduce a Result type, in an already crowded landscape. And the synchronous approach is *simpler*. GRDB aims at being a welcoming library, not a flagship for some fashionable patterns. It welcomes fashion, of course: in *your* extensions.

Swift is evolving. Language support for asynchronous constructs is expected for Swift 4 or 5. Be patient, and polish your views of promises (or futures, or reactive programming, or channels, or whatever gives you the thrill) in the meantime. A synchronous GRDB blends into all of those patterns, and I'm quite happy with that.

**Comment by simme** [comment]
That makes a lot of sense and seems perfectly reasonable. I was looking through the issue history looking for questions re async but somehow missed that issue you linked to.

I was mostly curious. Thank you for taking the time to answer thoroughly and thank you for a fantastic database framework! :)

**Comment by groue** [comment]
You're welcome @simme ! Happy GRDB ;-)
