### ISSUE TITLE
reader crashes app in macOS 15 (but works in macOS 14.6)

### ISSUE THREAD

**Issue by hansengj** [groue/GRDB.swift#1631]
### What did you do?

Upgraded GRDB package to latest version.

Made sure issue was not existing database:
Saved existing database, launched app which generates
the database with some tables populated. Relaunched app which
reads database and establishes some session state.

### What did you expect to happen?

reader works fine like it does with target macOS 14.6

### What happened instead?

With target macOS 15:
App crashed: Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)

### Environment

**GRDB flavor(s): GRDB (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version: 6.29.3
**Installation method: SPM using git URL (CocoaPods, SPM, manual?)
**Xcode version: 16
**Swift version: 5 (latest) NOT 6.
**Platform(s) running GRDB: macOS (iOS, macOS, watchOS?)
**macOS version running Xcode: 15

### Demo Project

Code: 
 private var dbWriter: (any DatabaseWriter)? 
 var dbReader: DatabaseReader {
        dbWriter!
 } 

Initialization code:
let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
let config = Configuration()
dbWriter  = try DatabasePool(path: "\(path)/assetManagerPlusDB.sqlite3", configuration: config)

dbReader.read crashes app

**Comment by groue** [comment]
Hello @hansengj,

This might well be the macOS version of #1619 or #1626.

**Comment by abournier** [comment]
> This might well be the macOS version of #1619 or #1626.

And I confirm also the same behaviour that on iOS:

Xcode 16 RC / macOS 15 target min: crash
Xcode 16 Beta 1 / macOS 15 target min: no crash

**Comment by hansengj** [comment]
I agree.

I strongly believe the bug is with macOS 15 given the proper behavior using macOS 14 and macOS 15 RC. 
Whether you can identify it and find a work around, or have to wait for Apple to fix the bug, remains to be seen.
I hope it is the former.

I would speculate that the GRDB reader relies on some underlying macOS code/API that has changed and is
causing the crash bug.

FYI, the code I provided to reproduce the error is  being executed in my app that is written entirely in SwiftUI and
Swift. I doubt if this is relevant. My desktop is a M1 macMini, which also shouldn't be relevant.

Regards,
Gil

**Comment by groue** [comment]
> I strongly believe the bug is with macOS 15 given the proper behavior using macOS 14 and macOS 15 RC. Whether you can identify it and find a work around, or have to wait for Apple to fix the bug, remains to be seen. I hope it is the former.

AFAIU, it is entirely in Apple's hands, and I can't do anything at the library level: https://mastodon.sdf.org/@mikeash/113136475433234842.

I recommend to avoid Xcode 16, or to use one of the known workarounds described here: https://github.com/groue/GRDB.swift/issues/1619#issuecomment-2351023394.

**Comment by hansengj** [comment]
At this point, I can make my targets iOS 17 and macOS 14. 

I assume you have made Apple aware of the bug. Please let everyone know when Apple fixes this bug in future OS updates.
If a compiler bug, then future Xcode updates.

The main reason to move the targets up a notch is to use Swift 6 and new SwiftUI features.

Thanks --Gil

**Comment by groue** [comment]
> I assume you have made Apple aware of the bug.

You should file a report at http://feedbackassistant.apple.com, regardless of your assumptions. And report the FB number here. Thank you.

**Comment by hansengj** [comment]
OK. Will do.
