### ISSUE TITLE
Loading an Identifiable record by ID from a view fails with 'no such table'

### ISSUE THREAD

**Issue by Jnosh** [groue/GRDB.swift#1648]
### What did you do?

Try to load an `Identifiable` record by ID from a **view**.

```swift
// Migration
try db.create(table: "item_table") { t in
    t.autoIncrementedPrimaryKey("id")
}
try db.create(view: "item", columns: ["id"], as: Table("item_table").all())

// Record type
struct Item: Equatable, Identifiable, Codable, FetchableRecord, TableRecord {
    var id: Int64
}

// Query
try dbWriter.read { db in
    try Item.fetchOne(db, id: 1)
}
```

### What did you expect to happen?

The query should succeed.

### What happened instead?

It fails with `SQLite error 1: no such table: <view name>`

I found an older issues about queries on views hitting the same error (#812). This seems to be another similar edge case.

It can be worked around by not filtering agains the primary key column(s) but instead providing the filter expression manually:

```swift
// This works
try Item.filter(Column("id") == 1).fetchAll(db)
```

As I understand it, to filter by ID, GRDB needs to know the primary key column(s) which it determines from the DB schema. But there is no schema for a view so this fails.
Unless I'm mistaken this isn't really fixable. GRDB would need something akin to `databaseTableName` that programmatically specifies the primary key column(s) for this and similar queries to work for views.

Feel free to close this issue if that is the case, at least this issue might help others searching for the same problem.

### Environment

**GRDB flavor(s):** Vanilla GRDB
**GRDB version:** 7.0.0-beta.2
**Installation method:** SPM via Xcode 
**Xcode version:** 16.1 beta 1
**Swift version:** 6.0.0
**Platform(s) running GRDB:** macOS 15.1 Beta 5
**macOS version running Xcode:** macOS 15.1 Beta 5

### Demo Project

[Demo Project](https://github.com/user-attachments/files/17250967/ViewFetchViaID.zip)

**Comment by groue** [comment]
Hello @Jnosh, thank you for this well-written issue.

> ```swift
> // This works
> try Item.filter(Column("id") == 1).fetchAll(db)
> ```

Yes 👍 

> As I understand it, to filter by ID, GRDB needs to know the primary key column(s) which it determines from the DB schema. 

Exactly.

> GRDB would need something akin to `databaseTableName` that programmatically specifies the primary key column(s) for this and similar queries to work for views.

Yes, you got it right. It is not a bad idea to allow `TableRecord` to customize this behavior:

```swift
protocol TableRecord {
    // New customization point
    // - precondition: the returned key must be an actual key.
    func defaultDatabaseKey(_ db: Database) throws -> SomeType
}
```

We must proceed with caution.

`TableRecord` and `TableRequest` get a `PrimaryKeyInfo` from [`Database.primaryKey(_:in:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/database/primarykey(_:in:)) in multiple occasions. For example:

```swift
Item.filter(id: 42)
Item.filter(...).orderByPrimaryKey()
```

There are also _niceties_ performed by the SQL builder. Not essential, but satisfying when we inspect the executed SQL:

```swift
// SELECT * FROM item LIMIT 1
try Item.fetchOne(db)

// SELECT * FROM item WHERE id = 42 LIMIT 1
try Item.filter(sql: "id = ?", arguments: [42]).fetchOne(db)

// -- Nicety: no LIMIT in the generated SQL
// SELECT * FROM item WHERE id = 42
try Item.filter(id: 42).fetchOne(db)
```

[`PrimaryKeyInfo`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/primarykeyinfo) has no public initializer. It contains much more information than just the names of the primary key columns. Some information is internal to GRDB such as whether a table is a `WITHOUT ROWID` table or not.

I don't know, as I'm writing right now, how much of this information is used when generating requests. We'd need to look at the code. This would help defining the minimum information that should be provided by the customisation we're talking about.

I also don't know, as I'm writing right now, how much of this information is not used yet, but could be used in the future. This would help designing a new API that can be eventually extended in a backward compatible way.

**Comment by groue** [comment]
Even if we do not allow customizing the default key, we could improve the error message. "No such table: item" is not very helpful. "View 'item' has no primary key" would be better.

**Comment by Jnosh** [comment]
Thank you for your thoughtful response!

A more specific error message would indeed be very helpful. 
For foreign keys GRDB fatalErrors when it can't automatically determine column names when views are involved, maybe something similar would be possible here as well?
This seems like an issue that probably always comes up during development and not dynamically so a fatalError might be fine and could include a longer message similar to the foreign key case while still throwing a regular error when no table or view exists for the record at all.

The future direction you outlined does indeed seem interesting but as you said, that is probably quite a bit more involved than adjusting the error message.

I can easily work around this current issue and I am likely to transition away from using a view in the case where I hit this issue in the first place so personally I don't have a direct need for this capability at the moment. So don't feel the need to prioritize this on my behalf. :-)

**Comment by groue** [comment]
The next GRDB version will raise a nice fatal error (2c49a69).

**Comment by Jnosh** [comment]
Tested my original code against the new beta and I get the new nice error, thank you!
