### ISSUE TITLE
compiler errors

### ISSUE THREAD

**Issue by Mopar440** [groue/GRDB.swift#165]
Using Xcode 8.0 /Swift3
I installed GRDB using cocoa pods.

I have not inserted any additional code into the project.
Running the simulator produces 2 build errors (line 7).
!Could not build Objective-C module 'SQLiteiPhoneSimulator'
!Header 'Applications/Xcode.app/Contents/Developer/Platform/SDKs/iPhoneSimulator.sdk/usr/include/sqlite3.h

Can you help clear up these errors??

```swift
import Foundation

#if !USING_BUILTIN_SQLITE
    #if os(OSX)
        import SQLiteMacOSX
    #elseif os(iOS)
        #if (arch(i386) || arch(x86_64))
            import SQLiteiPhoneSimulator // << Error here <<
        #else
            import SQLiteiPhoneOS
        #endif
    #elseif os(watchOS)
        #if (arch(i386) || arch(x86_64))
            import SQLiteWatchSimulator
        #else
            import SQLiteWatchOS
        #endif
    #endif
#endif
```

error below >>

```
module SQLiteiPhoneSimulator {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sqlite3.h"
    export *
}
```

**Comment by groue** [comment]
Cocoapods installation does not fail when I try. I suggest you keep on looking.

**Comment by swiftlyfalling** [comment]
@Mopar440: Where is your Xcode.app located, and what is it named?

The module map expects "/Applications/Xcode.app". If you have it located anywhere else, or (for example) have renamed it, you'll receive that error.

**Comment by groue** [comment]
Good point. That's indeed the [1st step](https://github.com/groue/GRDB.swift#cocoapods):

> 1. Make sure Xcode is installed in the /Applications folder, with its regular name Xcode.
> 2. Install cocoapods version 1.1 or higher
> 3. Specify in your Podfile:
> 
>     ```ruby
>     use_frameworks!
>     pod 'GRDB.swift'
>     ```

**Comment by Mopar440** [comment]
Xcode installed itself to folder 'desktop' my project folders end up on the 'desktop' ... do i need to reinstall Xcode?

**Comment by Mopar440** [comment]
I moved Xcode to the Applications folder, new project folders are still automatically placed on the desktop ...

**Comment by groue** [comment]
A regular Xcode can be moved freely: move Xcode (the application) into /Applications, and try again. The location of your project has no impact.

**Comment by Mopar440** [comment]
Thank you for your help!

**Comment by groue** [comment]
Happy GRDB!
