### ISSUE TITLE
Confusion About the Correct Usage Order of IFNULL and SUM

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1664]
Hi, @groue  I'm writing an SQL query to calculate the sum of a field, but the field a may contain NULL values. I've reviewed the documentation and searched for examples, but I'm still confused about how to correctly use the IFNULL expression.

```
var a: Int? = 0 // field

let request = TableName.select(sum(Column("a") ?? 0))

or ?

let request = TableName.select(sum(Column("a")) ?? 0)

return (try? Int.fetchOne(db, request)) ?? 0 // fetch
```

Specifically, I came across two codes where the order of SUM and IFNULL is different. I’m unsure whether SUM should be inside or outside of IFNULL. 

```
// s1
return try Int.fetchOne(db, sql: "SELECT IFNULL(SUM(value), 0) FROM \(table)")!
// s2
XCTAssertEqual(
            sql(dbQueue, tableRequest.select(count(Col.age ?? 0))),
            "SELECT COUNT(IFNULL(\"age\", 0)) FROM \"readers\"")
```

I would like clarification on which usage is more appropriate, or a detailed explanation to help me understand how to correctly use IFNULL and SUM in handling NULL values in calculations.

Thank you very much, all along.

**Comment by SF-Simon** [comment]
Specifically, I understand how SQLite handles these two. However, I am unclear about which one I should use in a GRDB expression, or if there is any difference between them in GRDB.

**Comment by groue** [comment]
Hello @SF-Simon,

I think both solutions gives exactly the same result. `IFNULL(SUM(value), 0)` has SQLite perform less work, because only the final NULL is replaced with 0, so I'd go (and I do in my own code) with `sum(Column("a")) ?? 0`.

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> I think both solutions gives exactly the same result. `IFNULL(SUM(value), 0)` has SQLite perform less work, because only the final NULL is replaced with 0, so I'd go (and I do in my own code) with `sum(Column("a")) ?? 0`.

I think using the same code as you may be safer. Hahahaha

thank you so much, groue.
