### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by gloparco** [groue/GRDB.swift#167]
When building the latest stable release, I am getting 21 warnings, each of which refers to a missing file.

Is this known, or might it be something wrong on my end?

Thanks, and keep up the great work!

/GRDB/Tests/Experimental/MappingTests.swift is missing from working copy
/GRDB/Core/DatabaseStore.swift is missing from working copy
/GRDB/Core/FetchRequest.swift is missing from working copy
/GRDB/QueryInterface/SQLFunction.swift is missing from working copy
/GRDB/Playgrounds/UserDefaults.playground/contents.xcplayground is missing from working copy
/GRDB/Playgrounds/DatabaseTimestamp.playground/contents.xcplayground is missing from working copy
/GRDB/Core/Support/Foundation/NSURL.swift is missing from working copy
/GRDB/Tests/Experimental/ManagedDataControllerTests.swift is missing from working copy
/GRDB/Playgrounds/UserDefaults.playground/Contents.swift is missing from working copy
/GRDB/Tests/Public/Record/RecordFetchTests.swift is missing from working copy
/GRDB/Tests/Public/Core/DatabasePool/DatabasePoolFileAttributesTests.swift is missing from working copy
/GRDB/Core/Support/Foundation/NSUUID.swift is missing from working copy
/GRDB/Support/GRDB-Swift2-ConversionHelper.swift is missing from working copy
/GRDB/Tests/Public/FetchRequest/FetchRequestTests.swift is missing from working copy
/GRDB/SQLiteCustom/README.md is missing from working copy
/GRDB/Core/Support/Foundation/NSDate.swift is missing from working copy
/GRDB/Tests/Public/Core/DatabaseQueue/DatabaseQueueFileAttributesTests.swift is missing from working copy
/GRDB/QueryInterface/SQLTableBuilder.swift is missing from working copy
/GRDB/QueryInterface/SQLOperator.swift is missing from working copy
/GRDB/Playgrounds/DatabaseTimestamp.playground/Contents.swift is missing from working copy
/GRDB/GRDB/QueryInterface/SQLCollation.swift is missing from working copy

**Comment by groue** [comment]
Hello @gloparco.

You are trying to build targets from the GRDB project. You are not applying one of the [installation methods](https://github.com/groue/GRDB.swift/blob/master/README.md#installation) to an application.

OK: download all git submodules, and open GRDB.xcworkspace This should fix your issues.

**Comment by gloparco** [comment]
Thanks Gwendal, but I had followed the installation instructions (for manual).  And I had been using GRDB for several months now, but only updated recently (instead of downloading the zip file, I am now using git pulls).

Anyway, I opened the workspace, but I get the same warnings in there.  I do have all submodules pulled as well: GRDBCipher, GRDBCustomerSQLite, Tests

But, as you can see, many of the files that are missing are in Core.

**Comment by gloparco** [comment]
It looks like 0.37.1 removed NSURL and other files.  I have the latest (v0.101.1), so I am not sure what is still looking for NSURL and other files.  Weird.

**Comment by groue** [comment]
Ah, I have a better picture now. You may suffer from an Xcode bug, and have to perform a "deep cleanup", which means not only the Derived Data folder, but also your personal xcuser directories filed inside the involved projects and workspaces. To see those personal directories that may well contain corrupt information, right click projects and workspaces in the Finder, and pick "Show Package Content".. Your projects and workspaces, and GRDB project and workspace.

After the deep cleanup, relaunch Xcode, and tell me if the problem is still there?

**Comment by gloparco** [comment]
Wow, I can't believe I never encountered that XCode bug before!  It turns out, in my case, that this happens when you delete files (remember, I had originally downloaded the zip file), and then clone the git repo.  It has to do with the fact that my changes were not checked into git and it confuses XCode.

So I committed my deleted files, re-cloned, and now I'm good to go.

Thanks for your help!  You can delete/close this issue if you would like.

**Comment by groue** [comment]
You're welcome @gloparco! Happy GRDB!
