### ISSUE TITLE
Error while observing changes

### ISSUE THREAD

**Issue by stoope** [groue/GRDB.swift#1671]
### What did you do?

I use `ValueObservation` to tracks changes.

### What did you expect to happen?

`ValueObservation` fetches the latest changes.

### What happened instead?

<img width="1234" alt="Screenshot 2024-11-20 at 16 03 15" src="https://github.com/user-attachments/assets/5c7ddba9-e4de-4a91-a22d-729f4e672326">

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.3
**Installation method:** SPM
**Xcode version:** 16.1
**Swift version:** 6
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:** iOS, macOS

### Demo Project

```
struct MainView: View {
    @State private var items: [Item] = []

    var body: some View {
          List(items) { item in
              Text(item.name)
          }
        .task {
            let observation = ValueObservation.tracking(Item.fetchAll)
            do {
                for try await items in observation.values(in: DBService.shared.dbWriter, scheduling: .immediate) {
                    self.items = items
                }
            } catch {
            }
        }
    }
}
```

The part above working fine on initial load but when I later try to insert new item I got the error.

```
try? await DBService.shared.dbWriter.write { db in
    let item = Item(name: "Test")
    try item.saved(db)
}
```

Any ideas of what do I miss here? I guess it is connected to swift 6 strict concurrency mode but I can't figure our why such a simple code doesn't work.

**Comment by Jnosh** [comment]
I checked the most recent Swift development snapshot and that no longer crashes in this example with GRDB 7.

So I think that crash is indeed a bug and it should be fixed in Swift 6.1.

**Comment by stoope** [comment]
Thanks @Jnosh!
Moving the fetch closure to a nonisolated function worked out.

> I would also recommend switching to GRDB 7 if you are compiling in Swift 6 mode. It's still in beta but IMO very stable and includes a lot of concurrency related improvements for use with the Swift 6 language mode.

Indeed, I started with GRDB 7 but downgraded once I encountered the bug.

**Comment by groue** [comment]
Thanks a lot @Jnosh for the explanation 👍
