### ISSUE TITLE
missing target with GUID 'PACKAGE-TARGET:GRDBSQLite

### ISSUE THREAD

**Issue by by123** [groue/GRDB.swift#1673]
Build target GRDB with configuration Debug
error: Unable to resolve build file: BuildFile<PACKAGE-TARGET:GRDB-5DC4DB053-dynamic::BUILDPHASE_1::0> (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:GRDBSQLite') (in target 'GRDB' from project 'GRDB')

Unable to resolve build file: BuildFile<PACKAGE-TARGET:GRDB-5DC4DB053-dynamic::BUILDPHASE_1::0> (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:GRDBSQLite')

Build failed    2024/11/22, 09:38    0.1 seconds

**Comment by groue** [comment]
Hello @by123,

Please open a [new issue](https://github.com/groue/GRDB.swift/issues/new) and fill in the form, thank you.

**Comment by groue** [comment]
See #1672 as well.
