### ISSUE TITLE
For encryption whether sqlcliper can be integrated separately, the developer can control the version？

### ISSUE THREAD

**Issue by BaronWj** [groue/GRDB.swift#1676]
### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

### Demo Project

For encryption whether sqlcliper can be integrated separately, the developer can control the version. thank you？

**Comment by groue** [comment]
> For encryption whether sqlcliper can be integrated separately, the developer can control the version. thank you？

I'm not sure I understand your question. Please see https://github.com/groue/GRDB.swift/discussions/1495.
