### ISSUE TITLE
Joining nested many-to-many relationships while filtering on a root record property?

### ISSUE THREAD

**Issue by alsaybar** [groue/GRDB.swift#1677]
### What did you do?

I'm trying to build a request that fetches a tree of data, going from Project -> Pipeline -> Branch -> Build.

Describing the data relationships:
- A project has many pipelines
- A pipeline may be run on many branches
- A branch has many builds
- A build belongs to a **branch and a pipeline**

Given the following dataset (foreign keys are in brackets):

```
Project A
Project B

Pipeline A[Project A]
Pipeline B[Project B]

Branch A
Branch B

BuildRun A[Branch A, Pipeline A]
BuildRun B[Branch B, Pipeline B]
BuildRun C[Branch B, Pipeline A]
``` 

I want a query that outputs a nested data structure like this: 

```
Project A
  Pipeline A[Project A]
    Branch A
      BuildRun A[Branch A, Pipeline A]
    Branch B
      BuildRun C[Branch B, Pipeline A]

Project B
  Pipeline B[Project B]
    Branch B
      BuildRun B[Branch B, Pipeline B]
```

But I'm getting this:

```
Project A
  Pipeline A[Project A]
    Branch A
      BuildRun A[Branch A, Pipeline A]
    Branch B
      BuildRun B[Branch B, Pipeline B] // This is wrong, does not belong to Pipeline A
      BuildRun C[Branch B, Pipeline A] 

Project B
  Pipeline B[Project B]
    Branch B
      BuildRun B[Branch B, Pipeline B] 
      BuildRun C[Branch B, Pipeline A] // This is wrong, does not belong to Pipeline B
```

Going forward, let's leave out Project, because there doesn't seem to be an issue fetching pipelines for a project.

My data model and associations look like this (I ommitted protocol conformances):

```swift
struct Pipeline {
    public let id: Id
    public let projectId: Project.ID

    static let branches = hasMany(Branch.self, through: buildRuns, using: BuildRun.branch)
    var branches: QueryInterfaceRequest<Branch> {
        request(for: Pipeline.branches)
    }

    static let buildRuns = hasMany(BuildRun.self)
    var buildRuns: QueryInterfaceRequest<BuildRun> {
        request(for: Pipeline.buildRuns)
    }
}

public struct Branch {
    let id: Id
    let label: String

    static let buildRuns = hasMany(BuildRun.self)
    var buildRuns: QueryInterfaceRequest<BuildRun> {
        request(for: Branch.buildRuns)
    }

    static let pipelines = hasMany(Pipeline.self, through: buildRuns, using: BuildRun.pipeline)
    var pipelines: QueryInterfaceRequest<Pipeline> {
        request(for: Branch.pipelines)
    }
}

public struct BuildRun {
    let number: Int
    let id: Id
    let branchId: Branch.ID
    let pipelineId: Pipeline.ID

    static let branch = belongsTo(Branch.self)
    var branch: QueryInterfaceRequest<Branch> {
        request(for: BuildRun.branch)
    }
    static let pipeline = belongsTo(Pipeline.self)
    var pipeline: QueryInterfaceRequest<Pipeline> {
        request(for: BuildRun.pipeline)
    }
}
```

Basically theres a many to many relation between pipelines and branches through build runs, and I suspect this is what's causing me headache.

The decoding struct and request looks like this:

```swift
public struct ProjectPipelines {
    public var project: Project
    public var pipelines: [PipelineBranches]

    public struct PipelineBranches {
        public var pipeline: Pipeline
        public var branches: [BranchBuildRuns]

        public struct BranchBuildRuns {
            public let branch: Branch
            public let buildRuns: [BuildRun]
        }
    }
}

let projectsWithPipelinesRequest = Project
                .including(all: Project.pipelines
                    .including(all: Pipeline.branches.distinct() // Maybe we can get rid of distinct as well?
                        .including(all: Branch.buildRuns)
                    )
                )
                .asRequest(of: ProjectPipelines.self)

let projectsWithPipelines = try projectsWithPipelinesRequest.fetchAll(db)
```

How can I filter/join build runs to make sure I only get records that belong to the correct branch? I tried to use a table alias on Pipeline and then apply a filter on the innermost include (`.filter(Column("workflowId") == pipelineAlias[Column("id")])`) without luck.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** 7.0.0-beta.6
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @alsaybar, 

I'm afraid to say that this is not expressible in the current state of the request API. 😬

Your best option is to filter the results, or to do "by hand" what the complex request does (in its entirety, or just the last fetch of `BuildRun`). Basically:

- Fetch all build runs filtered by the interesting branches and pipelines)
- Group them by pipeline and branch id (there's a `Dictionary` initializer that does just that)
- Hydrate the previously fetched data with those grouped build runs.

**Comment by groue** [comment]
The current [Associations Guide](https://github.com/groue/GRDB.swift/blob/v6.29.3/Documentation/AssociationsBasics.md) documents the missing feature:

> Note: you can't use the `including(all:)` method and use table aliases to filter the associated records on other records:
>
> ```swift
> // NOT IMPLEMENTED: loading all authors along with their posthumous books
> let authorAlias = TableAlias()
> let request = Author
>     .aliased(authorAlias)
>     .including(all: Author.books
>         .filter(Column("publishDate") >= authorAlias[Column("deathDate")]))    
> ```

I added the "needs revisiting" flag because while this issue is not quite a feature request, and there exists a workaround, it is the first time someone mentions the missing feature in an issue.

**Comment by alsaybar** [comment]
@groue Thank you for the swift response and follow-up explanation! Out of curiosity, wouldn't this be possible with a raw SQL query, since you have the context of all tables available to perform joins etc? (My SQL knowledge is rusty, so I might be wrong).

> Note: you can't use the including(all:) method and use table aliases to filter the associated records on other records:

I did encounter this in the docs, so thanks for confirming that this is indeed what's limiting me here. I'll be keeping an eye out to see if you some day get around to tackle this challenge 😉 

---

Anyways, I'll stop fighting to make this work and continue along the alternative solution you suggested! I think this the most complex case I will be handling for now – otherwise my experience with GRDB so far has been a real delight 👍

**Comment by groue** [comment]
> @groue Thank you for the swift response and follow-up explanation! Out of curiosity, wouldn't this be possible with a raw SQL query, since you have the context of all tables available to perform joins etc? (My SQL knowledge is rusty, so I might be wrong).

Sure! GRDB always generates raw SQL eventually. And you can write your own. For the above target request to work, someone just has to sit with a cup of their favorite hot beverage, write the desired SQL by hand, and find a way to generate it from the request ;-)

> > Note: you can't use the including(all:) method and use table aliases to filter the associated records on other records:
> 
> I did encounter this in the docs, so thanks for confirming that this is indeed what's limiting me here. I'll be keeping an eye out to see if you some day get around to tackle this challenge 😉

👍 

> Anyways, I'll stop fighting to make this work and continue along the alternative solution you suggested! I think this the most complex case I will be handling for now – otherwise my experience with GRDB so far has been a real delight 👍

Thank you very much! And thank you also for opening this issue. It's always great to hear first-hand experience, there's nothing more motivating for extending the library.
