### ISSUE TITLE
TransactionObserver databaseDidChange() called for FTS5 inserts

### ISSUE THREAD

**Issue by Jason-Abbott** [groue/GRDB.swift#1683]
### What did you do?

Added a `TransactionObserver` with an `observes()` implementation limiting observation to a subset of tables.

### What did you expect to happen?

I expected `databaseDidChange()` to be called only for the subset of tables matched in `observes()`.

### What happened instead?

Updates to virtual FTS5 tables (names ending with `_docsize` and `_data`) also triggered `databaseDidChange()`. I confirmed that updates to other regular (non-virtual) tables *were* correctly excluded on the basis of `observes()`. It doesn't appear that `observes()` is being called with the special FTS5 table names.

### Environment

**GRDB flavor(s):** Custom build to use a newer version of SQLite
**GRDB version:** latest 7.0 beta
**Installation method:**  Custom build
**Xcode version:** 16.1
**Swift version:** 6.0
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 15.1.1

### Demo Project

I only just began looking into the GRDB source so I'm mostly wondering if there's a quick answer here. Otherwise I don't mind digging in and maybe coming up with a PR.

**Comment by Jason-Abbott** [comment]
I just noticed a comment in GRDB source referencing a related issue https://github.com/groue/GRDB.swift/issues/620

**Comment by Jason-Abbott** [comment]
Always fast and detailed replies — you deserve some kind of GitHub badge 🙂

That is totally fine in my case. This is an integration with CKSyncEngine. I’m just now bringing all the parts together and saw a bunch of log warnings about unexpected tables hitting the engine. It already ignores them. Now that I understand the issue (thanks!) I’ll just turn off the warnings.

**Comment by groue** [comment]
Thank you! Detailed replies help me check and train my memory ;)

I'm glad the observation behavior does not create any problem in your app. Happy GRDB!
