### ISSUE TITLE
Column not found error when column shouldn't be requested

### ISSUE THREAD

**Issue by theoks** [groue/GRDB.swift#1684]
I encountered the following strange issue.

I have the following struct:

```swift
struct ServerConfigurationGRDB: Identifiable, Codable, TableRecord, FetchableRecord, PersistableRecord {
    static let databaseTableName = "server_configuration"
    var id: UUID
    var websiteURL: URL
}

extension ServerConfigurationGRDB {
    enum Columns {
        static let websiteURL = Column(ServerConfigurationGRDB.CodingKeys.websiteURL)
    }
}

```

Its table is created with the following migration:

```swift
try db.create(table: ServerConfigurationGRDB.databaseTableName) { t in
    // The `snakeCaseName` is a function to convert the name of the column in snake case, 
    // which I copied directly from the Swift `Foundation` repo.
    t.primaryKey(Column.id.snakeCaseName, .text)
    t.column(ServerConfigurationGRDB.Columns.websiteURL.snakeCaseName, .text)
        .notNull()
}
``` 

Then I initialize the DB as follows:

```swift
func initializeSQLite() async throws {
    var migrator = DatabaseMigrator()
    #if DEBUG
    migrator.eraseDatabaseOnSchemaChange = true
    #endif
        
    // Run migrations if any
    for migration in SQLMigration.allMigrations {
        // Run all migrations
    }
        
    try migrator.migrate(dbWriter)
        
    try await dbWriter.write { db in
        // The `try!` is only here to catch the error.
        let configuration = try! ServerConfigurationGRDB.fetchOne(db)
        if configuration == nil {
            // Create a configuration, if none found.
        }
    }
}
```

The first time the app runs, all migrations run normally, no configuration record is found, and one configuration is created.

The second time though I get a crash in line:
`let configuration = try! ServerConfigurationGRDB.fetchOne(db)`
with the following error:

> Fatal error: 'try!' expression unexpectedly raised an error: column not found: "relative" - row: [id:"8B678981-1713-415F-93A5-4987513640F1" website_url:"https://www.example.com" ], sql: `SELECT * FROM "server_configuration" LIMIT 1`, arguments: []

I found out that this issue manifests only when:
    a) I store a URL. Without the URL property the error doesn't happen.
    b) The column names are snake cased. If they are camel cased the error goes away.

I use the 7.0.0-beta6 version of the library, with Xcode 16.2, and a `DatabasePool`.

**Comment by theoks** [comment]
I experimented a little bit more, and I found out that the following extension eliminates the issue:

```
extension URL {
    /// Returns a TEXT database value containing the absolute URL.
    public var databaseValue: DatabaseValue {
        absoluteString.databaseValue
    }
    
    public static func fromDatabaseValue(_ dbValue: DatabaseValue) -> Self? {
        guard let string = String.fromDatabaseValue(dbValue) else {
            return nil
        }
        return URL(string: string)
    }
}
```

**Comment by groue** [comment]
Hello @theoks,

The `Decodable` facet of the configuration struct tries to decode the URL from the `websiteURL` column, which does not exist. This triggers a cascade of repair strategies, to no avail, that end up with URL trying to decode a `relative` column (also missing).

The root of the problem is the mismatch between the `websiteURL` property and the database column `website_url`.

According to Apple documentation [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types), a possible fix is a custom `CodingKeys` enumeration:

```swift
struct ServerConfigurationGRDB: Codable, Identifiable, FetchableRecord, PersistableRecord {
    static let databaseTableName = "server_configuration"
    var id: UUID
    var websiteURL: URL

    enum CodingKeys: String, CodingKey {
        case id, websiteURL = "website_url"
    }
}
```

(I took the liberty to remove `TableRecord`, implied from `PersistableRecord`).

**Comment by groue** [comment]
> I experimented a little bit more, and I found out that the following extension eliminates the issue

I don't quite understand. When I paste and run your code, this extension does not fix anything. Besides, implementations for those methods are supposed to be already provided by GRDB itself. I don't quite get it. Maybe you did not provide a full reproduction of your setup?

**Comment by theoks** [comment]
> > I experimented a little bit more, and I found out that the following extension eliminates the issue
> 
> 
> 
> I don't quite understand. When I paste and run your code, this extension does not fix anything. Besides, implementations for those methods are supposed to be already provided by GRDB itself. I don't quite get it. Maybe you did not provide a full reproduction of your setup?

Did you run the code on iOS 18 or earlier?

**Comment by theoks** [comment]
> Hello @theoks,
> 
> 
> 
> The `Decodable` facet of the configuration struct tries to decode the URL from the `websiteURL` column, which does not exist. This triggers a cascade of repair strategies, to no avail, that end up with URL trying to decode a `relative` column (also missing).
> 
> 
> 
> The root of the problem is the mismatch between the `websiteURL` property and the database column `website_url`.
> 
> 
> 
> According to Apple documentation [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types), a possible fix is a custom `CodingKeys` enumeration:
> 
> 
> 
> ```swift
> 
> struct ServerConfigurationGRDB: Codable, Identifiable, FetchableRecord, PersistableRecord {
> 
>     static let databaseTableName = "server_configuration"
> 
>     var id: UUID
> 
>     var websiteURL: URL
> 
> 
> 
>     enum CodingKeys: String, CodingKey {
> 
>         case id, websiteURL = "website_url"
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> (I took the liberty to remove `TableRecord`, implied from `PersistableRecord`).

Shouldn't the column decoders and encoders (I've set them to snake case) take care of this conversion automatically, without having to explicitly write all the keys as snake case?

**Comment by theoks** [comment]
@groue also thanks for the time you've taken to debug it. Really appreciate it.

**Comment by groue** [comment]
> Did you run the code on iOS 18 or earlier?

I ran it on my Mac (I'm still on Sonoma 14.6). 

> Shouldn't the column decoders and encoders (I've set them to snake case)

I don't see anything like that in the code you have shown.

Assuming you're using `DatabaseColumnDecodingStrategy.convertFromSnakeCase`, I'm sorry to say that I copied its implementation from [`JSONDecoder.KeyDecodingStrategy.convertFromSnakeCase`](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase), which decodes `website_url` into `websiteUrl`, not `websiteURL`. There are forum threads about this problem, such as [Roundtripping key coding strategies](https://forums.swift.org/t/roundtripping-key-coding-strategies/58494). I didn't try to make GRDB better than Foundation, here 🤷‍♂️

**Comment by theoks** [comment]
Yeah the roundtrip conversion, could be an issue here.

The reason I went ahead and added the protocol requirements on the `URL` type by hand, is because I thought there was something going on with the new Swift Foundation implementation in iOS18+ which still has some rough edges (and truth is that the error stopped happening for some reason when I did, at least on this platform).

But anyway, I reverted all table names and columns to camel case to avoid having to deal with snake case conversions.

**Comment by groue** [comment]
OK, @theoks. There is some kind of mystery around `URL`, but this issue does not contain a clear and self-contained path for reproduction. Since the main problem is solved since you could rename your tables and columns, I think the issue can be closed. Happy GRDB!
