### ISSUE TITLE
Session updates don't trigger observation

### ISSUE THREAD

**Issue by pnewell** [groue/GRDB.swift#1685]
### What did you do?

Use GRDB and GRDBQuery to observe changes to an sqlite database that occurred due to replaying a Session.

### What did you expect to happen?

As the session replays, each update/insert is reflected in database observations.

### What happened instead?

As the session replays, none of the updates/inserts are reflected in database observations. It is not until some other change occurs that all changes are then reflected.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 7.0 beta (but also seems to happen in older version I tried)
**Installation method:** spm
**Xcode version:** 16.1
**Swift version:** 6.0
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 15.2

### Demo Project

https://github.com/gerdemb/SQLiteChangesetSync (use Documentation/SQLiteChangesetSyncDemo/). To recreate you can Create a few players, push them to iCloud, reset DB (not CloudKit), then Fetch/Merge/Pull (nothing updates), create a new player, all the older players now show (plus the new one you created).

### Other Info
I also tested out the base GRDB Observation features, DatabaseRegionObservation didn't seem to work either, it looks like the only option currently is to TransactionObserver and then independently fetch the table each time which I imagine will be more overhead, but I am also curious why this wouldn't be working already since changes are in fact happening to the underlying Players table.

**Comment by groue** [comment]
Hello @pnewell,

> Use GRDB and GRDBQuery to observe changes to an sqlite database that occurred due to replaying a Session.

I assume you are talking about the [Session Extension](https://www.sqlite.org/sessionintro.html).

> As the session replays, none of the updates/inserts are reflected in database observations. It is not until some other change occurs that all changes are then reflected.

Indeed GRDB observation does not detect changes that are not performed through GRDB APIs.

But you can help `ValueObservation` refresh after such undetected changes were performed. See the [Dealing with Undetected Changes](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation#Dealing-with-Undetected-Changes) section of the `ValueObservation` documentation, and the `notifyChanges` method. This method was added after #1457, a previous discussion that describes the exact same problem. You'll get more context there.

**Comment by pnewell** [comment]
Yes, thank you, this was exactly what I needed! Thank you for building such a comprehensive library
