### ISSUE TITLE
.order(sql: "RANDOM()")

### ISSUE THREAD

**Issue by jubishop** [groue/GRDB.swift#1686]
is there anything built-in to GRDB to use besides saying:

```
.order(sql: "RANDOM()")
```

it works, I just like strong type safety.  :)

**Comment by groue** [comment]
Hello @jubishop,

There is no built-in method, no. But you can define your own:

```swift
extension DerivableRequest {
    func shuffled() -> Self {
        order(sql: "RANDOM()")
    }
}

// Usage
let randomPlayer = try Player.all().shuffled().fetchOne(db)
```

I don't know if `shuffled()` should become public and enter the list of [methods that control the ORDER BY clause](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/derivablerequest#The-ORDER-BY-Clause). I don't fully understand the statistical and performance aspects of `ORDER BY RANDOM()`, and I'm not sure it is a good built-in default.

**Comment by jubishop** [comment]
Thanks I'll use that!
