### ISSUE TITLE
including(all:) into OrderedSet

### ISSUE THREAD

**Issue by jubishop** [groue/GRDB.swift#1687]
My understanding is that `including(all:` only feeds into Sets or Arrays right now.  Any way to make it feed into an OrderedSet, where I can have the benefit of both specifying order and having O(1) look ups :)

**Comment by jubishop** [comment]
additionally, any way I could actually feed it into a Dictionary, keyed off a specific column in the record ?

**Comment by groue** [comment]
Hello @jubishop,

You are talking about [`OrderedSet`](https://github.com/apple/swift-collections/blob/main/Documentation/OrderedSet.md) from apple/swift-collections, right? The [GRDB doc for `including(all:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall) says:

> The associated records can be stored into an `Array` as in the above example, but also a `Set`, and generally speaking any decodable Swift collection.

`OrderedSet` conforms to Decodable [when its elements are Decodable themselves](https://github.com/apple/swift-collections/blob/1.1.4/Sources/OrderedCollections/OrderedSet/OrderedSet%2BCodable.swift#L23).

So I think it should work out of the box (I didn't try).

> additionally, any way I could actually feed it into a Dictionary, keyed off a specific (unique and not-null) column in the table ?

No, there is no such thing. GRDB completely relies on `Decodable` here. There is no built-in way to decode a JSON array of objects into a Dictionary, right? For the same reason, there is no built-in way to decode an array of database rows into a Dictionary.

It is possible to write some kind of wrapper that performs the custom decoding you need, though.

There is even a ready-made one: `IdentifiedArray` from https://github.com/pointfreeco/swift-identified-collections. It is an ordered collection, with O(1) lookup by id:

```swift
import IdentifiedCollections

struct TeamAndPlayers: Decodable {
  var team: Team
  var player: IdentifiedArrayOf<Player>
}
```

**Comment by groue** [comment]
You're welcome! I'm closing this issue, but please reopen if something does not work as expected!

**Comment by groue** [comment]
Extra bonus. In some apps, I want to fetch an `IdentifiableArray` instead of the plain array returned by `fetchAll(db)`.

To this end, I added this little extension:

```swift
import GRDB
import IdentifiedCollections

extension FetchRequest where RowDecoder: FetchableRecord & Identifiable {
    /// For example:
    ///
    /// ```
    /// let players = try Player.all().fetchIdentifiedArray(db)
    /// ```
    public func fetchIdentifiedArray(_ db: Database) throws -> IdentifiedArrayOf<RowDecoder> {
        try IdentifiedArray(fetchCursor(db))
    }
}
```

**Comment by jubishop** [comment]
I wanted to key off a value other than \.id and I think I have it working but I wonder if you'd be willing to critique my approach.  (this is only my second month writing Swift...).  The Episode class has a `guid` attribute.  This seems to work in my testing, but I'm not sure if there's a cleaner or better way...

```
struct PodcastSeries: Decodable, FetchableRecord, Equatable {
  let podcast: Podcast
  let episodes: IdentifiedArray<String, Episode>

  // MARK: - Decodable

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    podcast = try container.decode(Podcast.self, forKey: .podcast)
    self.episodes = IdentifiedArray(
      uniqueElements: try container.decode([Episode].self, forKey: .episodes),
      id: \Episode.guid
    )
  }

  private enum CodingKeys: String, CodingKey {
    case podcast, episodes
  }
}
```

**Comment by groue** [comment]
This looks correct to me. It is normal that you have to perform this manual decoding, because nobody (no Swift code) knows that an episode is identified by its guid.

If `guid` was renamed to `id` (and probably made the primary key of the database table for episodes), then `Episode` could adopt the Identifiable protocol. Identifiable unlocks some conveniences, because now Swift code "knows" that an episode is identified by its `id`. I think this could remove the need for this manual decoding.

Anyway. You don't have to do this (rename `guid` and all this refactoring). Your current code looks just right.

**Comment by jubishop** [comment]
Thanks!  Yeah this table already also has an id attribute that it's Identifiable with.  Technically guids in the podcast rss protocol can only be trusted to be unique per podcast series, which works here since my IdentifiableArray of episodes will always be in the same Podcast series, just wouldn't work globally.  Thanks again!

**Comment by jubishop** [comment]
(And yes a guid really should be "globally unique" but having inspected the contents of many podcast rss feeds they cannot be trusted to be that reasonable 🤣)

**Comment by groue** [comment]
Got it! It looks you are doing just fine :-)
