### ISSUE TITLE
sqlite3_close_v2 crash with NSFileProtectionComplete

### ISSUE THREAD

**Issue by kylemay-gridstone** [groue/GRDB.swift#1688]
### What did you do?

1. Create a database file that is stored on disk with `NSFileProtectionComplete`
2. In the background while the device is locked, deallocate and therefore deinitialize the `DatabasePool`

### What did you expect to happen?

App to not crash

### What happened instead?

App crashed (`EXC_BAD_ACCESS`), presumably because the file protection prevents access to the database. Also seeing this in the console:

```
os_unix.c:44053: (1) seekAndRead(/private/var/mobile/Containers/Shared/AppGroup/7855FD09-E8E4-4BA1-AC6B-6ACA057C6D69/database.sqlite-wal) - Operation not permitted
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v6.29.1
**Installation method:** SPM
**Xcode version:** 16.1
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 15.2

**Comment by groue** [comment]
Hello @kylemay-gridstone,

I'm sorry you're seeing a crash in `sqlite3_close_v2()`. I'm not sure anything can be done at the GRDB level. Maybe you can try to relax the protection level, or to avoid closing the database connection?

**Comment by groue** [comment]
You might get more information by setting the error log:

```swift
// To be called early in the lifetime of your application:
Database.logError = { (resultCode, message) in
    print("SQLite error \(resultCode): \(message)")
}
```

Explicitly closing the connection before deallocating it may provide more information as well (and it calls `sqlite3_close` instead of `sqlite3_close_v2`):

```swift
try dbPool.close()
```

**Comment by groue** [comment]
No news is good news: I suppose the issue has magically solved itself. Happy 2025!
