### ISSUE TITLE
How to open a database embedded as a resource in my application?

### ISSUE THREAD

**Issue by cafuni** [groue/GRDB.swift#17]
I have copied a SQLITE file in my project...
how can i set the path to use the library?

thank you

**Comment by groue** [comment]
Hello @cafuni 

To open a SQLite file that you have copied in your project, you can:

1. Make sure that the database file is embedded as a resource in your application, by selecting your database file in the left pane of the Xcode window, and checking your target in the right pane, under the Target Membership section.

2. Open your database, given its path:
    ```swift
    // Assuming the database file is named "database.sqlite":
    let databasePath = NSBundle.mainBundle().pathForResource("database", ofType: "sqlite")!
    let dbQueue = try DatabaseQueue(path: databasePath)
    ```

**Comment by cafuni** [comment]
<img width="1280" alt="screenshot 2016-01-12 12 19 52" src="https://cloud.githubusercontent.com/assets/15674190/12262766/27aa9802-b92a-11e5-88c4-166d65f28a73.png">

how can i fix this?

**Comment by groue** [comment]
I do not give Swift courses for free. The answers to your questions are abundantly documented by Apple, and it's high time you gave it a serious look before you keep on coding in the dark: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html.

**Comment by MonaHammad** [comment]
Hi @groue 
I'm already doing this but the app is copying the database every time I build the app, and the database updates is lost, how to fix that?

**Comment by groue** [comment]
@MonaHammad: isn't the answer in your question? Just don't copy the database each time.

**Comment by MonaHammad** [comment]
@groue 
I wasn't obvious actually, I thought it's handled by DatabaseQueue initialization, as it wasn't mentioned at all in the documentation.
I used a file manager and here is the code in case any one have the same issue.


    var configuration = Configuration()
    configuration.readonly = false
    configuration.foreignKeysEnabled = true // Default is already true
    configuration.trace = { print($0) }     // Prints all SQL statements
    
    let dbResourcePath = Bundle.main.path(forResource: "e_book_db", ofType: "sqlite")

    let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0] as String
    let url = NSURL(fileURLWithPath: path)
    let dbFilePath = url.appendingPathComponent("e_book_db.sqlite")?.path
    let fileManager = FileManager.default
    if  fileManager.fileExists(atPath: dbFilePath!) {
        print("FILE AVAILABLE")
    } else {
        print("FILE NOT AVAILABLE ... Copying")
        try fileManager.copyItem(atPath: dbResourcePath!, toPath: dbFilePath!)
    }
    
    dbQueue = try DatabaseQueue(path: dbFilePath!,configuration: configuration)

**Comment by groue** [comment]
Glad you found your solution, @MonaHammad ! There is also a FAQ: [How do I open a database stored as a resource of my application?](https://github.com/groue/GRDB.swift#how-do-i-open-a-database-stored-as-a-resource-of-my-application)

**Comment by MonaHammad** [comment]
Oh, thanks! I did't see it before you are really covering all the details.
Thanks for support and quick response.
