### ISSUE TITLE
foreign_key_check on transaction commit

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#172]
In several apps I work on, I have a pattern of deferring foreign keys during transactions which write the result of the synchronisation engine. But when the commit generates a foreign key error, I'd like to be able to grab the problematic lines out of the database before it's rollbacked.

Pseudo-code:
```
public func inTransactionWithDeferredForeignKeys(_ kind: TransactionKind? = nil, _ block: () throws -> TransactionCompletion) throws {
    // Begin transaction
    try beginTransaction(kind)
    try execute("PRAGMA defer_foreign_keys = 1")
        
    // Now that transaction has begun, we'll rollback in case of error.
    // But we'll throw the first caught error, so that user knows
    // what happened.
    var firstError: Error? = nil
    let needsRollback: Bool
    do {
        let completion = try block()
        switch completion {
        case .commit:
            try commit()
            needsRollback = false
        case .rollback:
            needsRollback = true
        }
    } catch {
        firstError = error
        needsRollback = true
    }

    if let firstError = firstError, firstError.code == 787 { // requires extended error codes
        // GET foreign key constraints failing and return in an error
        let foreignKeyOccurrences = try execute("PRAGMA foreign_key_check")
        throw ForeignKeyErrors(occurrences: foreignKeyOccurrences)
    }
        
    if needsRollback {
        do {
            try rollback(underlyingError: firstError)
        } catch {
            if firstError == nil {
                firstError = error
            }
        }
    }

    if let firstError = firstError {
        throw firstError
    }
}
```

**Comment by groue** [comment]
Hello @hartbit,

> In several apps I work on, I have a pattern of deferring foreign keys during transactions which write the result of the synchronisation engine.

Yes. One sometimes also destroys and later recreate unique indexes. Anyway, I understand and support your use case.

> But when the commit generates a foreign key error, I'd like to be able to grab the problematic lines out of the database before it's rollbacked.

Why don't you run `PRAGMA foreign_key_check` before committing the transaction? It will perform checks even after `PRAGMA foreign_keys = OFF`:

```swift
// Quick code, not verified
try dbQueue.inDatabase { db in
    try db.execute("PRAGMA defer_foreign_keys = OFF")
    defer {
        try db.execute("PRAGMA defer_foreign_keys = ON")
    }
    try db.inTransaction {
        ...
        let foreignKeyOccurrences = Row.fetchAll(db, "PRAGMA foreign_key_check")
        guard foreignKeyOccurrences.isEmpty else {
            throw ForeignKeyErrors(occurrences: foreignKeyOccurrences)
        }
        return .commit
    }
}
```

You can add this as a custom GRDB extension. If I'm right suspecting that you need the list of failed foreign keys when you are debugging (either debugging your app, or your synchronization server), meaning that this code won't ship in your production app, I'm not sure that this extension deserves a public GRDB API.

Feel free to discuss or invalidate my intuitions, of course.

**Comment by hartbit** [comment]
> You can add this as a custom GRDB extension. If I'm right suspecting that you need the list of failed foreign keys when you are debugging (either debugging your app, or your synchronization server), meaning that this code won't ship in your production app, I'm not sure that this extension deserves a public GRDB API.

Makes a lot of sense. But I want to be able to leave the check in production and not pay the price of checking for successful transactions, hence the wish to check only on a commit error. I do this in a `FMDB` app of mine because the data sent by the server sometimes contains inconsistencies which generate foreign key constraint errors I enjoy being able to see exactly what went wrong to tell the server guys.

**Comment by groue** [comment]
> I do this in a FMDB app of mine because the data sent by the server sometimes contains inconsistencies which generate foreign key constraint errors I enjoy being able to see exactly what went wrong to tell the server guys.

All right.

> But I want to be able to leave the check in production and not pay the price of checking for successful transactions, hence the wish to check only on a commit error.

The check will happen anyway, you know that.

BTW, I only knew `foreign_keys`, and overlooked your usage of `defer_foreign_keys` in your initial comment. Thanks for letting me know about this one.

I think the two following SQL sequences are exactly equivalent, both in terms of functionality, and performance:

```sql
BEGIN TRANSACTION
PRAGMA defer_foreign_keys = 1
...
COMMIT -- assume error
PRAGMA foreign_key_check -- error details
ROLLBACK
```

```sql
PRAGMA foreign_keys = OFF
BEGIN TRANSACTION
...
PRAGMA foreign_key_check -- assume non empty list
ROLLBACK
PRAGMA foreign_keys = ON
```

The difference is that the first (your proposal) isn't possible with current GRDB API, when the second can be achieved with the current GRDB API:

```swift
struct ForeignKeyErrors : Error {
    let occurrences: [Row]
}

extension Database {
    func inTransactionWithDeferredForeignKeys(_ kind: TransactionKind? = nil, _ block: () throws -> TransactionCompletion) throws {
        try execute("PRAGMA foreign_keys = OFF")
        defer {            
            try! execute("PRAGMA foreign_keys = ON") // Not supposed to fail
        }
        try inTransaction(kind) {
            let completion = try block()
            if completion == .commit {
                let rows = try Row.fetchAll(self, "PRAGMA foreign_key_check")
                guard rows.isEmpty else {
                    throw ForeignKeyErrors(occurrences: rows)
                }
            }
            return completion
        }
    }
}
```

Am I mistaken?

Oh, and your `inTransactionWithDeferredForeignKeys` implementation leaves the transaction open if there is a foreign key error - this is fixed in the sample code above.

**Comment by hartbit** [comment]
> The check will happen anyway, you know that.

Yes, but I was worried that it would duplicate that check: once manually, and once by the system on commit. But if you think that the performance cost is either negligible or non-existent if the system recognises that the check has been done and bypasses it, I'm happy with your suggestion for doing it with the current GRDB api :)

**Comment by groue** [comment]
> Yes, but I was worried that it would duplicate that check

I was concerned about that, too. But I really think that SQLite will happily commit failed foreign keys when `PRAGMA foreign_keys` is false (meaning: it won't check at all).

The extension I suggest performs foreign key check, then commits, and finally restore automatic checks: I thus think that it doesn't perform double check.

Stand by my words for now. I'll perform a deeper verification.

**Comment by hartbit** [comment]
By the way, how would you integrate this new `Database` function with `DatabaseWriter`s? We probably need to wrap it inside a custom write function, which serialises the call. But not sure it can be done without modifying GRDB. Thoughts?

**Comment by groue** [comment]
@hartbit The topic of deferred foreign key checks need polish, and it doesn't pass the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) yet. It's too early to even wonder if this extension should be a part of GRDB. Today, it lives very well as an extension in your app, doesn't it? Good.

Next, the scope of DatabaseWriter and DatabaseReader is limited. Those are *not* protocols intended to be used by an application. Those are protocols intended to provide concurrency primitives for reusable pieces of code that accept both database queues and pools. They are not a sink for convenience methods. Read again the [section of the README](https://github.com/groue/GRDB.swift#databasewriter-and-databasereader-protocols) that talks about them, and especially:

> As seen above, [those] protocols actually make applications harder to write correctly.

**Comment by hartbit** [comment]
Ok, I'll rephrase my question. I don't use the above extension of Database in my application because I can't figure out how to wrap it in a queue elegantly. Is it enough to wrap it in a write?

**Comment by groue** [comment]
> Ok, I'll rephrase my question. I don't use the above extension of Database in my application because I can't figure out how to wrap it in a queue elegantly. Is it enough to wrap it in a write?

What about using it first, and maybe make it elegant later?

```swift
try dbQueue.inDatabase { db in
    try db.inTransactionWithDeferredForeignKeys() {
        ...
        return .commit
    }
}
```

Now it's clear that it's not that complicated to wrap, after all:

```swift
extension DatabaseQueue {
    func inTransactionWithDeferredForeignKeys(...) throws {
        inDatabase { db in
            db.inTransactionWithDeferredForeignKeys(...)
        }
    }
}

try dbQueue.inTransactionWithDeferredForeignKeys { db in
    ...
    return .commit
}
```

**Comment by hartbit** [comment]
Elegant was the wrong word. I was looking for a solution which was thread-safe and wasn't quite sure what DatabaseQueue to wrap it with. Thanks!

**Comment by groue** [comment]
Great :-) Tell me if this works as expected!

**Comment by groue** [comment]
> I was looking for a solution which was thread-safe

With DatabaseQueue, it's all about the `inDatabase` method. As long as something is wrapped in it, it's serialized in a protected dispatch queue, and thread-safe. All other convenience methods, such as `inTransaction`, wraps it.

**Comment by groue** [comment]
@hartbit, my tests below confirm that the technique [above](https://github.com/groue/GRDB.swift/issues/172#issuecomment-282511719) works, in that it defers foreign key checks, eventually raises foreign keys errors, and prevents double checks.

First, the setup:

```swift
try db.execute("CREATE TABLE parents (id INTEGER PRIMARY KEY)")
try db.execute("CREATE TABLE children (parentId INTEGER REFERENCES parents(id))")
```

Foreign key checks are in place:

```swift
do {
    try db.execute("INSERT INTO children VALUES (1)")
} catch {
    // SQLite error 787 with statement `INSERT INTO children VALUES (1)`: FOREIGN KEY constraint failed
    print(error)
}
```

If we disable foreign key checks *inside* the transaction, it doesn't work. Foreign keys checks are not defered despite the pragma:

```swift
try db.execute("BEGIN TRANSACTION")
try db.execute("PRAGMA foreign_keys = OFF")
do {
    try db.execute("INSERT INTO children VALUES (1)")
} catch {
    // SQLite error 787 with statement `INSERT INTO children VALUES (1)`: FOREIGN KEY constraint failed
    print(error)
}
try db.execute("ROLLBACK")
```

If we disable and enable foreign key checks *around* the transaction, as in the sample code, it works. The code below *commits* erroneous data to prove that SQLite doesn't perform any extra check:

```swift
try db.execute("PRAGMA foreign_keys = OFF")
try db.execute("BEGIN TRANSACTION")
try db.execute("INSERT INTO children VALUES (1)")       // no error
try print(Row.fetchAll(db, "PRAGMA foreign_key_check")) // [<Row table:"children" rowid:1 parent:"parents" fkid:0>]
try db.execute("COMMIT")                                // no error
try print(Row.fetchAll(db, "SELECT * FROM children"))   // [<Row parentId:1>]
try db.execute("PRAGMA foreign_keys = ON")              // no error
```

I think this issue is resolved.

**Comment by hartbit** [comment]
@groue Thanks for the confirmation!
