### ISSUE TITLE
Record persistenceConflictPolicy

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#173]
As `Record` does not implement `persistenceConflictPolicy`, it gets the default implementation from  the `MutablePersistable` protocol extension, and there is no way to change it after that. What is worse is that copy/pasting the example from the documentation into a `Record` subclass compiles fine but fails to work at runtime:

```
class RecordSubclass : Record {
    // usual stuff
    static let persistenceConflictPolicy = PersistenceConflictPolicy(insert: .replace, update: .replace)
}
```

We should probably implement it in Record so that the above code fails to compile and notifies the user to implement an override property:

```
open class Record : RowConvertible, TableMapping, Persistable {
    // implementation ...

    open class var persistenceConflictPolicy: PersistenceConflictPolicy {
        return PersistenceConflictPolicy(insert: .abort, update: .abort)
    }
}
```

**Comment by hartbit** [comment]
PR: #174

**Comment by groue** [comment]
Thanks for the report, @hartbit!

Something is clearly wrong, and some tests are missing.

I'll have a look at this issue, and the others you have created, in a few days. I have no access to any computer right now. Hold on!

**Comment by hartbit** [comment]
I wrote the PR to fix it. I'll write some tests too if you want :)

**Comment by groue** [comment]
Let's close this issue, and continue on #174 instead.
