### ISSUE TITLE
Override Record.save()

### ISSUE THREAD

**Issue by olivierpascal** [groue/GRDB.swift#177]
Hi, thanks for this amazing lib. I want to provide custom Record implementation (ie: a SyncedRecord that is also designed to be subclassed). Whenever a SyncedRecord is saved, I need to set some header flags (ie: toSync = true). In this purpose, I want to override save() to prevent users calling directly this method without setting the flags:

```
override func save(db: Database) {
  // Set some flags
  super.save(db)
}
```

However, save() is final in Record. I can't either make my own Record class because it uses some internal methods.

Is there any recommended design pattern for this purpose?

**Comment by groue** [comment]
Hello, @olivierpascal 

Quoting [Customizing Persistence Methods](https://github.com/groue/GRDB.swift#customizing-the-persistence-methods):

> When you subclass Record, you simply have to override the customized method, and call `super`

So you're on the right track. Yet a few lines below, you'll read:

> Note: it is recommended that you do not implement your own version of the `save` method. Its default implementation forwards the job to `update` or `insert`: these are the methods that may need customization, not save.

Record enforces this recommendation by making `save` final. So here is your solution:

```swift
override func update(_ db: Database, columns: Set<String>) throws {
    setSomeFlags()
    try super.update(db, columns: columns)
}

override func insert(_ db: Database) {
    setSomeFlags()
    try super.insert(db)
}

private func setSomeFlags() {
    ...
}
```

This way, the three methods `save`, `insert`, and `update` will properly set the flags:

```swift
try stuff.save(db) // flags are set
```

**Comment by olivierpascal** [comment]
Thank you so much Groue. I cannot believe I didn't notice that!

**Comment by groue** [comment]
Happy GRDB!
