### ISSUE TITLE
Using array in SQL arguments

### ISSUE THREAD

**Issue by Chiliec** [groue/GRDB.swift#18]
I'd like to use in sql expressions with array:
```swift
// SELECT * FROM table WHERE id IN (1,2,3,5,8)
db.execute("SELECT * FROM table WHERE id IN (?)", arguments: [[1,2,3,5,8]] )
```
but I get an error: 
`Contextual type 'DatabaseValueConvertible' cannot be used with array literal`
What do you think about this?

**Comment by groue** [comment]
Hello @Chiliec 

GRDB supports your precise use case through the [RowConvertible protocol](https://github.com/groue/GRDB.swift#rowconvertible-protocol):

```swift
struct Book: RowConvertible, DatabaseTableMapping {
    static func databaseTableName() -> String { return "table" }
    static func fromRow(row: Row) -> Book {
        return Book(...)
    }
}

dbQueue.inDatabase { db in
    // SELECT * FROM table WHERE id IN (?,?,?)
    let books = Book.fetchAll(db, keys: [1,2,3])
}
```

More generally speaking, I wish GRDB would support arrays in arguments. I even sent a [pull request](https://github.com/ccgus/fmdb/pull/180) to FMDB which exactly supports this feature.

But I don't know how to make Swift accept as arguments an array of values or arrays of values:

```swift
// Swift can't express the type of [1,[2,3,4]]
db.execute("SELECT * FROM table WHERE  x > ? AND y IN (?)", arguments: [1,[2,3,4]])
```

Precisely speaking, Swift supports the `[1,[2,3,4]]` literal thanks to Foundation. But it fails to compile values that NSArray would not support (nil, enum cases, etc.):

```swift
import Foundation
let a = [1, [2,3,4]]    // Array<NSObject>
let b = [nil, [2,3,4]]  // error: type of expression is ambiguous without more context
```

**Comment by groue** [comment]
@Chiliec: I'm closing this issue since you did not answer, and since Swift actively prevents us from implementing your feature request.

**Comment by siuying** [comment]
@groue I noticed ``collection.contains(column)`` worked for select statement, but what if I want to do an update like this? 

```
db.execute("UPDATE table SET state = ? where id in (?)", arguments: ["completed", [1,2,3,5,8]] )
```

**Comment by groue** [comment]
Hello @siuying

For SQLite a `?` placeholder represents a *simple value*, and can't be used for an array.

A request such as `UPDATE table SET state = ? where id in (?)` must thus be written as `UPDATE table SET state = ? where id in (?,?,...)`, where the `IN` operator is followed by as many question marks as there are ids.

Following the same idea, the arguments to a query are only made of values, and won't accept arrays. Each value in a query arguments matches its own `?` in the SQL query, from left to right.

You would thus write something like:

```swift
let ids = [1,2,3,5,8]
let questionMarks = repeatElement("?", count: ids.count).joined(separator: ",")
let query = "UPDATE t SET state = ? WHERE id IN (\(questionMarks))"
var arguments: StatementArguments = ["completed"]
arguments += StatementArguments(ids)
print(arguments) // Prints ["completed", 1, 2, 3, 5, 8]
try db.execute(query, arguments: arguments)
```

**Comment by siuying** [comment]
Thank you for your pointer! I don't know where do I get the idea I can use array here... everything make sense now, thanks again!

**Comment by martindufort** [comment]
Is this still the recommend mechanism of injecting an array of IDS into an `IN` clause ?

**Comment by groue** [comment]
When you build a raw SQL string, you have to embed as many question marks as there are arguments. That's how SQLite interprets SQL:

```swift
let ids = [1, 2, 3]
let questionMarks = databaseQuestionMarks(count: ids.count)
let sql = "SELECT * FROM player WHERE id IN (\(questionMarks))"
let arguments = StatementArguments(ids)
let players = try Player.fetchAll(db, sql: sql, arguments: arguments)
```

You can also use [SQL Interpolation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md):

```swift
let ids = [1, 2, 3]
let request: SQLRequest<Player> = "SELECT * FROM player WHERE id IN \(ids)"
let players = try Player.fetchAll(db, request)
```

**Comment by smhk** [comment]
I've been thinking this out, would it be possible to have a sort of "super-interpolator" ..

```
let syncor = try db.makeStatement(sql: "delete from blah where group = ? and sid not in (?))
try syncor.hyperspaceExecute(arguments: ["dogs", ra])
```

hyperspaceExecute does seven things,

1. It understands all statements where an ? must be a list (such as the second ? in the example)
2. it knows that `sid` is (say) an `Int64`
3. it looks at `ra`, and ensures it is an array or perhaps Set (detail: no nulls, arguably not empty, etc etc)
4. it ensures that the type of `ra` is indeed correct, `Int64` in the example
5. it figures out how many question marks are needed (due to this particular `ra`) and modifies the statement thus so. (Yes, efficiency is lost, you can no longer `makeStatement` once and use it efficiently zillions of times)
6. it expands out the `ra` appropriately in an appropriate `execute#arguments`
7. cheer

I'm just wondering if I missed something?

(This would fix one of the most annoying bugbears in sql eh!)

**Comment by groue** [comment]
> It understands all statements where an ? must be a list (such as the second ? in the example)

This would require an SQL parser. SQLite does not ship with an SQL parser, and I have tried very hard to avoid depending on any one. The net advantage is that one does not need a new GRDB version when the version of the underlying SQLite library changes, and the SQL grammar evolves. I prefer planning against planned obsolescence :-)

The `databaseQuestionMarks` function, and SQL interpolation, both mentioned above, are the GRDB solution to this problem. I'd gladly welcome suggestions to improve those, but I will reject anything that requires parsing.
