### ISSUE TITLE
App crashes on "override func didInsert()"

### ISSUE THREAD

**Issue by tuananh2311** [groue/GRDB.swift#184]
Hi all

FYI I'm using the latest version (0.102.0) and it's only happening on real device, but works fine on the simulator.

The app crashes after a new record got inserted and GRDB returns the ID

**override func didInsert(with rowID: Int64, for column: String?) {**
        id = rowID
}

There was no error or stacktrace but the value of "column" is "unable to read data"

Does anyone know what happened and how to fix this?

Thanks,

**Comment by groue** [comment]
Hello @tuananh2311.

Please provide the full stack trace of the error, including the precise error message, as well as the declaration of the database table in which you insert.

**Comment by groue** [comment]
> There was no error or stacktrace but the value of "column" is "unable to read data"

Ah, sorry, there is no error.

What do you mean by 'the value of "column" is "unable to read data"'?

**Comment by tuananh2311** [comment]
@groue This is what I mean, thanks

![screen shot 2017-03-06 at 7 58 35 pm](https://cloud.githubusercontent.com/assets/804669/23599704/8492f4f2-02a7-11e7-9928-20b789ce22fd.png)

and the database table
try db.create(table: "mortgages") { t in
            t.column("id", .integer).primaryKey()
            t.column("name", .text).notNull()
            t.column("housePrice", .double).notNull()
            t.column("depositAmount", .double).notNull()
            t.column("loanTerm", .double).notNull()
            t.column("interestRate", .double).notNull()
            t.column("repaymentFrequency", .text).notNull()
            t.column("insurance", .double).notNull()
            t.column("colorcode", .text).notNull().defaults(to: "#FFFFFF")
        }

**Comment by groue** [comment]
The stack trace, please. This means the chain of all methods that lead to `didInsert(:with:for:)`

**Comment by groue** [comment]
If the stack trace is not printed in any log, check the sixth icon from the left in the left toolbar of the Xcode window.

**Comment by tuananh2311** [comment]
![screen shot 2017-03-06 at 8 16 15 pm](https://cloud.githubusercontent.com/assets/804669/23600121/d8231f1e-02a9-11e7-888c-65414d333a55.png)

Hope this helps

**Comment by groue** [comment]
OK. It's not clear. And I can't reproduce your issue when running a GRDB app on a device.

You have to provide as much information as possible in order to help reproduce the problem - that will help fixing it.

**Comment by groue** [comment]
> nothing wrong pops up

Not exactly: it looks like `Record.insert` calls `DAO.init` (ok) which in turns calls `didInsert` (wrong). This last chain link is not normal: the [DAO](https://en.wikipedia.org/wiki/Data_access_object) isn't supposed to notify that it has been inserted in its initializer. Can you shed so more light on this, please?

**Comment by groue** [comment]
Also, this strange stack trace makes me suspect a dubious GRDB binary - for example one that has been built with another version of Xcode. So please explain in details how you integrate GRDB in your app. Or, even better, restart from scratch from one of the [installation procedures](https://github.com/groue/GRDB.swift#installation), and check if the error is still there (and of course provide a *detailed* report if it does).

**Comment by groue** [comment]
No news, good news!
