### ISSUE TITLE
Complex records blow up Swift compiler

### ISSUE THREAD

**Issue by vhbit** [groue/GRDB.swift#188]
Steps to reproduce:

```
git clone https://github.com/vhbit/GRDB.swift
cd GRDB.swift
git checkout ouch
```

Open workspace and try to build iOS demo - it'll take forever as memory consumption goes up and at some point swapping kills everything. 

On successful attempt I've stopped it with 28Gb reported in Activity Monitor. On unsuccessful it swapped so hardly that I had to reset computer.

**Comment by vhbit** [comment]
And the workaround is to convert value for dictionary explicitly using `"field": field.databaseValue.value(),` construct like in 131830507f7c3ff5910313d11808d458f299c9a3

**Comment by groue** [comment]
Yes, @vhbit. This is addressed in the [FAQ "Compilation takes a long time"](https://github.com/groue/GRDB.swift#compilation-takes-a-long-time).

Your workaround is interesting, different from the one I suggest. I don't know which one is the best.

I'm closing this issue, since we're facing a *compiler* limitation. Feel free to reopen it if you want to suggest an alternative GRDB API that would prevent the problem altogether while preserving write [performances](https://github.com/groue/GRDB.swift/wiki/Performance).

**Comment by groue** [comment]
> Your workaround is interesting, different from the one I suggest. I don't know which one is the best.

Actually `field.databaseValue.value()` doesn't look very good on my eyes, as it has no obvious meaning. Plus I'm planning to remove the `DatabaseValue.value()` method altogether (it's already removed from the documentation, and I still have to remove it for good from the source code). I thus suggest, as in the FAQ:

```swift
var persistentDictionary: [String: DatabaseValueConvertible?] {
    var dict: [String: DatabaseValueConvertible?] = [:]
    dict.updateValue(a, forKey: "a")
    dict.updateValue(b, forKey: "b")
    ...
    return dict
}
```

**Comment by vhbit** [comment]
@groue
> This is addressed in the FAQ "Compilation takes a long time".
Ahh, sorry, I missed that part

> I'm closing this issue, since we're facing a compiler limitation.

well, my point was that considering it's a compiler limitation AND issue is new to you (wrong assumption), you might find a workaround by inventing another API to achieve the same goal without pissing off compiler. But if it's a known issue I guess no better APIs can be done ATM so my suggestion is to mention this in `Records` section

> Actually field.databaseValue.value() doesn't look very good on my eyes

It wasn't supposed to be a solution - just a workaround I found for myself to continue evaluation of the library :-)

**Comment by groue** [comment]
> my suggestion is to mention this in Records section

An excellent suggestion! I'll do that. Reopening until done.

**Comment by groue** [comment]
I hope the updated documentation will prevent other users from falling into this trap. Thanks for the feedback, @vhbit!
