### ISSUE TITLE
image blob storage?

### ISSUE THREAD

**Issue by pumplerod** [groue/GRDB.swift#189]
I'm just starting with GRDB and so far I really love it.  Perhaps I'm biting off more than I should in setting something up for the first time but I'm struggling to understand how one would store and recover image data from a UIImage object into a .blob field.  Or perhaps that's not recommended?

**Comment by groue** [comment]
Hello @pumplerod.

Did you try storing your images as data (png, jpeg, you choose)?

**Comment by pumplerod** [comment]
I created the table and column with

> try db.create(table: "person") { t in
>             t.column("id", .integer).primaryKey()
>             t.column("name", .text).notNull().collate(.localizedCaseInsensitiveCompare)
>             t.column("image", .blob)
>         }
> 

but I guess I'm not familiar with the proper way to convert the UIImage into an acceptable Data object.

I was thinking along the lines of myUIImage.cgImage?.bitmapInfo or something like that but I'm rather new to all this so I'm bungling my way through it.

**Comment by groue** [comment]
I'd rather recommend turning your images to jpeg or png with [UIImageJPEGRepresentation()](https://developer.apple.com/reference/uikit/1624115-uiimagejpegrepresentation) or [UIImagePNGRepresentation()](https://developer.apple.com/reference/uikit/1624096-uiimagepngrepresentation), and store the produced data in the database.

When reading, you decode image data with [UIImage.init(data:)](https://developer.apple.com/reference/uikit/uiimage/1624106-init).

**Comment by pumplerod** [comment]
Yes,  Thank you.  Now that I've got it, everything seems so simple.

This is a really wonderful library thank you very much.  Just FYI, as I've been reading through the docs (which are great), it took me a while to wrap my head around the fact that in much of your example code you use "db" and I had trouble gleaning the fact that my statements would always have to be wrapped in something like:
```
let allRecords = try! dbQueue.inDatabase { db in
    try MyModel.fetchAll(db)
} 
```

I eventually found it.  And I'm sure to experienced Swift developers it's probably obvious.  Just my observation as a Newbie.  Going through your docs has helped me learn a lot already.

**Comment by groue** [comment]
Glad you could store your images!

> I had trouble gleaning the fact that my statements would always have to be wrapped

I can understand your trouble. I don't know if the documentation would be improved if *all* code snippets where wrapped. What about explicit dbQueue/db wrapping in the initial examples of the most important entry points (SQL, Records, Query Interface)? I'll try that. Thank you very much for this suggestion.
