### ISSUE TITLE
[XCode 8.3] Could not build Objective-C module 'SQLiteiPhoneSimulator', SQLiteiPhoneOS

### ISSUE THREAD

**Issue by ibadcool** [groue/GRDB.swift#190]
I updated Xcode to the latest version 8.3, then GRDB can not work :[
When I select simulator, I got two errors
1. Module 'Drawin' was built in directory /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sqlite3.h:35:2: Module 'Darwin' was built in directory '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include' but now resides in directory '/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include'.    in sqlite3.h

2.Could not build Objective-C module 'SQLiteiPhoneSimulator'.   in 'Configuration.swift' file

Please check it out, thanks very much.

**Comment by groue** [comment]
Hello @ibadcool 

Please tell which [installation method](http://github.com/groue/GRDB.swift#installation) you picked (Carthage, CocoaPods, manual, SQLCipher, or custom SQLite build).

**Comment by jsoft-pl** [comment]
Hi,
I've got the same problem since 8.3 update last night. Manual installation.

**Comment by ibadcool** [comment]
hi, @groue , thanks for your reply.
I use CocoaPods.  I change to xcode8.3beta branch , and it fixed. 👍 both simulator and device can build success.

**Comment by groue** [comment]
Reopening since latest version 0.103.0 does not build on Xcode 8.3.

**Comment by groue** [comment]
Xcode 8.3 users should use the `modulemapRefactor` branch until the next GRDB release.

**Comment by jakusb** [comment]
Can you please explain to me how to specifically target that branch in my Podfile?

**Comment by groue** [comment]
Superseded by #194

**Comment by groue** [comment]
Support for Xcode 8.3 has shipped in v0.104.0
