### ISSUE TITLE
Xcode 8.2  unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by omarfraiwan** [groue/GRDB.swift#191]
Showing Recent Issues
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods
    export DEVELOPER_DIR=/Applications/Xcode8.2.app/Contents/Developer
    export PATH="/Applications/Xcode8.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode8.2.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode8.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    /Applications/Xcode8.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name GRDB -Onone -D COCOAPODS -sdk /Applications/Xcode8.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -enable-testing -I /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Products/Debug-iphonesimulator/GRDB.swift -F /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Products/Debug-iphonesimulator/GRDB.swift -c -j8 /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/CoreGraphics/CGFloat.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Configuration.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Cursor.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/Data.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Database.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/DatabaseCoder.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/DatabaseDateComponents.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseError.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Migrations/DatabaseMigrator.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabasePool.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseQueue.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseReader.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseSchemaCache.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseStore.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseValue.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseValueConvertible.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/DatabaseWriter.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/Date.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Record/FetchedRecordsController.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Legacy/Fixits-0-84-0.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Legacy/Fixits-0-90-1.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Legacy/Fixits-Swift2.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS3.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS3Pattern.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS3TokenizerDescriptor.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS4.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5CustomTokenizer.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5Pattern.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5Tokenizer.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5TokenizerDescriptor.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/FTS/FTS5WrapperTokenizer.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Migrations/Migration.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/NSData.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/NSNull.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/NSNumber.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/NSString.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Record/Persistable.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/QueryInterfaceRequest.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/QueryInterfaceSelectQueryDefinition.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/StandardLibrary/RawRepresentable.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Record/Record.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/ReferenceConvertible.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Request.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Row.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/RowAdapter.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Record/RowConvertible.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/SchedulingWatchdog.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/SerializedDatabase.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLCollatedExpression.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLCollection.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLExpression.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/Support/SQLFunctions.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/Support/SQLOperators.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLOrderingTerm.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLSelectable.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLSelectQuery.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/SQLSpecificExpressible.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/StandardLibrary/StandardLibrary.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Statement.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/StatementColumnConvertible.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/TableDefinition.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Record/TableMapping.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/URL.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Utils.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/Core/Support/Foundation/UUID.swift /Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/GRDB.swift/GRDB/QueryInterface/VirtualTableModule.swift -output-file-map /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/Objects-normal/x86_64/GRDB.swift-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/Objects-normal/x86_64/GRDB.swiftmodule -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/GRDB-generated-files.hmap -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/GRDB-own-target-headers.hmap -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/GRDB-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/GRDB-project-headers.hmap -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Products/Debug-iphonesimulator/GRDB.swift/include -Xcc -I/Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/Headers/Private -Xcc -I/Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods/Headers/Public -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/DerivedSources/x86_64 -Xcc -I/Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/Objects-normal/x86_64/GRDB-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/omarfraiwan/Library/Developer/Xcode/DerivedData/MyProjectSwift-hlebbmhicvsommffetsotrrbnbru/Build/Intermediates/Pods.build/Debug-iphonesimulator/GRDB.swift.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/omarfraiwan/Documents/MyProject/MyProjectSwift/Pods

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

**Comment by groue** [comment]
Gather yourself, and learn how to ask questions if you expect any answer.

**Comment by groue** [comment]
http://stackoverflow.com/help/mcve
