### ISSUE TITLE
db.execute and db.create(table) does not generate correct sql statments ...

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [groue/GRDB.swift#196]
I've tried both functions:
original SQL is ->
CREATE TABLE IF NOT EXISTS myTable (
id INTEGER, 
name TEXT NOT NULL, 
CONSTRAINT key PRIMARY KEY (id) ON CONFLICT REPLACE );

First function using the query interface:
db.create (table: myTable, temporary: false, ifNotExists: true, body: {
    t in 
    t .column("id", .integer).primaryKey(onConflict: .replace, autoincrement: false)
    t.column("name, .text").notNull()
})

and the Second function using the SQL api:
db.execute (" CREATE TABLE IF NOT EXISTS myTable (
id INTEGER, 
name TEXT NOT NULL, 
CONSTRAINT key PRIMARY KEY (id) ON CONFLICT REPLACE" )

after creation.. and by viewing the output structure on "SQLPro for SQLite Read-Only" 
the output is -> 
CREATE TABLE myTable (
id integer PRIMARY KEY,
name text NOT NULL
);

doing the same (using the execute method) on SQLite.swift library produces the correct structure

**Comment by groue** [comment]
Hello @Mina-R-Meshriky 

I don't see any issue here.

When I run your `db.create(table...` Swift snippet (after fixing your syntax errors 😒), I get the expected SQL (the one that your Swift code asks for):

```swift
// CREATE TABLE IF NOT EXISTS "myTable" (
//   "id" INTEGER PRIMARY KEY ON CONFLICT REPLACE,
//   "name" TEXT NOT NULL
// )
try db.create (table: "myTable", temporary: false, ifNotExists: true, body: {
    t in
    t .column("id", .integer).primaryKey(onConflict: .replace, autoincrement: false)
    t.column("name", .text).notNull()
})
```

When you want to check the SQL emitted by GRDB, please add a trace function to the database configuration: this is the most reliable witness of the generated SQL:

```swift
var configuration = Configuration()
configuration.trace = { print($0) }
let dbQueue = try DatabaseQueue(path: ..., configuration: configuration)
```

**Comment by Mina-R-Meshriky** [comment]
👍 my bad,, I always use other programs to find the generated SQL ... When I used another program (Firefox SQLite Manager) the "ON CONFLICT" constrained appeared but the "IF NOT EXIST" in "CREATE TABLE" didn't appear .... to tell you the truth I am confused.  do you have an explanation to that behavior?

Also, and this is a request, can you do a youtube video explaining how to use GRDB Properly, (I'v been reading the documentation for hours but I got very much lost) I come from an Android Background, in Android we have Content providers and other database tools to handle Sqlite CRUD operations and the Code is always structured so beautifully. In Comparison I don't Know exactly how I should structure my database Code in iOS.

**Comment by groue** [comment]
> do you have an explanation to that behavior?

Yes. In one case you look at some SQL that is *executed* (and it tells SQLite not to complain if the table already exists), and in the other case you look at some SQL that is *generated* from an existing database (and that database does not know that SQLite was told, in the past, not to complain about existing table).

> Also, and this is a request, can you do a youtube video explaining how to use GRDB Properly.

GRDB has already plenty of documentation, [sample code, and sample applications](https://github.com/groue/GRDB.swift#sample-code). Be the one that makes that first GRDB video tutorial!
