### ISSUE TITLE
Compile Error: Module 'Darwin'

### ISSUE THREAD

**Issue by pumplerod** [groue/GRDB.swift#199]
searching through your Issues I found something similar, however it was for an older version of Xcode so I hope this isn't redundant.  I didn't want to go changing anything in the .modulemap before I knew it was something I should do.  

I had set aside my GRDB project for a few days while I built the server side app.  Then when I came back and tried to run my GRDB based project I got this error.  I don't "think" I changed anything so I'm left scratching my head.  I have updated my Podfile installs and cleaned the project, but the error persists.

I've also removed and re-installed Xcode with the same results.

Are you able to make sense of this?  What could I have done to cause this?

XCode: Version 8.3

under the GRDB Framework I get the Swift Compile Error:
`Module 'Darwin' was built in directory '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include' but now resides in directory '/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include`

in my GRDB.modulemap:
`module SQLiteiPhoneSimulator {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sqlite3.h"
    export *
}`

Thinking this may have been because of an Xcode update I went back to Xcode version 8.2 which produces a different error during build...
11 separate `Segmentation fault: 11` errors within GRDB.swift/GRDB/Core

I'm not sure what version swift was on before the Xcode re-installs but it's currently at version 3.1

**Comment by groue** [comment]
Hello @pumplerod 

Update GRDB to the latest version (0.105.0).

**Comment by pumplerod** [comment]
Removing the MyApp.xcworkspace/ directory and re-running `pod install` along with re-installing GRDB.swift seems to have fixed the problem while running Xcode 8.2.

So I of course then tried again with Xcode 8.3 and it seems to be working just fine.  So I really don't know what I did to cause all the problem.

Could this have happened if I had accidently opened the .xcodeproj instead of the .xcworkspace?

**Comment by pumplerod** [comment]
So did you just fix something and I happened to update and pick up the fix?  Just trying to determine if it was something of my own doing that caused all the trouble.

**Comment by groue** [comment]
GRDB no longer has any modulemap file, in order to support Xcode 8.3 (long story). I guess it was a big enough change that has Xcode 8.2 gather itself and behave :-)

**Comment by pumplerod** [comment]
Wow.  Well thank you SO much.  You are a king among men!
