### ISSUE TITLE
sqlite3.h path is hardcoded

### ISSUE THREAD

**Issue by philtre** [groue/GRDB.swift#2]
The compiler could not find **sqlite3.h** because its hardcoded path in DRDB.swift.modulemap was incorrect on my machine

**Comment by groue** [comment]
Are you talking about https://github.com/groue/GRDB.swift/blob/master/GRDB/module.modulemap#L8 ?

What path did you have to use in order to have GRDB compile on your machine?

**Comment by philtre** [comment]
Yes, mine was:
"/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sqlite3.h"

**Comment by groue** [comment]
So you did not install the regular Xcode, did you?

**Comment by groue** [comment]
@philtre I did not intend to close the issue, sorry. Yet I don't quite know how to solve it.

**Comment by groue** [comment]
@philtre I'm considering closing this issue since it looks like it only affects people who did not install the regular Xcode. Anything against it?

**Comment by groue** [comment]
A solution to this issue may lie in https://github.com/stephencelis/SQLite.swift/issues/163

**Comment by groue** [comment]
Hi @davedelong.

I've tried to replace the hard-coded path to sqlite3.h with a direct embedding of SDKROOT/user/include/sqlite3.h, following your advice on https://github.com/stephencelis/SQLite.swift/issues/163.

This leads to a partial success:

1. Carthage is able to build the framework, and an application could run on top of it.

2. Cocoapods is able to perform its setup, but application could not run on top of it, with the "include of non-modular header inside framework module" error. It is so despite the CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES flag being set to YES in all targets I could find in the universe.

3. I could not apply your advice without adding sqlite3.h as a public header of the framework. I'm wondering if it's a good practice, considering the fact that the regular way of including sqlite3.h is #include <sqlite3.h>, not #include "sqlite3.h" or #include <MyFramework/sqlite3.h>. Plus there is a risk that this included header eventually goes out of sync with the one shipped with the SDK, the one that describes the actually linked dylib.

I was wondering what would be your opinion on point 3 (although I could sleep on it until an issue would come up), and if you had any advice on point 2.

Thanks for reading!

**Comment by stephencelis** [comment]
@groue CocoaPods doesn't support header files that aren't within the scope of the project. You'll need to continue to use the module map for CocoaPods at the very least.

**Comment by groue** [comment]
Thank you Stephen :-) Cross-linking to https://github.com/CocoaPods/CocoaPods/issues/3942 for reference.

**Comment by groue** [comment]
There is no currently solution to this problem. The workaround is to use the latest release of Xcode, which a quite reasonable requirement: I'm closing the issue.
