### ISSUE TITLE
How can I perform Full-text search

### ISSUE THREAD

**Issue by mrsaif** [groue/GRDB.swift#20]
Is full-text search is supported. if yes than how can i perform full-text search?

**Comment by groue** [comment]
Hello @mrsaif 

Yes, full-text search is supported, as all features of SQLite that use the SQL language (see [GRDB's SQLite API](https://github.com/groue/GRDB.swift#sqlite-api)).

"Full-text search" is easily said, but less easily understood. I recommend you have a look at https://www.sqlite.org/fts3.html.

**Comment by groue** [comment]
I'll help you if you need, but since there is no "one size fits all" answer to full text search in SQLite, I won't be able to help you much unless you come back with precise questions.

**Comment by groue** [comment]
@mrsaif, no news?

**Comment by mrsaif** [comment]
Thanks groue I was just wondering how to do it in using GRDB.Swift. I am new to swift. I will do my work and will let get back if I was not able to do it Many thanks.

**Comment by groue** [comment]
I'll be there. I haven't used GRDB with full-text yet, so I haven't even tried to integrate it in GRDB in any fashion. Knowing that SQL could do the job in some way or another didn't help pushing that task on top of my list. Yet I'm all keen to improve the lib after a little feedback and experience.
