### ISSUE TITLE
nested property

### ISSUE THREAD

**Issue by leonard2014** [groue/GRDB.swift#203]
How to store the following JSON into SQLite? The location property contains two float value. Thanks!

	"atms": [
		{
			"id": "829134",
			"name": "King Cross Station",
			"address": "8 Abc St, London",
			"location": {
				"lat": 25.338278,
				"lng": 0.230438
			}
		},
		{
			"id": "336899",
			"name": "Town Hall Square",
			"address": "53 Alex Avenue, London",
			"location": {
				"lat": 33.308471,
				"lng": 0.532876
			}
		}
    ]

**Comment by leonard2014** [comment]
What a bad response

**Comment by groue** [comment]
For a very bad question. Come back with an actual question after you have tried something.
