### ISSUE TITLE
warning: reached end of file in GRDB-Bridging.h in Xcode 8.3.2

### ISSUE THREAD

**Issue by markreddick** [groue/GRDB.swift#210]
I just started a new Swift project and want to use GRDB.swift. I followed the manual installation instructions and got it working. That is, I can read the database and return results. But, Xcode 8.3.2 is reporting a warning. 

I'd love to know if this is going to be an issue before I continue down the path of using GRDB.swift instead of trying out other SQLite wrappers.

And, please note that I also loved up the demo GRDBDemoIOS app and it gives me the same warning.

I took a look at the referenced .h file is empty (0 bytes) and perhaps that is why Xcode doesn't like it. 

I Googled and found somebody else reporting a similar issue with another [project with an empty file and Xcode 8.2](http://stackoverflow.com/questions/41818860/building-0-byte-file-on-xcode-8-2-causes-warning-mach-o-reached-end-of-file-wh) .

Here's the full warning:

`warning: /Users/MER/Library/Developer/Xcode/DerivedData/GRDBDemoiOS-dwacjmrqqtdmxlezvigijcadohol/Build/Products/Release-iphonesimulator/GRDB.framework/Headers/GRDB-Bridging.h: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.`

**Comment by swiftlyfalling** [comment]
Does adding a single return / newline to that file resolve the warning for you?

**Comment by swiftlyfalling** [comment]
@markreddick: Does adding a single return / newline to that file resolve the warning for you?

**Comment by groue** [comment]
Hello @markreddick, @swiftlyfalling.

This warning hasn't occurred to me yet: it does not ship with GRDB. What if you quit Xcode, delete your ~/Library/Developer/Xcode/DerivedData folder, and give another try?

**Comment by markreddick** [comment]
@swiftlyfalling, I just tried adding a newline to that file with the same result.

@groue, I deleted the DerivedData folder and get the same warning. What do you mean that it doesn't ship with GRDB? If you are referring to the header file, the GRDB-Bridging.h is in the Support folder.

I've attached the build activity log if you'd like to see it. The warning is on line 200.

[Build target GRDBDemoiOS_2017-05-12T07-36-20.txt](https://github.com/groue/GRDB.swift/files/996146/Build.target.GRDBDemoiOS_2017-05-12T07-36-20.txt)

**Comment by groue** [comment]
> What do you mean that it doesn't ship with GRDB?

It means that GRDB does not naturally produce this warning, I have never seen it, and you're the first user who reports it. I don't know what is happening. I can't really investigate: I suggest you ignore this warning, or try to fix it yourself.

> sqlite3_trace is deprecated

This is unrelated and harmless. See https://github.com/groue/GRDB.swift/issues/100 for more information.

**Comment by dmcgloin** [comment]
@markreddick Hey, did you ever find a fix for this warning? I'm seeing the same warning in our own project (not using GRDB). Sorry to spam here. The SO question never got an answer. Wondering if there is some compiler/linker flag that causes this.
