### ISSUE TITLE
Support SQLCipher through Cocoapods

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#211]
I'm currently using the SQLCipher variant of GRDB, which forces me to forgo managing it with Cocoapods. Now that I want to start using `RxGRDB`, it gets worse: I can't get that through Cocoapods as it would pull the version of GRDB I don't want.

How difficult is it to support SQLCipher through Cocoapods? I know that FMDB does it in their [Podspec](https://github.com/ccgus/fmdb/blob/master/FMDB.podspec) but I don't know how applicable it is to GRDB.

**Comment by groue** [comment]
Hello @hartbit!

> How difficult is it to support SQLCipher through Cocoapods?

I don't know 😉. And I don't know either how to have RxGRDB use GRDBCipher.

I guess we'd need subspecs in both GRDB.swift.podspec and RxGRDB.podspec, but I'm not yet familiar with "advanced" CocoaPods setup.

We also have https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec#L60-L69 as a reference.

**Comment by groue** [comment]
Thanks to @sroddy it is now possible to install GRDBCipher with CocoaPods: I'm closing this issue. However RxGRDB is not ready yet, though: the story continues on https://github.com/RxSwiftCommunity/RxGRDB/issues/6.
