### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by swiftlyfalling** [groue/GRDB.swift#216]
In my own runs of the test suite, and now in [this CI test run](https://travis-ci.org/swiftlyfalling/GRDB.swift/jobs/235393764), I've noticed that one test occasionally fails:
`DatabaseQueueReleaseMemoryTests.testDatabaseIteratorRetainConnection`

Here's the failure info from that recent CI test run:

> GRDBOSXTests.DatabaseQueueuReleaseMemoryTests
  testDatabaseIteratorRetainConnection, XCTAssertTrue failed - 
  > /Users/travis/build/swiftlyfalling/GRDB.swift/Tests/GRDBTests/DatabaseQueueReleaseMemoryTests.swift:171
>  ```
>                    cursor = nil
>                    XCTAssertTrue(connection == nil)
>                }
>  ```

(I've had `testDatabaseIteratorRetainConnection` fail locally - rarely - with the same error on the `XCTAssertTrue(connection == nil)` line.)

I haven't had a chance to dig into it yet, but might there be a race condition in the test itself?

**Comment by groue** [comment]
> I haven't had a chance to dig into it yet, but might there be a race condition in the test itself?

It smells like one, yes. Investigating...

**Comment by groue** [comment]
Note to self: rename "DatabaseIterator" to "Cursor"
