### ISSUE TITLE
How do i connect to multiple SQLite databases?

### ISSUE THREAD

**Issue by MuhamadMustafa** [groue/GRDB.swift#224]
hello,

I have multiple DB can I connect multiple databases?

**Comment by groue** [comment]
Hello @MuhamadMustafa,

Did you try to open as many database queues as there are database files? Looks like a simple answer to your question:

```swift
let dbQueue1 = try DatabaseQueue(path: path1)
let dbQueue2 = try DatabaseQueue(path: path2)
let dbQueue3 = try DatabaseQueue(path: path3)
```

Read the chapter about [database queues](https://github.com/groue/GRDB.swift#database-queues) for more information.

**Comment by johannprogram** [comment]
Hi, I hope you can help me, I have this problem

"the database file can not be opened"

In the emulator it works for me but in the physical device it does not. 


when starting it works fine, but when working with the app the problems start

 public String GetConnection ()
        {
            var sqliteFilename = "Medilink.db3";
#if __ANDROID__
// Just use whatever directory SpecialFolder.Personal returns
string libraryPath = Environment.GetFolderPath (Environment.SpecialFolder.Personal); ;
#else
            // we need to put in / Library / on iOS5.1 + to meet Apple's iCloud terms
            // (they do not want non-user-generated data in Documents)
            string documentsPath = Environment.GetFolderPath (Environment.SpecialFolder.Personal); // Documents folder
            string libraryPath = Path.Combine (documentsPath, "..", "Library"); // Library folder instead
#endif
            var path = Path.Combine (libraryPath, sqliteFilename);


            #region ConexionOLD
           // var fileName = "Medilink.db3";
        // var documentsPath = Environment.GetFolderPath (Environment.SpecialFolder.Personal);
           // var path = Path.Combine (documentsPath, fileName);
            return path;
            #endregion
