### ISSUE TITLE
GRDBCipher pod

### ISSUE THREAD

**Issue by Burtan** [groue/GRDB.swift#227]
Hi,
I've tried the new GRDBCipher pod which I really appreciate, but I get an error when trying to use it in SQLCipher-umbrella.h

`Error:(7, 1) unknown type name 'FOUNDATION_EXPORT'`

Commenting the two lines lets the app compile but I guess those two variables are used anywhere?

**Comment by groue** [comment]
Hello @Burtan. I'm not sure I have understood.

> [...] when trying to use it in SQLCipher-umbrella.h

What do you mean?

> Commenting the two lines lets the app compile but I guess those two variables are used anywhere?

Which lines? Which variables?

**Comment by Burtan** [comment]
When adding GRDBCipher pod, GRDBCipher pod and SQLCipher pod gets installed. Under SQLCipher -> Support Files -> SQLCipher-umbrella.h line 7 and 8 are affected. 
I tried adding @import Foundation and #import "Foundation/Foundation.h". Both didn't work and I'm not very familiar with C/Objective-C

**Comment by groue** [comment]
I'm sorry @burtan, but I can't really help. Make sure you **strictly follow the documented installation steps**. Start from a fresh project in which you add dependencies one after the other.
