### ISSUE TITLE
sqlite3_trace is deprecated warning...

### ISSUE THREAD

**Issue by KMessina1** [groue/GRDB.swift#231]
Database.swift

setupTrace()

...
                sqlite3_trace(sqliteConnection, { (dbPointer, sql) in
                    guard let sql = sql.map({ String(cString: $0) }) else { return }
                    let database = unsafeBitCast(dbPointer, to: Database.self)
                    database.configuration.trace!(sql)
                }, dbPointer)

![screen shot 2017-06-07 at 1 18 39 pm](https://user-images.githubusercontent.com/8019251/26891731-09b3e1c6-4b84-11e7-86c2-68cdb02a4822.png)

**Comment by groue** [comment]
https://github.com/groue/GRDB.swift/issues/100#issuecomment-304074665
