### ISSUE TITLE
Automatic generation of schema-classes, from schema.

### ISSUE THREAD

**Issue by smhk** [groue/GRDB.swift#232]
More and more, I think SQL middleware-kits should feature something like _automatic generation of the classes, from the schema_.

(What I mean is, during development-time.)

So, on every large, real world mobile-cloud project, the server team provides a url like this ... https://nice.client.eu/mobile_schema_suggestion and it looks like this...

![screenshot](https://user-images.githubusercontent.com/3938526/27183467-4660fb24-51a4-11e7-8cd9-f77a7f009a8e.png)

.. plus 50 more tables.

So, as work progresses, the schema changes from day to day, eventually it becomes stable.

(In practice, on every team I have been on, you add a line of code in your app, which, upon launching the app it glances at that URL and checks if the server schema has changed.  Again, I am speaking about purely during development time.)

Most/all SQL app middlewares such as Groue and the rest, feature some sort of "schema-classes" which you can (optionally or otherwise) use with each table .. so your table

`actruck:id TEXT NOT NULL UNIQUE, grouppo INTEGER, val TEXT, archived BOOLEAN default 0 check(archived in (0,1)), updated DATETIME, seq INTEGER`

becomes some sort of class or struct

```
class handy_actruck {
  var id: int
  var gruppo: Bool
  etc
}
```

(I do not care about the specifics of the syntax or the paradigm used.)  You can then very conveniently just uses classes (/ structs, singletons, whatever) in your code "like" using the data itself.

It has occurred to me, and it is quite obvious once I say it, perhaps there should be a tool - once again, I mean for development time - which, simply as it were,

just **reads the schema** from the SQL database, and, **spits out** a large .Swift file, with the entirety of the "schema-classes" as per the system at hand.

Is this not obvious?  Perhaps it exists already and I am just too silly to know it?

**Comment by groue** [comment]
Hello @smhk!

This looks like a nice project indeed. I'd be very happy if somebody would use GRDB to build Swift files from database schema.

This won't be me, because I have to manage my time and priorities. But please ring a bell when you have a working prototype, or any question while implementing this code generator!

**Comment by smhk** [comment]
I will do it when I can!

thanks for your attention !!!

John-Paul
