### ISSUE TITLE
GRDB records generation from SQL

### ISSUE THREAD

**Issue by gotev** [groue/GRDB.swift#234]
Hi, first of all thank you for this great project. Started using it some days ago and I really like it, great job! Coming from Android development using SQLite together with [SQLDelight](https://github.com/square/sqldelight) and [SQLBrite](https://github.com/square/sqlbrite), which I combined in my [db-framework](https://github.com/gotev/db-framework) library, I was wondering if some tool to generate GRDB `Record` implementation from plain SQL Create Table is available. Found nothing 'till now.

It will be great to have the following SQL:
```sql
CREATE TABLE user (
    _id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NULL DEFAULT '',
    surname TEXT NULL DEFAULT '',
    email TEXT NOT NULL,
    image TEXT NULL DEFAULT '',
    wizard_status INTEGER NOT NULL DEFAULT 0,
    color TEXT
);
```
produce the following Swift file:
```swift
import Foundation
import GRDB

class UserModel: Record {

    override class var databaseTableName: String {
        return "user"
    }

    var _id: Int64?
    var name: String = ""
    var surname: String = ""
    var email: String
    var image: String = ""
    var wizard_status: Int = 0
    var color: String = ""

    struct Columns {
        static let _id = "_id"
        static let name = "name"
        static let surname = "surname"
        static let email = "email"
        static let image = "image"
        static let wizard_status = "wizard_status"
        static let color = "color"
    }
    
    static let createTable = "CREATE TABLE \(databaseTableName) (" +
        "_id INTEGER NOT NULL PRIMARY KEY," +
        "name TEXT NULL DEFAULT ''," +
        "surname TEXT NULL DEFAULT ''," +
        "email TEXT NOT NULL," +
        "image TEXT NULL DEFAULT ''," +
        "wizard_status INTEGER NOT NULL DEFAULT 0," +
        "color TEXT" +
    ")"

    required init(row: Row) {
        _id = row.value(named: Columns._id)
        name = row.value(named: Columns.name)
        surname = row.value(named: Columns.surname)
        email = row.value(named: Columns.email)
        image = row.value(named: Columns.image)
        wizard_status = row.value(named: Columns.wizard_status)
        color = row.value(named: Columns.color)
        super.init(row: row)
    }

    init(_id: Int64, email: String) {
        self._id = _id
        self.email = email
        super.init()
    }

}
```
it will save a lot of development time and errors. Do you know something like this for GRDB? If not, are there any plans to make a tool like this? I would love to contribute

**Comment by groue** [comment]
Hello @gotev,

Thanks for your interest! If you like reactive SQLite, don't miss [RxGRDB](https://github.com/RxSwiftCommunity/RxGRDB)!

Your request is similar to https://github.com/groue/GRDB.swift/issues/232.

I don't currently have any plan extending GRDB with such an extension, for several reasons:

- On the boiler plate side, code generation is surely a solution, but it is not the single one. Swift 4 will soon come out with support for [Codable types](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md). This will improve record type definition:

    ```swift
    enum Color: String, DatabaseValueConvertible, Codable {
        case red, green, blue
    }

    struct Player : RowConvertible, Persistable, Codable {
        static let databaseTableName = "players"
        let name: String
        let score: Int
        let color: Color
    }

    // Automatically derived from Codable:
    //
    // extension Player {
    //     init(row: Row) { ... }
    //     func encode(to container: inout PersistenceContainer) { ... }
    // }

    try dbQueue.inDatabase { db in
        let arthur = Player(name: "Arthur", score: 100, color: .red)
        try arthur.insert(db)
        let players = try Player.fetchAll(db) // [Players]
    }
    ```

- Code generated from database schema can be sub-optimal, or even misleading.
    
    Note how the Player type above is able to declare `Int` and `Color` properties. An automatically generated model would be stuck with `Int64` (the only integer type known by SQLite, not quite easy to use in Swift), and `String` (no way to use specific types).
    
    Similarly, there would be no way to choose between `Date` and `DateComponents`, two types that don't have the same purpose at all. For example, birthdays are better represented by DateComponents: not everybody is born at midnight, and your birthday does not depend on your current time zone.

- About the `createTable` static variable in your sample code: a record type is not quite suited for creating its own table.
    
    That's because a record type fits a *specific database schema*, when applications have *evolving database schemas*. Because of this fundamental mismatch, GRDB fosters [migrations](https://github.com/groue/GRDB.swift#migrations) that are totally *independent from records, stable, and testable*. Check this [design comment](https://github.com/groue/GRDB.swift/issues/73#issuecomment-229859073) about how GRDB takes care of evolving schemas in its [database schema API](https://github.com/groue/GRDB.swift#database-schema).
    
    When it's still not quite clear to me how SQLDelite handles migrations, I kind of understand that it is not quite ideal (https://github.com/square/sqldelight/issues/89).
    
Finally, you can already write SQLDelite with existing GRDB public APIs. I have listed above the reasons why GRDB itself is unlikely to benefit from code generated from database schema. I also understand that you are already familiar with SQLDelite, SQLBrite, and db-framework, and that this setup suits your current development practices: you can just go ahead, and rewrite SQLDelite for GRDB.

**Comment by gotev** [comment]
Many thanks for the great and precise response! I've checked all the links you provided and I now better understand your point of view. I've already checked RxGRDB and I started using it. It does exactly what I need. Again, another great library, thank you ;)

The codable types in Swift 4 will surely add many benefits, but I have some additional notes regarding code generation, because my previous post was incomplete.

> Note how the Player type above is able to declare Int and Color properties. An automatically generated model would be stuck with Int64 (the only integer type known by SQLite, not quite easy to use in Swift), and String (no way to use specific types).

> Similarly, there would be no way to choose between Date and DateComponents, two types that don't have the same purpose at all. For example, birthdays are better represented by DateComponents: not everybody is born at midnight, and your birthday does not depend on your current time zone.

SQLDelight handles missing SQLite types this like this:
```sql
`active` INTEGER NOT NULL DEFAULT 0 AS Boolean
```
They implemented various mappings to specific Java Types, including `Date`. Something similar could be done with Swift too. In this case you get a `Boolean` in Java/Kotlin and it gets converted to/from `INTEGER` when the record gets saved/read. 

Regarding `createTable`, you're absolutely right, it's better to keep schema management separate from queries, so the create table should not be in the model.

From what I see, GRDB does a better job regarding schema management and migrations than SQLDelight.

Where SQLDelight really gives many benefits is in the generation of the row mappers for the queries, even for complex join operations, so you can simply write your plain SQL query, have the row mapper automatically generated and use it directly with Rx extensions. The row mappers includes only the query's resulting fields, so you don't have mapping and memory overhead for the resulting objects which gets generated from the query. Porting that part to GRDB could save a lot of dev time.

I'm no expert in the core of SQLDelight, but from what I know I think it will be possible to make a port for swift and GRDB. I will surely look at it deeper when I have some free time, because it can considerably speed up development with GRDB + RxGRDB.

**Comment by groue** [comment]
> SQLDelight handles missing SQLite types like this:
> ```sql
> `active` INTEGER NOT NULL DEFAULT 0 AS Boolean
> ```
> They implemented various mappings to specific Java Types, including `Date`. Something similar could be done with Swift too. In this case you get a `Boolean` in Java/Kotlin and it gets converted to/from `INTEGER` when the record gets saved/read.

Yes, I was wrong. It actually looks like SQLDelight has its own SQL grammar parser. That's quite involved, but it does the job!

> Where SQLDelight really gives many benefits is in the generation of the row mappers for the queries, even for complex join operations, so you can simply write your plain SQL query, have the row mapper automatically generated and use it directly with Rx extensions. The row mappers includes only the query's resulting fields, so you don't have mapping and memory overhead for the resulting objects which gets generated from the query. Porting that part to GRDB could save a lot of dev time.

Are you talking about the `.sq` files, as in https://github.com/gotev/db-framework#query below?

```sql
get_by_age:
SELECT *
FROM test
WHERE age = ?;
```

That's an interesting idea! I can indeed see the benefits.

For joins, I'm currently working on a very different approach (targetting people who *don't know* how to write joins, and a few common use cases that involve joins): https://github.com/groue/GRDB.swift/issues/176#issuecomment-306409884.

> I'm no expert in the core of SQLDelight, but from what I know I think it will be possible to make a port for swift and GRDB. I will surely look at it deeper when I have some free time, because it can considerably speed up development with GRDB + RxGRDB.

I'll help you whenever you have a question: just open an issue here.

**Comment by gotev** [comment]
Created a basic script which can at least save you from some boilerplate and does what I proposed: https://github.com/gotev/GRDB-Record-Generator

It is just a quick and dirty implementation, but it already saves you a lot of typing and can be the start for a more complete and better generator which can empower GRDB users, at least when you start a new project from scratch.

**Comment by groue** [comment]
That's great, @gotev!

Did you consider defining columns with the Column type instead of strings?

```swift
import Foundation
import GRDB

class UserModel: Record {
    // unchanged
    var _id: Int64?
    var name: String? = ""
    var surname: String? = ""
    var email: String
    var image: String? = ""
    var wizard_status: Int64 = 0
    var color: String?
    
    // unchanged
    override class var databaseTableName: String {
        return "user"
    }
    
    // Define an enum instead of a struct, to prevent instanciation.
    enum Columns {
        // Use Column instead of String
        static let _id = Column("_id")
        static let name = Column("name")
        static let surname = Column("surname")
        static let email = Column("email")
        static let image = Column("image")
        static let wizard_status = Column("wizard_status")
        static let color = Column("color")
    }
    
    required init(row: Row) {
        // value(_:) instead of value(named:)
        _id = row.value(Columns._id)
        name = row.value(Columns.name)
        surname = row.value(Columns.surname)
        email = row.value(Columns.email)
        image = row.value(Columns.image)
        wizard_status = row.value(Columns.wizard_status)
        color = row.value(Columns.color)
        super.init(row: row)
    }
    
    // unchanged
    override func encode(to container: inout PersistenceContainer) {
        container[Columns._id] = _id
        container[Columns.name] = name
        container[Columns.surname] = surname
        container[Columns.email] = email
        container[Columns.image] = image
        container[Columns.wizard_status] = wizard_status
        container[Columns.color] = color
    }
}
```

The benefit is that columns can be used in the query interface:

```swift
let users = try UserModel.order(UserModel.Columns.name).fetchAll(db)
```

**Comment by gotev** [comment]
Done! Thanks for your suggestions! If you have any idea on how I could make this tool better and to handle use cases you know about, don't hesitate to open me an issue on my repo. One thing I want to do is to add basic automated tests. The idea is simple, have a bunch of SQL files to use as input and the desired swift output. Then with a simple shell script I'll pass the input SQL files to the tool and check if the output is identical to the desired file using diff tool. If you have time and want to contribute, I really appreciate!
