### ISSUE TITLE
PersistentDictionary --> using encode... 

### ISSUE THREAD

**Issue by KMessina1** [groue/GRDB.swift#235]
Not sure where to ask this, but I am totally lost on the removal of persistent dictionaries as I used them extensively. 

I have a simple generic function that accepts a [Record] as parameter and returns a swift array of dictionaries of [[String:AnyObject]]. 

So an entire fetchAll can be returned as an array of dictionaries.

code:

    func convertDBClassToArrayOfDictionaries(_ dbClassArray:[Record]) -> [[String:AnyObject]] {
        var records:[[String:AnyObject]] = []
        
        for itemRecord:Record in dbClassArray {
            let dict = itemRecord.persistentDictionary as [String:AnyObject]
            records.append(dict)
        }
        
        return records
    }

I've read the documentation and the change log for encode: and although it compiles, I cannot figure out how to read that encoding, especially in a generic Record form.

Any assistance would be greatly appreciated, I am at a dead stop in my clients app and don't know where to turn to get this information or an example. 

-Kevin

**Comment by groue** [comment]
Hello @KMessina1,

I see your trouble: this change has ruined your conversion technique, and there currently is absolutely no workaround.

All right. Will you please fallback to 0.110.0 until the next version brings back a way to export records?

**Comment by groue** [comment]
> So an entire fetchAll can be returned as an array of dictionaries

Actually, If you want to turn fetched records into dictionaries, you have an option with GRDB 1.0: turn your request of records into a request of rows, which you can turn into dictionaries:

```swift
extension Row {
    var asDictionary: [String: Any] {
        var dict: [String: Any] = [:]
        for (column, dbValue) in self {
            dict[column] = dbValue.storage.value
        }
        return dict
    }
}

let request = MyRecord.all()
let records = try request.fetchAll(db) // no way to turn them into dictionaries
let rows = try Row.fetchAll(db, request) // [Row]
let dicts = rows.map { $0.asDictionary }
```

**Comment by KMessina1** [comment]
A ridiculous work around that seems to work as a bandage is terrible because I still have to test for each class type in the app which doesn't work as a shared "library" .swift file among all my apps (I am a independent client app developer) and update as I add more which kind of defeats the purpose of a generic function, but still better to have in a single function than all over the place is:

Once the class is cast it still sees the persistent dictionary definition I had defined after removing the orverride keywords in each class.

`    func convertDBClassToArrayOfDictionaries(_ dbClassArray:[AnyObject]) -> [[String:AnyObject]] {
        var records:[[String:AnyObject]] = []
        
        for item in dbClassArray {
            if let convertedItem = item as? CalibersAndGauges {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? InventoryCategory {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? InventoryDetails {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? Inventory {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? NoseTypes {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? JacketTypes {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? Vendors {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? Manufacturers {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? BulletTypes {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? Reloads {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }else if let convertedItem = item as? Hardware {
                records.append(convertedItem.persistentDictionary as [String:AnyObject])
            }
        }
        
        return records
    }
`

**Comment by KMessina1** [comment]
I will try your way now, thanks for the followup.

**Comment by groue** [comment]
See how I suggest not *converting fetched records*, but *fetching rows* instead, because rows can be turned into dictionaries.

If you want a general way to turn a record into a dictionary, as in the sample code below, then you're out of luck:

```swift
let record = MyRecord(id: 1, name: "foo")
let dictionary = record.asDictionary // no way to do that
```

But as long as you want to process database results, you can do whatever you want:

```swift
Row.fetchAll(db, MyRecord.all())
   .map { $0.asDictionary } // yeah
```

**Comment by groue** [comment]
Sorry I missed your last message :-)

**Comment by KMessina1** [comment]
let dict = try Row.fetchAll(db, CalibersAndGauges.all()).map { $0.asDictionary }

Works well as a direct conversion within the initial get. so I will implement this, thank you! 

Note: It still doesn't work after the class/struct is already populated as a data object to be read at any time after initial load as I had wanted, but it is a simple enough method. I'd really, really like to see the persistentDictionary concept re-enabled if possible in future updates if that could be done since it was such a convenience method to access classes already in memory. But for now, at least I am back into a working app model and can try and get paid this week :)

Thank you again!

-Kevin.

**Comment by groue** [comment]
> Works well as a direct conversion within the initial get. so I will implement this, thank you!

Great, @KMessina1!

> Note: It still doesn't work after the class/struct is already populated as a data object to be read at any time after initial load

Yes. We're talking about a database serialization library, after all, not a generic dictionary or JSON encoder.

>  I'd really, really like to see the persistentDictionary concept re-enabled if possible in future updates if that could be done since it was such a convenience method to access classes already in memory

In future developments, it is likely that `PersistenceContainer` becomes a protocol. That'll let you feed the `encode(to:)` method with custom objects that feed a dictionary.

In retrospect, I'm glad we've both found that this general record to dictionary export wasn't necessary, after all. There are two documentation chapters that I encourage you reading again:

- [Rows as Dictionaries](https://github.com/groue/GRDB.swift#rows-as-dictionaries), so that you better see the relation between rows and dictionaries.
- [Custom Requests](http://github.com/groue/GRDB.swift#custom-requests), so that you get more familiar with requests.

Happy GRDB!

**Comment by KMessina1** [comment]
I only started using GRDB atop SQLite about 3 weeks ago, and I am already hooked. 

I held out a long time in moving to data objects. Hated Core Data and it left a long lasting bad impression with me. Thanks for helping out so fast, it is greatly appreciated. 

-Kevin.
