### ISSUE TITLE
Row DictionaryLiteral support

### ISSUE THREAD

**Issue by avaidyam** [groue/GRDB.swift#238]
> Yet rows are not real dictionaries: they are ordered, and may contain duplicate keys...

Use [`DictionaryLiteral`](https://developer.apple.com/documentation/swift/dictionaryliteral) instead of `Dictionary` for that.

**Comment by groue** [comment]
Hello @avaidyam 

Row already adopts `ExpressibleByDictionaryLiteral`:

```swift
let row: Row = ["foo": "bar", "foo": Date(), "foo": nil]
print(row)
// prints <Row foo:"bar" foo:"2017-07-03 14:37:37.040" foo:NULL>
```

The sentence "rows are not real dictionaries: they are ordered, and may contain duplicate keys" is exact. What is your point/suggestion?

**Comment by avaidyam** [comment]
`ExpressibleByDictionaryLiteral` and `DictionaryLiteral` are different: `ExpressibleByDictionaryLiteral` implies you can use a literal syntax to create the object, but `DictionaryLiteral` is an actual struct, like `Dictionary` is. 

As to how they're different:
> Besides maintaining the order of the original dictionary literal, DictionaryLiteral also allows duplicates keys.

So, `DictionaryLiteral` objects provide exactly what rows could use.

**Comment by groue** [comment]
So you're talking about how rows are internally implemented, not about their public API, right? Are you thinking rows are using dictionaries for their inner storage, and suggesting a change? That's not the case, actually (how could they maintain the order of their columns if they used a dictionary?)

But maybe you are suggesting something else. I still don't know. Please be clear about the reason why you have opened this issue. Or let me close it.

**Comment by avaidyam** [comment]
I suppose I'm talking a little bit about both -- you could use a DictionaryLiteral internally as a backing store for the Row. In addition, you could explicitly replace `[String: DatabaseValueConvertible?]` and `[AnyHashable: Any]` with `DictionaryLiteral` to allow the user to maintain duplicates and ordering when creating rows.

**Comment by groue** [comment]
Thanks for the suggestions. Duly noted.
