### ISSUE TITLE
what's the version of GRDBCipher should i use?

### ISSUE THREAD

**Issue by greenhaixia** [groue/GRDB.swift#241]
I use the GRDB.swift with 0.108.0, but now i want to add encrypt function.
When i add pod 'GRDBCipher', '0.108.0' in pod file, it can't build success.
It show "could not build module 'UIKit' in SQLCipher-umbrella.h".
So what should i do?

**Comment by groue** [comment]
Hello @greenhaixia.

I don't know: you don't give enough information. What's the content of your podfile?

**Comment by greenhaixia** [comment]
platform :ios, '10.0'
use_frameworks!


target 'Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Player
pod 'SnapKit'
pod 'GRDB.swift', '0.108.0'
pod 'GRDBCipher', '0.108.0'
end

**Comment by groue** [comment]
Keep only the GRDBCipher.swift line, and remove the GRDB.swift line.

**And please learn how to format your messages.**

When you paste code in a Github issue, wrap it into backticks ```:

    ```
    platform :ios, '10.0'
    use_frameworks!


    target 'Player' do
      # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

      # Pods for Player
    pod 'SnapKit'
    pod 'GRDB.swift', '0.108.0'
    pod 'GRDBCipher', '0.108.0'
    end
    ```

Formatting your code snippets prevents

# Big text which make people think that you don't care much about anything.

It's easier to answer a question when it is easy to read.

**Comment by greenhaixia** [comment]
I removed GRDB.swift line, but the problem do not be solved.

**Comment by groue** [comment]
The GRDBCipher pod works. I don't know which issue your setup has. Maybe it's temporary: clean your project, and rebuild from scratch. Maybe you have Cocapods dirt somewhere: make sure you use the latest version of your tools, and reinstall all pods. Do your job. And if you remain stuck, come back with enough **information**. "Problem not solved" doesn't mean anything.
