### ISSUE TITLE
mach-o, but wrong architecture Error in Iphone 5

### ISSUE THREAD

**Issue by kamalupasena** [groue/GRDB.swift#242]
I am getting above error when i am running my code on iPhone 5 but its not became a issue in iPhone 6 or 7 

`dyld: Library not loaded: @rpath/GRDB.framework/GRDB
  Referenced from: /private/var/containers/Bundle/Application/D747DF25-E1A9-4218-B8F8-5873289FCF75/HostingApp.app/PlugIns/Keyboard.appex/Keyboard
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/D747DF25-E1A9-4218-B8F8-5873289FCF75/HostingApp.app/PlugIns/Keyboard.appex/Frameworks/GRDB.framework/GRDB: mach-o, but wrong architecture
	/private/var/containers/Bundle/Application/D747DF25-E1A9-4218-B8F8-5873289FCF75/HostingApp.app/PlugIns/Keyboard.appex/Frameworks/GRDB.framework/GRDB: mach-o, but wrong architecture
	/private/var/containers/Bundle/Application/D747DF25-E1A9-4218-B8F8-5873289FCF75/HostingApp.app/PlugIns/Keyboard.appex/Frameworks/GRDB.framework/GRDB: mach-o, but wrong architecture`

This is the complete error code my iPhone running on iOS 10.3.2

**Comment by groue** [comment]
Hello @kamalupasena,

I don't quite know what's wrong: iPhone 5 runs on the ARMv7s architecture, which belongs to the architecture supported by the framework.

Which installation technique did you follow?

**Comment by kamalupasena** [comment]
I used pod install

**Comment by groue** [comment]
When I set up a fresh iOS app with GRDB as a Cocoapods dependency, archive it with Xcode, and then inspect the content of the built archive to look for the architectures included in the GRDB framework embedded in the application, I get the following:

```
$ lipo -info /Users/groue/Library/Developer/Xcode/Archives/2017-07-18/Test 18-07-2017 10.24.xcarchive/Products/Applications/Test.app/Frameworks/GRDB.framework/GRDB
Architectures in the fat file: /Users/groue/Library/Developer/Xcode/Archives/2017-07-18/Test 18-07-2017 10.24.xcarchive/Products/Applications/Test.app/Frameworks/GRDB.framework/GRDB are: armv7 arm64 
```

This should perfectly suit your iPhone 5.

What happens when you compare the output of the `lipo -info` command on your own archive with the lines above? Generally, please grab more information about the error message you get, because I don't see any problem with GRDB so far.

**Comment by groue** [comment]
Besides, did you do your mandatory Google search before opening this issue?

**Comment by kamalupasena** [comment]
yes i did a google search, and i am using GRDB in Custom keyboard extension

**Comment by groue** [comment]
I'm not familiar with keyboard extensions. Please share with us the things you have learned! Your issue won't get solved by itself, you know 😉

**Comment by kamalupasena** [comment]
Able to fixed by adding GRDB pod into HostApp and extension both seems like when archiving pods at extension not archiving. So need to add pod in both extension and HostApp it will solved this issue, @groue  thank you for your support and this awesome lib

**Comment by groue** [comment]
I'm very happy you were able to fix this issue! And thanks for sharing your solution here: it will certainly help other users.

Happy GRDB!
