### ISSUE TITLE
compile error with rows.next() in Swift 3

### ISSUE THREAD

**Issue by sgmckenna** [groue/GRDB.swift#244]
I am developing an iOS app using Swift 3 and the GRDB SQLite library. The following code fragment causes a compile error of "value of type '[Row]' has no member 'next'"

    let rows = try Row.fetchAll(db, sql, arguments:arguments)
    while let row = try rows.next() {             <--- line with error
      ...
    }

As far as I can tell I am following the example in the docs correctly. Can anyone tell me what I am doing wrong?

**Comment by t089** [comment]
`[Row]` is an array of `Row` objects aka `Array<Row>`. Array has no function `next()`, as indicated by the error. Looking at the example you might want to use: `Row.fetchCursor()` instead.

```
let rows = try Row.fetchCursor(db, "SELECT * FROM pointOfInterests")
while let row = try rows.next() { 
  ...
}
```

**Comment by sgmckenna** [comment]
thanks. that fixed it :)
