### ISSUE TITLE
Not able to store a json in one of sqlite column 

### ISSUE THREAD

**Issue by prasann-1433** [groue/GRDB.swift#245]
Hi, 

First of all thanks for such a wonderful library. Its really good. 
But I am facing an issue and would be glad if you can help. 

I have a requirement to enter a json in one column of sqlite table. when I am trying to insert it insert all values of columns except the one column which needs to get the json. My json is simple:

{
	"xyz": ["xyz"],
	"eee": ["ddd"]
}

my query is also like insert into table ('x', 'y', 'z') values ('xx', '{"xyz": ["xyz"],"eee": ["ddd"]}', 'zz')

Please note the query is correct, since when I try using the same query in sqlite directly, it does inserted all values.

**Comment by groue** [comment]
> Please note the query is correct, since when I try using the same query in sqlite directly, it does inserted all values.

Good. Then make sure you run the same query with GRDB.

If you want to see the actual queries you run, provide a `trace` block to your database queue configuration (see the READLE for more details).

**Comment by groue** [comment]
No news, good news. Happy GRDB!
