### ISSUE TITLE
Q: Using Cocoa Pods, how do I install the xCode Beta/Swift 4 branch from my Pods file?

### ISSUE THREAD

**Issue by KMessina1** [groue/GRDB.swift#250]
Obviously, haven't done this before.

**Comment by gps** [comment]
@KMessina1: Something like this should work, I believe: `pod 'GRDB.swift', :git => 'https://github.com/groue/GRDB.swift', :branch => 'Swift4'`

See https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo.

**Comment by groue** [comment]
BTW @KMessina1, @gps, the Swift4 branch is still in flux. Check the [release notes](https://github.com/groue/GRDB.swift/blob/Swift4/CHANGELOG.md) when you upgrade.

**Comment by KMessina1** [comment]
Thank you so much for your help, I wasn't sure how to do it, simple enough. Yes, when I tried to compile it balked at the .row[column] in Fetched....swift file complaining can't subscript a string because column is set as [String].
