### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by alexch2000** [groue/GRDB.swift#251]
Hi, 

Can we add linux support for GRDB, 
because for now it can not be compiled because of including core graphics
`
.build/checkouts/GRDB.swift.git-6344093227085512296/GRDB/Core/Support/CoreGraphics/CGFloat.swift:1:8: error: no such module 'CoreGraphics'
22:27:33 import CoreGraphics
22:27:33        ^
`

**Comment by groue** [comment]
Hello @alexch2000 

Please see pull request #205.
