### ISSUE TITLE
GRDBCipher: Setting the cipher

### ISSUE THREAD

**Issue by iceColdChris** [groue/GRDB.swift#252]
I was wondering if its currently possible to set the cipher to a specified version, the version I need is GCM. Normally this can be done by running `Pragma cipher = 'aes-256-gcm'` right after the database is opened, this does not seem to be setting the cipher to GCM though. I was wondering if maybe there was a way I could set this, or some configuration field I'm missing.

Thanks in advance!

**Comment by groue** [comment]
Hello @iceColdChris,

I'm not sure, but I expect that the `pragma cipher` has to be run at a very precise step of the database creation. Would you mind looking at the current [database setup](https://github.com/groue/GRDB.swift/blob/v2.0.1/GRDB/Core/Database.swift#L351-L428)?

**Comment by iceColdChris** [comment]
@groue Taking a look at the official [doc's](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher) for SQLCipher, it says that "`PRAGMA cipher` must be called after `PRAGMA key` and before the first actual database operation or it will have no effect." 

Taking a look at the code in init, it looks like you are setting the key from the config at line [402](https://github.com/groue/GRDB.swift/blob/v2.0.1/GRDB/Core/Database.swift#L402). I don't have the code in front of me right now but I'm assuming the sqlite3_key function is similar to the `pragma key` command, and actually looking at the official documentation for SQLCipher it looks like the pragma interface actually calls the sqlite3_key function under the hood.

It would be my guess that `pragma cipher` should be run directly after this.

**Comment by groue** [comment]
@iceColdChris,

I've played with `pragma cipher` in the [customCipher](https://github.com/groue/GRDB.swift/tree/customCipher) branch, commit 98462b9f7dfc9886c7c7defb754a97607c3b5764.

Unfortunately, it won't change the cipher: SQLCipher keeps on using the default cipher `aes-256-cbc`. As a matter of fact, support for changing the cipher is deprecated:

- https://discuss.zetetic.net/t/pragma-cipher-command-is-deprecated-please-remove-from-usage/1766
- https://github.com/sqlcipher/android-database-sqlcipher/issues/224

I stop investigating. Please reopen this issue, or open a pull request, if you have some new elements.
