### ISSUE TITLE
Swift 4 protection level

### ISSUE THREAD

**Issue by EesaJacobs** [groue/GRDB.swift#253]
Hi,

When I include the latest pod into my Xcode project, at compile time I get several issues as a result of Swift 4.0. Private variables/properties cannot be used in Class extensions unless they're marked as internal instead of private.

I've since downloaded the Swift 4.0 GRDB branch and embedded it into my Xcode project as a Framework, made the private/internal protection level issues and it resolves the issue(s). I would however prefer to have this done via your accepted code or update pod. Unless there's something I'm not doing right with the Swift 4 GRDB branch (now known as GRDB 2.0.1). Can you please advise?

**Comment by groue** [comment]
Hello @EesaJacobs.

The file [README.md](https://github.com/groue/GRDB.swift/blob/master/README.md) lists, at its very beginning, which GRDB version should be used for each supported version of Swift. For Swift 4, it is GRDB 2.0.1.

Once you have chosen you GRDB version, make sure that GRDB is compiled with the version of Swift you expect. This is done by checking the value of the SWIFT_VERSION build setting in the GRDB target used by your application (in the Pods project if you use CocoaPods).  If SWIFT_VERSION is not the expected 4.0, then a quick fix may be the following:

- make sure that your own app uses Swift 4.0
- install the latest version of CocoaPods
- reinstall the pods

Checkout out relevant documentation if you don't know how to perform each one of those steps.

If this technique does not fit your needs, or if it doesn't fix your trouble, then please look for support at CocoaPods: this is not an issue with GRDB.

**Comment by EesaJacobs** [comment]
Hi,

Silly me, I was setting the SWIFT_VERSION setting to 3.2 to support pre-swift 4 pods. Updating this to 4.0 and rectifying the misaligned pods fixes issues raised in GRDB.

You guys have out done yourselves, keep up the good work and thanks!

**Comment by groue** [comment]
Thanks, @EesaJacobs ! It's a tiny mistake we've all done, you know. Happy GRDB 😄
