### ISSUE TITLE
Error : 'grdbStatementCache' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by FreudGit** [groue/GRDB.swift#254]
Hi.I get 75 error on GRDB installed using pod  when I try to compile a project with xCode 6.

Error like: Error : 'grdbStatementCache' is inaccessible due to 'private' protection level

Any Idea?

**Comment by groue** [comment]
Hello @FreudGit,

This error means that GRDB is not compiled with the correct version of Swift. Please refer to #253 for further information.
