### ISSUE TITLE
Help with installation!!

### ISSUE THREAD

**Issue by pranavBiz2Credit** [groue/GRDB.swift#256]
Hi 
First off, thank you so much for such a wonderful and easy to use plugin for SQlite. I've particularly enjoyed using it and found to be much more simpler than other options available such as FMDB and SwiftyDB among others.

Though I was able to make it the integration work by following the steps outlined on your github page under manual section adding it as an embedded binary. I wanted to ask whether or not is possible to integrate GRDB in the application that I'm working on by integrating swift files directly?

**Comment by groue** [comment]
Hello @pranavBiz2Credit 

Integrating GRDB files directly into your application is not a supported installation method, so I don't have any idea if this is working or not.

Just go ahead and try! But you get any support unless you give a good reason for using an unsupported installation method.

Happy GRDB!

**Comment by pranavBiz2Credit** [comment]
Thanks for a prompt response @groue 

Actually I tried doing it, failing which I opened an issue. Heres a sneak peek into error Im getting
**Trailing 'where' clause for extension of non-generic type 'Range'** and couple others involving 'upper bound' and 'lower bound'

I will try and outline my issue here. Hope you can make some sense out of it. 

It is often that I have to send the source code across to my client so that he can run the same on his system. It seems that when he does so the application loses all the references to the embedded binaries. As you can imagine he has to go through the whole process of adding the target dependencies, embedded framework etc for each build that I send across. If I were able to somehow add the the files to application directly, it will spare him a lot of time and efforts.

Regards
Pranav

**Comment by groue** [comment]
> I will try and outline my issue here. Hope you can make some sense out of it.

I'm sorry I have been misunderstood: *you* will spend the time making sense out of it. You are paid by your clients, so you take care of them.

**Comment by pranavBiz2Credit** [comment]
Fair enough!

> But you get any support unless you give a good reason for using an unsupported installation method.

My bad I thought you were keen on hearing out my reason for using unsupported installation method. Clearly thats not the case. 

Thank for GRDB nevertheless

**Comment by groue** [comment]
> My bad I thought you were keen on hearing out my reason for using unsupported installation method. Clearly thats not the case.

On the contrary, I was really curious! Sometimes people have interesting needs that can enhance the library for all its users. In your case, the need is too narrow for me to focus on it for free.

Happy GRDB!
