### ISSUE TITLE
Fetching from Record subclasses

### ISSUE THREAD

**Issue by pmanna** [groue/GRDB.swift#258]
Apologies if that has been discussed before, but I'm finding an issue moving from an old version of GRDB with Swift 3 to the latest & Swift 4.

My objects look like:

```swift
open class GenericObject: Record {
  ... some common code ...
  class func someRecords() -> [GenericObject] {
    return DatabaseHandler.sharedInstance.dbQueue.inDatabase { db in
      try! self.fetchAll(db, "SELECT * FROM \(self.databaseTableName) WHERE status=?",
            arguments: [Status.someStatus.rawValue])
    }
  }
}

open class ObjectA: GenericObject {
  ... some custom code ...
}

open class ObjectB: GenericObject {
  ... some custom code ...
}
```

With Swift 3 and a previous version, the following would happen:

```swift
  ObjectA.someRecords()  // [ObjectA]
  ObjectB.someRecords() //  [ObjectB]
```

Now, with Swift 4 and latest GRDB, I'm experiencing something different:

```swift
  ObjectA.someRecords()  // [GenericObject] - not what I was expecting!
  ObjectB.someRecords() //  [GenericObject]
```

Now, it's obvious how to work around that by copying the same someRecords() code to the subclasses, and everything goes as it should, but it would look awful. Besides, why is this happening? Is this Swift 4 or GRDB, and if the latter, is this intentional?

**Comment by groue** [comment]
Hello @pmanna,

The `someRecords()` is explicitely declared as returning an array of `GenericObject`:

```swift
open class GenericObject: Record {
    class func someRecords() -> [GenericObject]
}
```

It hence returns `[GenericObject]`, whatever the class upon it you call it:

```swift
ObjectA.someRecords()  // [GenericObject], as declared
```

This may not be what you expect, but this is what the declaration of `someRecords` mandates the compiler to do. For Swift 3, and 4.

**Now, the solution to your problem:**

You want `someRecords` to return `[Self]`, which means that it returns the same type as the receiver. Unfortunately, the compiler won't accept that you define a method that returns `[Self]` on GenericObject. Don't ask me why. Maybe this limitation will be lifted in a future compiler version.

But today, you can declare `someRecords` as an extension of the RowConvertible protocol. Why there? Because the `fetchAll` method, that you know and use, and is able to return the expected type, is declared this way. So let's just do the same. We want to restrict `someRecords` to GenericObject and its subclasses, though, so let's add a where clause to the extension:

```swift
extension RowConvertible where Self: GenericObject {
    static func someRecords() -> [Self] {
        return DatabaseHandler.sharedInstance.dbQueue.inDatabase { db in
            try! self.fetchAll(db,
                "SELECT * FROM \(self.databaseTableName) WHERE status=?",
                arguments: [Status.someStatus.rawValue])
        }
    }
}
```

And there you go!

```swift
ObjectA.someRecords()  // [ObjectA]
ObjectB.someRecords() //  [ObjectB]
```

**Comment by pmanna** [comment]
Thanks for your help, I'll certainly try to implement your suggestion.
I may have specified the problem improperly, though: of course I'd expect the 2 arrays to be of type [GenericObject], still the objects inside should be of the right type (i.e. ObjectA & ObjectB respectively), and I should be able to access them as such, but that's not the case!
Even though the objects are fetched from the right table (i.e. self.databaseTableName is used properly), all I get are GenericObject, and all the subclasses properties/methods are lost.

As a comparison, I've tried the following Playground:

```swift
class GenericObject {
    let commonString = "This is a generic object"
    
    required init() {
    }
    
    class func someRecords() -> [GenericObject] {
        let anObject = self.init()
        
        return [anObject]
    }
}

class ObjectA: GenericObject {
    let aString = "This is object A"
}

class ObjectB: GenericObject {
    let bString = "This is object B"
}

let genericObjs = GenericObject.someRecords()
print(genericObjs[0].commonString)

let objectAs = ObjectA.someRecords()
print((objectAs[0] as! ObjectA).aString)

let objectBs = ObjectB.someRecords()
print((objectBs[0] as! ObjectB).bString)
```

And the result is indeed what I expected (run on Swift4):
```
This is a generic object
This is object A
This is object B
```

GRDB doesn't seem to apply the same logic, at least in its recent builds, whenever I've the time I'll try to make a similar playground for it and post it here.
Make no mistake, I guess there may well be reasons why this is the desired behaviour, I'm just a bit confused, that's all!

**Comment by groue** [comment]
Hello again @pmanna,

Oh, I better understand now. I admit I'm totally puzzled by the behavior you are exhibiting. I don't know yet if this is a change introduced by mistake in GRDB, a change introduced by mistake in Swift 4, or a planned change of Swift4.

Let's reopen the issue until we have figured this out.

**Comment by pmanna** [comment]
Thanks @groue for your help!

In the meantime, I've tried the approach that you suggested, and it still doesn't return the object types I'm querying from, but everything is transformed in GenericObject somewhere on the way back to my code. What's worse, if I implement an ObjectZ class that tries to override someRecords() (in the real world, I'm querying on a different _ORDER BY_), the extension modified as

```swift
extension RowConvertible where Self: ObjectZ {
```
is never called, and the GenericObject one is used instead.

While this isn't clarified, I'm afraid the only way for now is to override someRecords() for each subclass…

**Comment by groue** [comment]
> In the meantime, I've tried the approach that you suggested, and it still doesn't return the object types I'm querying from

The following minimal code returns the type you're querying:

```swift
import GRDB

// Use a memory database for quick prototyping, with minimal table
let dbQueue = DatabaseQueue()
try! dbQueue.inDatabase { db in
    try db.execute("""
        CREATE TABLE t(a);
        INSERT INTO t(a) VALUES (NULL)
        """)
}

// Minimal record and subclass that can feed from table `t`
class GenericObject: Record {
    override class var databaseTableName: String { return "t" }
}
class ObjectA: GenericObject { }

// Define someRecords on RowConvertible
extension RowConvertible where Self: GenericObject {
    static func someRecords() -> [Self] {
        return dbQueue.inDatabase { db in
            try! self.fetchAll(db, "SELECT * FROM \(self.databaseTableName)")
        }
    }
}

let objects = ObjectA.someRecords() // [ObjectA]
print(type(of: objects[0]))         // "ObjectA"
```

**Comment by pmanna** [comment]
OK, I understand a bit more now: please bear with me, I'll post a few samples below of working and non-working code.
First, a pure Swift 4 code that resembles what I'm actually doing, and works as expected:

```swift
class GenericObject {
    let commonString = "This is a generic object"
    
    required init() {
    }
    
    class func someRecords() -> [GenericObject] {
        let anObject = self.init()
        
        print("I've created \(type(of: anObject))")
        
        return [anObject]
    }
}

class ObjectA: GenericObject {
    let aString = "This is object A"
}

class ObjectB: GenericObject {
    let aString = "This is object B"
}

let classes=[GenericObject.self,ObjectA.self,ObjectB.self]

let genericObjs = classes[0].someRecords()
print("Object 0 is \(type(of: genericObjs[0]))")

let objectAs = classes[1].someRecords()
print("Object 0 is \(type(of: objectAs[0]))")

let objectBs = classes[2].someRecords()
print("Object 0 is \(type(of: objectBs[0]))")
```

Output:
```
I've created GenericObject
Object 0 is GenericObject
I've created ObjectA
Object 0 is ObjectA
I've created ObjectB
Object 0 is ObjectB
```

**Comment by pmanna** [comment]
Then, the code as I first wrote it, but with fixed classes: this doesn't work, even though it's clear it's fetching from the right table
```swift
import GRDB

// Use a memory database for quick prototyping, with minimal table
let dbQueue = DatabaseQueue()
try! dbQueue.inDatabase { db in
    try db.execute("""
        CREATE TABLE generic(g);
        INSERT INTO generic(g) VALUES ("Generic")
        """)
    try db.execute("""
        CREATE TABLE objecta(g,a);
        INSERT INTO objecta(g,a) VALUES ("Generic","ObjectA")
        """)
    try db.execute("""
        CREATE TABLE objectb(g,b);
        INSERT INTO objectb(g,b) VALUES ("Generic","ObjectB")
        """)
}

class GenericObject: Record {
    override class var databaseTableName: String { return "generic" }
    
    static func someRecords() -> [GenericObject] {
        let tableName = self.databaseTableName
        
        print("Getting records from \(tableName)")
        
        let records = dbQueue.inDatabase { db in
            try! self.fetchAll(db, "SELECT * FROM \(tableName)")
        }
        
        if records.count > 0 {
            print("I've fetched a set of \(type(of: records[0]))")
        }
        return records
    }
}

class ObjectA: GenericObject {
    override class var databaseTableName: String { return "objecta" }
}

class ObjectB: GenericObject {
    override class var databaseTableName: String { return "objectb" }
}

let genericObjs = GenericObject.someRecords()
print("Object 0 is \(type(of: genericObjs[0]))")

let objectAs = ObjectA.someRecords()
print("Object 0 is \(type(of: objectAs[0]))")

let objectBs = ObjectB.someRecords()
print("Object 0 is \(type(of: objectBs[0]))")
```

Output:
```
Getting records from generic
I've fetched a set of GenericObject
Object 0 is GenericObject
Getting records from objecta
I've fetched a set of GenericObject
Object 0 is GenericObject
Getting records from objectb
I've fetched a set of GenericObject
Object 0 is GenericObject
```

**Comment by pmanna** [comment]
Now, the code modified as you suggested: it does indeed work, if I'm coding from statically defined classes:
```swift
import GRDB

// Use a memory database for quick prototyping, with minimal table
let dbQueue = DatabaseQueue()
try! dbQueue.inDatabase { db in
    try db.execute("""
        CREATE TABLE generic(g);
        INSERT INTO generic(g) VALUES ("Generic")
        """)
    try db.execute("""
        CREATE TABLE objecta(g,a);
        INSERT INTO objecta(g,a) VALUES ("Generic","ObjectA")
        """)
    try db.execute("""
        CREATE TABLE objectb(g,b);
        INSERT INTO objectb(g,b) VALUES ("Generic","ObjectB")
        """)
}

class GenericObject: Record {
    override class var databaseTableName: String { return "generic" }
}

class ObjectA: GenericObject {
    override class var databaseTableName: String { return "objecta" }
}

class ObjectB: GenericObject {
    override class var databaseTableName: String { return "objectb" }
}

extension RowConvertible where Self: GenericObject {
    static func someRecords() -> [Self] {
        let tableName = self.databaseTableName
        
        print("Getting records from \(tableName)")
        
        let records = dbQueue.inDatabase { db in
            try! self.fetchAll(db, "SELECT * FROM \(tableName)")
        }
        
        if records.count > 0 {
            print("I've fetched a set of \(type(of: records[0]))")
        }
        return records
    }
}

let genericObjs = GenericObject.someRecords()
print("Object 0 is \(type(of: genericObjs[0]))")

let objectAs = ObjectA.someRecords()
print("Object 0 is \(type(of: objectAs[0]))")

let objectBs = ObjectB.someRecords()
print("Object 0 is \(type(of: objectBs[0]))")
```

Output:
```
Getting records from generic
I've fetched a set of GenericObject
Object 0 is GenericObject
Getting records from objecta
I've fetched a set of ObjectA
Object 0 is ObjectA
Getting records from objectb
I've fetched a set of ObjectB
Object 0 is ObjectB
```

**Comment by pmanna** [comment]
Finally, the situation as it really is: the classes to fetch are defined at runtime, and even your suggestion doesn't work anymore

```swift
import GRDB

// Use a memory database for quick prototyping, with minimal table
let dbQueue = DatabaseQueue()
try! dbQueue.inDatabase { db in
    try db.execute("""
        CREATE TABLE generic(g);
        INSERT INTO generic(g) VALUES ("Generic")
        """)
    try db.execute("""
        CREATE TABLE objecta(g,a);
        INSERT INTO objecta(g,a) VALUES ("Generic","ObjectA")
        """)
    try db.execute("""
        CREATE TABLE objectb(g,b);
        INSERT INTO objectb(g,b) VALUES ("Generic","ObjectB")
        """)
}

class GenericObject: Record {
    override class var databaseTableName: String { return "generic" }
}

class ObjectA: GenericObject {
    override class var databaseTableName: String { return "objecta" }
}

class ObjectB: GenericObject {
    override class var databaseTableName: String { return "objectb" }
}

extension RowConvertible where Self: GenericObject {
    static func someRecords() -> [Self] {
        let tableName = self.databaseTableName
        
        print("Getting records from \(tableName)")
        
        let records = dbQueue.inDatabase { db in
            try! self.fetchAll(db, "SELECT * FROM \(tableName)")
        }
        
        if records.count > 0 {
            print("I've fetched a set of \(type(of: records[0]))")
        }
        return records
    }
}

let classes=[GenericObject.self,ObjectA.self,ObjectB.self]

let genericObjs = classes[0].someRecords()
print("Object 0 is \(type(of: genericObjs[0]))")

let objectAs = classes[1].someRecords()
print("Object 0 is \(type(of: objectAs[0]))")

let objectBs = classes[2].someRecords()
print("Object 0 is \(type(of: objectBs[0]))")
```

Output:
```
Getting records from generic
I've fetched a set of GenericObject
Object 0 is GenericObject
Getting records from objecta
I've fetched a set of GenericObject
Object 0 is GenericObject
Getting records from objectb
I've fetched a set of GenericObject
Object 0 is GenericObject
```

**Comment by pmanna** [comment]
I reckon that the problem is far from clear, still I've tried to collect as much data as possible.
What I understand from the above is that Swift 4 hasn't changed much to be an issue in itself, but somehow GRDB is affected: it knows the exact kind of object it's working with (the table name is correct), but it seems to miss the proper class, and it returns the superclass instead!

**Comment by groue** [comment]
> OK, I understand a bit more now: please bear with me, I'll post a few samples below of working and non-working code.

Sure, I'm with you.

You have given four sample codes, which explore three techniques, and test them against your "real goal" which is fetching records whose type is defined at runtime:

- [[Sample Code 1, with `self.init`](https://github.com/groue/GRDB.swift/issues/258#issuecomment-335417275)) (static type: OK, dynamic type: OK)
- [[Sample Code 2, with class method](https://github.com/groue/GRDB.swift/issues/258#issuecomment-335417939)) (static type: not OK, dynamic type: not OK)
- [[Sample Code 3, with protocol method](https://github.com/groue/GRDB.swift/issues/258#issuecomment-335418558)) (static type: OK)
- [[Sample Code 4, with protocol method](https://github.com/groue/GRDB.swift/issues/258#issuecomment-335419096)) (dynamic type: not OK)

Please tell me if I'm wrong when I say:

- We haven't yet found a solution to your "real goal".
- The issue has been introduced by the migration to Swift 4 and GRDB 2. Before this migration, you were using Swift 3 and GRDB 1.x, and you were able to fetch records whose type is defined at run time, with a technique similar to sample code 2 (with class method).

I bet that this issue has been introduced by Swift 4. The `fetchAll()` method is one of the most stable ones in GRDB. Its implementation has not changed during the transition to Swift 4. I'll have a look to the detailed changes, but I'm pretty sure I won't find anything.

This issue finds its roots in the behavior of Swift regarding static vs. dynamic dispatch. This behavior is subtle, to say the least. On top of that, I suspect that you push the boundaries of what the Swift implementors expect developers to do: your use case may well have been overlooked in their test cases.

When I look at the [Swift Evolution proposals implemented for Swift 4](https://apple.github.io/swift-evolution/#?version=4), I don't see any one which clearly aims at changing the dispatch behavior, but  [SE-0160](https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md), and [SE-0156](https://github.com/apple/swift-evolution/blob/master/proposals/0156-subclass-existentials.md). Did one of those proposals introduce the change we experience as an undesired side effect? Is this change intentional? I don't know.

We have two next steps:

- Open an issue at http://bugs.swift.org, in order to sort this out. For this, we need a minimal sample code that exhibits the issue. A piece of code that uses runtime types, and exhibits a different behavior in Swift 3 and Swift 4. Without any GRDB dependency, of course.
- Find a solution to your issue.

**Comment by groue** [comment]
> What I understand from the above is that Swift 4 hasn't changed much to be an issue in itself, but somehow GRDB is affected: it knows the exact kind of object it's working with (the table name is correct), but it seems to miss the proper class, and it returns the superclass instead!

Yes, this is pretty clear in [sample code 4](https://github.com/groue/GRDB.swift/issues/258#issuecomment-335419096), and this is **very** puzzling:

> Getting records from objecta
> I've fetched a set of GenericObject

**Comment by pmanna** [comment]
> We haven't yet found a solution to your "real goal".

Yes, that's correct: I'm just using a workaround where each subclass re-implements the same code, and it works

> The issue has been introduced by the migration to Swift 4 and GRDB 2. Before this migration, you were using Swift 3 and GRDB 1.x, and you were able to fetch records whose type is defined at run time, with a technique similar to sample code 2 (with class method).

Correct again: I've run the playgrounds above under Xcode 8 / Swift 3 / GRDB 1.3.0 (changing the multi-line strings, obviously), and they all run flawlessly, including sample 2.
If you need them, I can forward both projects to you, of course.

> Open an issue at http://bugs.swift.org, in order to sort this out. For this, we need a minimal sample code that exhibits the issue. A piece of code that uses runtime types, and exhibits a different behavior in Swift 3 and Swift 4. Without any GRDB dependency, of course.

I'm afraid I've spent on this as much time as I could afford without hurting my schedule: the one piece of code I came up with (sample 1) doesn't seem to suffer any issue between Swift 3 & 4.
There's something happening later within `fetchAll` (or possibly `inDatabase`) that triggers the issue, but I don't feel like diving in there at this time: you're certainly better equipped to do that, but I surely can't ask for that!

> Find a solution to your issue.

Well, I've that workaround of course, so I'm fine for the moment: if it stays in place for a while it will raise a few eyebrows when someone else will come to work on my code, but I'll write down some comments…

Thank you again, sorry to have created such an headache!

**Comment by groue** [comment]
OK, I'll deal with the Swift guys. Happy you found a workaround, @pmanna. Happy GRDB!

**Comment by erdem-inan** [comment]
Hello, 

First thanks you for this library :)

I am currently working on migrating our app to Swift 4 and I fell on the same issue.
I know the workaround, I was just wondering if you found any explaination to this ? Did you create a bug for swift for this ?

Thanks !

**Comment by groue** [comment]
Hello @erdem-inan, thank you! I'm sorry but I don't really remember now, nearly one year after. A quick search yields no result. And I'm not currently investigating this topic.

**Comment by erdem-inan** [comment]
Ok thanks ! I will use the "workaround" then :)
