### ISSUE TITLE
Sir,

### ISSUE THREAD

**Issue by burkaslarry** [groue/GRDB.swift#269]
Sir/Madam,

I am working on the recursive function to insert database record from server to local sqlite. Server provides more than one record for company . When it comes to more than one , only first one is inserted. It is not what I want. Would you please tell me more guideline for sequential transaction of sqlite database using your GRDB.swift 

Here is my code

```
   try dbQueue.inTransaction { db in
                 
                    let newCompany : Company = Company.init(chiName: servComp.chiName, engName:servComp.engName , brno:  servComp.brno  , country: servComp.country  , finyear : servComp.finyear )
                    newCompany.companyKey =  servComp.companyKey
                    newCompany.securityGroup = servComp.securityGroup
                    newCompany.companyVersion = servComp.companyVersion
                    newCompany.incomeExpenseVersion = servComp.incomeExpenseVersion
                    newCompany.fyreportVersion = servComp.fyreportVersion
                    
                    print("create proceed servComp : \(servComp.engName)")
                    
                    try newCompany.insert(db)
                    
                    print("create ok ")
                    let countComp : Int =  try Int.fetchOne(db , " SELECT COUNT(*) FROM company " )!
                    if countComp == 1 {
                        UserDefaults.standard.set(newCompany.id, forKey: "selected_comp")
                        user?.setCompany(thiscomp: newCompany)
                    }
                    
                    return .commit
                }
```

**Comment by groue** [comment]
Hello @burkaslarry,

> Sir,

**This is not a proper Github issue title.** A proper issue title provides information about the issue: "I can't compile the project", "error 10 while reading from the database", etc.

This allows internet search engines to index the issue, Github users to quickly find the issue they are looking for in a list, and repository maintainers to receive an email that has a clear subject.

Maybe you could not find any good title? Indeed, when I read the remaining of your issue, I also have a trouble finding out what you are asking for.

**When you can not find a proper issue title, it's too early to open an issue.**

Please come back when your ideas and question are clear.

**Comment by groue** [comment]
It's not the first time I do not answer one of your question. I'm sorry. You have to increase the quality and focus of your questions. Maybe find someone who is able to write English with more precision?
