### ISSUE TITLE
Problem running the demo project on a device

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [groue/GRDB.swift#272]
Hi again,

I'm on Xcode 9 and my device is an iPhone 5 running iOS 10.3.3. When I try to run the demo project, I get the following error.

> GRDBDemoiOS does not have an architecture that Isuru's iPhone can execute.

![screen shot 2017-11-15 at 8 29 28 am](https://user-images.githubusercontent.com/2551877/32816561-52d312c6-c9df-11e7-9b27-3e9b27a4d82d.png)

I searched and found that I need to set the Supported Platforms in Build Settings to iOS but it's already set as iOS. I also deleted the Derived Data folder, cleaned and build the project but to no avail.

**Comment by groue** [comment]
I don't quite know what's wrong: iPhone 5 uses the armv7 architecture, and should be supported by the GRDBDemo application.

Unfortunately I don't have any such device that would help me reproduce this issue, and help fixing it. Will you please keep on investigating? I'll happily accept a pull request that fixes this issue.

**Comment by groue** [comment]
Any news, @Isuru-Nanayakkara?

**Comment by Isuru-Nanayakkara** [comment]
Very sorry @groue, I've been quite busy with this application I'm currently working on. I ran your other [demo project](https://github.com/groue/GRDBDemo) without an issue though. I'll just close this issue for now. Will get back to it when I have more free time.

**Comment by groue** [comment]
That's fine, Isuru! Happy GRDB, meanwhile :-)
