### ISSUE TITLE
No such module GRDB

### ISSUE THREAD

**Issue by Pirokar** [groue/GRDB.swift#276]
## Environment

**GRDB flavor(s): GRDB.swift
**GRDB version: 2.3.1
**Installation method:** CocoaPods
**Xcode version:** 9.1
**Swift version:** 3.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.1

Hello! In XCode this error happend: No such module GRDB. Trying to remove xcode, didn't help. Works in AppCode.

**Comment by groue** [comment]
Hello @Pirokar,

The top of [README.md](https://github.com/groue/GRDB.swift/blob/master/README.md) lists GRDB requirements: GRDB v2.3.1 requires Swift 4. If you plan to keep Swift 3.2, use GRDB v1.3.0.
