### ISSUE TITLE
Can you make GRDB and GRDBCipher comply to protocol

### ISSUE THREAD

**Issue by IanLuo** [groue/GRDB.swift#277]
## What did you do?

My framework uses GRDB, I want to add a var to switch on/off cipher

## What did you expect to happen?

Can you make GRDB and GRDBCipher comply to protocol so I can call them with protocol

## What happened instead?
 Otherwise I can only provide two different frameworks 

## Environment

**GRDB flavor(s):** GRDB, GRDBCipher
**GRDB version:** 2.3.1
**Installation method:** Carthage
**Xcode version:** Xcode 9.2 beta
**Swift version:** Swift 4.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13

**Comment by groue** [comment]
Hello @IanLuo,

Just use GRDBCipher.

When you want to encrypt a database, provide a passphrase:

```swift
import GRDBCipher

// Encrypted database
var config = Configuration()
config.passphrase = "secret"
let dbQueue = try DatabaseQueue(path: "...", configuration: configuration)
```

When you don't want to encrypt, don't provide any passphrase:

```swift
import GRDBCipher

// Clear-text database
let dbQueue = try DatabaseQueue(path: "...")
```

Does it solve your issue?

**Comment by IanLuo** [comment]
@groue, it does, thank you for your great work on GRDB
