### ISSUE TITLE
Multiple sections in FetchedRecordsController

### ISSUE THREAD

**Issue by hitmanpt** [groue/GRDB.swift#278]
## What did you do?

Using GRDB I need to create sections on the table. My table as one column called datestamp and it's witch is the "timestamp" but only with date and I want to create sections for different dates.
So far the important part (I think) it's this. I have everything configured for the sections

```
var expensesController: FetchedRecordsController<Expense>!
self.expensesController = try! FetchedRecordsController(db, request: Expense.order(Column("datestamp").desc))
```

## What did you expect to happen?

Multiple sections on the table

## What happened instead?

Shows only one section

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:**
**Installation method:** CocoaPods
**Xcode version:** 9.1
**Swift version:** 4
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.1

**Comment by groue** [comment]
Hello @hitmanpt,

The [FetchedRecordsController documentation](https://github.com/groue/GRDB.swift/blob/v2.3.1/README.md#table-and-collection-views) states:

> **Note**: In its current state, FetchedRecordsController does not support grouping table view rows into custom sections: it generates a unique section.

You have a few options:

1. add yourself support for sections in FetchedRecordsController, and submit a pull request.
2. wait for me or another contributor to add support for sections in FetchedRecordsController, and submit a pull request (this may take a while).
3. build your own sections.

The third options is surely the easiest.

**Comment by groue** [comment]
Any thought or comment, @hitmanpt?

**Comment by hitmanpt** [comment]
@groue I haven’t had the time to work on my project but surely I’ll go with option three
I might need some help along the road...
That’s for your fast response and keep the awesome work

**Comment by groue** [comment]
No problem, @hitmanpt. Let's close this issue until you come back with any new question. Have a nice day!

**Comment by hitmanpt** [comment]
I had a little time to try and create the sections and for that I tried to create an array of `FetchedRecordsController` but after some tweaks the app just crashes
This is the code I just used
`try! db.inDatabase { _db in
            
            let expenses = try Expense.order(Column("datestamp").desc).fetchAll(_db)
            var datestamp = expenses.first?.datestamp
            var expensesGroup: [Expense]? = nil
            var add: bool = true
            for exp in expenses {
                if (datestamp == exp.datestamp && add == true) {
                    expensesController.append(try! FetchedRecordsController(db, request: Expense.order(Column("datestamp").desc)))
                    
                } else {
                    expensesController.sections.append(contentsOf: nil)
                    expensesGroup = nil
                    
                }
                
            }
        }`

The I removed temporarily the track changes and the table configuration I used the expensesController[indexPath.section] every time that I need to use the controller

**Comment by groue** [comment]
Hi again, @hitmanpt.

> I had a little time to try and create the sections and for that I tried to create an array of `FetchedRecordsController`

Looks like a good idea, but let's keep on reading.

> This is the code I just used

I don't quite understand what each FetchedRecordsController is in charge of. You create one FRC for each expense, and each FRC is responsible for the whole expenses. This is a weird loop, and it's hard to guess what you are trying to do here.

> but after some tweaks the app just crashes

Next time you have a crash, share a stack trace, the exact error message, and the line of code that crashes.

But this is not the current priority. The current priority is for you to gather your thoughts until you can explain how an array of FRC can help you achieve your requirements. How many FRC? What request should each of them track? What are trying to achieve?

**Comment by hitmanpt** [comment]
Ok, let's try again. I've noticed that I was missing the filter on the for cycle

So what I have it's the following.
On The class `var expensesController: [FetchedRecordsController<Expense>]!`

And on the viewDidLoad()
```
        // We get all the expenses on the db
        let exps = try! db.inDatabase { _db in
            try Expense.order(Column("datestamp").desc).fetchAll(_db)
        }

        var datestamp = ""
        
        // We go through all the expenses in the db
        for exp in exps {
            // if  the  datestamp is different that the one on memory we add a new FRC with filtered expenses (this filter was missing on my previous code)
            if (datestamp != exp.datestamp) {
                datestamp = exp.datestamp
                expensesController.append(try! FetchedRecordsController(db, request: Expense.filter(Column("datestamp") == datestamp)))
            }
        }
```

Now the strange part is the error... It's on this piece of code
```
// We get all the expenses on the db
let exps = try! db.inDatabase { _db in
    try Expense.order(Column("datestamp").desc).fetchAll(_db)
}
```
This is the message I get

> condition	() -> ()	0x0000000104b2f580 GRDB`partial apply forwarder for implicit closure #1 : @autoclosure () -> Swift.Bool in GRDB.SerializedDatabase.sync<A>((GRDB.Database) throws -> A) throws -> A at SerializedDatabase.swift

> message	() -> ()	0x0000000104b2eb40 GRDB`implicit closure #2 : @autoclosure () -> Swift.String in GRDB.SerializedDatabase.sync<A>((GRDB.Database) throws -> A) throws -> A at SerializedDatabase.swift

> file	StaticString	"/Users/pedrocavaleiro/Projects/App Store Projects/Finances Manager Pro/Pods/GRDB.swift/GRDB/Core/SerializedDatabase.swift"	

> line	UInt	89

And Xcode points me to the file Utils.swift in GRDB for this piece of code
```
/// Reserved for GRDB: do not use.
func GRDBPrecondition(_ condition: @autoclosure() -> Bool, _ message: @autoclosure() -> String = "", file: StaticString = #file, line: UInt = #line) {
    /// Custom precondition function which aims at solving
    /// https://bugs.swift.org/browse/SR-905 and
    /// https://github.com/groue/GRDB.swift/issues/37
    if !condition() {
        fatalError(message, file: file, line: line)
    }
}
```

Some extra information...
When I had only one section (it was working) with this single line
`self.expensesController = try! FetchedRecordsController(db, request: Expense.order(Column("datestamp").desc))`
So I assume that the class might be correctly built, but if you want/need to view the class just ask

**Comment by PedroCavaleiro** [comment]
Finally got it partially working. The table is loading everything nicely, the previous error was in my class and now it's fixed.
I'm currently unable to make the track changes to work.

I have the code above, it's working properly and below that

```
var i: Int = 0
        for frc: FetchedRecordsController in expensesController! {
            frc.trackChanges(
                willChange: { [unowned self] _ in
                    self.tableView.beginUpdates()
                }, onChange: { [unowned self] (controller, record, change) in
                    switch change {
                    case .insertion(let indexPath):
                        self.tableView.insertRows(at: [indexPath], with: .fade)
                        
                    case .deletion(let indexPath):
                        self.tableView.deleteRows(at: [indexPath], with: .fade)
                        
                    case .update(let indexPath, _):
                        if let cell = self.tableView.cellForRow(at: indexPath) {
                            self.configure(cell, at: indexPath)
                        }
                        
                    case .move(let indexPath, let newIndexPath, _):
                        // Actually move cells around for more demo effect :-)
                        let cell = self.tableView.cellForRow(at: indexPath)
                        self.tableView.moveRow(at: indexPath, to: newIndexPath)
                        if let cell = cell {
                            self.configure(cell, at: newIndexPath)
                        }
                        
                        // A quieter animation:
                        self.tableView.deleteRows(at: [indexPath], with: .fade)
                        self.tableView.insertRows(at: [newIndexPath], with: .fade)
                    }
                },
                   didChange: { [unowned self] _ in
                    self.tableView.endUpdates()
            })
            i = i + 1
        }
```
And after that

```
var i: Int = 0
        if (expensesController != nil) {
            for _ in expensesController! {
                try! self.expensesController![i].performFetch()
                i = i + 1
            }
        }
```

But after adding the a item it does not update the table

**Comment by PedroCavaleiro** [comment]
After a big effort I managed to get it to work with the tracker.
It adds items to the already existent sections and also add new sections (if needed)
The new cells/sections are being created in the correct paths 
If you want to see the code just ask
Thank you for your help

**Comment by groue** [comment]
That's great, @PedroCavaleiro! I may ping you whenever another user asks the same question 😉Happy GRDB!

**Comment by sirvon** [comment]
@PedroCavaleiro I would like to see this demo!

**Comment by PedroCavaleiro** [comment]
@sirvon I do not ensure that's working 100% neither that fully optimized
Seems to be working for my needs right now, I also haven't had the time to improve the code.
But right now I'm sure that deletion, insertion and update is fully working.
This is part of my app, I removed some of the unnecessary code and added more comments
If you need some help just ask

[grdb_sections_demo.zip](https://github.com/groue/GRDB.swift/files/1643314/grdb_sections_demo.zip)
