### ISSUE TITLE
About 109 issues (Semantic Issues) using GRDBCipher (SQLCipher)

### ISSUE THREAD

**Issue by saormart** [groue/GRDB.swift#285]
## What did you do?

Just installed the GRDBCipher using Cocoa Pods Installation:
use_frameworks!
pod 'GRDBCipher'

It's Normal have all this Warning issues for Swift 4 Xcode version 9.1 ?

## Environment
**GRDBCipher
**GRDB version: (CocoaPods installed the Version: 2.2.0) it's the latest ?
**GRDBCipher version: (CocoaPods installed the Version: 2.2.0) it's the latest ?
**Installation method:** (CocoaPods)
**Xcode version: 9.1
**Swift version: 4
**Platform(s) running GRDB:** (iOS)
**macOS version running Xcode: macOS Sierra Version 10.12.6

Thanks!

**Comment by groue** [comment]
Hello @saormart 

Those warnings come from the SQLCipher pod, aren't they?

**Comment by saormart** [comment]
Hello @groue, Yes you're right ! So probably we need they to fix it right ?
By the way, you have done an amazing work with this framework ! I'm glad I found it !
Thanks !

**Comment by groue** [comment]
No @saormart, we don't need to fix it, because GRDB is not responsible for warnings in the SQLCipher code. Maybe SQLCipher could have them removed, though. You can try to open an issue in [their repo](https://github.com/sqlcipher/sqlcipher)?

**Comment by saormart** [comment]
Sorry, I mean that we may need them (SQLCipher) to fix it because it's a issue on their library !
Sure I'll open a issue on it's repo! Thanks !

**Comment by groue** [comment]
No problem, @saormart. We're all trying to improve open source software. But GRDB can't fix SQLCipher :-)

**Comment by groue** [comment]
Now I must tell you that those warnings are much probably harmless. SQLite is confident in its correctness through thorough testing, not in muting compiler warnings. SQLCipher is not SQLite: it's derived from SQLite. But I *hope* that they don't screw up everything.
