### ISSUE TITLE
Invalid empty persistence container.

### ISSUE THREAD

**Issue by Joseph310** [groue/GRDB.swift#287]
Hi, 

I followed the example of the iOS Demo app, pretty much exactly.

When I call `myObject.save(db)` I get an error: 
Fatal error: MyObject: Invalid empty persistence container.

I set up the database just like the example using `dbQueue = try AppDatabase.openDatabase(atPath: databaseURL.path)` and if I go into the directory structure of the simulator with Terminal I can see my .sqlite file. It even contains the empty table. 

I am building my Swift 4 project with v 2.4.1 and against the iOS 10.3 SDK. 

What is going wrong?

Thanks

**Comment by groue** [comment]
Hello @Joseph310 

For `myObject.save(db)` to save anything in the database, you need to provide the name of the database table, and the values that are stored in the database columns, right?

The name of the database table is given by the static property `databaseTableName`. The values are given by the method `encode(to:)`, in which you provide one value for each column of the table:

```swift
func encode(to container: inout PersistenceContainer) {
    container["id"] = id
    container["name"] = name
    ...
}
```

When the `encode(to:)` method does not provide any value, GRDB doesn't know what to store in the database. It thus complains with the "Invalid empty persistence container" fatal error.

**Comment by groue** [comment]
If you need more information, please have a look at the [documentation of the Persistable protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#persistable-protocol)

**Comment by Joseph310** [comment]
Thanks! I overlooked that method in my object. 
Cheers!
