### ISSUE TITLE
Ignored Properties

### ISSUE THREAD

**Issue by mohamedgalalcs** [groue/GRDB.swift#290]
I want to know if there anything like ignored properties in GRDB? I want to have in my class some properties that I will use in my application and I don't want to add columns or save it's data in the database.

**Comment by groue** [comment]
Hello @mohamedgalalcs

> I want to know if there anything like ignored properties in GRDB?

Yes there is.

The only properties that are loaded from the database are the properties loaded in `init(row:)`. And the only ones that are persisted are the properties encoded in `encode(to:)`.

**Comment by groue** [comment]
Yes @mohamedgalalcs. But that's not a problem with GRDB. Instead, the Swift compiler wants you to set all non-optional properties to a valid value in your Contact initializers. You have two possible solutions: set `address` to a valid address, or make `address` an optional property. For more information, see the [Initialization](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html) chapter of the Swift documentation.

**Comment by mohamedgalalcs** [comment]
Thank you very much, understood.

**Comment by groue** [comment]
Happy Swift & GRDB!

**Comment by raid5** [comment]
I'm curious if there is another way to ignore properties given the new Swift 4 Codable protocol? I'm using Codable throughout my app and don't want to have to implement those functions everywhere just to ignore props. Thanks!

**Comment by groue** [comment]
Yes @raid5, that's true. According to the [documentation](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types):

> Codable types can declare a special nested enumeration named CodingKeys that conforms to the CodingKey protocol. When this enumeration is present, its cases serve as the authoritative list of properties that must be included when instances of a codable type are encoded or decoded. [...]
>
> Omit properties from the CodingKeys enumeration if they won't be present when decoding instances, or if certain properties shouldn't be included in an encoded representation. A property omitted from CodingKeys needs a default value in order for its containing type to receive automatic conformance to Decodable or Codable.

**Comment by raid5** [comment]
@groue Well that's easy. Thanks!
