### ISSUE TITLE
cannot find symbol when using GRDB in a macOS playground

### ISSUE THREAD

**Issue by aptly-io** [groue/GRDB.swift#296]
## What did you do?

Adding the only file `Stop.swift` to a framework named `Model`. It contains only 1 simple struct definition:
```swift
public struct Stop: Codable {
    public let id: String
    public let name: String
}
```

Try out the following source-code in a playground that imports `Model` and `GRDB`:
```swift

import Cocoa
import Model
import GRDB

extension Stop: RowConvertible, TableMapping {
    public static let databaseTableName = "stops"
}

let dbPath = "/tmp/stops.sqlite"
let dbQueue = try DatabaseQueue(path: dbPath)

let stops = dbQueue.inDatabase { (db) -> [Stop] in
    return try! Stop.fetchAll(db)
}
```

## What did you expect to happen?

No linking error  

## What happened instead?

Seeing this linking error:
```
Playground execution failed:

error: Couldn't lookup symbols:
  __T05Model4StopVs9DecodableAAWP
```

Reading the table works when adding the `Stop` struct definition directly into the playground (not from a framework)

## Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:** 2.7
**Installation method:** CocoaPods
**Xcode version:** 9.2
**Swift version:** 4
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.13

## Demo Project

See the code above

**Comment by groue** [comment]
Hello @aptly-io 

It looks that this is an issue with playgrounds, or Codable, or the Swift linker, but not with GRDB. Am I wrong?

**Comment by aptly-io** [comment]
Hello Groue,
Thank you for the fast response. I've also the feeling it's related to linking. GRDB tries making use of Decodable functionality but cannot find nor access that symbol (from within the playground ...?) I was hoping somebody would tell me something along the lines of please enable this or that option for the framework generation or you do it this or that way in swift ... For now I will just define my struct in the playground for prototyping  ...
Maybe I'd better take my question to SO as indeed it might not be GRDB specific? Thank you anyway!

**Comment by groue** [comment]
Yes @aptly-io, I guess SO is a better place to get an answer, *if it exists*. But I'm not quite sure a solution exists at all. I'd open a bug at bugs.swift.org. We're talking about a tooling issue, after all. Playgrounds are supposed to be a great prototyping tool. Make sure you provide a way to reproduce the problem (minimal Xcode workspace).

**Comment by groue** [comment]
Happy GRDB nevertheless!
