### ISSUE TITLE
GRDB Does not honor the  Swift 4 Decodable CodingKey

### ISSUE THREAD

**Issue by mazz** [groue/GRDB.swift#298]
## What did you do?

I mapped the incoming JSON key from ```uuid``` to ```categoryUuid``` using an ```enum CodingKeys```

```
public struct Book: Codable {
    var userId: Int64?
    public var categoryUuid: String
    public var title: String
    public var languageId: String
    public var localizedTitle: String

    enum CodingKeys: String, CodingKey {
        case userId
        case categoryUuid = "uuid"
        case title
        case languageId
        case localizedTitle
    }
}
```

I created an SQLite table with the key ```categoryUuid```

```
            do {
                try db.create(table: "book") { bookTable in
                    print("created: \(bookTable)")
                    bookTable.column("categoryUuid", .text).primaryKey()
                    bookTable.column("title", .text)
                    bookTable.column("languageId", .text)
                    bookTable.column("localizedTitle", .text)
                    bookTable.column("userId", .integer).references("user", onDelete: .cascade)
                }
            }
            catch {
                print("error making book table: \(error)")
            }
```

I extended the Book struct to contain an ```enum Columns```

```
extension Book {
    enum Columns {
        static let userId = Column("userId")
        static let categoryUuid = Column("categoryUuid")
        static let title = Column("title")
        static let languageId = Column("languageId")
        static let localizedTitle = Column("localizedTitle")
    }
}
```

I adopted RowConvertible:

```
extension Book: RowConvertible { }
```

I override didInsert:

```
extension Book: MutablePersistable {
    public static let databaseTableName = "book"
    public mutating func didInsert(with rowID: String, for column: String?) {
        categoryUuid = rowID
    }
}
```

Using  a Moya Target, I mapped the incoming JSON to a BookResponse(which contains a Book array)

```
        return self.kjvrvgNetworking.rx.request(.books(languageId: L10n.shared.language))
        .map { response -> BookResponse in try! response.map(BookResponse.self) }
            .flatMap { bookResponse -> Single<[Book]> in Single.just(bookResponse.result) 
            .flatMap { [unowned self] in self.replacePersistedBooks($0) }

```

Upon insertion(replacePersistedBooks()), I get the SQLite error:

```
2018-02-05 09:20:28.662544-0500 All Scripture[47115:782639] [logging] table book has no column named uuid
SQLite error 1 with statement `INSERT INTO "book" ("title", "userId", "uuid", "languageId", "localizedTitle") VALUES (?,?,?,?,?)`: table book has no column named uuid
Check user products failed with error: SQLite error 1 with statement `INSERT INTO "book" ("title", "userId", "uuid", "languageId", "localizedTitle") VALUES (?,?,?,?,?)`: table book has no column named uuid
```

## What did you expect to happen?

I expected GRDB to insert a row using a value named ```categoryUuid``` and NOT ```uuid```

## What happened instead?

GRDB inserted a row using a value named ```uuid``` and NOT ```categoryUuid```

## Environment

**GRDB flavor(s):GRDB.swift, RxGRDB
**GRDB version: see below
```
Using GRDB.swift (2.4.1)
Using RxGRDB (0.7.0)
```

**Installation method: CocoaPods
**Xcode version:9.2
**Swift version:4
**Platform(s) running GRDB:iOS
**macOS version running Xcode: High Sierra

## Demo Project

> Please link to or upload a project we can download that reproduces the issue.

**Comment by groue** [comment]
I'm currently on vacations, and won't be able to look at this issue until a couple of weeks. Would you mind looking at the problem in a precise fashion, and even maybe submitting a pull request (assuming your analysis of the situation is correct without the shadow of a doubt)?

**Comment by mazz** [comment]
I'm working on a small project to demo the bug. It may have to do with Moya+Rx(but I am not sure). I am using Moya+Rx and I will try and repro the issue using Moya but NO Rx.

**Comment by groue** [comment]
@mazz, what I'm really interested into is a fix. Codable support is in a single file. Tell me if you have difficulties finding the relevant lines.

**Comment by Kirow** [comment]
@mazz , there is no issue here.

Your CodingKeys says: Map external value (json or GRDB) under **"uuid"** into **categoryUuid** and vice versa. 
If you want it to work the way you described - you need to override Codable & Decodable initializers to add you custom logic.
for example:
encoding always into categoryUuid (in case if you will encode values only into database)
decoding - first try to get value from categoryUuid , if failed - from uuid. or vice versa

but for me - best solution is simply to rename categoryUuid to uuid. In this case you will not need to write your CodingKeys enum. Protocol will work out of box.

**Comment by mazz** [comment]
@Kirow ok I will override ```init(from decoder: Decoder)``` and see if that fixes it.

The reason I need to map it to ```categoryUuid``` is because I am using it as a foreign key for a table that already has a ```uuid``` primary key. Is there any other way around that?

**Comment by mazz** [comment]
@Kirow after implementing ```nit(from decoder: Decoder)``` like:
```swift
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.userId = try? container.decode(Int64.self, forKey: .userId)
        self.categoryUuid = try! container.decode(String.self, forKey: .categoryUuid)
        self.title = try! container.decode(String.self, forKey: .title)
        self.languageId = try! container.decode(String.self, forKey: .languageId)
        self.localizedTitle = try! container.decode(String.self, forKey: .localizedTitle)
    }
```
I am still getting the error ```Check user products failed with error: SQLite error 1 with statement `INSERT INTO "book" ("title", "userId", "uuid", "languageId", "localizedTitle") VALUES (?,?,?,?,?)`: table book has no column named uuid```

The field is definitely encoded as ```categoryUuid```:

<img width="1152" alt="screen shot 2018-02-08 at 10 53 43 pm" src="https://user-images.githubusercontent.com/808934/36011143-6fdc6d72-0d23-11e8-94d1-9b3c75f919f6.png">

when I step over ```try storeBook.insert(db)```

Deep inside I can see that GRDB 'sees' the field as ```categoryUuid```:

<img width="1149" alt="screen shot 2018-02-08 at 10 50 58 pm" src="https://user-images.githubusercontent.com/808934/36011173-a33f25b0-0d23-11e8-9ff5-bccfc45584c1.png">

And I define the table with ```categoryUuid```:
```swift
            do {
                try db.create(table: "book") { bookTable in
                    print("created: \(bookTable)")
                    bookTable.column("categoryUuid", .text).primaryKey()
                    bookTable.column("title", .text)
                    bookTable.column("languageId", .text)
                    bookTable.column("localizedTitle", .text)
                    bookTable.column("userId", .integer).references("user", onDelete: .cascade)
                }
            }
            catch {
                print("error making book table: \(error)")
            }
```

Yet I still get the insertion error. Not sure what else is wrong..

**Comment by Kirow** [comment]
@mazz , I were talking about such kind of changes

```swift
public struct Book: Codable {
    var userId: Int64?
    public var categoryUuid: String
    public var title: String
    public var languageId: String
    public var localizedTitle: String
    
    enum CodingKeys: String, CodingKey {
        case userId
        case categoryUuid, uuid
        case title
        case languageId
        case localizedTitle
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(categoryUuid, forKey: .categoryUuid)
        try container.encode(title, forKey: .title)
        try container.encode(languageId, forKey: .languageId)
        try container.encode(localizedTitle, forKey: .localizedTitle)
    }
    
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        
        self.userId = try values.decode(Int64?.self, forKey: .userId)
// take categoryUuid, if not exist then take uuid (at least one of them must present)
        self.categoryUuid = try values.decodeIfPresent(String.self, forKey: .categoryUuid)
            ?? (try values.decode(String.self, forKey: .uuid))
        self.title = try values.decode(String.self, forKey: .title)
        self.languageId = try values.decode(String.self, forKey: .languageId)
        self.localizedTitle = try values.decode(String.self, forKey: .localizedTitle)
    }
}
```

test:
```swift
var jsonInput = """
{
    "userId": 123,
    "uuid": "ABC-EFGH-QWERTY",
    "title": "Title",
    "languageId": "123",
    "localizedTitle": "Localized Title"
}
"""

let jsonInputData = jsonInput.data(using: .utf8)!

let encoder = JSONEncoder()
let decoder = JSONDecoder()

let decodedFromJson = try! decoder.decode(Book.self, from: jsonInputData) //json.uuid goes to Book.categoryUuid
let encodedFromDecodedJson = try! encoder.encode(decodedFromJson) //Book.categoryUuid goes to json.categoryUuid
let encodedJsonString = String(data: encodedFromDecodedJson, encoding: .utf8)!

let decodedFromEncoded = try! decoder.decode(Book.self, from: encodedFromDecodedData) //decodedFromEncoded same as decodedFromJson
```

**Comment by groue** [comment]
Folks, if the goal is just to store the record in the database with customized column names, then why do you bother fighting with Codable? Drop this "convenience" protocol which is all but convenient when it goes in the way, and directly implement RowConvertible and Persistable protocols. It will be way simpler, way faster, and you'll be able to move on to some more interesting task.

**Comment by mazz** [comment]
@groue while I get your point, legacy codebases may have already tightly integrated Codable. For instance, our app already used Codable but want to add an 'offline mode' and so ripping-out Codable for other protocols isn't so practical. Unless I am getting you wrong ..

**Comment by mazz** [comment]
@Kirow thanks for your help. Your contribution made a big difference.

**Comment by groue** [comment]
@mazz It's still unclear to me if anything is wrong with GRDB or not. Could you clarify this point, if you have a few minutes?

**Comment by mazz** [comment]
@groue there is no issue with GRDB. The issue was that I was working under the very false assumption that the default Codable behaviour that would correctly function to and from JSON would equally work as well as when encoding to and from the database. This of course can't work. So custom encoding logic had to be added to the struct. @Kirow please add anything or correct me if necessary.

**Comment by Cooparr** [comment]
> Folks, if the goal is just to store the record in the database with customized column names

@groue To clarify as that is currently my goal, for example, if I'm receiving JSON data from an API where the property names aren't exactly helpful, like this: 
```
{
    "fN": "John",
    "lN": "Doe,
}
```

And I would like to store that data in the database while conforming to Codable, with the column names `firstName` & `lastName`, is the only way to do that by using a custom `encode(to encoder: Encoder)`  & `init(from decoder: Decoder)` as @Kirow mentioned above? 

Thanks in advance

**Comment by groue** [comment]
Hello @Cooparr,

Yes, only custom implementations of `Decodable`/`Encodable` requirements can deal with distinct coding keys for JSON and the database (or any other coding source/destination). See [The userInfo Dictionary](https://github.com/groue/GRDB.swift/blob/master/README.md#the-userinfo-dictionary) for more information.

Alternatively, you can just not rely on `Codable` for the database.

This is abundantly documented:

- [FetchableRecord Protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#fetchablerecord-protocol)
- [PersistableRecord Protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol)

For example:

```swift
struct Player {
    var id: String
    var name: String
    var score: Int?
}

extension Player {
    enum Columns: String, ColumnExpression {
        // Actual database column names
        var id, name, score
    }
}

extension Player: FetchableRecord {
    init(row: Row) {
        id = row[Columns.id]
        name = row[Columns.name]
        score = row[Columns.score]
    }
}

extension Player: PersistableRecord {
    func encode(to container: inout PersistenceContainer {
        container[Columns.id] = id
        container[Columns.name] = name
        container[Columns.score] = score
    }
}
```

**Comment by Cooparr** [comment]
Apologies for my late reply @groue
Thank you for clarifying that for me, was exactly what I needed 😄
