### ISSUE TITLE
0.52.0 Swift Errors

### ISSUE THREAD

**Issue by Spacelapp** [groue/GRDB.swift#30]
Hello,

thx for this great tool :+1: 

But I found some compiling errors... 

![bildschirmfoto 2016-03-22 um 00 21 32](https://cloud.githubusercontent.com/assets/8951663/13937283/0b146efe-efc4-11e5-8cba-3c29ad97955f.png)

![bildschirmfoto 2016-03-22 um 00 20 19](https://cloud.githubusercontent.com/assets/8951663/13937277/000fd462-efc4-11e5-97c1-64045ba73088.png)

**Comment by Spacelapp** [comment]
Okay, seems to be a problem if using the old swift version

**Comment by groue** [comment]
OK, you fixed it yourself!
