### ISSUE TITLE
Please create Gitter community channel for GRDB

### ISSUE THREAD

**Issue by rlaferla** [groue/GRDB.swift#300]
SQLite.swift has one.  GRDB should have one.  It would reduce non-bug reports in Issues and can be better for certain discussions than StackOverflow.

https://gitter.im

**Comment by groue** [comment]
Hello @rlaferla 

I'm not familiar with Gitter. How does it work? What are the benefits? How much involvement is required to make it live in long term?

**Comment by Kirow** [comment]
@groue ,

It is chat application (like Slack or IRC). You can create official channel for your open source project and users will have place where to ask 'how to' questions. This does not mean that you will need to answer all of them, we can do it ourselves. But we need place where to do it. I guess GitHub Issues not a place for such kind of questions / conversations.

You've probably seen this before 
![Gitter](https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667)

**Comment by groue** [comment]
What's wrong with GitHub issues? I like *a lot* that they are asynchronous, focused, searchable, taggable, linkable, formatted, editable, and I certainly forget other advantages. You have to make a much stronger point for gitter. For example, an **actual issue that you have with the current state of affairs**.  We may then try to address it specifically.

**Comment by groue** [comment]
@rlaferla, @Kirow, any argument to support your request, or anything that bother you today? If not, this issue will die due to lack of anything to chew on, you know!

**Comment by groue** [comment]
OK guys! I'm closing this issue. Please dare opening a new one when you want to discuss of an actual problem you think needs addressing.
