### ISSUE TITLE
Question: Receiver for class message is a forward declaration

### ISSUE THREAD

**Issue by mohamedgalalcs** [groue/GRDB.swift#304]
My project contains both Objective c classes and Swift classes, I made a class "Message" in swift which inherits from Record and I made all the required methods and it build successfully and when I call any of it's methods from my swift classes everything works fine, but when I call it from objective c class this error appear and the app reject the build process "Receiver for class message is a forward declaration" even when I put @class Message. Would you please help in this

**Comment by groue** [comment]
Hello @mohamedgalalcs

Please refer to Apple documentation regarding the way to share both Swift and Objective-C in the same project:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Also, be conscious that being accessible from Objective-C is *not* a target of GRDB, which is a Swift library. Yet there is no active will to prevent it, and there even is a FMDB-compatible later over GRDB: [GRDBObjC](https://github.com/groue/GRDBObjc).

If you have any findings, don't hesitate sharing them here!

**Comment by mohamedgalalcs** [comment]
Thanks for your response, I already have lot of classes in my project written in objective c & lot of classes written in swift and they are woking fine together.

The point is I changed all of my model classes which are written in obj-c and uses FMDB and write them from scratch in Swift with GRDB, so the whole model layer now is swift classes with GRDB, but the problem appear when I try to access these new models in my obj-c controller classes, the app isn’t able to find these model classes in “productName-swift.h” file and that’s because all of my new model classes are inherited from “record” class not “NSObject” class, so this error appear.

I think now you know my problem in details, whould you help me how to fix this situation? I need to use the Swift GRDB model classes in my Objective c controllers.

Thanks very much for your great efforts and helping, really appreciated.

**Comment by groue** [comment]
@mohamedgalalcs I'm not sure at all that the Record class can be used from Objective-C. In fact I'm pretty sure it can't. Or if it can, in a terribly hampered fashion. You may well have picked the wrong horse. GRDB is a *Swift* library.

I suggest you have another look at FMDB. Maybe try FCModel.
