### ISSUE TITLE
How to store one model into different tables ?

### ISSUE THREAD

**Issue by daasan123** [groue/GRDB.swift#308]
> If I have a model called 'VideoModel'，how do I store it into different tables but not subclass it ? Because I have to distinguish it from 'Liked' and 'History'. What I had saw is that one class is binded to just one table.

```
override class var databaseTableName: String {
        return "HistoryVideoTable"
    }
```

**Comment by groue** [comment]
@daasan123, you still haven't used the issue template, despite my [explicit request](https://github.com/groue/GRDB.swift/issues/307). That's not correct. And, as expected, it is still impossible to answer your question.

Filling the template will have you start working on a solution to your issue. Before having "one model store into different tables", whatever it means (??????????), write naive code that does what you need. Only after that, you'll be able to express your question in a better way. You will be able to show something that's wrong, and to show how it should have been.
