### ISSUE TITLE
Use of undeclared type 'DatabaseSnapshot'

### ISSUE THREAD

**Issue by Joseph310** [groue/GRDB.swift#310]
Hi,

I updated my Cocoapods and GRDB was also updated to 2.9.0.

Now I can no longer compile my project (min. requirement iOS 9.3).
I get the error: `Use of undeclared type 'DatabaseSnapshot'`
It jumps to line 653 in Pods > GRDB.swift > DatabasePool.swift. 

I cleaned my build folder, but this did not solve the issue. 

What can I do?

Thanks

**Comment by groue** [comment]
Hello @Joseph310. I don't know. This looks like an Xcode-CocoaPods glitch. I did personally the upgrade on one of my apps today and did not experience that error.

**Comment by groue** [comment]
We'll investigate this issue further if more users start complaining.

**Comment by groue** [comment]
Last comment: you did ignore the issue template. We don't even know which software version you are using, and there's no way to get any context in which this issue may arise. Next time you open an issue in a repository that provides an issue template, please take the time to fill it (if you want repository maintainers to take the time to investigate your issue).
