### ISSUE TITLE
Upsert support?

### ISSUE THREAD

**Issue by rlaferla** [groue/GRDB.swift#315]
I don't see any examples of an upsert (update record if it exists, insert if it doesn't).  It would be great to see an example in the README assuming the framework even supports upserts.

**Comment by groue** [comment]
Hello @rlaferla 

SQLite does not support UPSERT. It has [INSERT OR REPLACE](https://www.sqlite.org/lang_conflict.html), though, which is similar.

The examples you are looking for are in the [Conflict Resolution](https://github.com/groue/GRDB.swift/blob/master/README.md#conflict-resolution) chapter of GRDB documentation.

**Comment by groue** [comment]
Oh, and there is also the save() [persistence method](https://github.com/groue/GRDB.swift/blob/master/README.md#persistence-methods), which performs an update or an insert.
