### ISSUE TITLE
flatMap is deprecated warnings

### ISSUE THREAD

**Issue by Johnne25** [groue/GRDB.swift#316]
In the latest Xcode there are several compile warnings.  Can you fix these please.

/Pods/GRDB.swift/GRDB/Core/Support/Foundation/DatabaseDateComponents.swift:108:41: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value

**Comment by groue** [comment]
Hello @Johnne25 

Stable versions of GRDB (latest is v2.9.0) target stable versions of Xcode (latest is Xcode 9.2). You are using a beta version of Xcode.
