### ISSUE TITLE
Make my own pods and add GRDB.swift dependency occurs an error

### ISSUE THREAD

**Issue by NicolasKim** [groue/GRDB.swift#317]
I'm making a pod and I add GRDB.swift dependency
but when I 'pod trunk push' my pod ,there occurs an error.
It's weird,Can you tell how should I fix this problem?

## Environment

**GRDB version:2.9.0
**Installation method:CocoaPods
**Xcode version:9.2
**Swift version:4
**Platform(s) running GRDB:iOS
**macOS version running Xcode: 10.13.3

## Demo Project

https://github.com/NicolasKim/Roy.git  branch=>0.0.2

##Terminal console error

[!] Found podspec `Roy.podspec`
Updating spec repo `master`
Validating podspec
 -> Roy (0.0.2)
    - WARN  | source: Git sources should specify a tag.
    - WARN  | description: The description is shorter than the summary.
    - WARN  | url: The URL (https://github.com/jinqiucheng1006@live.cn/Roy) is not reachable.
    - ERROR | [Roy/Core,Roy/UI] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:163:45: error: 'openConnection' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:194:25: note: 'openConnection' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:339:13: error: 'busyCallback' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:153:17: note: 'busyCallback' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:345:39: error: 'busyCallback' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:380:17: error: 'isClosed' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:158:17: note: 'isClosed' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:386:9: error: 'isClosed' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:475:9: error: 'functions' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:155:17: note: 'functions' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:481:9: error: 'functions' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:498:9: error: 'collations' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:156:17: note: 'collations' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:517:9: error: 'collations' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseFunction.swift:316:33: error: 'nArg' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseFunction.swift:13:17: note: 'nArg' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseFunction.swift:322:44: error: 'nArg' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:342:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:15:17: note: 'readerPool' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:146:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:149:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:162:14: error: 'application' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:21:22: note: 'application' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:169:33: error: 'application' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:244:20: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:288:20: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:328:24: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:375:9: error: 'functions' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:17:17: note: 'functions' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:377:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:384:9: error: 'functions' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:386:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:403:9: error: 'collations' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:18:17: note: 'collations' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:405:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:412:9: error: 'collations' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:414:9: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:444:20: error: 'writer' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:13:17: note: 'writer' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:506:20: error: 'writer' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:582:9: error: 'writer' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:592:13: error: 'readerPool' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:654:72: error: 'writer' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:655:25: error: 'setupDatabase' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabasePool.swift:100:18: note: 'setupDatabase' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:87:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:9:17: note: 'serializedDatabase' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:143:14: error: 'application' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:11:22: note: 'application' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:150:33: error: 'application' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:241:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:311:9: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseQueue.swift:341:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseRegion.swift:224:34: error: 'tableRegions' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseRegion.swift:43:17: note: 'tableRegions' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseRegion.swift:165:34: error: 'tableRegions' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseRegion.swift:199:21: error: 'tableRegions' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:64:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:8:17: note: 'serializedDatabase' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:71:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:78:20: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:96:9: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:101:9: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:116:9: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Core/DatabaseSnapshot.swift:121:9: error: 'serializedDatabase' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Record/FetchedRecordsController.swift:510:13: error: argument 'itemsAreIdenticalFactory' must precede argument 'queue'
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Record/FetchedRecordsController.swift:917:88: error: 'itemsAreIdentical' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/Record/FetchedRecordsController.swift:373:17: note: 'itemsAreIdentical' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:29:32: error: 'qualifier' is inaccessible due to 'private' protection level
    - NOTE  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:18:17: note: 'qualifier' declared here
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:39:15: error: 'qualifier' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:55:15: error: 'qualifier' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:69:17: error: 'qualifier' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:74:20: error: 'qualifier' is inaccessible due to 'private' protection level
    - ERROR | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:82:31: error: 'qualifier' is inaccessible due to 'private' protection level
    - WARN  | [Roy/Core,Roy/UI] xcodebuild:  GRDB.swift/GRDB/QueryInterface/SQLSelectable+QueryInterface.swift:85:16: warning: no calls to throwing functions occur within 'try' expression

**Comment by sobri909** [comment]
Can you show us the podspec you're trying? 

Here's an example of a podspec with GRDB dependency: https://github.com/sobri909/ArcKit/blob/master/ArcKit.podspec#L23

**Comment by groue** [comment]
Hello @NicolasKim 

I've already seen those "inaccessible due to 'private' protection level" errors. They occur when the Swift compiler is in "Swift 3" mode, when it should be in "Swift 4" mode.

Your issue will be solved after you have instructed CocoaPods to use Swift 4.

Quoting their blog post [CocoaPods 1.1.0 - Xcode 8 support, improved support for new Swift versions, extensions, frameworks, and more](http://blog.cocoapods.org/CocoaPods-1.1.0/):

> - CocoaPods defaults to Swift 3.0, if your pod uses Swift.
> - It uses the setting from your `.swift-version` file if present (inspired by swiftenv).
> - The `--swift-version` flag can be used to specify a version of Swift to use. This overrides the version set in the .swift-version file.

I did not spend much time looking for more precise documentation. I personally use a `.swift-version` file, whose content is `4.0`, and I'm happy.

Finally, reading your [podspec](https://github.com/NicolasKim/Roy/blob/0.0.2/Roy.podspec), I see:

```ruby
cs.dependency 'GRDB.swift'
```

This is dangerous, because it does not specify which version of GRDB your pod is compatible with.

It should read instead:

```ruby
sp.dependency 'GRDB.swift', '~> 2.9'
```

This will avoid the release of GRDB 3.0 to break your pod.

**Comment by sobri909** [comment]
Ah, sorry, I see your podspec in the 0.0.2 branch now. And yeah, as @groue says, it looks like it's a Swift version error. You've got the correct `SWIFT_VERSION` in your podspec, but your `.swift-version` file says `3.0`, which will be the problem.

**Comment by NicolasKim** [comment]
@groue  It works!!    thank you~

**Comment by groue** [comment]
Happy GRDB, @NicolasKim! And thanks @sobri909 for your support!
