### ISSUE TITLE
unique on multiple columns?

### ISSUE THREAD

**Issue by FormioCour** [groue/GRDB.swift#318]
How to implement this like
[sqlite-table-constraint-unique-on-multiple-columns](https://stackoverflow.com/questions/2701877/sqlite-table-constraint-unique-on-multiple-columns)

**Comment by groue** [comment]
```swift
try db.create(table: "t") { t in
    t.column("a")
    t.column("b")
    t.uniqueKey(["a", "b"])
}
```

Check the [documentation about table creation](https://github.com/groue/GRDB.swift/blob/master/README.md#create-tables) for more information.
