### ISSUE TITLE
"Fatal error: Object was retained too many times"

### ISSUE THREAD

**Issue by dproton** [groue/GRDB.swift#325]
Thank you for the great GRBD.swift. 
I tried these code in the example project and got error `Fatal error: Object was retained too many times`. Do you have any ideas about it ?

  ```
  @IBAction func stressTest() {
//        setEditing(false, animated: true)
            DispatchQueue.global().async {
                autoreleasepool(invoking: {
                    try! dbQueue.inTransaction { db in
                        // Insert a person
                        for i in 0..<80000 {
                            let person = Person(name: Person.randomName(), score: Person.randomScore())
                            print(i)
                            try person.insert(db)
                        }
                        return .commit
                    }
                })
            }
    }
```

<img width="1432" alt="screen shot 2018-03-20 at 10 13 49" src="https://user-images.githubusercontent.com/8925426/37634173-06db8168-2c28-11e8-941c-460714befb06.png">

GRDB version: v2.9.0
Installation method:** CocoaPods
Xcode version: 9.2
Swift version: 4.0

**Comment by groue** [comment]
Hello @dproton

I could not reproduce your fatal error, but I could reproduce the fact that FetchedRecordsController takes a *long* time computing its diff after your sample code has inserted 80000 records. And it consumes a *lot* of memory as well.

Maybe your error is a side-effect of this heavy computation.

Now let me quote the [documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#the-changes-notifications):

> ⚠️ **Warning**: notification of individual record changes (the onChange callback) has FetchedRecordsController use a diffing algorithm that has a high complexity, a high memory consumption, and is thus not suited for large result sets. One hundred rows is probably OK, but one thousand is probably not. If your application experiences problems with large lists, see Issue #263 for more information.

Inserting 80000 items is way beyond the (fuzzy) documented limit.

If you want to use FetchedRecordsController to track changes in big tables, you have two options:

1. Don't use the `onChange` callback which can animate tableview rows, and instead only use the `didChange` callback in which you can call tableView.reloadData(). This avoid triggering the slow diff algorithm.
2. Submit a pull request with an enhanced riffing technique, or sponsor GRDB (as explained in #263).

**Comment by dproton** [comment]
Thank for your support !
