### ISSUE TITLE
ISLIKE in SQLite?

### ISSUE THREAD

**Issue by rawandahmad698** [groue/GRDB.swift#327]
How do we find a row by `LIKE` operator, more specifically how can we find rows that are close or has atleast a word like the query?

**Comment by groue** [comment]
Hello @rawandahmad698 

> How do we find a row by LIKE operator

You'll find how to use the LIKE operator with GRDB in the [SQL operators](https://github.com/groue/GRDB.swift/blob/master/README.md#sql-operators) documentation chapter:

```swift
// SELECT * FROM players WHERE (email LIKE '%@example.com')
Player.filter(emailColumn.like("%@example.com"))
```

> more specifically how can we find rows that are close or has atleast a word like the query?

You may find your answer in the [SQLite documentation](https://www.sqlite.org/lang_expr.html#like).
