### ISSUE TITLE
How to insert list in Transaction?

### ISSUE THREAD

**Issue by FormioCour** [groue/GRDB.swift#338]
## What did you do?

> How to insert list in Transaction?

## Environment

**GRDB flavor(s): GRDB** 
**GRDB version: 2.10.0**
**Xcode version: Version 9.3 (9E145)**
**Swift version: 4**
**Platform(s) running GRDB: iOS** 
**macOS version running Xcode: 10.13.4**

The problem is under the code comments.

```swift

    class Item: Record {
        var id: Int64?
    }
    
    class ItemCover: Record {
        var id: Int64?
        var itemId: Int64 = 0
        init(itemId: Int64) {
            self.itemId = itemId
            super.init()
        }
    }
    
    func saveItemList(_ itemList: [Item]) {
        do {
            try dbQueue.inTransaction{ db in
                
                for item in itemList {
                    let itemRecord = item
                    
                    try itemRecord.insert(db)
                    
                    // Insert Cover List for Item
                    // Can't find itemId, itemRecord.id always be nil
                    if let itemId = itemRecord.id {
                        let itemCoverRecord = ItemCover(itemId: itemId)
                        try itemCoverRecord.insert(db)
                    }
                }
                return .commit
            }
        }catch {
            debugPrint(error)
        }
    }

```

**Comment by groue** [comment]
Hello @FormioCour

https://github.com/groue/GRDB.swift/blob/master/README.md#records

**Comment by groue** [comment]
Looking again at the doc, I can see how it has evolved into something complex where your question does not easily find its answer. I'll fix that. Meanwhile, look for the didInsert method.

**Comment by groue** [comment]
The new documentation chapter [Examples of Record Definitions](https://github.com/groue/GRDB.swift/blob/GRDB3/README.md#examples-of-record-definitions) will ship shortly. Click the link for a quick glance at some standard ways to declare record types.

**Comment by FormioCour** [comment]
solved it.  
My carelessness. Sorry
