### ISSUE TITLE
confusing generics placeholder

### ISSUE THREAD

**Issue by thommw** [groue/GRDB.swift#344]
## What did you do?

I tried to implement polymorphic records. I think this is a useful idea. According to you, you implemented it yourself and then removed it again. I don't think the reason for that was not that nobody wanted it. Everything compiles fine and I start the iOS tests. 

## What did you expect to happen?

I expected some failed tests but no crashes.

## What happened instead?

When running the tests I get a SIGABRT in FetchedRecordsController in the swift_rt_swift_dynamicCast. 

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** GRDB.master
**Installation method:** manual
**Xcode version:** 9.3 (9E145)
**Swift version:** 4.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.4

## Demo Project

> Please link to or upload a project we can download that reproduces the issue.

In `FetchedRecordsController`, `Row` and `RowConvertible` you are using the identifier `Record` as a generics placeholder while it is also a class name. The compiler seems to get confused which one to use. At least the editor is. I have not yet confirmed that this is the cause of the SIGABRT. If nothing else it would be a good idea to make this unambiguous.

**Comment by groue** [comment]
Thanks for the effort, @thommw. It's much appreciated.

> When running the tests I get a SIGABRT in FetchedRecordsController in the swift_rt_swift_dynamicCast

All right, but we still don't know what change you have performed. Nobody has any way to dig into your subject and experience your issue. It's still very very cloudy.

> In FetchedRecordsController, Row and RowConvertible you are using the identifier Record as a generics placeholder while it is also a class name. The compiler seems to get confused which one to use. At least the editor is. I have not yet confirmed that this is the cause of the SIGABRT.

That's an hypothesis. I'd like that you confirm it before you ask for my free time. It looks like you're able to do this preliminary research. For example, did you replace identifiers, and see if this fixes the problem? If so, is it a problem with GRDB (hence this issue), or a bug in the Swift compiler (bugs in the Swift compiler go to http://bugs.swift.org, not here) ? If this is a bug in the Swift compiler, does GRDB need to be updated with a workaround?

> If nothing else it would be a good idea to make this unambiguous.

Thanks for your opinion, duly recorded.

I'll keep this issue opened a few days, until you gather your thoughts and eventual needs.

For the record: the topic discussed here was first introduced in #341, which already has a valid answer at https://github.com/groue/GRDB.swift/issues/341#issuecomment-384292650.

**Comment by thommw** [comment]
You're welcome!
