### ISSUE TITLE
access sqlite file with .db extension 

### ISSUE THREAD

**Issue by alaaosman20** [groue/GRDB.swift#345]
i have an sqlite file in the document directory in .db extension and i'm having trouble to connect to the database, i'm getting  "FILE NOT AVAILABLE" error, is it because the extension of the database not .sqlite, if yes how we can connect to the sqlite database with .db extension in GRDB.swift.
Thank you,

**Comment by groue** [comment]
Hellon @alaaosman20. If you want help, please fill in the issue template, and provide as much detail as possible.
