### ISSUE TITLE
connect to sqlite file with .db extension

### ISSUE THREAD

**Issue by alaaosman20** [groue/GRDB.swift#346]
## What did you do?

> i wanted to connect to  the sqlite db file saved in document directory (the file is in .db extension)

## What did you expect to happen?

> i expected to connect to the db

## What happened instead?

>i got the this error: FILE NOT AVAILABLE

## Environment

**GRDB flavor(s):(GRDB)** 
**GRDB version:2.10** 
**Installation method:CocoaPods** 
**Xcode version:9.3**
**Swift version: 4**
**Platform(s) running GRDB:ios**
**macOS version running Xcode:10.13**

the database file is saved in: documents/MyDatabase/Database.db 

this is my code:
```
let documentDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first as URL!
    
    let datatbaseDirectory =  documentDirectory.appendingPathComponent("MyDatabase", isDirectory: true)
       let finalDirectory = datatbaseDirectory.appendingPathComponent("Database.db", isDirectory: false).path

let dbQueue =  try! DatabaseQueue(path: finalDirectory)
```

**Comment by groue** [comment]
Hello @alaaosman20.

Thanks for filling out the form. Now please provide the **full error information**. I'm sure there's much more to say than just "I get FILE NOT AVAILABLE". Copy/paste what you see, even if you don't understand it: it is likely to contain crucial information.

**Comment by alaaosman20** [comment]
i found the error it wasn't because of the extension it was because the try not handled, i fixed it now and it worked fine.
i'm very sorry for the confusion, but i'm still new to Ios.
Thank you very much for your support and for this great library.

**Comment by groue** [comment]
Thanks! Happy GRDB, @alaaosman20 👍
