### ISSUE TITLE
Record factory versus RowConvertible 

### ISSUE THREAD

**Issue by sobri909** [groue/GRDB.swift#349]
Lately I've been experimenting with `FetchedRecordsController` for some query result change observing I need, and it reminded me of your recent mention, in reply to someone else's issue, of the historical decision to go with a protocol instead of factory for `RowConvertible`.

Due to my lib's uniquing requirement I can't use `RowConvertible`, which means I can't use a large portion of GRDB's features. (My record instances have to come from a store factory, to ensure uniqueness). 

Basically this: 

```swift
let record = Record(row: row)
```

Versus this: 

```swift
let record = store.record(for: row)
```

The conclusion from my recent `FetchedRecordsController` experiments is that I'm better off subclassing `TransactionObserver` instead (which I'm doing now). Which is all good and fine. That all makes sense. But it reminded me again that `RowConvertible` is either blocking me entirely from certain GRDB functionality, or making certain functionality less efficient than I require, due to unnecessary copies.

In the case of my `FetchedRecordsController` experiments, I had to make a [RowCopy](https://github.com/sobri909/LocoKit/blob/develop/LocoKit/LocalStore/RowCopy.swift) wrapper class, which was awkwardly redundant and inefficient because the controller internally also has its own `Item<Record>` wrapper, which in turn also holds onto a raw row copy. 

I'm basically just throwing out some random thoughts here. I haven't played this idea all the way through yet. But on the face of it, it doesn't seem like instantiating records from a factory would excessively harm complexity. And it would seemingly open the door to uniquing, like what I'm doing in LocoKit. Unless I'm missing some fundamental flaw in the idea (which I usually am). 

 Thoughts?

**Comment by groue** [comment]
I'm currently in vacations, and won't be able to look into your question until a couple of days.

Yet I know that FetchedRecordsController is unfortunately coupled to RowConvertible. I didn't make the same mistake when designing RxGRDB. This one handles requests of anything (with built-in support for records, values, and raw rows.)

I'd thus look in a way to remove RowConvertible dependency from FetchedRecordsController, bring built-in support for RowConvertible through extensions, and allow FRC to work with an application-defined protocol that provides a factory method instead of an initializer.

I don't know if this sounds clear to you. If it does, and if you wish to experiment, I suggest you start from the GRDB3 branch.

**Comment by sobri909** [comment]
> Yet I know that FetchedRecordsController is unfortunately coupled to RowConvertible.

Oh that's no problem at all! I think that decision suits the current API. 

`TransactionObserver` is what I should have been using in the first place. It suits my needs much more directly. I just needed to go through the process of understanding `FetchedRecordsController` before I could realise that 😉

Now that I've got familiar with `TransactionObserver`, I don't see any future need for `FetchedRecordsController`. So changes to that class won't be any help to me personally.

My line of thinking here is more low level in GRDB, about replacing `RowConvertible` with a factory method in general, not just in one specific case. I'm talking about a more fundamental architectural question.

> I suggest you start from the GRDB3 branch.

I switched to that yesterday 😊 But quickly ran into some memory leaks and bad access crashes. And I couldn't be certain whether the leaks and crashes were due to my own poorly tested beta code, or in GRDB3, so I've had to switch back to v2 for now. (I'm still not certain where the fault lies there, due to fast moving changes in my own code. But if I do identify anything specific, I'll file a report. I'll switch back to GRDB3 again in the next few days). 

Anyway, enjoy your vacation! 😄 Definitely don't rush to reply to anything on my account! I only just got back from a two week beach holiday myself. So refreshing! I must do it more often.

If I could, I'd buy you a beer! Cheers 🍺🍺 Relax and enjoy 😉

**Comment by groue** [comment]
All right @sobri909, let's get clear on that. And you're right, @thommw deserves a better answer. When I'm back, I'll know why there is no factory method today, and whether we can introduce them or not.

**Comment by sobri909** [comment]
> When I'm back, I'll know why there is no factory method today, and whether we can introduce them or not.

My guess is that even though it superficially looks easy, it could have nasty repercussions over the whole library, both expected and unexpected. So it's one of those changes which first looks like "sure, we could do that", but then it's more like "oh wait, this will hurt a lot" 😉

I think the big question is how much hurt would it cause? Would it break everything, in unexpected ways? Or would it only require a few minor tweaks in some edge cases?

My hunch is that it would be simplest to add a static method to `RowConvertible` something like `instance(for: Row)`, which has a default implementation that just calls the existing `init(row: Row)`. 

GRDB could use the `instance(for:)` method internally, anywhere it currently uses `init(row:)`. That would provide backward compat with existing consumer code, as a first step.

But that's where I think the easy part would end and the hurt would start. It's one of those changes that looks simple, but could have a long list of unexpected side effects. And I don't know the GRDB internals well enough to have any idea how big that hurt would be...

**Comment by groue** [comment]
It's simple: I'll just replace the initializer with the factory method, and see where it goes ;-)

**Comment by sobri909** [comment]
Haha. Yeah, there's always the "just try it, and see what breaks" approach 😂

**Comment by groue** [comment]
So far GRDB compiles fine with a factory method:

```swift
protocol FetchableRecord {
    static func fromRow(_ row: Row) -> Self
}
```

The [Record class](https://github.com/groue/GRDB.swift/blob/GRDB3/README.md#record-class) has kept its row initializer so that it can copy its "reference row" and [track its own modifications](https://github.com/groue/GRDB.swift/blob/GRDB3/README.md#record-comparison).

```swift
open class Record : FetchableRecord, TableRecord, PersistableRecord {
    init()
    required init(row: Row)
}
```

> Note: the Record class is very very very important because it helps users who expect to subclass a root record type to find the entrance door they want and need. Most newbies and users who come from other ORMs subclass Record.

Now let's see how it looks in tests.

**Comment by sobri909** [comment]
> Note: the Record class is very very very important because it helps users who expect to subclass a root record type to find the entrance door they want and need. Most newbies and users who come from other ORMs subclass Record.

Yeah, that's what scares me.

Although as long as the default implementation just hands the job over to `init(row:)`, in theory it shouldn't do any harm to existing code.

**Comment by groue** [comment]
BTW, Swift 2 and Swift 4 are not at all the same beasts. The former limitations of Swift 2 may not apply any longer (GRDB was born on July 2015!) That's why it's hard to evaluate the consequences upfront: the initializer vs. factory method game does not run on the same ground at all!

> Although as long as the default implementation just hands the job over to init(row:), in theory it shouldn't do any harm to existing code.

Yep. I'd be OK with the same required initializer for Record as the one we used to have. Since it's likely that it would also be *expected* by Record users, everybody is happy.

**Comment by sobri909** [comment]
> The former limitations of Swift 2 may not apply any longer

I seem to remember some changes with the init cycle in the Swift 2 -> 3 transition. But I can't remember the details now.

**Comment by groue** [comment]
After a few second thoughts, I'm reluctant to make FetchableRecord a protocol that requires a factory method.

There are too many alternative fetching methods that may be needed by applications:

- Your application needs polymorphic row decoding (which means decoding some class or another depending on the values contained in a database row).
- Your application needs to decode rows with a context - which means that each decoded value should be initialized with some extra value that does not come from the database.
- Your application needs a record type that supports untrusted databases, and may fail at decoding database rows (throw an error when a row contains invalid values).

All those there needs have been requested by GRDB users. All of them are legit. But GRDB can't satisfy all of them with built-in support.

Instead, I now want to make it clear that GRDB can be extended for **customized row decoding**.

I will soon update README.md with related links, but right now a new playground has been added: https://github.com/groue/GRDB.swift/blob/GRDB3/Playgrounds/AlternateRowDecoder.playground/Contents.swift

This is my best answer so far to particular row decoding needs. And the most extensible as well.

@sobri909, @thommw, please tell me what you think?

**Comment by groue** [comment]
@fpillet, what do you think of the above linked playground?

**Comment by groue** [comment]
All right folks, I made up my mind: FetchableRecord will keep its plain and simple `init(row:)` initializer. Six reasons:

1. The initializer covers much more than 80% of application needs.
2. Introducing a factory method would break too much existing code, unless we introduce *another* record protocol (and complexify the API)
3. The initializer provides a nicer API to my subjective eye:

    ```swift
    struct Player {
        init(row: Row) {
            name = row["name"]
            score = row["score"]
        }
    }
    // vs.
    struct Player {
        static func decode(row: Row) -> Player {
            return Player
                name: row["name"],
                score: row["score"])
        }
    }
    ```

4. A factory method satisfies only **one of many** special row decoding needs:

    - Polymorphic decoding (this issue)
    - failable record decoding (#320)
    - decoding with context (https://github.com/groue/GRDB.swift/pull/313#issuecomment-386882401)
    - Known experimental needs (early versions of the Associations API would decode tuples from joined queries)
    - Other unknown needs
    
    It's impossible to cover all of these needs with a single protocol.
    
    Moreover, some of those needs are against long-term GRDB goals (failable record decoding, for example, would prevent optimizations such as late record decoding, used for example by FetchedRecordsController)

5. A row initializer is required by the Record class, and it is not bad to have a common row decoding method for all record types.

6. Generally speaking, I think that progressive disclosure is better serviced with a simple protocol that suits most needs, matches expectations of newcomers, and yet allows experts to extend the library when needed.

I thus added a new [Customized Decoding of Database Rows](https://github.com/groue/GRDB.swift/tree/GRDB3#customized-decoding-of-database-rows) documentation chapter, whose goal is to teach GRDB users that FetchableRecord is not sacred, and that you don't lose anything when you leave it because it is not a good fit for a particular need.

**Comment by sobri909** [comment]
Sounds reasonable to me.

I guessed the flow on to the rest of the API might get nasty and add too much extra complexity in layers that shouldn't be complex. It sounds like your experiments proved that to be the case.

I wonder if a better way to do it, at some much later time, might be through an optional higher level `PersistentStore` class, much like how I do it in LocoKit. Or probably more correctly named, a `ManagedContext`, to steal Core Data's terminology.

(My own PersistentStore in LocoKit is really a combination of both store and managed context. Which makes sense for LocoKit because there's only allowed to be one store and one context, both operating at essentially the same level, so the store/context separation isn't necessary there).

Anyway, that way it could be an additive and optional higher level layer which doesn't require changes to the base level protocols. An extra, separate feature, for SDK users who want a higher level layer between them and the database rows.

I know that's something you explicitly **do not** want to be part of GRDB. I've already read a few of your strong arguments against exactly that 😉 But I think if it's done as an optional decoupled layer on top, it could fit nicely as a sort of "semi managed GRDB", thus it wouldn't do any damage to GRDB's core principles nor require any/many changes to it to accommodate. 

Perhaps it could even be a separate project/repo, `ManagedGRDB`, or some such. To even more strongly ensure that it doesn't impact the core GRDB principles.

Though that does open up several cans of worms. One that I commonly run into with LocoKit is that there's no enforced requirement for me to interact with the database through my managed layer. So I can sometimes easily upset it, by performing changes outside of the store's expected contexts.

But being able to operate on the data from all levels, without having to worry about whether that will upset any of the other levels, would personally be a "must have" feature. There's no point in adding an optional higher level managed layer if it means you're shut off from also using the more direct lower levels.

So yeah, it would be a non trivial project to build, and much more than just a simple "let's try using a factory", so it's more of a "no thanks; not this year". But still does sound an appealing rainy day project to toy around with someday in the distant future 😄

**Comment by sobri909** [comment]
Just continuing that thought, I also think that would be beneficial to some of the existing functionality. For example things like `FetchedRecordsController`, which is essentially *already* a managed higher level layer, thus already breaks (or at least bends) some of GRDB's core principles.

If that sort of thing were split off into a separate project, it would allow the core GRDB to be more lean and clean about its focus on the core principles.

It would basically provide a clearly defined and enforced barrier between the managed and unmanaged functionality, so that one doesn't leak into the other.

**Comment by groue** [comment]
> Sounds reasonable to me.

Thanks, Matt. I need such feedback, both as a way to lift some doubts, but also because this project needs that I'm not alone understanding its goals :-)

> I guessed the flow on to the rest of the API might get nasty and add too much extra complexity in layers that shouldn't be complex. It sounds like your experiments proved that to be the case.

Yes. A valid but rare use case would have put a tax on everyone. I prefered documenting how to escape FetchableRecord.

> I wonder if a better way to do it, at some much later time, might be through an optional higher level `PersistentStore` class, much like how I do it in LocoKit. Or probably more correctly named, a `ManagedContext`, to steal Core Data's terminology.
> 
> (My own PersistentStore in LocoKit is really a combination of both store and managed context. Which makes sense for LocoKit because there's only allowed to be one store and one context, both operating at essentially the same level, so the store/context separation isn't necessary there).
> 
> Anyway, that way it could be an additive and optional higher level layer which doesn't require changes to the base level protocols. An extra, separate feature, for SDK users who want a higher level layer between them and the database rows.
> 
> I know that's something you explicitly **do not** want to be part of GRDB. I've already read a few of your strong arguments against exactly that 😉 But I think if it's done as an optional decoupled layer on top, it could fit nicely as a sort of "semi managed GRDB", thus it wouldn't do any damage to GRDB's core principles nor require any/many changes to it to accommodate.

Exactly. I don't want to prevent any user to write a managed layer on top of GRDB!

> [...] So yeah, it would be a non trivial project to build, and much more than just a simple "let's try using a factory", so it's more of a "no thanks; not this year". But still does sound an appealing rainy day project to toy around with someday in the distant future 😄

Yes. I hope that the new playground gives you an alternative to FetchableRecord.

> Just continuing that thought, I also think that would be beneficial to some of the existing functionality. For example things like `FetchedRecordsController`, which is essentially *already* a managed higher level layer, thus already breaks (or at least bends) some of GRDB's core principles.

That's right, you can say that FetchedRecordsController is managed :-) It would be nice if it would lose its coupling with FetchableRecord. But unless I'm mistaken, there's no rush: you have found a friend in TransactionObserver!

Thanks for this exploration, @sobri909!

**Comment by sobri909** [comment]
> Yes. I hope that the new playground gives you an alternative to FetchableRecord.

I wanted to have a look at that over the weekend, but didn't have time! I'll have a play with it soon. Looking forward to it 😄

> That's right, you can say that FetchedRecordsController is managed :-) It would be nice if it would lose its coupling with FetchableRecord. But unless I'm mistaken, there's no rush: you have found a friend in TransactionObserver!

Yep! Once I figured out what `FetchedRecordsController` was doing internally, it was easy for me to use `TransactionObserver` to write my own replacement that fitted my needs more specifically.

I think a `ManagedGRDB` lib would be quite fun to write, and would definitely have differentiation from things like Realm and Core Data. Because it could be a managed ORM that doesn't forcefully hide the SQL underbelly. I don't think anyone else is offering an Objective-C / Swift ORM like that yet?

Core Data and Realm forcefully separate you from the database layer. *[Or I assume Realm does - I've never actually looked at it closely]*. But that's not acceptable to me, because I grew up with SQL and I don't appreciate being separated from it.

I have to be able to see the database layer and be able to interact with it directly when I want to. If I need to optimise some code, I want to be able to work at the base level, outside of the management layer's rules, to get the job done precisely. The current high level ORMs don't allow that (or at least, if you tried to do it, you would probably be inviting disaster). 

There's a lot of benefit to having a high level managed layer that allows your application code to do most of its work on an appropriately abstracted high level. Ideally, application / business logic code should be operating on concepts and processes, not data structures and storage engines. But there's also a need (or desire) to be able to deal with the database directly, without having to perform any dangerous hacks. 

I don't think there's any Objective-C / Swift database libs that are enabling that full spectrum yet.

**Comment by groue** [comment]
A new chapter will ship in the GRDB 3 documentation: [Customized Decoding of Database Rows](https://github.com/groue/GRDB.swift/blob/GRDB3/README.md#customized-decoding-of-database-rows)
