### ISSUE TITLE
Monitoring queries

### ISSUE THREAD

**Issue by kaimatachi** [groue/GRDB.swift#357]
Hello,

I would like to know which of my queries are really heavy and should be reworked. So I want to monitor the time each query takes to be executed. I don't know how to do that in the case of a FetchedRecordsController. 

Could you help me find a way ? 

Thanks a lot for your work.

**Comment by groue** [comment]
Hello @kaimatachi,

At the time I'm writing this answer, I don't have any recommendation. Did you look for SQLite monitoring on Google in general, so that you have a better idea of what you need?

**Comment by kaimatachi** [comment]
Hi @groue ,

Thanks for your response. I will search more.

**Comment by groue** [comment]
Yes, @kaimatachi, if you please. Also, remember that Xcode ships with the Instruments application, which can monitor your app. It may be more interesting to check the user-facing behavior of your application, than the inner performance of SQLite.

**Comment by groue** [comment]
I'm closing this issue, @kaimatachi. Feel free to open a new one if you have further questions.
