### ISSUE TITLE
Problems with multiple queries

### ISSUE THREAD

**Issue by prsolucoes** [groue/GRDB.swift#359]
## What did you do?

Im trying execute two queries, but i got error after update to latest GRDB:

```
let statement = try db.makeUpdateStatement("DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;")
                
var arguments: StatementArguments = []
_ = arguments.append(contentsOf: ["uploaded": true])
                
statement.arguments = arguments
                
try statement.execute()
```

## What did you expect to happen?

Delete records and execute vacuum.

## What happened instead?

Error:

```
Erro ao executar query no banco de dados: SQLite error 21 with statement `DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;`: Multiple statements found. To execute multiple statements, use Database.execute() instead.
```

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** Latest from master
**Installation method:** GIT
**Xcode version:** Latest
**Swift version:** Latest
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Latest

## Demo Project

Dont need only the above code.

**Comment by prsolucoes** [comment]
I convert the code to:

```
let sql = "DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;"
                
var arguments: StatementArguments = []
_ = arguments.append(contentsOf: ["uploaded": true])
                
try db.execute(sql, arguments: arguments)
```

This is the correct way?

**Comment by groue** [comment]
Hello @prsolucoes,

As the error says:

> Multiple statements found. To execute multiple statements, use Database.execute() instead.

Indeed, `db.makeUpdateStatement(...)` can only build ONE statement. And `"DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;"` contains TWO statements, separated by a semicolon `;`.

You did follow the error advice, by using `Database.execute` instead. Good!

> I convert the code to:
>
> ```swift
> let sql = "DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;"
>              
> var arguments: StatementArguments = []
> _ = arguments.append(contentsOf: ["uploaded": true])
> 
> try db.execute(sql, arguments: arguments)
> ```
> 
> This is the correct way?

This is excellent! You can make it shorter this way:

```swift
let sql = "DELETE FROM bookmark WHERE uploaded = :uploaded; VACUUM;"
try db.execute(sql, arguments: ["uploaded": true])
```

Or even:

```swift
try db.execute("""
    DELETE FROM bookmark WHERE uploaded = :uploaded;
    VACUUM;
    """, arguments: ["uploaded": true])
```

Finally, a piece of advice. You wrote that you use the "latest GRDB version from master". This is not recommended. Instead, do follow the [installation instructions](https://github.com/groue/GRDB.swift/blob/master/README.md#installation), and install the **latest stable version** (currently tagged v2.10.0).

Happy GRDB!
