### ISSUE TITLE
Xcode 7.3 and Swift 2.2 - fails to build

### ISSUE THREAD

**Issue by da-na** [groue/GRDB.swift#36]
Hi!
After updating Xcode, my project that is using GRDB does not build no more. I get error messages:
![screen shot 2016-03-28 at 10 30 54 am](https://cloud.githubusercontent.com/assets/9628216/14080115/e449e6fc-f4d0-11e5-9bc1-d6932b875a6d.png)

and this: 
![screen shot 2016-03-28 at 10 30 36 am](https://cloud.githubusercontent.com/assets/9628216/14080142/1aa3554e-f4d1-11e5-833b-c0ffd931c922.png)

**Comment by groue** [comment]
Hello @da-na. Did you upgrade GRDB to its latest version 0.53.0?

**Comment by da-na** [comment]
I did pod update and I can see that the version I have installed is GRDB.swift (0.41.0)

**Comment by groue** [comment]
What about specifying `pod 'GRDB.swift', '~> 0.53.0'` in your Podfile, so that you make clear that your application won't work with earlier versions?

**Comment by da-na** [comment]
So I had exactly that line in the Podfile, but with the 0.41.0 version of GRDB. And now I have it as you wrote it.

**Comment by groue** [comment]
Did you `pod update`?

**Comment by da-na** [comment]
Yes, now it all works :) 
Thanks for your help!

**Comment by groue** [comment]
Great :-) Happy GRDB!
