### ISSUE TITLE
Compiling as static library using Cocoapods?

### ISSUE THREAD

**Issue by pocketpixels** [groue/GRDB.swift#360]
## What did you do?

I tried to use GRDB via Cocoapods without `use_frameworks!`, to build it as a static library. 

## What did you expect to happen?

I was hoping my Xcode project using GRDB would just compile without errors. 

## What happened instead?

When compiling in Xcode the Swift compiler reported this error:
".../GRDB.swift.modulemap:2:21: Umbrella header 'GRDB.h' not found"

Is there a way to modify the Podspec or module map so that GRDB can be compiled as a static library? 

## Environment

**GRDB flavor(s):** (GRDB, GRDBCipher, GRDBCustom?)
GRDB
**GRDB version:**
head of GRDB3 branch
**Installation method:** (CocoaPods, SPM, manual?)
Cocoapods (for iOS platform) via: 
`pod 'GRDB.swift' , :git => 'https://github.com/groue/GRDB.swift.git', :branch => 'GRDB3'
`
**Cocoapods version:**
1.5.2
**Xcode version:**
9.3.1
**Swift version:**
4.1
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
iOS
**macOS version running Xcode:**
10.13.4

**Comment by pocketpixels** [comment]
Just discovered that there is an [open bug against CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/7585) for this issue.

**Comment by groue** [comment]
Hello @pocketpixels, I noticed this issue too.

It looks like this is indeed a CocoaPods issue, not a GRDB issue.

I'm currently not investigating. Please reopen this issue if you want to investigate yourself. Actually, anyone can chime in and ask to reopen this issue. I just want to close it unless somebody is working on the topic.

**Comment by chrisballinger** [comment]
I'm going to take a crack at solving this. CocoaPods 1.7.4 gives the following error when trying to install GRDB as a static library:

```
[!] Using Swift static libraries with custom module maps is currently not supported. Please build `GRDB.swift` as a framework or remove the custom module map.
```

I think the right approach could be a subspec that does not use a custom modulemap, and instead relying on CocoaPods to generate a similar modulemap.
