### ISSUE TITLE
GRDB and Class Inheritance

### ISSUE THREAD

**Issue by 99xs** [groue/GRDB.swift#361]
Hi all,

I'm a newbie trying to use more advanced features in one of my projects. I'm sorry if this question has been asked before, but I haven't been able to find an answer yet and I'm a bit confused. If it has been answered already, a link to the answer would be very much appreciated too. :)

Basically, I'm trying to use class inheritance and it's failing. The two classes are below.

```
class Product: Record {
    var id: Int
    var sku: String?
    var type: String?
    var set: String?
    var categories: [Category]?
    var createdAt: NSDate?
    var updatedAt: NSDate?
    var typeId: Int?
    var name: String
    var description: String?
    var shortDescription: String?
    var status: Int?
    var visibility: Int?
    var categoryIds: String?
    var hasOptions: Bool?
    var price: Double
    var specialPrice: Double?
    var specialFromDate: NSDate?
    var specialToDate: NSDate?
    
    override class var databaseTableName: String {
        return "catalog_product"
    }
    
    required init(row: Row) {
        self.id = row["entity_id"]
        self.sku = row["sku"]
        self.type = row["type"]
        self.set = row["set"]
        self.createdAt = row["created_at"]
        self.updatedAt = row["updated_at"]
        self.typeId = row["type_id"]
        self.name = row["name"]
        self.description = row["description"]
        self.shortDescription = row["short_description"]
        self.status = row["status"]
        self.visibility = row["visibility"]
        self.categoryIds = row["category_ids"]
        self.hasOptions = row["has_options"]
        self.price = row["price"]
        self.specialPrice = row["special_price"]
        self.specialFromDate = row["special_from_date"]
        self.specialToDate = row["special_to_date"]
        super.init(row: row)
    }

    override func encode(to container: inout PersistenceContainer) {
        container["entity_id"] = self.id
        container["sku"] = self.sku
        container["type"] = self.type
        container["set"] = self.set
        container["created_at"] = self.createdAt
        container["updated_at"] = self.updatedAt
        container["type_id"] = self.typeId
        container["name"] = self.name
        container["description"] = self.description
        container["short_description"] = self.shortDescription
        container["status"] = self.status
        container["visibility"] = self.visibility
        container["category_ids"] = self.categoryIds
        container["has_options"] = self.hasOptions
        container["price"] = self.price
        container["special_price"] = self.specialPrice
        container["special_from_date"] = self.specialFromDate
        container["special_to_date"] = self.specialToDate
    }
    
    func didInsert(with rowID: Int, for column: String?) {
        self.id = rowID
    }
}


class QuoteItem:Product {
    var itemId: Int?
    var quoteId: Int?
    var quoteItemId: Int?
    var qty:Int = 1
    var discountPercent: Double?
    var discountAmount: Double?
    
    var rowTotal: Double {
        return Double(self.qty) * self.price
    }
    
    override class var databaseTableName: String {
        return "sales_quote_items"
    }
    
    required init(row: Row) {
        self.quoteItemId = row["quote_item_id"]
        self.itemId = row["product_id"]
        self.quoteId = row["quote_id"]
        self.qty = row["qty"]
        self.discountPercent = row["discount_percent"]
        self.discountAmount = row["discount_amount"]
        super.init(row: row)
    }
    
    override func encode(to container: inout PersistenceContainer) {
        container["quote_item_id"] = self.quoteItemId
        container["product_id"] = self.itemId
        container["quote_id"] = self.quoteId
        container["qty"] = self.qty
        container["discount_percent"] = self.discountPercent
        container["discount_amount"] = self.discountAmount
        container["row_total"] = self.rowTotal
    }
    
    override func didInsert(with rowID: Int, for column: String?) {
        self.quoteItemId = rowID
    }   
}
```

## What did you expect to happen?

I try to read from database the QuoteItems like...

```
do {
            let dbQueue = try DatabaseQueue(path: DatabaseUtility.getPath())
            try dbQueue.inDatabase { db in
                let quoteId = Column("quote_id")
                result = try QuoteItem.filter(quoteId == self.quoteId).fetchAll(db)
            }
        } catch {
            print(error.localizedDescription)
        }
```
... and it fails to initialise with error on 'entity_id' key. As I mentioned already, I'm a newbie and I probably did not understand exactly how inheritance works with GRDB.

Any help would be very much appreciated.
Thank you.

**Comment by groue** [comment]
Hello @99xs,

Don't apologize for being a newbie, and let's focus on your issue. Your records look well-defined, as well as your fetching code.

When you report an issue, be as precise as possible: what is the exact error you get? Provide `error.description`, or the text of any fatal error.

**Comment by 99xs** [comment]
The fatal error I get is: No such column. (Thread 1: Fatal error: no such column: entity_id)
In the database, catalog_product table contains column "entity_id" though. 

So... basically I use two tables, one for Query Items and one for Products.

**Comment by groue** [comment]
If the error reads `no such column: entity_id`, then this column does not exist in the fetched results. It's as simple as that.

You wrote:

> In the database, catalog_product table contains column "entity_id" though

But this is irrelevant, because you run `QuoteItem.filter(quoteId == self.quoteId).fetchAll(db)` which fetches from the `sales_quote_items` table (as defined by QuoteItem.databaseTableName).

Please read my edits in my initial answer. It really looks like you should reconsider having QuoteItem inherit from Product.

Finally, here are some recommendations for debugging this kind of issues, when you don't quite know what is happening:

1. Connect to the database with SQLite tracing on, to see the exact queries that are run:

    ```swift
    var config = Configuration()
    config.trace = { print($0) }
    let dbQueue = try DatabaseQueue(path: DatabaseUtility.getPath(), configuration: config)
    ```

2. Run the failing query with SQLite itself, given the exact path to the database:

    ```swift
    // swift
    print(dbQueue.path)
    ```

    ```sh
    # in terminal
    $ sqlite3 [insert the path here]
    sqlite> [insert the query here]
    ```

3. Check the reality vs. your expectations, and draw conclusions.

I hope that this answer should help you resolve your issue.

**Comment by 99xs** [comment]
Thank you so much for your help. I think your edits on the first answer solved the issue. Just for confirmation, I'm using now:

```
override func encode(to container: inout PersistenceContainer) {
        container["quote_item_id"] = self.quoteItemId
        container["product_id"] = self.itemId
        container["quote_id"] = self.quoteId
        container["qty"] = self.qty
        container["discount_percent"] = self.discountPercent
        container["discount_amount"] = self.discountAmount
        container["row_total"] = self.rowTotal
        super.encode(to: &container)
    }


override func didInsert(with rowID: Int, for column: String?) {
        self.quoteItemId = rowID
        super.didInsert(with: self.itemId!, for: column)
    }

```

Is this correct from your point of view? I can't know for sure at this moment, as by running my app I've found out that now it's not inserting into db (but this because I missed the super.encode and super.didInsert on all my previous uses).

**Comment by groue** [comment]
I can't say for sure, @99xs: I don't know your application enough. If you don't have any error, that's good. If you can understand the errors your application faces, that's good too. Keep on developing your application: you'll solve problems as they come to you :-) Happy GRDB!

**Comment by 99xs** [comment]
Thank you so much again for your help. I guess it was a rookie mistake... :)
Very good support!
