### ISSUE TITLE
GRDBCustom with FTS5 crashing with SQLite error 11

### ISSUE THREAD

**Issue by siegesmund** [groue/GRDB.swift#366]
## What did you do?

Followed the instructions detailing how to build a custom SQLite database in order to use FTS5. I also referenced the WWDC example. 
 
## What did you expect to happen?

My macOS app was working smoothly with GRDB & FTS4. I had hoped to utilize some of the features of FTS5. 

## What happened instead?

I repeatedly got SQLite error 11 with the warning "database disk image is malformed."

## Environment

**GRDB flavor(s):** GRDBCustom
**GRDB version:** 2.10.0
**Installation method:** Manual, per the SQLite custom build instructions.
**Xcode version:** 9.4
**Swift version:** 4.1.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.13.4

**Comment by groue** [comment]
Hello @siegesmund,

Could you please add information, and especially how and when you get this error 11? Don't hesitate sharing a little sample code and as much context as you can: the more somebody else can *reproduce* your issue, the more help you may expect.

**Comment by siegesmund** [comment]
It happens every time I try to execute a full text query: 
```swift
let pattern = FTS5Pattern(matchingAnyTokenIn: searchText)
let sql = "SELECT company_profiles.* FROM company_profiles JOIN company_profiles_fts ON company_profiles.id = company_profiles_fts.id AND company_profiles_fts MATCH ? ORDER BY RANK"
 let profiles = try! CompanyProfile.fetchAll(db, sql, arguments: [pattern])
```

**Comment by groue** [comment]
@siegesmund, thank you.

But this does not help much anybody reproduce your issue, and guide you out. GRDB support for FTS5 is well-tested, which means that there is no known issue: your active cooperation is required if you want help.

Did you search Google for the meaning of error 11 "database disk image is malformed"?

**Comment by siegesmund** [comment]
Yes, I have googled the error. It was the first thing I did. I posted the issue here after spending half a day trying to chase down the bug. I was hoping that in the GRDB + FTS5 context, this error message might point to a well known gotcha or simple mistake, perhaps in setting up the custom SQLite build. Your response indicates that it does not.

Unfortunately, I cannot upload the app here. Here are the steps I have taken to debug this issue: 

1. I have tried to execute the sql query above on the database using the terminal application. It executes successfully, without an error. 
2. I have run integrity check on the database. It returns 'ok'
3. I have rebuilt the apps dependencies as well as the database at least five times, each time walking through the instructions to make sure I followed them exactly, as well as comparing them to the WWDC example app. I cannot see any difference. 

Other facts: 

- I was able to use FTS4 with the standard GRDB package, everything else equal, without problems.
- The database size is 1.72 GB.

Thanks for your feedback.

**Comment by groue** [comment]
OK, thanks for the extra information.

I'm like you: I don't know what's wrong. Is it in the database file? In SQLite? In GRDB? In your application? 

I hope that you realize that the error 11 SQLITE_CORRUPT "database disk image is malformed" is not a good error message at all.

> Unfortunately, I cannot upload the app here

I'd try a little harder:

Since GRDBCustom plus FTS5 still embeds FTS4, you should be able to provide some sample code which, step after step:

1. Demonstrates how "smooth" FTS4 was,.
2. Shows how your app migrates to FTS5,
3. Until it hits SQLITE_CORRUPT.

We'd have a reproducible case. Without that, I'm afraid I won't be able to help much.

**Comment by groue** [comment]
No news is good news: happy GRDB!
