### ISSUE TITLE
Swift 4.2 branch fails to build as a dependency

### ISSUE THREAD

**Issue by QuestofIranon** [groue/GRDB.swift#379]
### What did you do?

added the 4.2 branch as a dependency for a swift 4.2/ XCode 10 project
`pod 'GRDB.swift', :git => 'https://github.com/groue/GRDB.swift.git', :branch => 'swift4.2'`

### What did you expect to happen?

The library to build with Swift 4.2 set as the version

### What happened instead?

Fails to build
![image](https://user-images.githubusercontent.com/2449351/42246839-0623a216-7ed3-11e8-8b5e-919dc3b7ed59.png)

I have to set it to build in 4.0 everytime a podfile update is required.

### Environment

**GRDB flavor(s):**  GRDB
**GRDB version:** Swift 4.2 Branch
**Installation method:** CocoaPods `pod 'GRDB.swift', :git => 'https://github.com/groue/GRDB.swift.git', :branch => 'swift4.2'`
**Xcode version:** Version 10.0 beta 2 (10L177m)
**Swift version:** 4.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** High Sierra 10.13.5

**Comment by groue** [comment]
Hello @QuestofIranon,
.
You're using beta software, and a branch that is not advertised anywhere

**Comment by groue** [comment]
Hello @QuestofIranon,

**You're backcountry skiing**: beta Xcode + unadvertised branch. This is not for everyone.

I recommend that you step back:

- `pod 'GRDB.swift', '~> 3.1'`
- If Xcode 10 keeps on complaining, add at the end of your Podfile:
    
    ```ruby
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if target.name == 'GRDB.swift'
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
          end
        end
      end
    end
    ```

**Comment by groue** [comment]
I'm reopening this issue until Xcode 10 is out (see https://github.com/groue/GRDB.swift/issues/383#issuecomment-404127426)

**Comment by groue** [comment]
GRDB 3.3.0-beta1 is out. It supports Xcode 10 beta 6 and Swift 4.2.
