### ISSUE TITLE
Enable FTS5 support on GRDBCipher version (requires updating SQLCipher to v3.4.2)

### ISSUE THREAD

**Issue by Marus** [groue/GRDB.swift#392]
This is a feature request. Would be useful to have FTS5 support enabled in the GRDBCipher. 

With the v3.4.2 release of SQLCipher this can be done with no changes to the library code, just adding the SQLITE_ENABLE_FTS5 to the appropriate build settings.

The full test suite passes as-is with one minor exception. In a number of the tests in `EncryptionTests.swift` file you check for the exact error message "file is encrypted or is not a database" - v3.4.2 of SQLCipher changes this message back to the original sqlite message of "file is not a database" (I think this is a bit of a strange choice on their part but that's another story). This would require either a) updating the tests to use the new message or b) replacing that error message in your fork of sqlcipher.

You can see the changes in my forks of sqlcipher (https://github.com/Marus/sqlcipher) and GRDB.swift (grdbcipher_fts5 branch - https://github.com/Marus/GRDB.swift/tree/grdbcipher_fts5)

I didn't create a pull-request directly as it would create a dependency on my fork of sqlcipher (this has the additional flag in the .xcconfig file and the changes in your repo rebased upon the v3.4.2 tag)

### Environment

**GRDB flavor(s):** (GRDB, GRDBCipher, GRDBCustom?) GRDBCipher
**GRDB version:** 3.2
**Installation method:** (CocoaPods, SPM, manual?) Manual
**Xcode version:** 9.4.1
**Swift version:** Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) iOS
**macOS version running Xcode:** 10.13.5

**Comment by groue** [comment]
Hello @Marus. I'm currently on vacations: please give me a few days before I can look at your request.

**Comment by groue** [comment]
Obsoleted by #393
