### ISSUE TITLE
Schema Recommendations 

### ISSUE THREAD

**Issue by Sully73** [groue/GRDB.swift#402]
I not sure if this is the correct place for asking general questions, if not I apologize and can move this to StackOverflow.

I have a question about schema best practices, I have parent Type `Entry` with a "many to one" relationship with 2 child types, `Note` and `Event.` 

![datarecords](https://user-images.githubusercontent.com/1440684/44311492-ecfe4280-a3be-11e8-829f-8340b9fe8601.png)

Although I'm in the early stages of development, this schema is generally working well for me. However, frequently I have an Event and would like to know if it has a sibling Note (shared with a common Entry). Currently, I'm doing something like this to determine that
```
    public func noteId(for event: Event) throws -> Int64? {
        return try dbPool.read({ db -> Int64? in
            let entry = try Entry
                .filter(Column("eventId") == event.id)
                .filter((Column("noteId") != nil))
                .fetchOne(db)
            return entry?.noteId
        })
    }

```

I thought about adding a noteId to Events, but this would create a circular reference, which I suspect will lead to problems down the road.

I guess what I'm asking is it OK what I'm currently doing? Or should I have the relationships set up differently? maybe some intermediate table to tie together an event with a note

```
public struct Entry: Codable, Equatable {
    public var id: Int64?
    public var type: EventType
    public var createdDate: Date
    public var textPreview: String?
    public var noteId: Int64?
    public var eventId: Int64?
}
    
public extension Entry {
    private static let note = belongsTo(Note.self)    
    private static let event = belongsTo(Event.self)
    public var note: QueryInterfaceRequest<Note> {
        return request(for: Entry.note)
    }
    public var event: QueryInterfaceRequest<Event> {
        return request(for: Entry.event)
    }
}

public class Note: Record, Codable {
    public var id: Int64?
    public var text: String?
}
		
public extension Note {
    private static let entry = hasMany(Entry.self)
    public var entry: QueryInterfaceRequest<Entry> {
        return request(for: Note.entry)
    }
}

public struct Event: Codable, Equatable {
    public var id: Int64?
    public var createdDate: Date
    public var startDate: Date
    public var endDate: Date
    public var identifier: String
    public var title: String
    public var isAllDay: Bool
}

public extension Event {
    private static let entry = hasMany(Entry.self)
    public var entry: QueryInterfaceRequest<Entry> {
        return request(for: Event.entry)
    }
}

```

**Comment by groue** [comment]
Hello @Sully73,

> Frequently I have an Event and would like to know if it has a sibling Note (shared with a common Entry). [...]
> I thought about adding a noteId to Events, but this would create a circular reference, which I suspect will lead to problems down the road.

It looks that an event should be linked to **zero or one** note (its one and only "sibling note").

But the database schema implements something else: it tells that an event is linked to **zero or several** notes, with no one among them being more special that the others.

I'm note sure how you want this contradiction to be solved. It all depends on the actual features of you app. You may need to:

1. Fix the code, so that one should not be able to load one special note from an event. Maybe knowing that an event has some notes is enough.
2. Fix the schema so that one event can not have more than one note.
3. Fix the schema so that one event can have several notes through its entries, but one is special (for some reason).

**Comment by Sully73** [comment]
Thanks @groue I think i'll review the schema
