### ISSUE TITLE
Error: "Unkeyed decoding is not supported" when querying a model composed of associations

### ISSUE THREAD

**Issue by SD10** [groue/GRDB.swift#406]
Hey @groue,

First and foremost, thanks for all the effort you've put into creating this project! I know the amount of effort it requires to manage an open source project and you're doing an incredible job 💪

I'm currently facing an issue where I'm having trouble querying a model object from a `FetchedRecordsController`. I have listed some pseudocode below in an attempt to describe my issue.

This object, `AuthorInfo`, is a combination of underlying table models:
- `Author` the parent model
- `Book` (Author has a hasMany relationship)
- `Stats` (Author has a hasOne relationship)

```Swift
// MARK: - Database Models

struct Author: Codable, Fetchable, MutablePersistableRecord {

   var uid: String = ""

   static var stats = hasOne(Stats.self)

   var stats: QueryInterfaceRequest<Stats> {
       return request(Author.stats)
   }

  static var books = hasMany(Book.self)

   var books: QueryInterfaceRequest<Book> {
      return request(Author.books)
   }
}

struct Book: Codable, Fetchable, MutablePersistableRecord {

   var uid: String = ""
   var authorId: String = "" // foreign key for `Author.uid`

}

struct Stats: Codable, Fetchable, MutablePersistableRecord {

   var uid: String = ""
   var authorId: String = "" // foreign key for `Author.uid`

}

// MARK: - Query Model

struct AuthorInfo: Codable, Fetchable {
   var author: Author
   var stats: Stats?
   var books: [Books]

    static func all() -> QueryInterfaceRequest<AuthorInfo> {
        return Author
            .including(optional: Author.stats)
            .including(required: Author.books)
            .asRequest(of: AuthorInfo.self)
    }
}
```

This request works fine if I comment out the code related to querying the `[Books]`. However, with that code I am receiving the error: 
```
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.typeMismatch(Swift.UnkeyedDecodingContainer, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "books", intValue: nil)], debugDescription: "unkeyed decoding is not supported", underlyingError: nil))
```

Please forgive me if I'm missing something obvious or just don't understand relational databases in general. I typically use NoSQL or ORMs -- so using GRDB has really required me to start thinking in a completely different way. 

**Environment**

**GRDB flavor(s)**: GRDB
**GRDB version**: 3.2
**Installation method**: Carthage
**Xcode version**: 9.4
**Swift version**: 4.1
**Platform(s) running GRDB**: iOS
**macOS version running Xcode**: 10.13.5

**Comment by groue** [comment]
Hello @SD10,

Ouch! You are experiencing a current limitation of associations: they can't fetch *arrays of associated records* yet:

```swift
struct AuthorInfo: Codable, Fetchable {
    var author: Author
    var stats: Stats?
    var books: [Books] // <- there lies the issue
    
    static func all() -> QueryInterfaceRequest<AuthorInfo> {
        return Author
            .including(optional: Author.stats)
            .including(required: Author.books)
            .asRequest(of: AuthorInfo.self)
    }
}
```

Associations can only build "flat" requests that fetch items made of individual associated records (for example, book/author pairs). There is not yet any "tree" request that deals with records and arrays of associated records.

A request such as `Author.including(required: Author.books)` still has a meaning, but not the one you need: it loads (Author, Book) pairs. If the database contains one author (A) who has written two books (B1 and B2), you'd get two pairs: (A, B1) and (A, B2).

When the feature you need is eventually implemented, you'll write your request differently:

```swift
// Expected Future
Author.including(all: Author.books) // Fetches (Author, [Book]) pairs
```

But... future is only the future. What can you do *right now*?


### Fetch AuthorInfo

```swift
struct AuthorInfo {
    var author: Author
    var stats: Stats?
    var books: [Books] // <- there lies the issue
}
```

Since no built-in GRDB request is able to feed AuthorInfo, let's start by fetching them by hand:

```swift
extension AuthorInfo {
    static func fetchAll(_ db: Database) throws -> [AuthorInfo] {
        // First fetch (author, stats) pairs:
        struct PartialAuthorInfo: Codable, Fetchable {
            var author: Author
            var stats: Stats?
        }
        let partialRequest = Author.including(optional: Author.stats)
        let partials = try PartialAuthorInfo.fetchAll(db, partialRequest)
        
        // Now that we have authors, fetch their books
        let authorIds = partial.map { $0.author.uid }
        let books = try Book
            .filter(authorIds: authorIds) // Assume an existing Book.filter(authorIds:) method that returns QueryInterfaceRequest<Book>
            .fetchAll(db)
        
        // Group books by author uid in a Dictionary<String, [Book]>
        let booksForAuthorId = Dictionary(grouping: books, by: { $0.authorId })
        
        // Merge
        return partials.map { partial in
            let books = booksForAuthorId[partial.author.uid] ?? []
            return AuthorInfo(
                author: partial.author,
                stats: partial.stats,
                books: books)
        }
    }
}
```

This technique is somewhat complex, but it is able to build your results in only two database requests, instead of performing as many book requests as there are authors. It is supposed to be more efficient (but we'd need benchmarks for confirmation).


### Observe changes

Now, everything depends on your observation needs. Are you using the `willChange` and `onChange` callbacks of FetchedRecordsController, or only `didChange`?

**Comment by SD10** [comment]
Hey @groue,

Thanks for the speedy response! 🏎 

I had suspected this was the case and the solution you propose was my intended workaround -- however -- I did get caught up on how to allow this two-part request to drive the `FetchedRecordsController`.

> ### Observe Changes
> Now, everything depends on your observation needs. Are you using the willChange and onChange callbacks of FetchedRecordsController, or only didChange?

All I need in this situation is the callback for `didChange`. My initial thought was to drive the request with a `TransactionObserver` which would mimic a `FetchedRecordsController`? If you could recommend a best practice, I'm all ears 😄

**Comment by groue** [comment]
Yes, TransactionObserver is definitely your friend here. I only have one recommendation: mind your dispatch queues!

**Comment by groue** [comment]
Limiting factors are time, and my current skills.

GRDB wants time in development, documentation, support, and maintenance. [GRDB 3.3](https://github.com/groue/GRDB.swift/blob/development/CHANGELOG.md) will ship with Xcode 10.

The topic of associations is well-known: other libraries out there are able to use the best SQL strategies that fetch the graphs of associated objects declared by the developer: Active Record, Core Data, Django ORM, maybe https://github.com/PersistX/PersistDB, many others.

The information is out there in the wild, but I haven't taken the time to look at it yet.

What I've done, on the other side, is decide how associations are declared, how one builds requests, and how one consumes graphs in dedicated types like `AuthorInfo`, with a big focus on Codable. This all looks pretty well integrated and conceptually sound, and I'm quite happy of it. But it was just the beginning of the journey! We still lack:

- Complete nested graphs of records (this is your need): give me all authors with their books.
- Aggregates: give me all authors with their number of books.
- Missing associations: "hasOneThrough", "hasManyThrough", and maybe "hasAndBelongsToMany" (see [ActiveRecord](https://guides.rubyonrails.org/association_basics.html#the-types-of-associations))
- etc.

I'm right in the middle: I have a somewhat precise idea of the desired feature set, I'm aware of many traps and gotchas, but I don't know yet how to proceed. Maybe it won't be me !?

**Comment by groue** [comment]
As a support for your transaction observers, I've pushed a new doc paragraph about **database regions**: 056db7ff6fec187513e54bed6e197320e1de3a8c (in development branch, but regions are already public in GRDB 3.2.0).

You don't have to use them, but they may help you write reusable code. There is more doc about regions at https://github.com/RxSwiftCommunity/RxGRDB/#databaseregionconvertible-protocol

**Comment by SD10** [comment]
Hey @groue,

Thanks for all of the help and very detailed responses! 🙇 I've managed to solve my issue and I'm going to close this for now.

> I'm right in the middle: I have a somewhat precise idea of the desired feature set, I'm aware of many traps and gotchas, but I don't know yet how to proceed. Maybe it won't be me !?

It would be naive of me to think I could contribute this feature given my current understanding of SQLite / relational databases -- but if we go with GRDB for our apps local persistence layer -- I will surely take a deep dive into the GRDB codebase in hopes of making a contribution 💪 

Thanks again!

**Comment by groue** [comment]
That's very nice of you, Steven. It's vital for GRDB to attract more contributors. You know it [pretty well](https://medium.com/@_SD10_/scaling-and-managing-open-source-communities-e9761b691e39). And yes indeed, such a project teaches a lot about relational databases, SQLite, ORMs, etc :-) And I did not know that it was possible to bring something fresh when I wrote the first lines of this lib!

**Comment by groue** [comment]
Eager loading of HasMany associations is coming: #505

**Comment by groue** [comment]
The feature has just landed in GRDB 4. Check the updated documentation of Associations.
