### ISSUE TITLE
Xcode 10 GRDBCipher Build Error

### ISSUE THREAD

**Issue by isaac-weisberg** [groue/GRDB.swift#411]
### What did you do?

Build via Carthage

### What did you expect to happen?

Successful build.

### What happened instead?

Errored out while building `GRDBCipheriOS` in `GRDB.xcworkspace`, stating `error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture.`

### Environment

**GRDB flavor(s):** GRDBCipher
**GRDB version:** 3.2.0
**Installation method:** Carthage
**Xcode version:** 10 GM
**Swift version:** 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13

**Comment by isaac-weisberg** [comment]
Wait a minute, what? But i386 is set only for the-- uhm, the macOS target... what the heck

**Comment by groue** [comment]
Hello @isaac-weisberg,

Please use GRDB 3.3.0-beta1 with Xcode 10.

Note that Carthage is **not supported** by GRDB (see the main README), which literally means that you shouldn't expect any support from maintainers. Some other users may help you, of course. Carthage maintainers may help you as well. Or StackOverflow.

**Comment by groue** [comment]
See #408 for more context.
