### ISSUE TITLE
dyld: Symbol not found: __T0BOWV

### ISSUE THREAD

**Issue by zp19921992** [groue/GRDB.swift#412]
I add GRDB to my project by Submodule.when i run my project.it's crash!

dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/5C6E0A35-B8F7-4B8C-AAF4-D039823000A1/EOS.app/Frameworks/GRDB.framework/GRDB
  Expected in: /private/var/containers/Bundle/Application/5C6E0A35-B8F7-4B8C-AAF4-D039823000A1/EOS.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/5C6E0A35-B8F7-4B8C-AAF4-D039823000A1/EOS.app/Frameworks/GRDB.framework/GRDB

**Comment by groue** [comment]
Hello @zp19921992. Please do your own Google search before asking. And please fill the issue template when you create an issue. Thanks.
