### ISSUE TITLE
SQLite error 14: unable to open database file

### ISSUE THREAD

**Issue by herotheone** [groue/GRDB.swift#415]
### What did you do?

I wanted to connect my pre-loaded sqlite database and bundled it within the Xcode project navigator.

### What did you expect to happen?

I wanted to  connect that database. I already have successful connection with simulator but no luck with real iPhone.
### What happened instead?

I get this error:

2018-09-22 19:01:42.098199+0800 myWay[1069:233261] [logging-persist] cannot open file at line 42249 of [95fbac39ba]
2018-09-22 19:01:42.098231+0800 myWay[1069:233261] [logging-persist] os_unix.c:42249: (0) open(/var/containers/Bundle/Application/B93852F8-F874-445F-911C-624CEDD765C3/myWay.app/db2.sqlite-wal) - Undefined error: 0
2018-09-22 19:01:42.098246+0800 myWay[1069:233261] [logging-persist] unable to open database file
SQLite error 14: unable to open database file

### Demo Project

https://github.com/herotheone/myWay

**Comment by groue** [comment]
Hello @herotheone 

Error code 14 stands for [SQLITE_CANTOPEN](https://www.sqlite.org/rescode.html#cantopen), "unable to open database file". I don't know why SQLite is unable to open your database. But did you check, for example, that there exists a database file at the path you provide?

**Comment by herotheone** [comment]
In the simulator everything works perfectly. I think i need to copy that sqlite file right ?
How can i copy that sqlite file to iPhone's path folder ? Is there a way to do it with FileManager.copyItems(at: to:) ?

**Comment by groue** [comment]
What path are you currently using? The one that works on the simulator, but fails on the device?

**Comment by herotheone** [comment]
` let dbPath = Bundle.main.path(forResource: "db2", ofType:"sqlite")
        
       do {
            
            let dbQueue = try DatabaseQueue(path: dbPath!)
            
            try dbQueue.inDatabase { db in
                
                //Select all data from the table named tablename residing in SQLite
               
                let rows = try Row.fetchCursor(db, "SELECT * FROM ZIMPORT")
                
                while let row = try rows.next() {
                    
                  let someString : String = row["gAnahtarKelime"]
                    let someString2 : String = row["gMana1"]
                    let someString3 : String = row["gMana2"]
                    let someString4 : String = row["gMana3"]
                    print("Anahtar Kelime : \(someString)")
                    print("Mana 1 : \(someString2)")
                    print("Mana 2 : \(someString3)")
                    print("Mana 3 : \(someString4)")
                   
                }
            }
        } catch {
            
            print(error.localizedDescription)
            
        }`

**Comment by herotheone** [comment]
`let dbPath2 = Bundle.main.path(forResource: "db2", ofType:"sqlite")
        
        do {
            
            let dbQueue2 = try DatabaseQueue(path: dbPath2!)
            
            try dbQueue2.inDatabase { db in
                
                //Select all data from the table named tablename residing in SQLite
                let rows2 = try Row.fetchCursor(db, "SELECT * FROM ZIMPORT WHERE gAnahtarKelime = '\(gelenAnahtarKelime)'")
                
                while let row2 = try rows2.next() {
                    
                    let someString : String = row2["gAnahtarKelime"]
                    let someString2 : String = row2["gMana1"]
                    let someString3 : String = row2["gMana2"]
                    let someString4 : String = row2["gMana3"]
                  
                    altSonuc = [ ]
                    
                    altSonuc.append(someString)
                    altSonuc.append(someString2)
                    altSonuc.append(someString3)
                    altSonuc.append(someString4)
                    
                    aramaSonuclariTableView.reloadData()
                    
                }
             
            }
            
            
        } catch {
            
            print(error.localizedDescription)
            
        }`

**Comment by herotheone** [comment]
```
let dbPath = Bundle.main.path(forResource: "db2", ofType:"sqlite")
        
       do {
            
            let dbQueue = try DatabaseQueue(path: dbPath!)
            
            try dbQueue.inDatabase { db in
                
                //Select all data from the table named tablename residing in SQLite
               
                let rows = try Row.fetchCursor(db, "SELECT * FROM ZIMPORT")
                
                while let row = try rows.next() {
                    
                  let someString : String = row["gAnahtarKelime"]
                    let someString2 : String = row["gMana1"]
                    let someString3 : String = row["gMana2"]
                    let someString4 : String = row["gMana3"]
                    print("Anahtar Kelime : \(someString)")
                    print("Mana 1 : \(someString2)")
                    print("Mana 2 : \(someString3)")
                    print("Mana 3 : \(someString4)")
                   
                }
            }
        } catch {
            
            print(error.localizedDescription)
            
        }
```

**Comment by groue** [comment]
This looks correct. Now make sure that all those sentences below are true. Do check them, don't simply assume they are true:

- you have a `db2.sqlite` resource in your project.
- you made sure that this resource is bundled in your application, on the device.
- you run this code **only once** in the lifetime of your application.
- the format of the `db2.sqlite` file is compatible with the version of SQLite that ships with the iOS version on your device.

If you still have error SQLITE_CANTOPEN after those checks, then I really don't know what is happening.

**Comment by groue** [comment]
Also, since the log you provide in the initial comment contains `db2.sqlite-wal`, I conclude that your database is not a simple `db2.sqlite` file. It has been opened in the WAL mode at some point. The real story is more complex than the one you have told.

Do you also use DatabasePool? Don't mix DatabaseQueue and DatabasePool. Choose one. And create **one** in the lifetime of your application.

Do you attempt at modifying the content of the database? You can not do that if the database is bundled as a resource, because resources can not be modified by the application. To make sure the database resource is not modified, open the database in the read-only mode:

```swift
var config = Configuration()
config.readonly = true
let dbQueue = DatabaseQueue(path: ..., configuration: config)
```

**Comment by herotheone** [comment]
```
var dbPath : String = ""
        var dbResourcePath : String = ""
        
        
        var config = Configuration()
        config.readonly = true
       
        let fileManager = FileManager.default
        do{
         dbPath = try fileManager
            .url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            .appendingPathComponent("db2.sqlite")
            .path
        if !fileManager.fileExists(atPath: dbPath) {
            dbResourcePath = Bundle.main.path(forResource: "db2", ofType: "sqlite")!
            try fileManager.copyItem(atPath: dbResourcePath, toPath: dbPath)
        }
        }catch{
            print("An error has occured")
        }
        
        
       do {

        let dbQueue = try DatabaseQueue(path: dbPath, configuration: config)

            try dbQueue.inDatabase { db in

                //Select all data from the table named tablename residing in SQLite

                let rows = try Row.fetchCursor(db, "SELECT * FROM ZIMPORT")

                while let row = try rows.next() {

                  let someString : String = row["gAnahtarKelime"]
                    let someString2 : String = row["gMana1"]
                    let someString3 : String = row["gMana2"]
                    let someString4 : String = row["gMana3"]
                    print("Anahtar Kelime : \(someString)")
                    print("Mana 1 : \(someString2)")
                    print("Mana 2 : \(someString3)")
                    print("Mana 3 : \(someString4)")

                }
            }
        } catch {
        
            print(error.localizedDescription)

        }
```

I edited my code like this. Still getting same error

**Comment by herotheone** [comment]
I changed this line 
`let dbQueue = try DatabaseQueue(path: dbPath, configuration: config)
` with this
`let dbQueue = try DatabaseQueue(path: dbPath)`
Now it is working !!

**Comment by groue** [comment]
> Now it is working !!

Great! I don't quite know what happened, but what counts is that your app can run. Happy GRDB!

**Comment by mohamede1945** [comment]
I faced a similar issue and the solution is to execute the following command on the database before using it as read-only database (or part of the app's bundle):
```
PRAGMA journal_mode=DELETE
```
See https://www.sqlite.org/wal.html _**Read-Only Databases**_ section.

**Comment by herotheone** [comment]
Thank you very much for your help brothet

21 Nis 2019 Paz, saat 06:08 tarihinde Mohamed Afifi <
notifications@github.com> şunu yazdı:

**Comment by ahmedk92** [comment]
For noobs like me. If your database  is read-only, and it was somehow created with WAL mode. You can change that to 'DELETE' with your database editor (e.g. DB Browser for SQLite) under "Edit Pragmas" or similar. This the GUI equivalent to @mohamede1945 's answer.

![Screen Shot 2019-07-16 at 5 51 08 PM](https://user-images.githubusercontent.com/11476927/61309497-97aafb00-a7f2-11e9-94d3-94676d7d897b.png)

**Comment by rteuteu55** [comment]
> I faced a similar issue and the solution is to execute the following command on the database before using it as read-only database (or part of the app's bundle):
> 
> ```
> PRAGMA journal_mode=DELETE
> ```
> 
> See https://www.sqlite.org/wal.html _**Read-Only Databases**_ section.

This helped me, thank you !!

**Comment by seong7** [comment]
@rteuteu55 
> PRAGMA journal_mode=DELETE

Can you let me know where you wrote it?

**Comment by rteuteu55** [comment]
@seong7 
> @rteuteu55
> 
> > PRAGMA journal_mode=DELETE
> 
> Can you let me know where you wrote it?

I use SQLite DB Browser and I just typed the command in the execute SQL tab.
I then saved the DB and it worked. Any SQL file editor where you can run SQL command should work I assume.

**Comment by groue** [comment]
Users who want to be able to open a read-only connection on a WAL database, while preserving its WAL qualities, should read [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md#the-specific-case-of-readonly-connections) and particularly the "The specific case of readonly connections" chapter.
