### ISSUE TITLE
Is it possible to sort the results of a FetchedRecordsController using a property that is not a database column?

### ISSUE THREAD

**Issue by james-rantmedia** [groue/GRDB.swift#432]
### What did you do?

I have a struct that models a table in my database. It has a property that is a derived value that is not in the database itself. I would like to sort the fetched records from a `FetchedRecordsController` using this property, but I don't see how to do this (or even if it is possible).

### What did you expect to happen?

A way to sort the fetched records that doesn't rely on having a column in the database. For example, I may set the `FetchedRecordsController`'s request to return all rows for my table, but specify that it should sort using a provided comparator closure.

### What happened instead?

Unable to see anything that might allow sorting on a property that does not rely on having a related column in the table.

### Environment

**GRDB flavor(s):** GDRBCipher
**GRDB version:** v3.3.0
**Installation method:** Carthage
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14

**Comment by groue** [comment]
Hello @james-rantmedia 

This is not currently possible. Ordering has to be done by SQLite. You may want to have a look at [Custom SQL Functions and Aggregates](https://github.com/groue/GRDB.swift/blob/master/README.md#custom-sql-functions-and-aggregates): this can make SQLite able to access your derived values, and sort.
