### ISSUE TITLE
How to notify if Update or execute sql statement is succeded ?

### ISSUE THREAD

**Issue by faizbaraja** [groue/GRDB.swift#434]
I want to know how to notify the result of update, delete or executing sql statement whether it is succeded or failed..

Thanks

**Comment by Kirow** [comment]
use try-catch or RxGRDB. not sure what you need...

**Comment by faizbaraja** [comment]
ok2....just tried with try catch...and it worked good....Thanks

**Comment by groue** [comment]
> I want to know how to notify the result of update, delete or executing sql statement whether it is succeded or failed

If you want to know if a database change has succeeded or failed, just catch Swift errors, and check the [`changesCount`](https://groue.github.io/GRDB.swift/docs/3.4/Classes/Database.html#/s:4GRDB8DatabaseC12changesCountSivp) property:

```swift
do {
    try db.execute("UPDATE ...")
    if db.changesCount > 0 {
        print ("some rows were updated")
    } else {
        print ("no row was updated")
    }
} catch {
    print("an error occurred")
}
```

If you want to get automatically notified, in other parts of your applications, of database changes, check the [Database Observation](https://github.com/groue/GRDB.swift/blob/master/README.md#database-changes-observation) chapter.
