### ISSUE TITLE
Difference fields in database and data model

### ISSUE THREAD

**Issue by Mahdimm** [groue/GRDB.swift#438]
Hi @tonyarnold

I have a table with 3 columns but its model has 4 properties, What should I do in this case? because when I set insert query I got this error:

> Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement INSERT INTO "student" ("id", "name", "lastName", "age") VALUES (?,?,?,?): table student has no column named age!

My table columns are: id, name, lastName
My model properties: id, name, lastName, age

is there any protocol that I can fix this problem?

**Comment by groue** [comment]
Hi @Mahdimm,

> is there any protocol that I can fix this problem?

You did not say much, so I'll suppose that you use the [PersistableRecord](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol) protocol, the one which provides the GRDB [persistence methods](https://github.com/groue/GRDB.swift/blob/master/README.md#persistence-methods) such as `insert`, `update`, etc.

You control the stored columns with the `encode(to:)` method. In your case, store `id`, `name`, `lastName`, but omit `age`:

```swift
func encode(to container: inout PersistenceContainer) {
    container["id"] = id
    container["name"] = name
    container["lastName"] = lastName
}
```

If you happen to use the standard Encodable protocol on top of PersistableRecord, then you can't profit from the persistence code generated by the compiler. It stores all properties, including `age`. But you can still provide your own Encodable implementation which omits `age`. Please refer to the [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) documentation.

**Comment by Mahdimm** [comment]
thanks for replay @groue 

We solved problem in this way and maybe this code help someone who is searching for same problem:

```
struct Student: Codable, TableRecord {
    var id : Int64?
    var name: String
    var lastName: String? //this is an optional property and maybe set Null in Database
    var age: Int? // we have this field in our model but do not have in our databse!

    init(id:Int64?, name:String, lastName: String, age: Int?) {
        self.id = id
        self.name = name
        self.lastName = lastName
        self.age = age
    }

    //read data from database
    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(Int64.self, forKey: .id)
        name = try values.decode(String.self, forKey: .name)
        lastName = try! values.decode(String?.self, forKey: .lastName)
        age = 0 // set our default value here
    }

    //insert data to database
    func encode(to container: inout PersistenceContainer) {
        container["id"] = id
        container["name"] = name
        container["lastName"] = lastName
    }

}

extension Student: FetchableRecord {  }

extension Student: MutablePersistableRecord {
    static let databaseTableName = "Student"
    
    enum Columns: String, ColumnExpression {
        case id, name, lastName
    }
    
    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
}
```

**Comment by groue** [comment]
Great you found your solution, @Mahdimm! Happy GRDB!

**Comment by MrShafiee** [comment]
Hello @groue,
I have a question, this line is correct ? 
`lastName = try! values.decode(String?.self, forKey: .lastName)`

in _init(from decoder: Decoder) throws_ function, **lastName** is optional, to set value for this; @Mahdimm  use above line, is that okey? or are there any better ways?

because if we use like this:
`try? values.decode(String.self, forKey: .lastName)`
 app crash with this error: _**Fatal error: could not convert database value NULL to String**_ , although
its property define optional in its model.

Thanks for your response.
