### ISSUE TITLE
Failed to run the first code

### ISSUE THREAD

**Issue by quanguyen** [groue/GRDB.swift#44]
Hi,

It's unfortunate for me not to be able to install this great lib. I followed [your instruction](https://github.com/groue/GRDB.swift#installation) - Manual. After the 4 steps (download, drag&drop `GRDB.xcodeproj` to my project, add `GRDBiOS` to `Target Dependencies` in `Build Phases` of my app, add `GRDB.framework` to `Embedded Binaries` in `General` tab of my app), I get this error in my `ViewController.swift`:

<img width="889" alt="screen shot 2016-05-10 at 7 03 57 pm" src="https://cloud.githubusercontent.com/assets/11938078/15145809/0f8622a8-16e2-11e6-84cc-5ab935c7f05e.png">

2 questions:

1) As in the warning, do I have to import the `GRDB`?
2) Why after the 4 steps, I still cannot compile my first line of code with `DatabaseQueue`?

Please show me how to solve my issues.

Note that I am using XCode 7.3.1.

Thanks a lot

**Comment by groue** [comment]
Hello @quanguyen 

The [GRDBDemoiOS](https://github.com/groue/GRDB.swift/tree/master/DemoApps/GRDBDemoiOS) was built following the manual integration instructions. It compiles fine.

So I don't quite know where your app got something wrong, but the warning gives us a hint. Did you carefully read it before pasting a raw picture here? Do you understand it?

It says: "ViewController.swift is part of module GRDB". Do you think it's normal that your application code is part of the third-party GRDB framework?

No, it is not normal.

Depending on your skills, you may already have enough information to solve your trouble. If you are still stuck, here is what you have to do:

1. Open the GRDBDemoiOS app project (in the DemoApps/GRDBDemoiOS folder of the GRDB distribution)
2. Read again the manual installation steps, and make sure you understand exactly each sentence. Use the demo app as a reference. Repeat until you will eventually spot the problem, and successfully solve your issue.

**Comment by quanguyen** [comment]
Thanks for the hint. I found out that my sample project has the same name as GRDB project. That is why XCode confuses. I just renamed and everthing is just fine.

**Comment by groue** [comment]
Good catch! Happy GRBD!
