### ISSUE TITLE
Compiler error: "Could not cast value of type 'GRDB.Record'"

### ISSUE THREAD

**Issue by DanielBalsalobre** [groue/GRDB.swift#447]
### What did you do?

After update from early beta version to 3.5.0 i lose the capability of auto map collections of [Record] to collections of [SomeClass]

### What did you expect to happen?

Automatic cast [Record] to [SomeClass] like early versions.
Or at least cast Record to SomeClass directly.

### What happened instead?

When i try to cast a [Record] into [SomeClass]: Fatal error: Down-casted Array element failed to match the target type
2018-11-26 16:08:38.139454+0100 Fatal error: Down-casted Array element failed to match the target type

When i try to cast a Record into a SomeClass:  Could not cast value of type 'GRDB.Record' (0x1064b4630) to 'SomeClass' (0x104164328).

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 3.5.0
**Installation method:** CocoaPods
**Xcode version:** 10.1 (10B61)
**Swift version:** 4.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14 (18A391)

**Comment by DanielBalsalobre** [comment]
Im close to get a solution, if i use type(of: someObject).fetchAll i get non castable [Record] but if i use SomeClass.fetchAll i get a [SomeClass] that is good and casted. My problem now is to unify this solution in one function instead do one function per class

**Comment by groue** [comment]
Hello @DanielBalsalobre,

Thanks for upgrading GRDB to the latest version. I hope you'll enjoy a library that has matured a lot since its early stages.

Swift has evolved also, as you can see. The "Could not cast value of type 'GRDB.Record' to 'SomeClass'" is not an issue with GRDB. It is a Swift error. If your issue persists, I suggest you look for a similar trouble on [StackOverflow](https://stackoverflow.com).

**Comment by DanielBalsalobre** [comment]
> Hello @DanielBalsalobre,
> 
> Thanks for upgrading GRDB to the latest version. I hope you'll enjoy a library that has matured a lot since its early stages.
> 
> Swift has evolved also, as you can see. The "Could not cast value of type 'GRDB.Record' to 'SomeClass'" is not an issue with GRDB. It is a Swift error. If your issue persists, I suggest you look for a similar trouble on [StackOverflow](https://stackoverflow.com).

Yeah, good job! thanks

**Comment by DanielBalsalobre** [comment]
Wait a couple of days for close this issue, if i get a solution i will post it here

**Comment by groue** [comment]
Thank you @DanielBalsalobre ! It's highly appreciated :-) Happy GRDB!

**Comment by DanielBalsalobre** [comment]
Yes!! i have solved the problem using "Row.fetchAll" directly and doing ".map { SomeClass(row: $0) }"

Thanks! hope this can help someone with the same issue.

**Comment by groue** [comment]
Glad you found a solution!

**Comment by groue** [comment]
But normally, `SomeClass.fetchAll(...)` should work directly. Check https://github.com/groue/GRDB.swift/blob/master/Playgrounds/Record.playground/Contents.swift

**Comment by DanielBalsalobre** [comment]
> But normally, `SomeClass.fetchAll(...)` should work directly, and is the recommended way to do. Look at https://github.com/groue/GRDB.swift/blob/master/Playgrounds/Record.playground/Contents.swift for a sample code.

Agree but our app have more of 30 classes and our fetch functions are unified and maintenance free, i want to keep this as is if possible. 

Here is an example of function that fetch data from any class passed by parameter and a simple sql filter:  

`func get(obj: Record, filter: String) -> [Record] {
    var list: [Row]? = []
    if Sesion.dbQueue == nil {
        return []
    }
    var filterString = ""
    if filter != "" {
        filterString = [" WHERE ", filter].joined()
    }
    do {
        
        try Sesion.dbQueue?.inDatabase { db in
            list = try Row.fetchAll(db, ["SELECT * FROM ", String(describing: obj).components(separatedBy: ".")[1], filter].joined())
        }
    } catch let error {
        print(error)
    }
    return list!.map { type(of: obj).init(row: $0) }
}`

Thanks for the support.
