### ISSUE TITLE
Failure with Carthage for Mac build

### ISSUE THREAD

**Issue by skreutzberger** [groue/GRDB.swift#45]
While installing GRDB 0.6.1 via Carthage with a Mac as platform I get the following failure:

<img width="1012" alt="screenshot 2016-05-11 at 09 51 00" src="https://cloud.githubusercontent.com/assets/564725/15174297/2e0ab0b6-1761-11e6-8b09-c2d6f5d12321.png">

**Comment by groue** [comment]
Hello @skreutzberger,

I can't reproduce your issue:

```
$ carthage version
0.16.2
$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
$ cat Cartfile
github "groue/GRDB.swift" ~> 0.61.0
$ carthage update
*** Cloning GRDB.swift
*** Checking out GRDB.swift at "v0.61.0"
*** xcodebuild output can be found in /var/folders/40/k86369xs6ql1tnvs7twcmgq00000gq/T/carthage-xcodebuild.6O0jFT.log
*** Building scheme "GRDBOSX" in GRDB.xcworkspace
*** Building scheme "GRDBCipherOSX" in GRDB.xcworkspace
*** Building scheme "GRDBCipheriOS" in GRDB.xcworkspace
*** Building scheme "GRDBiOS" in GRDB.xcworkspace
(snip: some warning)
$ ls -1 Carthage/Build/Mac/
GRDB.framework
GRDB.framework.dSYM
GRDBCipher.framework
GRDBCipher.framework.dSYM
```

Can you give more context?

**Comment by skreutzberger** [comment]
I tried it now with different carthage update calls (with and without platform) but it still does not work. Here a screenshot
<img width="834" alt="screenshot 2016-05-11 at 10 49 00" src="https://cloud.githubusercontent.com/assets/564725/15175367/39098050-1766-11e6-853f-0f3efcaa200c.png">

In the log file it says:
```
checking for library containing fdatasync... none required
checking for library containing dlopen... none required
configure: creating ./config.status
config.status: creating Makefile
config.status: creating sqlcipher.pc
config.status: creating config.h
config.status: executing libtool commands
make: *** No rule to make target `/Users/sebastian/...PATHTOPROJECT...', needed by `Makefile'.  Stop.
Command /bin/sh failed with exit code 2
```

**Comment by skreutzberger** [comment]
Interestingly it works without any issues if I download the project and build the OSX target by myself.

**Comment by groue** [comment]
The building of the GRDBCipher frameworks have a long history of trouble with Carthage (previous issue: https://github.com/groue/GRDB.swift/issues/41).

GRDBCipher needs to build sqlite from scratch, with a Makefile. The issue used to be that environment variables were not properly set, causing make to fail. I'm not even sure of the actual responsible of those issues: is it Carthage, Xcode, the build tools? Finding a workaround has been everything but trivial.

But in your case, I'm not sure this is the same issue, even though make is involved again.

My advice: try to activate the most verbose flags, and open the sharpest eye. I'll try to help you investigate. But until your trouble can be reproduced, my efficiency will be fairly limited.

**Comment by skreutzberger** [comment]
Understood. To save time I will embed the framework directly and try to find the issue later.

**Comment by groue** [comment]
All right @skreutzberger. I'll be there when you come back!

**Comment by simme** [comment]
I'm also having issues using GRDB with Carthage. This seems to be the failing step:

```
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace -scheme GRDBCipheriOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/TransactionObserver.playground' in workspace '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/JSONSynchronization.playground' in workspace '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/DatabaseTimestamp.playground' in workspace '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/Tour.playground' in workspace '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/UserDefaults.playground' in workspace '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/GRDB.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/simme/Projects/MyProject/Carthage/Checkouts/GRDB.swift/Playgrounds/Record.playground' in workspace '/Users/simme/Projects/MyProject/Checkouts/GRDB.swift/GRDB.xcworkspace'.
```

Builds just fine if I embed the project file in my Xcode project. I'm on the Swift3 branch.

Let me know if there's anything else I can provide to help with debugging. :) Embedding works for now, so no hurry.

**Comment by groue** [comment]
Hello @simme Thanks for the report. Something has to be done with Carthage, I agree. The setup is too fragile.
