### ISSUE TITLE
Question: FetchedRecordsController

### ISSUE THREAD

**Issue by embassem** [groue/GRDB.swift#459]
what is the different between FetchedRecordsController and FetchRequest ?

**Comment by groue** [comment]
Hello @embassem,

A **request** is used to fetch values from the database.

For example, those are requests:

```swift
let request1 = Player.all()
let request2 = Player.filter(key: 1)
let request3 = Player.filter(Column("score") >= 1000)
let request4 = Player.select(max(Column("score")), as: Int.self)
```

Those requests can fetch values when your app needs them:

```swift
// Let's fetch values!
try dbQueue.read { db in
    let players: [Player] = try request1.fetchAll(db)
    let player: Player? = try request2.fetchOne(db)
    let numberOfGoodPlayers: Int = try request3.fetchCount(db)
    let maxScore: Int? = try request4.fetchOne(db)
}
```

Now, your app sometimes needs not only to fetch values, but also to be notified when the database is changed by another component of your app.

For example, you have a screen which displays the list of players stored in the database. And you also have a network request which loads a fresh list of players from the internet, and then saves them in the database.

It is interesting, in this case, to refresh the list on screen with the new players.

And this is where FetchedRecordsController can help. Given a request (as seen above), it can animate a table view when the results of the request change.

The **request** defines the values you want to fetch or observe. The **FetchedRecordsController** can track a request and notify your application when the results of the request are changed.
