### ISSUE TITLE
Full-text Search

### ISSUE THREAD

**Issue by skreutzberger** [groue/GRDB.swift#46]
It is a must-have requirement for my app and as far as I understand SQLite it is somehow already built-in. I know how to use it in SQLite.swift and already implemented it there ([documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#full-text-search)) but I would prefer GRDB over SQLite.swift because it is more light-weight and also seems to be more actively maintained.

I want to index a longer message string for log entries with full-text search. For that to accomplish I need to be able to create a VirtualTable which stores the reference ID of the entries table and the message text with .FTS4

In SQLite.swift I did the following line:

`try db.run(table.create(.FTS4([cols.entriesID, cols.message], tokenize: .Porter)))`

What do I need to do to make it work with GRDB?

**Comment by groue** [comment]
Hello @skreutzberger.

```swift
try db.execute("CREATE VIRTUAL TABLE someTableName USING fts4(entriesID, message, tokenize=porter)")
```

I'm urging you to read https://www.sqlite.org/fts3.html.

**Comment by groue** [comment]
And thanks for the compliments :-) Yes GRDB is simple, maintained, actively used, and focused on productivity. This is also why there is no full-text support yet: the topic is much wider than SQLite.swift had you think. SQLite.swift oversimplifies some aspects of SQLite, full text search in particular, and this is not a trend I want to follow. I really advise you to have a full read of https://www.sqlite.org/fts3.html, and make your own opinion.

**Comment by skreutzberger** [comment]
Awesome! thanks for sharing your vision & philosophy for the project, I strongly endorse that. I agree that SQLite.swift is "abstracting away" many things which makes it actually much harder to learn and understand. I don’t like frameworks which want to solve a problem by hiding the real problem and adding some magic which takes much more time to understand than the underlying problem itself.

**Comment by groue** [comment]
I'm glad we agree: GRDB is the toolkit for you 😄
