### ISSUE TITLE
Self-association not loading data

### ISSUE THREAD

**Issue by igorkulman** [groue/GRDB.swift#466]
### What did you do?

Using GRDB I have a `messages` table

```swift
try db.execute(
            "CREATE TABLE IF NOT EXISTS \(MessagesTableDescription.tableName) (" +
                "\(Columns.threadId.name) TEXT NOT NULL , " +
                "\(Columns.messageId.name)  TEXT NOT NULL, " +
                "\(Columns.timestamp.name)  INTEGER NOT NULL, " +
                "\(Columns.messageType.name)  INTEGER NOT NULL, " +
                "\(Columns.fromUserId.name)  TEXT, " +
                "\(Columns.body.name)  TEXT, " +
                "\(Columns.messageState.name)  INTEGER NOT NULL, " +
                "\(Columns.attachmentData.name)  TEXT, " +
                "\(Columns.attachmentType.name) INTEGER, " +
                "\(Columns.attachmentUploadState.name)  INTEGER, " +
                "\(Columns.statusMessageData.name)  TEXT, " +

                "PRIMARY KEY (\(Columns.threadId.name), \(Columns.messageId.name)))"
        )
```

where I later added a new field `replyTo` as part of a migration

```swift
try db.alter(table: MessagesTableDescription.tableName, body: { t in
    t.add(column: MessagesTableDescription.Columns.replyTo.name, .text).indexed()
})
```

This `replyTo` field contains the `messageId` of the "original" message that the given message is a reply to.

I added the association using an extension

```swift
extension MessageModel {
    static let replyToForeignKey = ForeignKey([MessagesTableDescription.Columns.replyTo.name], to: [MessagesTableDescription.Columns.messageId.name])
    static let replyTo = belongsTo(MessageModel.self, using: replyToForeignKey)
}
```

To load the data I created a model

```swift
struct MessageRelationModel: FetchableRecord, Decodable {
    var message: MessageModel
    var replyTo: MessageModel?
}
```

That I load using

```swift
var query = MessageModel.including(optional: MessageModel.replyTo).filter(MessagesTableDescription.Columns.threadId == thread.threadId)
...
let data = try MessageRelationModel.fetchAll(db, query)
```

### What did you expect to happen?

I expected to get a list of `MessageRelationModel` with the `replyTo` property filled in where `replyTo` is not null on the message. Basically I expected the join to work.

### What happened instead?

The `replyTo` property is always empty on `MessageRelationModel` if when `replyTo` DB field is filled in and has a valid value.

The generated SQL query is

```sql
SELECT "messages1".*, "messages2".* FROM "messages" "messages1" LEFT JOIN "messages" "messages2" ON ("messages2"."message_id" = "messages1"."reply_to") WHERE ("messages1"."thread_id" = 'ZHfpL5EooKbJUpvx4zcmgm') ORDER BY "messages1"."timestamp" DESC LIMIT 15
```

I guess the problem is both tables have columns of the same names in the resulting data

### Environment

**GRDB flavor(s):** (GRDB, GRDBCipher, GRDBCustom?)
GRDBCipher
**GRDB version:**
v3.4.0
**Installation method:** (CocoaPods, SPM, manual?)
Carthage
**Xcode version:**
10.1
**Swift version:**
4.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
iOS
**macOS version running Xcode:**
10.13.6

**Comment by groue** [comment]
Hello @igorkulman,

If I understand well, the SQL looks correct, but the `replyTo` property of MessageRelationModel is not populated.

I have a slight idea of the problem, but I can't be 100% sure. Yet here is my interpretation:

For the `replyTo` property to be filled, the association that feeds it (MessageModel.replyTo) must have the "replyTo" key (those [association keys](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#the-structure-of-a-joined-request) are what allows database rows to match Codable keys).

Your current definition of MessageModel.replyTo is:

```swift
extension MessageModel {
    static let replyToForeignKey = ForeignKey([MessagesTableDescription.Columns.replyTo.name], to: [MessagesTableDescription.Columns.messageId.name])
    static let replyTo = belongsTo(MessageModel.self, using: replyToForeignKey)
}
```

It's all good, but MessageModel.replyTo has the default key, which is the name of the linked table ("messages"). Because of that, MessageRelationModel doesn't find its "replyTo" coding key. And you end up with a nil `replyTo` property.

To fix this, give MessageModel.replyTo the "replyTo" key:

```swift
extension MessageModel {
    static let replyTo = belongsTo(MessageModel.self, using: replyToForeignKey).forKey("replyTo")
}
```

If you do not like using raw strings, here is a more robust variant, that uses the target CodingKey:

```swift
// Exactly the same as today
extension MessageModel {
    static let replyToForeignKey = ForeignKey([MessagesTableDescription.Columns.replyTo.name], to: [MessagesTableDescription.Columns.messageId.name])
    static let replyTo = belongsTo(MessageModel.self, using: replyToForeignKey)
}

extension MessageRelationModel {
    static func filter(thread: Thread) -> QueryInterfaceRequest<MessageRelationModel> {
        let replyTo = MessageModel.replyTo.forKey(CodingKeys.replyTo) // Use CodingKey instead of a string
        return MessageModel
            .including(optional: replyTo)
            .filter(MessagesTableDescription.Columns.threadId == thread.threadId)
            .asRequest(of: MessageRelationModel.self)
    }
}

// Fetch
let models = try MessageRelationModel.filter(thread: thread).fetchAll(db)
```

**Comment by groue** [comment]
Also, it looks like the [Self Joins](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#self-joins) documentation chapter needs to talk about this.

Thanks for pointing this out, @igorkulman!

**Comment by igorkulman** [comment]
Thanks, adding `.forKey("replyTo")` to the association works fine. 

Regarding the documentation, exactly, I was looking at the employee x manager sample, which should have the same problem and there was no mention about this.

**Comment by groue** [comment]
> Thanks, adding `.forKey("replyTo")` to the association works fine. 

Great!

> Regarding the documentation, exactly, I was looking at the employee x manager sample, which should have the same problem and there was no mention about this.

Yes, I'll do something about it.

If you ever have another issue when decoding associated requests, have a look at the [Debugging Joined Request Decoding](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#debugging-joined-request-decoding) chapter.
