### ISSUE TITLE
Playgrounds

### ISSUE THREAD

**Issue by ApplebaumIan** [groue/GRDB.swift#467]
### What did you do?
Tried to open the Swift Playground

### What did you expect to happen?
I expected the Playground to run out of the box after cloning the project

### What happened instead?
In Playgrounds it says no module "No such module 'GRDB'"  but the rest of the Xcode project works.

### Environment

**GRDB flavor(s):** (GRDB, GRDBCipher, GRDBCustom?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by Kirow** [comment]
@ApplebaumIan, you should build GRDBOSX target first

**Comment by groue** [comment]
Yes @Kirow. See this Twitter thread for some context: https://twitter.com/ApplebaumIan/status/1083599337668648960

@ApplebaumIan was having issues with running GRDB in an iPad playground. I admit I have no clue about this topic.
