### ISSUE TITLE
[Question] Association through a 3rd table

### ISSUE THREAD

**Issue by igorkulman** [groue/GRDB.swift#469]
I have a question about something I did not find in the documentation.

Imagine I have a table `threads` with `thread_id`, `users` with `user_id` and `subscription` with `thread_id`, `user_id` .. meaning a `thread` and an `user` and connected using another table.

Writing classic SQL I would write something like

```sql
SELECT threads.*, users*
FROM threads as t
LEFT JOIN subscriptions as s ON s.thread_id = t.thread_id
LEFT JOIN users as u ON s.user_id = u.user_id
```

Now I am trying to model it using GRDB. First a struct to hold the result

```swift
struct ThreadsQueryResult: FetchableRecord, Decodable {
        var thread: ThreadModel
        var subscriber: UserModel?
        ...
```

Now it seems logical to add the relation to the subscription model

```swift
extension ThreadSubscriptionModel {
    static let threadForeignKey = ForeignKey([ThreadSubscriptionTableDescription.Columns.threadId.name], to: [ThreadsTableDescription.Columns.threadId.name])
    static let thread = hasOne(ThreadModel.self, using: threadForeignKey)

    static let userForeignKey = ForeignKey([ThreadSubscriptionTableDescription.Columns.userId.name], to: [UsersTableDescription.Columns.userId.name])
    static let user = hasOne(UserModel.self, using: userForeignKey)
}
```

But when writing a query (it includes some other thing also)

```
var query = ThreadModel
                .including(optional: ThreadModel.group.filter(Column(GroupsTableDescription.Columns.isActive.name) == 1))
                .including(optional: ThreadModel.lastMessage.including(optional: MessageModel.replyTo).including(optional: MessageModel.fromUser))
                .including(optional: ThreadModel.lastUnreadAlertMessage.including(optional: MessageModel.replyTo).including(optional: MessageModel.fromUser))
```

I do not know how to actually do the join to do get the user through subscription.

I cannot just add `.joining(optional: ThreadSubscriptionModel.thread)` because it does not make much sense. 

I guess I need some way to join or include it from the thread side, but how?

**Comment by groue** [comment]
> I guess I need some way to join or include it from the thread side, but how?

Exactly.

**Associations must match the database schema**: user association must be declared on subscription, just as subscription association must be declared on thread (if I have understood your schema well).

Look at [Fetching Values from Associations ](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#fetching-values-from-associations) for an example of a request with two levels of associations.

I agree documentation is long, but it is on your side. Open a new issue if you have more question.
