### ISSUE TITLE
Generic parameter T could not be inferred (Swift 2.2)

### ISSUE THREAD

**Issue by skreutzberger** [groue/GRDB.swift#47]
I am using the latest version from master branch on the latest Xcode and database queue creation does work. Now I am stuck with my first execution call which somehow does not want to compile.

I saw that there was an issue with Swift 2.2 some weeks ago and it was fixed so I don’t know why that error occurs :(

<img width="817" alt="screenshot 2016-05-11 at 15 26 45" src="https://cloud.githubusercontent.com/assets/564725/15182510/2e89bd94-178d-11e6-8a6a-97e71b1456ca.png">

**Comment by skreutzberger** [comment]
sorry for my ignorance. I found the issue. it was the `return statement` which seems not to be allowed in the `inDatabase` block.

**Comment by groue** [comment]
Hello back @skreutzberger :-)

The inDatabase block can return a value, or not:

```swift
try dbQueue.inDatabase { db in
    try db.execute("...")
}

let id = dbQueue.inDatabase { db in
    try db.execute("INSERT ...")
    return db.lastInsertedRowId
}
```

I did not known that the Swift compiler was so picky when you don't use the returned value, as in your sample code!

**Comment by groue** [comment]
See https://github.com/groue/GRDB.swift#database-queues for an overview of DatabaseQueue usages.

**Comment by groue** [comment]
**Solution**

You may get this error when using DatabaseQueue.inDatabase, DatabasePool.read, or DatabasePool.write:

```swift
// Generic parameter 'T' could not be inferred
let x = dbQueue.inDatabase { db in
    let result = String.fetchOne(db, ...)
    return result
}
```

This is a Swift compiler issue (see [SR-1570](https://bugs.swift.org/browse/SR-1570)).

The general workaround is to explicitly declare the type of the closure result:

```swift
// General Workaround
let x = dbQueue.inDatabase { db -> String? in
    let result = String.fetchOne(db, ...)
    return result
}
```

You can also, when possible, write a single-line closure:

```swift
// Single-line closure workaround:
let x = dbQueue.inDatabase { db in
    String.fetchOne(db, ...)
}
```
