### ISSUE TITLE
DatabasePool doesn't work in physical device

### ISSUE THREAD

**Issue by KosratDAhmad** [groue/GRDB.swift#471]
### What did you do?

I have developed a CocoaPod dependency that works with predefined data in sqlite database so I used this library with **DatabasePool** connection 

### What did you expect to happen?

I have tested on iOS simulator it works properly 

### What happened instead?

but in the physical device it didn't work the **DatabasePool** connection return nill without any catch error but if I will use **DatabaseQueue** it will work properly.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 3.6.2
**Installation method:** CocoaPods
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.2

### Demo Project

https://github.com/KosratDAhmad/MuslimData

**Comment by groue** [comment]
Hello @KosratDAhmad,

> but in the physical device it didn't work the DatabasePool connection return nill without any catch error but if I will use DatabaseQueue it will work properly.

Your project sometimes uses `try?` when you access database ([example](https://github.com/KosratDAhmad/MuslimData/blob/34f661e5de25eeaf34a0feea84d7bbd045863c6a/MuslimData/Classes/DB%20Helper/DBHelper.swift#L21)). This returns nil and hide eventual errors.

Do use `try` instead. You will get a proper error that you will be able to analyse and understand.

**Comment by groue** [comment]
BTW, if your database is stored as a resource, make sure you read the [How do I open a database stored as a resource of my application?](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-open-a-database-stored-as-a-resource-of-my-application) FAQ.

**Comment by KosratDAhmad** [comment]
Thank you very much @groue I have added the configuration parameter to the **DatabasePool** it works
