### ISSUE TITLE
Using QueryInterfaceRequest with External FTS table

### ISSUE THREAD

**Issue by herlihalim** [groue/GRDB.swift#477]
### What did you do?

This is a question.

I'm trying to do querying external content using FTS, there are 2 examples given, one in https://github.com/groue/GRDB.swift#external-content-full-text-tables and the other one is in WWDC companion app. However, both of them are using raw SQL as the way to do it.

### What did you expect to happen?

Able to join the table for FTS using QueryInterfaceRequest so the API is nicer and reusing a lot of nice things already provided by QueryInterfaceRequest.

Wondering whether it's a possibility (and the example is just out of date), and if it's whether the example can be updated.

### What happened instead?

The need to write raw SQL.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** . 3.6.2
**Installation method:** CocoaPods
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) iOS
**macOS version running Xcode:** 10.14.2

**Comment by groue** [comment]
Hello @herlihalim,

> I'm trying to do querying external content using FTS [...] Both examples are using raw SQL as the way to do it.

This is true.

> **What did you expect to happen?**
>
> Able to join the table for FTS using QueryInterfaceRequest so the API is nicer and reusing a lot of nice things already provided by QueryInterfaceRequest.

As you noticed, this area has not been explored yet 😅 

It is possible to do what you need, using [Associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md).

You will find below some sample code which explores a few techniques. I hope one of them will match your needs:

<details>
<summary>Sample Code</summary>

```swift
// MARK: - Setup

let dbQueue = DatabaseQueue()

try! dbQueue.write { db in
    try db.create(table: "person") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
    }
    
    try db.create(virtualTable: "personFullText", using: FTS4()) { t in
        t.synchronize(withTable: "person")
        t.column("name")
    }
    
    try db.execute("INSERT INTO person (name) VALUES (?)", arguments: ["Arthur"])
    try db.execute("INSERT INTO person (name) VALUES (?)", arguments: ["Barbara"])
}

struct Person: Codable, FetchableRecord, MutablePersistableRecord {
    var id: Int64?
    var name: String
    
    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
}

// MARK: - Raw SQL (you know this already)

try! dbQueue.read { db in
    let pattern = FTS3Pattern(matchingAllTokensIn: "Arthur")
    let sql = """
        SELECT person.*
        FROM person
        JOIN personFullText
          ON personFullText.rowid = person.rowid
         AND personFullText MATCH ?
        """
    let persons = try Person.fetchAll(db, sql, arguments: [pattern])
    print("Raw SQL : \(persons.map { $0.name })")
}

// MARK: - Query Interface + SQL Snippet

extension Person {
    // Declare a convenience record...
    struct FullText: TableRecord {
        static let databaseTableName = "personFullText"
    }
    // ... and the association that can generate SQL joins
    static let fullText = hasOne(FullText.self, using: ForeignKey([Column.rowID], to: [Column.rowID]))
}

try! dbQueue.read { db in
    let pattern = FTS3Pattern(matchingAllTokensIn: "Arthur")
    let fullText = Person.fullText.filter(sql: "personFullText MATCH ?", arguments: [pattern])
    let request = Person.joining(required: fullText) // .filter(...).order(...)
    let persons = try request.fetchAll(db)
    print("Query Interface + SQL snippet : \(persons.map { $0.name })")
}

// MARK: - Query Interface + Extension

extension HasOneAssociation where RowDecoder == Person.FullText {
    // This method should be provided by GRDB.
    // Until then, do it by hand.
    func matching(_ pattern: FTS3Pattern?) -> HasOneAssociation {
        return filter(sql: "personFullText MATCH ?", arguments: [pattern])
    }
}

try! dbQueue.read { db in
    let pattern = FTS3Pattern(matchingAllTokensIn: "Arthur")
    let request = Person.joining(required: Person.fullText.matching(pattern)) // .filter(...).order(...)
    let persons = try request.fetchAll(db)
    print("Query Interface + extension : \(persons.map { $0.name })")
}
```

</details>

There is surely room for improvements.

> Wondering whether it's a possibility (and the example is just out of date), and if it's whether the example can be updated.

Are the examples not working?

**Comment by herlihalim** [comment]
Ah, thank you very much, I'll try this out. I did try Association, but I incorrectly setup the hasOne association, this makes it clear. I'll try again and let you know. Cheers!

**Comment by groue** [comment]
All right, @herlihalim. Happy GRDB!
