### ISSUE TITLE
Correct mechanism to load aggregates?

### ISSUE THREAD

**Issue by schveiguy** [groue/GRDB.swift#49]
Simple aggregate case, I have an array of items.

```SQL
CREATE TABLE container (id INTEGER PRIMARY KEY)
CREATE TABLE item (container_id INTEGER, name TEXT, val INTEGER)
```

So I have two structs to model this:

```swift
struct Item
{
   var value : Int64
   var name : String
}

struct Container
{
    var id : Int64
    var items : [Item]
}
```

I can apply RowConvertible to each of these, and I can then query them from the DB. But I am not sure of the correct way to construct the aggregate. The Container type really needs all the rows of the items in order to truly construct itself. But its row basically is just the id. Plus, I'm not sure from reading the docs if GRDB supports running another query (say, to get the items for a specific row) while an existing query is running (say, to get the containers in the db). I also can't really do this from RowConvertible interface as there is no mechanism to run a new query.

What is the recommended way to handle this situation?

**Comment by groue** [comment]
Hello @schveiguy, I'm glad to see you again!

> I can apply RowConvertible to each of these, and I can then query them from the DB. But I am not sure of the correct way to construct the aggregate. The Container type really needs all the rows of the items in order to truly construct itself. But its row basically is just the id.

So... You want an array of containers whose items are populated. Right?

> Plus, I'm not sure from reading the docs if GRDB supports running another query (say, to get the items for a specific row) while an existing query is running (say, to get the containers in the db).

That's an excellent question. I think SQLite supports it, and GRDB as well. Yet this may, or may not, be the best way to load your containers (read on).

> I also can't really do this from RowConvertible interface as there is no mechanism to run a new query.

Correct. RowConvertible is a good fit when one row matches one model. And this is not what we need.

Here is how I tackle the container / items loading these days. I don't use RowConvertible, because it is not the correct tool for the job. Instead, I write a custom loading method. And I run a single SQL query, because running a single query is better than running N + 1 queries (the list of containers + 1 query per container):

```swift
// Assume the following schema:
//
// CREATE TABLE containers (
//   id INTEGER PRIMARY KEY
// );
// CREATE TABLE items (
//   containerID INTEGER NOT NULL REFERENCES containers(id)
//   name TEXT NOT NULL
// );
// CREATE INDEX itemsByContainerID ON items(containerID);
struct Item
{
   var name : String
}

struct Container
{
    var id : Int64
    var items : [Item]
}

extension Container
{
    /// Return all containers, sorted by id, with items prefilled
    class func fetchAllWithItems(db: Database) -> [Panelist]
    {
        var containers: [Container] = []
        let sql = "SELECT containers.*, items.name " +
            "FROM containers " +
            "LEFT JOIN items " +
            "ON items.containerID = containers.id " +
            "ORDER BY containers.id"
        for row in Row.fetch(db, sql) {
            // Create new container unless this row has the same container ID.
            let id: Int64 = row.value(named: "id")
            if let container = containers.last where container.id == id {
            } else {
                let container = Container(row)
                containers.append(container)
            }
            
            // Append the item
            if let name: String = row.value(named: "name") {
                containers.last!.items.append(Item(name: name))
            }
        }
        return containers
    }
}
```

And there I go: `Container.fetchAllWithItems(db)` returns my containers, prepopulated with their items.

**Comment by schveiguy** [comment]
OK, thanks. I can probably work with that. What I really want is a way to fetch containers, the items are really never fetched or stored by themselves (indeed, I don't even want to use a unique id there).

The single query may work OK with one array, but with 2 arrays or more I think you get combinatorical explosion. I think for most cases in my code, I'm only going to fetch one array at a time, so this will probably be fine. Thanks!

**Comment by groue** [comment]
> OK, thanks. I can probably work with that. What I really want is a way to fetch containers, the items are really never fetched or stored by themselves (indeed, I don't even want to use a unique id there).

You'll see that items have no unique id in my assumed schema above.

> The single query may work OK with one array, but with 2 arrays or more I think you get combinatorical explosion. I think for most cases in my code, I'm only going to fetch one array at a time, so this will probably be fine.

If you have already used [ActiveRecord associations](http://guides.rubyonrails.org/association_basics.html) or similar, then you may well look at them with envy :-)

I know that support for associations is lacking today in GRDB. Maybe I'll eventually be able to ship something that is not too lousy. Or maybe not :-)

> Thanks!

You're welcome Steven!

**Comment by schveiguy** [comment]
I dabbled a bit in Ruby on Rails, and still don't quite get it :) But I'm also quite a novice to ORM systems, so I don't know any of the accepted practices either. To be honest, I just wanted something better than FMDB :) Thanks again.

**Comment by groue** [comment]
ActiveRecord shines at generating efficient SQL when you load a complex graph of objects: http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

Of course it does not deal with all possible patterns - and once in a while it will betray you, and force you to dig deep in not-so-well-documented low-level APIs, and this can be very frustrating.

As you say, GRDB has niceties that FMDB doesn't have, and I'm personally OK when I have to write down some custom fetching logic. The way I see it is that when things turn complex, it is less painful when you had not lost contact with the low-level reality. Conversely, when you have been numbed by unicorn tools, it can be a big disappointment.

Until now I have always been able to make complex stuff look like simple stuff *at the call site*. This means that code gets gradually more complex without heavy refactoring. I'm quite happy with that. And I hope GRDB will follow you as nicely as it follows me these days! Take a look at those little articles when you have time: https://medium.com/@gwendal.roue/grdb-stories-993b9d016867

**Comment by egrimmius** [comment]
After trying out your suggested custom loading method, fetchAllWithItems, @groue, I'm getting a error of 

> Cannot use mutating member on immutable value: 'last' is a get-only property

> 

when trying to append a item to the Container.  What am I missing?

**Comment by groue** [comment]
@egrimmius: I don't know. You may not be using the same version of the Swift language. Maybe it never worked. It shouldn't be too hard to make it work for you.

**Comment by egrimmius** [comment]
You're right @groue, it wasn't too hard after all.  In a data heavy app, using a relationship heavy database, do you recommend creating a custom fetch method in all but the simplest model classes or structs?

**Comment by groue** [comment]
@egrimmius, I recommend a reading of the Associations paragraph of https://medium.com/@gwendal.roue/how-to-build-an-ios-application-with-sqlite-and-grdb-swift-d023a06c29b3#.2aa9m9gvv. The whole article is about good GRDB practices.

**Comment by egrimmius** [comment]
That article helped a lot, thanks @groue.  I've used a pattern very similar to that for years with SQL Server and .net.  I'm glad to see it promoted for swift and SQLite.  I'm currently making a switch from FMDB to GRDB, so I want to make sure I'm following best practices from the start.
