### ISSUE TITLE
BusyMode timeout: Time Scale?

### ISSUE THREAD

**Issue by recordandmix** [groue/GRDB.swift#498]
Just looking at BusyMode, trying to set up a timeout to deal with an occasionally slow read-only query from a database located on another computer on a local network.  

Looking at http://groue.github.io/GRDB.swift/docs/3.6/Classes/Database.html#/s:4GRDB8DatabaseC8BusyModeO, it references the SQLite documentation on busyMode (here: https://www.sqlite.org/c3ref/busy_timeout.html).  That doc says the handler uses milliseconds as its time scale.  Does GRDB use the same scale when specifying a timeout?  The sample code proposes (1) as the timescale -- since I'm dealing with delays of sometimes 3-5 seconds until a query is returned, I'm just hoping to double-check that I'm on the right order of magnitude in setting up my busyMode delay.  That is, 5 milliseconds isn't going to cut it -- but 5 seconds might.  Just trying to make sure I'm on the right scale.  Thanks!

**Comment by groue** [comment]
Hello @recordandmi!

`BusyMode.timeout` accepts a `TimeInterval`, that is to say a number of seconds. This number is converted to milliseconds for SQLite.

This should lift the ambiguity. I'll update the doc to make it clear. And next time I add an advanced SQLite feature, I'll hesitate changing the units!

**Comment by groue** [comment]
cc @Marus: this reminds me of our recent [conversation](https://github.com/groue/GRDB.swift/pull/497#discussion_r263357003) about SQLCipher page size. People who read the source documentation (SQLite or SQLCipher) are confused when they discover that GRDB does not use the same scales or types. Especially for advanced configuration where an unambiguous vocabulary is helpful. I think I'll switch `cipherPageSize` back to a regular Int.

**Comment by Marus** [comment]
That sounds fine to me.
