### ISSUE TITLE
Any example populating a tableview

### ISSUE THREAD

**Issue by kiwo12345** [groue/GRDB.swift#5]
Hello, 

Awesome work!

But do you have any example when populating a table view?

**Comment by groue** [comment]
You have a -- very simple -- example in the Demo iOS App that ships with the repository.

Check https://github.com/groue/GRDB.swift/blob/master/DemoApps/GRDBDemoiOS/GRDBDemoiOS/MasterViewController.swift

Is it enough for you?

**Comment by kiwo12345** [comment]
Perfect, thanks a lot!

**Comment by groue** [comment]
Cool! Happy GRDB!

**Comment by kiwo12345** [comment]
@groue do you have a branch for swift 1.2?

**Comment by groue** [comment]
No, and I don't plan to have any, since Swift 2 will very soon go out of the beta phase.
