### ISSUE TITLE
UPSERT support?

### ISSUE THREAD

**Issue by saormart** [groue/GRDB.swift#501]
I know that's "duplicated" issue on [UPSERT support?](https://github.com/groue/GRDB.swift/issues/315)
but that issue was opened on Feb 27, 2018.
According to the SQLite website, starting from SQLIte 3.24.0, released on June 4, 2018, there is finally a support for [UPSERT](https://www.sqlite.org/lang_UPSERT.html) clause!

Please let me know if it will be supported on GRDB!

Thanks!

**Comment by groue** [comment]
Hello @saormart!

> Please let me know if it will be supported on GRDB!

Nobody is working on it at the time, as far as I know! It may be you!

**Comment by groue** [comment]
All right, @saormart. I'm closing this issue until someone dives in. Support for UPSERT is listed in the [suggested contributions](https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md#suggested-contributions).
