### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _sqlite3_close_v2

### ISSUE THREAD

**Issue by sablib** [groue/GRDB.swift#51]
Crash on iOS 8.1 at [Database.deinit](https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/Database.swift#L147)

Same with SQLite.swift
[issue239](https://github.com/stephencelis/SQLite.swift/issues/239)

**Comment by groue** [comment]
Thanks for the report, @sablib. Hold on.

**Comment by groue** [comment]
@sablib: would you please use GRDB at commit 82fa559962bc87a433d8266626ee68b8573358aa, and tell me if your issue is solved?

**Comment by groue** [comment]
@sablib: GRDB v0.63.0 is out, with restored support for iOS before iOS 8.2. Thanks again for the report.
