### ISSUE TITLE
Deletes not reported by ValueObservation

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#512]
### What did you do?

I have this pretty crazy query that I run to generate "preview" records of couple of tables in my database:
```swift
private func deckPreviewQuery(locale: Locale) -> String {
    return """
    SELECT
        deck.id as deckId,
        ifnull(deckSetting.locale, '\(locale.identifier)') as locale,
        json_extract(deck.name, '$.' || ifnull(deckSetting.locale, '\(locale.identifier)')) as name,
        json_extract(deck.info, '$.' || ifnull(deckSetting.locale, '\(locale.identifier)')) as info,
        json_extract(card.files, '$.' || ifnull(deckSetting.locale, '\(locale.identifier)')) as coverImage,
        deck.weight as weight,
        MIN(deckCard.weight) as cardWeight

    FROM deckCard
        JOIN deck ON deckCard.deckId = deck.id
        JOIN card ON cardId = card.id
        LEFT JOIN deckSetting ON deckSetting.deckId = deck.id
    GROUP BY deckCard.deckId
    ORDER BY deck.weight
    """
}
```

I then have this method that creates a `ValueObservation` for that query.

```swift
    public func start() throws {
        observer.map(database.remove(transactionObserver:))
        observer = nil
        let queryRequest = SQLRequest<T>(sql: query)
        var observation = ValueObservation.trackingAll(queryRequest)
        observation.scheduling = .async(onQueue: queue, startImmediately: true)
        observer = try observation.start(in: database) { [unowned self] changes in
            do {
                try self.destination.write { db in
                    try changes.forEach { immutableRow in
                        var mutableRow = immutableRow
                        if let id = try T.idRequest(for: immutableRow).fetchOne(db) {
                            mutableRow.id = id
                        }
                        try mutableRow.save(db)
                    }

                }
                self.oldRows = newRows
            } catch {
                dump(error)
            }
        }
    }
```

It correctly reports all _changes_ but no _deletes_. Is the query somehow too complex for it to pick up deletes?

Rows in the table `deckCard` are automatically deleted thanks to foreign key constraints from the table `deck`.

### What did you expect to happen?

I expect the change callback to be called when a row in the `deck` table is removed.

### What happened instead?

Nothing.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** I'm on the 4.0 branch
**Installation method:** Manual
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.3

**Comment by groue** [comment]
Hello @simme,

Observation should not miss anything, regardless of the complexity of the observed request. Would you please share some sample code which reproduces the issue?

**Comment by groue** [comment]
Any update, @simme? My own tests did not reveal any issue here. I may just have missed something in your particular setup. Please bring something to eat, or I'll have to close this issue!

**Comment by simme** [comment]
Hey,

Sorry, I've had a very busy week. Will be doing some work on the project related to this issue tonight and this weekend. I'll try to reduce it to an example project. Might be there's something wrong with my setup.

**Comment by simme** [comment]
Here's a _very_ quick and dirty example I threw together from pieces of the app I'm working on. Since this is stitched together from parts of a work in progress it's not very pretty code. But it displays the issue.

The setup is fairly straight forward:

* There are two databases a `source` and a `destination`.
* The `source` has a somewhat "normalized" table structure and also contains columns with JSON that contains localizations for that particular column.
* The `destination` has "denormalized" tables that contain rows optimized for display. Data from several tables and no JSON columns.
* There's a `DatabaseQuerySyncer` that takes a references to both these databases and a query that it runs against the `source` to generate a record that is saved in the `destination`. It uses `ValueObservation` to monitor this query and update the `destination` whenever the database detects changes in the observed query.
* As you can see from the example app; adding a new row correctly reloads the table view, but deleting a row does not.

Hopefully its just me missing some implementation detail! :)

[ValueObservationIssue.zip](https://github.com/groue/GRDB.swift/files/3075238/ValueObservationIssue.zip)

**Comment by groue** [comment]
Thank you @simme for the sample project. It does not show any bug in GRDB.

When I launch the app, I see four items in the table view. When I delete one, I can see that the ValueObservation in DatabaseQuerySyncer.start is triggered, as expected.

The table view does not update, though.

And when I delete the same table view row again, I can see that AppDelegate.delete attempts to delete a database row which does not exist (the id was already deleted, and is no longer present). You can see existing decks by running `po Row.fetchAll(db, sql: "SELECT * FROM deck")` in the debugger.

I'm not sure how I can help, so I'm closing this issue. You have to review your database sync mechanism. Of course, you can ask any question you'll meet on your way.

**Comment by simme** [comment]
Ah, crap. Sorry, you're right! I got blinded by corrupted data. And brought that into the sample project too.

Sorry for wasting your time and thanks for the help!

**Comment by groue** [comment]
Dont worry, you're welcome!
