### ISSUE TITLE
[GRDB4] Error Swift 5 string interpolation

### ISSUE THREAD

**Issue by zdnk** [groue/GRDB.swift#524]
### What did you do?

Using string interpolation with `TableRecord` and/or `FetchableRecord`.

### What did you expect to happen?

String interpolation works amazingly :)

### What happened instead?

> Instance method 'appendInterpolation' requires that 'Allergen' conform to 'SQLExpressible'

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4
**Installation method:** CocoaPods
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** latest

### Code
```swift
extension Allergen: TableRecord, FetchableRecord {
    
    
    enum Columns: String, ColumnExpression {
        case productId = "product_id"
        case title
        case position
    }
    
    public static var databaseTableName: String {
        return "product_extras_allergens"
    }
    
    public static func delete(_ db: Database, productId: Int) throws {
        try db.execute(literal: """
            DELETE FROM \(self)
            WHERE \(Columns.productId) = \(productId)
        """)
    }
    
    public init(row: Row) {
        self.init(
            title: row[Columns.title],
            position: row[Columns.position]
        )
    }
    
    func insert(_ db: Database, productId: Int) throws {
        try db.execute(literal: """
            INSERT INTO \(self) (\(Columns.title), \(Columns.position), \(Columns.productId))
            VALUES (\(title), \(position), \(productId))
        """)
    }
    
}
```

**Comment by groue** [comment]
Hello @zdnk,

In the `delete` method, `self` is the Allergen type. It is interpolated as the table name.
 
But in the `insert` method, `self` is an Allergen instance. There is no obvious way to translate this record to SQL, so it is not supported by SQL interpolation. The error outputted by the Swift compiler is not very clear, unfortunately.

You have a few options:

Embed `type(of:self)`:

```swift
extension Allergen (
    func insert(_ db: Database, productId: Int) throws {
        try db.execute(literal: """
            INSERT INTO \(type(of: self)) (\(Columns.title), \(Columns.position), \(Columns.productId))
            VALUES (\(title), \(position), \(productId))
            """)
    }
}
```

Embed `Allergen.self`:

```swift
extension Allergen (
    func insert(_ db: Database, productId: Int) throws {
        try db.execute(literal: """
            INSERT INTO \(Allergen.self) (\(Columns.title), \(Columns.position), \(Columns.productId))
            VALUES (\(title), \(position), \(productId))
            """)
    }
}
```

Add support for  a new kind of interpolation (yes this code can run in your app):

```swift
extension SQLInterpolation {
    public mutating func appendInterpolation<Record: TableRecord>(tableOf record: Record) {
        appendInterpolation(type(of: record))
    }
}

extension Allergen {
    func insert(_ db: Database, productId: Int) throws {
        try db.execute(literal: """
            INSERT INTO \(tableOf: self) (\(Columns.title), \(Columns.position), \(Columns.productId))
            VALUES (\(title), \(position), \(productId))
            """)
    }
}
```

Maybe this last kind of interpolation should be built-in and ready-made. I admit I did not foresee your use case.

**Comment by groue** [comment]
No news is good news. Happy GRDB!

**Comment by groue** [comment]
@zdnk, [`...\(tableOf: record)...`](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md#sql-interpolation-reference) interpolation has shipped in GRDB 4. Thanks for reporting this issue!
