### ISSUE TITLE
.save(_: Database): REPLACE INTO support

### ISSUE THREAD

**Issue by zdnk** [groue/GRDB.swift#526]
Hello again,

I am repeatedly running into the fact that I need `REPLACE INTO` statement to be used in `save(_: Database)` method. Is there any plan to support it, or enable it, or am I just missing something somewhere?

Right now, I always end up writing my own `replace`/`insert` on the model.

**Comment by zdnk** [comment]
Found it in test: `static let persistenceConflictPolicy = PersistenceConflictPolicy(insert: .replace, update: .replace)`

**Comment by groue** [comment]
Documentation: https://github.com/groue/GRDB.swift/blob/master/README.md#conflict-resolution
