### ISSUE TITLE
Compare Date column in record if it's between 2 dates without using SQL queries

### ISSUE THREAD

**Issue by sameer4** [groue/GRDB.swift#527]
### What did you do?

I'm trying to fetch all records between 2 dates and was looking for non SQL queries way.
tried SQLExpressible

`ProdplanEntries.CodingKeys.date between currentDate and NextDate`

was hoping for some magic 😄 

### What happened instead?

compile error  😛

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 3.7.0
**Installation method:** CocoaPods
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.4

### Demo Project

No Need

**Comment by micpringle** [comment]
@sameer4 there’s an example of how to use BETWEEN in the README...

`Player.filter(("A"..."N").contains(initialColumn))`

Will generate the following SQL...

`SELECT * FROM player WHERE initial BETWEEN 'A' AND 'N'`

So you could try something like...

`YourModel.filter((currentDate...nextDate).contains(Column(“date”)))`

**Comment by sameer4** [comment]
oh sorry, my mistake... I thought it was generating an array from range to compare too

**Comment by groue** [comment]
Thank you @micpringle. This looks like a correct answer to @sameer4's question. I'm closing this resolved issue.
