### ISSUE TITLE
[Feature request] Providing prebuilt frameworks

### ISSUE THREAD

**Issue by igorkulman** [groue/GRDB.swift#529]
Looking at the GRDB 4 documentation only CocoaPods is supported for use with SQLCipher, not even manual install. 

With 3.x I used Carthage which was not supported but worked with a few tweaks but I cannot make it work for 4 because the build with SQLCipher is just a special podspec not a target in the project like with 3.x.

I created [a special project just to build GRDB + SQLCipher from CocoaPods as frameworks](https://blog.kulman.sk/using-pods-to-just-build-frameworks/) to use in my project because I do not want to use CocoaPods.

So I want to suggest a feature, providing prebuilt frameworks for every release, just as .framework files uploaded to the Github release. 

I noticed you use Travis CI so it can be probably done as a Travis job.

**Comment by groue** [comment]
Hello @igorkulman,

I can't afford supporting Carthage, as many other Carthage-related issues here will tell you.

> I noticed you use Travis CI so it can be probably done as a Travis job.

The difficulty lies in this "probably". Maintaining a production-grade library requires more effort then that.

Maybe you will become the long-running contributor who will keep Carthage support up-to-date, **for all GRDB users, supported platforms, Swift and Xcode versions**?

> I do not want to use CocoaPods.

You also see that this comes with a price.

**Comment by osteslag** [comment]
@igorkulman, I also don’t want to use CocoaPods. Even for consumers, these dependency frameworks (including Carthage) tend to cause a whole lot of pain (by being a dependency in and of itself, I guess). After having suffered long enough, I switched to git submodules, and while not perfect, it’s certainly simpler. Maybe you want to give it a try.

And I’m with @groue here. Even with my [tiny framework](https://github.com/osteslag/Changeset), these [issues](https://github.com/osteslag/Changeset/issues/53) come up, and when you’re not using Carthage yourself, it becomes unmanageable to maintain.

**Comment by igorkulman** [comment]
To be clear I was not asking for Carthage support, maybe I  wrote it in a way that is unclear. 

I was asking for pre-built frameworks being released with a release so you can just download them and use however you like without any dependency manager.

I of course get that it is not trivial to do.

About submodules, it is not always about what you want to use, sometimes it is also about what you have to use. I think using grdb 4 as a submodule would not help me, I would have to create a project that builds it with SQL cipher as it is not a target only podspec so I want for the solution linked in my first post.
