### ISSUE TITLE
Wrong number of statement arguments with "like '%?%'"

### ISSUE THREAD

**Issue by Timac** [groue/GRDB.swift#530]
### What did you do?

I am trying to perform some SQLite queries using the like operator.
For example I would like to delete all rows from mytable where the title column contains the string "something":

```
do {
	try databasePool.write { db in
		try db.execute(sql: "DELETE FROM mytable where title like '%?%'", arguments: ["something"])
	}
} catch let error as DatabaseError {
	debugPrint("Failed with error \(error)")
} catch {
	debugPrint("Failed with unknown error")
}
```

### What did you expect to happen?

The SQLite query looks valid. I would expect the query to delete all rows from mytable where the substring is found.

### What happened instead?

I see instead an error `SQLite error 21: wrong number of statement arguments: 1`
Note that if I use instead the following, I don't see the error and the expected rows are deleted:

```
try db.execute(sql: "DELETE FROM mytable where title like '%\(something)%'")
```

A similar issue occurs when using SELECT:

```
try db.execute(sql: "SELECT * FROM mytable where title like '%?%'", arguments: ["something"])
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.0 (revision 0e2daff329040ddf8694cdd1be1bc3e5ba0d4138)
**Installation method:** manual
**Xcode version:** 10.2.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.4

**Comment by groue** [comment]
Please see https://github.com/Nike-Inc/SQift/issues/9 for an identical issue. It is a misunderstanding of what SQLite parameters are.

**Comment by Timac** [comment]
@groue Thanks a lot for the clarification!
Since I am not the first one asking this question and probably not the last one, I added a paragraph to the README to clarify this point.

See https://github.com/groue/GRDB.swift/pull/531

**Comment by groue** [comment]
That's lovely, @Timac! You're right, this is a FAQ :-) I'll soon look into your PR.

**Comment by sobri909** [comment]
It also works if you put the percent marks in the argument. 

```swift
let notes = Stalker.store.notes(
    where: "body LIKE ? AND deleted = 0 ORDER BY date DESC",
    arguments: ["%\(query)%"])
```
