### ISSUE TITLE
Problem in batch insert records

### ISSUE THREAD

**Issue by MrShafiee** [groue/GRDB.swift#532]
Hi @groue ,
Thanks for your great library, I have a problem in batch insert records while I make my queries in loop.
I use Xcode 10.2 and swift 5.0 .

You can see my code in below image:
[image of my code](http://oi67.tinypic.com/2dw4umt.jpg)

when I want pass studentsQueriesParams to db.execute() I get this error:

> Cannot convert value of type 'StatementArguments' to expected argument type 'StatementArguments?'

I searched the document and issues, and all of them were the same as me, what should I do?
Thanks

**Comment by groue** [comment]
Hello @MrShafiee,

This is very weird, but more a problem somewhere in the Swift code or compiler than a problem with GRDB. I'm sure you'll figure it out. Try to create an intermediate StatementArguments variable, it should help.

**Comment by MrShafiee** [comment]
Hi @groue ,
Thanks for your response, I check all parameters about GRDB library, swift version, Xcode compiler and finally found it's about **_GRDBCipher_** !!
when I use it and import GRDBCipher instead of GRDB I got above Swift Compiler Error and if I change it to GRDB everything is okey!

But I need encrypt my DataBase file, what is your suggestion? Do you have any experience about this issue?

Thanks.

**Comment by MrShafiee** [comment]
Oops,I found the problem!
In my database config file I _import GRDBCipher_ but in queries controller I _import GRDB_ , therefore I got that compiler error.
I changed both of the to _import GRDBCipher_ and everything work perfectly.
I share it here maybe help other persons.

Thanks

**Comment by groue** [comment]
Yes you caught it! You don't need to build GRDB either. GRDBCipher is a standalone library that does not need support from the core GRDB.
