### ISSUE TITLE
Documentation: Order by joined/included association

### ISSUE THREAD

**Issue by zdnk** [groue/GRDB.swift#536]
Hello,

It would be nice to document best/correct practice for ordering the result set by joined/included table/relationship/association.

**Comment by groue** [comment]
Hello @zdnk,

Do you have any specific question that is not answered in the [Sorting Associations ](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#sorting-associations) chapter?

**Comment by zdnk** [comment]
My bad, missed that one. Sorry and thanks :)
