### ISSUE TITLE
Xcode 11 beta & SPM build errors

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#544]
GRDB version 4.0.1 does not integrate well with SPM in Xcode 11 beta iOS apps. You'll get errors related to method availability.

The fix is currently in the [development](https://github.com/groue/GRDB.swift/tree/development) branch. Update your Package.swift file:

```swift
let package = Package(
  dependencies: [
    .package(url: "http://github.com/groue/GRDB.swift", .branch("development")),
  ]
)
```

The development branch contains other changes that will eventually ship with [GRDB 4.1](https://github.com/groue/GRDB.swift/milestone/8).

**Comment by groue** [comment]
Update: https://github.com/openbitapp/GRDB.swift/commit/b6f988194c52a2f6113348e992099949cd85c5bf might be a better solution without breaking change.

**Comment by groue** [comment]
Fixed by #546.

**Comment by robcas3** [comment]
Hi, sorry to bother you. I find out that the fix I submitted is a really hacky one and not really elegant.
Since [this has been implemented in Swift 5](https://github.com/apple/swift-evolution/blob/master/proposals/0236-package-manager-platform-deployment-settings.md), i can resubmit a pull request to make it more elegant and up to date with the newest standards. Let me now if you are interested.

**Comment by groue** [comment]
Hello @robcas3. You will never bother me with your good will :-)

GRDB claims support for Swift 4.2, and will have to do so until GRDB 5. We thus can not use the PackageDescription API Version 5 yet, which is the one that introduces [supported platforms](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#supportedplatform).

When we can upgrade Package.swift to `// swift-tools-version:5.0`, then yes, we will do exactly as you suggest!

#546 was just perfect, because it fixed the issue without breaking compatibility with Swift 4.2 👍

**Comment by groue** [comment]
I know SPM will only become mainstream when Xcode 11 is out of beta. I will not be stubborn: if we really have to force Swift 5 with SPM, I'll be able to defend this breaking change :she . But if we can move on and still support 4.2, let's just do it!

**Comment by robcas3** [comment]
Oh, right, I forgot about PackageDescription API Version and its impact to Swift version compatibility 😓
Alright then, we'll wait until GRDB 5! 

I completely agree with you. Let's be nice to those who can't update the Swift version!

Thank you 🙂

**Comment by groue** [comment]
GRDB 4.1.1 has been released, which fixes this issue.
