### ISSUE TITLE
Question about iCloud sync

### ISSUE THREAD

**Issue by ahmedk92** [groue/GRDB.swift#547]
HI @groue , Thanks for the amazing library!

I have a general question though, not an issue with GRDB.

Is it safe to put a writable sqlite database file in the Documents directory in iOS without turning off sync?

I know this question is (in)famous. But if you trace relevant discussions, you'll find that there are two parties on the subject; some say it's OK, and the others say it will get corrupted.

So, What's your take?

Thanks!

**Comment by groue** [comment]
Hello @ahmedk92, thank you!

Your question is a little too tough for me.

I know iOS ships with an Apple-customized build of SQLite. And I know iOS sometimes [messes](https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-355063368) with the life of SQLite files. I also know GRBD does not uses any NSFileCoordinator at all (in case this would be relevant in any way to your question).

But this does not help me answering your question, unfortunately. Maybe one of those "two parties" sounds more trustable than the other?

**Comment by ahmedk92** [comment]
Indeed it's tough. I'll try to investigate this even more. I was just looking for a quick-and-dirty iCloud sync without having to build a full-blown CloudKit sync stack. However, CloudKit seems to be the safest approach.

Thanks for the fast reply!

**Comment by groue** [comment]
CloudKit is another subject I'm clueless about. But I'm watching https://github.com/mentrena/SyncKit because it looks well maintained and robust. It supports Core Data and Realm. I wonder if it would be possible to add GRDB support to it.
