### ISSUE TITLE
Swift Enums as columns for structs

### ISSUE THREAD

**Issue by Querschlag** [groue/GRDB.swift#557]
### What did you do?

I used the example for [Swift Enums](https://github.com/groue/GRDB.swift#swift-enums) to create a record struct with enums as columns.

### What did you expect to happen?

Successful compilation.

### What happened instead?

Swift compiler error: 
`Type 'Wine' does not conform to protocol 'Decodable'`
`Type 'Wine' does not conform to protocol 'Encodable'`

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.0.1
**Installation method:** CocoaPods
**Xcode version:** 11.0 beta
**Swift version:** 5.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.5

### Demo Project

```swift
enum Color : Int {
    case red, white, rose
}

enum Grape : String {
    case chardonnay, merlot, riesling
}

// Declare empty DatabaseValueConvertible adoption
extension Color : DatabaseValueConvertible { }
extension Grape : DatabaseValueConvertible { }

struct Wine: Codable, MutablePersistableRecord, FetchableRecord {
    
    var id: Int64?
    var created: Date
    var color: Color
    var grape: Grape
    
    func encode(to container: inout PersistenceContainer) {
        container["id"] = id
        container["created"] = created
        container["color"] = color
        container["grape"] = grape
    }
    
    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
}
```

**Comment by groue** [comment]
Hello @Querschlag,

Thanks to DatabaseValueConvertible, your Color and Grape enums are able to be stored or read from the database, that's great.

But you want your Wine struct to be `Codable`. Codable is a standard Swift protocol, and it means **more** than just dealing in the database. It also makes your Wine struct able to read/write JSON, for example. So you need to go further.

This quote from the [Apple documentation](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) explains your error:

> **Encode and Decode Automatically**
> 
> The simplest way to make a type codable is to declare its properties using types that are already Codable.

Conclusion: add Codable conformance to Color and Grape.
