### ISSUE TITLE
FTS5 Support using SPM

### ISSUE THREAD

**Issue by robcas3** [groue/GRDB.swift#565]
Hi, I'm trying to migrate all of my project dependencies to SwiftPackageManager but I'm stuck with this tricky problem.

I'm regularly using GRDB with FTS5 enabled when installed via cocoapods, that in the post_install script defines SQLITE_ENABLE_FTS5 compiler setting.
When I install GRDB using SPM and defining manually the swift flag in my project build settings seem like GRDB is not getting the compiler setting because the FTS5 related classes were missing.

I tried also this: I make my own Swift Package with tool version v5 and defined the setting like this: 
```swift 
...
dependencies: [
    .package(url: "https://github.com/groue/GRDB.swift.git", 
             .upToNextMajor(from: "4.1.1")),
],
...
.target(
    name: "TestPackage",
    dependencies: 
        "GRDB"
    ],
    swiftSettings: [
        .define("SQLITE_ENABLE_FTS5")
    ]
),
...
```

If I test with
```swift 
#if SQLITE_ENABLE_FTS5
#endif
```
it seems to work, but only inside the package source code; 
FTS5 classes were still missing.

Any thoughts?

Edit:

I tried to define this in my fork of GRDB
```swift 
swiftSettings: [
    .define("SQLITE_ENABLE_FTS5")
]
```
and did in fact work.
Now I can see FTS5 classes.

Seems like there is no real solution; 
Enabling FTS5 by default did work but is not what we want, I suppose.

**Comment by groue** [comment]
Hello @robcas3,

Thanks for investigating the topic. I'm currently in vacations and not quite able to look deeper now. Let's keep this issue open. And if you grab more pieces of useful information, please report them here!

**Comment by groue** [comment]
Hello again. I'm not sure I know any other way than the fork, as you have noticed.

I'm closing this issue because it does not look that anybody is performing any further investigation. Feel free to add any useful information you want to share with other GRDB+SPM users :-)

**Comment by popamihai** [comment]
```
swiftSettings: [
    .define("SQLITE_ENABLE_FTS5")
]
```
does not seem to work for me. I still get the "Cannot find FTS5 in scope" message. Are there any solutions?

**Comment by aehlke** [comment]
likewise - any tips?

**Comment by aehlke** [comment]
1. run `make SQLiteCustom` in fork
2. remove SQLiteCustom from `.gitignore` and commit the modified files

enjoy
