### ISSUE TITLE
PersistenceContainer public init

### ISSUE THREAD

**Issue by zdnk** [groue/GRDB.swift#573]
It would be nice to make the initializer public so it is possible to use for scenarios like these:

```
protocol PreparedInsertable {
    
    associatedtype Columns: CaseIterable
    
    static func insertStatement(_ db: Database) throws -> UpdateStatement
    func preparedInsert(_ db: Database, statement: UpdateStatement) throws
    
}

extension PreparedInsertable where Self: PersistableRecord, Self.Columns: RawRepresentable, Self.Columns.RawValue == String {
    
    static func insertStatement(_ db: Database) throws -> UpdateStatement {
        var sql = "INSERT INTO \(self.databaseTableName) ("
        
        let columns = Columns.allCases.map { $0.rawValue }
        
        sql += columns.joined(separator: ", ")
        sql += ") VALUES ("
        sql += columns.map { ":\($0)" }.joined(separator: ", ")
        sql += ")"
        
        return try db.cachedUpdateStatement(sql: sql)
    }
    
    func preparedInsert(_ db: Database, statement: UpdateStatement) throws {
        var container = PersistenceContainer()
        self.encode(to: &container)
        
        for column in Columns.allCases {
            // ...
        }
    }
    
}
```

**Comment by groue** [comment]
Hello @zdnk,

Could you please explain a little more what you are aiming at? I don't quite get the purpose.

Is it about performance? The built-in PersistableRecord protocol already uses cached prepared statements in its various persistence methods (update, insert, etc.) Do you expect significant performance improvements with your `PreparedInsertable` protocol? And if so, don't you think it would be better if we'd improve GRDB for all users, instead of keeping the improvements for your app only?

Is it about implementing a particular feature on top of GRDB? But what is this feature, exactly?

**Comment by zdnk** [comment]
Oops, I didnt know you are using prepared statements internally already. Sorry for that.
However this issue is basically about being able to leverage the GRDBs encode function to be used with custom built queries as well.

**Comment by groue** [comment]
> However this issue is basically about being able to leverage the GRDBs encode function to be used with custom built queries as well.

OK, but... The example you show is basically the same as the built-in `insert`, so I still don't get the point.

You know, exposing PersistenceContainer initializer would have several severe consequences:

- We could no longer make it a protocol in the future with minimal source-breaking changes.
- It would be difficult to make [this useful optimization](https://github.com/groue/GRDB.swift/blob/v4.1.1/GRDB/Record/PersistableRecord.swift#L755) available to users without exposing too much guts in the public API.

So I beg you, for the last time, to justify your request with more energy, by providing a convincing need for such a public initializer.

**Comment by zdnk** [comment]
I am sorry, I did not realize prepared statements are already being used by default with the pre-defined functions in GRDB. Now my request does not make sense for sure :)

**Comment by groue** [comment]
All right @zdnk. Let's close this issue, then. Maybe something has to be improved, but we still don't know what. Feel free to reopen this issue, or open a new one, whenever you have another question or suggestion!
