### ISSUE TITLE
Transaction over several RxSwift obersables

### ISSUE THREAD

**Issue by zdnk** [groue/GRDB.swift#579]
Hello,

I have another question.

The problem:
I am trying to to download and persist to SQLite 4 ~10MB files. The issues is these files contain data that reference each other across the files so I need to persist them in single transaction so the user experience is smooth.

The question:
I am using RxSwift fo API calls and everything else. I would like to call one endpoint, get the data and persist it, call another endpoint, persist. Meaning that the transaction basically needs to be open of the whole time the app is downloading and persisting the data.

I was thinking of something like
```swift
dbPool.write { db -> Observable<Void> in
  return api.get(..)
    .map { response in
      try response.save(db) // response is PersistableRecord
    }.flatMap {
      return api.get(..)
    }.map { anotherResponse in
       try anotherResponse.save(db)
    }
}
```

But I am having issue with threads obviously, the `map` is called on different thread so GRDB crashes and I am not sure about the proper way to synchronize it.

I hope you will understand my issue and be able to provide some guidance :)

**Comment by groue** [comment]
I do totally understand your question. It is very frequent that our server endpoints don't quite match our local database needs.

The general problem we have to solve is the following:

Given two server endpoints which return different but related data, we want our application to update its local database according to the server input, while maintaining a consistent state.

I have two strategies for dealing with such situation.

1. **Relaxed database consistency**

    Allow the database to contain columns that refer to inexistant rows, don't define the foreign keys that each endpoint, individually, doesn't allow to fully honor.

    This strategy has a few advantages: you can process the results of your endpoints in any order, and you can allow one endpoint to fail temporarily without ignoring the results of the other endpoint. Optimistic, the application knows that it will eventually succeed in loading of remote data it needs. Meanwhile, it displays the available local data.

    There are drawbacks, of course, because the app must be ready for missing references, in all its reads and writes.

    Yet I successfully deployed this approach in a recent app, with 5 or 6 related endpoints. All in all, it was not so difficult to deal with potentially missing links in the local database. The network layer was very simple: one network endpoint is one database transaction. I'm happy this rather unorthodox decision (drop *a few* foreign keys) would turn out so well, so that my tool belt has yet another trick now.

2. **Strict database consistency**

    Don't allow the database to contain columns that refer to inexistant rows with SQLite foreign keys.

    This strategy makes it easy to work with the local database, but it makes it difficult to deal with the server:

    1. You'll often need to process the results of your endpoints in a single transaction, and to process the results of your endpoints in a precise order (for example: parents first, children last).
    2. Endpoints can provide inconsistent data if the server state has changed between your two requests.
    
    This gives (excuse the quick and dirty Swift):

    ```swift
    Observable
        .zip(api.get1(...), api.get2(...))
        .map { (data1, data2) in
            try save(data1, data2)
        }
    ```

    In the save method, you again have the choice between different strategies in order to face with server inconsistencies:

    1. Fail whenever any piece of data is inconsistent
    2. In case of inconsistent data, retry loading both endpoints.
    3. Succeed partially: save consistent data, and ignore inconsistent one.

    I guess there are other ways to deal with those nasty cases.

Let me now quote a few sentences of yours:

> I would like to call one endpoint, get the data and persist it, call another endpoint, persist.

If this *sequence of events* is really what you want, then you need the **relaxed** database consistency. This will allow you to perform the two writes independently. And to allow the second endpoint to fail.

> these files contain data that reference each other across the files so I need to persist them in single transaction

If this sentence is true, then you can profit from the **strict** database consistency. But now the sequence has to be: call both endpoints, and persists them both in a single transaction.

I hope things are more clear now. I don't know what is the best solution for your app, but I'm sure you will make a wise choice ;-)

**Comment by zdnk** [comment]
I see, so basically theres no simple way to do this with Rx and strict database consistency?
Thats what I was afraid of :(

The complexity raises a little bit, because we are actually getting a diff from server which means we need to cleanup the data that were related to other that don't exist anymore.

**Comment by groue** [comment]
> I see, so basically theres no simple way to do this with Rx and strict database consistency?

Just make it no more simple than it has to be.

To put it in another way: everything would be so much simpler if the server would expose a **single** endpoint which is **guaranteed** to be consistent.

When it does not, well... the client has to deal with each and every assumption it can not rely on. It is more or less difficult, depending on the app.

**Comment by groue** [comment]
BTW: remember database access methods are *synchronous*:

```swift
dbPool.write { db in
    // Must access database now, not in any asynchronous way
    
    // OK:
    try db...
    
    someAsyncStuff(completion: {
        // NOT OK
        try db...
    })
}
```

**Comment by groue** [comment]
@zdnk, I suppose this discussion is ended, isn't it? I close this issue. Feel free to reopen if you have more questions.
