### ISSUE TITLE
Playground - EXC_BAD_INSTRUCTION if imported CoreLocation

### ISSUE THREAD

**Issue by Kirow** [groue/GRDB.swift#582]
https://github.com/groue/GRDB.swift/blob/d290102d9cb5c425fee7260034beaa997d581d86/Playgrounds/Tour.playground/Contents.swift#L54-L56

Need to change `import CoreLocation` to `import MapKit`. Not sure why.

**Comment by groue** [comment]
Hi @Kirow 

I do not witness this EXC_BAD_INSTRUCTION.

Please reopen a new issue, and *fill the template*, please. Thanks.
