### ISSUE TITLE
How to use custom values with GRDB?

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#589]
Hi @groue 
First things first, I'd like to say thank you for sharing this amazing tool with the community. I genuinely appreciate the effort and time invested. I don't normally open issues to ask questions about repos on github so I'm sorry in advance if I commit a mistake or forget about any info needed on making this question.

The thing is I'm not sure I understood the docs about DatabaseValueConvertible. I've been using GRDB to store and retrieve regular SQLite accepted types such as String, Int... But I'm wondering how would it be possible to store a custom value, let's say "Contact" in my chat app.

```
import GRDB

final class Contact: Record {
    let name: String
    let userId: Data

    enum Columns: String, ColumnExpression {
        case name, userId
    }

    override class var databaseTableName: String {
        return String(describing: self)
    }

    required init(row: Row) {
        name = row[Columns.name]
        userId = row[Columns.userId]
        super.init()
    }

    init(name: String, userId: Data) {
        self.name = name
        self.userId = userId
        super.init()
    }

    override func encode(to container: inout PersistenceContainer) {
        container[Columns.name] = name
        container[Columns.userId] = userId
    }
}
```

I want Contact to be a column of a Message table:

```
import GRDB

final class Chat: Record {
    // MARK: - Columns
    var id: Int64?
    let contact: Contact <-------------
    var timestamp: Int64

    enum Columns: String, ColumnExpression {
        case id, contact, timestamp
    }

    // MARK: - Properties
    override class var databaseTableName: String {
        return String(describing: self)
    }

    // MARK: - Init
    required init(row: Row) {
        id = row[Columns.id]
        contact = row[Columns.contact]
        timestamp = row[Columns.timestamp]
        super.init()
    }

    init(contact: Contact, timestamp: Int64) {
        self.id = nil
        self.contact = contact
        self.timestamp = timestamp
        super.init()
    }

    override func encode(to container: inout PersistenceContainer) {
        container[Columns.contact] = contact
        container[Columns.timestamp] = timestamp
        container[Columns.id] = id
    }
}

```
I checked a closed issue about DatabaseValueConvertible and it seems I should serialize/deserialize custom values?  I'm not really sure how would that be in my case. Could you give me a tip? 

I really appreciate your help. Thank you again!

**Comment by groue** [comment]
Hello @brunomunizaf,

Your Contact type is a record, which is stored in its own table. It is made of several *values*, each one of them stored in a column of this table.

The [DatabaseValueConvertible](https://github.com/groue/GRDB.swift/blob/master/README.md#custom-value-types) is dedicated to those *values* which can be stored in a single database column. For example, Int, String, Date conform to DatabaseValueConvertible. All are basic data types that can be represented as one of the fundamental SQLite values (int, double, string, data - and NULL).

DatabaseValueConvertible is not a good fit for records, which span several columns.

In your specific case, I assume that at the database level, in the schema, the table for chats *references* a row in the table for contacts.

Is it true? Then please check out the [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md). Please focus on the first chapter, which talks about the database schema. Make sure you get it right. Things will just flow from this fundamental starting point.

**Comment by brunomunizaf** [comment]
Hi @groue ,

I went throught the wiki and learned pretty much everything I needed. Thank you very much for your help and quick response.

Best,
Bruno.
