### ISSUE TITLE
multiple sections in uitableview

### ISSUE THREAD

**Issue by tanstaafl856** [groue/GRDB.swift#608]
re:  FetchedRecordsController collection view and multiple sections #500 
wondering if there is any progress or maybe workarounds yet for using sections / dictionaries. Thnx

### What did you do?

added an index/sections to a list of names in a subclassed tableview

### What did you expect to happen?

not crash when table cell item swiped and deleted

### What happened instead?

simulator app crashed with the following non-insightful error...
libc++abi.dylib: terminating with uncaught exception of type NSException

reloading the app reveals that *A* record was indeed deleted, but always 1st record in section 0

researching the issue revealed it just might not be possible [yet], but that use cases and demand might help...providing both

### Environment

**GRDB flavor(s):** (GRDB 4.4.0, SQLCipher 4.2.0)
**Installation method:** (CocoaPods)
**Xcode version:** (10.2)
**Swift version:** (Swift 5)
**Platform(s) running GRDB:** (iOS 12.4)
**macOS version running Xcode:** (10.14.5)

### Demo Project
since it seems to be a known issue, no demo app...just the code that forces a query result into a dictionary. 

    func buildDictionaryFromDB() {
        do {
            let array = try dbQueue.read { db in
                try Contact.fetchAll(db)
            }
            for row in array {
                print(row.name)
                let indexKey = String(row.name.prefix(1))
                if var indexValues = indexDictionary[indexKey] {
                    // if there're already entries in this section...append
                    indexValues.append(row.name)
                    indexValues.sort() // because they don't always come sorted...WTF
                    indexDictionary[indexKey] = indexValues
                } else {
                    // else add the first entry
                    indexDictionary[indexKey] = [row.name]
                }
            }
        } catch {print("ERROR setting up section data")}
        
        indexSectionTitles = [String](indexDictionary.keys)
        indexSectionTitles = indexSectionTitles.sorted(by: { $0 < $1 }) // again...not always sorted???
        }

**Comment by groue** [comment]
Hello @tanstaafl856 

> wondering if there is any progress or maybe workarounds yet for using sections / dictionaries. 

No progress I'm aware of on table view sections. My advice:

- Observe the database with GRDB. This gives you fresh database values.
- Perform your own grouping of those database values into sections. You know how to do that.
- If you need table view animations, use a dedicated library. These days, I'd recommend https://github.com/ra1028/DifferenceKit.

**Comment by tanstaafl856** [comment]
Got it. Thnx
