### ISSUE TITLE
UI stucks while writing in database

### ISSUE THREAD

**Issue by VickyPrajapati24** [groue/GRDB.swift#610]
I have used below code to insert records in the database. But it stucks UI when it commit statement executes.

try dbPool.writeInTransaction { db in
              let tableName = "ABC"
              for raw in arrValues {
                        try db.execute(literal: "INSERT INTO \(sql: tableName) VALUES \(raw)")
               }
    return .commit
}

So how I manage it so it won't stucks UI.

**Comment by groue** [comment]
Hello @VickyPrajapati24 

Database access methods like `read`, `write`, `writeInTransaction`, etc. block your current thread until they have performed your database tasks.

As a consequence, if they are called from the main thread, they block your UI.

If the database access take too much time, and creates undesired delay and lag in your user interface, consider calling them from some background thread, or using an [asynchronous database access method](https://github.com/groue/GRDB.swift/blob/master/README.md#asynchronous-apis) instead.

**Comment by VickyPrajapati24** [comment]
Hello @groue,
Thank you so much for Quick reply. I have tried to use asyncWrite method. But I am facing some issue "Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)". My project is developed in swift 5 and Xcode version is 10.2.1.

Please see the attached screenshot. I will be grateful for the quick help. Thanks in advance.

![Screenshot 2019-09-11 at 2 13 16 PM](https://user-images.githubusercontent.com/19743627/64682206-ba7a2880-d49e-11e9-9c0b-a519cadae146.png)

**Comment by groue** [comment]
@VickyPrajapati24, It looks like your application shadows the standard Result type, with two type parameters, with another Result type which has a single one. Try `Swift.Result<Int, Error>`.

**Comment by VickyPrajapati24** [comment]
It works. Thank you @groue. You are great.

**Comment by groue** [comment]
Happy GRDB!
