### ISSUE TITLE
Best way to perform conditional decoding of prefetched rows

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#612]
### What did you do?

I have a master - detail relationship which is decoded by the `init(row: Row)` constructor. 
The detail records are prefetched using the `.including(all: detailAssociation)` request construct. 

So the `init(row: Row)` is expecting to see a decoding key `details` for all those prefetched records. 

### What did you expect to happen?

Every works great when the request is actually prefetching those details records. 
However, in some specific cases, I do not want to prefetch those `detail` records. 

Currrently, If I don't, I get the following error: 
`Fatal error: missing key for prefetched rows 'details'`

I understand the issue is on my side but wanted to get some insights about how to handle such a case. 

Thanks

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.2.1
**Installation method:** CocoaPods
**Xcode version:** 10.2.1
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.14.5

**Comment by groue** [comment]
Hello @martindufort,

You can ask if there are prefetched rows named "details" before decoding them:

```swift
init(row: Row) {
    if row.prefetchedRows.keys.contains("details") {
        details = row["details"]
    } else {
        ... 
    }
}
```

The `prefetchedRows` property is not documented in the main README, because I did not foresee a use case like yours. See the [reference](http://groue.github.io/GRDB.swift/docs/4.4/Classes/Row/PrefetchedRowsView.html) for more information.

**Comment by martindufort** [comment]
Superb !!! Thanks for the quick reply.

**Comment by groue** [comment]
Happy GRDB!
