### ISSUE TITLE
[Q] What's the best practice to do associations in GRDB?

### ISSUE THREAD

**Issue by lastcc** [groue/GRDB.swift#613]
```swift
struct Author {
    var id: Int64
    var name: String
}

struct Book {
    var id: Int64
    var authorId: Int64?
    var title: String
}
```

How do I save the book and author in one go?

Let's say we want to create a new `book` and associate it with a new `author`.  First I will have to save the author first so that I can get the id of the author object. Then I'll create a book object and save again.

Is there a way to save both object in one transaction?

**Comment by groue** [comment]
Hello @lastcc,

You describe a correct say to insert an author and a book in the database (author first, and book next).

A way to save them both in a transaction is to wrap the two insertions in the `write` database access method, available on both database queues and pools:

```swift
try dbQueue.write { db in
    var author = Author(id: nil, name: "Ray Bradbury")
    try author.insert(db)
    var book = Book(id: nil, authorId: author.id!, title: "The Martian Chronicles")
    try book.insert(db)
}
```

For more information, check [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md).

**Comment by groue** [comment]
In other words: GRDB associations help when reading from the database. They can build database requests that involve several record types. But they do not come with any writing facilities at this point. So there is no "good practice" for modifying the database with associations.

**Comment by lastcc** [comment]
Thank you! I love GRDB!
