### ISSUE TITLE
ENABLE_PREUPDATE_HOOK already available ?

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#614]
Hi Gwendal,

As `ENABLE_PREUPDATE_HOOK` look available on iOS since (at least) 11.4, do we still need a custom SQLite build to use this behavior ?

**Comment by groue** [comment]
Hello @skrew,

I didn't now ENABLE_PREUPDATE_HOOK had turned available, thanks for the information!

Just make sure GRDB is compiled with `-D SQLITE_ENABLE_PREUPDATE_HOOK`.

If you use CocoaPods, add to your podfile:

```ruby
platform :ios, '11.4' # or above
pod 'GRDB.swift'

post_install do |installer|
  installer.pods_project.targets.select { |target| target.name == "GRDB.swift" }.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['OTHER_SWIFT_FLAGS'] = "$(inherited) -D SQLITE_ENABLE_PREUPDATE_HOOK"
    end
  end
end
```

**Comment by skrew** [comment]
Yes I was surprised to see that it existed (with the PRAGMA COMPILE_OPTIONS command) 

And, most surprised after looking on yours pages... You already listed it here: [https://github.com/groue/GRDB.swift/wiki/SQLite-versions](https://github.com/groue/GRDB.swift/wiki/SQLite-versions) :)

**Comment by groue** [comment]
As you see I did not read it very closely :-) And it's a chore to keep this page up to date... I'm late already!

**Comment by skrew** [comment]
I can update it if you want...

Also adding ATV

**Comment by groue** [comment]
Hey, why not! It's a wiki after all :-) Dont feel obliged in any way: you're not responsible for my own laziness :-D

**Comment by skrew** [comment]
I have no access to the wiki... How do you want the updates ? In a issue ?

BTW, back to the subject...
The `sqlite3.h` file (from the Xcode include folder) doesn't contain the `sqlite3_preupdate_hook` declaration... 
So it's not usable "like that"

I've added (just for testing purpose), in `grdb_config.h` file:

```
extern SQLITE_API void *sqlite3_preupdate_hook(sqlite3 *db, void(*xPreUpdate)(
                                                          void *pCtx,
                                                          sqlite3 *db,
                                                          int op,
                                                          char const *zDb,
                                                          char const *zName,
                                                          sqlite3_int64 iKey1,
                                                          sqlite3_int64 iKey2
                                                          ),
                                        void*
                                        );
extern SQLITE_API int sqlite3_preupdate_old(sqlite3 *, int, sqlite3_value **);
extern SQLITE_API int sqlite3_preupdate_count(sqlite3 *);
extern SQLITE_API int sqlite3_preupdate_depth(sqlite3 *);
extern SQLITE_API int sqlite3_preupdate_new(sqlite3 *, int, sqlite3_value **);
```

and implemented `func databaseWillChange(with event: DatabasePreUpdateEvent)` in my app to test... Seem OK 👌

**Comment by groue** [comment]
I'm happy you made it work, and thanks a lot for your investigation. It looks that we need a couple extra steps before we can update the doc about preupdate hook support!

**Comment by groue** [comment]
@skrew I have the same problem with the [SQLITE_ENABLE_SNAPSHOT](https://www.sqlite.org/c3ref/snapshot_get.html) option, that I wish to explore for #619. SQLite is compiled with this option, but `sqlite3.h` is incomplete :-/

**Comment by skrew** [comment]
@groue Have you tested with my method ? I don't know any other way to make it works.
With some conditional around declarations, it will works for all users (I will post an update of my app just to be sure Apple don't handle that as using "private api")

**Comment by groue** [comment]
Yes @skrew I did, and it works 👍 

I have been looking at some ways to permanently commit those extra declarations, and still support the various GRDB flavors and OS versions. Availability macros, Other C flags, etc, it's an experimental cocktail recipe!

**Comment by skrew** [comment]
Before tvOS 13 is out, there is infos from tvOS 12.4.1, for the wiki:

```
SQLite Version: 3.24.0
SQLite Compile Options: ["BUG_COMPATIBLE_20160819", "COMPILER=clang-10.0.1", "DEFAULT_CACHE_SIZE=128", "DEFAULT_CKPTFULLFSYNC", "DEFAULT_JOURNAL_SIZE_LIMIT=32768", "DEFAULT_PAGE_SIZE=4096", "DEFAULT_SYNCHRONOUS=2", "DEFAULT_WAL_SYNCHRONOUS=1", "ENABLE_API_ARMOR", "ENABLE_COLUMN_METADATA", "ENABLE_DBSTAT_VTAB", "ENABLE_FTS3", "ENABLE_FTS3_PARENTHESIS", "ENABLE_FTS3_TOKENIZER", "ENABLE_FTS4", "ENABLE_FTS5", "ENABLE_JSON1", "ENABLE_LOCKING_STYLE=1", "ENABLE_PREUPDATE_HOOK", "ENABLE_RTREE", "ENABLE_SESSION", "ENABLE_SNAPSHOT", "ENABLE_SQLLOG", "ENABLE_UNKNOWN_SQL_FUNCTION", "ENABLE_UPDATE_DELETE_LIMIT", "HAS_CODEC_RESTRICTED", "HAVE_ISNAN", "MAX_LENGTH=2147483645", "MAX_MMAP_SIZE=20971520", "MAX_VARIABLE_NUMBER=500000", "OMIT_AUTORESET", "OMIT_LOAD_EXTENSION", "STMTJRNL_SPILL=131072", "SUBSTR_COMPATIBILITY", "THREADSAFE=2", "USE_URI"]
```

**Comment by groue** [comment]
Thanks @skrew! Added to the [wiki](https://github.com/groue/GRDB.swift/wiki/SQLite-versions).

**Comment by groue** [comment]
@skrew, what is your integration technique? Do you use CocoaPods, or something else?

**Comment by skrew** [comment]
Yes, CocoaPods but i'm using SwiftPM too, since Xcode 11 (and apps that i'm ready to build with iOS 13 support)

**Comment by groue** [comment]
I think I have a CocoaPods solution. For SPM I'm clueless.

**Comment by groue** [comment]
Next version of GRDB will come with support for SQLITE_ENABLE_PREUPDATE_HOOK for CocoaPods, with a few extra configuration lines in the Podfile.

I was unable to find a satisfying equivalent setup for SPM. Volunteers are welcome.

This issue can be closed.

**Comment by kellyhuberty** [comment]
Just a warning for anyone who wants to use this option as is, I received this warning from ASC TestFlight review. Seems as though although this option is unofficially supported, it isn't publicly supported and you'll get a flag from ASC about it.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1676539/233790662-02f21972-8c23-4ae5-9473-056b8b268283.png">
