### ISSUE TITLE
FetchedRecordsController tracking changes calculation of IndexPaths

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#618]
### What did you do?

Hello again....

In my MacOS app, I'm using the `FetchedRecordsController` to track database changes to a collection of _Master_ objects. 

This tracking is used to animate the changes of rows within an associated `NSTableView`. 

### What did you expect to happen?
My initial request returns 4 records:
- master-1
- master-2 
- master-3
- master-4 

Then a background thread issues a network API call to get new updates for those records. 
This updates _master-2_ and _master-3_ within an ` . inTransaction( ` request. 

Those 2 records are then no longer part on the original request. 

Within the `trackChanges` method, I'm receiving the proper callbacks for a `.deletion` change.

One for each record with associated indexPath.
_master-2_ : IndexPath = [0, 1]
_master-3_ : IndexPath = [0, 2]

then this code is performed twice:

```
case .deletion(let indexPath):
	
     self.mainTableView.removeRows(at: IndexSet(integer:indexPath.item), withAnimation: NSTableView.AnimationOptions.slideLeft)
```

_master-2_ : is visually removed and slided left
_master-4_ : is visually removed and slided left

Was expecting _master-2_ **and** _master-3_ to be removed. 

How can I obtain an IndexSet with the proper indexPaths to be removed ?

so I can do all changes inline:
```
let deletedSet = IndexSet([indexPath1, indexPath2, indexPathN])
self.mainTableView.removeRows(at: deletedSet, withAnimation: NSTableView.AnimationOptions.slideLeft)
 ```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.2
**Installation method:** CocoaPods
**Xcode version:** 10.2.1
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hi @martindufort 

Would you please provide a reproducible sample code?

**Comment by martindufort** [comment]
Sure, let me update this issue with a sample project.... 

-- 
Martin Dufort

On September 17, 2019 at 13:47:22, Gwendal Roué (notifications@github.com) wrote:

Hi @martindufort

Would you please provide a reproducible sample code?

**Comment by martindufort** [comment]
Just as an FYI, the updating mechanism within a `beginUpdates` and `endUpdates` scope for `NSTableView` behaves differently than the same one in `UITableView`. 

Changes are done live and are not batched together automatically. 

For reference, this [WWDC video](https://developer.apple.com/videos/play/wwdc2011/120/) explains the process at timemark **48:10**. 

So in my example, 
`self.mainTableView.removeRows(at: IndexSet(integer: 2))`
`self.mainTableView.removeRows(at: IndexSet(integer: 3))`

is functionality different than: 

`self.mainTableView.removeRows(at: IndexSet([2,3]))`

Assuming there are more than 4 rows in the table.

**Comment by groue** [comment]
@martindufort, I have never looked at NSTableView, so I can't guarantee it should work out of the box.

The question is: **do the events emitted by FetchedRecordsController allow you to correctly animate an NSTableView, or not?**

I don't have the NSTableView skills to answer this question directly.

A proper reproducible case should look like this:

1. setup the database with *content 1*
2. setup the FetchedRecordsController with *request*
3. change the database to *content 2*
4. note the callbacks emitted by FetchedRecordsController, in order.

If the callbacks make it impossible to correctly animate a UITableView, then we have a GRDB bug.

If the callbacks make it impossible to correctly animate an NSTableView, then we have a feature request, which is to have FetchedRecordsController emit *different* callbacks for NSTableView.

In this last case, I have to be clear. The diffing algorithm that powers FetchedRecordsController is far from being the best available, and performing the required refactoring is not on my personal priority list. Instead, I recommend these days to look at https://github.com/ra1028/DifferenceKit. It deals with UITableView pretty well, I hope it deals with NSTableView just as well.

**Comment by martindufort** [comment]
> If the callbacks make it impossible to correctly animate an `NSTableView`, then we have a feature request

Because of the difference between the `UITableView` and the `NSTableView` implementations that's the case.

Thus, out of the box, `FetchedRecordsController.trackChanges` is not supporting MacOS `NSTableView` animation properly.

This would be a **feature request.** 

Thanks for the ref to `DifferenceKit`. I will look into it and see if I can solution this problem using `ValueObservation` and this library. 

Merci et à bientôt...

**Comment by groue** [comment]
> Because of the difference between the UITableView and the NSTableView implementations that's the case.

OK, thanks for teaching me that :-)

Yes, I hope DifferenceKit, or another third-party diffing library, can create the diff you need. You can still use FetchedRecordsController in order to be notified of changes - just do not use its diffing callback:

```swift
var players: [Player] = []
controller.trackChanges { controller in
    let newPlayers = controller.fetchedRecords
    let diff = computeDiff(from: players, to: newPlayers) // <-
    players = newPlayers
    tableView.apply(diff)
}
```

Will you share the results of your investigation?

**Comment by groue** [comment]
OK Martin! I'm sorry there are less people who know NSTableView as well as UITableView.
