### ISSUE TITLE
Record.deleteAll emitting too many SQL requests

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#624]
### What did you do?

I have this operation that I'm executing within an `OperationQueue`.

```swift 
let deleteOp = BlockOperation {
	do {
		let _ = try AppDelegate.dbQueue.write { db in
				try Master.deleteAll(db)
			}
		}
	catch let e as DatabaseError {
		debugPrint("Database error while deleting \(e.localizedDescription)")
	}
	catch {
		debugPrint("Fatal error while deleting \(error.localizedDescription)")
	}
}
```

### What did you expect to happen?

Was expecting GRBD to issue a single (1): 
`
DELETE FROM "master"
`

### What happened instead?

With this configuration in place
```swift
		var config = Configuration()
		#if DEBUG
			config.trace = { print($0) } // Prints all SQL statements
		#endif
```

The console is displaying as many 'Delete' statements as they are records within the <Master> table.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:**4.2.1
**Installation method:** CocoaPods
**Xcode version:** 10.2.1
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hi @martindufort,

A single delete statement is executed. But is is notified several times to the sqlite3_trace_v2() function.

This log stuttering  has troubled me many times :-) I don't know why it happen, I don't know if it is the sign of anything wrong, I didn't even perform a Google search about it.

**Comment by groue** [comment]
No news is good news.

**Comment by martindufort** [comment]
Yes this can be closed. Thanks for the response on this.

**Comment by martindufort** [comment]
Coming back to this log repetition behavior. 
Wondering now why we don't have this stuttering in a consistent manner. Some are unique while others are repeated. 

How can I validate, apart from the log printouts, if the same statement has been executed more than once?  

Any ideas ? Can I log something in a special table with a trigger ?

**Comment by groue** [comment]
Hi @martindufort. You can't go more low-level than putting a symbolic breakpoint on `sqlite3_step`. Updates statements like DELETE, INSERT, etc should execute it only once. Thanks for keeping on investigating!
