### ISSUE TITLE
Application crashes when Codable objects change their format

### ISSUE THREAD

**Issue by nominalista** [groue/GRDB.swift#626]
### What did you do?

Let's assume we have simple record like this:

```
// User

struct User {
    let id: String
    let personalData: PersonalData
}

extension User: Codable {

    enum CodingKeys: String, CodingKey {
        case id
        case personalData
    }
}

extension User: TableRecord, FetchableRecord, MutablePersistableRecord {

    static let databaseTableName = "user"

    enum Columns {
        static let id = Column(CodingKeys.id)
        static let personalData = Column(CodingKeys.personalData)
    }
}

// Personal data

struct PersonalData {
    let name: String
}

extension PersonalData: Codable {
    enum CodingKeys: String, CodingKey {
        case name
    }
}
```

Now we during development process we change schema of `PersonalData` to this:
```
// Personal data

struct PersonalData {
    let firstName: String
    let lastName: String
}

extension PersonalData: Codable {
    enum CodingKeys: String, CodingKey {
        case firstName
        case lastName
    }
}
```

We store user records in our application and now we need to push application update with new `PersonalData` format.

### What did you expect to happen?

I expected that this part of code would catch an error, that GRDB is unable to decode `PersonalData` because it has changed its format. 
```
do {
    try database.read { db 
        try User.all().fetchAll(db)
    }
} catch let error {
    // Catching error
}
```

### What happened instead?

Instead application crashed, because initializing `FetchableRecord` uses `try!`.
```
extension FetchableRecord where Self: Decodable {
    public init(row: Row) {
        let decoder = RowDecoder<Self>(row: row, codingPath: [])
        try! self.init(from: decoder)
    }
}
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.4
**Installation method:** CocoaPods
**Xcode version:** 11
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14

**Comment by groue** [comment]
Hello @nominalista,

The FetchableRecord protocol provides an `init(row: Row)` initializer which does not throw. In other words, a type must be able to decode rows without error if it wants to profit from FetchableRecord services.

You only have two choices:

1. Don't have User conform to FetchableRecord
2. Have User conform to FetchableRecord, but make sure `User.init(row: Row)` can decode rows.

To make `User.init(row: Row)` able to decode rows, you again have choices:

1. Don't use Decodable and provide a custom implementation of `init(row: Row)` which can handle your various row formats
2. Use Decodable, but make sure your Decodable implementation can handle your various row formats
3. Use Decodable with all benefits of compiler code generation, but then make sure the database contains a SINGLE row format that is suitable for your User type: migrate your database to the desired format when your application starts up.

My own choice would be to migrate the database, but YMMV.

**Comment by nominalista** [comment]
Hello @groue,

Thank you for your fast response. In my real case, GRDB is only responsible for caching data when user is offline, so I use `eraseDatabaseOnSchemaChange` to simplify any migration. 

I think the fastest solution when nested data changes its format (again, in my case where GRDB is just a cache) would be to drop old table when migrating database. What do you think?

**Comment by groue** [comment]
Thanks for the extra context @nominalista.

Indeed `eraseDatabaseOnSchemaChange` can't spot that the `PersonalData` implementation has changed. The `personalData` columns is still a string, and the database schema itself has not changed.

> I think the fastest solution when nested data changes its format (again, in my case where GRDB is just a cache) would be to drop old table when migrating database. What do you think?

I'm not sure migrations can help here. Not only you'd have to *add* a migration each time the schema changes. And it would be error-prone to make sure those migrations do not ship in your released app.

Before `eraseDatabaseOnSchemaChange` was introduced, I used to remove the app from my simulators or devices. It have also used environment variables that the app checks at boot in ordre to destroy its existing database. Those environment variables are just two clicks away from Xcode, and are quite useful. There are various strategies, depending on your use cases :-)

**Comment by nominalista** [comment]
Hmm if I understand correctly, environment variables are useful during development, so they can reinstall the app completely. 

What if there is an existing version of the application with the old format of `PersonalData` in  the App Store?

Maybe we could still use advantage of `eraseDatabaseOnSchemaChange`. E.g. we can add version suffix (`v1`, `v2`) to the table name when we know that `PersonalData` format changed internally.

**Comment by groue** [comment]
> What if there is an existing version of the application with the old format of PersonalData in the App Store?

That's exactly where migrations shine: they can transform existing data so that it turns into the shape expected by the application code.

> Maybe we could still use advantage of eraseDatabaseOnSchemaChange. E.g. we can add version suffix (v1, v2) to the table name when we know that PersonalData format changed internally.
 
I can't really make formal recommendation. I suggest you experiment until you find the technique that fits your practices.

**Comment by nominalista** [comment]
Thank you for support. I think the issue can be closed now IMHO.

**Comment by groue** [comment]
Happy GRDB!
