### ISSUE TITLE
This is the library with the best maintenance and documentation I have ever seen

### ISSUE THREAD

**Issue by acecilia** [groue/GRDB.swift#629]
Because we usually open issues for things not working, I just wanted to take some time and do the opposite :)

Thanks for your effort and support, Keep it up @groue!

**Comment by groue** [comment]
That's a lovely message, and it does indeed goes straight to my heart! I don't know what to say on top of that, except that this lib is made for its users, that I'm one of them, and that I'm happy that what I need in my everyday job marches other people's need. Thank you @acecilia!
