### ISSUE TITLE
Cannot build with custom SQLite

### ISSUE THREAD

**Issue by davenquinn** [groue/GRDB.swift#630]
https://github.com/groue/GRDB.swift/blob/aa157a77d20133d3ca1757343c2e27831e5d5fa7/Support/grdb_config.h#L12

When using the instructions for building with custom SQLite, the header `GRDBCustom/sqlite.h` cannot be found. However, when I change this line to `#include <GRDBCustomSQLite/sqlite3.h>`, everything works fine. `GRDBCustom.xcodeproj` is embedded in my app's XCode project as laid out [here in the documentation](https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md#custom-sqlite-builds).

**Comment by groue** [comment]
Hi @davenquinn,

Thank you very much for the report: you did spot a wrong header setup.

I don't quite understand how it could be missed. As a matter of fact I could not myself reproduce any error. But I was able to notice a wrong setup of the `GRDBCUSTOMSQLITE` processor definition, which is used to include the correct sqlite3.h header.

#631 aims at addressing this issue. Would you mind checking it?

**Comment by davenquinn** [comment]
Hi @groue,

The issue is fixed for me on the #631 branch; all builds complete as expected when the fix is applied. Many thanks!
