### ISSUE TITLE
defaultDatabaseTableName should be cached

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#637]
We have noticed a fairly big cpu and memory impact when inserting/updating many items from repeated calls to `TableRecord.defaultDatabaseTableName` (because of the regex calls). This should be easily cacheable. I'm sorry, I don't have time to send a Pull Request 🙁

**Comment by hartbit** [comment]
It's already what I ended up doing :)

**Comment by groue** [comment]
Fixed by #685, shipped in v4.9.0
