### ISSUE TITLE
Add Test section to Document

### ISSUE THREAD

**Issue by Mahdimm** [groue/GRDB.swift#639]
Hi, @groue  
Thanks for this awesome library.

I think it would be great if we have a way or configuration to test our database queries, but I didn't see in the documentation section?

**Comment by groue** [comment]
Hello @Mahdimm,

I don't quite know what you mean by testing your database queries.

You may have a look at the [RxGRDB demo app](https://github.com/RxSwiftCommunity/RxGRDB/tree/v0.17.0/Documentation/RxGRDBDemo) and its [tests](https://github.com/RxSwiftCommunity/RxGRDB/tree/v0.17.0/Documentation/RxGRDBDemo/RxGRDBDemoTests) if you are looking for some inspiration.

**Comment by Mahdimm** [comment]
Thanks for reply @groue 
 
but I mean how we can implement best practice tests, but with this sample that you provided, I get the idea thanks.

**Comment by groue** [comment]
I'm not quite a testing expert, so I don't dare giving advice. Yet, here are a few practices I follow that make database testing easier:

I want to run tests with a real database. Hence I make sure that the code that initializes the database is not the code that decides of its actual path. I usually have:

```swift
// Usable from both app and tests
func setupDabatase(_ database: DatabaseWriter) throws {
    // Run migrations
    try migrator.migrate(dabatase)
    // ...other eventual database initialization steps
}

// In app delegate
func makeAppDatabase() throws -> DatabasePool {
    // App needs a database stored at some path
    let path = ...
    let dbPool = try DatabasePool(path: path)
    try setupDabatase(dbPool)
    return dbPool
}

// In tests
func makeTestDatabase() throws -> DatabaseQueue {
    // tests run faster in an in-memory database
    let dbQueue = DatabaseQueue()
    try setupDabatase(dbQueue)
    return dbQueue
}
```

In order to let the app use an efficient DatabasePool, and tests use a fast in-memory DatabaseQueue, I have my "database managers" accept a DatabaseWriter (the common protocol shared by both DatabaseQueue and DatabasePool):

```swift
class PlayersManager {
    let database: DatabaseWriter
    init(database: DatabaseWriter) {
        self.database = database
    }

    func doSomeStuff() throws {
        try database.write { db in ... }
    }
}
```

This makes it possible to use those managers from the app, and tests them:

```swift
// In app delegate
func makePlayersManager() -> PlayersManager {
    let database = try makeAppDatabase()
    return PlayersManager(database: database)
}

// In tests
func makePlayersManager() -> PlayersManager {
    let database = try makeTestDatabase()
    return PlayersManager(database: database)
}
```

From this base, you should be able to run sharp and focused tests that actually test your app.

**Comment by groue** [comment]
Last advice: don't test for the generated SQL. GRDB may change it, without notice, and break your tests:

```swift
// Don't do that: this test is fragile
func testPlayersOrderByNameSQL() throws {
    let database = try makeTestDatabase()
    let request = Player.orderByName()
    let sql = try database.read { db in
        try SQLRequest(db, request: request).sql
    }
    XCTAssertEqual(sql, "SELECT * FROM player")
}
```

Instead, test that your request provide the expected results:

```swift
func testPlayersOrderByName() throws {
    // Given two players
    let database = try makeTestDatabase()
    try database.write { db in
        try Player(uuid: UUID(), name: "Arthur").insert(db)
        try Player(uuid: UUID(), name: "Barbara").insert(db)
    }
    
    // When we fetch players ordered by name
    let request = Player.orderByName()
    let players = try database.read(request.fetchAll)
    
    // Then the players are ordered by name
    let names = players.map { $0.name }
    XCTAssertEqual(names, ["Arthur", "Barbara"])
}
```

Of course, the real job is to find interesting and useful tests, not toy ones like above :-D Try not to test SQLite or GRDB. Instead, only test your app methods and objects.

**Comment by groue** [comment]
Feel free to reopen this issue if you have another question, @Mahdimm
