### ISSUE TITLE
Could you please provide a demo app for SwiftUI?

### ISSUE THREAD

**Issue by sicilian-lizard** [groue/GRDB.swift#645]
I did quite some search but couldn't find a way to make GRDB with SwiftUI, is it possible for you to provide a very simple demo/skeleton to show us how to make GRDB work with SwiftUI? I believe it will help a lot of people, especially for newbies like me.

**Comment by groue** [comment]
Hello @sicilian-lizard,

I suggest you look at http://github.com/groue/GRDBCombine and its demo application.

**Comment by sicilian-lizard** [comment]
I did, thanks.

**Comment by malhal** [comment]
I wouldn't recommend that demo it doesn't use SwiftUI best practices, e.g. it uses view-model objects instead of View structs so doesn't take advantage of the built-in dependency tracking.
