### ISSUE TITLE
databaseMigrator.appliedMigrations throws error for new users

### ISSUE THREAD

**Issue by michaelkirk-signal** [groue/GRDB.swift#652]
### What did you do?

As our schema changes, we register new migrations with our DatabaseMigrator. Existing users will run the new migrations incrementally as they are run.

As an optimization for new users, we want to skip the incremental migrations, and only import the final resultant schema.

We need to:
1. Detect if the user is a new user.
2. Import the final resultant schema, which we track outside of GRDB.
3. Mark all the currently existing migrations as "run", so they don't get "re-run" next launch.

For [1], to detect if the user is new, we thought to inspect `databaseMigrator.appliedMigrations`. However an error is thrown when running `try migrator.appliedMigrations(in: pool)` for new users.

### What did you expect to happen?

I expected to run `try migrator.appliedMigrations(in: pool)` for a new user and get an empty result, to infer that no migrations had been run. 

This would mean we could run the optimized version of the migrator which imports the final schema, rather than running the incremental migrations.

### What happened instead?

An error is thrown because `appliedMigrations` consults the `grdb_migrations` table, which does not necessarily exist. Furthermore, the method which sets up the migration table, is private:

```
private func setupMigrations(_ db: Database) throws {
    try db.execute(sql: "CREATE TABLE IF NOT EXISTS grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)")
}
```

It seems reasonable that this method is private, but we're wondering if there's a public stable API to achieve what we want without hardcoding assumptions about where the migrations will live.

### Environment

**GRDB flavor(s):** SQLCipher
**GRDB version:** 4.3.0
**Installation method:** CocoaPods
**Xcode version:** 10.3
**Swift version:** 5.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14

### Demo Project

I can provide one if it's not clear from the above.

**Comment by groue** [comment]
Hello @michaelkirk-signal,

`appliedMigrations` should unquestionably return an empty array if the migrations table has not been created yet. Would you like to set up a pull request for this fix?
