### ISSUE TITLE
Loop through database tables

### ISSUE THREAD

**Issue by VickyPrajapati24** [groue/GRDB.swift#654]
I want to fetch all tables from the database and want to delete all records of those tables. So is there any way to fetch all tables & loop through it.

Thanks in advance.

**Comment by groue** [comment]
Hello @VickyPrajapati24,

As explained in the SQLite frequently asked question [How do I list all tables/indices contained in an SQLite database](https://www.sqlite.org/faq.html#q7), you fetch the names of all database tables in the `sqlite_master` table. With GRDB, it gives:

```swift
try dbQueue.write { db in
    let tables = try String.fetchAll(db, sql: """
        SELECT name FROM sqlite_master WHERE type='table'
        """)
```

You then iterate all table names and execute [DELETE](https://www.sqlite.org/lang_delete.html) statements:

```swift
    for table in tables {
       try db.execute(sql: "DELETE FROM \(table)")
    }
}
```

**If you have anything to remember from this answer, it is that GRDB is based on SQLite.** Uncommon use cases that do not have a ready-made Swift method can always be achieved at a lower level. SQLite has great documentation, and GRDB has great support for raw SQL.

**Comment by hllovesgithub** [comment]
thx a lot

**Comment by karloscarweber** [comment]
Exactly what I was looking for, Thanks!
