### ISSUE TITLE
Self-association not loading optional data on raw SQL query

### ISSUE THREAD

**Issue by igorkulman** [groue/GRDB.swift#664]
### What did you do?

I have a full-text search query over `users` using a visualized table `users_ft`. Each `user` has an nullable `organisationId` foreign key to pointing to the `organisations` table.

I do a full text search using raw SQL (as I could not really make it work using records because of the virtualized table)

```swift
let sql = """
            SELECT \(UsersTableDescription.tableName).*, \(OrganisationsTableDescription.tableName).*
            FROM \(UsersTableDescription.tableName)
            JOIN \(UsersTableDescription.fullTextTableName) ON
            \(UsersTableDescription.fullTextTableName).rowid = \(UsersTableDescription.tableName).rowid AND
            \(UsersTableDescription.fullTextTableName) MATCH ?
            LEFT JOIN \(OrganisationsTableDescription.tableName) ON \(UsersTableDescription.tableName).\(UsersTableDescription.Columns.organisationId.name) = \(OrganisationsTableDescription.tableName).\(OrganisationsTableDescription.Columns.orgId.name)
            WHERE \(UsersTableDescription.tableName).\(UsersTableDescription.Columns.isActive.name) = 1 AND \(UsersTableDescription.tableName).\(UsersTableDescription.Columns.userId.name) <> ?
            ORDER BY \(UsersTableDescription.tableName).\(UsersTableDescription.Columns.lastName.name) COLLATE NOCASE ASC
            LIMIT ?
        """

        return try FullTextUserSearchResult.fetchAll(db, sql: sql, arguments: [pattern, userId ?? "", limit])
```

For this definition of the result 

```swift
struct FullTextUserSearchResult: FetchableRecord, Decodable {
    var user: UserModel
    var organisation: OrganisationEntity?
}
```

the `organisation` property is always nil.

### What did you expect to happen?

The  `organisation` property to be not nil when the data is available

### What happened instead?

The `organisation` property is always nil.

### Observation

When I change the result type to make the `organisation` property not optional

```swift
struct FullTextUserSearchResult: FetchableRecord, Decodable {
    var user: UserModel
    var organisation: OrganisationEntity
}
```
the data loads as expected, the  `organisation` property is not nil.

This makes me think that the problem is the optionality of the  `organisation` property but it has to be optional as the data is no always available.

### Environment

**GRDB flavor(s):** SQLCipher
**GRDB version:** 4.4.0
**Installation method:** CocoaPods built then manually added to project
**Xcode version:** 11.2.1
**Swift version:** 5.1.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hello @igorkulman,

Your code, as it is, is not supposed to work. The fact that it loads "stuff" without throwing any error is the sign of a loophole in the way GRDB decodes records. You can consider it a bug. And I'm sorry for the confusion.

But you should be able to make it work as below. I suppose both UserModel and OrganisationEntity conform to the TableRecord protocol.

```swift
let sql = """
    SELECT ...
    """
let request = SQLRequest<FullTextUserSearchResult>(
    sql: sql,
    arguments: [pattern, userId ?? "", limit])
    .adapted { db in
        let adapters = try splittingRowAdapters(columnCounts: [
            UserModel.numberOfSelectedColumns(db),
            OrganisationEntity.numberOfSelectedColumns(db)])
        return ScopeAdapter([
            "user": adapters[0],
            "organisation": adapters[1]])
    }
let results = try request.fetchAll(db) // [FullTextUserSearchResult]
```

If organisation is optional, then it will be nil if and only if all its columns in the fetched results are NULL (this is what happens when the LEFT JOIN won't find a matching row).

For more information about this technique for consuming hand-crafted joined request, see [Joined Queries Support](https://github.com/groue/GRDB.swift/blob/master/README.md#joined-queries-support). The idea is that you have to help GRDB dispatching columns into nested records:

```sql
--     <UserModel> <OrganisationEntity>
SELECT user.*,     organisation.*       FROM ...
```

**Comment by igorkulman** [comment]
Thanks for the explanation. I kind of thought that I am combining two things that might not be designed to work together, but it worked for me in a different query where everything in the result is non-optional so I tried it here also.

 The code you provided works exactly as needed, thanks! 

Reading the documentation it is also great to see I can replace `"user": adapters[0]` with `UserQueryResult.CodingKeys.user.stringValue: adapters[0]`etc as I implement codable.

**Comment by groue** [comment]
Good, @igorkulman :-)

I have closed the loophole in the above commit, which will be merged in the next shipped version. Thank you for spotting this issue!
