### ISSUE TITLE
[Q] How does encrypting fits into migration?

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#665]
Hi,

This is not a bug report, but a question instead. I'm currently using GRDB and I already have 1 migration. Now, to encrypt this clear text db, according to the readme I should create an encrypted db on a different path and export the data from the first one to the new one. Gotcha. My question is not really about the encryption process itself but instead how would that work regarding db migration. Can someone give me an example of how would this migration look like? I'm a bit confused about new users actually. I mean, a new user would pass through all the process of 
- creating a clear text db
- migrating to the first migration
- creating a new encrypted db
- exporting the content from the clear text db to the encrypted db
- deleting the clear text db

I just want to make sure i'm doing it right, thanks in advance! 

Happy GRDB!!

**Comment by groue** [comment]
Hello @brunomunizaf,

Migrations are about the schema of the database, and encryption is about the format of the database file. Those are independent concerns, and must not be conflated.

If your application transitions from a clear-text database to encrypted database, you could apply the following strategy:

1. Pick two distinct paths for the clear-text and the encrypted database (let's say `clearPath` and `encryptedPath`).
2. Does the database exists at `encryptedPath`? If it doesn't, export the content at `clearPath` to `encryptedPath`, and if the export succeed, delete the database at  `clearPath`.
3. Normally migrate the schema of the database at `encryptedPath`. The migrator does not need to know that on some devices, the database used to exist as a clear-text!
