### ISSUE TITLE
Fatal error: keyed encoding is not supported

### ISSUE THREAD

**Issue by matinouf** [groue/GRDB.swift#667]
Hi.
Thanks for your fantastic library.
I can't find any solution  in documentation and Demo app.
please give me an example how to insert 'Bank' as JSON
 
I also tried `CheckListRecord: Record { ... }`. But I did not succeed

### What did you do?
I try to save CheckListRecord...
```

try dbQueue.write { (db) in
            let checkList = CheckListRecord(id: 1,
                                            logoImage: "http://....",
                                            companyName: "My Company",
                                            title: "title",
                                            description: "some description...",
                                            status: 0,
                                            from_name: nil,
                                            from_email: nil,
                                            created_at: nil,
                                            bank: Bank(id: 1, money: "100", status: 1))
            try checkList.insert(db)
}

struct CheckListRecord: Codable, FetchableRecord, PersistableRecord {
    
    var id: Int64
    var logoImage: String?
    var companyName: String?
    var title: String?
    var description: String?
    var status: Int!
    var from_name: String?
    var from_email: String?
    var created_at: String?
    var bank: Bank?
    
    static var databaseTableName: String = "checkLists"
}

struct Bank: Codable {
   let id: Int
   let money: String
   let status: Int
}

```

### What happened instead?
when try to write: **Fatal error: keyed encoding is not supported**
when try to read: **Fatal error: could not convert database value Data(33 bytes) to Bank .....**

### Environment

**GRDB version:**4.6.2
**Installation method:** CocoaPods
**Xcode version:**11.2
**Swift version:**5.0
**Platform(s) running GRDB:** iOS

**Comment by groue** [comment]
Hello @matinouf,

The code you have pasted does not compile because of the `structureData` initializer argument. This prevents anyone from reproducing the issue.

> when try to read: Fatal error: could not convert database value Data(33 bytes) to Bank .....

You have truncated the error messages, preventing any analysis of your trouble.

Please enhance your report with all information needed for reproduction (for both write and read error). And when you experience a crash, provide the stack trace.

**Comment by matinouf** [comment]
Sorry!
The problem was solved and it was for something else
Thank you

**Comment by groue** [comment]
Good! Happy GRDB!
