### ISSUE TITLE
Update record type fails

### ISSUE THREAD

**Issue by VickyPrajapati24** [groue/GRDB.swift#669]
Hello, I am using dbpool asyncwrite method, In which I have fetched a couple of records using records type. Then I am updating one value of record type key and using try record.update(db) which fails with  **The operation couldn’t be completed. (GRDB.PersistenceError error 0.)**

```
`DBManager.shared.dbPool.asyncWrite({ (db: Database) -> Void in
            let records = try TABLE1.fetchAll(db, sql: "SELECT * FROM \(TABLE1.databaseTableName)")
     
            for record in records {
                let batchId = "sndbcfbbc"
                record.batchId = batchId
                try v.update(db)
            }
        }, completion: { (_: Database, result: Swift.Result<Void, Error>) in
            DispatchQueue.main.async {
                switch result {
                case let .success:
                case let .failure(error):
                    print(error.localizedDescription)
                    failure()
                }
            }
        })`
```

It goes to failure block and print: **The operation couldn’t be completed. (GRDB.PersistenceError error 0.)**

**Comment by groue** [comment]
Hello @VickyPrajapati24 

> The operation couldn’t be completed. (GRDB.PersistenceError error 0.)

This is not a clear error message.

Try simply `print(error)`

**Comment by VickyPrajapati24** [comment]
Hello @groue ,
I have print the error it shows below.
`(GRDB.PersistenceError) $R0 = recordNotFound {
  recordNotFound = {
    databaseTableName = "OUT_SCORECARD"
    key = 1 key/value pair {
      [0] = {
        key = "id"
        value = {
          storage = null
        }
      }
    }
  }
}`

I have print whole the object before try table.update(db), it have id key and its auto-incremented value is there.

**Comment by VickyPrajapati24** [comment]
Hello @groue,
Sorry to bother you but I was stuck from the past 3-4 hours. Actual issue was I didn't assign id key to encode in **override func encode(to container: inout PersistenceContainer)** method.

**Comment by groue** [comment]
Great, @VickyPrajapati24.

The `update(db)` method throws `PersistenceError.recordNotFound` if the record that you want to update does not exist in the database.

The error is also thrown if you forget to encode the primary key in `encode(to:)`, because GRDB tries to update a record with a null primary key (which does not exist).
