### ISSUE TITLE
fatel error when using Row

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#67]
I must be missing something obvious ... the only difference being String or Row

This works

```swift
        dbQueue.inDatabase { db in
        let row = String.fetchOne(db, "SELECT word, action FROM words INNER JOIN groups ON words.groupid = groups.groupid WHERE groups.enabled=1 AND LIKE ('%' || word, ?)", arguments: [wordToExpand])
        }
```
but this causes a fatal error

```swift
        dbQueue.inDatabase { db in
        let row = Row.fetchOne(db, "SELECT word, action FROM words INNER JOIN groups ON words.groupid = groups.groupid WHERE groups.enabled=1 AND LIKE ('%' || word, ?)", arguments: [wordToExpand])
        }
```

**Comment by groue** [comment]
Hello @mtissington. I can't help with so little information.

**Comment by mtissington** [comment]
When I use String.fetchOne a value is returned. When I change it to Row.fetchOne I get a fatal error, I can't even step into GRDB code - dyld`dyld_fatal_error:

**Comment by groue** [comment]
Come on @mtissington, play the game, and learn how to report bugs. The minimum is the error message.

**Comment by mtissington** [comment]
Sorry, there is NO error message the only information that I see is xcode breaks to assembly code and shows a fatal error dyld`dyld_fatal_error:, no message, nothing else that might be helpful. If there was more information I'd willingly post it. The error happens even before I can single step into the fetchOne code. What else can I give you to help?

**Comment by groue** [comment]
All right. The stack trace could help?

**Comment by groue** [comment]
If you don't know how to provide more information, you can try to help me reproduce the crash, by providing a short code snippet that reveals the issue. Something I can run to exhibit the crash.

**Comment by mtissington** [comment]
Here is the stack trace
```swift
Thread 1Queue : GRDB.SerializedDatabase (serial)
#0	0x0000000120019088 in dyld_fatal_error ()
#1	0x000000012001befc in dyld::halt(char const*) ()
#2	0x000000012001bff8 in dyld::fastBindLazySymbol(ImageLoader**, unsigned long) ()
#3	0x00000001809fcba0 in dyld_stub_binder ()
#4	0x00000001000ae5d8 in ActiveWords.(test(String!) -> ()).(closure #1) at /Users/michael/Developer/ActiveWords/ActiveWords/ActiveWords.swift:216
#5	0x00000001000a5b8c in partial apply for ActiveWords.(test(String!) -> ()).(closure #1) ()
#6	0x00000001000ae420 in thunk ()
#7	0x00000001001bba10 in static DatabaseScheduler.(dispatchSync<A> (OS_dispatch_queue, database : Database, block : (db : Database) throws -> A) throws -> A).((impl #2)(OS_dispatch_queue, database : Database, block : (db : Database) throws -> A, onError : (ErrorType) throws -> ()) throws -> A).(closure #1) ()
#8	0x00000001001b2d84 in thunk ()
#9	0x00000001809cd47c in _dispatch_client_callout ()
#10	0x00000001809d8728 in _dispatch_barrier_sync_f_invoke ()
#11	0x00000001001bb76c in static DatabaseScheduler.(dispatchSync<A> (OS_dispatch_queue, database : Database, block : (db : Database) throws -> A) throws -> A).(impl #2)(OS_dispatch_queue, database : Database, block : (db : Database) throws -> A, onError : (ErrorType) throws -> ()) throws -> A ()
#12	0x00000001001b9ec8 in static DatabaseScheduler.dispatchSync<A> (OS_dispatch_queue, database : Database, block : (db : Database) throws -> A) throws -> A ()
#13	0x0000000100215f40 in SerializedDatabase.performSync<A> ((db : Database) throws -> A) throws -> A ()
#14	0x00000001001b57fc in DatabaseQueue.inDatabase<A> ((db : Database) throws -> A) throws -> A ()
#15	0x00000001000a5a68 in ActiveWords.test(String!) -> () at /Users/michael/Developer/ActiveWords/ActiveWords/ActiveWords.swift:217
```

**Comment by groue** [comment]
Weird... Did you try to clean the build folder?

**Comment by mtissington** [comment]
Maybe this shows the problem more clear?

```swift
    func test (wordToExpand: String!) {
        dbQueue.inDatabase { db in
            
            // this works
            let value1 = String.fetchOne(db, "SELECT word, action FROM words INNER JOIN groups ON words.groupid = groups.groupid WHERE groups.enabled=1 AND LIKE ('%' || word, ?)", arguments: [wordToExpand])
            
            // this crashes (the only difference is using Row instead of String)
            let value2 = Row.fetchOne(db, "SELECT word, action FROM words INNER JOIN groups ON words.groupid = groups.groupid WHERE groups.enabled=1 AND LIKE ('%' || word, ?)", arguments: [wordToExpand])
        }
        
    }
```

**Comment by mtissington** [comment]
Weird indeed ... just done another clean and now I've started getting an error 
 Cannot load underlying module for 'GRDB' but strangely the product builds without any errors.

**Comment by mtissington** [comment]
I mean it build without errors but the issue is still there.

**Comment by mtissington** [comment]
Weird, I do a clean, delete all derived data, rebuild several times, reboot machine and now the code works. Seems like some sort of xcode or swift bug ... but the error Cannot load underlying module is still present ... thanks for your patience!

**Comment by groue** [comment]
Your Xcode has entered the twilight zone... So you're able to run your code now, but Xcode still emits a strange error? That's already a very positive achievement :-) Sometimes I also have to clean the xcuserdata folder inside the xcodeproj: when things go wild, Xcode won't easily clean *everything* up.
