### ISSUE TITLE
HasOneThrough association issues

### ISSUE THREAD

**Issue by mtancock** [groue/GRDB.swift#672]
Thanks for the library. It's amazing and so well documented.

### What did you do?
I'm following the association guide [here](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#hasonethrough), and trying to create an "association through", however, the compiler is not liking the code in the example. I'm trying the book/library/address example as written in the guide:
This line causes problems:
```
static let returnAddress = hasOne(Address.self, through: library, using: library.address)
```

If I use the code as is, it complains that there is `Extra argument 'through' in call` - it doesn't seem to recognise the existence of the `static let library...` at all.

If I change that line to: 
```
static let returnAddress = hasOne(Address.self, through: Book.library, using: Library.address)
```
 it seems to keep it happy. 

Is this correct? Or am I doing something else wrong!

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.7.0
**Installation method:** Cocoapods
**Xcode version:** 11.2
**Swift version:** 5.1.1
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.15

**Comment by mtancock** [comment]
Great - thanks for confirming (and so quickly). I'll leave this open in case you want it to track the docs issue - otherwise feel free to close it :)

**Comment by groue** [comment]
Fixed. Thank you @mtancock, happy 2020!
