### ISSUE TITLE
Encoding Arrays into Record Class Column

### ISSUE THREAD

**Issue by peppababy7** [groue/GRDB.swift#673]
### What did you do?
Hi, @groue , Thanks your works
When i Encoding Arrays into Record Class Column, Xcode will report error `Subscript 'subscript(_:)' requires that '[Int64?]' conform to 'DatabaseValueConvertible'`
I read Record Class  documentation and GRDBDemo, but can not find works code, please help me, thanks

### What did you expect to happen?

`Subscript 'subscript(_:)' requires that '[Int64?]' conform to 'DatabaseValueConvertible'`
 
###  Environment
GRDB flavor(s): GRDB
GRDB version: 4.7.0
Installation method: Cocoapods
Xcode version: 11.2
Swift version: 5.1.1
Platform(s) running GRDB: macOS
macOS version running Xcode: 10.15

### Demo Project

```
class DayEvent: Record {
    var id: Int64?
    var taskIds: [Int64?]
 
    init(id: Int64?,  taskIds: [Int64?]) {
        self.id = id
        self.taskIds = taskIds
        super.init()
     }
     
     /// The table name
     override class var databaseTableName: String {
         return "taskEvent"
     }
     
     /// The table columns
     enum Columns: String, ColumnExpression {
         case id, taskIds
     }

     /// Creates a record from a database row
    required init(row: Row) {
        id = row[Columns.id]
        taskIds = row[Columns.taskIds]
        super.init(row: row)
    }
     
     /// The values persisted in the database
    override func encode(to container: inout PersistenceContainer) {
        container[Columns.id] = id
        container[Columns.taskIds] = taskIds
    }
    
     /// Update record ID after a successful insertion
     override func didInsert(with rowID: Int64, for column: String?) {
         id = rowID
     }
    
}

```

**Comment by peppababy7** [comment]
At first, I use struct for this feature, It is works.But you know, when i assign one struct to another, then edie new struct, the old one will not changed. So I use Record Class. but cause i error, i can not find any solvetion in demo or documentation. So I Need your help.

**Comment by groue** [comment]
Hi @peppababy7,

This is Christmas break here. I suggest you read again the documentation about **Values** and **Codable Records**.  Happy GRDB!

**Comment by peppababy7** [comment]
Merry Christmas!

When i read JSON Columns, it says 

> When a Codable record contains a property that is not a simple value (Bool, Int, String, Date, Swift enums, etc.), that value is encoded and decoded as a JSON string.

So I convert Array to String. It works ,thank you very much

**Comment by groue** [comment]
Good! Happy GRDB!
