### ISSUE TITLE
DB Operations while app is in background Mode

### ISSUE THREAD

**Issue by VickyPrajapati24** [groue/GRDB.swift#674]
Hello @groue,
In my application, I am storing user data in the database. Users can manually go and sync records to the server. Now the client requires that records should upload to server and DB while the app is in the background state. 

So, is iOS & GRDB provides any way to manage the execution of API's and DB operations while the app is in the background ??

**Comment by groue** [comment]
Yes @VickyPrajapati24, iOS and GRDB can run in the background. Please check iOS documentation.
