### ISSUE TITLE
Database is crashing on production and testflight

### ISSUE THREAD

**Issue by chirayu25** [groue/GRDB.swift#675]
Please fill out this template when filing an issue.

 What did you do?

 - Launched app in production and logged in to get data from API and store the same in GRDB Database.

What did you expect to happen?

- Create sqlite database file.

What happened instead?
- App Crashed. Database file was not created. This is working perfectly in development mode. Issue is on production and testflight app.

Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
	GRDB.swift/SQLCipher, SQLCipher

**GRDB version:** - 
	GRDB.swift/SQLCipher (4.7.0):
    	SQLCipher (>= 3.4.0)
**Installation method:** 
	CocoaPods
**Xcode version:**
	Version 11.3
**Swift version:**
	Version 5

**Platform(s) running GRDB:** 
	iOS

**macOS version running Xcode:**
	macOS Version: 10.15.2

### Demo Project

```
import GRDB
import SQLCipher

func getDatabaseInstance() throws {

    let fileManager = FileManager.default
    let directory = fileManager.containerURL(forSecurityApplicationGroupIdentifier: AppConstants.appGroup)

    do {
        let encDatabasePath = directory?.appendingPathComponent(“ProjectName.sqlite").path

        var configuration = Configuration()
        configuration.passphrase = AppConstants.dbPassphrase

        dbQueue = try DatabaseQueue(path: encDatabasePath!, configuration: configuration)

    }
    catch {
        print(error.localizedDescription)
    } 
}
```

### Error Trace
Thread 0 name:  Dispatch queue: GRDB.DatabaseQueue
Thread 0 Crashed

**Comment by groue** [comment]
Hello @chirayu25,

You don't provide enough information. But since you are sharing an encrypted database in an Application Group, I recommend you have a good read of [this guide](https://github.com/groue/GRDB.swift/blob/master/Documentation/AppGroupContainers.md). It should help you.

**Comment by chirayu25** [comment]
@groue Thanks for the update. 

Why is this issue coming since last 15 days? Earlier with the above mentioned code it was working fine.

**Comment by groue** [comment]
> Why is this issue coming since last 15 days? 

I don't know. If you have any information to share after you have investigated your issue, please come back and tell what you have learned!

**Comment by groue** [comment]
Check https://forums.swift.org/t/grdb-sqlcipher-crash-release-builds-only-solved/37598 for a potential solution to this issue.
