### ISSUE TITLE
How to concat two columns in a filter

### ISSUE THREAD

**Issue by tarun-personatech** [groue/GRDB.swift#680]
I am doing a `LIKE` search in a Person table like this:

```
let searchFilters = [
  firstNameColumn.like("%\(search)%"),
  lastNameColumn.like("%\(search)%")
  bioColumn.like("%\(search)%")
].joined(operator: .or)

Person.filter(searchFilters).fetchAll(db)
```

Now I also want to include the combination of fisrtName and lastName column to the search. Like SQL's CONCAT function.
The equivalent SQLite expression for this would be something like this:
`select * from Person where (firstName like %search%) or (lastName like %search%) or (firstName || '  ' || lastName like %search%)`

Is there any way I can do the last bit in the above `searchFilters`?

### Environment

**GRDB flavor(s):**  GRDB
**GRDB version:** 4.7.0
**Installation method:** SPM
**Xcode version:** 11.3
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS

**Comment by groue** [comment]
Hello @tarun-personatech,

GRDB has no built-in concatenation function yet.

You can use `SQLExpressionLiteral` instead:

```swift
let fullName = SQLExpressionLiteral(literal: "\(firstNameColumn) || \(lastNameColumn)")
let searchFilters = [
  firstNameColumn.like("%\(search)%"),
  lastNameColumn.like("%\(search)%"),
  fullName.like("%\(search)%")
].joined(operator: .or)

Person.filter(searchFilters).fetchAll(db)
```

**Comment by groue** [comment]
Pull request #683 addresses string concatenation.
