### ISSUE TITLE
TransactionObserver for new record insertion

### ISSUE THREAD

**Issue by VickyPrajapati24** [groue/GRDB.swift#692]
Hello @groue,
    I have implemented transaction observer to get notified when new record will be inserted while notification arrives. I have one table **Notification** which stores push notification records to database. I have designed one screen which populate list of notifications saved in DB. When user is on the notification screen & new notification arrives & stored in db, I want to get notified to update  my list & tableview.

        // Define a ValueObservation which tracks table view sections
        let observation = ValueObservation.tracking(DatabaseRegion.fullDatabase, fetch: {
            try NOTIFICATION.fetchAll($0, sql: "SELECT * FROM NOTIFICATION where userid = '\(userid)' ORDER BY responsedate DESC")
        })
        
        observer = observation.start(
            in: DBManager.shared.dbPool,
            onError: { error in
                print("EntityObserver = observation.start ERROR --- investigate further?!?") },
            onChange: { [weak self] arrNotification in
                guard let self = self else { return }
                self.arrNotification = arrNotification
                self.tableView.reloadData()
        })  

on change doesn't get called when new records will be stored while push notification comes. 
is that works when I am inserting new record from notification service and showing list in other target view controller. So is there any issue with multiple targets or anything else.

Please help me.

**Comment by groue** [comment]
Hello @VickyPrajapati24,

Il currently in vacations, and won't have any access to any computer until a few weeks, so it's difficult to spot where your trouble is.

I don't know if you found a bug, or if something is wrong in your setup, or in your assumptions.

I suggest you reduce your trouble to a simple reproducible case. Something that can be pasted in a playground, or something that can be tested.

**Comment by VickyPrajapati24** [comment]
Hello @groue, 
     I have written below code, Where observer.start was set for dbpool which was declared in my first target of project. I am using app group for storing notification from notification service target in database which is using different dbpool object because I won't be able to access dbpool of first target.

```
observer = observation.start(
        in: DBManager.shared.dbPool,
        onError: { error in
            print("EntityObserver = observation.start ERROR --- investigate further?!?") },
        onChange: { [weak self] arrNotification in
            guard let self = self else { return }
            self.arrNotification = arrNotification
            self.tableView.reloadData()
    })  

```
So that's why it won't be tracking database changes. What do you feel? If this is the case then how can I solve this.
Thanks In advance.

**Comment by groue** [comment]
Exact. Database pools and queues don't perform cross-process observation.

I don't give advice for cross-process communication. This is far beyond the scope of this project. This issue can be closed.

But have a look at the App Group Guide, in GRDB documentation.
