### ISSUE TITLE
CREATE Triggers ... incomplete input error

### ISSUE THREAD

**Issue by tanstaafl856** [groue/GRDB.swift#694]
# What did you do?
ran in a migration...
```
try db.execute(sql: """
                 CREATE TRIGGER lock_TransXion_trigger
                    BEFORE UPDATE ON TransXion
                    WHEN new.itemsWereRcvd = true
                         AND ( new.balance = 0 OR old.balance = 0 )
                 BEGIN
                     UPDATE TransXion SET locked = true WHERE id = new.id;
                 END;


                 CREATE TRIGGER insert_TransXion_Dollar_Values_trigger
                     AFTER INSERT ON CartItem
                 BEGIN
                     UPDATE TransXion SET total = (SELECT SUM(CartItem.retail) AS retail_total FROM CartItem WHERE TransXion.id=CartItem.transactionID);
                 END;
""")
```

### What did you expect to happen?

BOTH triggers get CREATE'd

### What happened instead?

only the 1st [lock_TransXion_trigger] is created. the 2nd silently fails. confirmed by opening .sql file in DB Browser. 

the trigger CAN BE created successfully in DB Browser. then through the app I can see it working as expected.

I moved the second trigger into a regular code block with catch let reporting and got...
```
SQLite error 1 with statement `CREATE TRIGGER insert_TransXion_Dollar_Values_trigger
    AFTER INSERT ON CartItem
BEGIN
    UPDATE TransXion SET total = (SELECT SUM(CartItem.retail) AS retail_total FROM CartItem WHERE TransXion.id=CartItem.transactionID)`: incomplete input
```
searching 'sqlite incomplete input', I found https://github.com/sqlitebrowser/sqlitebrowser/issues/1470. so I played with ';' placements with no success.

any thoughts on how to rewrite the trigger that pleases GRDB would be appreciated. Thnx

### Environment

**GRDB flavor(s):** GRDB, SQLCipher
**GRDB version:**  GRDB.swift 4.9.0
**Installation method:** CocoaPods
**Xcode version:** 11.3.1
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.5

**Comment by groue** [comment]
Hello @tanstaafl856 

I don't know what you mean by "please GRDB": statements are executed by SQLite, and you get an SQLite error.

There exist tested [evidence](https://github.com/groue/GRDB.swift/blob/66bce33a3631bd362f184a6a2bcee31823a8e279/GRDB/FTS/FTS4.swift#L116) that GRDB can create several triggers in a row.

Finally, I don't currently have any computer to help you.

I suggest you try to solve your error by focusing on SQLite instead if GRDB.

**Comment by tanstaafl856** [comment]
https://stackoverflow.com/questions/60045955/sqlite-create-trigger-sqlite-error-1-with-statement-incomplete-input
