### ISSUE TITLE
Insert more than one records, only success one

### ISSUE THREAD

**Issue by archerx3** [groue/GRDB.swift#696]
### What did you do?

Insert more than two records to DB 

### What did you expect to happen?

All records should be inserted 

### What happened instead?

Only one record be inserted

### Environment

**GRDB flavor(s): GRDB**
**GRDB version: 4.6.2**
**Installation method: CocoaPods**
**Xcode version: 11.3/11.3.1**
**Swift version: 5.0**
**Platform(s) running GRDB: iOS**
**macOS version running Xcode: 10.15.2 & 10.15.3**

`INSERT OR IGNORE INTO "Lists" ("rowIdentifier", "accountUserIdentifier", "identifier", "ownerIdentifier", "nameApplication", "nameServer", "userShareIdentifier", "publicShareIdentifier", "parentTwoFactoredShareUserIds", "queueState", "delettedApplication", "delettedServer", "dogTagIds", "createdTimeInterval", "modifiedTimeInterval", "modifiedTimeIntervalServer", "anyModifiedTimeIntervalServer", "permission", "syncActionCount", "updateOnServerAction", "updateOnServerAnyModifiedTimeInterval") VALUES (NULL,43432193,2014302209,43432193,'123','123',0,0,'',0,0,0,'',1580875611,1580875611,1580875611,1580875611494527,255,0,0,0)`

`INSERT OR IGNORE INTO "Lists" ("rowIdentifier", "accountUserIdentifier", "identifier", "ownerIdentifier", "nameApplication", "nameServer", "userShareIdentifier", "publicShareIdentifier", "parentTwoFactoredShareUserIds", "queueState", "delettedApplication", "delettedServer", "dogTagIds", "createdTimeInterval", "modifiedTimeInterval", "modifiedTimeIntervalServer", "anyModifiedTimeIntervalServer", "permission", "syncActionCount", "updateOnServerAction", "updateOnServerAnyModifiedTimeInterval") VALUES (NULL,43432193,2014302465,43432193,'456','456',0,0,'',0,0,0,'',1580875616,1580875616,1580875616,1580875616197818,255,0,0,0)`

`INSERT OR IGNORE INTO "Lists" ("rowIdentifier", "accountUserIdentifier", "identifier", "ownerIdentifier", "nameApplication", "nameServer", "userShareIdentifier", "publicShareIdentifier", "parentTwoFactoredShareUserIds", "queueState", "delettedApplication", "delettedServer", "dogTagIds", "createdTimeInterval", "modifiedTimeInterval", "modifiedTimeIntervalServer", "anyModifiedTimeIntervalServer", "permission", "syncActionCount", "updateOnServerAction", "updateOnServerAnyModifiedTimeInterval") VALUES (NULL,43432193,2014302977,43432193,'789','789',0,0,'',0,0,0,'',1580881913,1580881913,1580881913,1580881913934297,255,0,0,0)`

**The first SQLite statement is printed by ten times.
The second and third is printed by once.** 

![image](https://user-images.githubusercontent.com/15372277/73816202-013c3680-4823-11ea-8a07-7829fb7e9a35.png)

```       
try CADatabaseManager.shared.write { (db) in
      try CAList.syncLists(listsToSync,
                               for: userIdentifier,
                               processingClosure: processingClosure,
                               in: db)
} 
```
`listsToSync` is an array for `CAList`, in method `syncLists()`, only check whether is exist in db, if exist, will update, not exist, insert.
`processingClosure` will let user to update `CAList`

**Note: I try to insert record on Navicat Preminum 15 failed too.**

**Comment by groue** [comment]
Hello @archerx3, it looks like there is some flaw in your application, because GRDB is quite able to insert records in the database. If your issue is still not solved, I suggest you simplify your code and check all your assumptions: you will eventually find the flaw.
