### ISSUE TITLE
This repository uses too many softlinks which blocked SwiftPM resolving submodules

### ISSUE THREAD

**Issue by kelvinjjwong** [groue/GRDB.swift#698]
### What did you do?

I tried to use SPM (to replace CocoaPods) to build dependencies. GRDB is one of dependencies.

### What did you expect to happen?

command "swift package generate-xcodeproj" or "swift package update" should complete smoothly.

### What happened instead?

The procedure was blocked at below command when I added "--verbose" to "swift package" command. I have to manually run "git clone" from the exact repository, such as realm-cocoa, fmdb, SQLiteLib, to clone those code to local folder and replace with the name of softlinks.

git -C /Users/kelvinwong/Documents/Develop/mac/PostgresTester/.build/checkouts/GRDB.swift submodule update --init --recursive

Cloning into '/Users/kelvinwong/Documents/Develop/mac/PostgresTester/.build/checkouts/GRDB.swift/Tests/Performance/Realm'...

Cloning into '/Users/kelvinwong/Documents/Develop/mac/PostgresTester/.build/checkouts/GRDB.swift/SQLiteCustom/src'...

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?) GRDB
**GRDB version:** 4.9.0
**Installation method:** (CocoaPods, SPM, manual?) SPM
**Xcode version:** 11.3
**Swift version:** 5.0
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) macOS
**macOS version running Xcode:** Catalina 10.15.2

### Demo Project

mkdir testproj
cd testproj
swift package init
add GRDB as a dependency into Package.swift
swift package update

**Comment by groue** [comment]
Hello @kelvinjjwong. I'm sorry you're experiencing troubles with this repository. You are the first to report such an issue. I'm not sure it has a high priority.

Yet I would be interested in a action plan. Feel free to reopen this issue, and ask questions, if you are willing to contribute.

Thanks.

**Comment by groue** [comment]
FYI, some submodules are removed in #749, in the ongoing effort towards GRDB version 5.
