### ISSUE TITLE
fetchOne() returns nil where there is a Date column

### ISSUE THREAD

**Issue by gimbalg** [groue/GRDB.swift#700]
### What did you do?

Ran a fetchOne() on a table that had a date column

### What did you expect to happen?

Expected the first row to be returned

### What happened instead?

nil was returned by fetchOne()
However a fetchAll() returned the two rows in the table

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 4.9.0
**Installation method: CocoaPods
**Xcode version: 11.3.1 (11C504)
**Swift version: 5
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 10.14.6 (18G103)

### Demo Project

Code snippets:

// Migrator code

        migrator.registerMigration("createWarningMetric") { db in
            try db.create(table: "warningMetric") { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("count", .integer).notNull()
                t.column("date", .datetime).notNull()
            }
        }
        
        migrator.registerMigration("test") { db in
            var warning_metric = WarningMetric(id: nil, count: 28, date: Date())
            try warning_metric.insert(db)
            warning_metric = WarningMetric(id: nil, count: 29, date: Date())
            try warning_metric.insert(db)
        }

// Warning metric code

    struct WarningMetric {
        var id: Int64?
        var count: Int
        var date: Date
    }

// Hashable conformance supports tableView diffing

    extension WarningMetric: Hashable { }

    // MARK: - Persistence

    extension WarningMetric: Codable, FetchableRecord, MutablePersistableRecord {

        // Define database columns from CodingKeys

        private enum Columns {
            static let id = Column(CodingKeys.id)
            static let count = Column(CodingKeys.count)
            static let date = Column(CodingKeys.date)
        }
    
       // Update a warning metric id after it has been inserted in the database.

        mutating func didInsert(with rowID: Int64, for column: String?) {
            id = rowID
        }
    }

// Test code

        try! dbQueue.inDatabase { db in
            let metrics = try WarningMetric.fetchAll(db)
            let metricTop = try WarningMetric.fetchOne(db)
        }

**Comment by groue** [comment]
Hello @gimbalg, thanks for the sample code.

It does not reveal any issue. Particularly, the `let metricTop = try WarningMetric.fetchOne(db)` line returns a non-nil value.

On top of that, I do not understand why your comment mentions Date columns as being special.

I suggest you setup a clearer case if you think you have found an issue with GRDB. Thanks.

**Comment by gimbalg** [comment]
Hello @groue, thanks for getting back.

I've checked again and you're right that a non-nil value is actually returned, though the Xcode debugger was showing it as nil. So it appears to be a feature of the debugger (perhaps as a result of optimisation?) and GRDB is functioning correctly.

Thanks again.

**Comment by gimbalg** [comment]
Hello @groue 

Just realised I didn't answer your question about the Date column. So if 'date' is removed from WarningMetric and elsewhere, the debugger no longer shows nil, but shows the row. So it seems that the debugger doesn't display the correct information when the Date field is included which is what led me to think it was a Date issue, but as discussed it seems to be a debugger issue and GRDB is functioning correctly.

Thanks.
