### ISSUE TITLE
convertFromSnakeCase KeyDecodingStrategy

### ISSUE THREAD

**Issue by JoeLago** [groue/GRDB.swift#701]
### Suggested Contribution
I've inherited a database that uses snake case naming. Unfortunately, this means that I have to define coding keys for every table that has a column with underscores. It would be nice if I could add a `convertFromSnakeCase` decoding strategy like [`JSONDecoder.KeyDecodingStrategy.convertFromSnakeCase`](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase).

### Example
https://github.com/JoeLago/MHWDB-iOS/blob/master/MHWDB/Screens/Item/Models/Item.swift#L20

**Comment by groue** [comment]
Hello @JoeLago, this would be a useful contribution indeed. A pull request will be highly appreciated.

Feel free to reopen if you have any question!
