### ISSUE TITLE
Using the SQLite function 'instr'

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#705]
Quick take: 

I want to convert this raw SQL into a beautiful GRDB query: 
```
select * from master as m where instr(m.subject, 'tea' > 0)
```

To find all occurrences of 'tea' within the subject column.
Not clue if this is 'natively' supported.

**Comment by groue** [comment]
Hi @martindufort 

The `INSTR` function is not natively supported yet.

But from GRDB 4.10 and Swift 5, you can add support for it, thanks to #690:

```swift
func instr(_ lhs: SQLExpressible, _ rhs: SQLExpressible) -> SQLExpression {
    SQLLiteral("INSTR(\(lhs.sqlExpression), \(rhs.sqlExpression))").sqlExpression
}
```

And now, there you go:

```swift
// SELECT "m".* FROM "master" "m" WHERE (INSTR("m"."subject", 'tea')) > 0
let tableAlias = TableAlias(name: "m")
let subjectColumn = Column("subject")
let request = Master
    .aliased(tableAlias)
    .filter(instr(subjectColumn, "tea") > 0)
let masters = try request.fetchAll(db) // [Master]
```

**Comment by martindufort** [comment]
Visually way more pleasing 💯. Thanks

**Comment by groue** [comment]
Happy GRDB!

**Comment by groue** [comment]
Thank you: this was an opportunity to improve the [documentation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md#sql-interpolation-and-the-query-interface) by explicitly showing how to write such a function 👍
