### ISSUE TITLE
Can not find v4.10.0

### ISSUE THREAD

**Issue by HuuLiang** [groue/GRDB.swift#708]
pod search GRDB
-> GRDB.swift (4.9.0)
   A toolkit for SQLite databases, with a focus on application development.
   pod 'GRDB.swift', '~> 4.9.0'
   - Homepage: https://github.com/groue/GRDB.swift
   - Source:   https://github.com/groue/GRDB.swift.git
   - Versions: 4.9.0, 4.8.1, 4.8.0, 4.7.0, 4.6.2, 4.6.1, 4.6.0, 4.5.0, 4.4.0, 4.3.0, 4.2.1, 4.2.0, 4.1.1, 4.1.0, 4.0.1, 4.0.0, 3.7.0, 3.6.2, 3.6.1,
   3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.3.0-beta1, 3.2.0, 3.1.0, 3.0.0, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.1, 2.6.0, 2.5.0, 2.4.2, 2.4.1, 2.4.0, 2.3.1,
   2.3.0, 2.2.0, 2.1.0, 2.0.3, 2.0.2, 2.0, 1.3.0, 1.2.2, 1.2.1, 1.2, 1.1, 1.0, 0.110.0, 0.109.0, 0.108.0, 0.107.0, 0.106.1, 0.105.0, 0.104.0, 0.103.0,
   0.102.0, 0.101.1, 0.101.0, 0.100.0, 0.99.2, 0.99.1, 0.99.0, 0.98.0, 0.97.0, 0.96.0, 0.95.0, 0.94.0, 0.93.1, 0.93.0, 0.92.1, 0.92.0, 0.91.0, 0.90.1,
   0.90.0, 0.89.2, 0.89.1, 0.89.0, 0.88.0, 0.87.0, 0.86.0, 0.85.0, 0.84.0, 0.83.0, 0.82.1, 0.81.2, 0.81.1, 0.81.0, 0.80.1, 0.80.0, 0.79.4, 0.79.3,
   0.79.2, 0.79.1, 0.79.0, 0.78.0, 0.77.0, 0.76.0, 0.75.2, 0.75.1, 0.75.0, 0.74.0, 0.73.0, 0.72.0, 0.71.0, 0.70.1, 0.70.0, 0.69.0, 0.68.0, 0.67.0,
   0.66.0, 0.65.0, 0.64.0, 0.63.0, 0.62.0, 0.61.0, 0.60.1, 0.60.0, 0.59.1, 0.59.0, 0.58.0, 0.57.0, 0.56.2, 0.56.1, 0.56.0, 0.55.0, 0.54.2, 0.54.1,
   0.53.0, 0.52.1, 0.52.0, 0.51.2, 0.51.1, 0.51.0, 0.50.1, 0.50.0, 0.49.0, 0.48.0, 0.47.0, 0.46.0, 0.45.1, 0.45.0, 0.44.0, 0.43.1, 0.43.0, 0.42.1,
   0.42.0, 0.41.0, 0.40.0, 0.39.1, 0.39.0, 0.38.2, 0.38.1, 0.38.0, 0.37.1, 0.37.0, 0.36.0, 0.35.0, 0.34.0, 0.33.0, 0.32.2, 0.32.1, 0.32.0, 0.31.0,
   0.30.0, 0.29.0, 0.28.0, 0.27.0, 0.26.1, 0.26.0, 0.25.0, 0.24.0, 0.23.0, 0.22.0, 0.21.0, 0.20.0, 0.19.0, 0.18.0, 0.17.0, 0.16.0, 0.15.0, 0.14.0,
   0.13.0, 0.12.0, 0.11.0, 0.10.0, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0 [trunk repo]
   - Subspecs:
     - GRDB.swift/standard (4.9.0)
     - GRDB.swift/SQLCipher (4.9.0)

**Comment by groue** [comment]
Hello @HuuLiang,

It looks like I forgot to publish v4.10.0 on CocoaPods. This should be fixed now. Thank you for the report!
