### ISSUE TITLE
JSONEncoder of nil value in MacOS Catalina

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#714]
### What did you do?
Moved a database from MacOS Mojave to MacOS Catalina for an application using GRDB. 

1. The application is fetching a `NULL` value for a JSONEncoded column. 
2. The application updates a different `String` column and saves the change to the database. 
3. The application re-reads the same record later, `nil` value checking fails. 

Looks like the `JSONEncoder` class encoding behavior for `nil` value in Mojave and Catalina is different. 

```swift
import Cocoa

let encoder = JSONEncoder()
let name : String? = nil

let e = try? encoder.encode(name)
```

Executed on MacOS Mojave (10.14.6):
```
e = nil
```

Executed on MacOS Catalina (10.15.2)
```
e = 4 bytes // null 
```

So upon updating records, the database column value with the initial `NULL` value is now replaced with the 4-character string "null". 

This breaks the `nil` value code checking within `ModelClass.init(row:)` function.

### What did you expect to happen?

Not sure this is a GRDB issue but not really sure how to handle this cleanly either.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.2
**Installation method:** CocoaPods
**Xcode version:** 11.3.1
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.15.2

**Comment by groue** [comment]
Hello @martindufort,

Thanks for pointing this out. I'll try to have a look.

**Comment by groue** [comment]
BTW: you can think about a solution and suggest a pull request as well, you know.

**Comment by martindufort** [comment]
Totally !!! Mining the web to find best solution. 

-- 
Martin Dufort

On March 3, 2020 at 08:25:04, Gwendal Roué (notifications@github.com) wrote:

Hello @martindufort,

Thanks for pointing this out. I'll try to have a look.

**Comment by groue** [comment]
This looks like an awful JSONEncoder breaking change, actually. Please also report all versions of the tools you are using.

**Comment by martindufort** [comment]
Tried this XCode playground code on both Mojave and Catalina. 
```swift
import Foundation

let encoder = JSONEncoder()
let name : String? = nil

let e = try? encoder.encode(name)
print(e)

// Print Swift version
#if swift(>=5.2)
print("Swift: 5.2")
#elseif swift(>=5.1)
print("Swift: 5.1")
#elseif swift(>=5.0)
print("Swift: 5.0")
#elseif swift(>=4.2)
print("Swift: 4.2")
#endif
```

## MacOS Mojave
* OS Version (10.14.6)
* XCode (11.3)

*Results*
```
nil
Swift: 5.1
```

## MacOS Catalina 
* OS Version (10.15.2)
* XCode (11.3.1)

*Results*
```
4 bytes
Swift: 5.1
```

**Comment by groue** [comment]
I admit I'd be happier with a GRDB sample code which reveals the issue, so that we can get **straight to the point**. You can for example setup a quick and dirty sample code with an in-memory database:

```swift
struct MyInterestingModel { ... }
let dbQueue = DatabaseQueue()
try dbQueue.write { db in
    // Reveal trouble
}
```

**Comment by groue** [comment]
OK, I've reproduced the JSONEncoder behavior on my mac.

But no GRDB test fails in the only built-in JSON-related feature in GRDB, [JSON columns in codable records](https://github.com/groue/GRDB.swift/blob/master/README.md#json-columns).

In particular, if a codable records has an nil optional property which its JSON-encoded, it is properly encoded as NULL, and properly decoded as nil. See for example [this test](https://github.com/groue/GRDB.swift/blob/db546bf47859fc7eb4c49cef4decea2856286843/Tests/GRDBTests/FetchableRecordDecodableTests.swift#L339-L363).

I thus believe that the problem you are facing lies inside your application code, not inside GRDB.

Please reopen this issue with some code which reliably reproduces the problem if you have some good reason to think that it lies inside GRDB. Thank you!

**Comment by martindufort** [comment]
After triple-checking my stuff, you are totally correct. 

This is an issue that is outside the GRDB framework. 
Thanks for investigating.
