### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ahmedk92** [groue/GRDB.swift#727]
### What did you do?

Execute a `read` on a `DatabaseQueue`.

### What did you expect to happen?

Execute my fetch query or throw an error.

### What happened instead?

GRDB crashes with `Fatal error: Unexpectedly found nil while unwrapping an Optional value `

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.11.0
**Installation method:** CocoaPods
**Xcode version:** 11.3
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15 (19A583)

### Demo Project

Cannot disclose project. But the code that uses GRDB is wrapped in private Swift development cocoapods. I use the private pod from an Objective-C project. **The crash only happens from the Objective-C project; it doesn't crash when I run the Swift demo project for the pod**.

![Screen Shot 2020-03-09 at 8 50 48 PM](https://user-images.githubusercontent.com/11476927/76247677-9a0e0980-6248-11ea-9606-bbae99d2a6a4.png)

**Comment by groue** [comment]
Hello @ahmedk92,

The fatal error happens in the block you provide to GRDB. Not inside GRDB.

It means that a nil optional has been force-unwrapped (`someValue!` with a trailing `!` operator).

In other words, it is in your app that the bug has to be fixed. I suggest you learn about Swift optionals, a topic which is abundantly documented as any Google search will tell you.

**Comment by ahmedk92** [comment]
> I suggest you learn about Swift optionals

I’ve been developing with Swift for four years now 😂

I have no Optionals directly in my implementation. Maybe it’s buried deep somewhere and it’s not easily caught by Xcode. I’ll investigate and return with the results. Thanks for replying.

**Comment by groue** [comment]
Please excuse me if I sounded rude. But, yes, I suggest you better look at the stack trace. After all, the GRDB code in the screenshot is unable to trigger such a fatal error, because it does not force-unwrap any optional. It is irrelevant to the crash.

**Comment by groue** [comment]
Of course, we'll reopen the issue if you spot an actual bug in GRDB, ideally with a way to reproduce it.

**Comment by ahmedk92** [comment]
Some progress on the error. I removed the Cocoapods setup, and integrated my Swift code manually in the ObjC project. I get the following more specific stacktrace:

In the debug console, I get these two lines too:

`[logging] API call with invalid database connection pointer`
`[logging] misuse at line 131400 of [378230ae7f]`

![Screen Shot 2020-03-10 at 5 00 32 PM](https://user-images.githubusercontent.com/11476927/76326148-e57bf280-62f0-11ea-8746-e4d2793df0bf.png)

**Comment by groue** [comment]
All right @ahmedk92.

If we read the error message, we understand that something is **misusing** SQLite. This is bad.

But who is misusing SQLite? Is it GRDB ? Or is it the application, which misuses GRDB by telling it to misuse SQLite?

My advice:

1. I asked you for a way to reproduce the issue. Please tell **how** to get your error if you want more help.

2. Screenshots are, generally, a poor reporting tool. Always report stacktraces instead. You can get one with the `bt` command in the debugger.

3. Think **hard**, **by yourself**, about the error message. Could some connections be used after they are closed? Does your app create several instances of DatabaseQueue for the same database file, despite the Rule 1 of the [Concurrency Guide](https://github.com/groue/GRDB.swift#concurrency), which states:

    > Rule 1: Have a unique instance of DatabaseQueue or DatabasePool connected to any database file.

**Comment by ahmedk92** [comment]
Good news, it's solved! But first, may I reply?

>I asked you for a way to reproduce the issue. Please tell how to get your error if you want more help.

I was trying, it's not that simple. I already have another demo project that uses the exact same code, and it works perfectly.

>Screenshots are, alone, a very poor reporting tool. Always report stacktraces. You can get one with the bt command in the debugger.

Indeed. I didn't know about `bt`. Thanks for the heads up!

> Think hard, by yourself, about the error message. Do you understand what it says?

That's what I've been doing for 1.5 days now. I'm mainly here for support (not necessarily implying there's a bug in GRDB), I hoped you give me a few pointers, and you did regarding concurrency, but it wasn't concurrency related.

The problem was that specific project used an old custom build of sqlcipher. The way it's setup seems to override any reference to sqlite even if used by a dependency (GRDB in our case). GRDB picked *_v3 sqlite functions, while the custom sqlite needed *_v2 ones.

I manually edited `Statement.swift`, and removed the following checks:

```swift
        #if GRDBCUSTOMSQLITE || GRDBCIPHER
        let code = sqlite3_prepare_v3(
            database.sqliteConnection, statementStart, -1, UInt32(bitPattern: prepFlags),
            &sqliteStatement, statementEnd)
        #else
        let code: Int32
        if #available(iOS 12.0, OSX 10.14, tvOS 12.0, watchOS 5.0, *) {
            code = sqlite3_prepare_v3(
                database.sqliteConnection, statementStart, -1, UInt32(bitPattern: prepFlags),
                &sqliteStatement, statementEnd)
        } else {
            code = sqlite3_prepare_v2(database.sqliteConnection, statementStart, -1, &sqliteStatement, statementEnd)
        }
        #endif
```

I left the *_v2 code path, specifically: `code = sqlite3_prepare_v2(database.sqliteConnection, statementStart, -1, &sqliteStatement, statementEnd)`, and it worked!

**Comment by groue** [comment]
@ahmedk92, it looks like you mismatch free support and free work. My free time is not dedicated to guessing what happens in your app from imprecise inputs, nor solving your specific troubles.

**Comment by ahmedk92** [comment]
I didn't intend to mean what you may have understood. I just post a question, if you or anyone have the time to help it's good. I don't expect an immediate support. I'm not paying for anything, so I don't have that high bar of expectations. I'm aware of that. I'm not a choosing beggar.

GRDB is the best sqlite library for Swift in my opinion. And I really appreciate your immediate replies. I'm afraid to say this, but I doubt I'm going to pick GRDB again as I'm not feeling fine reading this condescending replies (you apologized for the first reply, and I accepted that wholeheartedly as I respect the pressure to maintain such a well-used piece of software). Also, while I was debugging I noticed a similar tone in the [comments](https://github.com/groue/GRDB.swift/blob/039dd3775920d3205607b781e091cd6a49587068/GRDB/Core/Database.swift#L405). I don't think this is cool.

Thank you for this good library and for the help, and I'm sorry if I bothered you.
