### ISSUE TITLE
Static library target

### ISSUE THREAD

**Issue by cfilipov** [groue/GRDB.swift#74]
Currently it's not possible to use 3rd party frameworks with command line xcode targets. It would be helpful to have a static library target for GRDB.

**Comment by groue** [comment]
Sure, that's a good idea!

**Comment by groue** [comment]
BTW, @cfilipov: do you have the need for such a command line utility?

**Comment by cfilipov** [comment]
Yes. I am trying to write a command line companion to an app I have. The idea is that all the lower level bits for querying data from SQLite and running reports is done in a library which can be shared by the command line tool and the app. Right now I have three options:

1. Link to the GRDB.framework in the command line tool and copy it to the user frameworks directory. This means an install step would be required.
2. Copy the sources from GRDB into the base library shared by the app and the command line tool. This is not ideal since GRDB is not part of the code but it can be mitigated by creating a modulemap to at least have some separation. This is what I'm doing now. The benefit is that the command line tool is a standalone binary.
3. Create a static library of GRDB and link that to the command line tool. This is a lot of extra mantenence for me to maintain a fork that has a static lib.

**Comment by groue** [comment]
OK. I suppose your companion runs on macOS, doesn't it?

Do you feel comfortable submitting a pull request? Ideally it would contain a static lib target for macOS, a test target that run all tests of the GRDBOSXTests target, and installation instructions.

**Comment by cfilipov** [comment]
Perhaps. I'm still considering the first option, just installing the framework, since that's actually simpler. Also, using the second option with a modulemap isn't actually as bad as I expected, because then I can benefit from whole-module optimization (which as far as I understand doesn't happen across framework boundaries right now). If I end up doing the static lib, I will send a pull request knowing you are open to it.

**Comment by groue** [comment]
Yes, I'm open to it - yet I'd really like to rely on automated tests in order to avoid regressions in it. Let's wait for a PR, then! Thanks, @cfilipov.
