### ISSUE TITLE
Rename GRDBCustomSQLite to GRDB for compatibility with dependents?

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#743]
Would you mind elaborating on why GRDB with a custom SQLite build has a different module name from the ordinary GRDB? I ask because there is a major practical problem with the current convention. As-is, no framework that imports "GRDB" (e.g. GRDBCombine) is source compatible with GRDBCustomSQLite. Yet I don't understand why the underlying implementation of SQLite should be reflected in the module name, as long as the underlying code is API-compatible.

Even in my app's source code, I don't see a reason it needs to know whether I'm linking against the implementation of GRDB with the standard SQLite build or an implementation with a custom SQLite build—except for where I'm using the custom interface. But shouldn't those differences be restricted to the smallest possible API surface area?

**Comment by groue** [comment]
Hello @mallman,

This name was picked in #62 and has not changed since.

GRDBCipher was eventually renamed to GRDB in v4.0.0.

Well, GRDBCustomSQLite will be renamed to GRDB in v5.0.0, all right 👍 

You can check #718 for the progress.

**Comment by groue** [comment]
Fixed in #747 and #756

**Comment by groue** [comment]
Fixed in v5.0.0-beta
