### ISSUE TITLE
Statement: CREATE TABLE IF NOT EXISTS 

### ISSUE THREAD

**Issue by thdlx** [groue/GRDB.swift#746]
### What did you do?

func createReportsDB(dbQueue:DatabaseQueue, table:String) throws {
    do {
        try dbQueue.write { db in
            try db.execute(literal: """
            CREATE TABLE IF NOT EXISTS \(table) (id integer PRIMARY KEY,Date text,Activity text,DateDep integer,DateArr integer,CheckIn integer,CheckOut integer,LieuDep text,LieuArr text,AcType text,AcVersion text,Cat text,DutyDesignator text,Misc1 text,Misc2 text,Vol text, HeureCheckIn float, HeureDep float, HeureArr float, HeureCheckOut float);
            """)
        }
    } catch let error as DatabaseError {
        throw error
    }
}

### What did you expect to happen?

Create a table with provided values.
### What happened instead?
Can't figure why this error happened; as I've tested the statement and it's OK with SQLPro app.

[logging] near "?": syntax error in "CREATE TABLE IF NOT EXISTS ? (id integer PRIMARY KEY,Date text,Activity text,DateDep integer,DateArr integer,CheckIn integer,CheckOut integer,LieuDep text,LieuArr text,AcType text,AcVersion text,Cat text,DutyDesignator text,Misc1 text,Misc2 text,Vol text, HeureCheckIn float, HeureDep float, HeureArr float, HeureCheckOut float);"

### Environment

**GRDB flavor(s): GRDB
**GRDB version:** 4.11.0
**Installation method:** CocoaPods
**Xcode version:** 11.2
**Swift version:** 5.0
**Platform(s) running GRDB:** iOS Simulator 13.2
**macOS version running Xcode:** macOS 10.14.4

**Comment by groue** [comment]
Hello @thdlx.

Replace the `literal` argument name with `sql`, and the error will be fixed.

When you build your own SQL strings, always use the `sql` argument name.

Only use the `literal` argument name when you want to use [SQL interpolation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md).

Hint: see how the table name was replaced with `?` in the SQL reported with the error. Such a `?` is an SQL parameter, a placeholder for a value. Indeed this is an SQL syntax error.

**Comment by thdlx** [comment]
Hi Gwendal.
Thanks for your quick reply, you give me the answer, my problem is fixed !!
Regards,
Thierry
