### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by cfilipov** [groue/GRDB.swift#75]
Any plans to use spm in the Swift3 branch? I realize there is a [PackageManager](https://github.com/groue/GRDB.swift/tree/PackageManager) branch but it is quite out of date. 

By the way, getting spm to work would solve #74 for free.

**Comment by groue** [comment]
Hello @cfilipov. Please see #72 which also asks for SPM support.

TL;DR: Nothing against SPM, but:

1. Unless I'm mislead, server is the main target of SPM nowadays, even more than command-line tools (#74). And GRDB has not been fool-proofed for the server.
2. Maintaining it is lot of work

Please add your comments to #72 if you have any.
