### ISSUE TITLE
unlock with wrong password gives wrong error

### ISSUE THREAD

**Issue by haemi** [groue/GRDB.swift#751]
when trying to unlock the database with a wrong password, I get the following GRDBError:

```
▿ SQLite error 26 with statement `SELECT * FROM sqlite_master LIMIT 1`: file is not a database
  ▿ extendedResultCode : 26 (file is not a database)
    - rawValue : 26
  ▿ message : Optional<String>
    - some : "file is not a database"
  ▿ sql : Optional<String>
    - some : "SELECT * FROM sqlite_master LIMIT 1"
  - arguments : nil
```

Is this intentionally? Isn't it possible to throw a more specific error in that case?

**Comment by groue** [comment]
Hello @haemi,

[SQLITE_NOTADB (26)](https://www.sqlite.org/rescode.html#notadb) is the error code returned by SQLCipher when the passphrase is wrong. You can't really get more specific.

You can catch it:

```swift
do {
    dbQueue = try DatabaseQueue(path: "...", configuration: configuration)
} catch let error as DatabaseError where error.resultCode == .SQLITE_NOTADB {
    // Handle unreadable file format, including wrong password
}
```

**Comment by haemi** [comment]
Hi @groue , thanks a lot for the quick response!
