### ISSUE TITLE
Get values from a row in another table using foreign key

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#762]
Two questions: 
1) Is it possible to get values from a different table using foreign keys?
2) If this ^ is possible, how can I make it the latest row from that other table?
Maybe this question is more about SQL than GRDB.

Table Chats
- id (PK)
- lastMessage: Int (FK for Message.id)

Table Messages
- id (PK)
- chatId (FK for Chat.id)
- content: String

Considering I have dozens of messages, i want that 'lastMessage' points to the latest row from Message table that has that chat id.

When I used Parse (rest in peace), i could set include=Messages and it would bring me the its values along with the Chat.

Thanks.

**Comment by groue** [comment]
Hello @brunomunizaf,

What is your question? Maybe this one below?

How can I fetch from the database a list of chats, along with their latest message, in order to feed the classic screen of chat apps: the list of latest conversations with a preview of the latest message?

**Comment by brunomunizaf** [comment]
Hi @groue,

I bet you read a lot of malformed questions here right? My apologies. But yea, this is what I meant to ask.

Thanks for the support.

**Comment by groue** [comment]
Oh yes @brunomunizaf, making educated guesses is definitely part of the maintainer job ;-) I'm happy we're on the same track now.

Your question is simple, but it's indeed an SQL challenge at its root. I don't have any ready-made answer yet.

But it's a classic use case, so I'm quite interested in shaping a canonical GRDB answer to it. Please stay tuned.

**Comment by groue** [comment]
Hello again, @brunomunizaf,

You wrote:

> Table Chats
> 
> - id (PK)
> - lastMessage: Int (FK for Message.id)

**So there already exists a foreign key from one chat to its latest message.** We don't have to look for the message with the most recent date, for example.

So this is not as special a case as I thought. That's cool, because it will be easier!

This foreign key can just feed a regular [belongsTo](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#belongsto) association. I suggest you learn about the different kinds of associations. They allow GRDB to turn the foreign keys defined in the database schema into Swift code, for your benefit.

Here is a sample code:

```swift
// A DatabaseMigrator which defines the database schema
var migrator = DatabaseMigrator()
migrator.registerMigration("chats") { db in
    try db.create(table: "chat") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("latestMessageId", .integer)
            .references("message", column: "id", onDelete: .setNull)
    }
    
    try db.create(table: "message") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("chatId", .integer)
            .notNull()
            .references("chat", onDelete: .cascade)
        t.column("content", .text)
    }
}

// Set up the database
let dbQueue = DatabaseQueue()
try migrator.migrate(dbQueue)

// Define the record types for the chat and message tables
struct Message: Codable, TableRecord, FetchableRecord, PersistableRecord {
    var id: Int64
    var chatId: Int64
    var content: String
}

struct Chat: Codable, TableRecord, FetchableRecord, PersistableRecord {
    // The latestMessage association.
    //
    // It uses an explicit "latestMessage" key in order to replace the
    // default key which would be "message". This makes it possible to
    // decode that message in a Swift struct that has a property
    // properly named "latestMessage". See ChatInfo below.
    static let latestMessage = belongsTo(Message.self, key: "latestMessage")
    var id: Int64
    var latestMessageId: Int64?
}

// Populate the database
try dbQueue.write { db in
    var chat1 = Chat(id: 1, latestMessageId: nil)
    try chat1.insert(db)
    for messageId in Int64(1)...3 {
        try Message(id: messageId, chatId: chat1.id, content: "Hello \(messageId)").insert(db)
    }
    try chat1.updateChanges(db) { $0.latestMessageId = 3 }
    
    var chat2 = Chat(id: 2, latestMessageId: nil)
    try chat2.insert(db)
    for messageId in Int64(4)...6 {
        try Message(id: messageId, chatId: chat2.id, content: "Hello \(messageId)").insert(db)
    }
    try chat2.updateChanges(db) { $0.latestMessageId = 6 }
    
    try Chat(id: 3, latestMessageId: nil).insert(db)
}

// Fetch all chats with their latest message
try dbQueue.read { db in
    struct ChatInfo: Decodable, FetchableRecord {
        var chat: Chat
        var latestMessage: Message?
    }
    
    let chatInfos = try Chat
        .including(optional: Chat.latestMessage)
        .asRequest(of: ChatInfo.self)
        .fetchAll(db)
    
    // Prints:
    // - latest message from chat 1: Hello 3
    // - latest message from chat 2: Hello 6
    // - latest message from chat 3: -
    for chatInfo in chatInfos {
        print("latest message from chat \(chatInfo.chat.id): \(chatInfo.latestMessage?.content ?? "-")")
    }
}
```

**Comment by brunomunizaf** [comment]
This is exactly what I needed - so much simpler than using straight SQLite framework. I wonder if Apple will ever incorporate it into iOS SDK. 

Thank you very much @groue

**Comment by groue** [comment]
Happy GRDB, @brunomunizaf!

FYI, things would have been less easy if the `lastMessageId` foreign key were not there, and if you had to load, for example, the last message sorted by date. This is the subject of #767.
