### ISSUE TITLE
Encoding and decoding date results in different values

### ISSUE THREAD

**Issue by jcavar** [groue/GRDB.swift#763]
### What did you do?

Write date to database and read it.

### What did you expect to happen?

Compared written and read dates should be the same.

### What happened instead?

Compared dates are different.

### Environment

**GRDB flavor(s):** SQLCipher
**GRDB version:** 4.9.0
**Installation method:** CocoaPods
**Xcode version:** 11.4.1
**Swift version:** 5
**Platform(s) running GRDB:** (OS
**macOS version running Xcode:** 10.15.3

### Demo Project

Unit test reproducing issue

```
    func testDates() throws {
        let queue = DatabaseQueue()
        try queue.write { database in
            try database.create(table: "player", ifNotExists: true) { table in
                table.column("date", .text)
            }
        }
        let date = Date()
        let dateDb = try self.queue.write({ db -> Date in
            try db.execute(sql: "INSERT INTO player (date) VALUES (?)", arguments: [date])
            let row = try Row.fetchOne(db, sql: "SELECT * FROM player")!
            let date: Date = row["date"]
            return date
        })
        print(date.timeIntervalSinceReferenceDate)
        print(dateDb.timeIntervalSinceReferenceDate)
        XCTAssertEqual(date, dateDb)
    }
```

This prints:

```
608742427.539547
608742427.54
```
so it seems like GRDB date encoder rounds to lower number of decimal places (sometimes 2, sometimes 3).

**Comment by groue** [comment]
Hello @jcavar,

Please see #492 for an explanation of why you witness an expected behavior, a discussion about the available date storage options, and some general advice regarding comparing dates for equality.

**Comment by jcavar** [comment]
Wow, thank you, that makes sense now!

**Comment by groue** [comment]
Thanks for your cooperation in front of the nasty topic of dates, @jcavar :-)
