### ISSUE TITLE
What is the safest way to use sqlite date functions with arguments?

### ISSUE THREAD

**Issue by simensol** [groue/GRDB.swift#765]
In the [Avoiding SQL Injection](https://github.com/groue/GRDB.swift#avoiding-sql-injection) part of the documentation, we are told not to do:
```
try db.execute(sql: "UPDATE students SET name = '\(name)' WHERE id = \(id)")
```

However, working with date functions in sqlite, the following doesn't work:
```
try db.execute(sql: "UPDATE students SET date = DATETIME(CURRENT_TIMESTAMP, '+? hours')", arguments: [5])
```

While this works:
```
let hours = 5

try db.execute(sql: "UPDATE students SET date = DATETIME(CURRENT_TIMESTAMP, ?)", arguments: ["+\(hours) hours"]")
```
However, the last approach seems to be vulnerable to SQL injection. What is the safest way to use sqlite date functions with arguments?

**Comment by groue** [comment]
Hello @simensol,

Your third version is totally immune to SQL injection, you're good to go.

If you are not convinced, or if you are looking for a better understanding, *try to attack*: feed your app code with nasty values, attempt to break your app. Use your imagination! This is quite funny, and you'll get better at understanding what all this fuss is about.

**Comment by simensol** [comment]
Alright, thanks (again) @groue!
