### ISSUE TITLE
WAL mode and AUTO_VACUUM read error

### ISSUE THREAD

**Issue by johnkassebaum** [groue/GRDB.swift#768]
First off, GRDB is a lovely tool. Thank you so much.

### What did you do?

File: `Database.swift`:
```
import Foundation
import GRDB

protocol DatabaseMigrationInfo: RawRepresentable, CaseIterable, CustomStringConvertible {
    typealias MigrationSteps = (_ database: Database) throws -> Void
    var migrationSteps: MigrationSteps { get }
    var description: String { get }
    static var migrator: DatabaseMigrator { get }
}

struct Item: Codable, FetchableRecord, MutablePersistableRecord {
    let itemKey: Int64
    let itemName: String
    
    enum CodingKeys: String, CodingKey, ColumnExpression {
        case itemKey = "item_key"
        case itemName = "item_name"
    }
    
    static var databaseTableName: String { return "item" }
}

class ItemDatabase {
    enum Migration: Int, DatabaseMigrationInfo {
        case item
        
        var description: String {
            switch self {
            case .item: return "item"
            }
        }
        
        var migrationSteps: ((_ database: Database) throws -> Void) {
            switch self {
            case .item:
                return { database in
                    try database.create(table: Item.databaseTableName) { table in
                        table.column(Item.CodingKeys.itemKey.rawValue, .integer).primaryKey()
                        table.column(Item.CodingKeys.itemName.rawValue, .text).notNull()
                    }
                }
            }
        }
        
        static var migrator: DatabaseMigrator = {
            var migrator = DatabaseMigrator()
            Migration.allCases.forEach { migrator.registerMigration($0.description, migrate: $0.migrationSteps) }
            return migrator
        }()
    }
    
    let pool: DatabasePool
    
    init(filePath: String) throws {
        var config = Configuration()
        config.prepareDatabase = { database in
            try database.execute(sql: "PRAGMA auto_vacuum = FULL")
        }
        
        let pool = try DatabasePool(path: filePath, configuration: config)
        try Migration.migrator.migrate(pool)
        self.pool = pool
    }
}
```
File `ViewController.swift`:
```
import UIKit
import GRDB

class ViewController: UIViewController {
    var itemStore: ItemDatabase!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let storePath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("ItemStore.sqlite")
        
        try? FileManager.default.removeItem(at: storePath)
        
        do {
            itemStore = try ItemDatabase(filePath: storePath.path)
            let rowCount = try itemStore.pool.read {
                try Item.fetchCount($0)
//                try Int.fetchOne(database, sql: "SELECT COUNT(*) FROM \(Item.databaseTableName)")
            }
            print("rowCount=\(rowCount)")
        } catch {
            print("error=\(error)")
        }
    }
}
```

### What did you expect to happen?

Expected output:
`rowCount=0`

### What happened instead?

Actual output:
```
error=SQLite error 8 with statement `PRAGMA auto_vacuum = FULL`: attempt to write a readonly database
```

Note: if the database is created without the configuration (`let pool = try DatabasePool(path: filePath)`), then get the expected output.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.14.0
**Installation method:** CocoaPods
**Xcode version:** 11.14.1
**Swift version:** 5
**Platform(s) running GRDB:**  iOS
**macOS version running Xcode:** 10.15.4

**Comment by groue** [comment]
Hello @johnkassebaum,

SQLite won't accept to run this pragma from a read-only connection, as clearly explained by the error message.

Your application runs this pragma from the [prepareDatabase](http://groue.github.io/GRDB.swift/docs/4.14/Structs/Configuration.html#/s:4GRDB13ConfigurationV15prepareDatabaseyAA0D0CKcSgvp) configuration function, which is run whenever an SQLite connection is opened, including read-only connection used by `DatabasePool.read`.

This is the reason for your error.

Maybe try to move this pragma in ItemDatabase.init:

```swift
init(filePath: String) throws {
    let pool = try DatabasePool(path: filePath)
    try Migration.migrator.migrate(pool)
    try pool.write { database in
        try database.execute(sql: "PRAGMA auto_vacuum = FULL")
    }
    self.pool = pool
}
```

**Comment by groue** [comment]
Since DatabasePool currently never closes its writer connection, you can be sure that the vacuum won't be forgotten in the DatabasePool life time. But you may prefer to use prepareDatabase again:

```
var config = Configuration()
config.prepareDatabase = { database in
    if database.configuration.readonly == false {
        try database.execute(sql: "PRAGMA auto_vacuum = FULL")
    }
}
```

This should be more robust against future versions of GRDB.

**Comment by johnkassebaum** [comment]
Thanks so much. After your first message I was working on the latter.  Thanks for the super fast feedback!

**Comment by groue** [comment]
Happy GRDB @johnkassebaum !

**Comment by johnkassebaum** [comment]
Happy GRDB to you @groue !!

**Comment by groue** [comment]
Reading https://www.sqlite.org/pragma.html#pragma_auto_vacuum, it looks like one can't run this pragma whenever one wants:

> Auto-vacuuming is only possible if the database stores some additional information that allows each database page to be traced backwards to its referrer. Therefore, auto-vacuuming must be turned on before any tables are created. It is not possible to enable or disable auto-vacuum after a table has been created.

Reading this, I think `prepareDatabase`, as in https://github.com/groue/GRDB.swift/issues/768#issuecomment-619149775, is the only correct way to go.

And make sure you check that the database exhibits the expected vacuum behavior!

**Comment by johnkassebaum** [comment]
Hmm, that is interesting.  I recall reading somewhere that `AUTO_VACUUM` could be randomly enabled but would first perform a `VACUUM` operation, which tho may fail if there is insufficient drive space to copy the data to new pages. But even so I preferred the configuration at creation.  Thanks so much for your continued feedback!

**Comment by johnkassebaum** [comment]
Following up: `AUTO_VACUUM` is working as expected. Nice work!
