### ISSUE TITLE
Crash at NativeSet.copyAndResize

### ISSUE THREAD

**Issue by fmnavarretem** [groue/GRDB.swift#769]
### What did you do?

Currently the crash report has been reporting a fatal issue in different devices, I can't reproduce the crash on my devices. The report says:

<compiler-generated> - Line 124
specialized _NativeSet.copyAndResize(capacity:) + 124

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:** 4.7.0
**Installation method:** (CocoaPods)
**Xcode version:** 11.3.1
**Swift version:** 5
**Platform(s) running GRDB:** (iOS)
**macOS version running Xcode:** 10.15.1

**Comment by groue** [comment]
Hello @fmnavarretem,

This issue does not contain any information that links your crash to GRDB.

**Comment by fmnavarretem** [comment]
Thanks for your answer, I share with you my crash report. This have never  happened before just when I update the GRDB version.

<img width="979" alt="Screen Shot 2020-04-28 at 9 42 17 AM" src="https://user-images.githubusercontent.com/25638602/80501093-a3585000-8934-11ea-8321-cda1cf34ae8f.png">

**Comment by groue** [comment]
That's better, but with such incomplete information, there is still no way to give you any hand.

> I can't reproduce the crash on my devices.

Try harder. Share the results of your investigations, thank you.
