### ISSUE TITLE
How to add GRDBCipher in project?

### ISSUE THREAD

**Issue by dat-dt** [groue/GRDB.swift#77]
i installed GRDB using manually, i feeling happy when import with GRDB, but the problem is when i import GRDBCipher and running then show failed built. Please help me! i'm very want using SQLiteCipher for GRDB in my project.

**Comment by groue** [comment]
Hello @Datithaui. Please tell me:

1. which [installation procedure](https://github.com/groue/GRDB.swift#installation) you have chosen.
2. at which step of the installation procedure you have a problem.
3. the precise nature of the problem, with all error messages and details you can give.

**Comment by Datithaui** [comment]
1. i was used to install Manually
2. i was passed the steps
3. Everything good when added GRDB in my project. but when I do the same thing to added GRDBCipher in my project...everything worse. you can see when I was running the project...
<img width="711" alt="screen shot 2016-07-01 at 9 27 18 pm" src="https://cloud.githubusercontent.com/assets/10258252/16524530/d5a051de-3fd2-11e6-8cd1-b005784d1d98.png">
<img width="695" alt="screen shot 2016-07-01 at 9 27 43 pm" src="https://cloud.githubusercontent.com/assets/10258252/16524547/e643a4e6-3fd2-11e6-9705-677cd963a010.png">
<img width="1038" alt="screen shot 2016-07-01 at 9 29 52 pm" src="https://cloud.githubusercontent.com/assets/10258252/16524621/fc693696-3fd2-11e6-816f-6a8d234ba8eb.png">

**Comment by groue** [comment]
I can see nice images, but not the error itself. A good report contains error *messages*, not a screenshot. Look for the detailed error log.

**Comment by Datithaui** [comment]
failed here: <GRDBCipher/sqlite3.h> not found. why? please explans with me?
<img width="1240" alt="screen shot 2016-07-01 at 10 13 12 pm" src="https://cloud.githubusercontent.com/assets/10258252/16525971/31791698-3fd9-11e6-844b-5112962cede6.png">

**Comment by groue** [comment]
Try this:

1. Download GRDB submodules: `git submodule update --init`
2. Remove GRDB from Embedded Binaries and Linked Frameworks. Keep GRDBCipher.

**Comment by groue** [comment]
No news, good news!

**Comment by dat-dt** [comment]
Sorry for my late reply. i tried and succeeded, but when i used it to encrypt then show up the error message: "fatal error: 'try!' expression unexpectedly raised an error: SQLite error 26: file is encrypted or is not a database". While database with me is sqllite database and previous unencrypted.
<img width="1280" alt="screen shot 2016-07-05 at 4 49 20 pm" src="https://cloud.githubusercontent.com/assets/10258252/16580833/863f70ce-42d0-11e6-8050-3ad1f53fb156.png">

**Comment by groue** [comment]
Hello @dat-dt 

I'm happy that you could compile and run GRDBCipher.

Now you have a second error. This error means that SQLite could not decrypt the database with the key you have provided.

Maybe the key is wrong. Or, more likely, the database already exists, and is not encrypted.

It is a classic mistake : SQLCipher can setup a new encrypted database, or change the passphrase of an existing encrypted database. But it can not encrypt an existing clear-text database.

That's the way it is.

You have two options:

1. Erase your existing database, and recreate a new encrypted one.
2. [Copy](https://github.com/groue/GRDB.swift#backup) the content of your existing database into a new encrypted one.

**Comment by groue** [comment]
@dat-dt, please read the updated documentation of encrypted databases: https://github.com/groue/GRDB.swift#encryption. It will answer your last questions, I hope.

**Comment by dat-dt** [comment]
Thanks @groue . I'll try it 👍

**Comment by dat-dt** [comment]
hi @groue , i was succcessful. So, i have a question: how to open database encrypted to read and write?
If possible, can you give me an example where you made? thank you very much :)

**Comment by groue** [comment]
You access encrypted databases just like regular databases. What about reading some [documentation](https://github.com/groue/GRDB.swift#documentation) now?

**Comment by dat-dt** [comment]
Error when i access encrypted database, i'm using syntax: 
let dbQueue = try DatabaseQueue(path: "/path/to/database.sqlite") to connection the database after successfully encrypted.
Still error show: "fatal error: 'try!' expression unexpectedly raised an error: SQLite error 26: file is encrypted or is not a database"

**Comment by groue** [comment]
You need to learn about file management. "/path/to/database.sqlite" is an example path for documentation purpose. It is not a valid path.

Let's me be clear: I don't have to time to be your iOS/macOS teacher.

See https://github.com/groue/GRDB.swift/issues/7 for a hint (this user had a problem similar to yours). And go learn your operating system. I'll be happy answering your questions, as long as they are about GRDB.

**Comment by groue** [comment]
You need to learn about file management. "/path/to/database.sqlite" is an example path for documentation purpose. It is not a valid path.

Let's me be clear: I don't have to time to be your iOS/macOS teacher.

See https://github.com/groue/GRDB.swift/issues/7 for a hint (this user had a problem similar to yours). And go learn your operating system. I'll be happy answering your questions, as long as they are about GRDB.

**Comment by dat-dt** [comment]
perfect! thanks @groue. 
I misused passpharse :D
