### ISSUE TITLE
Can the WAL mode files creation (-shm and -wal) be avoided in read-only access ?

### ISSUE THREAD

**Issue by spicymatt** [groue/GRDB.swift#771]
First of all, thank you for your amazing work. 
GRDB is the foundation of our work here and we are more than happy with its robustness and quality...
Then, sorry if this is a _naive question_.

Is it possible to prevent the wal mode files (-wal, -shm) files from being created when accessing a database in **read-only** mode
```
var config = Configuration()
config.readonly = true
etc...
```
I am not referring to the persistence of those files like in #739 but to their creation during the lifetime of the app. 
We are in a sandboxed MacOS app, and are accessing databases that are potentially in many different places. In theory, we would only need **read** access to those folders because we never write to the databases. But the -wal,-shm file creation means that we need write-access to those folders. It is not really a blocker, but adding write permission to app entitlements raises always more concerns.
It looks like WAL mode goes beyond write transactions and is also used when accessing for read transactions. I was just curious if not creating those files was at all possible.

Thanks

### What did you do?

Access a database in read-only mode.

### What did you expect to happen?

Wondering if -shm and -wal file creation could be avoided.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:**4.8.1
**Installation method:** Manual
**Xcode version:11.3
**Swift version:5.x
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.14

**Comment by groue** [comment]
Hello @spicymatt,

Is it possible to access a WAL database, even from read-only connections, without write permission to the file system? According to https://www.sqlite.org/wal.html, readers impact writers, and I don't see any other communication channel than the file system.

Maybe you can't use the WAL mode.

**Comment by groue** [comment]
For the record, GRDB only activates the WAL mode for read/write DatabasePool. This means that DatabaseQueue, and read-only DatabasePool won't activate the WAL mode, and won't trigger the creation of -shm and -wal files (unless the database has been put in the WAL mode by some other means).

**Comment by spicymatt** [comment]
hello @groue 
Thanks for answering. After reading your last comment, I double checked my code as I was seeing those files being created for a read-only DatabasePool. But it was my mistake, as there was a path through the code where the readonly flag was unset. My bad!
Regarding your first comment, I did not realize that having an enclosing folder with read-only access could pave the road for lots of trouble even when accessing the DB in read-only mode, when WAL is set. I need to experiment more. Thanks for the heads-up.

**Comment by groue** [comment]
> Regarding your first comment, I did not realize that having an enclosing folder with read-only access could pave the road for lots of trouble even when accessing the DB in read-only mode, when WAL is set.

Actually, I'm not quite sure. I've made a few tests on my machine, with an external unix user having only r/o access to the db directory, but they were inconclusive. I'm not quite sure of the test scenario, actually. We want... to make sure that a reader that has no write access can acquire a lock (by opening a deferred transaction and reading *something*) which prevents a writer from checkpointing?

(Yeah, sorry, this is all [WAL jargon](https://www.sqlite.org/wal.html)).

You're right that we need more experiments in order to conclude with anything.

BTW, I was fast in my first replies:

> GRDB is the foundation of our work here and we are more than happy with its robustness and quality...

This is very nice, thank you very very much :-)

**Comment by groue** [comment]
@spicymatt, we may get a conclusive answer from https://sqlite.org/forum/forummain. They are very helpful. Do you feel like asking there? If so, just make sure you ask an SQLite/unix question, because Swift, iOS, and GRDB are not quite relevant here. I'll do it if you prefer.

**Comment by spicymatt** [comment]
@groue I'll try the sqlite forum with your guidelines and keep you posted. Making conclusive tests seems challenging but I'll try to devise a scenario.

**Comment by groue** [comment]
https://sqlite.org/forum/forumpost/0ba094491f

**Comment by groue** [comment]
(my curiosity is hungry)

**Comment by spicymatt** [comment]
it seems ;-) sorry I wasn't as fast (in the middle of a release...)

**Comment by groue** [comment]
Initially I wanted to wait but eventually I could not resist :-) Lockdown is boring at times ;-)

**Comment by groue** [comment]
All right, D. Richard Hipp himself has answered. Here is a summary:

1. YES a read-only process can access a WAL database, without any ill side effects (I still don't know how it works).
2. BUT such a connection *requires* that the -wal and -shm files are present before it starts reading.

**Comment by spicymatt** [comment]
Very active thread and interesting read on that forum. Thanks for channeling those discussions and getting a precise answer. Amazing.
So:
- if I am accessing a WAL database in read-only mode, in a folder that is readonly, it should work ok provided that the -shm and -wal files are present before the reads;
But suppose I am accessing a NON-WAL database with a DatabasePool.
If I forget to set the readonly flag in the configuration, the DatabasePool will set the journal_mode to WAL (as per the documentation), won't it ? So even if I intend to only perform reads, the connection will fail ?
Maybe I should experiment...

**Comment by groue** [comment]
> Amazing.

Come on, this thread is a joke, and I'm a very poor interviewer 😞 

There is a sure fact: a reader without unix write permission CAN NOT read from a WAL database when the -wal and -shm files are not present. This I could test, in the terminal, with two unix users.

There is a second sure fact: a writer is supposed to delete the -wal and -shm files when it closes the last connection to the database (this is the topic of #739).

Conclusion: WAL is unsuitable when some readers without unix write permission may come at any time, because of the chance that -wal and -shm files are not present.

**Comment by groue** [comment]
> There is a sure fact: a reader without unix write permission CAN NOT read from a WAL database when the -wal and -shm files are not present. This I could test, in the terminal, with two unix users.

Failure case:

```
other@Gauvain ~ % ls -l /Users/groue/test_wal*  
-rw-r--r--  1 groue  staff  8192 May  6 06:59 /Users/groue/test_wal.sqlite

other@Gauvain ~ % sqlite3
sqlite> .open --readonly  /Users/groue/test_wal.sqlite
sqlite> select count(*) from t;
Error: unable to open database file
```

Success case:

```
other@Gauvain ~ % ls -l /Users/groue/test_wal*
-rw-r--r--  1 groue  staff   8192 May  6 07:02 /Users/groue/test_wal.sqlite
-rw-r--r--  1 groue  staff  32768 May  6 07:02 /Users/groue/test_wal.sqlite-shm
-rw-r--r--  1 groue  staff      0 May  6 07:02 /Users/groue/test_wal.sqlite-wal

other@Gauvain ~ % sqlite3
sqlite> .open --readonly  /Users/groue/test_wal.sqlite
sqlite> select count(*) from t;
7
```

**Comment by groue** [comment]
OMG I missed this paragraph in the doc:

> If the application invokes [sqlite3_file_control](https://www.sqlite.org/c3ref/file_control.html)([SQLITE_FCNTL_PERSIST_WAL](https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal)) on the database connection prior to closing, then the final checkpoint is still run but the WAL and WAL-index files are not deleted as they normally would be. This leaves the database in a state that allows other processes without write permission on the database, WAL, or WAL-index files to open the database read-only. If the WAL and WAL-index files are missing, then a process that lacks permission to create and initialize those files will not be able to open the database, unless the database is designated as immutable using the immutable query parameter.

Not only does it answers our question, and confirms that write permission is necessary for reading. It also provides an escape plan that makes sure the -wal and -shm are available.

**Comment by groue** [comment]
All right, the SQLITE_FCNTL_PERSIST_WAL flag does control whether the -wal and -shm files are left when a database pool closes ([see tests](https://github.com/groue/GRDB.swift/blob/db7fb961423e2a3b77302eb5dfba07b7f5912a57/Tests/GRDBTests/DatabasePoolTests.swift)). I think this will be very interesting for @mallman and @scottandrew as well.

So. If one wants:

1. A WAL database
2. With readers that do not have system-level write permission on the database

Then one should activate the [persistent WAL mode](https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal).

To do so, I suggest the following sample code:

```swift
var configuration = Configuration()
configuration.prepareDatabase = { db in
    // Activate the persistent WAL mode
    if db.configuration.readonly == false {
        var flag: CInt = 1
        let code = withUnsafeMutablePointer(to: &flag) { flagP in
            sqlite3_file_control(db.sqliteConnection, nil, SQLITE_FCNTL_PERSIST_WAL, flagP)
        }
        guard code == SQLITE_OK else {
            throw DatabaseError(resultCode: ResultCode(rawValue: code))
        }
    }
}
let dbPool = try DatabasePool(path: ..., configuration: configuration)
```

You'll need access to the raw SQLite C API. For GRDB 4, you'll need an extra `import`: see [Raw SQLite Pointers](https://github.com/groue/GRDB.swift/tree/v4.14.0#raw-sqlite-pointers). For GRDB 5, you don't need any extra import.

**Comment by groue** [comment]
Note to myself: this needs to be mentioned in https://github.com/groue/GRDB.swift/blob/master/Documentation/AppGroupContainers.md

**Comment by groue** [comment]
Open question: should we expose a high-level flag for this setting? If we do, with a default value, then it would be a breaking change. We have to profit from the GRDB 5 beta opportunity. What do you think, @spicymatt, @mallman, @scottandrew?

**Comment by pmanna** [comment]
How breaking a change would be, if you keep the default the same that it is now? And, probably, the developers that have encountered the issue (like myself) would be happy to have that change anyway…
Or am I misunderstanding the question?

**Comment by groue** [comment]
> How breaking a change would be, if you keep the default the same that it is now?

I was not clear, you are right. It looks like the default value of SQLITE_FCNTL_PERSIST_WAL depends on the iOS/macOS system version (https://github.com/groue/GRDB.swift/issues/739#issuecomment-604363998).

If GRDB exposes a boolean flag which overwrites the default one, then GRDB will change behavior on *some* system versions, and this is the breaking change.

> And, probably, the developers that have encountered the issue (like myself) would be happy to have that change anyway…

This is my opinion as well.

But we can address this with a new GRDB configuration flag, or with documentation (as [above](https://github.com/groue/GRDB.swift/issues/771#issuecomment-624479526)). My question is: which path should be take, and why?

**Comment by pmanna** [comment]
Can't really decide for you, obviously: documentation is needed either way, and at least for myself the reference in App Group (that's where I came from to WAL) would certainly work.
How often will this happen, though? It's the usual struggle to put your time where the most value is…

**Comment by groue** [comment]
> Can't really decide for you,

Sure, but I really appreciate the advice of users who are facing such WAL issues, especially since I did not, personally, meet any of those :-)

We have a collective opportunity to build a great and quite probably unmatched WAL experience - at least in open source libraries. When I look for `SQLITE_FCNTL_PERSIST_WAL` on Github, I really don't see much:

- https://github.com/search?q=SQLITE_FCNTL_PERSIST_WAL&type=Issues 
- https://github.com/search?q=SQLITE_FCNTL_PERSIST_WAL+language%3Aswift&type=Code
- https://github.com/search?q=SQLITE_FCNTL_PERSIST_WAL+language%3Aobjc&type=Code

My current position is not to add any new high-level APIs, but to document how to perform the desired setup with the raw C SQLite API.

- This does not change the behavior of the underlying SQLite build
- Expert users may look for `SQLITE_FCNTL_PERSIST_WAL`, and discover that it can be used as they would expect
- Novice users will use Google and hopefully find this issue or the documentation.

**Comment by spicymatt** [comment]
In my specific case, the result of this makes it quite hard to build a consistent user experience, because the databases I'm trying to access are not databases that I created or accessed last.
So if a process that has UNIX write access accesses those database and leaves the -shm, -wal files behind, I'll be able to open them if I have only unix read-access. If on the other hand, thoses processes do a proper cleanup, I won't be able to read from those databases.
My app being targeted at consumers, I cannot explain them why some databases open and some others don't. I can live with it because it's a rare situation.
Regarding your question I would tend towards the documented approach, without adding an API. As for me, it's a very rare use case. But I value the fact that there is no more mystery about all this and that all the pieces make sense now. Understanding what GRDB does (by looking at the documentation) is good enough for me.

**Comment by groue** [comment]
Thank you @spicymatt,

I too am very happy that we have solved this nagging mystery, and that you can now take decisions :-)

> Regarding your question I would tend towards the documented approach, without adding an API.

I agree. I may have to partially rewrite the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/AppGroupContainers.md) guide, make it less iOS-focused, so that it attracts mac developers as well. I really want this guide to answer as many questions as possible, because this topic is such a time sink!

OK, so... It looks like we can close this issue 👍

**Comment by groue** [comment]
A last discovery: the write unix permission is not enough for a readonly connection to be able to open a WAL database which has no -wal and -shm companions:

```
groue$ ls -al test_wal.sqlite*
-rw-r--r--  1 groue  staff   8192 May  6 07:02 test_wal.sqlite

groue$ sqlite3
sqlite> .open --readonly test_wal.sqlite
sqlite> select count(*) from t;
Error: unable to open database file

sqlite> .open test_wal.sqlite
sqlite> select count(*) from t;
7

sqlite> .open --readonly test_wal.sqlite
sqlite> select count(*) from t;
7
sqlite> ^D

groue$ ls -al test_wal.sqlite*
-rw-r--r--  1 groue  staff   8192 May  6 07:02 test_wal.sqlite
-rw-r--r--  1 groue  staff  32768 May  6 19:02 test_wal.sqlite-shm
-rw-r--r--  1 groue  staff      0 May  6 19:02 test_wal.sqlite-wal
```

New conclusion: the `SQLITE_FCNTL_PERSIST_WAL` is actually recommended as soon as there exist readonly connections *in general*.

**Comment by groue** [comment]
The [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide has been updated.

**Comment by groue** [comment]
@spicymatt, it is possible a open a readonly connection to a WAL database that has no `-wal` and `-shm` companions with the `immutable` flag:

```swift
path = "file://path/to/database?immutable=1"
configuration.readonly = true
dbQueue = try DatabaseQueue(path: path, configuration: configuration)
```

(Yeah, SQLite interprets a "path" starting with `file:` as an URI - see https://sqlite.org/uri.html)

With such a flag, though, SQLite assumes that the database won't be modified by some external connection. If the assumption turns out false... see https://sqlite.org/uri.html#uriimmutable for more information.
