### ISSUE TITLE
InputStream support?

### ISSUE THREAD

**Issue by tspike** [groue/GRDB.swift#776]
I'm working on a Swift package that includes a SQLite database that I'd like to access via GRDB. Including resources directly with SPM is not supported until Swift 5.3 which is as yet unreleased. I can include the encoded binary data of the DB in my package and expose it as an `InputStream`, but in eg. the available `DatabaseQueue` constructors, I don't see an option for directly providing the bytes as the data source.

Is there a straightforward way to directly read data rather than passing a path?

Thanks for all the great work on this library. Love the approach.

**Comment by groue** [comment]
Hello @tspike,

I'm not aware of such a feature at the SQLite level itself, did I miss anything?

**Comment by tspike** [comment]
Nope, looks like you are right. I was hoping since `:memory:` databases are supported, you could initialize an existing DB the same way, but doesn't look to be the case. I'll see if I can find another way. Thank you.

**Comment by groue** [comment]
All right, @tspike. If you find a nice technique, don't hesitate sharing a description here. Happy GRDB!

**Comment by tspike** [comment]
It's a pretty sorry solution, but on the off chance anyone stumbles across this before SPM provides proper resource support, I was able to work around this by putting the base64-encoded SQLite data into a raw string in a .swift file, and then loading it into a temp file on initialization - then I can use the normal GRDB APIs to access the database.

**Comment by groue** [comment]
Both SE-0271 and SE-0278 will ship with Swift 5.3 :-)
