### ISSUE TITLE
Observing Database writes (via Reactive bindings)

### ISSUE THREAD

**Issue by RuiAAPeres** [groue/GRDB.swift#780]
### What did you do?

Currently testing the behaviour of a `ViewModel`. Said `ViewModel` has the following (roughly speaking) signature:

```swift
protocol ViewModel {
   func add(entity: Entity) -> SignalProducer<Never, Error>
   func observe() -> SignalProducer<[Entity], Never>
}
```

The consumer of said API can add an `Entity` and observe changes in the `ViewModel` via the `observer`. `SignalProducer` aren't much different than an Rx `Observable` and I am currently using [these extensions](https://gist.github.com/RuiAAPeres/ee11a4a50970f68c68a0e9bc78290d75). Internally, the `ViewModel` compliant entity is running with a `DatabasePool`. I am also using the `asyncWrite` version for adding the Entity and using the `ValueObservationScheduler = .immediate` for the observation. I believe that this is likely the cause for this problem.

### What did you expect to happen?

I wanted to test the following scenario:

1. Assuming an empty ViewModel (and corresponding Database).
2. If a user inserts an `Entity` I can observe said `Entity` being sent via observer.

The setup looks like this:

```swift
viewModel.add(entity).ignoreError()
.then(viewModel.observe)
.startWithValues { values in

}
```

What I receive (in the `startWithValues` handler`) is first an empty array and then an array with the entity I inserted. My expectations, was to receive the array with an entity, since I only start the observation *after* the entity is added. 

### What happened instead?

Instead I first receive an empty array and then an array with the inserted entity. Ultimately, I would like to understand what's happening here, so that I can rely on that intuition going forward. 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.0beta2
**Installation method:** CocoaPods
**Xcode version:** Version 11.4.1 (11E503a)
**Swift version:** 5.2.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.3 (19D76)

### Demo Project

N/A.

**Comment by groue** [comment]
Hello @RuiAAPeres,

Yes, a value observation starts from the latest committed state of the database. We expect it to see the latest entity addition, indeed.

Let me perform some quick sanity test based on RxGRDB...

<details>
    <summary>It works</summary>
    
```swift
struct Entity: Codable, FetchableRecord, PersistableRecord, Equatable {
    var id: Int64
    var name: String
}
try dbPool.write { db in
    try db.create(table: "entity") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text)
    }
}
let observation = ValueObservation.tracking(Entity.fetchAll)
let entities = try dbPool.rx
    .write { db in try Entity(id: 1, name: "foo").insert(db) }
    .asCompletable()
    .andThen(observation.rx.observe(in: dbPool).scheduling(.immediate).asObservable())
    .take(1)
    .toBlocking(timeout: 1)
    .single()
XCTAssertEqual(entities, [Entity(id: 1, name: "foo")]) // Pass
```

</details>

OK, so some assumption in the setup has to be false. Let's try to find out.

First, [this is good](https://gist.github.com/RuiAAPeres/ee11a4a50970f68c68a0e9bc78290d75#file-reactiveswift-grdb-swift-L42): your `write` signal producer completes after the database updates have been committed in the database. That is sane.

So...

Maybe `viewModel.add(entity).ignoreError().then(viewModel.observe)` subscribes to `viewModel.observe` **before** `viewModel.add(entity)` has completed?

Or... maybe the database was changed by some other component of your app, **between** the insertion and the beginning of the observation?

**Comment by groue** [comment]
> Maybe viewModel.add(entity).ignoreError().then(viewModel.observe) subscribes to viewModel.observe before viewModel.add(entity) has completed?

This is not what the documentation of `then` [says](https://github.com/ReactiveCocoa/ReactiveSwift/blob/6.2.1/Sources/SignalProducer.swift#L2311-L2322)...

**Comment by groue** [comment]
@RuiAAPeres, I would at least put two breakpoints: one on your application line which inserts the entity, and one on the line that fetches the observed values (probably `insert(db)` and `fetchAll(db)`). I suppose the fetch happens first, and we need to understand who is messing up with the scheduling.

**Comment by RuiAAPeres** [comment]
@groue thank you so much for the detailed response. Your assessment is correct and the problem is within my own ViewModel, that, at the point of creation, it immediately reads from the Database. Given that it's empty, it rightfully emits an empty array. The following test, using two ViewModels solves the problem:

```swift
/// viewModel1's purpose is to add an entity into the DB, nothing else
viewModel1.add(entity).startWithCompletion {
 let viewModel2 = ...
 viewModel2. observe { values in 
 //  Assertion ...
  }
}
```

**Comment by groue** [comment]
Good, @RuiAAPeres! Happy GRDB!
