### ISSUE TITLE
Not possible to filter "child records" based on value on associated "parent record" when using Self Joins?

### ISSUE THREAD

**Issue by simensol** [groue/GRDB.swift#782]
I have a `Task` record which has a `HasMany` association (one-to-many connection) to other `Task` records using _Self Joins_. Thus, the `Task` record has two types: `project` and `subtask`:

```
struct Task: Identifiable {
    var id = UUID()
    var projectId: UUID?
    var title: String
    var status: TaskStatus
}

extension Task: TableRecord {
    // Projects and tasks.
    static let subtasks = hasMany(Task.self, key: "subtasks")
    static let project = belongsTo(Task.self, key: "project")
}
```

I have created the following request to get all `project` and associated `subtask`:

```
let request = Task
    .all()
    .including(optional: Task.project)
    .including(all: Task.subtasks)
```

I want to filter `subtask` based on the value on `Task.Columns.status` of the associated `project`:

1. If `project` has `Task.Columns.status == TaskStatus.Active`: Include _all_ associated `subtask`.

2. If `project` has `Task.Columns.status != TaskStatus.Active`: Include associated `subtask` with `Task.Columns.status == TaskStatus.Active`.

I have tried to use table aliases:

```
let projectAlias = TableAlias()

let request = Task
    .all()
    .including(optional: Task.project.aliased(projectAlias))
    .including(all: Task.subtasks.filter(Task.Columns.status == TaskStatus.Active || (Task.Columns.status != TaskStatus.Active && projectAlias[Task.Columns.status == TaskStatus.Active])))
```

Using the request above, GRDB generates the following query:

```
SELECT *, "projectId" AS "grdb_projectId" FROM "task" WHERE (("status" = 'Active') OR (("status" <> 'Active') AND ("task"."status" = 'Active'))) AND ("projectId" IN (x'07ae4c9fd1774f22adc2fb1a2452ef9d', ...))
```

This query only returns `subtask` with `Task.Columns.status == TaskStatus.Active`.

Is my approach wrong, is this expected behavior, or is it an issue with GRDB?

### Environment

**GRDB flavor(s): GRDB + GRDBCombine
**GRDB version: 5.0.0-beta.2
**Installation method: SPM
**Xcode version: 11.5 beta 2 (11N605f)
**Swift version: 5.2.2
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 10.15.4 (19E287)

**Comment by groue** [comment]
Hello @simensol,

Using table aliases in `including(all:)` is not currently supported. It is one of the [known limitations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#known-issues).

**Comment by simensol** [comment]
Ah, I missed that. Thanks anyway!
