### ISSUE TITLE
ValueObservation doesn't monitor associated table

### ISSUE THREAD

**Issue by rpoelstra** [groue/GRDB.swift#783]
### What did you do?

I've the following observation:
```
let observation =  ValueObservation.tracking { db  -> [LayerImagesListItem] in
            let request = Layer.including(all: Layer.imageFiles.order(ImageFile.Columns.url))
            return try LayerImagesListItem.fetchAll(db, request)
        }

```
### What did you expect to happen?

This correctly notifiers when anything changes in the layer table, but when a row is added to the imageFile table, which contains the FK to the layer table, no notification is send.

### What happened instead?

I would expect that adding a row to the imageFile table would trigger an observation. Of course, the row has a association with one of the layers.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.0 beta 2
**Installation method:** manual
**Xcode version:** 11.4.1
**Swift version:** 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.15.4

**Comment by groue** [comment]
Hello @rpoelstra,

It definitively should track the imageFile table as well.

Can you help by providing a sample code which reproduces the issue?

**Comment by groue** [comment]
Nah, it's OK @rpoelstra, I'm able to reproduce. There were some missing tests, and I did not notice this bug. Stay tuned, a ship will fix.

**Comment by groue** [comment]
Meanwhile, if you are looking for a workaround:

```swift
let observation =  ValueObservation.tracking { db  -> [LayerImagesListItem] in
    // Workaround GRDB bug: track image files as well
    #warning("TODO: remove line below when GRDB issue #783 is fixed")
    _ = try ImageFile.fetchCursor(db).next()
    let request = Layer.including(all: Layer.imageFiles.order(ImageFile.Columns.url))
    return try LayerImagesListItem.fetchAll(db, request)
}
```

**Comment by groue** [comment]
OK the fix is found.

**Comment by groue** [comment]
@rpoelstra, would you please check if #784 solves the problem in your application? Thank you very much.

**Comment by rpoelstra** [comment]
Hi,

You're going too fast for me!
But I can confirm that the current development branch fixes this issue for me.

Thanks for the quick solution.

**Comment by groue** [comment]
Great! Beta 3 will ship shortly. Thank you for your report, @rpoelstra!
