### ISSUE TITLE
How to create Class Heirarchy instaed of struct

### ISSUE THREAD

**Issue by vishaldroisys** [groue/GRDB.swift#788]
We have JSON data and convert that data into models(Array of object not stucture type).

and wants to insert that array of objects into tables.

Thanks in advanced.

**Comment by groue** [comment]
Hello @vishaldroisys. You may want to subclass the [Record](https://github.com/groue/GRDB.swift/blob/master/README.md#record-class) class.

**Comment by vishaldroisys** [comment]
Ok.

How can we initialise class property through JSON object. i mean without Row, how can it be possible??

**Comment by groue** [comment]
Grab your favorite JSON conversion technique. Have a look at Foundation's JSONDecoder, for example ? Now this library is about **SQLite**, not JSON, so please take care of asking *focused* questions, thank you.
