### ISSUE TITLE
Predicate Support??

### ISSUE THREAD

**Issue by vishaldroisys** [groue/GRDB.swift#789]

**Comment by groue** [comment]
Hello @vishaldroisys. I guess you mean [NSPredicate](https://developer.apple.com/documentation/foundation/nspredicate)? No one has asked for it before. Contributions are welcome.

**Comment by groue** [comment]
> Contributions are welcome.

I should add that "contribution" does not necessarily mean code. A description of a use case which is not well addressed today would be well appreciated. The terse "Predicate Support??" obviously does not pass this threshold.
