### ISSUE TITLE
Please hide raw subscript with flag

### ISSUE THREAD

**Issue by LesykMelnychuk** [groue/GRDB.swift#792]
### What did you do?
Got trouble on fetching Int and Data results from Row

```
init?(from row: Row) {
            guard
                let fieldGroup = row["field_group"] as? String,
                let fieldKey = row["field_key"] as? String,
                let fieldGroupCopiedFlagInt = row["field_group_copied_flag"] as? Int,
                let fieldGroupData = row["field_group_data"] as? Data
            else {
                Log.assertionFailureOnNoParameters()
                return nil
            }

            self.fieldGroup = fieldGroup
            self.fieldKey = fieldKey
            self.fieldGroupCopiedFlag = fieldGroupCopiedFlagInt.bool
            self.fieldGroupData = fieldGroupData
        }
```

### What did you expect to happen?

Please replace this method
 ```
Row.swift
 ```
 ```
 public subscript(_ columnName: String) -> DatabaseValueConvertible? {
        // IMPLEMENTATION NOTE
        // This method has a single know use case: checking if the value is nil,
        // as in:
        //
        //     if row["foo"] != nil { ... }
        //
        // Without this method, the code above would not compile.
        guard let index = index(ofColumn: columnName) else {
            return nil
        }
        return impl.databaseValue(atUncheckedIndex: index).storage.value
    }
```
with _bool_ flag

### What happened instead?

Got **_nil_** instead of **_Int_** result

### Environment

**GRDB flavor(s):** (GRDBCipher)
**GRDB version: v3.7.0
**Installation method:** CocoaPods
**Xcode version: 11.5
**Swift version: 5
**Platform(s) running GRDB:** iOS, macOS

**Comment by LesykMelnychuk** [comment]
Thanks for reply.

**Comment by groue** [comment]
Hello @LesykMelnychuk,

You missed this line in the [documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#column-values):

> ⚠️ Warning: avoid the as! and as? operators:
> 
> ```swift
> if let int = row[...] as? Int { ... } // BAD - doesn't work
> if let int = row[...] as Int? { ... } // GOOD
> ```

So please replace your usages of `as?`. This is the correct fix, not the removal of an API which serves other purposes (even though you don't happen to use it, other users do).

**Comment by LesykMelnychuk** [comment]
Ok, thank for reply.
