### ISSUE TITLE
more explain the manually installation guide

### ISSUE THREAD

**Issue by munkhbolde** [groue/GRDB.swift#8]

**Comment by groue** [comment]
Hello, @munkhbolde.

I just added a demo application that targets iOS7, with some explanations: https://github.com/groue/GRDB.swift/tree/master/DemoApps/GRDBDemoiOS7.

**Comment by groue** [comment]
Oh, and if you wanted to integrate frameworks, look at https://github.com/groue/GRDB.swift/tree/master/DemoApps/GRDBDemoiOS.

**Comment by munkhbolde** [comment]
today I tried Drag the GRDB project in your own project.

In the Build Phase tab of your target, add GRDBiOS in the Target Dependencies section.

Run but compile failed xcode didn't displayed errors I don't what's wrong. just failed.  Can you help me

**Comment by groue** [comment]
I'd like to help you but I need details. You don't say enough.

**Comment by munkhbolde** [comment]
I don't know why don't display error in Xcode. Xcode just displayed "Failed". no error code.  i already do  your installation guide.

**Comment by munkhbolde** [comment]
and also i used pod install and then no module named GRDB and then i tried to install manually. drag a project and configure target dependencies.

**Comment by groue** [comment]
What? You tried to mix manual integration and Cocoapods ? You can't do that. Choose a solution, and remain faithful to it, or you will make a mess.

My advice: choose the Cocoapods way. Read their documentation. Then read GRDB cocoapod installation guide. Install the latest version of all your tools : Xcode, cocoapods, etc. You will learn a lot.

**Comment by munkhbolde** [comment]
Hello Mr Groue. How to alter column in migrator.

**Comment by groue** [comment]
Hello! You run an [ALTER TABLE](https://www.sqlite.org/lang_altertable.html) command:

```swift
try dbQueue.inDatabase { db in
    try db.execute("ALTER TABLE foo ADD COLUMN bar INTEGER")
}
```

**Comment by munkhbolde** [comment]
```swift
try dbQueue.inDatabase { db in
    try db.execute("ALTER TABLE foo ALTER COLUMN bar INTEGER UNIQUE ON CONFLICT REPLACE")
}
```
but There's no ALTER COLUMN in sqlite.

**Comment by groue** [comment]
Yes, SQLite has limited table alteration support. Their documentation explains how to perform other kinds of changes (look for "Making Other Kinds Of Table Schema Changes" in https://www.sqlite.org/lang_altertable.html).

**Comment by munkhbolde** [comment]
Can you explain about "How it works migrations in GRDB"?

**Comment by groue** [comment]
What information do you lack in https://github.com/groue/GRDB.swift#migrations ?

**Comment by munkhbolde** [comment]
the migrations works like that "Migrations run in order, once and only once. When a user upgrades your application, only non-applied migrations are run."  If applied migrations is fake or work i want to reset registered Migrations identifier. is it possible or not?

**Comment by groue** [comment]
A migration is granted applied (and won't run again), if and only if its name has been stored in the database, in a table that is private to GRDB, and that you must not read of write to.

HENCE you can not rename a migration. If you do it, it is considered as a new migration, and it will run even if it has been already applied (under its previous name).

During development, as your migrations are not well written yet, your best option is to run your migrations againts a database that is in a well known version: an empty database, or a database extracted from a previous version of your application.

**Comment by munkhbolde** [comment]
yeah if the faked migrations run again it's so COOL :D

**Comment by groue** [comment]
Do you have some example of your "faked migrations"? Some actual code that you can share? I'm not sure I understand you well.

**Comment by groue** [comment]
@munkhbolde: if you need to alter a column in a migration, update GRDB to version 0.27.0, and check https://github.com/groue/GRDB.swift#advanced-database-schema-changes.

**Comment by munkhbolde** [comment]
woooow thank you Mr. @groue

**Comment by munkhbolde** [comment]
I'm sorry @groue  i can't explain it well. 
The first migration was I forget ON CONFLICT and something
```swift
       migrator.registerMigration("createFoo") { db in
            try db.execute(
                "CREATE TABLE Foo ("    +
                    "bar INTEGER"     +
                    ")")
        }
```
because  I choose the drop table and create table again 
```swift
        migrator.registerMigration("dropTableFoo") { db in
            try db.execute("drop table Foo")
        }
```
and then again I create the table foo with little fixing
```swift
       migrator.registerMigration("createFooAgain") { db in
            try db.execute(
                "CREATE TABLE Foo ("    +
                    "bar INTEGER UNIQUE ON CONFLICT REPLACE"     +
                    ....")")
        }
```
createFoo is faked migrations example if the migrations are have some options like a  fake or version code  Change migration with run again is easy. I'm sorry bro my english is so bad because i can't explain enough.

**Comment by groue** [comment]
Well, if there exists any device that you do not control, and which contains a database which has only run the `createFoo` migration, then you must keep your `dropTableFoo` and `createFooAgain` migrations: they are there to repair your users'  applications, and they are very important.

On the other side, if you are still developing your application, and no device other than yours contains a bad database, you can just delete the code for `createFoo` and `dropTableFoo` after you have applied those migrations to your database. You are left with a single migration named `createFooAgain`, and that's it. Don't try to rename it, it worthless.
