### ISSUE TITLE
Xcode 12 error: "Cannot find 'CodingKeys' in scope"

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#804]
This error is a compiler bug: https://bugs.swift.org/browse/SR-13137 (please click the link and vote in order to help having it fixed).

It happens when a `Column` defined by one record type is used in another file.

A workaround is to prepend `CodingKeys` with the name of the record:

```diff
 struct Player: Codable {
     var score: Int
     ...
 }
 extension Player: FetchableRecord {
     enum Columns {
-        static let score = Column(CodingKeys.score)
+        // TODO: remove `Player.` prefix when SR-13137 is solved
+        static let score = Column(Player.CodingKeys.score)
     }
 }
```

**Comment by groue** [comment]
The fix https://github.com/apple/swift/pull/33586 was merged into the Swift 5.3 compiler. Xcode 12 beta 6 does not include it yet. Let's wait for the next Xcode release.

**Comment by groue** [comment]
Xcode version 12.0 (12A7209) wasn't shipped with the fix :-/

**Comment by groue** [comment]
Xcode version 12.2 beta (12B5018i) wasn't shipped with the fix :-/

**Comment by tobyspark** [comment]
Perhaps worth noting that while you can submit apps to Testflight with the beta Xcode, you can only submit apps for App Store release with the public (GM) Xcode.

**Comment by groue** [comment]
Xcode 12.2 has shipped, I can close this issue.

**Comment by AngelSteve13** [comment]
For me it was the target check.

**Comment by sonnv106** [comment]
Xcode version 14 has this problem
