### ISSUE TITLE
Empty date field causes app to crash while obtaining models from database

### ISSUE THREAD

**Issue by DZoki019** [groue/GRDB.swift#805]
### What did you do?

I'm trying to obtain models with custom created function:
```swift
func obtainModel<T: FetchableRecord>() -> [T]? {
    let tableName = String(describing: T.self).replacingOccurrences(of: "TS", with: "")
    
    var rows: [T]?
    
    do {
        try dbQueue.read { db in
            rows = try T.fetchAll(db, sql: "SELECT * FROM \(tableName)")
        }
    } catch {
        print(error)
    }
    return rows
}
```
Some models contain optional `Date?` as a parameter, but sometimes the field in the database is empty string. As a result, the application crashes.

### What did you expect to happen?

My expectations are to set `nil` for the object because the date doesn't exist.

### What happened instead?

The app crashes.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.14.0
**Installation method:** CocoaPods
**Xcode version:** 11.5
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.5

### My solution

My current solution is to change code in `FetchableRecord+Decodable.swift` file in `decodeIfPresent(sqliteStatement: SQLiteStatement, index: Int32)` function, actually to add another condition when the bytes count of the field is equal to 0.

Solution:

```swift
fileprivate func decodeIfPresent(sqliteStatement: SQLiteStatement, index: Int32) -> Date? {
    if sqlite3_column_type(sqliteStatement, index) == SQLITE_NULL || Int(sqlite3_column_bytes(sqliteStatement, index)) == 0 {
        return nil
    }
    return decode(sqliteStatement: sqliteStatement, index: index)
}
```

**Comment by groue** [comment]
Hello @DZoki019,

You have this error because an empty string `""` is not a valid representation of a `Date`, or even a `Date?`.

I suggest two possible ways to handle your case:

- Option "make the database trustable":

    Fix the content of your database, so that it does only contain valid dates, or `NULL`.

- Option "deal with this weird database":

     Don't ask GRDB to decode dates, since the database *does not* contains valid dates. Instead, ask GRDB to decode strings. And perform your own string to date decoding in the application.

**Comment by DZoki019** [comment]
Hello @groue,

Thank you so much!
