### ISSUE TITLE
How can I check for key existence?

### ISSUE THREAD

**Issue by shshalom** [groue/GRDB.swift#81]
Or alternatively what would be the right approach to store unique keys?
The way my database is set is (id, key, blob) fields, every key is unique and I need to make sure that an attempt to insert an existing key would be handled in nicely. 

Your thought?

**Comment by groue** [comment]
Hello @shshalom. What did you try?

**Comment by shshalom** [comment]
I tried using Records base models to check for existence like so:
```
dbQueue.inDatabase { db in 
   let record = DBRecord(key:"a_unique_key", data: blob_data)
    if record.exists(db) {
       try record.insert(db)
    }
}
```

when I tried that it throws the following error:

> fatal error: invalid primary key in MyProject.MyDBRecord: file /Users/shalom/Workspace/NuroComponents/Pods/GRDB.swift/GRDB/Record/Persistable.swift, line 550

**Comment by shshalom** [comment]
Any idea on what I'm doing wrong?

**Comment by groue** [comment]
The "invalid primary key" error means that your record could not be identified in the database. Check that the colum(s) of the primary key of the table returned by the databaseTableName method are used in the dictionary returned by persistentDictionary property, and associated with non-null values (the necessary condition for the record to be able to identify a single row in the database)

**Comment by groue** [comment]
No news, good news!

**Comment by shshalom** [comment]
Sorry for not responding, still had trouble figuring it out, bit  I think I've got it now.
Thanks.
