### ISSUE TITLE
Discussion: naïve query interface filters on "boolean" columns

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#816]
Suppose we create a database `test` with the following schema:

```sql
CREATE TABLE version (
  id integer PRIMARY KEY NOT NULL,
  isInTrash boolean NOT NULL
)
```

Let's assume we have a GRDB `Version` record that simply follows the table definition. Let's consider three query interface requests:

```swift
let requestA = Version.select(Column("id")).filter(Column("isInTrash"))
let requestB = Version.select(Column("id")).filter(Column("isInTrash") == true)
let requestC = Version.select(Column("id")).filter(Column("isInTrash") == 1)
```

These requests generate the following SQL queries, respectively:

```sql
Query A: SELECT "id" FROM "version" WHERE "isInTrash"
Query B: SELECT "id" FROM "version" WHERE "isInTrash"
Query C: SELECT "id" FROM "version" WHERE "isInTrash" = 1
```

The SQL for `requestA` makes perfect sense. What surprises me is that the SQL for `requestB` is not the same as the SQL for `requestC`. In examining the source code for GRDB, I see why this is the case. I don't know if you would consider this a bug. However, I'd like to suggest this is not the best experience for the GRDB user. Let me elaborate.

I believe there is a common circumstance where a user who writes a query interface request like `requestB` will benefit greatly from using the SQL generated by `requestC`.

Suppose that every value in the `isInTrash` column is either 0 or 1. Then queries B and C return identical result sets.

Now suppose we create an index on the `isInTrash` column:

```sql
CREATE INDEX version_on_isInTrash ON version (isInTrash)
```

Let's examine the query plans for queries B and C.

```
sqlite> explain query plan select id from version where isInTrash;
QUERY PLAN
`--SCAN TABLE version USING COVERING INDEX version_on_isInTrash
sqlite> explain query plan select id from version where isInTrash = 1;
QUERY PLAN
`--SEARCH TABLE version USING COVERING INDEX version_on_isInTrash (isInTrash=?)
```

Without defending my logic, I will assert that (in almost all cases) a `SCAN TABLE` plan is significantly slower than a `SEARCH TABLE` plan. This is especially true when using a covering index. In fact, depending on the size of the table and the distribution of values, Query C can be orders of magnitude faster than Query B. The user should clearly favor Query C over Query B. This means they need to use `requestC`. However, I suggest that `requestB` is a more natural formulation of Query C than `requestC`. In fact, I believe only an experienced SQLite user will even understand or appreciate the difference among these three requests.

I assert that this a common scenario because, if the user sticks to using the Swift-based GRDB interfaces and/or exercises some sensible discipline, every value of a boolean column will be null, 0 or 1. And further, indexing a boolean column is a best-practice for filtering on such a column. And in fact, I've encountered this issue in my personal experience with GRDB where the difference in performance for a particular query like B versus C was 1 versus 10 seconds. The consequence is that—after 2+ years using GRDB and SQLite—I discovered I need to replace my `Column("mybooleancolumn")` filter expressions with `Column("mybooleancolumn") == 1` 🤦 . (Granted I can define `let TRUE = 1` and `let FALSE = 0` to make the code a bit tidier, but I'm not sure that's much better. After all, that begs the question of what's the problem with using Swift's built in `true` and `false` values. Also, I grant that part of my long standing mistake has nothing to do with GRDB. The fact is the implementation of boolean-typed columns and values in SQLite are far from intuitive for someone coming from an RDBMS that has a true boolean column type.)

Granted, making `requestB` and `requestC` produce the same SQL would be a breaking change for boolean columns with values other than null, 0 or 1. But perhaps that could be advertised as part of the release notes for GRDB 5? Thoughts?

**Comment by groue** [comment]
> Granted, making requestB and requestC produce the same SQL would be a breaking change for boolean columns with values other than null, 0 or 1. But perhaps that could be advertised as part of the release notes for GRDB 5?

Thank you @mallman for your detailed post. This is a good idea, and I support it. Let's remove the specific handling of boolean equality checks!

**Comment by groue** [comment]
Closing in favor of #817
