### ISSUE TITLE
"database disk image is malformed" when trying to copy database to shared AppGroup folder

### ISSUE THREAD

**Issue by silviupetrescu84** [groue/GRDB.swift#818]
### What did you do?

Hello,
I want to preface this by saying I just took over from a senior developer as he departed the team and my understanding of the underlying mechanism of how it all works is not 100%, but from the looks of it's, this is either something deep in SQLite or in GRDB.  
When the app starts, we have a local database that is bundled with the app that needs to be copied to a shared AppGroup.  
This is done the first time the app starts and after that the other apps read it at first in read/write and then readonly. The database is rather large, about 360 mb.

This bug doesn't happen on all devices for all users (we have about 400 of them), sometimes a re-install of the app fixes it, sometimes the whole device needs to be reset, but for some users not even that helps. This doesn't happen when the device is connected to XCode or Simulator. We were unable to test with the same devices that the users crashed on.

We are logging the crash into Firebase because there was no other way to identify this. 

### What did you expect to happen?

1. This one is high priority - The database gets copied and the DB Queue is generated properly
2. This one is low priority - The WAL dissappears after the DB is copied and set up

### What happened instead?

1. The code throws an error when getting the DB Queue - "SQLite error 11 with statement `SELECT * FROM sqlite_master LIMIT 1`: database disk image is malformed"
2. The message "WAL file is still present and has a size of 370 MB" and it grows with each launch is present. This is a problem as long as the users keep re-starting the app, but I think I have an idea on the solution here to delete the database if the WAL file is still active or some other resolution.

### Environment

**GRDB flavor(s): GRDB 
**GRDB version: 5.4
**Installation method: Manual, framework embed
**Xcode version: 11.5
**Swift version: 5.2
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 10.15.5

### Demo Project

We are using this function across all our projects to load up the database:

```
fileprivate func createDBQueueOrPool() -> DatabaseWriter {
	let debugMode	= infoDict[gDBTagDebug] as? Bool ?? false
	let newVersion	= Double(infoDict[gDBTagVersion] as? String ?? "1.0") ?? 1.0
	var config		= Configuration()

	config.readonly = isReadOnly
	if debugMode {
		config.trace = { TinyConsole.print($0) }     // Prints all SQL statements
	}

	var dbq: DatabaseWriter?

	do {
		if isDBShared {
			let coordinator = NSFileCoordinator(filePresenter: nil)
			var coordinatorError: NSError?
			var dbError: Error?
			
	#if DEBUG || TEST
			let walPath	= dbPath + "-wal"
			
			if FileManager.default.fileExists(atPath: walPath) {
				if let attributes = try? FileManager.default.attributesOfItem(atPath: walPath) as NSDictionary {
					let fileSize = attributes.fileSize()
					
					if fileSize > 0 { TinyConsole.error("WAL file is still present and has a size of \(fileSize / 1048576) MB") }
				} else {
					TinyConsole.error("WAL file \(walPath) is still present - size unknown")
				}
			}
	#endif
			if isReadOnly {
				coordinator.coordinate(readingItemAt: URL(fileURLWithPath: dbPath), options: .withoutChanges, error: &coordinatorError, byAccessor: { url in
					do {
						dbq	= try DatabasePool(path: url.path, configuration: config)
					} catch {
						dbError = error
					}
				})
			} else {
				// See https://github.com/groue/GRDB.swift/blob/master/Documentation/AppGroupContainers.md#how-to-limit-the-sqlite_busy-error
				config.busyMode					= .timeout(5.0)
				config.defaultTransactionKind	= .immediate
				coordinator.coordinate(writingItemAt: URL(fileURLWithPath: dbPath), options: .forMerging, error: &coordinatorError, byAccessor: { url in
					do {
						dbq	= try DatabasePool(path: url.path, configuration: config)
					} catch {
						dbError = error
					}
				})
			}
			if let error = dbError ?? coordinatorError {
				throw error
			}
		} else {
			dbq	= try DatabaseQueue(path: dbPath, configuration: config)
		}
		
		if !isReadOnly, dbq != nil {
			try migrate(dbq!, version: newVersion)
		}
	} catch {
		TinyConsole.error(error.localizedDescription)
		CLSLogv("Database exception - %@", getVaList([error.localizedDescription]))
	}

	return dbq!
}		
```

And then we call it like this:  
`lazy var dbQueue: DatabaseWriter! = { createDBQueueOrPool() }()`

And in AppDelegate:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

	db	= GRDBManager.checkAndCopyDatabase(name: "db.sqlite", shareDB: true)
	_				= siteFinderDB.dbQueue
```

Just to be a little more clear here, according to the log and the breakpoints, this happens on the main thread, and should not be a problem due to multithreading, but might become one because it's on the first start of the app, before the root view controller got initialized. I am thinking here to start the app first, display the first view controller, start a Spinner so the user knows something is happenning and Apple doesn't kill the app because it didn't start, and only then copy the database/create the queue.

**Comment by groue** [comment]
Hello @silviupetrescu84 

> What did you expect to happen?
> 
> This one is high priority - The database gets copied and the DB Queue is generated properly
> This one is low priority - The WAL dissappears after the DB is copied and set up

I don't know what `GRDBManager.checkAndCopyDatabase` does with database files, but it is likely the cause of your error.

Now and in the future, always use the [backup(to:)](https://github.com/groue/GRDB.swift/blob/master/README.md#backup) method when you want to copy a database.

**Comment by silviupetrescu84** [comment]
Hi,
Thank you for the help and sorry if putting my whole code there made it seem like I wanted you to debug my code.
The problem is that if you look over it we have 2 different try-es there and they are:

`dbq	= try DatabasePool(path: url.path, configuration: config)`
`dbq	= try DatabaseQueue(path: dbPath, configuration: config)'

And these are the lines that throw the error, so the error comes back from GRDB, so it looks like there is something there that causes issues. 
As per your final point, we are not copying via the SQL engine, but rather the file itself, we move it over to the AppGroup.
Sorry, again, this might be something on our side, but just want to make sure as one of those 2 try is throwing up the error.
Thank you.

**Comment by groue** [comment]
> we are not copying via the SQL engine, but rather the file itself

Yes. This code needs to be fixed.

This code does something with database files which prevents SQLite from opening the file. And GRDB reports the SQLite error to your application. But the cause of the error is not in SQLite, and not in GRDB. It is this code. Is it clear now?

Please read again my first answer, and use the `backup(to:)` method. Thank you.

**Comment by silviupetrescu84** [comment]
Sorry again and thank you very much for sticking with me. From whatever reason, I understood that the copying is done by GRDB also but after looking through the code more carefully I understand that is on our side. I will follow your guidance and use backup(to:)

**Comment by groue** [comment]
All right! Just ask if you face a difficulty using `backup`!
