### ISSUE TITLE
More descriptive error message

### ISSUE THREAD

**Issue by gshaviv** [groue/GRDB.swift#820]
### What did you do?

By mistake I did a Record.save(db) inside a read { } block. The error I got was a very non descriptive sql error that made it hard to figure out the problem. A more descriptive error message would be nice and make development better. 

### What did you expect to happen?

I expect the error to have a description like attempt to write in a read block

### What happened instead?

The error was an SQLite error attempt to write to a read only database. This is undescriptive and suggests somehow the database has a problem while the problem is a misuse of the grdb api.  

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
Thanks @gshaviv for the report. Would you mind reporting the error reporting you got, versus the kind of error reporting you would have expected, so that your issue becomes more explicit, please?

**Comment by gshaviv** [comment]
More info:

My faulty code looked like this:
do {
      try dbPool.read { db in
                try record.save(db)
    }
 } catch {
    print(error.localizedDescription)
}

And the error message I got was:
SQLite error 8 with statement `...` arguments [...]: attempt to write a readonly database

This made it look like an SQLite error since the message stated "SQLite error 8..." and made it sound like a problem with the database open, so it was not obvious it was actually an API usage error - trying to write within a read block.

An error along the lines of:
"attempting to write in a read only block"

would have made it much faster to figure out the problem - as it is took me a day to notice my mistake.

**Comment by gshaviv** [comment]
Another option if it's difficult to know the cause of the error, in case there is an error related to writing just add the string to the error message "Are you trying to write in a read block?"

**Comment by groue** [comment]
> And the error message I got was:  
> SQLite error 8 with statement ... arguments [...]: attempt to write a readonly database

"attempt to write in a readonly database" is not a bad sentence, and SQLite error 8 can also be easily found on the internet: https://sqlite.org/rescode.html#readonly

I see how "attempting to write in a read only block" or "Are you trying to write in a read block?" can be seen as improvements. However I think that exposing the raw SQLite messages is a much saner path forward.

Consider, for example, what translating error 8 **really** means. Such an error is emitted by SQLite when you attempt to write in a GRDB `read` method, but also when you write in a database that you have opened in the read-only mode, and also when you write in a database stored on a read-only volume, and also, very likely, in other scenarios that I do not foresee. It is a huge job to (1) maintain a list of (2) accurate "enhanced" error messages. As you see, there are situations where "attempting to write in a read only block" and "Are you trying to write in a read block?" are just misleading.

On the other hand, SQLite error 8 is always accurate. And "attempt to write in a readonly database", the message chosen by SQLite authors, is really not that bad when one does "a Record.save(db) inside a read { } block".

**Comment by groue** [comment]
Even if I close this issue as "won't fix", thank you @gshaviv for opening it. Please dare reporting other annoyances, I'm sure some deserve a fix.

**Comment by groue** [comment]
Maybe GRDB should change its error formatting, and put the raw SQL statement *after* the raw SQLite error message, so that this message gets more prominent. Maybe it would have helped you spotting the problem earlier.

**Comment by groue** [comment]
> And the error message I got was:
> SQLite error 8 with statement ... arguments [...]: attempt to write a readonly database

Next GRDB version will output instead: "SQLite error 8: attempt to write a readonly database - while executing ..."

I hope it will help.
