### ISSUE TITLE
Can GRDB handle generic PersistableRecords?

### ISSUE THREAD

**Issue by James-Coleman** [groue/GRDB.swift#822]
I was interested in how GRDB uses generics and whether or not a generic object itself can be stored in the DB. I'm not very experienced with SQL and SQL might be the weak link which cannot store a generic object like this.
I've pasted some code at the bottom, maybe someone could see what I'm trying to do and suggest a better way?

Ideally I'd like to be able to call `try Parent<ChildString>.fetchAll()` and `try Parent<ChildInt>.fetchAll()` without any problems. I'm open to changing the database setup as much as needed.

### What did you do?

I attempted to use a generic PersistableObject with GRDB.
The child object was saved as a .blob

### What did you expect to happen?

I wasn't sure what would happen. I didn't know if GRDB/SQL could support this.

### What happened instead?

The Swift compiler was happy, but GRDB could not decode properly.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.14.0
**Installation method:** CocoaPods
**Xcode version:** 11.5
**Swift version:** 5
**Platform(s) running GRDB:** iOS (Playground)
**macOS version running Xcode:** 10.15.5

### Demo Project

This can be pasted into a playground:

```swift
import GRDB

struct ChildString: Codable {
    let property: String
}

struct ChildInt: Codable {
    let property: Int
}

struct Parent<ChildType: Codable>: Codable, FetchableRecord, PersistableRecord {
    let child: ChildType
}

var config = Configuration()

config.trace = { print($0) }

let dbQueue = DatabaseQueue(configuration: config)

var migrator = DatabaseMigrator()

do {
    migrator.registerMigration("v1") { db in
        try db.create(table: "parent") { table in
            table.column("child", .blob).notNull()
        }
    }
    
    try migrator.migrate(dbQueue)
} catch {
    print(error)
}

let childString = ChildString(property: "Something")

let parentString = Parent<ChildString>(child: childString)

do {
    try dbQueue.write { db in
        try parentString.save(db)
    }
} catch {
    print(error)
}

let childInt = ChildInt(property: 1)

let parentInt = Parent<ChildInt>(child: childInt)

do {
    try dbQueue.write { db in
        try parentInt.save(db)
    }
} catch {
    print(error)
}

do {
    try dbQueue.read { db in
        guard let parent = try Parent<ChildString>.fetchOne(db) else { return }
        
        parent.child.property
    }
} catch {
    print(error)
}

do {
    try dbQueue.read { db in
        // This crashes.
        // The Swift compiler is fine with it, but GRDB cannot handle generic objects in this way.
        // Expected to decode Int but found a string/data instead.
        guard let parent = try Parent<ChildInt>.fetchOne(db) else { return }
        
        parent.child.property
    }
} catch {
    print(error)
}
```

**Comment by groue** [comment]
Hello @James-Coleman 

> Expected to decode Int but found a string/data instead

The exact verbatim of your sample code is:

```
CREATE TABLE "parent" ("child" BLOB NOT NULL)
INSERT INTO grdb_migrations (identifier) VALUES ('v1')
PRAGMA foreign_key_check
COMMIT TRANSACTION
PRAGMA foreign_keys = ON
BEGIN DEFERRED TRANSACTION
PRAGMA table_info("parent")
INSERT INTO "parent" ("child") VALUES ('{"property":"Something"}')
COMMIT TRANSACTION
BEGIN DEFERRED TRANSACTION
INSERT INTO "parent" ("child") VALUES ('{"property":1}')
COMMIT TRANSACTION
PRAGMA query_only = 1
SELECT * FROM "parent" LIMIT 1
PRAGMA query_only = 0
PRAGMA query_only = 1
SELECT * FROM "parent" LIMIT 1
Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "property", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil)): file /Users/groue/Documents/git/groue/GRDB.swift/GRDB/Record/FetchableRecord+Decodable.swift, line 7
```

I'm not sure it does what you expect (which is pretty hard to guess).

The crash happens because GRDB considers a decoding error as a *programmer error* that requires a fix in the application code, or in the database content. This is not a problem with GRDB, this is a problem with the program that uses the database in an incorrect way. Indeed decoding an Int from a String property stored in a JSON blob database column is just begging for trouble.

As for the answer to your question, "Can GRDB handle generic PersistableRecords?", I'll say yes, sure.

If you have a more precise question, or a sample code that makes sense but creates some unexpected difficulty to you, please open another issue.
