### ISSUE TITLE
shouldn't DatabaseValue(storage) be public?

### ISSUE THREAD

**Issue by thieso2** [groue/GRDB.swift#825]
### What did you do?

I'm implementing a custom field that will hold a value that is serialized via Protobuf. 

### What did you expect to happen?

my code reads:

``` 
extension ProtoBufArray: DatabaseValueConvertible {
    var databaseValue: DatabaseValue {
        DatabaseValue(storage: DatabaseValue.blob(try? self.serializedData()))
    }
    
    static func fromDatabaseValue(_ dbValue: DatabaseValue) -> ValueAtBoolArray? {
        switch dbValue.storage {
        case .blob(let data):
            return try? ValueAtBoolArray(serializedData: data)
        default:
            return nil
        }
    }
}
``` 

I expected it to compile;-)

### What happened instead?

compiler complains  about init(storage: Storage) not being public in DatabaseValue.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
GRDB
**GRDB version:**
v5.0.0-beta.10
**Installation method:** (CocoaPods, SPM, manual?)
SPM
**Xcode version:**
12b5
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
macOS
**macOS version running Xcode:**
10.15.6

**Comment by groue** [comment]
Hello @thieso2,

Indeed this initializer is not public. Use `Data.databaseValue` instead:

```swift
extension ProtoBufArray: DatabaseValueConvertible {
    var databaseValue: DatabaseValue {
        try! serializedData().databaseValue
    }
}
```

In the same vein, it is recommended to build `fromDatabaseValue(_:)` from another `fromDatabaseValue(_:)` implementation:

```swift
extension ProtoBufArray: DatabaseValueConvertible {
    static func fromDatabaseValue(_ dbValue: DatabaseValue) -> ValueAtBoolArray? {
        guard let data = Data.fromDatabaseValue(dbValue) else { return nil }
        return try? ValueAtBoolArray(serializedData: data)
    }
}
```

**Comment by thieso2** [comment]
That does the trick! Thank you
