### ISSUE TITLE
Help with chaining writePublisher

### ISSUE THREAD

**Issue by scottandrew** [groue/GRDB.swift#827]
I am a big confused as to how to chain this into my code.

### What did you do?
`public class FeedGrabber {
    private var downloads = [URL: AnyCancellable]()

    public init() {}

    public func download(url: URL) -> AnyPublisher<RssFeed, Error> {
        return URLSession.shared.dataTaskPublisher(for: url)
            .mapError { $0 as Error }
            .map { $0.data }
            .map { data -> RssFeed in
                let parser = RssParser()
                parser.parse(xml: data, url: url)

                return parser.feed
            }
            .tryMap { feed -> RssFeed in
                return Database.shared.database.writePublisher { (db) -> RssFeed in
                    try feed.save(db)
                    return feed
                }
            }
            .eraseToAnyPublisher()
    }
}`

Solution I have: 

`public class FeedGrabber {
    private var downloads = [URL: AnyCancellable]()

    public init() {}

    public func download(url: URL) -> AnyPublisher<RssFeed, Error> {
        return URLSession.shared.dataTaskPublisher(for: url)
            .mapError { $0 as Error }
            .map { $0.data }
            .map { data -> RssFeed in
                let parser = RssParser()
                parser.parse(xml: data, url: url)

                return parser.feed
            }
            .flatMap { feed -> AnyPublisher<RssFeed, Error> in
                return Database.shared.database.writePublisher { (db) -> RssFeed in
                    try feed.save(db)
                    return feed
                }
                .eraseToAnyPublisher()
            }
            .eraseToAnyPublisher()
    }
}`
### What did you expect to happen?

Not get an error.

### What happened instead?

/Users/scottandrew/Sources/New Wave/Newsie/Newsie/FeedGrabber.swift:27:31: Declared closure result 'DatabasePublishers.Write<RssFeed>' is incompatible with contextual type 'RssFeed'

### Environment

**GRDB flavor(s):** 
GRDB
**GRDB version:**
5.0beta10
**Installation method:** (CocoaPods, SPM, manual?)
SPM
**Xcode version:**
12.0beta6
**Swift version:**
5.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
macOS
**macOS version running Xcode:**
osx 11

**Comment by groue** [comment]
Hello @scottandrew,

Your second version indeed works.

The first one doesn't. We'll see how to make it work. But if both versions have the same effect (download + save + publish the saved feed), they do not have the same *sheduling* (how tasks are dispatched on application threads). And the difference may be important for your app, so let's make it very explicit.

The first version uses `tryMap`. This Combine operator accepts a transformation closure, not a publisher, and processes values immediately:

```swift
public func download(url: URL) -> AnyPublisher<RssFeed, Error> {
    return URLSession.shared.dataTaskPublisher(for: url)
        .mapError { $0 as Error }
        .map { $0.data }
        .map { data -> RssFeed in
            let parser = RssParser()
            parser.parse(xml: data, url: url)
            return parser.feed
        }
        .tryMap { feed -> RssFeed in
            // I just removed "Publisher"
            return Database.shared.database.write { (db) -> RssFeed in
                try feed.save(db)
                return feed
            }
        }
        .eraseToAnyPublisher()
}
```

In the `tryMap` version, the database access is performed on the thread on which `dataTaskPublisher` completes. It may well be the main thread. This particular write should be very quick. But remember that SQLite writes are globally serialized (no two threads can write in parallel). It is thus *possible* that another application component is performing a long database write at the same time. When this happens, your feed will only be saved after this concurrent long write has completed, and this may block the main thread (your UI).

In the `flatMap` version, on the other side, you use `writePublisher`, which is an asynchronous publisher. It is guaranteed that the database access is not performed on the main thread. If will still wait for eventual concurrent writes, but without blocking the main thread.

All in all, the second version is better than the first. It builds a publisher that waits for a network response, then for a database access, without ever blocking the user interface.

**Comment by scottandrew** [comment]
Thank you very much.
