### ISSUE TITLE
Documentation broken links

### ISSUE THREAD

**Issue by aczel** [groue/GRDB.swift#830]
The link on the following site are broken. Please fix it. Thanks!

https://medium.com/@gwendal.roue/how-to-build-an-ios-application-with-sqlite-and-grdb-swift-d023a06c29b3

> Since most iOS apps access a single database, you can store the singleton queue/pool in a global initialized when application starts. Even if you do not like globals, make sure to instantiate a single queue or pool. For sample code, see Database.swift in the GRDBDemo app.

The dead link is:

https://github.com/groue/GRDBDemo/blob/master/GRDBDemo/Database.swift

**Comment by aczel** [comment]
The dead link is:

https://github.com/groue/GRDBDemo/blob/master/GRDBDemo/Database.swift

**Comment by aczel** [comment]
Also I can see this repo (https://github.com/groue/GRDBDemo) has been archived. But the follow-up link is also dead.

> The GRDB demo application has moved!

https://github.com/groue/GRDB.swift/blob/master/DemoApps/GRDBDemoiOS/README.md

**Comment by aczel** [comment]
Thank you for your AWESOME job. This library is amazing! :)

**Comment by groue** [comment]
Thank you @aczel for reporting this! 👍

**Comment by groue** [comment]
Links are fixed 🙂

**Comment by aczel** [comment]
@groue Thank you! :)
