### ISSUE TITLE
SQLite error 1 "no such column" when using Xcode12

### ISSUE THREAD

**Issue by thieso2** [groue/GRDB.swift#834]
### What did you do?

I feel really stupid for submitting this. You have been so helpful in the past and *maybe* this will trigger an immediate  "Oh!" on your side (fingers crossed)? Having said this I am _willing_ to dive deep on this one and create a test case if you need that..

I have a project that works fine using Xcode11. Xcode12b6 works fine on Catalina. On BigSur I get :

```
            try db.execute(sql:"""
                update WebSession set portName = "", extensionId = "", extensionVersion = ""
                """)

```

### What did you expect to happen?

the update to work;-)

### What happened instead?

Error: 'SQLite error 1 with statement `update WebSession set portName = "", extensionId = "", extensionVersion = ""`: no such column: '

the interesting bit is that if I change the double-quotes to single-quotes in the SQL statement it works. So it has to do with parsing the sql in GRDB. That's all I can say. I have other occurrences of the same problem where the error-message contains a fieldName that it not even in the query.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
GRDB
**GRDB version:**
5.0b10 
**Installation method:** (CocoaPods, SPM, manual?)
SPM
**Xcode version:**
Xcode12b6
**Swift version:**
latest
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
BigSur (latest beta)
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @thieso2,

You are not the first to witness an app which starts failing after the upgrade to Big Sur or iOS 14. And it's all about the double-quote indeed. 

I just added a new FAQ just about it: [SQLite error 1 "no such column"](https://github.com/groue/GRDB.swift/blob/master/README.md#sqlite-error-1-no-such-column). Please tell me if it makes sense and helps you fix your app :-)

**Comment by martindufort** [comment]
Confirmed. 
Same thing here running on Xcode 12 / DTK (Apple Silicon). 
```
Ocean[13442:2647878] [logging] no such column: 2020-09-10T00:00:00.000Z in "	select count(ocean_task.uuid) from ocean_task
	where ocean_task.due_date < "2020-09-10T00:00:00.000Z"
			and ocean_task.is_completed = 0
			and ocean_task.is_archived = 0"
```

SQLite version on Big Sur is:
```
martindufort@Siliconius ~ % sqlite3 --version
3.31.1 2020-02-01 00:08:28 d250d085fa4bd6509ab074d15f1c11fcc15d0cc150e5e429b191eb5a92e0aapl 
```

**Comment by groue** [comment]
Good!
