### ISSUE TITLE
How to filter records by subtracting two columns with datetime in SQLite?

### ISSUE THREAD

**Issue by dingronghui** [groue/GRDB.swift#835]
Hi @groue,
I use GRDB and am really happy. And I'm syncing with CloudKit now. I must get all records that need to be pushed to iCloud.
### Question:
```swift
class BodyData : Record, Encodable {
	var modified: Date
	var ckLastSaved: Date
	var height: Double
	var weight: Double
	var ckRecord: Data
	...
}
```
I want to get all records that (Column("modified") - Column("ckLastSaved)) > (1 second). Then push them.
Maybe like this:
```swift
BodyData.filter(Column("modified") - Column("ckLastSaved")>1).fetchAll(db)
```
How can i achieve it. Thank you so much.

**Comment by groue** [comment]
Hello @dingronghui,

You can use the [julianday](https://sqlite.org/lang_datefunc.html) SQLite function. It is available from Swift:

```swift
// Convert dates to Julian days, and subtract:
let dayDiff = julianDay(Column("modified")) - julianDay(Column("ckLastSaved"))
// Convert to seconds
let secondDiff = dayDiff / 86400
// Filter items
let items = try BodyData.filter(secondDiff > 1).fetchAll(db)
// SELECT * FROM ... WHERE ((julianday(modified) - julianday(ckLastSaved)) / 86400) > 1
```

Caution: the julianday SQLite function does not accept all date formats. By default, GRDB stores dates using the `YYYY-MM-DD HH:MM:SS.SSS` format, which is compatible. Check [julianday](https://sqlite.org/lang_datefunc.html) and [Date and DateComponents](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-datecomponents) for more information.

**Comment by dingronghui** [comment]
@groue

**Comment by dingronghui** [comment]
@groue 
Your reply is always very efficient. It just took me  a little time [Migrating From GRDB 4 to GRDB 5](https://github.com/groue/GRDB.swift/blob/master/Documentation/GRDB5MigrationGuide.md). Then I got the excellent julianday SQLite function .
A little fix:
```swift
// Convert to seconds
let secondDiff = dayDiff *86400
```
Thank you so much.😃
