### ISSUE TITLE
Unexpected results with custom `update(_ db: Database, columns: Set<String>)` implementation 

### ISSUE THREAD

**Issue by daSkier** [groue/GRDB.swift#839]
### What did you do?

I'm working on implementing a record `struct` conforming to `MutablePersistableRecord` with support for a custom update persistence method as follows: 
```Swift 
struct FISList: Codable, FetchableRecord, MutablePersistableRecord  {
    public var id: Int64?
    public var vaporId: UUID
    public var listId: Int
    public var listString: String
    public var listYear: Int
    public var yearlyListNumber: Int
    public var seasonCode: Int
    public var calculationDate: Date
    public var startRaceDate: Date
    public var endRaceDate: Date
    public var validFromDate: Date
    public var validToDate: Date
    public var athleteImportComplete: Bool
    public var pointsImportComplete: Bool
    public var vaporCreatedAt: Date
    public var vaporUpdatedAt: Date
    public var localCreatedAt: Date?
    public var localUpdatedAt: Date?

    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
    
   mutating func insert(_ db: Database) throws {
        if localCreatedAt == nil {
            localCreatedAt = Date()
        }
       localUpdatedAt = Date()
       try performInsert(db)
       }
       
   mutating func update(_ db: Database, columns: Set<String>) throws {
        localUpdatedAt = Date()
        try performUpdate(db, columns: columns)
    }
}

extension FISList: TableRecord {
    // Customized table name
    static let databaseTableName = "fisList"
}

extension FISList: Hashable { }
extension FISList: Identifiable { }
```

```Swift
struct FISListRepository {
    private let database: DatabaseWriter
    typealias GRDBType = FISList

    init(database: DatabaseWriter) {
        self.database = database
    }

    func update(fisList: GRDBType) throws {
        try database.write { db in
            var listForUpdate = fisList
            try listForUpdate.save(db)
        }
    }

    // since importing from an external datasource, check for existence of the external key "vaporId"
    func upsert(fisList: GRDBType) throws {
        try database.write { db in
            guard var fetchedFisList = try GRDBType.filter(FISList.Columns.vaporId == fisList.vaporId).fetchOne(db) else {
                var fisListForSave = fisList
                try fisListForSave.insert(db)
                return
            }
            try fetchedFisList.updateChanges(db, from: fisList)
        }
    }
}
```

When updating a record with new information I'd like the `localUpdatedAt` value to be updated automatically. To do this I've implemented the `update(_ db: Database, columns: Set<String>)` function to update `localUpdatedAt` on any update calls [as shown in [Customizing the Persistence Methods](https://github.com/groue/GRDB.swift#customizing-the-persistence-methods)]. 

To test this I ran the following:
```Swift
class FISListRepositoryTests: XCTestCase {
    override func setUpWithError() throws {
        try GlobalDBManager.fisListRepository.deleteAll()
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }
    
    func testFisListUpdate() throws {
        // Initial List Creation and Insert
        var firstFisList = FISList.sampleFISList()
        try GlobalDBManager.fisListRepository.insert(fisList: &firstFisList)
        guard let returnedFirstFisList = try GlobalDBManager.fisListRepository.allLists().first else {
            XCTFail()
            return
        }
        XCTAssertNotNil(returnedFirstFisList.id)
        XCTAssertNotNil(returnedFirstFisList.localCreatedAt)
        XCTAssertNotNil(returnedFirstFisList.localUpdatedAt)
        
        // Sleep just to make sure Date() can't be the same
        sleep(1)
        
        // Update list and test update
        var updatedFisList = returnedFirstFisList
        updatedFisList.calculationDate = Date()
        try GlobalDBManager.fisListRepository.update(fisList: updatedFisList)
        guard let returnedUpdatedFisList = try GlobalDBManager.fisListRepository.allLists().first else {
            XCTFail()
            return
        }
        XCTAssertNotEqual(returnedUpdatedFisList.localUpdatedAt, returnedFirstFisList.localUpdatedAt)
        XCTAssertNotEqual(returnedUpdatedFisList.calculationDate, returnedFirstFisList.calculationDate)
    }
}
```

### What did you expect to happen?
Based on the [Customizing the Persistence Methods](https://github.com/groue/GRDB.swift#customizing-the-persistence-methods) documentation I expected the save in `update(fisList:)` to eventually call my implementation of `update(_ db: Database, columns: Set<String>)` and result in `localUpdatedAt` being updated to the current date. 

### What happened instead?

The tests show that the `localUpdatedAt` values are the same for both `returnedFirstFisList` and `returnedUpdatedFisList` in `testFisListUpdate()`. 

Also of note, I don't see my version of `update(_ db: Database, columns: Set<String>)` ever getting called when I set a breakpoint and step through the execution . 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.0-beta.11
**Installation method:** SPM
**Xcode version:** 12.0
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.6 (19G2021)

### Demo Project

[GRDBDemoUpdateError.zip](https://github.com/groue/GRDB.swift/files/5250812/GRDBDemoUpdateError.zip)

**Comment by groue** [comment]
Hello @daSkier,

The `update(_: columns:)` method defined by the record protocols is not mutating. The customized version in your sample code is mutating, and is not recognized by the compiler as the one that should be called by `save(_:)` and other persistence methods. This explains why the test is failing.

One possible solution is to declare `FISList` as a class instead of a struct, and have it conform to `PersistableRecord` instead of `MutablePersistableRecord`.

**Comment by daSkier** [comment]
Hi @groue,

Thanks for the assistance. Are there any downsides to using the class based records rather than structs when using the GRDBCombine components?

**Comment by groue** [comment]
> Are there any downsides to using the class based records rather than structs when using the GRDBCombine components?

Ideally, GRDB lets you choose between structs or classes. But this scenario is one of the few that are better served with a class.

The consequences are the same as they generally are with Swift structs and classes. But there is no consequence on GRDB and related code.

**Comment by groue** [comment]
I close this issue since it looks like you accept the proposed solution. Feel free to reopen or ask for more information if needed!
