### ISSUE TITLE
Swift 2.3 compability

### ISSUE THREAD

**Issue by dral3x** [groue/GRDB.swift#84]
Hi there,

first thank you for this great SQLite wrap library!

I'm trying to update my app to iOS10 and swift 2.3 (at least) using Xcode 8 beta 1 (for now).
I'm not able to compile GRDB.swift framework because of this main error 
```
/workspace/ios-radio/Pods/GRDB.swift/GRDB/Core/Configuration.swift:10:20: Could not build Objective-C module 'SQLiteiPhoneOS'
```

Any hint on how to solve this?

**Comment by groue** [comment]
Hello @dral3x 

I'm currently working on Swift 2.2 on the master branch, and on Swift 3 on the Swift3 branch. I don't plan to support Swift 2.3.

**Comment by groue** [comment]
I think your current problem lies in the paths defined in the Module map: update the iOS path so that if points inside Xcode-beta.app

**Comment by dral3x** [comment]
Good point. I will check it. Thanks

**Comment by dral3x** [comment]
It works.
Is there anything we can do for not having Xcode path hardcoded in the modulemap file?

Thanks

**Comment by groue** [comment]
Not to my knowledge. What do https://bugs.swift.org, http://www.openradar.me, and Google say?

**Comment by dral3x** [comment]
Nothing relevant. Thanks anyways
