### ISSUE TITLE
Grammar nit GRDBCombineDemo uses "edition" where I think it should use "editing"

### ISSUE THREAD

**Issue by jackpal** [groue/GRDB.swift#843]
I noticed that the GRDBCombineDemo source code uses the word "edition" where I think the intended word was "editing", "editor", or "editing session".

It's possible that "edition" is a term of the art for an editing session, but I don't think I've ever heard or read it being used that way.

See for example

https://github.com/groue/GRDB.swift/blob/master/Documentation/DemoApps/GRDBCombineDemo/GRDBCombineDemo/Views/PlayerForm.swift

line 3: /// The Player edition form, embedded in both

I wonder if there was a search-and-replace accident somewhere along the line.

**Comment by groue** [comment]
Thanks @jackpal for fixing my non-native English 🙂. I hope it sounds better now.

**Comment by groue** [comment]
The new wording has shipped in v5.0.1. Improvements to the English language in this project and its documentation are very much welcome: don't hesitate submitting a pull request when you spot an odd-looking sentence!
