### ISSUE TITLE
Is it possible to enable FTS5 when installing via Swift Package Manager?

### ISSUE THREAD

**Issue by janine-knowink** [groue/GRDB.swift#848]
### What did you do?

Our app has until recently used Carthage exclusively.  Due to GRDB not supporting that (which I fully understand), we have included the built framework in our app.  This has to be updated every time we update Xcode, and I thought I'd try out installing it via SPM instead so that it would be automatically rebuild with the new version of the swift compiler.

This worked fine except for one thing - no FTS5.  I have read the documentation about how to make this work with Cocoapods, and the project does have "-D SQLITE_ENABLE_FTS5" added to OTHER_SWIFT_FLAGS, but that doesn't seem to be being used when compiling the package.   It looks like I could possibly get it enabled by using a Custom SQLite build, but since that requires cloning the project it seems like that would preclude using the SPM package.

### What did you expect to happen?

FTS5 support to be present.

### What happened instead?

Errors such as "Cannot find type 'FTS5TokenizerDescriptor' in scope" when compiling our code, which worked fine before I switched from embedded framework to SPM.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.2, I believe
**Installation method:** SPM
**Xcode version:** 12.0
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.6

### Demo Project

Right now this is just a question.  If it turns out there's an actual issue here, I will try to make one.

**Comment by groue** [comment]
Hello @janine-knowink,

This issue is the same as https://github.com/groue/GRDB.swift/issues/819
