### ISSUE TITLE
Use of undeclared type 'DatabaseCancellable'

### ISSUE THREAD

**Issue by SNNafi** [groue/GRDB.swift#851]
### What did you do?

I have used the GRDBDemoiOS from DemoApps

### What did you expect to happen?

Build successfully

### What happened instead?

 got this error "Use of undeclared type 'DatabaseCancellable' "

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version: 4.14.0
**Installation method:** (CocoaPods)
**Xcode version:** 11.7 
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS 
**macOS version running Xcode:** 10.15.7

### Demo Project
I have used the GRDBDemoiOS from DemoApps

**Comment by groue** [comment]
Hello @SNNaf,

The `DatabaseCancellable` type was introduced with GRDB 5. It was not there in the GRDB 4.14 version you are using.

I suggest you upgrade to v5, or download the demo app of v4.14.

**Comment by SNNafi** [comment]
Thank you
