### ISSUE TITLE
Bug with IFNULL on iOS 14 ?

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#857]
Hi

GRDB 4.14.0 (i will test later with GRDB 5.x, it's an occasion to migrate)

I see a strange bug since iOS 14, and i'm almost sure it don't come from GRDB, but ...

```
Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement 

`SELECT mediaitems.`primary`, mediaitems.`title`, "idxorder", mediaitems.`image`,
            IFNULL(xmltvepg.`start`, "2020-10-20 22:00:00 +0000") AS `start`,
            IFNULL(xmltvepg.`end`, "2020-10-26 22:00:00 +0000") AS `end`,
            IFNULL(xmltvepg.`title`, "N/A") AS xmltitle,
            IFNULL(xmltvepg.`keyCompare`, "") AS keyCompare
            FROM "mediaitems"
            LEFT JOIN xmltvepg ON ((xmltvepg."channel" = mediaitems."virtualPath") AND (xmltvepg.`primary` = '<redacted>'))
            WHERE (((mediaitems.credent = '<redacted>') AND (mediaitems.customInt3 = 0) AND (mediaitems.isVirtualPath = 0)) AND (mediaitems.playurl <> '') AND mediaitems.isSerieRoot = 0 AND mediaitems.mediaType = 5)
            ORDER BY mediaitems.titleNormalized`

: no such column: 2020-10-20 22:00:00 +0000:
```

This query works on iOS <= 13 and tvOS <= 13 but since iOS 14 i got this error
Also, using this query on my sqlite client on macOS works fine too.

Do you have see something similar on your side ?

**Comment by groue** [comment]
Hello @skrew, it's good to see you again ;)

This `no such column` error is indeed something that can happen on the recent version of SQLite that ships with iOS 14. See the [SQLite error 1 "no such column"](https://github.com/groue/GRDB.swift#sqlite-error-1-no-such-column) FAQ, it explains everything!

**Comment by skrew** [comment]
It's good to see you again too, and you bring luck ! :)

I have tested with single quote, which works, and i just go back here to say "hey i have found it !" but too late ! :)

I think you have to put this iOS 14 problem somewhere it can be found easily.

Thanks again ;)
