### ISSUE TITLE
GRDB Swift Package Manager + SQLCipher Manually

### ISSUE THREAD

**Issue by xramos** [groue/GRDB.swift#858]
For the project i'm working on I am not able to install GRDB with cocoapods so instead I installed via Swift Package Manager and is working perfect. However I have a problem now if I want to use SQLCipher, "Configuration has no method usePassphrase".

So even if I install SQLCipher manually I won't be able to link it with GRDB, right? There's anything that can be done here? Like having a GRDB+SQLCipher extension or something like this?

### What did you do?

Install GRDB via Swift Package Manager

### What did you expect to happen?

I did expect to be able to encrypt/decrypt database using SQLCipher

### What happened instead?

Configuration method usePassphrase is not defined

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.2
**Installation method:** SPM
**Xcode version:** 12.0.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Catalina 10.15.7

**Comment by groue** [comment]
Hello @xramos. As you've seen, SPM is not listed in the supported installation procedures for SQLCipher. For further information, please see #556 and the related issues.

**Comment by xramos** [comment]
actually the problem is not with SPM. GRDB via SPM is installed correctly and I have no issue there. The problem is regarding the connection between GRDB and SQLCipher installed manually

**Comment by groue** [comment]
This is a dangerous territory, @xramos. GRDB via SPM links against the system SQLite, not SQLCipher. And it is often painful to have both SQLite and SQLCipher linked to an application: unexpected conflicts arise. Unless you have a local Xcode guru, I strongly suggest you drastically simplify your setup.

**Comment by xramos** [comment]
Thanks for your answers @groue I will try a different approach then

**Comment by brunomunizaf** [comment]
I thought I could finally ditch cocoapods... *sobbing*
