### ISSUE TITLE
attempt to write a readonly database - while executing `UPDATE ....

### ISSUE THREAD

**Issue by waleedmakarem** [groue/GRDB.swift#860]
Dear Sir, 
Thanks for this nice library, really appreicciate sharing it. 

when creating DB, works properly, when insert new records, .. works fine. but when try to update database record, I get below error :
"atal error: 'try!' expression unexpectedly raised an error: SQLite error 8: attempt to write a readonly database - while executing `UPDATE ...."

my code is 

func  UpdateRecord(){
        do { dbQueue.read { db in
            try! db.execute(
                   sql: "UPDATE \(TABLE_NAME) SET \(COLUMN_COUNT) = :newcount WHERE \(COLUMN_CODE) = :barcode",
                   arguments: ["newcount": itemCount, "code": code])
        }
        }

-----------> I am initializing my database in ViewDidLoad with following code 

 let fileURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false).appendingPathComponent(dbName)
   dbQueue =  try! DatabaseQueue(path: fileURL.path)

-------- > Also , I am setting below variables as global 
let dbName = "myDBmmzM.drk"
var dbQueue  =   DatabaseQueue(  )

**Comment by groue** [comment]
Hello @waleedmakarem,

An `UPDATE` sql statement modifies the database, and raises an error when executed from `dbQueue.read { ... }`.

When you want to modify the database, use `dbQueue.write { ... }` instead.

**Comment by waleedmakarem** [comment]
Excellent... Thanks for the library and the support as well -:)
