### ISSUE TITLE
No such column when using multiple foreign keys

### ISSUE THREAD

**Issue by UnderratedDev** [groue/GRDB.swift#865]
## What did you do?
I used #377 as a template for implementing the hasMany, & it caused SQLite issues. I believe it is something to do with the double quotes, not 100% but I tried copying & past

### What did you expect to happen?

It should make a middle table so that I could get a hasMany relation

### What happened instead?

```Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1: no such column: scheduleID, scheduledBlockID - while executing `CREATE TABLE "ScheduleScheduledBlock" ("scheduleID" INTEGER NOT NULL REFERENCES "Schedule"("id") ON DELETE CASCADE, "scheduledBlockID" INTEGER NOT NULL REFERENCES "ScheduledBlock"("id") ON DELETE CASCADE, PRIMARY KEY ("scheduleID, scheduledBlockID")); CREATE INDEX "ScheduleScheduledBlock_on_scheduleID" ON "ScheduleScheduledBlock"("scheduleID"); CREATE INDEX "ScheduleScheduledBlock_on_scheduledBlockID" ON "ScheduleScheduledBlock"("scheduledBlockID"):```

I tried my own SQLite & this worked:
```
CREATE TABLE "Schedule" (
    ID integer PRIMARY KEY
);

CREATE TABLE "ScheduledBlock" (
    ID integer PRIMARY KEY
);

CREATE TABLE "ScheduleScheduledBlock" (
    "ScheduleID" INTEGER NOT NULL,
    "ScheduledBlockID" INTEGER NOT NULL,
    
    FOREIGN KEY ("ScheduleID") REFERENCES "Schedule"("ID")
    FOREIGN KEY ("ScheduledBlockID") REFERENCES "ScheduledBlock"("ID")
    
    PRIMARY KEY ("ScheduleID", "ScheduledBlockID")
);
```

I think it is the References being on the same line as the column verses a separate foreign key statement but I'm not entirely sure
### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.1
**Installation method:** SPM
**Xcode version:** 12.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS (iPhone 8 simulator + iPhone 6 real device)
**macOS version running Xcode:** 10.15.6

### Demo Project

```
migrator.registerMigration("scheduledBlock") { (database) in
    try database.create(table: "ScheduledBlock") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("duration", .double).notNull()
        t.column("iconID", .integer)
            .notNull()
            .indexed()
            // deletes all scheduled blocks associated to icon when icon is deleted
            .references("Icon", onDelete: .cascade)
        t.column("name", .text).notNull()
        t.column("colourHex", .text).notNull()
    }
}

migrator.registerMigration("schedule") { (database) in
    try database.create(table: "Schedule") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("dateSeconds", .double)
    }
}

migrator.registerMigration("scheduleScheduledBlock") { (database) in
    try database.create(table: "ScheduleScheduledBlock") { t in
        t.primaryKey(["scheduleID, scheduledBlockID"])
        t.column("scheduleID", .integer)
            .notNull()
            .references("Schedule", onDelete: .cascade)
            .indexed()
        t.column("scheduledBlockID", .integer)
            .notNull()
            .references("ScheduledBlock", onDelete: .cascade)
            .indexed()
    }
}
```

**Comment by groue** [comment]
Hello @UnderratedDev,

Indeed your code attempts at creating a primary key on a non-existing column named `"scheduleID, scheduledBlockID"`. In your case, your primary key has two columns, so you need to pass an array of two columns to the `primaryKey` method:

```diff
-t.primaryKey(["scheduleID, scheduledBlockID"])
+t.primaryKey(["scheduleID", "scheduledBlockID"])
```

Yes, #377 contains faulty manually written code, that was not fully tested, and that you copied into your app. This happens.

#377 also contains quite outdated information. Since then (2018), the [HasManyThrough](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#hasmanythrough) association has been introduced in order to help dealing with many-to-many relationships.

Happy GRDB!

**Comment by UnderratedDev** [comment]
Hey Groue, thanks so much for the quick reply. Also I want to say, I was originally going to manually do SQLite & then I saw this library which had lots of cool features but sometimes libraries go dead after a while. However, I decided to go for it as I saw how much support you give & the active community!! Thanks for the quick reply & help!!
