### ISSUE TITLE
I'm using sqlite.swift on my project. How do I use GRDB.swift

### ISSUE THREAD

**Issue by she1323** [groue/GRDB.swift#867]
I'm using sqlite.swift on my project. How do I use GRDB.swift

**Comment by groue** [comment]
Thank you for switching, but this question is overly vague. This is your second question of low quality today (previous was #866).

Please only open a Github issue for reporting specific issues, or asking specific questions about GRDB. Meanwhile, please refer to the documentation, thank you.
