### ISSUE TITLE
SQLite error 1: no such column:  - while executing...

### ISSUE THREAD

**Issue by jaaabeee** [groue/GRDB.swift#874]
### What did you do?
GRDB 5.0.2 with XCode 12.1 - fetchAll() query on a temporary table works fine in my MacOS app.
Updated to XCode 12.2 and Swift 5.2.4 (and Big Sur) and fetchAll() now throws a 'no such column' error with no column specified. 

App built before the updates still works. Executing the query at the command line still works. Executing the query in SQLPro still works.

Updated GRDB pod to 5.1 but no change in result.
fetchAll() on normal non-TEMP tables works fine in same app. 

### What did you expect to happen?

Expected query of temporary table to still return array of records, rather than throw exception. 

### What happened instead?

```
SQLite error 1: no such column:  - while executing `    SELECT
        r.dtFrom AS 'From',
        r.dtTo AS 'To',
        r.gallons AS 'Gallons',
       ...
```

### Environment

**GRDB flavor(s): GRDB** 
**GRDB version: 5.1.0**
**Installation method: CocoaPods**
**Xcode version: 12.2**
**Swift version: 5.2.4**
**Platform(s) running GRDB: macOS** 
**macOS version running Xcode: 11.0.1**

**Comment by groue** [comment]
Hello @jaaabeee. There's a FAQ about your issue: https://github.com/groue/GRDB.swift/blob/master/README.md#sqlite-error-1-no-such-column

**Comment by jaaabeee** [comment]
Thanks, but that FAQ doesn’t apply in my case. I’m not using double quotes, and if you look at the error being thrown it doesn’t provide a column name - it is blank. Also, this query works fine in the command line and SQLite Pro, and worked in GRDB until I installed Swift 5.2. Finally, this only occurs with temporary tables. I have dozens of queries that work fine - only the ones that query TEMP tables fail in this way.

I combined the queries into a large one to avoid using TEMP tables - that works but is much less sustainable. But I’ll have to do that to get the app working again for the client.

JB

—
"The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time." - Tom Cargill

**Comment by groue** [comment]
> Thanks, but that FAQ doesn’t apply in my case. I’m not using double quotes, and if you look at the error being thrown it doesn’t provide a column name - it is blank.

A simple empty string literal `""` (which you know IS NOT a string literal now that you've read the FAQ) will trigger the bug: please check again the SQL request run by your app.

> Also, this query works fine in the command line and SQLite Pro, and worked in GRDB until I installed Swift 5.2.

The FAQ explains that it's more likely a deployment target issue, and also that SQLite Pro is likely to accept non-standard SQL, or to run a different SQLite version.

> Finally, this only occurs with temporary tables. I have dozens of queries that work fine - only the ones that query TEMP tables fail in this way.

Please remember that `no such column` is an **SQLite error** generated by the SQL run by your app. They are not a GRDB error. I must make this pretty clear, since you seem to imply that those errors are generated in this library.

So do review the SQL run by your app again. When you can prove the FAQ does not apply, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):

```swift
try DatabaseQueue().write { db in
    // Reproduce the failure
}
```

Thank you

**Comment by jaaabeee** [comment]
I’m only saying that updating to the new Xcode/Swift with no database or code changes triggered the sqlite error, which of course seems silly. My working theory is that the new toolchain is injecting or resulting in injecting the empty literal somewhere to cause the problem.

The query in the command line in sqlite3 itself works without an error. The only thing I changed was updating to Xcode 11.2, which updated Swift to 5.2. No other changes to the code, the database, or the GRDB pod. The app built with Xcode 11.1 runs fine even in the new OS.

Will isolate the code into a small example and send along.

--
It is no coincidence that in no known language does the phrase 'As pretty as an Airport' appear. 
-- Douglas Adams

**Comment by groue** [comment]
> I’m only saying that updating to the new Xcode/Swift with no database or code changes triggered the sqlite error, which of course seems silly.

macOS evolves, and SQLite as well.

You can opt-in for non-standard SQL with [Configuration.acceptsDoubleQuotedStringLiterals](http://groue.github.io/GRDB.swift/docs/5.1/Structs/Configuration.html#/s:4GRDB13ConfigurationV33acceptsDoubleQuotedStringLiteralsSbvp). This may help you move on to your next interesting task faster:

```swift
var config = Configuration()
config.acceptsDoubleQuotedStringLiterals = true
let dbQueue = DatabaseQueue(configuration: config)
let string = try dbQueue.read { db in
    try String.fetchOne(db, sql: "SELECT \"\"") // OK
}
```

**Comment by jaaabeee** [comment]
I found the error - rookie mistake for someone who’s been writing code for over 50 years. :-)

I had the following in my SELECT
	ifnull(r.flag, "") AS 'Flag’,  <-double quotes
Instead of 
	ifnull(r.flag, '') AS 'Flag’,  <- correct single-quoted literal

Doh! Not sure how changing Xcode triggered this, but glad to move this (quickly) behind me…

Thanks for the feedback.

—
“Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun. Orbiting this at a distance of roughly ninety-two million miles is an utterly insignificant little blue green planet whose ape-descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea.” 
― Douglas Adams

**Comment by groue** [comment]
> rookie mistake for someone who’s been writing code for over 50 years. :-)

You're welcome! That's 15 more years than myself ;-)
