### ISSUE TITLE
Filter column being IN a set of values

### ISSUE THREAD

**Issue by georgbachmann** [groue/GRDB.swift#876]
I have a table with a column called "type". It contains Integers and I'd like to filter something like:

`SELECT * FROM myTable where type IN (1, 2, 3);`

I've seen that I can write something like `Column("type").like` or `Column("type") == 1` but no `Column("type").in` or something like that.

Also trying to do in manually doesn't work for me:
```
let types = [1, 2, 3]
let allTypesAsString = types.map({ "\($0.intValue)" }).joined(separator: ",")
let filterExpression = "type IN (\(allTypesAsString))".sqlExpression
```
which would generate something that is valid SQL (like the sample query above), but when querying with it, I always get 0 results.

As I have multiple filters (besides that type IN filter) that I want to add to my query, I'd be nice if I could build them as `SQLExpression` and then join that array using the `.joined(operator: .and)` function. I guess that's the intended way of doing it, right?

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.14 (I still have to support older iOS versions at least for one build)
**Installation method:** SPM
**Xcode version:** 12.2
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** BigSur (11.0.1)

P.s.: if my question was already asked by someone else... sorry... the word `in` is such a stupid word to search for :)

**Comment by georgbachmann** [comment]
Ok... blind me already found it ;)
So for anybody else being as blind as I am:

```
        extension Sequence where Self.Iterator.Element: SQLExpressible {
            /// An SQL expression that checks the inclusion of an expression in
            /// a sequence.
            ///
            ///     // id IN (1,2,3)
            ///     [1, 2, 3].contains(Column("id"))
            public func contains(_ element: SQLSpecificExpressible) -> SQLExpression {
                return SQLExpressionsArray(self).contains(element.sqlExpression)
            }

            /// An SQL expression that checks the inclusion of an expression in
            /// a sequence.
            ///
            ///     // name IN ('A', 'B') COLLATE NOCASE
            ///     ["A", "B"].contains(Column("name").collating(.nocase))
            public func contains(_ element: SQLCollatedExpression) -> SQLExpression {
                return SQLExpressionCollate(contains(element.expression), collationName: element.collationName)
            }
        }
```

so my query now looks like this:

```
let validTypes = [1, 2, 3]
let filterExpression = validTypes.contains(Column("type"))
```

**Comment by groue** [comment]
Hello @georgbachmann,

You found it! 👍 

See [SQL Operators](https://github.com/groue/GRDB.swift/blob/master/README.md#sql-operators) for a reference.

---

On building expressions from raw SQL:

> ```swift
> let types = [1, 2, 3]
> let allTypesAsString = types.map({ "\($0.intValue)" }).joined(separator: ",")
> let filterExpression = "type IN (\(allTypesAsString))".sqlExpression
> ```

This builds a string value, not raw SQL. A working version would be:

```swift
let types = [1, 2, 3]
let allTypesAsString = types.map({ "\($0.intValue)" }).joined(separator: ",")
let sql = "type IN (\(allTypesAsString))"
let request = MyRecord.filter(sql: sql)
```

Yet, here is the mandatory advice: generally beware of injecting values in your hand-crafted SQL.

Preferred options are:

```swift
// WHERE type IN (?, ?, ?)
let types = [1, 2, 3]
let sql = "type IN (\(databaseQuestionMarks(count: types.count)))"
let request = MyRecord.filter(sql: sql, arguments: StatementArguments(types))
```

GRDB 4 `SQLExpression` has been replaced in GRDB 5, which relies much more on [SQL Interpolation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md) in order to help developers build raw SQL snippets when the query interface falls short:

```swift
// Also works when the types collection is empty.
// Also works with complex expressions (you can `&&`, `||`, etc)
// Also works when request is joined with other tables and the `type` column needs disambiguation.
let types = [1, 2, 3]
let literal: SQLLiteral = "\(Column("type")) IN \(types)"
let expression = literal.sqlExpression
let request = MyRecord.filter(expression)
```

**Comment by georgbachmann** [comment]
@groue thank you so much for your great answer! GRDB is a delight because of the awesome support from you!
Thank you very much!

**Comment by groue** [comment]
You may help your coworkers, this issue may help other users, and answering trains my memory of the GRDB apis ;-)

**Comment by groue** [comment]
Also, @georgbachmann, this repo is lucky enough to have mostly issues of high quality and genuine interest, even when the answer is easy. This is a blessing :-)
