### ISSUE TITLE
Using an association struct with the combine framework fails.

### ISSUE THREAD

**Issue by Chpetrou** [groue/GRDB.swift#878]
### General Information

Hello

I have a database already loaded with data, and I am trying to load them into my macOS app. As I am using SwiftUI, I followed the demo of GRDB with the Combine framework, and I tried to use the relevant parts with my own data. I also have several association structs as it is documented here: https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#combining-associations.

When I try to use it normally in with the dbQueue like this `ContinentInfo.request.fetchAll`, it fetches the results just fine.

When I try to use it with Combine, it returns an empty list, and when debugging, it says,

> error message: "no such table: continentInfo"
> sql: "SELECT (SELECT * FROM \"continents\") FROM \"continentInfo\""

my database has a "continents" table and a "countries" table, and continentInfo struct has a `var continent: Continents` and a `var countries: [Countries]` along with their requests and associations.

### Question

How can I fetch the results of continentInfo with the Combine framework for using it with SwiftUI?

**Comment by groue** [comment]
Hello @Chpetrou,

> When I try to use it normally in with the dbQueue like this `ContinentInfo.request.fetchAll`, it fetches the results just fine.

I don't know what `.request` is (this is not built-in GRDB api), but so far, so good.

> When I try to use it with Combine, it returns an empty list, and when debugging, it says, `no such table: continentInfo`

Well, you don' run the same request as in the successful case, then. There's no other conclusion. Besides, nothing in GRDB "returns an empty list, and says something when debugging". Only application code does (and in this case, this somewhat obscures your investigation).

My advice: make sure you run the same request from Combine publishers. If you still have an issue, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Chpetrou** [comment]
Hello @groue,

Thanks for the quick response!

Below i provide the relevant code examples for this issue. Most of the code, is derivable from the documentation: [Documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#documentation) and from the demo code: [GRDBCombineDemo](https://github.com/groue/GRDB.swift/tree/master/Documentation/DemoApps/GRDBCombineDemo)

My ContinentInfo is like this:

``` swift
import Foundation
import GRDB

struct ContinentInfo: FetchableRecord, Codable {
    var continent: Continents
    
    var countries: [Countries]
}

extension ContinentInfo: EncodableRecord {
    static let request = Continents.including(all: Continents.countries)

    static func createRequestByName(name: String) -> QueryInterfaceRequest<Continents> {
        return Continents
            .including(all: Continents.countries)
            .filter(Column("name") == name)
    }

    static func createRequestById(id: Int64) -> QueryInterfaceRequest<Continents> {
        return Continents
            .including(all: Continents.countries)
            .filter(Column("id") == id)
    }

    static func orderRequestByName() -> QueryInterfaceRequest<Continents> {
        return Continents
            .including(all: Continents.countries
                        .order(Column("name")))
    }

    static func orderRequestById() -> QueryInterfaceRequest<Continents> {
        return Continents
            .including(all: Continents.countries
                        .order(Column("id")))
    }

    static func addRequest(request: QueryInterfaceRequest<Continents>) -> QueryInterfaceRequest<ContinentInfo> {
        return select(request)
    }
}
```

I have it conforming to the `TableRecord` protocol, so i am able to have the `addRequest` function, which i may give as a parameter the result of the `createRequestByName` function.

My ModelView is like this:

``` swift
import Foundation
import Combine

final class CatalogueSpaceViewModel: ObservableObject {
    enum Ordering {
        case byName
        case byId
    }

    /// The list ordering
    @Published var ordering: Ordering = .byName

    /// The continents in the list
    @Published var continentList: [ContinentInfo] = []

    private let database: AppDatabase
    private var continentCancellable: AnyCancellable?

    init(database: AppDatabase) {
        self.database = database
        continentCancellable = continentPublisher(in: database)
            .sink { [weak self] continentList in
                self?.continentList = continentList
            }
    }

    /// Toggles between the available orderings
    func toggleOrdering() {
        switch ordering {
        case .byName:
            ordering = .byId
        case .byId:
            ordering = .byName
        }
    }

    private func continentPublisher(in database: AppDatabase) -> AnyPublisher<[ContinentInfo], Never> {
        $ordering.map { ordering -> AnyPublisher<[ContinentInfo], Error> in
            switch ordering {
            case .byId:
                return database.continentsOrderedByIdPublisher()
            case .byName:
                return database.continentsOrderedByNamePublisher()
            }
        }
        .map { continentsPublisher in
            // Turn database errors into an empty continents list.
            continentsPublisher.catch { error in
//                print(error)
                Just<[ContinentInfo]>([])
            }
        }
        .switchToLatest()
        .eraseToAnyPublisher()
    }
}
```

And the AppDatabase is like this:

``` swift
import Combine
import GRDB

struct AppDatabase {
    private let dbWriter: DatabaseWriter

    /// Creates an AppDatabase and make sure the database schema is ready.
    init(_ dbWriter: DatabaseWriter) throws {
        self.dbWriter = dbWriter
    }
}

extension AppDatabase {
    /// Returns a publisher that tracks changes in continents ordered by name
    func continentsOrderedByNamePublisher() -> AnyPublisher<[ContinentInfo], Error> {
        ValueObservation
            .tracking(ContinentInfo.addRequest(request: ContinentInfo.orderRequestByName()).fetchAll)
            .publisher(in: dbWriter)
            .eraseToAnyPublisher()
    }

    func continentsOrderedByIdPublisher() -> AnyPublisher<[ContinentInfo], Error> {
        ValueObservation
            .tracking(ContinentInfo.addRequest(request: ContinentInfo.orderRequestById()).fetchAll)
            .publisher(in: dbWriter)
            .eraseToAnyPublisher()
    }
}
```

**Comment by groue** [comment]
> Most of the code, is derivable from the documentation

Well, except when it does not 😅 

> I have `ContinentInfo` conforming to the `TableRecord` protocol.

Do refactor your code so that you do not. Remove `EncodableRecord` conformance as well.

It is not correct to have `ContinentInfo` conform to protocols that do not match any feature needed by this type:

- `TableRecord`? But `ContinentInfo` does not handle any **table** (`Continents` and `Countries` do, but the `continentInfo` table does not exist).
- `EncodableRecord`? But `ContinentInfo` does not **encode** anything (instead, it is decoded from database results).

Some confusion has to be cleared up.

`TableRecord` is a protocol that generates SQL for a table. In your case, the only record types that manage tables and can generate SQL are `Continents` and `Countries`.

You build requests from `Continents` and `Countries`, and their associations. `ContinentInfo` is only involved in *decoding* those requests.

```swift
let request = Continents
    .including(all: Continents.countries.order(Column("name")))
    .asRequest(of: ContinentInfo.self)

let infos = try dbWriter.read { db in try request.fetchAll(db) }
let observation = ValueObservation.tracking { db in try request.fetchAll(db) }
```

Apply my advice, reread the doc if necessary, and above all, don't give up!

**Comment by Chpetrou** [comment]
Hello @groue,

Thanks for the response, and the advice!

It seems that I had not understood well the way these work and what is happening behind all of the framework code. Once i read your advices, a lot of the things that were confusing to me, now made a lot of sense. It was actually very easy. Most of the issues had to do with the protocols, which before i did not understood what conforming to each of those meant. Once they were clear to me, i fixed it in 2 minutes.

Again, thank you for the helpful and explainable advices 🙂

**Comment by groue** [comment]
Great! Happy GRDB on stronger basis, @Chpetrou 😉👍
