### ISSUE TITLE
GRDBCipher build fails

### ISSUE THREAD

**Issue by opencookie** [groue/GRDB.swift#88]
Hi.

I'm using Xcode 7.3 with ios 8.2 target.
![2016-07-25 4 45 03](https://cloud.githubusercontent.com/assets/4231656/17094460/62514222-528a-11e6-9440-00e19008000d.png)
It fails with following lines. 

> ld: warning: ignoring file /Users/kd/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqxdxwpuuzjmxifzfujrvgfpynud/Build/Products/Debug-iphoneos/libsqlcipher.a, file was built for archive which is not the architecture being linked (armv7): /Users/kd/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqxdxwpuuzjmxifzfujrvgfpynud/Build/Products/Debug-iphoneos/libsqlcipher.a
  "_sqlite3_value_type", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_value_int64", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
...
...

**Comment by groue** [comment]
See https://github.com/groue/GRDB.swift/issues/77

**Comment by opencookie** [comment]
I followed #77 
![2016-07-26 10 54 09](https://cloud.githubusercontent.com/assets/4231656/17123619/c5dd9238-531f-11e6-957c-0dfa926f39ac.png)
![2016-07-26 10 54 37](https://cloud.githubusercontent.com/assets/4231656/17123624/d169b5e6-531f-11e6-8193-1b4d035678cb.png)
![2016-07-26 10 54 54](https://cloud.githubusercontent.com/assets/4231656/17123629/d722511e-531f-11e6-9834-4934955fb737.png)

and submodules are downloaded.
But, error is same.

**Comment by groue** [comment]
You shouldn't have both GRDBiOS and GRDBCiipheriOS in your target  dependencies. Also, try cleaning your build folder. And make sure you build for iOS.

**Comment by opencookie** [comment]
I removed GRDBiOS in target dependencies.
clean and build is fail.
It works well with GRDB but not GRDBCipher.

**Comment by groue** [comment]
@opencookie 

I could successfully integrate GRDBCipher in an app using the [manual installation procedure](https://github.com/groue/GRDB.swift#manually). You can as well.

Make sure that you add the GRDBCipheriOS target in your target dependencies. Make sure that you add the GRDBCipher.framework (the one for iOS, not OSX) in your embedded binaries.

If necessary, restart the whole procedure from the start.

And it will work just fine.

**Comment by opencookie** [comment]
I removed GRDBiOS in target dependencies.
Reclone, Clean and Build for iOS.
It's same.

**Comment by groue** [comment]
All right, @opencookie. You have to provide much more information now, anything that can reveal useful.

For example, give a complete and detailed scenario of what you are doing, from the start until the full error message. Until I can reproduce your issue, I won't be able to help.

**Comment by opencookie** [comment]
Basically, I followed https://github.com/groue/GRDB.swift#manually.
My setting is here.
![2016-08-02 10 59 52](https://cloud.githubusercontent.com/assets/4231656/17314566/55b3396e-58a0-11e6-9e5e-cb199362832e.png)
![2016-07-26 10 54 37](https://cloud.githubusercontent.com/assets/4231656/17314574/62cf7270-58a0-11e6-8a23-bffce5e8868a.png)
![2016-07-26 10 54 54](https://cloud.githubusercontent.com/assets/4231656/17314581/67ac39ae-58a0-11e6-8870-12635463925a.png)



Full error message is here:
ld: warning: ignoring file /Users/kd/Library/Developer/Xcode/DerivedData/Unity-iPhone-atusazlpwrfjnzeknwnkordtjqux/Build/Products/Debug-iphoneos/libsqlcipher.a, file was built for archive which is not the architecture being linked (armv7): /Users/kd/Library/Developer/Xcode/DerivedData/Unity-iPhone-atusazlpwrfjnzeknwnkordtjqux/Build/Products/Debug-iphoneos/libsqlcipher.a
Undefined symbols for architecture armv7:
  "_sqlite3_value_type", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_value_int64", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_value_double", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_value_text", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_column_double", referenced from:
      (extension in GRDBCipher):Swift.Double.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Double in StandardLibrary.o
      (extension in GRDBCipher):Swift.Float.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Float in StandardLibrary.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_column_text", referenced from:
      (extension in GRDBCipher):Swift.String.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.String in StandardLibrary.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_column_int64", referenced from:
      (extension in GRDBCipher):Swift.Bool.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Bool in StandardLibrary.o
      (extension in GRDBCipher):Swift.Int.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Int in StandardLibrary.o
      (extension in GRDBCipher):Swift.Int32.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Int32 in StandardLibrary.o
      (extension in GRDBCipher):Swift.Int64.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> Swift.Int64 in StandardLibrary.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_backup_init", referenced from:
      (extension in GRDBCipher):GRDBCipher.DatabaseReader.(backup (to : GRDBCipher.DatabaseWriter, afterBackupInit : () -> ()?, afterBackupStep : () -> ()?) throws -> ()).(closure #1).(closure #1) in DatabaseReader.o
  "_sqlite3_backup_step", referenced from:
      (extension in GRDBCipher):GRDBCipher.DatabaseReader.(backup (to : GRDBCipher.DatabaseWriter, afterBackupInit : () -> ()?, afterBackupStep : () -> ()?) throws -> ()).(closure #1).(closure #1) in DatabaseReader.o
  "_sqlite3_backup_finish", referenced from:
      (extension in GRDBCipher):GRDBCipher.DatabaseReader.(backup (to : GRDBCipher.DatabaseWriter, afterBackupInit : () -> ()?, afterBackupStep : () -> ()?) throws -> ()).(closure #1).(closure #1) in DatabaseReader.o
  "_sqlite3_column_blob", referenced from:
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).dataNoCopy (atIndex : Swift.Int) -> __ObjC.NSData? in Row.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_changes", referenced from:
      GRDBCipher.Database.changesCount.getter : Swift.Int in Database.o
  "_sqlite3_column_count", referenced from:
      GRDBCipher.SelectStatement.(columnCount.getter : Swift.Int).(closure #1) in Statement.o
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).init (sqliteStatement : Swift.COpaquePointer, statementRef : Swift.Unmanaged<GRDBCipher.SelectStatement>) -> GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6) in Row.o
      GRDBCipher.(StatementCopyRowImpl in _6B2D55C58B5A010700200D9607F91DE6).init (sqliteStatement : Swift.COpaquePointer, columnNames : [Swift.String]) -> GRDBCipher.(StatementCopyRowImpl in _6B2D55C58B5A010700200D9607F91DE6) in Row.o
      GRDBCipher.Row.count.getter : Swift.Int in Row.o
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).count.getter : Swift.Int in Row.o
  "_sqlite3_bind_parameter_name", referenced from:
      GRDBCipher.Statement.((sqliteArgumentNames in _6117F0CFC3A9F433E9B9B886F21276E4).getter : [Swift.String?]).(closure #1).(closure #1) in Statement.o
  "_sqlite3_open_v2", referenced from:
      GRDBCipher.Database.init (path : Swift.String, configuration : GRDBCipher.Configuration, schemaCache : GRDBCipher.DatabaseSchemaCacheType) throws -> GRDBCipher.Database in Database.o
  "_sqlite3_bind_parameter_count", referenced from:
      GRDBCipher.Statement.(sqliteArgumentCount.getter : Swift.Int).(closure #1) in Statement.o
  "_sqlite3_rollback_hook", referenced from:
      GRDBCipher.Database.(installTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
      GRDBCipher.Database.(uninstallTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
  "_sqlite3_wal_checkpoint_v2", referenced from:
      GRDBCipher.DatabasePool.(checkpoint (GRDBCipher.CheckpointMode) throws -> ()).(closure #1) in DatabasePool.o
  "_sqlite3_step", referenced from:
      GRDBCipher.UpdateStatement.execute (arguments : GRDBCipher.StatementArguments?) throws -> () in Statement.o
      GRDBCipher.DatabaseSequence.(init (statement : GRDBCipher.SelectStatement, element : () -> A) -> GRDBCipher.DatabaseSequence<A>).(closure #1).(closure #1) in Statement.o
  "_sqlite3_result_blob", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_clear_bindings", referenced from:
      GRDBCipher.Statement.(clearBindings in _6117F0CFC3A9F433E9B9B886F21276E4) () throws -> () in Statement.o
  "_sqlite3_column_bytes", referenced from:
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).dataNoCopy (atIndex : Swift.Int) -> __ObjC.NSData? in Row.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_bind_null", referenced from:
      GRDBCipher.Statement.(bindDatabaseValue in _6117F0CFC3A9F433E9B9B886F21276E4) (GRDBCipher.DatabaseValue, atIndex : Swift.Int) throws -> () in Statement.o
  "_sqlite3_bind_double", referenced from:
      GRDBCipher.Statement.(bindDatabaseValue in _6117F0CFC3A9F433E9B9B886F21276E4) (GRDBCipher.DatabaseValue, atIndex : Swift.Int) throws -> () in Statement.o
  "_sqlite3_result_null", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_result_double", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_exec", referenced from:
      GRDBCipher.Database.init (path : Swift.String, configuration : GRDBCipher.Configuration, schemaCache : GRDBCipher.DatabaseSchemaCacheType) throws -> GRDBCipher.Database in Database.o
  "_sqlite3_finalize", referenced from:
      GRDBCipher.Statement.deinit in Statement.o
  "_sqlite3_result_text", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_last_insert_rowid", referenced from:
      GRDBCipher.Database.lastInsertedRowID.getter : Swift.Int64 in Database.o
  "_sqlite3_result_error", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_prepare_v2", referenced from:
      GRDBCipher.Database.(execute (Swift.String, arguments : GRDBCipher.StatementArguments?) throws -> ()).(closure #3) in Database.o
      GRDBCipher.Statement.(init (database : GRDBCipher.Database, sql : Swift.String, observer : GRDBCipher.StatementCompilationObserver) throws -> GRDBCipher.Statement).(closure #1) in Statement.o
  "_sqlite3_errcode", referenced from:
      GRDBCipher.Database.lastErrorCode.getter : Swift.Int32 in Database.o
  "_sqlite3_user_data", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_set_authorizer", referenced from:
      GRDBCipher.StatementCompilationObserver.start () -> () in Database.o
      GRDBCipher.StatementCompilationObserver.stop () -> () in Database.o
  "_sqlite3_busy_handler", referenced from:
      GRDBCipher.Database.(setupBusyMode in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
  "_sqlite3_bind_text", referenced from:
      GRDBCipher.Statement.(bindDatabaseValue in _6117F0CFC3A9F433E9B9B886F21276E4) (GRDBCipher.DatabaseValue, atIndex : Swift.Int) throws -> () in Statement.o
  "_sqlite3_create_collation_v2", referenced from:
      GRDBCipher.Database.addCollation (GRDBCipher.DatabaseCollation) -> () in Database.o
      GRDBCipher.Database.removeCollation (GRDBCipher.DatabaseCollation) -> () in Database.o
  "_sqlite3_busy_timeout", referenced from:
      GRDBCipher.Database.(setupBusyMode in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
  "_sqlite3_close_v2", referenced from:
      GRDBCipher.(closeConnection in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.COpaquePointer) -> () in Database.o
  "_sqlite3_trace", referenced from:
      GRDBCipher.Database.(setupTrace in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
  "_sqlite3_db_release_memory", referenced from:
      GRDBCipher.Database.releaseMemory () -> () in Database.o
  "_sqlite3_close", referenced from:
      GRDBCipher.(closeConnection in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.COpaquePointer) -> () in Database.o
  "_sqlite3_key", referenced from:
      static GRDBCipher.Database.(setPassphrase in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.String, forConnection : Swift.COpaquePointer) throws -> () in Database.o
  "_sqlite3_rekey", referenced from:
      GRDBCipher.Database.changePassphrase (Swift.String) throws -> () in Database.o
  "_sqlite3_sql", referenced from:
      GRDBCipher.(closeConnection in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.COpaquePointer) -> () in Database.o
      GRDBCipher.Statement.sql.getter : Swift.String in Statement.o
  "_sqlite3_result_int64", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_next_stmt", referenced from:
      GRDBCipher.(closeConnection in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.COpaquePointer) -> () in Database.o
  "_sqlite3_column_name", referenced from:
      GRDBCipher.SelectStatement.(columnNames.getter : [Swift.String]).(closure #1).(closure #1) in Statement.o
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).(init (sqliteStatement : Swift.COpaquePointer, statementRef : Swift.Unmanaged<GRDBCipher.SelectStatement>) -> GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6)).(closure #1) in Row.o
  "_sqlite3_value_bytes", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_stricmp", referenced from:
      static GRDBCipher.== infix (GRDBCipher.DatabaseCollation, GRDBCipher.DatabaseCollation) -> Swift.Bool in Database.o
  "_sqlite3_create_function_v2", referenced from:
      GRDBCipher.Database.addFunction (GRDBCipher.DatabaseFunction) -> () in Database.o
      GRDBCipher.Database.removeFunction (GRDBCipher.DatabaseFunction) -> () in Database.o
  "_sqlite3_reset", referenced from:
      GRDBCipher.Statement.reset () throws -> () in Statement.o
  "_sqlite3_result_error_code", referenced from:
      GRDBCipher.Database.(addFunction (GRDBCipher.DatabaseFunction) -> ()).(closure #1) in Database.o
  "_sqlite3_errmsg", referenced from:
      GRDBCipher.Database.lastErrorMessage.getter : Swift.String? in Database.o
      GRDBCipher.Database.init (path : Swift.String, configuration : GRDBCipher.Configuration, schemaCache : GRDBCipher.DatabaseSchemaCacheType) throws -> GRDBCipher.Database in Database.o
      static GRDBCipher.Database.(setPassphrase in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.String, forConnection : Swift.COpaquePointer) throws -> () in Database.o
      GRDBCipher.(closeConnection in _4FD3C4B7F7EF8BF3459D4D5C0752607F) (Swift.COpaquePointer) -> () in Database.o
      GRDBCipher.Database.changePassphrase (Swift.String) throws -> () in Database.o
  "_sqlite3_bind_int64", referenced from:
      GRDBCipher.Statement.(bindDatabaseValue in _6117F0CFC3A9F433E9B9B886F21276E4) (GRDBCipher.DatabaseValue, atIndex : Swift.Int) throws -> () in Statement.o
  "_sqlite3_column_type", referenced from:
      GRDBCipher.Row.(fastValue in _6B2D55C58B5A010700200D9607F91DE6) <A where A: GRDBCipher.DatabaseValueConvertible, A: GRDBCipher.StatementColumnConvertible> (atUncheckedIndex : Swift.Int) -> A? in Row.o
      GRDBCipher.Row.(fastValue in _6B2D55C58B5A010700200D9607F91DE6) <A where A: GRDBCipher.DatabaseValueConvertible, A: GRDBCipher.StatementColumnConvertible> (atUncheckedIndex : Swift.Int) -> A in Row.o
      GRDBCipher.(StatementRowImpl in _6B2D55C58B5A010700200D9607F91DE6).dataNoCopy (atIndex : Swift.Int) -> __ObjC.NSData? in Row.o
      static (extension in GRDBCipher):GRDBCipher.DatabaseValueConvertible<A where A: GRDBCipher.DatabaseValueConvertible, A: GRDBCipher.StatementColumnConvertible>.(fetch (GRDBCipher.SelectStatement, arguments : GRDBCipher.StatementArguments?, adapter : GRDBCipher.RowAdapter?) -> GRDBCipher.DatabaseSequence<A>).(closure #2) in StatementColumnConvertible.o
      static (extension in GRDBCipher):GRDBCipher.DatabaseValueConvertible<A where A: GRDBCipher.DatabaseValueConvertible, A: GRDBCipher.StatementColumnConvertible>.(fetchOne (GRDBCipher.SelectStatement, arguments : GRDBCipher.StatementArguments?, adapter : GRDBCipher.RowAdapter?) -> A?).(closure #2) in StatementColumnConvertible.o
      GRDBCipher.DatabaseValue.init (sqliteStatement : Swift.COpaquePointer, index : Swift.Int32) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_update_hook", referenced from:
      GRDBCipher.Database.(installTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
      GRDBCipher.Database.(uninstallTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
  "_sqlite3_bind_blob", referenced from:
      GRDBCipher.Statement.(bindDatabaseValue in _6117F0CFC3A9F433E9B9B886F21276E4) (GRDBCipher.DatabaseValue, atIndex : Swift.Int) throws -> () in Statement.o
  "_sqlite3_total_changes", referenced from:
      GRDBCipher.Database.totalChangesCount.getter : Swift.Int in Database.o
  "_sqlite3_value_blob", referenced from:
      GRDBCipher.DatabaseValue.init (sqliteValue : Swift.COpaquePointer) -> GRDBCipher.DatabaseValue in DatabaseValue.o
  "_sqlite3_commit_hook", referenced from:
      GRDBCipher.Database.(installTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
      GRDBCipher.Database.(uninstallTransactionObserverHooks in _4FD3C4B7F7EF8BF3459D4D5C0752607F) () -> () in Database.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)



I doubt about "libsqlcipher.a, file was built for archive which is not the architecture being linked (armv7)".
Is it normal?

**Comment by groue** [comment]
>> For example, give a complete and detailed scenario of what you are doing, from the start until the full error message. Until I can reproduce your issue, I won't be able to help.
>
> Basically, I followed https://github.com/groue/GRDB.swift#manually.

Basically, I did succeed building an archiving an iOS application that uses GRDBCipher.

I'm not sure how to help you with this, you'll have to debug it on your own.
