### ISSUE TITLE
Don’t compile for armv7?

### ISSUE THREAD

**Issue by osteslag** [groue/GRDB.swift#884]
Hi @groue,

When compiling GRDB from package in Release configuration for iOS, GRDB.o takes up 12.5 MB which is a hefty footprint, I think. It turns out that the file contains `armv7` code (also with `ENABLE_BITCODE` turned off). But the final app executable contains only `arm64`, so the other slice must be thrown away in the end. 

Do you know how to disable `armv7` code generation? If nothing else, then for saving time not compiling the unused slice.

Thanks,
Joachim

**Comment by groue** [comment]
Hello @osteslag, your question is more about SPM or Xcode than about GRDB. I don't have a straight answer, unfortunately.

You may be more lucky on http://forums.swift.org (SPM focus), https://developer.apple.com/forums/ (Xcode focus), or http://stackoverflow.com. Don't hesitate bringing back your findings here, when you get an answer!

**Comment by osteslag** [comment]
I know. I knew already when posting, just hoped you had an answer :-) I’ll comment with a solution, if I find one. Feel free to close, if you want.

**Comment by groue** [comment]
Thank you for your patience and contribution :-) We can keep the issue open for a few days! Maybe somebody will have a ready-made answer to share.

**Comment by groue** [comment]
I usually keep inactive issues open for a week. Did you find out how to have SPM disable armv7 code generation?

**Comment by groue** [comment]
All right, @osteslag. Let's close this issue, and let the Internet eventually find a way to control how SPM builds packages.
