### ISSUE TITLE
SelectStatement.sql doesn't include chained associations sometimes

### ISSUE THREAD

**Issue by bellebethcooper** [groue/GRDB.swift#888]
### What did you do?

I created a request involving chained associations, then printed the raw SQL (before fetching the request) like this:

```swift
let names = ["Jean Genet"]

let request = Book
    .annotated(with: max(Column("created")))
    .group(Column("authorId"))
    .including(required: Book.author
            .filter(names.contains(Column("name")))
            .including(all: Author.bookTags.filter(Column("name") == "literature")))

let statement = try request.makePreparedRequest(db, forSingleResult: false).statement
print(statement.sql)
```

### What did you expect to happen?

I expected the printed string to include all my joins, but I may be using the wrong debugging approach. I couldn't find any recommendations in the docs or other issues that suggested a different way of printing out the SQL generated by GRDB.

### What happened instead?

With a complicated request, my chained associations were not included in the printed SQL string. Here's the result of the print statement above, which is missing any reference to `BookTag`:

`SELECT "book".*, MAX("book"."created"), "author".* FROM "book" JOIN "author" ON ("author"."id" = "book"."authorId") AND ("author"."name" = ?) GROUP BY "book"."authorId"`

I noticed that using `db.trace` does show SQL that includes `SELECT` queries on the `BookTag` table in this example, so I was wondering if this is a case where using `SelectStatement.sql` for debugging is inappropriate? Or is it not the way to debug a query in any situation? And if so, is there another approach besides `.trace`, which generates a lot of output compares to using the `SelectStatement` approach? Thanks!

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.2.0
**Installation method:** SPM
**Xcode version:** 12.2
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.0.1

### Demo Project

This is an edited version of the Associations.playground file from the GRDB.swift repo. I edited it to replicate the issue I was noticing. If you can run it, you should see the difference between the print statement from `statement.sql` and the print statements from `db.trace`.

[Associations_test.playground.zip](https://github.com/groue/GRDB.swift/files/5670949/Associations_test.playground.zip)

**Comment by bellebethcooper** [comment]
Just wanted to add that I found this as I was working on what I mentioned in #887 so the model setup is the same as I mentioned there. It's also included in the playground file, but I can add more details about how the models are related to each other if that's useful.

**Comment by groue** [comment]
Hello @bellebethcooper,

> I expected the printed string to include all my joins, but I may be using the wrong debugging approach. I couldn't find any recommendations in the docs or other issues that suggested a different way of printing out the SQL generated by GRDB.
>
> ```swift
> let statement = try request.makePreparedRequest(db, forSingleResult: false).statement
> print(statement.sql)
> ```

I'll answer to this question, and leave the rest to #887.

I guess you got the `makePreparedRequest` technique from this [FAQ](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-print-a-request-as-sql). I'll need to make it a little more clear, by summing up the raw explanations I write below:

Not all requests perform a single SQL query:

```swift
// 1. SELECT * FROM author
Author.fetchAll(db)

// 1. SELECT * FROM author
// 2. SELECT * FROM bookTag WHERE authorID IN (...)
Author.including(all: Author.bookTags).fetchAll(db)
```

Indeed, all `including(all:)` invocations trigger the execution of an extra SQL request. This is how GRDB handles the [N + 1 Problem](https://stackoverflow.com/questions/97197), as many other ORMs out there.

The `makePreparedRequest` method returns an object that exposes a single `SelectStatement`, which represents a single SQL query, the one that fetches the "base" of the request: the base records, the `including/joining(optional/required:)` associations, but not the `including(all:)` associations that need extra SQL queries.

This explains why you don't see the SQL query for bookTags with your sample code.

There is no public API that exposes all SQL queries that would be run by a request.

The only available technique, currently, is to trace database execution. You can do it globally as in the [FAQ](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-print-a-request-as-sql). You can also trace temporarily:

```swift
db.trace { print($0) }
defer { db.trace(options: []) } // stops tracing
try request.fetchAll(db)
```

(See [`Database.trace(_:_:)`](http://groue.github.io/GRDB.swift/docs/5.2/Classes/Database.html#/s:4GRDB8DatabaseC5trace7options_yAC14TracingOptionsV_yAC10TraceEventOcSgtF), [`TracingOptions`](http://groue.github.io/GRDB.swift/docs/5.2/Classes/Database/TracingOptions.html), and [`TraceEvent`](http://groue.github.io/GRDB.swift/docs/5.2/Classes/Database/TraceEvent.html) for more tracing options.)

Note that if the base request fetches an empty set, all `including(all:)` associations are not executed, so you won't see any extra SQL query.

**Comment by bellebethcooper** [comment]
Thanks @groue, this answers my question perfectly!
