### ISSUE TITLE
"attempt to write a readonly database" Oddity

### ISSUE THREAD

**Issue by akbsteam** [groue/GRDB.swift#89]
I am using DatabasePool to connect to my sqlite DB which works fine for reading but can't write - with "attempt to write a readonly database" error.

querying the pool object for the path I get something of the form:-
`/var/mobile/Containers/Data/Application/....../Documents/downloadedPOIs.sqlite3`

and I start the pool using 

```
var config = Configuration()
config.readonly = false
dbPool = try DatabasePool(path: path, configuration: config)
```

Any thoughts on what the issue might be?

**Comment by groue** [comment]
Hello @akbsteam.

Could you please share the code that gives this error? I expect something like:

```swift
try dbPool.write { db in
    try <some statement that throws the error>
}
```

**Comment by groue** [comment]
(pretty intense profile picture, btw)

**Comment by akbsteam** [comment]
Thanks for your super quick response! 

```
do {
    try dbPool.writeInTransaction { db -> TransactionCompletion in
        for entry in entries {
            self.updateRelevancyScore(db, entry: entry)
        }
        return .Commit
    }
} catch let error as DatabaseError {
    print(error.description)
} catch let error as NSError {
    print(error.description)
}
```

with the inner function call being

```
func updateRelevancyScore(db: Database, entry: ParsedRelevancy)
    {
        do {
            try db.execute(
                "UPDATE posts SET insightrelevancy = ?, insightdelta = ? WHERE guid = ?",
                arguments: [entry.insightrelevancy, entry.insightrelevancy, entry.guid])
            
        } catch let error as DatabaseError {
            print(error.description)
            
        } catch let error as NSError {
            print(error.description)
        }
    }
```

I'm beginning to narrow it down though to possibly being something to do with opening the pool connection, then later overwriting the database; it should open a new connection pool and use that with the updated db, but maybe its not quite working right?

(profile pic is a tin-type; wet plate collodion process from the 1800s; my wife does them:
http://wildaesthetic.co.uk)

**Comment by groue** [comment]
> I'm beginning to narrow it down though to possibly being something to do with opening the pool connection, then later overwriting the database.

I did not expect that :-) Let me list what I understand. Please fix my assumptions if they are false:

You first open a pool to, say, /path/to/database.

The /path/to/database is a valid writable path (not a readonly file or an application resource).

Later, as the pool is still alive, you "hot swap" /path/to/database with another database file.

If that true? If so, I suspect that SQLite does not support that, and this is the source of the error. GRDB does not support that as well, as it caches some database information, and a hot swap could make this cache irrelevant.

> it should open a new connection pool and use that with the updated db.

Yes, I think this is your best option. The "old" pool will close as soon as it is deallocated (precisely speaking, after all statements have completed - watch out eventual unfinished background tasks). After the old pool has closed, you can overwrite the database, and then open a new pool.

When overwriting the database, make sure to replace *all* database files (don't forget the -shm and -wal files, and actually [all files](https://www.sqlite.org/tempfiles.html) with extra -xxx suffix). The simpler way to be sure is to overwrite a *directory*, not individual files.

**Comment by akbsteam** [comment]
thanks for your help, will see how I go!

**Comment by groue** [comment]
No news, good news: I assume you were able to fix your issue. Happy GRDB!

**Comment by akbsteam** [comment]
all good, thanks
