### ISSUE TITLE
How can i join three tables with GRDB?

### ISSUE THREAD

**Issue by Chpetrou** [groue/GRDB.swift#891]
### Required Information

Hello,

I have three tables like this:

(Table 1) belongsTo -> (Table 2) belongsTo -> (Table 3)
(Table 1) <- hasMany (Table 2) <- hasMany (Table 3)

(Table 1) to (Table 2) is notNull
(Table 2) to (Table 3) could be Null

The query i would like to execute is:
`SELECT * from Table1 INNER JOIN Table2 ON Table1.table2Id == Table2.id INNER JOIN Table3 ON Table2.table3Id == Table3.id;`

### Question

How could i do this in GRDB and have the results in a struct like this?

```
struct Table1Info: FetchableRecord, Decodable {
    var table1: Table1

    var table2: Table2
    var table3: Table3?
}
```

**Comment by groue** [comment]
Hello @Chpetrou,

This topic is documented in the [Combining Associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#combining-associations) chapter of the association guide.

It should give, given a proper setup of record types and their associations:

```swift
// SELECT table1.*, table2.*, table3.*
// FROM table1
// JOIN table2 ON table1.table2Id == table2.id
// LEFT JOIN table3 ON table2.table3Id == table3.id
let infos = try Table1
    .including(required: Table1.table2
        .including(optional: Table2.table3))
    // How to decode
    .asRequest(of: Table1Info.self)
    // Fetch
    .fetchAll(db)
```

**Comment by Chpetrou** [comment]
Hello @groue,

I was searching for that as i remember seeing it somewhere before, but I must have missed it.

Thanks for the answer!
