### ISSUE TITLE
'SQLCipher/sqlite3.h' file not found

### ISSUE THREAD

**Issue by wuyuehyang** [groue/GRDB.swift#894]
### What did you do?

Create a new iOS project, install GRDB/SQLCipher with Cocoapods

### What did you expect to happen?

Compile

### What happened instead?

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/GRDB.swift-umbrella.h"
        ^
/Users/wu/Develop/Demo/GRDBDemo/Pods/Target Support Files/GRDB.swift/GRDB.swift-umbrella.h:13:9: note: in file included from /Users/wu/Develop/Demo/GRDBDemo/Pods/Target Support Files/GRDB.swift/GRDB.swift-umbrella.h:13:
#import "SQLCipher_config.h"
        ^
/Users/wu/Develop/Demo/GRDBDemo/Pods/GRDB.swift/Support/SQLCipher_config.h:4:10: error: 'SQLCipher/sqlite3.h' file not found
#include <SQLCipher/sqlite3.h>
         ^
<unknown>:0: error: could not build Objective-C module 'GRDB'
```

#### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

#### Installation Source

```
Executable Path: /usr/local/bin/pod
```

#### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

#### Podfile

```ruby
install! 'cocoapods',
:generate_multiple_pod_projects => true

platform :ios, '12.0'

target 'GRDBDemo' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher', '~> 4.0'
end
```

### Demo Project

[GRDBDemo.zip](https://github.com/groue/GRDB.swift/files/5718996/GRDBDemo.zip)

**Comment by groue** [comment]
Hello @wuyuehyang,

I indeed see the `'SQLCipher/sqlite3.h' file not found` error with your demo project.

However, if I create a new project, add a Podfile identical to yours, run `pod install`, and open the generated Xcode workspace, I can build it without any error and create an encrypted database. There's no issue with GRDB and its documentation for SQLCipher integration, as far as I know.

I will not attempt at finding what's wrong in your demo project. I suggest you restart from scratch and move on to your next interesting task.

**Comment by wuyuehyang** [comment]
Hello @groue , thanks for your help
May I have your demo project? I would like to compare it with mine, maybe I can figure out the reason.

**Comment by groue** [comment]
Sure. I deleted the Pods folder. I hope it won't alter your investigation.


[Issue894.zip](https://github.com/groue/GRDB.swift/files/5719822/Issue894.zip)

**Comment by wuyuehyang** [comment]
For anyone encountered same issue:
This may happen due to a corrupted Cocoapods cache. Goto ~/Library/Caches/CocoaPods/Pods/Release/ and delete the folder named SQLCipher, remove Pods from your project folder, and run pod install again.
