### ISSUE TITLE
How to use GRDB to realize inheritance

### ISSUE THREAD

**Issue by Xfcmy** [groue/GRDB.swift#895]
Our project plans to refactor the database, our old implementation is using CoreData.

We think GRDB is a good choice, so now I'm developing a demo to explore how to use GRDB to realize the function of CoreData.

But I can't find the document about inheritance.

Here is my code

* for CoreData

```Swift
class ParentCoreDataModel: NSManagedObject {
    @NSManaged var id: Int64
    @NSManaged var label: String
    @NSManaged var isNew: Bool
}
```

* for GRDB

```Swift
/// Model
struct ParentGRDBModel: Codable, FetchableRecord, MutablePersistableRecord {
    var id: Int64
    var label: String
    var isNew: Bool
}

/// Migration
var migrator = DatabaseMigrator()
m.registerMigration("createTable") { (db) in
    try db.create(table: ParentGRDBModel.databaseTableName) { (t) in
        t.autoIncrementedPrimaryKey("id")
        t.column("label", .text).notNull()
        t.column("isNew", .boolean).notNull()
    }
}
try migrator.migrate(dbQueue)
```

That works fine.

And to realize inheritance in CoreData

```Swift
class ChildCoreDataModel: ParentCoreDataModel {
    @NSManaged var count: Int
}
```

* In CoreData, I can easily register `ChildCoreDataModel` and `ParentCoreDataModel` in the `.xcdatamodeld` file. Then `ChildCoreDataModel` and `ParentCoreDataModel` will be in the same table.I can fetch a `ParentCoreDataModel` and transform it into `ChildCoreDataModel` if it is. 

* So my questions are: 
    * How to realize `ChildGRDBModel`(as `ChildCoreDataModel` for `ParentCoreDataModel`) using GRDB? 
    * How to realize the migartion of `ChildGRDBModel`? 
    * Will it change the migration of `ParentGRDBModel`?

**Comment by groue** [comment]
Hello @Xfcmy,

Thanks for asking! I'm sure other issues talk about this as well.

The topic of record inheritance has not been explored in GRDB. You're entering an uncharted territory, and I suggest you keep on exploring.

My advice is to consider GRDB for what it is: a thin convenience layer above SQLite. An SQLite schema is not a Core Data model. It is reasonable to expect some coding practices to change.

I always suggest *starting from the database schema first*. Your goal is to make it as robust as possible, which means:

- Have it as unable as possible to express invalid data states.
- While making sure application needs are possible and reasonably handy and efficient (reads and writes).

Possible options are:

- Define one table for both types, with a discriminant column:
    
    ```swift
    // Contains parents and children
    try db.create(table: "parent") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("kind", .text).notNull().indexed() // 'child' or 'parent'
        t.column("label", .text).notNull()
        t.column("isNew", .boolean).notNull()
        // Nullablity of the 'count' column depends on the kind
        t.column("count", .integer).check(sql: "kind <> 'child' OR count IS NOT NULL")
    }
    ```
    
- One table for parents, one table for children, with the children table having extra columns, and a reference to parents. For example:
    
    ```swift
    // Contains parents and children
    try db.create(table: "parent") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("label", .text).notNull()
        t.column("isNew", .boolean).notNull()
    }
    
    // Contains children-specific columns
    try db.create(table: "child") { t in
        t.column("parentID", .integer)
            .references("parent", onDelete: .cascade)
            .primaryKey()
        // Plain not null constraint is possible
        t.column("count", .integer).notNull()
    }
    ```
    
- Two distinct tables:
    
    ```swift
    // Contains only parents
    try db.create(table: "parent") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("label", .text).notNull()
        t.column("isNew", .boolean).notNull()
    }
    
    // Contains only children
    try db.create(table: "child") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("label", .text).notNull()
        t.column("isNew", .boolean).notNull()
        // Plain not null constraint is possible
        t.column("count", .integer).notNull()
    }
    ```

Once you have the schema that fits your application needs, you can start building record types.

Inheritance is an option. Composition as well. Composition may be easier to deal with, especially regarding `Codable` conformance ([thread](https://forums.swift.org/t/inheriting-from-a-codable-class/14874)).

**Comment by Xfcmy** [comment]
Thank you for your reply! 

The possible options you offered are very inspirational. All of them can meet some features of class inheritance.
I need to give them a try to see whether thay can meet our needs. I may finished this job till tomorrow. Then I can give you a further reply.

Again, apprciate for your support!

**Comment by Xfcmy** [comment]
I had considered the options you gave, I believed that the second one would be better. I just need to do some simple extension, then it can work.

Before talking about my idea for realize class inheritance in our project. Let me introduce the usage of database in our project so that you can have a better understanding of our needs.

Our app is a picture processing application. The basic functions are Edit, Filter, Sticker, Brush Pen and so on. So each function will have its own material, they are different, but they have some universal params(lots of). That's why we use class inheritance. Also, in order to make it easier for users to manage the material they download and use, we have a material center, so we need to use database.

* Define one table for both types, with a discriminant column
    * Our parent class will have lots of child classes. If we use only one class, it will be very complicated, so it can be costly to maintain and manage.

* One table for parents, one table for children, with the children table having extra columns, and a reference to parents(√) 
    * When I am going to save a child class to database, I need to save its parent class before.
    * When I want to fetch a child class from database, I fetch its parent class first, and assign the universal params from parent class to child class.
    * I can easity fetch all the parent classes and then check weather it has child class or not by each.

* Two distinct tables
    * This method is similar to the second one, I think it can work as well, but it will be more complicated and much trouble
    * The migration will be more complicated, if I want to add a column in parent table, I need to do the same thing to all child tables.
    * It will be lots of duplicate codes for encode and decode.

Here is my code:

```Swift
protocol MYDBProtocol {
    func saveToDB() -> Bool
    static func fetchFromDB(with id: Int64) -> Self?
}

class ParentModel: Codable, MYDBProtocol {
    let id: Int64
    var flag: Bool
    
    init(id: Int64) {
        self.id = id
        self.flag = false
    }
    
    // MARK: -
    
    enum ParentCodingKeys: String, CodingKey {
        case id
        case flag
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: ParentCodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(flag, forKey: .flag)
    }
    
    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: ParentCodingKeys.self)
        
        id = try container.decode(Int64.self, forKey: .id)
        flag = try container.decode(Bool.self, forKey: .flag)
    }
    
    // MARK: -
    
    class func fetchFromDB(with id: Int64) -> Self? {
        do {
            return try AppDataBase.dbQueue.read { (db) -> Self? in
                return try self.fetchOne(db, key: id)
            }
        } catch {
            return nil
        }
    }
    
    func saveToDB() -> Bool {
        do {
            return try AppDataBase.dbQueue.write({ (db) -> Bool in
                try self.save(db)
                return true
            })
        } catch {
            return false
        }
    }
}

extension ParentModel: FetchableRecord, PersistableRecord {
    
}

class ChildModel: ParentModel {
    var count: Int
    var label: String
    
    override init(id: Int64) {
        self.count = 0
        self.label = ""
        super.init(id: id)
    }
    
    // MARK: -
    
    enum ChildCodingKeys: String, CodingKey {
        case id
        case count
        case label
    }
    
    override func encode(to encoder: Encoder) throws {
        // if I'm transforming model to json, I should enable this and disable the id encode
//        try super.encode(to: encoder)
        
        var container = encoder.container(keyedBy: ChildCodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(count, forKey: .count)
        try container.encode(label, forKey: .label)
    }
    
    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: ChildCodingKeys.self)
        count = try container.decode(Int.self, forKey: .count)
        label = try container.decode(String.self, forKey: .label)
        let id = try container.decode(Int64.self, forKey: .id)
        super.init(id: id)
        
        // if I'm transforming json to model, I should enable and disable super.init(id:)
//        try super.init(from: decoder)
    }
    
    // MARK: -
    override func saveToDB() -> Bool {
        if parent.saveToDB() {
            do {
                return try AppDataBase.dbQueue.write({ (db) -> Bool in
                    try self.save(db)
                    return true
                })
            } catch {
                return false
            }
        } else {
            return false
        }
    }
    
    override class func fetchFromDB(with id: Int64) -> Self? {
        if let p = ParentModel.fetchFromDB(with: id) {
            do {
                return try AppDataBase.dbQueue.read { (db) -> Self? in
                    let res = try self.fetchOne(db, key: id)
                    // I can use Mirror to do the reflection
                    res?.flag = p.flag
                    return res
                }
            } catch {
                return nil
            }
        } else {
            return nil
        }
    }
}

extension ChildModel {
    private var parent: ParentModel {
        let p = ParentModel(id: id)
        // I can use Mirror to do the reflection
        p.flag = flag
        return p
    }
}
```

**Comment by groue** [comment]
I'm glad you found a solution, @Xfcmy.

I'm not surprised encoding and decoding requires boilerplate code: Swift does not provide any encoding facilities for class hierarchies. And I'm very reluctant to have GRDB build anything on top of `Mirror`.
