### ISSUE TITLE
How to use Full Text Search for fuzzy search?

### ISSUE THREAD

**Issue by dreammeng93** [groue/GRDB.swift#897]
I want to implement fuzzy search，but  I did not find relevant documents，Please tell me how to achieve it，thank you

### Demo Project

//插入数据
let data1 = FTSData(name: "小红", nick_name: "小乖", age: 26, gender: true)
//查询
let pattern = FTS5Pattern(matchingAllTokensIn:"小")
        return try! self.dbQueue.unsafeRead({ (db) -> [FTSData] in
            let finalArr = try FTSData.matching(pattern).order(Column("name")).fetchAll(db)
            return finalArr
        })

**Comment by groue** [comment]
Hello @dreammeng93 

FTS5 supports latin languages our of the box, but not Chinese.

My advice: grab information about Chinese full text search with SQLite and FTS5. If you have troubles applying the techniques you will learn with GRDB, open a detailed issue about the precise challenge you meet.

**Comment by dreammeng93** [comment]
However, now searching for English can only search for all matches? 

//insert
let data1 = FTSData(name: "xiaohong", nick_name: "xiaoguai", age: 26, gender: true)

//The search result is also empty
let pattern = FTS5Pattern(matchingAllTokensIn:"x*")

//This can be searched out
let pattern = FTS5Pattern(matchingAllTokensIn:"xiaohong")

**Comment by groue** [comment]
Please have a more precise look at https://github.com/groue/GRDB.swift/blob/master/Documentation/FullTextSearch.md#fts5pattern. Distinguish *raw patterns* such as `x*` from user-provided strings.

**Comment by dreammeng93** [comment]
I read this document carefully，But I did not find the syntax for fuzzy query，For example, I want to query the data of "Xiaohong" through "xiao", But no search results. The grammar in the document is all matching

**Comment by groue** [comment]
OK.

1. Study https://www.sqlite.org/fts5.html#full_text_query_syntax, and find what you need there
2. Use `makeFTS5Pattern(rawPattern:forTable:)` and enjoy the results

**Comment by dreammeng93** [comment]
So now GRDB does not support fuzzy search?
