### ISSUE TITLE
FTS 5 custom tokenizer

### ISSUE THREAD

**Issue by leonylcatwork** [groue/GRDB.swift#899]
### What did you do?

Try to add custom tokenzier with FTS 5. I followed the description in https://github.com/groue/GRDB.swift/blob/master/Documentation/FTS5Tokenizers.md.

### What did you expect to happen?

Should be able to create virtual table with custom tokenizer.

### What happened instead?

Suppose the name of custom tokenizer is "simple", ran
```
try db.create(virtualTable: "t1", using: FTS5()) { t in
    t.tokenizer = SimpleTokenizer.tokenizerDescriptor()
    t.column("x")
}
```

I got 
```
SQLite error 1: no such tokenizer: simple - while executing `CREATE VIRTUAL TABLE "t1" USING fts5(x, tokenize='simple')`
```

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** v5.2.0
**Installation method:** (CocoaPods, SPM, manual?)  CocoaPods
**Xcode version:** 12.3
**Swift version:** 5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)  macOS
**macOS version running Xcode:**  Big Sur 11.1

### Demo Project

Have not uploaded demo. But have following code snippets:

Due to code `xToken` was in c++, I created a bridge with Objective C++ and declaire the function signature as
```
FOUNDATION_EXPORT int simple_xTokenize(void * _Nullable pCtx,
                                       int flags,
                                       const char * _Nullable pText,
                                       int nText,
                                       int (*xTokenFn)(void * _Nullable, int, const char * _Nullable, int, int, int));
```

I then create a class conforming to FTS5CustomTokenizer and in func `tokenzie(...)` call above function `simple_xTokenize(...)`: 
```
final class SimpleTokenizer : FTS5CustomTokenizer {
    init(db: Database, arguments: [String]) throws {
    }
    
    func tokenize(context: UnsafeMutableRawPointer?, tokenization: FTS5Tokenization, pText: UnsafePointer<Int8>?, nText: Int32, tokenCallback: @escaping FTS5TokenCallback) -> Int32 {
        simple_xTokenize(context, tokenization.rawValue, pText, nText, tokenCallback)
    }
    
    static let name = "simple"
}
```

Not sure what to put in the initializer `init(db: Database, arguments: [String]) throws` though.
All built alright, but got above error when create virtual table:

```
SQLite error 1: no such tokenizer: simple - while executing `CREATE VIRTUAL TABLE "t1" USING fts5(x, tokenize='simple')`

```

I put breakpoint in `init(db: Database, arguments: [String]) throws` it does not come in. So I guess I am missing something for registering the tokenizer?

Cheers
Leon

**Comment by leonylcatwork** [comment]
Added a simple demo: https://github.com/leonylcatwork/FTS5TokenizerDemo

**Comment by leonylcatwork** [comment]
Problem solved. Missed

**Comment by groue** [comment]
Well done, @leonylcatwork!

> Due to code xToken was in c++, I created a bridge with Objective C++ [...] I then create a class conforming to `FTS5CustomTokenizer`.

Glad you made it work. Next time, you may rely entirely on the C++ code base, and avoid the Swift wrapper. I guess there exists a C++ api that registers the tokenizer given a raw SQLite connection. You can call it directly (or through the C bridge) from `prepareDatabase`:

```swift
config.prepareDatabase { db in
    setup(db.sqliteConnection)
}
```
