### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by lltu** [groue/GRDB.swift#9]
I use my iPhone 6 test the program:

dyld: Library not loaded: @rpath/GRDB.framework/GRDB
  Referenced from: /var/mobile/Containers/Bundle/Application/3E9FBA0D-0CCD-4F02-B29B-946AAE91CF4A/TSPTest.app/TSPTest
  Reason: image not found

**Comment by groue** [comment]
Yes, this happens from time to time. I usually run Product > Clean Build Folder (Shift-Command-K) and that problem goes away.

**Comment by groue** [comment]
Also, there are a couple of stackoverflow answers regarding this error message. Don't miss them since they may help tuning your project. I hope you will then share your solution here.

**Comment by groue** [comment]
Also, make sure you add the GRDB framework in the "Embedded Binaries" section of the "General" tab of your target.

**Comment by groue** [comment]
(Deleted previous comments that were inaccurate).

Thank you for spotting that the documentation is lacking.

Please tell me which integration method you chose: is it CocoaPods, Carthage, or Manual integration?

**Comment by groue** [comment]
@lltu Any update?

**Comment by groue** [comment]
No news, good news! Feel free to reopen an issue if you still have problems using GRDB.

**Comment by kybishop** [comment]
Hey @groue, I'm seeing this issue with a fresh install on a brand new project via CocoaPods.

```
dyld: Library not loaded: @rpath/GRDB.framework/Versions/A/GRDB
  Referenced from: /Users/kybishop/Library/Developer/Xcode/DerivedData/import-passwords-exlafwmxibluybhjocwpqhqibrzg/Build/Products/Debug/import-passwords
  Reason: image not found
(lldb) 
```

Steps to reproduce:
1. Create a new command line project with xcode 9.0.1
2. `pod init`
3. Add GRDB.swift to the Podfile
4. `pod install`
5. attempt to run the project without even importing GRDB
6. 💥

**Comment by kybishop** [comment]
Ah, it appears that one can't use Cocoa{ods on a CLI like I was hoping. For anyone else who arrives here, see [this SO post](https://stackoverflow.com/a/631005/471947) for explanation and potential workarounds.

**Comment by groue** [comment]
Hello @kybishop. Command line tools can not embed frameworks, this is the root of your issue.

Have a look at https://stackoverflow.com/questions/630911/using-frameworks-in-a-command-line-tool for more information.

You can also wait until CocoaPods can build static Swift libraries: https://github.com/CocoaPods/CocoaPods/issues/6899

**Comment by groue** [comment]
Crossed messages ;-)
