### ISSUE TITLE
Failed to create wrapped tokenizer with multiple arguments

### ISSUE THREAD

**Issue by wuyuehyang** [groue/GRDB.swift#900]
### What did you do?

Using FTS5 with custom tokenizer like this:

```Swift
class Tokenizer: FTS5WrapperTokenizer {
    
    static let name = "test"
    
    let wrappedTokenizer: FTS5Tokenizer
    
    required init(db: Database, arguments: [String]) throws {
        wrappedTokenizer = try db.makeTokenizer(.unicode61(diacritics: .removeLegacy, separators: ["-", "_"]))
    }
    
    func accept(token: String, flags: FTS5TokenFlags, for tokenization: FTS5Tokenization, tokenCallback: (String, FTS5TokenFlags) throws -> Void) throws {
        try tokenCallback(token, [])
    }
    
}
```

### What did you expect to happen?

Running without error

### What happened instead?

```
SQLite error 1: error in tokenizer constructor - while executing `CREATE VIRTUAL TABLE "foo_fts" USING fts5(a, tokenize='test')`
```

#### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

#### Podfile

```ruby
install! 'cocoapods',
:generate_multiple_pod_projects => true

platform :ios, '12.0'

target 'FTS5TokenizerDemo' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher', '~> 4.4.2'
end
```

### Researches

I tried to do some research by myself. The SQLITE_ERROR is thrown from `fts5UnicodeCreate`, which gets called when GRDB  initialize a unicode61 tokenizer. It checks if `nArg%2` in the beginning, to ensure the arguments are in pairs. When a tokenizer is created with `.unicode61(diacritics: .removeLegacy, separators: ["-", "_"])`, sqlite receives an nArg of 1, which prevents unicode61 tokenizer from creation.

Somehow I managed to make it work by modifying init of FTS5RegisteredTokenizer, to create the tokenizer like this:
```Swift
let cargs = ContiguousArray(arguments.map({ strdup($0) }))
code = cargs.withUnsafeBufferPointer { azArg in
    xCreate(
        contextPointer,
        UnsafeMutablePointer(OpaquePointer(azArg.baseAddress!)),
        Int32(cargs.count),
        &tokenizerPointer)
}
cargs.forEach({ free($0) })
```

Here's the comparison from my fork:
https://github.com/groue/GRDB.swift/compare/master...wuyuehyang:mixin

I would like to contribute by creating some pull requests, but I'm not quite familiar with porter or ascii tokenizers, don't know whether creating tokenizers like this will break them or not. Neither do I test my changes with FTS5TokenizerTests, it runs only when SQLITE_ENABLE_FTS5 is defined. I think maybe I should test it with a custom SQLite build? But I didn't find any guide about testing with FTS5.

### Demo project

[FTS5TokenizerDemo.zip](https://github.com/groue/GRDB.swift/files/5740238/FTS5TokenizerDemo.zip)

**Comment by groue** [comment]
Hello @wuyuehyang,

So it looks like you found a bug, and a fix? Thank you for both!

> I would like to contribute by creating some pull requests, but I'm not quite familiar with porter or ascii tokenizers, don't know whether creating tokenizers like this will break them or not. Neither do I test my changes with FTS5TokenizerTests, it runs only when SQLITE_ENABLE_FTS5 is defined. I think maybe I should test it with a custom SQLite build? But I didn't find any guide about testing with FTS5.

Thanks for looking for tests 👍 

You have two options for running FTS5 tests:

1. Run `make SQLiteCustom` in the Terminal, open the GRDB Xcode workspace, and run tests for the GRDBOSX target in the GRDBCustom project.
2. Modify `Support/GRDBDeploymentTarget.xcconfig` and uncomment the `GCC_PREPROCESSOR_DEFINITIONS` and `OTHER_SWIFT_FLAGS` lines. Now you can run FTS5 tests in the regular GRDB project. Those changes to GRDBDeploymentTarget.xcconfig must not be committed.

Maybe you could add your custom tokenizer to `FTS5CustomTokenizerTests.swift`?

**Comment by wuyuehyang** [comment]
#901
