### ISSUE TITLE
rename colum (iOS 12)

### ISSUE THREAD

**Issue by she1323** [groue/GRDB.swift#902]
if #available(iOS 13.0, *) {
        t.rename(column: "ss", to: "cc")
   } else {
        / / **how to do rename colum**
  }

**Comment by groue** [comment]
Hello @she1323.

Old versions of SQLite can't rename columns. You have to recreate the table. See [Advanced Database Schema Changes](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#advanced-database-schema-changes).
