### ISSUE TITLE
Queue question

### ISSUE THREAD

**Issue by SalsaShark** [groue/GRDB.swift#905]
First off, thanks so much for GRDB. When I rewrote my app in Swift, I used _that other SQLite library_ and performance was very much an issue. When data is updated there are as many as 6000 separate INSERTs. When I tried switching to GRDB it became **25 times faster**. This is not a paid endorsement. ;)

Anyway, I'm using a single db connection as prescribed. I had one instance where a query loop tried to do another call resulting in the "Database methods are not reentrant" issue, so I handed off the db to the nested call and resolved that.

However, I have a question about how the database queue works. Here's roughly what was being attempted, all on a single queue:

> AlamoFire Request 1:
>
> - on success, parse data and perform a series of inserts to table A
> - on completion, send notification A and do next request
>
>AlamoFire Request 2:
> - as above, perform actions on table B
 
...and so on until all files have been fetched.

The issue is that when that notification A is sent, it tries to reload the data in a view which includes reading from table A. Even though table A is no longer being written to, it crashes. Other tables are being written to, but I was under the impression that the dbQueue would still safely allow table A to be read from when able. Am I not understanding how the queue works? At least for now, I just send out a notification when all the db writes are done and all the views reload with no issue.

**Comment by groue** [comment]
Hello @SalsaShark,

Your description is not clear. Maybe you should have filled the [issue template](https://raw.githubusercontent.com/groue/GRDB.swift/master/.github/ISSUE_TEMPLATE.md). It's not too late.

**Comment by SalsaShark** [comment]
Without posting a thousand lines of code, it looks something like this. There's a function calling each of the fetchers in sequence using a DispatchGroup and when each completes it posts a notification, then a View Controller would try to reload data when the notification is received.

Actually, looking at this now, the notification should probably be sent by the completion handler and not sent in the fetcher's do block. That could be the issue.

The bottom line is, if a single queue is writing to a table, should the same queue be able to read from a different table?

```
class CalendarViewController: UITableViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        NotificationCenter.default.addObserver(forName: Notification.Name(rawValue: "teamsUpdated"), object: nil, queue: OperationQueue.main, using: fetchData)
    }
    func fetchData() {
        do {
            try AppDatabase.shared.dbQueue.read { db in
                let rows = try Row.fetchAll(db, sql: "SELECT ...")
                for row in rows {
                    // populate data
                }
            }
         } catch { print(error) }
    }
}

class TeamFetcher {
    func loadTeams(version: Int, dispatch: DispatchGroup, completion: @escaping (Bool) -> ()) {
        dispatch.enter()
        var teams: [Team] = []
        
        guard let url = URL(string: "http://foo.txt") else {
            completion(false)
            dispatch.leave()
            return
        }

        AF.request(url, method: .get, parameters: nil).validate().responseData { response in
            switch response.result {
            case .success(let value):
               // value is processed and...
                        do {
                            try AppDatabase.shared.dbQueue.write { db in
                                try db.execute(sql: "DELETE FROM `teams`")
                                for team in teams {
                                    if (team.id > 0) {
                                        try db.execute(
                                                sql: "INSERT INTO teams (id, name, shortname, conf, coach, twtrList) VALUES (?, ?, ?, ?, ?, ?)",
                                                arguments: [
                                                    team.id,
                                                    team.name,
                                                    team.shortname,
                                                    team.confId,
                                                    team.coach,
                                                    team.twtrList
                                                ])
                                    }
                                }
                                NotificationCenter.default.post(name: Notification.Name("teamsUpdated"), object: nil)
                            }
                        } catch {
                            print("TeamFetcher database error: \(error)")
                            completion(false)
                            dispatch.leave()
                            return
                        }
                    }
                }
                
            case .failure(let error):
                print("TeamFetcher error: \(error)")
                completion(false)
                dispatch.leave()
                return
            }
            
            dispatch.leave()
            completion(true)
        }
    }
}

```

**Comment by groue** [comment]
I can't find a way to understand your messages as a question or an issue about GRDB.
