### ISSUE TITLE
Trying to access existing SQLite DB

### ISSUE THREAD

**Issue by apptessence** [groue/GRDB.swift#906]
### What did you do?

I'm implementing GRDB in a Swift project. It's part of a framework that is in turn part of a Swift single-screen app. I have an existing DB that was developed for another project. We want to use this DB and access it (read only) using GRDB. GRDB is currently being imported into a class that is part of the framework.

### What did you expect to happen?

I expected to provide a filename appended to the usual Filemanager composition of the path to the DB. Since the command is given in the class in the Framework, I expected that GRDB would look for it relative to that file. 

### What happened instead?

A new, empty DB with the same name is created and exists in the Application Support folder that is used to run the app in the simulator.

### Environment

Straight GRDB
14.4
manual, i.e. Zip extraction, copied into project, then .xcodeproj dragged into FRAMEWORK, then added as library to Framework, import statement added.
12.3
5.2
iOS
10.15.7

### Demo Project
```
import Foundation
import UIKit

import GRDB

var dbQueue: DatabaseQueue!

public class WordDB {

    var dbPath : String = "words.sqlite3"
    
    init() {
        setup()
    }
    
    func setup()  {
        do { let databaseURL = try FileManager.default
            .url(for: .applicationDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
                .appendingPathComponent(dbPath)
            print(databaseURL.path)

            dbQueue = try  DatabaseQueue(path: databaseURL.path)
            print(" queue : \(dbQueue)")
        } catch {
            print("damn")
        }
//        dbQueue.setupMemoryManagement(in: application)
    }

    public func read() ->Int {
       return 0
    }
}
```

![Screen Shot 2021-01-12 at 4 22 41 PM](https://user-images.githubusercontent.com/61812307/104294936-6cda5980-54f2-11eb-86ad-970ddaddaf6a.png)

Again, the issue is (I hope) that the location of the db is not being picked up, because it's not documented where the DB will be stored in the Swift Project.

**Comment by groue** [comment]
Hello @apptessence,

GRDB opens a database at the path your app provide. It is the responsibility of your application to provide a path that matches your intents.

In your case, the database file is provided as a [resource](https://developer.apple.com/documentation/foundation/bundle) of your app bundle, embedded right into it. See the [How do I open a database stored as a resource of my application?](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-open-a-database-stored-as-a-resource-of-my-application) FAQ.
