### ISSUE TITLE
Performance on insert

### ISSUE THREAD

**Issue by comaxime** [groue/GRDB.swift#91]
Hi!
I am seriously considering GRDB for my upcoming app/project (seems to fit nicely), one concern for me being the performance, as I started "playing" with it.

I ran the sample tests provided (InsertRecordTests), the results I get are quite different though:
  - testCoreData ==> measured [Time, seconds] average: 0.663
  - testGRDB ==> measured [Time, seconds] average: 2.621
  - testRealm ==> measured [Time, seconds] average: 0.789

GRDB seems quite slower than the 2 other solutions.
Is there something I missed during the test, to get a similar result (GRDB faster) as in the wiki? :)

Thanks.

**Comment by groue** [comment]
Hello @comaxime,

Thanks for double checking the performance tests!

Make sure to run the tests in the Release configuration (Edit Scheme > Test > Build Configuration > Release). And GRDB will show its true speed.

- testCoreData: 0.62s
- testGRDB: 0.31s
- testRealm: 0.76s

It does indeed look like I have introduced a slight performance regression somewhere: GRDB is only twice as fast as Core Data when the Wiki promises better figures. It's high time I update the Wiki page with the latest version of all libs, and do a little performance hunting again.

**Comment by comaxime** [comment]
Hello @groue 

Ah yes indeed, that's the thing I was missing :) It is now much better.

DEBUG
 - testCoreData ==> measured [Time, seconds] average: 0.468
 - testGRDB ==> measured [Time, seconds] **average: 1.948**
 - testRealm ==> measured [Time, seconds] **average: 0.720**

RELEASE
 - testCoreData ==> measured [Time, seconds] average: 0.469
 - testGRDB ==> measured [Time, seconds] average: 0.305 ==> 6x faster :)
 - testRealm ==> measured [Time, seconds] average: 0.732


By running Instruments / Time Profiler on my own app (test to insert 20k rows), I noticed that some operations on persistentDictionary are responsible for 20-25% of the total time, and could be optimized by using 2 arrays in the MutablePersistable protocol, instead of 1 dictionnary:
- persistentColumns: [String] = column names (i.e. keys of persistentDictionary)
- persistentValues: [DatabaseValueConvertible?] = values to insert (i.e. values of persistentDictionary)

This avoids to call, in DataMapper / insertStatement():
- persistentDictionary.keys ==> directly use persistentColumns instead
- persistentDictionary.values ==> directly use using persistentValues instead
And persistentColumns can be a static/class array, only instantiated once, not for every record (of course if the persistentDictionary is always the same, for all situations)

Execution time dropped from 3.43s ==> 2.55s with these 2 arrays, intead of one dictionnary.
This is the only modification I made, to get this 25% time improvement.
But a dictionary is clearer to understand ("colum": value), while 2 arrays may easily lead to errors if the order of their values get wrong...

**Comment by groue** [comment]
> It is now much better.

I have a cold sweat each time I run the performance tests in Dev config by mistake :-)

> that some operations on persistentDictionary are responsible for 20-25% of the total time, and could be optimized by using 2 arrays in the MutablePersistable protocol, instead of 1 dictionary:
> [...]
> But a dictionary is clearer to understand ("column": value), while 2 arrays may easily lead to errors if the order of their values get wrong...

Yes. Being reasonably fast is a goal, but helper developers is a much higher goal.

If you look after raw insertion performance:

- Build a prepared statement using raw SQL
- Wrap executions in a transaction (to prevent SQLite from writing to disk for each insertion)
- Don't use dictionaries, but use arrays instead
- Use [unsafe statement arguments](http://cocoadocs.org/docsets/GRDB.swift/0.77.0/Classes/Statement.html#/s:FC4GRDB9Statement18unsafeSetArgumentsFVS_18StatementArgumentsT_) (if you trust your input).

```swift
try dbQueue.inTransaction { db in
    let statement = try! db.updateStatement("INSERT INTO records (a, b, c) VALUES (?,?,?)")
    for record in records {
        statement.unsafeSetArguments([record.a, record.b, record.c])
        try statement.execute()
    }
    return .Commit
}
```

**Comment by comaxime** [comment]
I did not see this, thanks a lot!

**Comment by groue** [comment]
Unsafe statement arguments are not documented yet, you're right.

**Comment by groue** [comment]
@comaxime Check the new Performance chapter in the doc: https://github.com/groue/GRDB.swift#performance

**Comment by comaxime** [comment]
Thanks a lot @groue for the advice.

I'll definitely be using GRDB for my project, starting today :)
