### ISSUE TITLE
[feature] Documentaion enhancement for SPM

### ISSUE THREAD

**Issue by einsweniger** [groue/GRDB.swift#913]
(template does not really fit the need of this, sorry :O)

I want ask in this issue if this is relevant enough to document a little more in detail (#903 related).
I'd be happy create a PR once someone gives me a nod :D

I'm building a swift library package that abstracts from SQLite and only hands out the the assembled types.
I found this project, and had a little trouble setting it up.
Thus, I'd like to add the caveats and error messages to the documentation, so others can resolve their troubles quicker.
As I just picked up swift recently, this might have been obvious errors on my behalf. 

### problem

I added the package without the `.package(name: "GRDB", ...` parameter and ran into trouble, like so:

```swift
import PackageDescription

let package = Package(
    name: "GRDBTest",
    products:  [ /*...*/ ],
    dependencies: [ // v---- there's your problem
        .package(/*name: "GRDB", */url: "https://github.com/groue/GRDB.swift.git", from: "5.3.0"),
    ],
    targets: [
        .target(
            name: "GRDBTest",
            dependencies: [
                .product(name: "GRDB", package: "GRDB"),
            ],
        ),
    ]
)
```
and ended up with a completely screwed up build :D
:x: `unknown package 'GRDB' in dependencies of target 'GRDBTest'`
once I added the name back in GRDB was recognized.
I was mislead by XCode, since the template adds a comment that I should add the dependencies like so:
```
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
```

**Proposed change** 
add the warning text from XCode to the documentation and tell what was done wrong, at least I did not see it

### minor remark

As the XCode template is also not generating the package platforms within Package.swift, I was promptly greeted by
:x:`The package product 'GRDB' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0`

I resolved that by adding this:

```swift
/* ... */
let package = Package(
    /* ... */
    platforms: [
        .iOS(.v10),
    ],
    /* ... */
)
```
Since I'm going to use the package in iOS, that's no trouble anyways.

**Proposed change**
add a remark to the documentation? Not sure if this is worth mentioning
[GRDBTest.zip](https://github.com/groue/GRDB.swift/files/5879395/GRDBTest.zip)

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v5.3.0
**Installation method:** SPM
**Xcode version:** Version 12.3 (12C33)
**Swift version:** Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1).
**Platform(s) running GRDB:** n/a
**macOS version running Xcode:** 11.1 (20C69)

### Demo Project
[GRDBTest.zip](https://github.com/groue/GRDB.swift/files/5879400/GRDBTest.zip)

PS: this is such a exceptionally neatly documented package and judging from that, the API seems delightful as well :3
Thank you all for making this

**Comment by groue** [comment]
Hello @einsweniger,

Thanks for the report. And I'm happy you could setup your package :-)

The SPM chapter of the doc is old: it was written at a time Xcode had no SPM support... Now I regret putting so much detail in it. A recent pull request addresses it as well: #903.

Fact is, SPM is very complex, it evolves, and it even introduces breaking changes. Making promises about SPM in the GRDB doc is just creating a maintenance burden without purpose.

I'll drastically shorten this chapter shortly.

**Comment by groue** [comment]
Done. Happy GRDB, @einsweniger!

**Comment by einsweniger** [comment]
Well, at least it's documented here :D Thank you!
