### ISSUE TITLE
I need a table name that can be adjusted according to the actual situation, instead of a fixed table name. How can I do that?

### ISSUE THREAD

**Issue by forkdog** [groue/GRDB.swift#916]
`static var databaseTableName: String {
        return "name"
}`

**Comment by groue** [comment]
Hello @forkdog,

This question was already asked in #833.

If your database schema contains a dynamic number of tables, you must explain why you need to escape the standard relational model.

If your database schema contains a fixed set of tables, but you need to access several tables through a single record type, then this is a distinct question, and we may discuss it.

Considering the terse way you asked the question, and the fact that you did not provide any explanation for your request, I don't expect any answer: I close this issue. Feel free to reopen if you have something specific to ask.

**Comment by groue** [comment]
QueryInterfaceRequest builder with dynamic table/view name is addressed by the pull request #993.
