### ISSUE TITLE
Getting error "Type of expression is ambigious without more context." while implementing hasMany(through, using) method

### ISSUE THREAD

**Issue by abdbutt** [groue/GRDB.swift#917]
Table 1: Programs
Table 2: Goals
Pivot Table: ProgramGoals

I have a class Program and another class Goals. They have many to many relationship. For this i am trying to create static variable goals in Program class. 

============================================================================
`static let programGoals = hasMany(ProgramGoal.self)
    var programGoals: QueryInterfaceRequest<ProgramGoal> {
        request(for: Program.programGoals)
    }
    
    static let goals = hasMany(Goal.self, through: programGoals, using: ProgramGoal.program)`
============================================================================

1) programGoals is the relationship of Program with pivot table ProgramGoal
2) goals is the relation between Program and Goals i.e many to many. 

but on declaring goals xcode is giving me an error of "Type of expression is ambiguous without more context".

![Screenshot 2021-02-03 at 5 04 42 PM](https://user-images.githubusercontent.com/42769843/106745576-1c62a180-6643-11eb-9bfc-87400fa8b21e.png)

**Comment by groue** [comment]
Hello @abdbutt,

You did not fill the issue template, and did not care providing a reproducing example. Will you please create another issue with the requested information? You make it difficult for other people that to help you if you hide information, I'm sure you understand. Thank you.
