### ISSUE TITLE
Possible defaults to another column value?

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#921]
Hello,

Is it possible to set a table schema where one column defaults to the value of another column w/ the same type?

Here's a draft of what I'm trying to achieve:
```
table { Contact in
  .name, .text 
  .nickname, .text .defaults(to Contact.Name)
}
```

**Comment by groue** [comment]
Hello @brunomunizaf,

There is no such feature in SQLite: https://sqlite.org/lang_createtable.html
