### ISSUE TITLE
Error: 'too many SQL variables'

### ISSUE THREAD

**Issue by rpoelstra** [groue/GRDB.swift#924]
### What did you do?

I run the following query in a `TransactionObserver` `databaseDidCommit()`
```
let request = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .filter(keys: insertedElementIDs)
    .order(Element.Columns.polarityIndex.desc)
```

This is the same dataset as the one that seems a bit slow (issue for that will follow later), so we're talking about lots of rows here. Hence this error isn't entirely unexpected, but leaves me wondering how to proceed. Should GRDB do some kind of split up? Or maybe group the ID's and fetch ranges? Or should the application code do so? 
And how to do the split up efficiently? When should a split be made?

### What did you expect to happen?

To get back the requested rows.

### What happened instead?

SQLite shows the following error:
```
[logging] too many SQL variables in "SELECT "element"."id", "element"."type", "element"."lineNumber", "element"."imageId", "element"."layerId", "element"."parentId", "element"."sibling", "element"."xRepeat", "element"."yRepeat", "element"."xStep", "element"."yStep", "element"."clearPolarity", "element"."polarityIndex", "element"."rotation", "element"."scale", "element"."x1", "element"."y1", "element"."x2", "element"."y2", "element"."x3", "element"."y3", "element"."x4", "element"."y4", "element"."x5", "element"."y5", "element"."angle", "element"."xMirror", "element"."yMirror", "element"."apertureId", "element"."apertureWidth", "element"."apertureHeight", "element"."apertureOffsetX", "element"."apertureOffsetY", "aperture"."apertureData" FROM "element" LEFT JOIN "aperture" ON "aperture"."id" = "element"."apertureId" WHERE "element"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.2.0
**Installation method:**  SPM
**Xcode version:** 12.4
**Swift version:** 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.2.1

**Comment by groue** [comment]
Hello @rpoelstra,

> this error isn't entirely unexpected ...

Indeed, SQLite has [limits](https://www.sqlite.org/limits.html).

> ... but leaves me wondering how to proceed. Should GRDB do some kind of split up? 

GRDB can't split your request. The `QueryInterfaceRequest` type has a `makePreparedRequest` method that forces it to compile into one SQLite prepared statement (and fail when there are too many arguments). This `makePreparedRequest` method is useful for GRDB users when they want to know [which SQL would be run by a request](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-print-a-request-as-sql), but also for anything they want to do with this prepared statement: it's not a public API that can be changed lightly.

---

**Filter in the database, split in the app, sort in the app**

You can call the `Database.maximumStatementArgumentCount` property, which returns the value of [SQLITE_LIMIT_VARIABLE_NUMBER](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber). For example:

```swift
// Not filtered, not ordered
let baseRequest = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .asRequest(of: ElementInfo.self)

// Fetch chunks
var items: [ElementInfo] = []
items.reserveCapacity(insertedElementIDs) // Assume all inserted ids will be found
let chunkSize = db.maximumStatementArgumentCount
for ids in insertedElementIDs.chunks(ofCount: chunkSize) {
    let partialRequest = baseRequest.filter(keys: ids)
    try items.append(contentsOf: partialRequest.fetchAll(db))
}

// Sort items by polarityIndex
items = items.sorted { ... }
```

(The `chunks(ofCount:)` method comes from https://github.com/apple/swift-algorithms/blob/main/Guides/Chunked.md)

---

**Sort in the database, filter in the app**

Alternatively, you can also fetch all rows without filtering, and discard them after they are fetched:

```swift
let request = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .order(Element.Columns.polarityIndex.desc)
    .asRequest(of: ElementInfo.self)

let items = request.fetchAll(db).filter { insertedElementIDs.contains($0.id) }
```

A variant of the same technique, which only decodes filtered rows:

```swift
let request = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .order(Element.Columns.polarityIndex.desc)
    .asRequest(of: Row.self)

var items: [ElementInfo] = []
items.reserveCapacity(insertedElementIDs) // Assume all inserted ids will be found
let rows = try request.fetchCursor(db)
while let row = try rows.next() {
    guard insertedElementIDs.contains(row["id"]) else { continue }
    items.append(ElementInfo(row: row))
}
```

Since you're after performance, I suggest you profile those variants (in release configuration) before you pick one (or design a better alternative).

**Comment by groue** [comment]
> Since you're after performance [...]

Also don't miss the "plain struct optimized for fetching performance" in [Examples of Record Definitions](https://github.com/groue/GRDB.swift/blob/master/README.md#examples-of-record-definitions). Avoid Decodable, any column/string lookup, and go straight to numerical column indexes.

**Comment by groue** [comment]
Gosh, it looks like I erased the details answer by mistake. Did you get an email, @rpoelstra ?

**Comment by rpoelstra** [comment]
@groue Yes, I did :) Thanks. I'll look into it ASAP. Looks very useful already.

**Comment by groue** [comment]
All right ;-) Maybe you lost some slight edits and clarifications. Just ask if something is not clear!

**Comment by rpoelstra** [comment]
Hi @groue ,
Your first suggestion (filter in the database, sort in there app) took about 4 minutes to fetch everything. Most of this time was spend binding arguments to the statement.
The second approach (sort in the database, filter in the app) takes 4 seconds, assuming the `insertedElementIDs` is a Set, otherwise it takes, well, long. I didn't wait for it to complete.
I was thinking that using an `IndexSet`'s `rangeView` might be a possibility to construct multiple (but few) `BETWEEN` clauses. This with the notion that a single transaction will likely create consecutive ID's. The problem here is that `IndexSet` always holds on `Int`, instead of the `Int64` that SQL (or at least my structs) use. I haven't investigated this though. I'm happy with 4 seconds for now, compared to the 50 s that the inserts take.

**Comment by rpoelstra** [comment]
For reference your original post:
-----------------------------------
Hello @rpoelstra,

this error isn't entirely unexpected ...

Indeed, SQLite has limits.

... but leaves me wondering how to proceed. Should GRDB do some kind of split up?

GRDB can't split your request. The QueryInterfaceRequest type has a makePreparedRequest method that forces it to compile into one SQLite prepared statement (and fail when there are too many arguments). This makePreparedRequest method is useful for GRDB users when they want to know which SQL would be run by a request, but also for anything they want to do with this prepared statement: it's not a public API that can be changed lightly.

Filter in the database, split in the app, sort in the app

You can call the Database.maximumStatementArgumentCount property, which returns the value of SQLITE_LIMIT_VARIABLE_NUMBER. For example:

// Not filtered, not ordered
let baseRequest = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .asRequest(of: ElementInfo.self)

// Fetch chunks
var items: [ElementInfo] = []
items.reserveCapacity(insertedElementIDs) // Assume all inserted ids will be found
let chunkSize = db.maximumStatementArgumentCount
for ids in insertedElementIDs.chunks(ofCount: chunkSize) {
    let partialRequest = baseRequest.filter(keys: ids)
    try items.append(contentsOf: partialRequest.fetchAll(db))
}

// Sort items by polarityIndex
items = items.sorted { ... }
(The chunks(ofCount:) method comes from https://github.com/apple/swift-algorithms/blob/main/Guides/Chunked.md)

Sort in the database, filter in the app

Alternatively, you can also fetch all rows without filtering, and discard them after they are fetched:

let request = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .order(Element.Columns.polarityIndex.desc)
    .asRequest(of: ElementInfo.self)

let items = request.fetchAll(db).filter { insertedElementIDs.contains($0.id) }
A variant of the same technique, which only decodes filtered rows:

let request = Element
    .annotated(with: apertureAlias[Column("apertureData")])
    .joining(optional: Element.aperture.aliased(apertureAlias))
    .order(Element.Columns.polarityIndex.desc)
    .asRequest(of: Row.self)

var items: [ElementInfo] = []
items.reserveCapacity(insertedElementIDs) // Assume all inserted ids will be found
let rows = try request.fetchCursor(db)
while let row = try rows.next() {
    guard insertedElementIDs.contains(row["id"]) else { continue }
    items.append(ElementInfo(row: row))
}
Since you're after performance, I suggest you profile those variants (in release configuration) before you pick one (or design a better alternative).

**Comment by groue** [comment]
Thanks for the report, @rpoelstra!

I have never investigated such heavy setups, so you're pretty much exploring uncharted territories here. It looks like arguments binding could get a little more love. You may have other suggestion.

All in all, thank you for patiently exploring various alternatives 👍. At this level, it's difficult to setup a one-size-fits-all technique. I'm happy you could achieve a satisfying resting point!

**Comment by rpoelstra** [comment]
> > Since you're after performance [...]
> 
> Also don't miss the "plain struct optimized for fetching performance" in [Examples of Record Definitions](https://github.com/groue/GRDB.swift/blob/master/README.md#examples-of-record-definitions). Avoid Decodable code synthesis, any column/string lookup, and go straight to numerical column indexes.

I do use this technique for the basic `Element` struct, but decoding `ElementInfo` seems to use a bit of the string based approach, as I see references to `KeyedContainer` as well as `Row.index(forColmn:)`, but that's all done in a second or so.
