### ISSUE TITLE
Decoding rows from prefetch with custom decoder

### ISSUE THREAD

**Issue by rpoelstra** [groue/GRDB.swift#927]
### What did you do?
I use custom  `init(row:)` initialiser to decode rows using numeric indexes (for performance). This works fine if I do 'normal' fetches of the type.
But when I fetch a helper struct, like:
```
    struct LayerWithElements: Decodable, FetchableRecord, Equatable, Hashable {
        let layer: Layer
        let elements: [Element]
    }
```
with a query like: 
```
let request = Layer
    .including(all: Layer.elements.filterObjects().order(Element.Columns.id.desc))
```
then my custom `init(row:) isn't called. I noticed during profiling that `init('from:)` is called and there seem to be a lot of calls related to keyed decoding, but there are only 20 `Layer`'s fetched, with thousands of `Element`'s, so decoding the helper struct shouldn't take much time. (Both `Layer` and `Element` (can) use numeric decoding).

For reference, the actual fetch takes 284 ms and decoding takes 3.26 s.
It seems this is due to the fact that `Collection.map(_:)` (FetchableRecord:368) doesn't know about `init(row:)`. Is there a way to make it use the `init(row:)` initialiser? Or should I drop to fetching the `Element`'s myself?

### What did you expect to happen?

Super fast decoding :)

### What happened instead?

Quite slow decoding

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.4.0
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.2.1

**Comment by groue** [comment]
Hello @rpoelstra,

`LayerWithElements` is decoded with the `Decodable` machinery, which happens to use `Decodable.init(from:)` instead of `FetchableRecord.init(row:)` when it decodes a property. Maybe it's possible to force `init(row:)` for types that conform to both `FetchableRecord` and `Decodable`, with a runtime check.

This runtime check does not exist today, so your solution is to avoid the `Decodable` machinery, and rely on `FetchableRecord` only:

```swift
struct LayerWithElements: FetchableRecord, Equatable, Hashable {
    let layer: Layer
    let elements: [Element]

    init(row: Row) {
        layer = Layer(row: row)
        elements = row.prefetchedRows["elements"].map { Element(row: $0) }
    }
}
```

**Comment by rpoelstra** [comment]
Hi @groue,
This works great as usual!
Thanks!
