### ISSUE TITLE
Association works with hasOne but not with hasMany

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#928]
### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.4.0
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.x
**Platform(s) running GRDB:** iOS

Hi Gwendal, 

Long time, wasn't ? :) I hope you are fine

I have a problem with associations:
It only works when i use `hasOne` but i got a `nil` value with `hasMany`

**OK:** 
```
struct SSerie: Codable, FetchableRecord, MutablePersistableRecord, TableRecord {
    ...
    static let itemsyncFK = ForeignKey(["primary"], to: ["primary"])
    static let itemsync = hasOne(SItemSync.self, using: itemsyncFK)
    var itemsync: SItemSync?
   ...
}

...

try? dbQueue.read { db in
    let items = try SSerie
                .filter(sql: "serie.`primary` = 'S-454'")
                .including(optional: SSerie.itemsync)
                .fetchAll(db)
}
```
itemsync contain one row, so association is working

**Not OK:**
```
struct SSerie: Codable, FetchableRecord, MutablePersistableRecord, TableRecord {
...
    static let itemsyncFK = ForeignKey(["primary"], to: ["primary"])
    static let itemsync = hasMany(SItemSync.self, using: itemsyncFK)
    var itemsync: [SItemSync]?
...
}
...

try? dbQueue.read { db in
    let items = try SSerie
                .filter(sql: "serie.`primary` = 'S-454'")
                .including(all: SSerie.itemsync)
                .fetchAll(db)
}
```
`itemsync`= nil

Note: When i'm looking SQL log, i see:
```
SQL> SELECT * FROM "serie" WHERE serie.`primary` = 'S-454'
SQL> SELECT *, "primary" AS "grdb_primary" FROM "itemsync" WHERE "primary" = 'S-454'
```

Any idea ?
Thanks !

**Comment by groue** [comment]
Hello faithful @skrew :-)

I'm not 100% sure, but I'd expect the array to be decoded into the `itemsyncs` property name.

You can rename the property, or change the association key with:

```swift
static let itemsync = hasMany(...).forKey(CodingKeys.itemsync)
```

**Comment by skrew** [comment]
As i read the docs, the plurial is the first thing i have tested :)
BTW, plurial or not, `forKey()` or not, i'm still getting `nil` but it's not a problem anymore, i have changed the structure of the DB.

But if you want to know why i'm getting `nil` i remain at your disposal for further tests.

**Comment by groue** [comment]
@skrew, without some kind of reproducible case, it's hard to dig further. Let's wait for another user to report a similar issue - I don't expect it to be very nasty. See you then ;-)
