### ISSUE TITLE
`COLLATE` operator is applied to the wrong operand for `IN` and `NOT IN` operators

### ISSUE THREAD

**Issue by gcox** [groue/GRDB.swift#929]
### What did you do?

Attempted to fetch records where a text column's value is found in an array of values. Using `RecordType.filter(['stringa', 'stringb'].contains(Column.name.collating(.nocase)))`

### What did you expect to happen?

Records with names like 'StringA' and 'StringB' to be returned

### What happened instead?

Only records with names like 'stringa' and 'stringb', exact matches, are returned. The filter is not ignoring case.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.4
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS, macOS
**macOS version running Xcode:** 11.2.2

### Cause

The problem is that the `COLLATE` operator is applied to the wrong operand of the `IN` operator. For the `IN`/`NOT IN` operators, the `COLLATE` operator must be applied to the left operand.

From [section 7.1 of the documentation](https://sqlite.org/datatype3.html#assigning_collating_sequences_from_sql), see the last sentence:

> The expression "x BETWEEN y and z" is logically equivalent to two comparisons "x >= y AND x <= z" and works with respect to collating functions as if it were two separate comparisons. The expression "x IN (SELECT y ...)" is handled in the same way as the expression "x = y" for the purposes of determining the collating sequence. The collating sequence used for expressions of the form "x IN (y, z, ...)" is the collating sequence of x. ***If an explicit collating sequence is required on an IN operator it should be applied to the left operand, like this: "x COLLATE nocase IN (y,z, ...)".***

**Comment by groue** [comment]
Hello @gcox, thank you for the report!

**Comment by gcox** [comment]
@groue Sorry it doesn't come with a PR. It just wasn't clear to me how to modify the placement of the COLLATE part of the expression in a specific case like this.

**Comment by groue** [comment]
The fix (#930) will ship soon!

**Comment by groue** [comment]
The fix has shipped in v5.5.0.

Thanks again for reporting this bug, @gcox.

**Comment by gcox** [comment]
@groue Thanks for fixing it so quickly!
