### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by zmeyc** [groue/GRDB.swift#94]
I'm trying to build GRDB on Linux (with SPM).

At first I tried to use `swift-corelibs-libdispatch` from `experimental/foundation` branch. It lacks new Dispatch wrappers from OS X Foundation (DispatchQueue etc). Converting GRDB to use C-style libdispatch API calls on Linux seemed like a lot of unnecessary work considering there's an ongoing work to port new libdispatch wrappers to Linux.

Then I tried to use `swift-3.0-branch` branch which contains these wrappers. It did not work with 2016-07-25 toolchain, swiftc crashed with assertion failure when building libdispatch. Preview-4 also crashed.

I was able to build libdispatch using 2016-08-04 Swift toolchain. Now I'm updating GRDB to compile with 2016-08-04 syntax changes.

Steps below are for setting up compilation environment on Ubuntu 14.04 in case anyone wants to experiment too:

Install swiftenv:

```
sudo apt-get install git
git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' >> ~/.bashrc
echo 'export PATH="$SWIFTENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(swiftenv init -)"' >> ~/.bashrc
```

Install Swift and it's dependencies:

```
sudo apt-get install clang
swiftenv install swift-DEVELOPMENT-SNAPSHOT-2016-08-04-a
```

Build libdispatch.

For building libdispatch clang 3.8+ is required:

```
sudo apt-get install clang-3.8 lldb-3.8
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
```

Build and install libdispatch:

```
sudo apt-get install autoconf libtool libkqueue-dev libkqueue0 libcurl4-openssl-dev libbsd-dev libblocksruntime-dev
export SWIFT_HOME=~/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-08-04-a
git clone --recursive -b swift-3.0-branch https://github.com/apple/swift-corelibs-libdispatch.git
cd swift-corelibs-libdispatch
sh ./autogen.sh
./configure --with-swift-toolchain=$SWIFT_HOME/usr --prefix=$SWIFT_HOME/usr
make
make install
```

My fork https://github.com/zmeyc/GRDB.swift.git contains two updated branches:

`Swift3` is 2016-08-04 snapshot port (NOT SPM compabile). @groue I'm not sure if I got Data / NSData / AnyObject casts correctly. Also, I'm not able to run the tests: swiftc crashes when I try to build the project using `GRDB.xcworkspace`, yet it builds successfully from xcodeproj generated by SPM.

`SPM` has Package.swift plus a few minor tweaks to get it working with SPM.

I'll merge them soon and continue with Linux port.

**Comment by groue** [comment]
That's great, @zmeyc, thanks for your hard work!

Loosely following https://github.com/IBM-Swift/GRMustache.swift, I can see that support for Foundation on Linux requires a heck a lot of `#if os(Linux)`. I hope it gets better as time passes.

You must have seen that I update the Swift3 branch quite regularly, targeting Xcode's Swift 3 (not the latest master snapshot). I hope this to not disturb you too much.

**Comment by groue** [comment]
Related issue: #72

**Comment by zmeyc** [comment]
Not at all, Previews are very frequent anyway, but snapshots are untested and often unusable. I also prefer Xcode releases, but libdispatch Swift shims require a newer version.

I've got it compiling on Linux, the changes are in `Linux` branch: https://github.com/zmeyc/GRDB.swift/commit/b183d22a400724f98b155fb6e726553bf347a741

A quick summary of changes:

- I use CSQLite external module to build sqlite. Currently it contains amalgamated sqlite3.c, but users can make their own fork of CSQLite with custom built sqlite and add it to project's Package.swift if needed. I think it will override GRDB's one. `CSQLite` is imported conditionally if `SWIFT_PACKAGE` is defined. `SWIFT_PACKAGE` is defined when SPM is used: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#packaging-legacy-code
Maybe `CSQLite` can be made an internal module (inside of GRDB repo), but I haven't tried this.

- `NSLog` is missing, replaced with `print` on Linux.

- Added `import Dispatch` in some files.

- `DispatchSourceFileSystemObject` is not supported on Linux and probably won't be in the nearest time. I disabled the monitoring of directories for newly created files in DatabaseStore.swift.

- Lots of ifdefs where Linux and OS X APIs mismatch.

- Some of init-s don't have `required` attribute on them in Linux which makes classes impossible to construct by calling `self.init`, I had to use very ugly workarounds which won't work correctly with subclasses:

```
     public static func fromDatabaseValue(_ databaseValue: DatabaseValue) -> Self? {
...
+            let coder = NSCoder()
+            let data = NSData(data: data)
+            data.encode(with: coder)
+            return self.init(coder: coder)
```

I'll report these issues, hopefully they will be fixed. I'll now try to get the tests running.

**Comment by johnburkey** [comment]
Did you get this running on Linux ?

**Comment by zmeyc** [comment]
@johnburkey @groue I've sent a PR: https://github.com/groue/GRDB.swift/pull/205

**Comment by groue** [comment]
Closing in favor of #205
