### ISSUE TITLE
Filtering with Combine publishers

### ISSUE THREAD

**Issue by seowalex** [groue/GRDB.swift#943]
I would like to use publishers to update my list of models, but also be able to filter the models through a `TextField`. Right now, I am trying to follow the demo app given using Combine, but the publisher does not seem to update with the correct list of models. One way I have tried is adding a `didSet` to my `query` variable to update the `playersCancellable`, which works, but that does not seem like the correct solution.

For reference, my code (simplified) looks something like this:

```swift
final class PlayerListViewModel: ObservableObject {
  @Published var query: String = ""
  @Published var players: [Player] = []

  private let database: AppDatabase
  private let playersCancellable: AnyCancellable?

  init(database: AppDatabase) {
    self.database = database
    playersCancellable = playersPublisher(in: database)
      .sink { [weak self] players in
        self?.players = players
      }
    }

  private func playersPublisher(in database: AppDatabase) -> AnyPublisher<[Player], Never> {
    database.playersFilteredByNamePublisher(query)
      .catch { _ in
        Just<[Player]>([])
      }
      .eraseToAnyPublisher()
    }
  }
}
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.6.0
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15

**Comment by groue** [comment]
Hello, @seowalex.

The [SwiftUI demo app](https://github.com/groue/GRDB.swift/tree/master/Documentation/DemoApps/GRDBCombineDemo) updates a publisher according to an ordering (so that the user can sort a list of players by name or by score). You should be able to adapt it for your needs, because your use case looks very similar.

**Comment by seowalex** [comment]
I have indeed tried to adapt it, but it seems that when the `TextField` gets updated, the publisher does not republish a new list of `Players` with the new query.

**Comment by groue** [comment]
Then adapt [playersPublisher(in:)](https://github.com/groue/GRDB.swift/blob/v5.6.0/Documentation/DemoApps/GRDBCombineDemo/GRDBCombineDemo/ViewModels/PlayerListViewModel.swift#L98-L116) again. The sample publisher *does* publish a new list of players when the ordering changes. First understand what you are trying to adapt. You'll be able to ask better, more focused question. And, most likely, to answer them yourself.

**Comment by groue** [comment]
@seowalex, did you make any progress, or do you have any specific question that emerged from your attempts at solving this Combine/SwiftUI/GRDB puzzle? This issue will close if you remain silent.

**Comment by seowalex** [comment]
Apologies, have been rather busy. I realised that it was due to my publisher function not mapping from the published variables. It works now, thanks!
