### ISSUE TITLE
Question: How to search a simple column, via Query Syntax?

### ISSUE THREAD

**Issue by eytanschulman** [groue/GRDB.swift#949]
I've been looking for a good while in documentation, and past issues regarding what syntax to use in order to search a particular column of a table for a search query.

Most searches have led me to Full Text Search with `FTS5`, but I have yet to get it to work and it seems like an overkill for this? I simply want to match a particular column to partial search text.

Would greatly appreciate help!

Thanks

**Comment by groue** [comment]
Hello @eytanschulman,

> I simply want to match a particular column to partial search text.

Would you mind giving more information? I'm afraid we can't afford the "simply" word when we talk about search, even if I dearly wish we could.

For example, you can use the `LIKE` operator to look for strings that contain another string:

```swift
// Finds "Bob Ball", "Bobby Bing", "Arthur Bobtown", ...
let players = Player.filter(Column("name").like("%Bob%")).fetchAll(db)
```

Or strings that start with another string:

```swift
// Finds "Bob Ball", "Bobby Bing", ...
let players = Player.filter(Column("name").like("Bob%")).fetchAll(db)
```

Those queries [do what the LIKE operator does](https://sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators), no more, no less.

Full text search does much more, as you have seen in the documentation.

But no one knows what you mean by "simply".

**Comment by eytanschulman** [comment]
> Hello @eytanschulman,
> 
> > I simply want to match a particular column to partial search text.
> 
> Would you mind giving more information? I'm afraid we can't afford the "simply" word when we talk about search, even if I dearly wish we could.
> 
> For example, you can use the `LIKE` operator to look for strings that contain another string:
> 
> ```swift
> // Finds "Bob Ball", "Bobby Bing", "Clara Bobtown", ...
> let players = Player.filter(Column("name").like("%Bob%")).fetchAll(db)
> ```
> 
> Or strings that start with another string:
> 
> ```swift
> // Finds "Bob Ball", "Bobby Bing", ...
> let players = Player.filter(Column("name").like("Bob%")).fetchAll(db)
> ```
> 
> Those queries [do what the LIKE operator does](https://sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators), no more, no less.
> 
> Full text search does much more, as you have seen in the documentation.
> 
> But no one knows what you mean by "simply".

Thanks @groue , I definitely didn't provide enough context here to get a solid answer, sorry about that.
What I'm doing is using a `UISearchController`, which I want to filter database results for a particular table based off of two columns.

The second column I am filtering by (`name`), needs to be by the partial search result from the `UISearchController.`

Thanks to your example with the use of the `LIKE` operator (`.like()`) I managed to get it working now!

The following is what worked for me:
```swift
let cityFilter = rawTypes.contains(Column(Location.Column.type.rawValue))
let nameFilter = Column(Location.Column.name.rawValue).like("%\(searchText)%")
let request = Location.filter(cityFilter && nameFilter)
return try request.fetchAll(db)
```

Thanks again!
