### ISSUE TITLE
Passing a collection of objects to arguements

### ISSUE THREAD

**Issue by blkbam** [groue/GRDB.swift#95]
I'm attempting to migrate some code from SQLite.Swift to GRDB and one of the things it allowed me to do was to have a collection of objects to pass a parameters.  This is beneficial because I generate where clauses dynamically. With the arguments parameter being a struct, I'm not seeing a clear migration path for this code. How can I accomplish the same goal using this library?

Here's a sample of what I'm trying to accomplish:

```
let authorName = "Arthur"
let authorScore = 20

var valueCollection = [ AnyObject ]()
var whereClause = ""

if authorName != ""
{
    whereClause += "name = ? "
    valueCollection.append(authorName)
}

if authorScore > -1
{
    whereClause += "score = ? "
    valueCollection.append(authorScore)
}

let rows = Row.fetchAll(db,
    "SELECT * FROM persons WHERE \(whereClause)",
    arguments: valueCollection)

```

**Comment by groue** [comment]
Hello @blkbam 

You have two options. The first one is generating SQL, as you have tried to do:

```swift
let authorName = "Arthur"
let authorScore = 20

var whereArguments = [DatabaseValueConvertible?]()
var whereClauses = [String]()

if authorName != "" {
    whereClauses.append("name = ?")
    whereArguments.append(authorName)
}

if authorScore > -1 {
    whereClauses.append("score = ?")
    whereArguments.append(authorScore)
}

let whereClause = "(" + whereClauses.joinWithSeparator(") AND (") + ")"
let rows = Row.fetchAll(db,
    "SELECT * FROM persons WHERE \(whereClause)",
    arguments: StatementArguments(whereArguments))
```

Note how statement arguments are not AnyObject. They're DatabaseValueConvertible, which helps the compiler make sure you only use values that can be used with SQLite. Also, the type of arguments is StatementArguments - you can pass array literal in, or explicitly build one from an array of yours.

The second option is the [query interface](https://github.com/groue/GRDB.swift#the-query-interface).

The minimal setup is declaring a type that adopts the TableMapping protocol:

```swift
struct Person : TableMapping {
    static func databaseTableName() -> String { return "persons" }
}
```

From then, you don't build SQL by hand. Instead, you refine a fetch request until you have the one you need:

```swift
let authorName = "Arthur"
let authorScore = 20

var request = Person.all()

if authorName != "" {
    request = request.filter(SQLColumn("name") == authorName)
}

if authorScore > -1 {
    request = request.filter(SQLColumn("score") == authorScore)
}

let rows = Row.fetchAll(db, request)
```

Pick the solution you prefer, and happy GRDB!

**Comment by blkbam** [comment]
Thanks for the quick response. AnyObject was just a placeholder for the example since I wasn't sure which object to use. I've put in the example and it works.
