### ISSUE TITLE
Problem with 0xdead10cc exception

### ISSUE THREAD

**Issue by georgbachmann** [groue/GRDB.swift#957]
### What did you do?

I am using GRDB in my app to store and read data. I do so also right after the app starts. Now I've noticed some crashes in my app that users are having and found the termination reason: Namespace RUNNINGBOARD, Code 0xdead10cc.

I then googled a bit and found @groue s conversation in AppleDeveloper Forums: https://developer.apple.com/forums/thread/126438 and also this issue here https://github.com/groue/GRDB.swift/issues/643

So basically... it means that this happens, when my app is holding a lock while being suspended, right?
I am only wondering, cause my app did just start.
Also does it only happen when the database is in an App-Group-Container? (mine is)

Would be great if somebody could explain to me how to fix the problem? Or what exactly I might be doing wrong. Especially since, according to my crashlogs, my app ist just starting...

I know my question is a bit vague, but I don't really know that much about that crash. I've only seen Xcode Crash Logs and they are not that suuuuper helpful to me :( And I've not managed to reproduce the crash yet. Also tried the code from https://github.com/groue/10deadcc in my app, but I just can't reproduce the crash :(

So any help is greatly appreciated!!! :)

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.7.3
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.1

**Comment by groue** [comment]
Hello @georgbachmann,

Welcome to the team of the 0x10DEADCC victims!

Sharing is database in an App Group Container is hard. You will need elbow grease. Start there: https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md

Above all, remember that it may be **much simpler** to avoid sharing the database, and export some small pieces of data in the App Group Container. Only share if you **really have to**.

Debugging such issues is *very* difficult, so I won't be able to provide the usual free support. Yet, the linked guide above contains advice. If you discover something that should be changed, please report your discoveries.

**Comment by georgbachmann** [comment]
Thank you very much for your as usual super fast and accurate answers! Really appreciate it!

Ok... so my database isn't even shared yet... I just moved it to the Shared-App-Container just so that I COULD share it... 
But does simply having it in the shared container already cause a potential problem?

**Comment by groue** [comment]
Yes, it does. This is precisely the presence of the database file in the shared container that causes iOS to monitor SQLite locks and crash the app when it enters the suspended mode. Check the tech note, and https://developer.apple.com/forums/thread/126438

**Comment by groue** [comment]
All right, @georgbachmann. I'll close this issue. Please open a new one when you have a new specific question!
