### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by classified** [groue/GRDB.swift#96]
it seems there's no support for watchOS. FMDB does have watchOS support but for swift version i like GRDB more. will watchOS get supported?

**Comment by groue** [comment]
Yes, it will: I was waiting for such a request. Please hold on. If you feel like doing it, you can also create a WatchOS target yourself in the GRDB project, based on the iOS target, with reasonable chances of success.

**Comment by groue** [comment]
The [WatchOS](https://github.com/groue/GRDB.swift/tree/WatchOS) branch contains a framework for WatchOS. You can install it using the [manual installation procedure](https://github.com/groue/GRDB.swift/tree/WatchOS#manually).

Xcode 7.3 doesn't allow testing WatchOS frameworks. That means that you're on the very edge: I hope that you won't have any problem, but I provide no guarantee. Your feedback is welcome.

**Comment by classified** [comment]
Thank you very much.

**Comment by classified** [comment]
It's working perfect at the moment. if any type error occurs i will let you know. Thanks again.

**Comment by groue** [comment]
Good news!

Did you run it on both simulator and device?

If so, I'll merge it into the master branch and ship WatchOS support officially.

**Comment by classified** [comment]
I've tested it on simulator and device. it's working good for now. Currently i'm testing with multiple conditions on watchOS 2 and will try to test it on my older watchOS 1 too. But for now it's ready to be shipped. if you want to wait for some more test result. i can do it in 1-2 days. Thanks

**Comment by groue** [comment]
I personally can wait two days, even more. Your experience is welcome: yes I'm interested in your confirmation that you had no trouble.

> will try to test it on my older watchOS 1 too

I think I have set the framework target SDK to WatchOS 2.0 - WatchOS 1 would be nice, for sure, but I don't expect that many people will support it as WatchOS 3 is about to ship: don't do it unless you really need it!

**Comment by classified** [comment]
I will test in upcoming 2-3 days as currently i am working on my project. sorry for that but i found one error which prevent me from building framework for device . i've fixed that. in .modulemap file in WatchOS target you need add / after include to make it work as of right now i've only encountered this bug only. i will update you more about working condition in 2-3 days sorry for that.

**Comment by groue** [comment]
You're very helpful, thank you!

**Comment by classified** [comment]
Sorry for the late response. i've tested it and it does work with watchOS 2. No any extra crashes from sqlite lib found yet. so i think it's ready to be released. Tested version : 2.0 to 2.2

**Comment by groue** [comment]
Thanks, @classified!

**Comment by groue** [comment]
WatchOS support has shipped in v0.80.0
