### ISSUE TITLE
How to exclude some fields correctly?

### ISSUE THREAD

**Issue by HeebeLee** [groue/GRDB.swift#963]
```
class A: NSObject, Codable, Identifiable, FetchableRecord, PersistableRecord...{
    var a: Int!
    var b: String!
    
    /// I'd like to rule it out
    var _lastEditTime: Date!
}

/// read
var list = try dbQueue.read { (db) in
    let info = try A.fetchAll(db)
    ...
    item._lastEditTime = Date()
    ...
    return info
}

// db create
try db.create(table: "a") { t in
    t.column("a", .integer)
    t.column("b", .text).notNull()
}
```

I defined a class with some complex inheritance fields.

I now define a dynamic field in the bottom class. This field does not need to be read from the database. It is read and written dynamically according to the running time of the program.

At present, I have to read it. There is no error or prompt. But I don't know if it's normal that I have to do it. I don't want my program to crash here in the future.

How can I reasonably exclude this field? thx

**Comment by groue** [comment]
Hello @HeebeLee 

You can:

- Learn more about `Codable`. See for example "Choose Properties to Encode and Decode Using Coding Keys" in [Encoding and Decoding Custom Types ](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)

- Do not rely on `Codable` for database encoding, and use the [FetchableRecord](https://github.com/groue/GRDB.swift/blob/master/README.md#fetchablerecord-protocol) and [PersistableRecord](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol) protocols directly.

**Comment by HeebeLee** [comment]
thank you very much. @groue 
Finally, I chose the first method, so that I could have less code.
