### ISSUE TITLE
Not building 

### ISSUE THREAD

**Issue by PratikThakareIos** [groue/GRDB.swift#972]
Please check
<img width="755" alt="Screenshot 2021-05-01 at 8 39 41 PM" src="https://user-images.githubusercontent.com/25743876/116782713-5c5be800-aabd-11eb-95e9-81b3f4bc6660.png">

### What did you do?

Trying to install new rxGRDB or grdb  using pod but project is not building

### What did you expect to happen?

project should building

### What happened instead?

throwing error

### Environment
iOS 
**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)

**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:**

**Comment by groue** [comment]
@PratikThakareIos, GRDB builds well in all supported configuration. Do not expect any support if you do not provide any information that can help somebody reproduce your setup. Also, **when you open an issue in a repository that provides an issue template, fill this template**. This really is basic etiquette.

**Comment by nominalista** [comment]
@groue let me add more context to this issue, as I experienced the same troubles as @PratikThakareIos.

### What did you do?

I try to use GRDB in a xcframework along with CocoaPods. I've received the same error as in original question while trying to build the project with GDRB dependency in the podfile. It occurs that the build fails only with `BUILD_LIBRARY_FOR_DISTRIBUTION` set as `true`. 

I assume that GRDB may not supporting this setting and there are several reason as in case of [gRPC](https://github.com/grpc/grpc-swift/issues/1063), but it would be great if you someone could verify this issue.

### What did you expect to happen?

To be able to build the project with `BUILD_LIBRARY_FOR_DISTRIBUTION` flag or at least find out some explanation for this problem..

### What happened instead?

Received `'let' property 'storage' may not be initialized directly, [...]` compilation error.

### Environment

**GRDB flavor(s):** GRDB.
**GRDB version:** 5.7.4
**Installation method:** CocoaPods
**Xcode version:** 12.5
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.2.3

### Demo Project

Reproduction steps:
- Create Framework project.
- Instantiate podfile with `GRDB` dependency.
- Set `BUILD_LIBRARY_FOR_DISTRIBUTION` to `true`.
- Try to build the project.

**Comment by groue** [comment]
Hello @nominalista. About `BUILD_LIBRARY_FOR_DISTRIBUTION`, please see #964.
