### ISSUE TITLE
Recommended way to update a column to NULL

### ISSUE THREAD

**Issue by chrism1974** [groue/GRDB.swift#98]
Using v0.73.0

I have a model object setup as follows
```
var fieldID:String = NSUUID().UUIDString
var contextID: String? = nil
```

The persistentDictionary method is:
```
tmpDict["fieldID"] = fieldID
tmpDict["contextID"] = contextID
```
The contextID column is defined to allow NULL in the create table statement.

The model attribute contextID is updated to an initial value of "1234" and the database column gets updated correctly.  Later, it is set to nil elsewhere in the code, however, the column is never updated to NULL in the database when the update statement runs.  This seems to be related to the contextID field not in the persistentDictionary because its nil.

What is the recommended way to update a column to NULL?

**Comment by groue** [comment]
Hello @chrism1974 

> This seems to be related to the contextID field not in the persistentDictionary because its nil.

That's the gist of your issue. Put *all* your fields in the persistentDictionary. Even if they are nil.
