### ISSUE TITLE
Create DatabaseValueConvertible from list of values

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDB.swift#985]
Hi,

I want to write my own queries instead of the GRDB query helper. I would expect this to compile:

```
    static func allWithProvidedFirstNames(db: Database, firstName: [String]) throws -> [DbUser] {
        let statement = try db.cachedSelectStatement(sql: """
        select * from user where firstName in (?)
        """)
        let arguments: StatementArguments = try [
            firstName,
        ]

        statement.setUncheckedArguments(arguments)
        let converted: [DbUser] = try Row.fetchAll(statement).map { row -> DbUser in
            DbUser(row: row, startingIndex: 0)
        }
        return converted
    }
```

It fails to compile with the following error:
**Cannot convert value of type '[String]' to expected element type 'DatabaseValueConvertible?'**

How can I create a `DatabaseValueConvertible` from a list of values? I guess I shouldn't adding them really one by one in the StatementArguments, because if I got two `in` queries with two `?`, it is impossible to figure out which values belong to which parameter.

**Comment by groue** [comment]
Hello @Jasperav,

> I want to write my own queries instead of the GRDB query helper.

Fine

> I would expect this to compile:

It doesn't, because GRDB follows closely SQLite. `?` can only be used as a placeholder for **one** value, not one array of values. That's why a `[String]` is not a valid argument value.

When you want to inject arrays into SQL, you must use as many `?` as there are values to inject, and use each string as an argument (instead of the whole array as one argument).

You should get less errors with:

```swift
let firstNamesSQL = databaseQuestionMarks(count: firstNames.count) // "?,?,?,..."
let sql = "select * from user where firstName in (\(firstNamesSQL))"
let statement = try db.cachedSelectStatement(sql: sql)
let arguments = StatementArguments(firstNames)
statement.setUncheckedArguments(arguments)
...
```

Note that the generated SQL will be invalid if the `firstNames` array is empty (`IN ()` is not a valid SQL expression).

A more robust solution will thus be:

```swift
if firstNames.isEmpty {
    return []
}
let firstNamesSQL = databaseQuestionMarks(count: firstNames.count) // "?,?,?,..."
let sql = "select * from user where firstName in (\(firstNamesSQL))"
...
```

**Comment by Jasperav** [comment]
> ? can only be used as a placeholder for one value, not one array of values.

Woops, I didn't know that! I executed the query in my question in CLion and the IDE just made it work with a dynamic sized list, that's why I thought it should work. I will go with the solution you provided, thanks!

**Comment by groue** [comment]
> Woops, I didn't know that!

You're not alone!

That's why [SQL Interpolation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md) addresses this:

```swift
static func allWithProvidedFirstNames(db: Database, firstName: [String]) throws -> [DbUser] {
    let rows = try Row.fetchAll(db, literal: """
        select * from user where firstName in \(firstName)
        """)
    let converted: [DbUser] = rows.map { row -> DbUser in
        DbUser(row: row, startingIndex: 0)
    }
    return converted
}
```

But I forgot to add SQL interpolation support to cached statements :facepalm:

**Comment by Jasperav** [comment]
@groue I made it work in the ORM, but I don't understand something Swift related. Maybe you can help out :). 

At this line, I must force unwrap the result, because the initializer `(_ array: [Any]) `is invoked, but I want to invoke the `init<Sequence: Swift.Sequence>(_ sequence: Sequence) where Sequence.Element: DatabaseValueConvertible` initializer. I pass in an array where the element is DatabaseValueConvertible. You got an idea?

**Comment by groue** [comment]
> You got an idea?

Yes: `[DatabaseValueConvertible]` is not `Swift.Sequence where Sequence.Element: DatabaseValueConvertible`.

It is `Swift.Sequence where Sequence.Element == DatabaseValueConvertible` (notice the `==` instead of `:`).

In other words, `[DatabaseValueConvertible]` is an "array of `DatabaseValueConvertible` existentials", not an "array of some type which conforms to `DatabaseValueConvertible`.

GRDB does not provide support for initializing `StatementArguments` from arrays of existentials.

But it does from arrays of some type which conform, such as `[String]`, `[Int]`, or `[DatabaseValue]`.

So just write:

```
let arguments = StatementArguments(firstName)
```

**Comment by Jasperav** [comment]
@groue I didn't know about the difference between `==` and `:`, cool! Hmm, your fix would work when only 1 parameter is present, but what about multiple? 

I have also a 'complex' query: https://github.com/Jasperav/GRDB-ORM/blob/cd568344329a63f776403a108888b88ef8b10966/GRDBPerformance/GRDBPerformance/Generated/DynamicQueries.swift#L217. It has multiple parameters with multiple types. Do you have any suggestion on how to improve this method?

**Comment by groue** [comment]
> Do you have any suggestion on how to remove the force unwrap in that method?

Yes, use `[DatabaseValue]`, an homogeneous array type that contains database values which can wrap ints, strings, etc:

```swift
var myValues: [DatabaseValue] = []
myValues.append(42.databaseValue)
myValues.append("foo".databaseValue)
myValues.append("bar".databaseValue)
let arguments = StatementArguments(myValues)
```

But personally I'd use [StatementArguments apis](http://groue.github.io/GRDB.swift/docs/5.8/Structs/StatementArguments.html) directly:

```swift
var arguments = StatementArguments()
arguments += [42]
arguments += ["foo", "bar"]
```

**Comment by Jasperav** [comment]
Thanks @groue, I got it working :)

**Comment by groue** [comment]
> But I forgot to add SQL interpolation support to cached statements 🤦

This will ship in next GRDB version. You will be able to write:

```swift
let statement = try db.cachedSelectStatement(literal: """
   select * from user where firstName in \(firstNames)
   """)
```
