### ISSUE TITLE
How to decode an associated record on init(row: Row)

### ISSUE THREAD

**Issue by raphaelcruzeiro** [groue/GRDB.swift#987]
I am currently rewriting the data layer of a large iOS app from Realm to GRDB and it definitely feels like a breath of fresh air after living in the Realm world for so long. Everything has been going really smoothly until I stumbled upon what I assume is an uncommon use case: I have a record that implements `FetchableRecord` and I define my own `init(row: Row)` as some of the fields cannot be automatically mapped to sqlite. This record has a `belongsTo` association with another record and I just can't seem to figure out how to decode this from the row object in the initialiser.  I've searched the documentation and the examples but couldn't find anything. I assume I am missing something obvious here.

How can I implement this initialiser?

```
struct Planet {
    var solarSystem: SolarSystem
    // Other fields
}

extension Planet: FetchableRecord {
     
     init(row: Row) {
         solarSystem = // ???
     }
     
}

```

**Comment by groue** [comment]
Hello @raphaelcruzeiro,

Please show the request.

**Comment by raphaelcruzeiro** [comment]
Hey @groue, thank you for the quick response. I hope you are having a great Sunday!

I plan on using this with the following requests:

```
// association
static let solarSystem = belongsTo(SolarSystem.self)

// request
let request = Planet.including(required: Planet.solarSystem)
```

and

```
// association
static let planets = hasMany(Planet.self)

// request
let request = SolarSystem.joining(required: SolarSystem.planets)
```

**Comment by groue** [comment]
All right. Did you check the [Fetching Values from Associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#fetching-values-from-associations) chapter?

**Comment by raphaelcruzeiro** [comment]
Ah I somehow missed it there! Thanks for pointing me to the right direction @groue! Have a great Sunday!

**Comment by groue** [comment]
All right, @raphaelcruzeiro, happy GRDB! Just open a new issue if you have some specific question!
