### ISSUE TITLE
table.synchronize() cancels the transaction when triggers already exist

### ISSUE THREAD

**Issue by pp5x** [groue/GRDB.swift#988]
Hi @groue

### What did you do?

In a application first launch case (out of migrations cases), I'm initialising the DB schema with:

```.swift
// Initializing table record; if not exists
try db.create(table: "record", ifNotExists: true) { t in
    // ...
}

// Initializing a virtual table to index content from the record table.
try db.create(virtualTable: "content", ifNotExists: true, using: FTS4()) { t in
    t.synchronize(withTable: "record")
    t.column("title")
}
```

### What did you expect to happen?

I want to make sure the DB schema is up to date; without using transactions since if there is breaking change I can still trash the DB files.

### What happened instead?

There are the following cases:

1. The DB file does not exists yet: it creates the tables and the triggers. ✅ 
2. The DB was cleared with drop tables and delete triggers, the DB file may remain but there is no issue. ✅ 
3. The code is called again but we kept the data (no clear), we make sure the schema is up to date, but the triggers created from `t.synchronize` already exists and it makes the whole transaction to fail. 🔴 

Should the `t.synchronize` have a `ifNotExists` parameter? Or even better, it would follow the `ifNotExists` from the table creation.

Or am I initialising the DB the wrong way? How can I figure out the DB state to figure out if a call to `t.synchronize` must be made?

### Current workaround

What I found so far, but it is relying on GRDB's implementation details:

```.swift
let mustCreateTriggers = try !db.triggerExists("__content_bu")
try db.create(virtualTable: "content", ifNotExists: true, using: FTS4()) { t in
      if mustCreateTriggers {
           t.synchronize(withTable: "record")
      }
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v5.8.0
**Installation method:** SPM
**Xcode version:** 12.5
**Swift version:** 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.4

**Comment by groue** [comment]
Hello @pp5x,

Oops: the `ifNotExist` parameter is not passed to [FTS4.database(_:didCreate:using:)](https://github.com/groue/GRDB.swift/blob/v5.8.0/GRDB/FTS/FTS4.swift#L94-L135), which creates the synchronization triggers.

It happens that I use migrations 100% of the time, and this might explain why I did not spot this issue.

> Should the t.synchronize have a `ifNotExists` parameter? Or even better, it would follow the `ifNotExists` from the table creation.

The second option looks reasonable.

Do you feel like contributing a fix?

- The underlying `VirtualTableModule` protocol was not quite designed for it, unfortunately. Yet it is a public protocol, and I'd prefer to avoid breaking changes. This constraint will surely create a little friction in finding a way to let FTS4 do the right thing.
- We'd also have to deal with the same issue in FTS5.

If you can't, I will, of course.

> What I found so far, but it is relying on GRDB's implementation details:

This looks like an efficient workaround 👍. Of course the underscored trigger name looks awful. What about checking for the presence of the `content` table instead? After all, if all released versions of your app create both the table and the triggers in a single transaction, the presence of the first is always equivalent to the presence of the latter:

```swift
if try !db.tableExists("content") {
    try db.create(virtualTable: "content") { t in ... }
}
```

**Comment by pp5x** [comment]
Thank you for your ⚡ blazing fast answer!

I will use the workaround for now.
I made a draft PR #989 to help GRDB support `ifNotExists` from the table. But I may need some help or advices.

**Comment by groue** [comment]
👍 You were quite fast as well! OK, I look at #989 as soon as I can :-)
