### ISSUE TITLE
Crashed at Assert at DataBase.swift

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#992]
### What did you expect to happen?

Find the root cause of the crash issue.

### What happened instead?

When i launch the app. Crash happens occasionally at file: DataBase.swift on line 418, assert method

```swift
    /// This method must be called before database deallocation
    func close() {
        SchedulingWatchdog.preconditionValidQueue(self)
        assert(!isClosed)
        
        ...
    }
```

### Environment

**GRDB flavor(s): GRDB** 
**GRDB.swift (= 4.14.0):**  
**Installation method: CocoaPods** 
**Xcode version: Xcode 12.2**
**Swift version: 5.0**
**Platform(s) running GRDB: iOS** 
**macOS version running Xcode:**

**Comment by glve1027** [comment]
My Project has another sqlite pods. [WCDB](https://github.com/Tencent/wcdb)
Is this the root cause of the crash?

**Comment by groue** [comment]
Hello @glve1027,

The database must only be accessed from within a database access method such as `read` or `write`:

```swift
// CORRECT
let players = try dbQueue.read { db in
    try Player.fetchAll(db)
}
```

It is a programmer error to access the database in any other context:

```swift
// WRONG
let db = try dbQueue.read { db in
    return db
}
let players = try Player.fetchAll(db)

// WRONG
try dbQueue.read { db
    DispatchQueue.main.async {
        let players = try Player.fetchAll(db)
    }
}
```

So make sure your database accesses are only ever performed in the `read` and `write` methods.
