### ISSUE TITLE
SQLite error 5 (SQLITE_BUSY) when using DatabasePool

### ISSUE THREAD

**Issue by raphaelcruzeiro** [groue/GRDB.swift#997]
Hello @groue ,

We have finally released the first version of our app that replaces Realm with GRDB. Everything seems to be going fine except for a few crashes at launch that are popping up on our crashlog:

``` 
SQLite error 5: database is locked - while executing `CREATE TABLE IF NOT EXISTS grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)`
```

This is something that we cannot reproduce ourselves. The database access is done by a single `DatabasePool` that is created an maintained in a singleton object:

```
import Foundation
import GRDB

public final class DatabaseContainer {
    
    public static let instance = DatabaseContainer()
    
    private init() {}
    
    lazy var fileURL: URL = {
        var group = "group.co.bitdreams.Tangerine"
        
        if Bundle.main.bundleIdentifier?.contains("retaildemo") ?? false {
            group = "group.co.bitdreams.Tangerine.retaildemo"
        }
        
        return FileManager.default
                   .containerURL(forSecurityApplicationGroupIdentifier: group)!
                   .appendingPathComponent("database.sqlite")
    }()
    
    lazy var dbPool: DatabaseWriter = {
        #if DEBUG
        if ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] != nil {
            return DatabaseQueue()
        }
        #endif
        
        let path = fileURL.path
        let dbPool = try! DatabasePool(path: path)
        
        return dbPool
    }()
    
    public func runMigrations() {
        try! migrator.migrate(dbPool)
    }
    
    // Used in tests only
    func tearDown() {
        #if DEBUG
        if ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] != nil {
            dbPool = DatabaseQueue()
        }
        #endif
    }
    
}
```

Any idea what we might be doing wrong here?

**Comment by groue** [comment]
Hello @raphaelcruzeiro,

Welcome on board :-)

The error 5 ([SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy)) usually means that a database is used by several multiple connections. One connection acquires an SQLite lock on the database, and the other connections are swiftly kicked off until the lock is released. There are *many* opportunities to get SQLITE_BUSY. GRDB attempts at avoiding most of them, given some rules are followed, and sometimes some require some extra work accomplished.

First, the mother of all rules: do you happen to create *several* instances of DatabasePool for the same database file? If yes, please stop, and make sure you use and reuse the same instance for the whole lifetime of your databases accesses. Most apps deal with a single database, and open *one* connection, when the app boots. It is an anti-pattern to close and open the database for each use. For more rules, see the [Concurrency Guide](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency).

Now, the potential extra work: do you happen to use the same database from *several* processes (the app and its extensions, for example)? If yes, check the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide.

There are other nasty opportunities for SQLITE_BUSY, but we first have to make sure the two previous points are correctly handled.

**Comment by raphaelcruzeiro** [comment]
Hey @groue,

You are always incredibly fast to reply!

I am thinking on the seconds possibility since the framework with my application logic is also used by Siri Intents (though I've only seen the crash on the main app process and I've tested the Intents extensively). I'll take another look at the "Sharing a Database" and see if I can spot something.

**Comment by groue** [comment]
> I'll take another look at the "Sharing a Database" and see if I can spot something.

Yep. If you're a **single process**, then the [How to limit the SQLITE_BUSY error](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md#how-to-limit-the-sqlite_busy-error) should be enough.

**Comment by groue** [comment]
You'll see that sharing a database is *very difficult*. You may be better sharing information with the Siri intents through another mean, such plists or JSON files 😬

**Comment by raphaelcruzeiro** [comment]
@groue I think got it!

As it turns out there is a race condition in my code! I keep forgetting that lazy var initalisations are not thread-safe and right after my singleton is called for the first time (and begins initialising all its properties), it is called again from a background queue and this might be initialising 2 Database Pools. Since it's a hard error to reproduce, I will release a version with a lock added around that initialisation. If I am correct, this error should not pop up on my crash logger for the updated version.

**Comment by groue** [comment]
It looks like you found your issue 🙂

**Comment by raphaelcruzeiro** [comment]
As it turns out, it was not that. I am still investigating and will update this thread with my findings.

**Comment by raphaelcruzeiro** [comment]
@groue After collecting some logs with the Xcode crash logger, I realised that the Siti Intents were not crashing at all! The problem was a race condition when initialising the WidgetExtensions (which make read-only access to the database). I have now changed my WidgetExtension initialisation code to create a read-only DatabasePool as described in the [Sharing Databases](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) document.

Let's see how it goes!

**Comment by groue** [comment]
Thank you, your help is very precious. I do hope the database sharing guide helps, but it will only get better with people who share their experience, just as you do 👍

**Comment by raphaelcruzeiro** [comment]
This issue has disappeared from our crash logs after most of our user base updated to the latest version. So what I did there was :

- Use an app group to save the shared database
- Open the database in read-only mode if possible on the extensions. The only extension I could not do that was the Siri extension but it ended up working fine (probably because it only briefly uses the database when the user issues a Siri command). All other extensions such as Spotlight and Widgets open the database in read-only mode.
- Added a 3 seconds timeout to the DatabasePool configuration. This was just to be safe. Everything seems instantaneous to me.

**Comment by groue** [comment]
Sounds like a success 🙂 Well done, and thanks for sharing!
