### ISSUE TITLE
0xdead10cc when opening database in a watch extension

### ISSUE THREAD

**Issue by jason-gabriele** [groue/GRDB.swift#998]
I'm trying to run GRDB in my watch extension but when the app is backgrounded, the process is immediately terminated. The debugger doesn't output any messages other than `Message from debugger: Terminated due to signal 9` and the backtrace isn't helpful. After installing the syslog profile, I'm able to see the following message in the Console log:

```
error	10:32:02.791285-0700	runningboardd	[application<com.myapp.watchkitapp>:186] suspended with locked system files:
/var/mobile/Containers/Data/PluginKitPlugin/380C85E2-6AE3-49E6-B3CE-3C7767717402/Library/core_sdk.db
error	10:32:02.791369-0700	runningboardd	[application<com.myapp.watchkitapp>:186] locked files not in allowed directories: /var/mobile/Containers/Data/Application/45C739FD-5DFB-4E47-8DB8-7BCBDB6D2FAF/tmp
/var/mobile/Containers/Data/Application/45C739FD-5DFB-4E47-8DB8-7BCBDB6D2FAF
```
(note I changed the app name for privacy)

These are both under the "Errors and Faults" filter though it's unclear if it's complaining about the first db or the application directory. I don't see anything in the code locking those application directory paths. This issue also disappears if I just don't initialize the GRDB database, so I know it has something to do with the db. I also tried using the .documents path and ran into the same message. 

I do see a bunch of reports in Analytics Data that report the `Code 0xdead10cc` which lead me to [this page](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md#how-to-limit-the-0xdead10cc-exception). This page mostly describes working in shared containers, which I'm not doing `(NSSearchPathForDirectoriesInDomains(.libraryDirectory, .userDomainMask, true)[0]` the db lives in the watch extension's lib directory and is not shared with the app). I can see it posting the `Database.suspendNotification` notification but that doesn't seem to prevent the termination.

Wondering if anyone has run into this issue before. 

Should also add that we use the same db code on iOS and have no issues there. 

### Environment

**GRDB flavor(s):** SQLCipher 4.2.0
**GRDB version:** 5.1.0
**Installation method:** CocoaPods
**Xcode version:** 12.5
**Swift version:** 5
**Platform(s) running GRDB:** watchOS 7.5, iOS 14.6
**macOS version running Xcode:** 11.4

Config:

```
var config = Configuration()
config.label = dbName
config.observesSuspensionNotifications = true
config.prepareDatabase { database in
 ...
try database.execute(sql: "PRAGMA cipher_plaintext_header_size = 32;")
try database.usePassphrase(key)
try database.execute(sql: "PRAGMA journal_mode=WAL;")
try database.execute(sql: "PRAGMA auto_vacuum=INCREMENTAL;")
}
```

**Comment by groue** [comment]
Hello @jason-gabriele,

I'm sorry you're facing `0xdead10cc`.

First, I want to blame Apple for removing TN2151 from internet, the source of information about this exception. Booooh 👎 Do not remove documentation from internet, bad Apple! Some remnants of it can be found at https://developer.apple.com/forums/thread/126438

Now, IIRC, 0xdead10cc happens, on iOS, when an application that enters the [suspended state](https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle) (not the background state) while holding a lock on an SQLite database stored in a shared container.

Indeed, such a locked database would be impossible to use from other processes that want to use it (SQLite would refuse), because the suspended app has no opportunity to release this lock. That's why iOS preemptively kills the app and removes the lock. By removing the lock, other processes can access the database. By killing the app, iOS makes sure the app won't proceed using a database that's no longer in the expected state.

This is the story for iOS.

I don't know how it translates on watchOS, but we can try to make hypothesis.

- Your database is not shared. But maybe some *other* database is shared. Does your app have a shared container? Could some third-party put a database in there? What is `/var/mobile/Containers/Data/PluginKitPlugin/380C85E2-6AE3-49E6-B3CE-3C7767717402/Library/core_sdk.db`?
- Maybe watchOS does not need a database to be shared before it triggers 0xdead10cc? Could it happen that your apps holds a lock on your database somehow _at the wrong time_?

    Locks are acquired when you use the database, and released when you stop using the database. Excuse the gross approximation, but it more or less looks like that:
    
    ```swift
    // Database is not locked
    try dbQueue.write { db in
        // Database is locked
    }
    // Database is not locked
    ```

    Consider requesting additional background execution so that your database jobs can complete before the app enters the suspended state (things are different on iOS and watchOS here, and I'll let you figure this out. Maybe [performExpiringActivity(withReason:using:)](https://developer.apple.com/documentation/foundation/processinfo/1617030-performexpiringactivity) can still be useful).
    
    Generally speaking, try to tighten your control of your [watchOS app's life cycle](https://developer.apple.com/documentation/watchkit/wkextensiondelegate/working_with_the_watchos_app_life_cycle), so that you have a clear idea of what is happening and when.

**Comment by groue** [comment]
> First, I want to blame Apple for removing TN2151 from internet, the source of information about this exception

Thanks to @patters in https://twitter.com/patters/status/1408426834161713152, who is much more patient than I am, we now have some links:

- The web archive of TN2151: https://web.archive.org/web/20200620201213/https://developer.apple.com/library/archive/technotes/tn2151/_index.html
- The last doc about 0xdead10cc: https://developer.apple.com/documentation/xcode/understanding-the-exception-types-in-a-crash-report

I'll update the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) documentation with those new links asap (filing this issue with the "needs revisiting" flag).

**Comment by jason-gabriele** [comment]
Thanks for you help!

I was able to fix it by simply commenting out this line:
```
try database.usePassphrase(key)
```

I believe the OS is angry at the tmp file lock. Any idea why SQLCipher is doing that?

Here are some logs around this process check with and without the passphrase:

With setPassphrase:
```
default	12:37:05.419099-0700	runningboardd	[application<com.myapp.watchkitapp>:426] check if suspended process is holding locks
default	12:37:05.430335-0700	runningboardd	[application<com.myapp.watchkitapp>:426] Found locked file lock: /var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/core_sdk.db
default	12:37:05.430536-0700	runningboardd	[application<com.myapp.watchkitapp>:426] Found locked file lock: /var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/app_kit.db
error	12:37:05.430952-0700	runningboardd	[application<com.myapp.watchkitapp>:426] suspended with locked system files:
/var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/core_sdk.db
/var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/app_kit.db
error	12:37:05.431015-0700	runningboardd	[application<com.myapp.watchkitapp>:426] locked files not in allowed directories: /var/mobile/Containers/Data/Application/9530A919-E38E-4461-BFE3-6719729CBD53/tmp
/var/mobile/Containers/Data/Application/9530A919-E38E-4461-BFE3-6719729CBD53
default	12:37:05.431132-0700	runningboardd	[application<com.myapp.watchkitapp>:426] Terminating with context: <RBSTerminateContext| domain:15 code:0xDEAD10CC explanation:[application<com.myapp.watchkitapp>:426] was suspended with locked system files:
/var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/core_sdk.db
/var/mobile/Containers/Data/PluginKitPlugin/181E4179-1F92-4B33-800E-5BB5547C7CBA/Library/app_kit.db
not in allowed directories:
/var/mobile/Containers/Data/Application/9530A919-E38E-4461-BFE3-6719729CBD53/tmp
/var/mobile/Containers/Data/Application/9530A919-E38E-4461-BFE3-6719729CBD53 reportType:CrashLog maxTerminationResistance:Interactive>
default	12:37:05.431849-0700	runningboardd	[application<com.myapp.watchkitapp>:426] terminate_with_reason() success
default	12:37:05.432075-0700	Carousel	[application<com.myapp.watchkitapp>:426] Setting process task state to: Suspended
```

Without:
```
default	12:57:17.379089-0700	runningboardd	Calculated state for application<com.myapp.watchkitapp>: running-suspended (role: None)
default	12:57:17.379134-0700	runningboardd	[application<com.myapp.watchkitapp>:432] Suspending task.
error	12:57:17.379259-0700	kernel	Sandbox: runningboardd(73) deny(1) file-read-metadata /dev/ttys000
default	12:57:17.379369-0700	runningboardd	[application<com.myapp.watchkitapp>:432] Shutdown sockets (ALL)
default	12:57:17.379499-0700	runningboardd	[application<com.myapp.watchkitapp>:432] Set darwin role to: None
default	12:57:17.379592-0700	runningboardd	[application<com.myapp.watchkitapp>:432] check if suspended process is holding locks
error	12:57:17.379640-0700	runningboardd	[application<com.myapp.watchkitapp>:432] proc_pidfdinfo failed for fd 1 with errno 1
error	12:57:17.379684-0700	runningboardd	[application<com.myapp.watchkitapp>:432] proc_pidfdinfo failed for fd 2 with errno 1
default	12:57:17.384387-0700	Carousel	[application<com.myapp.watchkitapp>:432] Setting process task state to: Suspended
```

**Comment by groue** [comment]
All right, I'll close the issue since you were able to fix it. Please reopen if you have some new information.

**Comment by jason-gabriele** [comment]
We seem to have fixed this issue by using both the `"PRAGMA cipher_plaintext_header_size = 32"` and also including the cipher_salt with the passphrase. We used this [documentation](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size) to do that. This allows the OS to look inside the DB and see it's in WAL mode. It seems to relax its checks one it does that. 

There's more info in [this thread](https://github.com/sqlcipher/sqlcipher/issues/255).

We didn't need the `observesSuspensionNotifications` feature.

**Comment by groue** [comment]
So you think this chapter should be updated? https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md#how-to-limit-the-0xdead10cc-exception

It mentions both `PRAGMA cipher_plaintext_header_size = 32` and the issue 255 of SQLCipher, but does not talk about the salt. I would appreciate if you would share some sample code so that other users can read an accurate GRDB doc!

**Comment by jason-gabriele** [comment]
I think you should add the bit about cipher_salt. There are [several ways to do it](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size). We ended up just using a raw key and appending the cipher to it. 

```
let key = "x'\(key)\(cipherSalt)'"
...
try database.usePassphrase(key)
try database.execute(sql: "PRAGMA cipher_plaintext_header_size=32;")
try database.execute(sql: "PRAGMA journal_mode=WAL;")
...
```

That way you can just store the salt along with the key the way we were doing before.

**Comment by groue** [comment]
Thank you @jason-gabriele. The documentation has been updated in 3de6f5142745d7254c2c439b150d8c002e43d439.
